Работа с табличными данными

In [574]:
import pandas as pd
import numpy as np
import copy
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch
from dotenv import load_dotenv
import wandb
import os
import logging
import time
import torch.nn as nn
import random
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import *
import pickle

In [575]:
df = pd.read_csv('dataset/train.csv', sep="|")
df

,trustLevel,totalScanTimeInSeconds,grandTotal,lineItemVoids,scansWithoutRegistration,quantityModifications,scannedLineItemsPerSecond,valuePerSecond,lineItemVoidsPerPosition,fraud
0,5,1054,54.70,7,0,3,0.027514,0.051898,0.241379,0
1,3,108,27.36,5,2,4,0.129630,0.253333,0.357143,0
2,3,1516,62.16,3,10,5,0.008575,0.041003,0.230769,0
3,6,1791,92.31,8,4,4,0.016192,0.051541,0.275862,0
4,5,430,81.53,3,7,2,0.062791,0.189605,0.111111,0
...,...,...,...,...,...,...,...,...,...,...
1874,1,321,76.03,8,7,2,0.071651,0.236854,0.347826,0
1875,1,397,41.89,5,5,0,0.065491,0.105516,0.192308,1
1876,4,316,41.83,5,8,1,0.094937,0.132373,0.166667,0
1877,2,685,62.68,1,6,2,0.035036,0.091504,0.041667,0
1878,4,1140,38.03,2,2,3,0.016667,0.033360,0.105263,0

In [576]:
df.dtypes

trustLevel                     int64
totalScanTimeInSeconds         int64
grandTotal                   float64
lineItemVoids                  int64
scansWithoutRegistration       int64
quantityModifications          int64
scannedLineItemsPerSecond    float64
valuePerSecond               float64
lineItemVoidsPerPosition     float64
fraud                          int64
dtype: object

In [577]:
df.isna().sum()

trustLevel                   0
totalScanTimeInSeconds       0
grandTotal                   0
lineItemVoids                0
scansWithoutRegistration     0
quantityModifications        0
scannedLineItemsPerSecond    0
valuePerSecond               0
lineItemVoidsPerPosition     0
fraud                        0
dtype: int64

In [578]:
df.fraud.value_counts()

fraud
0    1775
1     104
Name: count, dtype: int64

In [579]:
y = df["fraud"]
X = df.drop(columns=["fraud"])

In [580]:
df.describe()

,trustLevel,totalScanTimeInSeconds,grandTotal,lineItemVoids,scansWithoutRegistration,quantityModifications,scannedLineItemsPerSecond,valuePerSecond,lineItemVoidsPerPosition,fraud
count,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000
mean,3.401809,932.153273,50.864492,5.469931,4.904204,2.525279,0.058138,0.201746,0.745404,0.055349
std,1.709404,530.144640,28.940202,3.451169,3.139697,1.695472,0.278512,1.242135,1.327241,0.228720
min,1.000000,2.000000,0.010000,0.000000,0.000000,0.000000,0.000548,0.000007,0.000000,0.000000
25%,2.000000,474.500000,25.965000,2.000000,2.000000,1.000000,0.008384,0.027787,0.160000,0.000000
50%,3.000000,932.000000,51.210000,5.000000,5.000000,3.000000,0.016317,0.054498,0.350000,0.000000
75%,5.000000,1397.000000,77.285000,8.000000,8.000000,4.000000,0.032594,0.107313,0.666667,0.000000
max,6.000000,1831.000000,99.960000,11.000000,10.000000,5.000000,6.666667,37.870000,11.000000,1.000000

## Предобработка данных

In [581]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [582]:
X_train.shape

(1503, 9)

In [583]:
X_val.shape

(376, 9)

In [584]:
X_test = pd.read_csv("dataset/test.csv", sep="|")
X_test

,trustLevel,totalScanTimeInSeconds,grandTotal,lineItemVoids,scansWithoutRegistration,quantityModifications,scannedLineItemsPerSecond,valuePerSecond,lineItemVoidsPerPosition
0,4,467,88.48,4,8,4,0.014989,0.189465,0.571429
1,3,1004,58.99,7,6,1,0.026892,0.058755,0.259259
2,1,162,14.00,4,5,4,0.006173,0.086420,4.000000
3,5,532,84.79,9,3,4,0.026316,0.159380,0.642857
4,5,890,42.16,4,0,0,0.021348,0.047371,0.210526
...,...,...,...,...,...,...,...,...,...
498116,4,783,59.10,2,2,0,0.012771,0.075479,0.200000
498117,1,278,98.90,9,5,4,0.050360,0.355755,0.642857
498118,3,300,5.41,6,6,4,0.030000,0.018033,0.666667
498119,2,1524,33.97,2,5,3,0.005906,0.022290,0.222222
498120,3,1456,56.97,11,7,2,0.019231,0.039128,0.392857

In [585]:
y_test = pd.read_csv("dataset/DMC-2019-realclass.csv", sep="|")["fraud"]
y_test.value_counts()

fraud
0    474394
1     23727
Name: count, dtype: int64

In [586]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [587]:
X_train = torch.tensor(X_train, dtype=torch.float32)
X_val = torch.tensor(X_val, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)

In [588]:
y_train = torch.tensor(y_train.values, dtype=torch.float32).reshape(-1, 1)
y_val = torch.tensor(y_val.values, dtype=torch.float32).reshape(-1, 1)
y_test = torch.tensor(y_test.values, dtype=torch.float32).reshape(-1, 1)

In [589]:
BATCH_SIZE = 64

In [590]:
train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(TensorDataset(X_val, y_val), batch_size=256)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=1024)

вес для редкого класса, чтобы модель его не пропускала

In [591]:
n_pos = (y_train == 1).sum()
n_neg = (y_train == 0).sum()

In [592]:
pos_weight = n_neg / n_pos
pos_weight

tensor(17.1084)

## Подготовка

In [593]:
load_dotenv()

WANDB_API_KEY = os.getenv("WANDB_API_KEY")
WANDB_PROJECT = os.getenv("WANDB_PROJECT", "gp5")
WANDB_ENTITY = os.getenv("WANDB_ENTITY")

In [594]:
wandb.login(key=WANDB_API_KEY)

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.

False

In [595]:
def stop_logging():
    logger = logging.getLogger()
    for handler in logger.handlers:
        handler.flush()
        handler.close()
        logger.removeHandler(handler)

def new_log_file():
    stop_logging()
    timestamp = str(time.time()).replace('.', '_')
    log_file = f'part_2_{timestamp}.log'
    logging.basicConfig(
        filename=log_file,
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        force=True
    )
    logging.info("Начал логгировать новый запуск")
    return log_file

In [629]:
def evaluate_model(model, X, y, threshold=0.5, name="dataset"):
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED) 

    model.eval()

    with torch.no_grad():
        logits = model(X)
        probs = torch.sigmoid(logits)

    y_true = y.numpy().ravel()
    y_prob = probs.numpy().ravel()
    y_pred = (y_prob > threshold).astype(int)

    roc_auc = roc_auc_score(y_true, y_prob)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f05 = fbeta_score(y_true, y_pred, beta=0.5)

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    profit = tp * 5 - fp * 25 - fn * 5

    print(name)
    print("ROC-AUC:", round(roc_auc, 4))
    print("Precision:", round(precision, 4))
    print("Recall:", round(recall, 4))
    print("F0.5-score:", round(f05, 4))
    print("Profit:", profit)
    print()

    return {
        "dataset": name,
        "threshold": threshold,
        "roc_auc": roc_auc,
        "precision": precision,
        "recall": recall,
        "f05": f05,
        "profit": profit
    }

In [630]:
def train_model(model, train_loader, X_valid, y_valid, loss_fn, optimizer, 
    epochs=30, threshold=0.5,model_name="model"):
    
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED) 

    best_metric = -10**9
    best_epoch = 0
    best_state = None

    history = []
    logging.info(f"Начали обучение {model_name}")

    for epoch in range(1, epochs + 1):
        model.train()
        epoch_loss = 0

        for xb, yb in train_loader:
            optimizer.zero_grad()
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        epoch_loss /= len(train_loader)

        valid_metrics = evaluate_model(model, X_valid, y_valid, threshold=threshold,
            name=f"{model_name} | valid epoch {epoch}")
            
        current_metric = valid_metrics["roc_auc"]
        
        if current_metric > best_metric:
            best_metric = current_metric
            best_epoch = epoch
            best_state = copy.deepcopy(model.state_dict())

        print(f"Эпоха {epoch} | " f"Train Loss: {epoch_loss:.4f} | " 
        f"Val ROC-AUC: {valid_metrics['roc_auc']:.4f} | " f"Val Profit: {valid_metrics['profit']}")
        
        
        logging.info(
            f"Эпоха {epoch} | "
            f"Train Loss: {epoch_loss:.4f} | "
            f"Val ROC-AUC: {valid_metrics['roc_auc']:.4f} | "
            f"Val Profit: {valid_metrics['profit']}"
        )

        wandb.log({
             f"{model_name}/train_loss": epoch_loss,
             f"{model_name}/valid_profit": valid_metrics["profit"],
             f"{model_name}/valid_roc_auc": valid_metrics["roc_auc"],
             f"{model_name}/valid_precision": valid_metrics["precision"],
             f"{model_name}/valid_recall": valid_metrics["recall"],
             f"{model_name}/valid_f05": valid_metrics["f05"],
         })

    model.load_state_dict(best_state)

    print()
    print(f"Лучшая эпоха для {model_name}: {best_epoch}")
    print(f"Лучший ROC-AUC: {best_metric}")
    logging.info("Закончили обучение")
    logging.info(f"Лучшая эпоха для {model_name}: {best_epoch}")
    logging.info(f"Лучший ROC-AUC: {best_metric}")

    return model

In [627]:
def save_results(model, name, log_file, run):
    train_metrics = evaluate_model(model, X_train, y_train, threshold=0.5, name="Train")
    test_metrics = evaluate_model(model, X_test, y_test, threshold=0.5, name="Test")
    pickle.dump(model.state_dict(), open(f"models/{name}.pkl", 'wb'))
    logging.info("Сохранили веса модели в папку models")

    metric_keys = list(train_metrics.keys())

    table = wandb.Table(columns=metric_keys)
    table.add_data(*[train_metrics[i] for i in metric_keys])
    table.add_data(*[test_metrics[i] for i in metric_keys])
    wandb.log({'results': table})
    artifact = wandb.Artifact(name=name, type="model", description=f"Тест логгирования модели: {name}")

    artifact.add_file(f"models/{name}.pkl")
    artifact.add_file(log_file)
    run.log_artifact(artifact)

## model_1_baseline

In [635]:
EPOCHS = 30
LR = 0.01
SEED = 42


random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 

model_1 = nn.Sequential(
    nn.Linear(9, 16),
    nn.ReLU(),
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_1.parameters(), lr=LR)

config = {
    "model": "MLP",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_1)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_1_baseline", config=config)
log_file = new_log_file()

model_1 = train_model(
    model=model_1,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_1_baseline"
)

save_results(model_1, "model_1_baseline", log_file, run)


run.finish()

model_1_baseline | valid epoch 1
ROC-AUC: 0.9411
Precision: 0.25
Recall: 0.0952
F0.5-score: 0.1887
Profit: -235

Эпоха 1 | Train Loss: 1.2482 | Val ROC-AUC: 0.9411 | Val Profit: -235
model_1_baseline | valid epoch 2
ROC-AUC: 0.9553
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 2 | Train Loss: 0.7541 | Val ROC-AUC: 0.9553 | Val Profit: -1770
model_1_baseline | valid epoch 3
ROC-AUC: 0.972
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 3 | Train Loss: 0.4640 | Val ROC-AUC: 0.9720 | Val Profit: -1420
model_1_baseline | valid epoch 4
ROC-AUC: 0.9728
Precision: 0.2625
Recall: 1.0
F0.5-score: 0.3079
Profit: -1370

Эпоха 4 | Train Loss: 0.3839 | Val ROC-AUC: 0.9728 | Val Profit: -1370
model_1_baseline | valid epoch 5
ROC-AUC: 0.972
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 5 | Train Loss: 0.3468 | Val ROC-AUC: 0.9720 | Val Profit: -1270
model_1_baseline | valid epoch 6
ROC-AUC: 0.9741
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 6 | Train Loss: 0.3189 | Val ROC-AUC: 0.9741 | Val Profit: -1220
model_1_baseline | valid epoch 7
ROC-AUC: 0.9738
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 7 | Train Loss: 0.2919 | Val ROC-AUC: 0.9738 | Val Profit: -1070
model_1_baseline | valid epoch 8
ROC-AUC: 0.9744
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 8 | Train Loss: 0.2605 | Val ROC-AUC: 0.9744 | Val Profit: -970
model_1_baseline | valid epoch 9
ROC-AUC: 0.9764
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 9 | Train Loss: 0.2485 | Val ROC-AUC: 0.9764 | Val Profit: -945
model_1_baseline | valid epoch 10
ROC-AUC: 0.9768
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 10 | Train Loss: 0.2287 | Val ROC-AUC: 0.9768 | Val Profit: -820
model_1_baseline | valid epoch 11
ROC-AUC: 0.9777
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 11 | Train Loss: 0.2115 | Val ROC-AUC: 0.9777 | Val Profit: -695
model_1_baseline | valid epoch 12
ROC-AUC: 0.9763
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 12 | Train Loss: 0.1939 | Val ROC-AUC: 0.9763 | Val Profit: -720
model_1_baseline | valid epoch 13
ROC-AUC: 0.9799
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 13 | Train Loss: 0.1913 | Val ROC-AUC: 0.9799 | Val Profit: -620
model_1_baseline | valid epoch 14
ROC-AUC: 0.9788
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 14 | Train Loss: 0.1819 | Val ROC-AUC: 0.9788 | Val Profit: -695
model_1_baseline | valid epoch 15
ROC-AUC: 0.9842
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 15 | Train Loss: 0.1805 | Val ROC-AUC: 0.9842 | Val Profit: -470
model_1_baseline | valid epoch 16
ROC-AUC: 0.9812
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 16 | Train Loss: 0.1615 | Val ROC-AUC: 0.9812 | Val Profit: -645
model_1_baseline | valid epoch 17
ROC-AUC: 0.9832
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 17 | Train Loss: 0.1667 | Val ROC-AUC: 0.9832 | Val Profit: -495
model_1_baseline | valid epoch 18
ROC-AUC: 0.9826
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 18 | Train Loss: 0.1447 | Val ROC-AUC: 0.9826 | Val Profit: -505
model_1_baseline | valid epoch 19
ROC-AUC: 0.9855
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 19 | Train Loss: 0.1497 | Val ROC-AUC: 0.9855 | Val Profit: -495
model_1_baseline | valid epoch 20
ROC-AUC: 0.9801
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 20 | Train Loss: 0.1397 | Val ROC-AUC: 0.9801 | Val Profit: -440
model_1_baseline | valid epoch 21
ROC-AUC: 0.9811
Precision: 0.4884
Recall: 1.0
F0.5-score: 0.544
Profit: -445

Эпоха 21 | Train Loss: 0.1537 | Val ROC-AUC: 0.9811 | Val Profit: -445
model_1_baseline | valid epoch 22
ROC-AUC: 0.9867
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 22 | Train Loss: 0.1514 | Val ROC-AUC: 0.9867 | Val Profit: -330
model_1_baseline | valid epoch 23
ROC-AUC: 0.9832
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 23 | Train Loss: 0.1205 | Val ROC-AUC: 0.9832 | Val Profit: -480
model_1_baseline | valid epoch 24
ROC-AUC: 0.986
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 24 | Train Loss: 0.1452 | Val ROC-AUC: 0.9860 | Val Profit: -570
model_1_baseline | valid epoch 25
ROC-AUC: 0.9867
Precision: 0.5385
Recall: 1.0
F0.5-score: 0.5932
Profit: -345

Эпоха 25 | Train Loss: 0.1412 | Val ROC-AUC: 0.9867 | Val Profit: -345
model_1_baseline | valid epoch 26
ROC-AUC: 0.9854
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 26 | Train Loss: 0.1226 | Val ROC-AUC: 0.9854 | Val Profit: -380
model_1_baseline | valid epoch 27
ROC-AUC: 0.9756
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 27 | Train Loss: 0.1269 | Val ROC-AUC: 0.9756 | Val Profit: -490
model_1_baseline | valid epoch 28
ROC-AUC: 0.9783
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 28 | Train Loss: 0.1541 | Val ROC-AUC: 0.9783 | Val Profit: -580
model_1_baseline | valid epoch 29
ROC-AUC: 0.9831
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

Эпоха 29 | Train Loss: 0.1602 | Val ROC-AUC: 0.9831 | Val Profit: -315
model_1_baseline | valid epoch 30
ROC-AUC: 0.9885
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 30 | Train Loss: 0.1275 | Val ROC-AUC: 0.9885 | Val Profit: -570

Лучшая эпоха для model_1_baseline: 30
Лучший ROC-AUC: 0.9884641180415827
Train
ROC-AUC: 0.9949
Precision: 0.4611
Recall: 1.0
F0.5-score: 0.5168
Profit: -2010

Test
ROC-AUC: 0.9861
Precision: 0.4143
Recall: 0.9676
F0.5-score: 0.4678
Profit: -700395

In [636]:
train_metrics = evaluate_model(model_1, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_1, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9949
Precision: 0.4611
Recall: 1.0
F0.5-score: 0.5168
Profit: -2010

Test
ROC-AUC: 0.9861
Precision: 0.4143
Recall: 0.9676
F0.5-score: 0.4678
Profit: -700395

Неплохо, но видно сильное переобучение! Можно например, добавить регуляризацию, но так как это бейзлайн, то оставим так, а регуляризацию сделаем попозже

### Попробуем подобрать порог

In [ ]:
with torch.no_grad():
    val_prob = torch.sigmoid(model(X_val)).numpy()

val_true = y_val.numpy()

In [ ]:
from sklearn.metrics import precision_recall_curve

target_recall = 0.90

prec, rec, thr = precision_recall_curve(val_true, val_prob)
best_threshold = thr[rec[:-1] >= target_recall].max()
logging.info(f"Подобрали порог {best_threshold}")
wandb.log({"best_threshold": best_threshold})
best_threshold

In [ ]:
y_pred = (y_prob > best_threshold).astype(int)

In [ ]:
pre_at_score = precision_score(y_true, y_pred)
#logging.info(f"На тесте Precision: {pre_at_score}")
pre_at_score

In [ ]:
rec_at_score = recall_score(y_true, y_pred)
#logging.info(f"На тесте Recall: {rec_at_score}")
rec_at_score

In [ ]:
import matplotlib.pyplot as plt

plt.plot(rec, prec)
plt.xlabel("recall")
plt.ylabel("precision")
plt.title("PR кривая")
plt.show()

In [ ]:
#import pickle

#pickle.dump(model.state_dict(), open("models/model_fraud_1.pkl", 'wb'))
#logging.info("Сохранили веса модели в папку models")

In [ ]:
#results = wandb.Table(columns=['model', 'test/roc_auc', 'test/precision', 'test/recall', 'test/recall_new_threshold', 'test/precision_new_threshold'])
#results.add_data("nn_baseline", auc_score, pre_score, rec_score, rec_at_score, pre_at_score)
#wandb.log({"results": results})

In [ ]:
#artifact = wandb.Artifact(name="model_fraud_1", type="model", description="Тест логгирования модели MLP")

#artifact.add_file("models/model_fraud_1.pkl")
#artifact.add_file(log_file)
#run.log_artifact(artifact)

In [ ]:
#run.finish()

## model_2_dop_sloi

In [638]:
EPOCHS = 30
LR = 0.01

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_2 = nn.Sequential(
    nn.Linear(9, 32),
    nn.ReLU(),

    nn.Linear(32, 16),
    nn.ReLU(),

    nn.Linear(16, 8),
    nn.ReLU(),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_2.parameters(), lr=LR)

config = {
    "model": "MLP_added_layer",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_2)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_2_added_layers", config=config)
log_file = new_log_file()

model_2 = train_model(
    model=model_2,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_2_dop_sloi"
)

save_results(model_2, "model_2", log_file, run)

run.finish()

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.9311
Precision: 0.3051
Recall: 0.8571
F0.5-score: 0.3502
Profit: -950

Эпоха 1 | Train Loss: 1.1825 | Val ROC-AUC: 0.9311 | Val Profit: -950
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9552
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 2 | Train Loss: 0.6270 | Val ROC-AUC: 0.9552 | Val Profit: -1120
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9502
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 3 | Train Loss: 0.4225 | Val ROC-AUC: 0.9502 | Val Profit: -1470
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9642
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 4 | Train Loss: 0.4105 | Val ROC-AUC: 0.9642 | Val Profit: -1155
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.9641
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 5 | Train Loss: 0.3026 | Val ROC-AUC: 0.9641 | Val Profit: -1020
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.9599
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 6 | Train Loss: 0.2684 | Val ROC-AUC: 0.9599 | Val Profit: -1105
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.9604
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 7 | Train Loss: 0.2346 | Val ROC-AUC: 0.9604 | Val Profit: -855
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9655
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 8 | Train Loss: 0.2385 | Val ROC-AUC: 0.9655 | Val Profit: -780
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9616
Precision: 0.4
Recall: 0.7619
F0.5-score: 0.442
Profit: -545

Эпоха 9 | Train Loss: 0.2673 | Val ROC-AUC: 0.9616 | Val Profit: -545
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.967
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 10 | Train Loss: 0.2220 | Val ROC-AUC: 0.9670 | Val Profit: -795
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.9667
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 11 | Train Loss: 0.2146 | Val ROC-AUC: 0.9667 | Val Profit: -690
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.9722
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 12 | Train Loss: 0.2322 | Val ROC-AUC: 0.9722 | Val Profit: -745
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9764
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 13 | Train Loss: 0.2764 | Val ROC-AUC: 0.9764 | Val Profit: -555
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9741
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 14 | Train Loss: 0.2126 | Val ROC-AUC: 0.9741 | Val Profit: -500
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9716
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 15 | Train Loss: 0.1698 | Val ROC-AUC: 0.9716 | Val Profit: -540
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9777
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 16 | Train Loss: 0.1524 | Val ROC-AUC: 0.9777 | Val Profit: -340
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9768
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 17 | Train Loss: 0.1288 | Val ROC-AUC: 0.9768 | Val Profit: -365
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9805
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 18 | Train Loss: 0.1281 | Val ROC-AUC: 0.9805 | Val Profit: -290
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9764
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 19 | Train Loss: 0.1899 | Val ROC-AUC: 0.9764 | Val Profit: -275
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9734
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 20 | Train Loss: 0.1419 | Val ROC-AUC: 0.9734 | Val Profit: -720
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9759
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 21 | Train Loss: 0.1684 | Val ROC-AUC: 0.9759 | Val Profit: -360
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9673
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 22 | Train Loss: 0.3742 | Val ROC-AUC: 0.9673 | Val Profit: -1020
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9745
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 23 | Train Loss: 0.2413 | Val ROC-AUC: 0.9745 | Val Profit: -620
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.984
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 24 | Train Loss: 0.1695 | Val ROC-AUC: 0.9840 | Val Profit: -570
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9865
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 25 | Train Loss: 0.1293 | Val ROC-AUC: 0.9865 | Val Profit: -265
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9885
Precision: 0.6667
Recall: 0.8571
F0.5-score: 0.6977
Profit: -150

Эпоха 26 | Train Loss: 0.0959 | Val ROC-AUC: 0.9885 | Val Profit: -150
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.987
Precision: 0.4884
Recall: 1.0
F0.5-score: 0.544
Profit: -445

Эпоха 27 | Train Loss: 0.1140 | Val ROC-AUC: 0.9870 | Val Profit: -445
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9852
Precision: 0.6667
Recall: 0.8571
F0.5-score: 0.6977
Profit: -150

Эпоха 28 | Train Loss: 0.1468 | Val ROC-AUC: 0.9852 | Val Profit: -150
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9824
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 29 | Train Loss: 0.2468 | Val ROC-AUC: 0.9824 | Val Profit: -300
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.9866
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 30 | Train Loss: 0.1535 | Val ROC-AUC: 0.9866 | Val Profit: -290

Лучшая эпоха для model_2_dop_sloi: 26
Лучший ROC-AUC: 0.9884641180415827
Train
ROC-AUC: 0.9974
Precision: 0.7345
Recall: 1.0
F0.5-score: 0.7757
Profit: -335

Test
ROC-AUC: 0.9854
Precision: 0.5884
Recall: 0.8528
F0.5-score: 0.6273
Profit: -270185

In [639]:
train_metrics = evaluate_model(model_2, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_2, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9974
Precision: 0.7345
Recall: 1.0
F0.5-score: 0.7757
Profit: -335

Test
ROC-AUC: 0.9854
Precision: 0.5884
Recall: 0.8528
F0.5-score: 0.6273
Profit: -270185

Да, добавив всего 1 доп слой, видно, как сильно улучшилась наша метрика Profit. С -700к поднялась до -270к

## model_3_bolshe_neyronov

In [644]:
EPOCHS = 30
LR = 0.01

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 

model_3 = nn.Sequential(
    nn.Linear(9, 32),
    nn.ReLU(),
    nn.Linear(32, 64),
    nn.ReLU(),
    nn.Linear(64, 1),
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_3.parameters(), lr=LR)

config = {
    "model": "MLP_added_neurons",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_3)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_3_more_neurons", config=config)
log_file = new_log_file()

model_3 = train_model(
    model=model_3,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_3_bolshe_neyronov"
)


save_results(model_3, "model_3", log_file, run)

run.finish()

model_3_bolshe_neyronov | valid epoch 1
ROC-AUC: 0.9586
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 1 | Train Loss: 0.9062 | Val ROC-AUC: 0.9586 | Val Profit: -1520
model_3_bolshe_neyronov | valid epoch 2
ROC-AUC: 0.9599
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 2 | Train Loss: 0.4444 | Val ROC-AUC: 0.9599 | Val Profit: -1095
model_3_bolshe_neyronov | valid epoch 3
ROC-AUC: 0.9612
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 3 | Train Loss: 0.3691 | Val ROC-AUC: 0.9612 | Val Profit: -930
model_3_bolshe_neyronov | valid epoch 4
ROC-AUC: 0.9679
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 4 | Train Loss: 0.3041 | Val ROC-AUC: 0.9679 | Val Profit: -680
model_3_bolshe_neyronov | valid epoch 5
ROC-AUC: 0.9658
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 5 | Train Loss: 0.2697 | Val ROC-AUC: 0.9658 | Val Profit: -755
model_3_bolshe_neyronov | valid epoch 6
ROC-AUC: 0.969
Precision: 0.3333
Recall: 0.9524
F0.5-score: 0.3831
Profit: -905

Эпоха 6 | Train Loss: 0.2454 | Val ROC-AUC: 0.9690 | Val Profit: -905
model_3_bolshe_neyronov | valid epoch 7
ROC-AUC: 0.9714
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 7 | Train Loss: 0.2276 | Val ROC-AUC: 0.9714 | Val Profit: -425
model_3_bolshe_neyronov | valid epoch 8
ROC-AUC: 0.974
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 8 | Train Loss: 0.2453 | Val ROC-AUC: 0.9740 | Val Profit: -605
model_3_bolshe_neyronov | valid epoch 9
ROC-AUC: 0.9716
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 9 | Train Loss: 0.1928 | Val ROC-AUC: 0.9716 | Val Profit: -540
model_3_bolshe_neyronov | valid epoch 10
ROC-AUC: 0.973
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 10 | Train Loss: 0.1748 | Val ROC-AUC: 0.9730 | Val Profit: -720
model_3_bolshe_neyronov | valid epoch 11
ROC-AUC: 0.974
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 11 | Train Loss: 0.2044 | Val ROC-AUC: 0.9740 | Val Profit: -705
model_3_bolshe_neyronov | valid epoch 12
ROC-AUC: 0.967
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 12 | Train Loss: 0.1910 | Val ROC-AUC: 0.9670 | Val Profit: -490
model_3_bolshe_neyronov | valid epoch 13
ROC-AUC: 0.9714
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 13 | Train Loss: 0.1986 | Val ROC-AUC: 0.9714 | Val Profit: -720
model_3_bolshe_neyronov | valid epoch 14
ROC-AUC: 0.9687
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 14 | Train Loss: 0.2118 | Val ROC-AUC: 0.9687 | Val Profit: -490
model_3_bolshe_neyronov | valid epoch 15
ROC-AUC: 0.9751
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 15 | Train Loss: 0.1885 | Val ROC-AUC: 0.9751 | Val Profit: -480
model_3_bolshe_neyronov | valid epoch 16
ROC-AUC: 0.978
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 16 | Train Loss: 0.1764 | Val ROC-AUC: 0.9780 | Val Profit: -500
model_3_bolshe_neyronov | valid epoch 17
ROC-AUC: 0.9805
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 17 | Train Loss: 0.1284 | Val ROC-AUC: 0.9805 | Val Profit: -325
model_3_bolshe_neyronov | valid epoch 18
ROC-AUC: 0.9789
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 18 | Train Loss: 0.1074 | Val ROC-AUC: 0.9789 | Val Profit: -355
model_3_bolshe_neyronov | valid epoch 19
ROC-AUC: 0.9799
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 19 | Train Loss: 0.0962 | Val ROC-AUC: 0.9799 | Val Profit: -280
model_3_bolshe_neyronov | valid epoch 20
ROC-AUC: 0.98
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 20 | Train Loss: 0.0833 | Val ROC-AUC: 0.9800 | Val Profit: -290
model_3_bolshe_neyronov | valid epoch 21
ROC-AUC: 0.9783
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 21 | Train Loss: 0.0919 | Val ROC-AUC: 0.9783 | Val Profit: -355
model_3_bolshe_neyronov | valid epoch 22
ROC-AUC: 0.9785
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 22 | Train Loss: 0.0859 | Val ROC-AUC: 0.9785 | Val Profit: -245
model_3_bolshe_neyronov | valid epoch 23
ROC-AUC: 0.9832
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

Эпоха 23 | Train Loss: 0.1034 | Val ROC-AUC: 0.9832 | Val Profit: -205
model_3_bolshe_neyronov | valid epoch 24
ROC-AUC: 0.9759
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 24 | Train Loss: 0.1897 | Val ROC-AUC: 0.9759 | Val Profit: -655
model_3_bolshe_neyronov | valid epoch 25
ROC-AUC: 0.9765
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 25 | Train Loss: 0.2923 | Val ROC-AUC: 0.9765 | Val Profit: -580
model_3_bolshe_neyronov | valid epoch 26
ROC-AUC: 0.9851
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 26 | Train Loss: 0.1758 | Val ROC-AUC: 0.9851 | Val Profit: -330
model_3_bolshe_neyronov | valid epoch 27
ROC-AUC: 0.984
Precision: 0.5882
Recall: 0.9524
F0.5-score: 0.6369
Profit: -255

Эпоха 27 | Train Loss: 0.1093 | Val ROC-AUC: 0.9840 | Val Profit: -255
model_3_bolshe_neyronov | valid epoch 28
ROC-AUC: 0.9878
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

Эпоха 28 | Train Loss: 0.0932 | Val ROC-AUC: 0.9878 | Val Profit: -205
model_3_bolshe_neyronov | valid epoch 29
ROC-AUC: 0.9851
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 29 | Train Loss: 0.0811 | Val ROC-AUC: 0.9851 | Val Profit: -330
model_3_bolshe_neyronov | valid epoch 30
ROC-AUC: 0.9854
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

Эпоха 30 | Train Loss: 0.0716 | Val ROC-AUC: 0.9854 | Val Profit: -205

Лучшая эпоха для model_3_bolshe_neyronov: 28
Лучший ROC-AUC: 0.9877934272300469
Train
ROC-AUC: 0.9981
Precision: 0.6803
Recall: 1.0
F0.5-score: 0.7268
Profit: -560

Test
ROC-AUC: 0.985
Precision: 0.5541
Recall: 0.8915
F0.5-score: 0.5995
Profit: -332630

In [645]:
train_metrics = evaluate_model(model_3, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_3, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9981
Precision: 0.6803
Recall: 1.0
F0.5-score: 0.7268
Profit: -560

Test
ROC-AUC: 0.985
Precision: 0.5541
Recall: 0.8915
F0.5-score: 0.5995
Profit: -332630

Увеличение количества нейронов в 2 раза тоже улучшило качество отновительно бейзлайна, но не так сильно, как добавление доп слоя. 

Из интересного, если увеличить колво нейронов в 4 раза, то качество станет хуже

## model_4_tolko_batchnorm

In [647]:
EPOCHS = 30
LR = 0.01

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_4 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),

    nn.Linear(8, 1)
)



run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_4_batchnorm_only", config=config)
log_file = new_log_file()

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_4.parameters(), lr=LR)

config = {
    "model": "MLP_batchnorm_only",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_4)
}

model_4 = train_model(
    model=model_4,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_4_tolko_batchnorm"
)


save_results(model_4, "model_4", log_file, run)

run.finish()

model_4_tolko_batchnorm | valid epoch 1
ROC-AUC: 0.9526
Precision: 0.1321
Recall: 1.0
F0.5-score: 0.1598
Profit: -3345

Эпоха 1 | Train Loss: 0.9802 | Val ROC-AUC: 0.9526 | Val Profit: -3345
model_4_tolko_batchnorm | valid epoch 2
ROC-AUC: 0.9611
Precision: 0.1963
Recall: 1.0
F0.5-score: 0.2339
Profit: -2045

Эпоха 2 | Train Loss: 0.5755 | Val ROC-AUC: 0.9611 | Val Profit: -2045
model_4_tolko_batchnorm | valid epoch 3
ROC-AUC: 0.9569
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 3 | Train Loss: 0.4234 | Val ROC-AUC: 0.9569 | Val Profit: -1545
model_4_tolko_batchnorm | valid epoch 4
ROC-AUC: 0.9654
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 4 | Train Loss: 0.4019 | Val ROC-AUC: 0.9654 | Val Profit: -1295
model_4_tolko_batchnorm | valid epoch 5
ROC-AUC: 0.9755
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 5 | Train Loss: 0.3175 | Val ROC-AUC: 0.9755 | Val Profit: -595
model_4_tolko_batchnorm | valid epoch 6
ROC-AUC: 0.9777
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 6 | Train Loss: 0.2555 | Val ROC-AUC: 0.9777 | Val Profit: -565
model_4_tolko_batchnorm | valid epoch 7
ROC-AUC: 0.9745
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 7 | Train Loss: 0.2651 | Val ROC-AUC: 0.9745 | Val Profit: -930
model_4_tolko_batchnorm | valid epoch 8
ROC-AUC: 0.9791
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 8 | Train Loss: 0.3230 | Val ROC-AUC: 0.9791 | Val Profit: -1145
model_4_tolko_batchnorm | valid epoch 9
ROC-AUC: 0.9745
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 9 | Train Loss: 0.2583 | Val ROC-AUC: 0.9745 | Val Profit: -530
model_4_tolko_batchnorm | valid epoch 10
ROC-AUC: 0.9725
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 10 | Train Loss: 0.2138 | Val ROC-AUC: 0.9725 | Val Profit: -335
model_4_tolko_batchnorm | valid epoch 11
ROC-AUC: 0.9769
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 11 | Train Loss: 0.2295 | Val ROC-AUC: 0.9769 | Val Profit: -400
model_4_tolko_batchnorm | valid epoch 12
ROC-AUC: 0.9815
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 12 | Train Loss: 0.1978 | Val ROC-AUC: 0.9815 | Val Profit: -280
model_4_tolko_batchnorm | valid epoch 13
ROC-AUC: 0.9826
Precision: 0.8333
Recall: 0.7143
F0.5-score: 0.8065
Profit: -30

Эпоха 13 | Train Loss: 0.1671 | Val ROC-AUC: 0.9826 | Val Profit: -30
model_4_tolko_batchnorm | valid epoch 14
ROC-AUC: 0.9349
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 14 | Train Loss: 0.1320 | Val ROC-AUC: 0.9349 | Val Profit: -90
model_4_tolko_batchnorm | valid epoch 15
ROC-AUC: 0.9657
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 15 | Train Loss: 0.3041 | Val ROC-AUC: 0.9657 | Val Profit: -1470
model_4_tolko_batchnorm | valid epoch 16
ROC-AUC: 0.9805
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 16 | Train Loss: 0.3201 | Val ROC-AUC: 0.9805 | Val Profit: -795
model_4_tolko_batchnorm | valid epoch 17
ROC-AUC: 0.9805
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 17 | Train Loss: 0.2332 | Val ROC-AUC: 0.9805 | Val Profit: -335
model_4_tolko_batchnorm | valid epoch 18
ROC-AUC: 0.9792
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 18 | Train Loss: 0.1919 | Val ROC-AUC: 0.9792 | Val Profit: -230
model_4_tolko_batchnorm | valid epoch 19
ROC-AUC: 0.9814
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 19 | Train Loss: 0.1785 | Val ROC-AUC: 0.9814 | Val Profit: -90
model_4_tolko_batchnorm | valid epoch 20
ROC-AUC: 0.9781
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 20 | Train Loss: 0.1531 | Val ROC-AUC: 0.9781 | Val Profit: -70
model_4_tolko_batchnorm | valid epoch 21
ROC-AUC: 0.9801
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 21 | Train Loss: 0.2053 | Val ROC-AUC: 0.9801 | Val Profit: -465
model_4_tolko_batchnorm | valid epoch 22
ROC-AUC: 0.9398
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 22 | Train Loss: 0.2263 | Val ROC-AUC: 0.9398 | Val Profit: -360
model_4_tolko_batchnorm | valid epoch 23
ROC-AUC: 0.9531
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 23 | Train Loss: 0.2190 | Val ROC-AUC: 0.9531 | Val Profit: -310
model_4_tolko_batchnorm | valid epoch 24
ROC-AUC: 0.9386
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 24 | Train Loss: 0.1802 | Val ROC-AUC: 0.9386 | Val Profit: -150
model_4_tolko_batchnorm | valid epoch 25
ROC-AUC: 0.9392
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 25 | Train Loss: 0.1544 | Val ROC-AUC: 0.9392 | Val Profit: -115
model_4_tolko_batchnorm | valid epoch 26
ROC-AUC: 0.9433
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 26 | Train Loss: 0.1180 | Val ROC-AUC: 0.9433 | Val Profit: -55
model_4_tolko_batchnorm | valid epoch 27
ROC-AUC: 0.881
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 27 | Train Loss: 0.1017 | Val ROC-AUC: 0.8810 | Val Profit: -145
model_4_tolko_batchnorm | valid epoch 28
ROC-AUC: 0.9773
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 28 | Train Loss: 0.3205 | Val ROC-AUC: 0.9773 | Val Profit: -1195
model_4_tolko_batchnorm | valid epoch 29
ROC-AUC: 0.961
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 29 | Train Loss: 0.2884 | Val ROC-AUC: 0.9610 | Val Profit: -1030
model_4_tolko_batchnorm | valid epoch 30
ROC-AUC: 0.9693
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 30 | Train Loss: 0.2897 | Val ROC-AUC: 0.9693 | Val Profit: -655

Лучшая эпоха для model_4_tolko_batchnorm: 13
Лучший ROC-AUC: 0.982562038900067
Train
ROC-AUC: 0.994
Precision: 0.8312
Recall: 0.7711
F0.5-score: 0.8184
Profit: -100

Test
ROC-AUC: 0.97
Precision: 0.7059
Recall: 0.6019
F0.5-score: 0.6823
Profit: -124565

In [648]:
train_metrics = evaluate_model(model_4, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_4, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.994
Precision: 0.8312
Recall: 0.7711
F0.5-score: 0.8184
Profit: -100

Test
ROC-AUC: 0.97
Precision: 0.7059
Recall: 0.6019
F0.5-score: 0.6823
Profit: -124565

Так как в предыдущие разы качество улучшилось с увеличением колво слоев, то теперь мы решили добавить колво слоев, а также после каждого слоя сделать только BatchNorm

Видно, что это сильно улучшило качество!

## model_5_tolko_dropout

In [653]:
EPOCHS = 40
LR = 0.01
DROPOUT_COEF = 0.1

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_5 = nn.Sequential(
    nn.Linear(9, 128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_5.parameters(), lr=LR)

config = {
    "model": "MLP_dropout_only",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "dropout_coef": DROPOUT_COEF,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_5)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_5_dropout_only", config=config)
log_file = new_log_file()

model_5 = train_model(
    model=model_5,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_5_tolko_dropout"
)

save_results(model_5, "model_5", log_file, run)

run.finish()

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.8844
Precision: 0.1944
Recall: 1.0
F0.5-score: 0.2318
Profit: -2070

Эпоха 1 | Train Loss: 1.1128 | Val ROC-AUC: 0.8844 | Val Profit: -2070
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9249
Precision: 0.1909
Recall: 1.0
F0.5-score: 0.2278
Profit: -2120

Эпоха 2 | Train Loss: 0.8482 | Val ROC-AUC: 0.9249 | Val Profit: -2120
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9371
Precision: 0.3409
Recall: 0.7143
F0.5-score: 0.3807
Profit: -680

Эпоха 3 | Train Loss: 0.5357 | Val ROC-AUC: 0.9371 | Val Profit: -680
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9647
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 4 | Train Loss: 0.4602 | Val ROC-AUC: 0.9647 | Val Profit: -1095
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9548
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 5 | Train Loss: 0.3578 | Val ROC-AUC: 0.9548 | Val Profit: -980
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9603
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 6 | Train Loss: 0.3530 | Val ROC-AUC: 0.9603 | Val Profit: -1145
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9717
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 7 | Train Loss: 0.2863 | Val ROC-AUC: 0.9717 | Val Profit: -720
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9627
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 8 | Train Loss: 0.2870 | Val ROC-AUC: 0.9627 | Val Profit: -1045
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9573
Precision: 0.2564
Recall: 0.9524
F0.5-score: 0.3003
Profit: -1355

Эпоха 9 | Train Loss: 0.3138 | Val ROC-AUC: 0.9573 | Val Profit: -1355
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9685
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 10 | Train Loss: 0.3002 | Val ROC-AUC: 0.9685 | Val Profit: -705
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9702
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 11 | Train Loss: 0.3421 | Val ROC-AUC: 0.9702 | Val Profit: -1695
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9651
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 12 | Train Loss: 0.3770 | Val ROC-AUC: 0.9651 | Val Profit: -1645
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9458
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 13 | Train Loss: 0.3648 | Val ROC-AUC: 0.9458 | Val Profit: -1345
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9618
Precision: 0.375
Recall: 0.8571
F0.5-score: 0.4225
Profit: -675

Эпоха 14 | Train Loss: 0.2491 | Val ROC-AUC: 0.9618 | Val Profit: -675
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9635
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 15 | Train Loss: 0.1774 | Val ROC-AUC: 0.9635 | Val Profit: -730
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9682
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 16 | Train Loss: 0.1872 | Val ROC-AUC: 0.9682 | Val Profit: -940
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9573
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 17 | Train Loss: 0.4040 | Val ROC-AUC: 0.9573 | Val Profit: -940
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9623
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 18 | Train Loss: 0.3855 | Val ROC-AUC: 0.9623 | Val Profit: -980
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9741
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 19 | Train Loss: 0.3076 | Val ROC-AUC: 0.9741 | Val Profit: -995
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.972
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 20 | Train Loss: 0.2369 | Val ROC-AUC: 0.9720 | Val Profit: -1070
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9763
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 21 | Train Loss: 0.2220 | Val ROC-AUC: 0.9763 | Val Profit: -745
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9691
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 22 | Train Loss: 0.1811 | Val ROC-AUC: 0.9691 | Val Profit: -705
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9721
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 23 | Train Loss: 0.1628 | Val ROC-AUC: 0.9721 | Val Profit: -430
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9678
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 24 | Train Loss: 0.2916 | Val ROC-AUC: 0.9678 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9666
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 25 | Train Loss: 0.3669 | Val ROC-AUC: 0.9666 | Val Profit: -1145
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9726
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 26 | Train Loss: 0.1893 | Val ROC-AUC: 0.9726 | Val Profit: -515
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9756
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 27 | Train Loss: 0.1309 | Val ROC-AUC: 0.9756 | Val Profit: -325
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9777
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 28 | Train Loss: 0.0880 | Val ROC-AUC: 0.9777 | Val Profit: -440
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9595
Precision: 0.3519
Recall: 0.9048
F0.5-score: 0.4008
Profit: -790

Эпоха 29 | Train Loss: 0.2351 | Val ROC-AUC: 0.9595 | Val Profit: -790
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9736
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 30 | Train Loss: 0.2029 | Val ROC-AUC: 0.9736 | Val Profit: -615
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9728
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 31 | Train Loss: 0.1338 | Val ROC-AUC: 0.9728 | Val Profit: -780
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9769
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 32 | Train Loss: 0.2359 | Val ROC-AUC: 0.9769 | Val Profit: -340
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9792
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 33 | Train Loss: 0.1657 | Val ROC-AUC: 0.9792 | Val Profit: -325
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9434
Precision: 0.2769
Recall: 0.8571
F0.5-score: 0.3203
Profit: -1100

Эпоха 34 | Train Loss: 0.3010 | Val ROC-AUC: 0.9434 | Val Profit: -1100
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9707
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 35 | Train Loss: 0.1745 | Val ROC-AUC: 0.9707 | Val Profit: -665
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9776
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 36 | Train Loss: 0.1070 | Val ROC-AUC: 0.9776 | Val Profit: -325
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9691
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 37 | Train Loss: 0.1055 | Val ROC-AUC: 0.9691 | Val Profit: -565
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9717
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 38 | Train Loss: 0.1733 | Val ROC-AUC: 0.9717 | Val Profit: -440
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9748
Precision: 0.6154
Recall: 0.7619
F0.5-score: 0.64
Profit: -195

Эпоха 39 | Train Loss: 0.0858 | Val ROC-AUC: 0.9748 | Val Profit: -195
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9779
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 40 | Train Loss: 0.0531 | Val ROC-AUC: 0.9779 | Val Profit: -175

Лучшая эпоха для model_5_tolko_dropout: 33
Лучший ROC-AUC: 0.9792085848423877
Train
ROC-AUC: 0.9895
Precision: 0.7019
Recall: 0.8795
F0.5-score: 0.7315
Profit: -460

Test
ROC-AUC: 0.9788
Precision: 0.5378
Recall: 0.7792
F0.5-score: 0.5733
Profit: -330965

In [654]:
train_metrics = evaluate_model(model_5, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_5, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9895
Precision: 0.7019
Recall: 0.8795
F0.5-score: 0.7315
Profit: -460

Test
ROC-AUC: 0.9788
Precision: 0.5378
Recall: 0.7792
F0.5-score: 0.5733
Profit: -330965

Теперь сделаем эксперимет с dropout. Увеличим колво эпох и попробуем подобрать коэффицент экспериментально. Лучшее качество достигли при коэффиценте = 0.1

Увеличение колво эпох не улучшило ситуацию с переобучением

Это лучше чем бейзлайн, но батнорм показал себя лучше в 3 раза чем дропаут в этом эксперименте

## model_6_batchnorm_i_dropout

In [661]:
EPOCHS = 30
LR = 0.01
DROPOUT_COEF = 0.1
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_6 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_6.parameters(), lr=LR)

config = {
    "model": "MLP_batchnorm_dropout",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "dropout_coef": DROPOUT_COEF,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_6)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_6_batchnorm_dropout", config=config)
log_file = new_log_file()

model_6 = train_model(
    model=model_6,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_6_batchnorm_i_dropout"
)


save_results(model_6, "model_6", log_file, run)

run.finish()

model_6_batchnorm_i_dropout | valid epoch 1
ROC-AUC: 0.9462
Precision: 0.1207
Recall: 1.0
F0.5-score: 0.1464
Profit: -3720

Эпоха 1 | Train Loss: 1.1907 | Val ROC-AUC: 0.9462 | Val Profit: -3720
model_6_batchnorm_i_dropout | valid epoch 2
ROC-AUC: 0.9659
Precision: 0.1641
Recall: 1.0
F0.5-score: 0.197
Profit: -2570

Эпоха 2 | Train Loss: 0.7817 | Val ROC-AUC: 0.9659 | Val Profit: -2570
model_6_batchnorm_i_dropout | valid epoch 3
ROC-AUC: 0.9602
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 3 | Train Loss: 0.4925 | Val ROC-AUC: 0.9602 | Val Profit: -1105
model_6_batchnorm_i_dropout | valid epoch 4
ROC-AUC: 0.9486
Precision: 0.2234
Recall: 1.0
F0.5-score: 0.2645
Profit: -1720

Эпоха 4 | Train Loss: 0.4173 | Val ROC-AUC: 0.9486 | Val Profit: -1720
model_6_batchnorm_i_dropout | valid epoch 5
ROC-AUC: 0.9663
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 5 | Train Loss: 0.3899 | Val ROC-AUC: 0.9663 | Val Profit: -1145
model_6_batchnorm_i_dropout | valid epoch 6
ROC-AUC: 0.9717
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 6 | Train Loss: 0.3152 | Val ROC-AUC: 0.9717 | Val Profit: -680
model_6_batchnorm_i_dropout | valid epoch 7
ROC-AUC: 0.9708
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 7 | Train Loss: 0.2320 | Val ROC-AUC: 0.9708 | Val Profit: -325
model_6_batchnorm_i_dropout | valid epoch 8
ROC-AUC: 0.9746
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 8 | Train Loss: 0.2737 | Val ROC-AUC: 0.9746 | Val Profit: -930
model_6_batchnorm_i_dropout | valid epoch 9
ROC-AUC: 0.9261
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 9 | Train Loss: 0.1803 | Val ROC-AUC: 0.9261 | Val Profit: -195
model_6_batchnorm_i_dropout | valid epoch 10
ROC-AUC: 0.8897
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 10 | Train Loss: 0.1271 | Val ROC-AUC: 0.8897 | Val Profit: -185
model_6_batchnorm_i_dropout | valid epoch 11
ROC-AUC: 0.9646
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 11 | Train Loss: 0.2170 | Val ROC-AUC: 0.9646 | Val Profit: -1520
model_6_batchnorm_i_dropout | valid epoch 12
ROC-AUC: 0.9591
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 12 | Train Loss: 0.3112 | Val ROC-AUC: 0.9591 | Val Profit: -1055
model_6_batchnorm_i_dropout | valid epoch 13
ROC-AUC: 0.9725
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 13 | Train Loss: 0.2482 | Val ROC-AUC: 0.9725 | Val Profit: -480
model_6_batchnorm_i_dropout | valid epoch 14
ROC-AUC: 0.9734
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 14 | Train Loss: 0.1831 | Val ROC-AUC: 0.9734 | Val Profit: -245
model_6_batchnorm_i_dropout | valid epoch 15
ROC-AUC: 0.9698
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 15 | Train Loss: 0.1417 | Val ROC-AUC: 0.9698 | Val Profit: -230
model_6_batchnorm_i_dropout | valid epoch 16
ROC-AUC: 0.9647
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 16 | Train Loss: 0.1161 | Val ROC-AUC: 0.9647 | Val Profit: -220
model_6_batchnorm_i_dropout | valid epoch 17
ROC-AUC: 0.9588
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 17 | Train Loss: 0.0880 | Val ROC-AUC: 0.9588 | Val Profit: -210
model_6_batchnorm_i_dropout | valid epoch 18
ROC-AUC: 0.9535
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 18 | Train Loss: 0.0696 | Val ROC-AUC: 0.9535 | Val Profit: -125
model_6_batchnorm_i_dropout | valid epoch 19
ROC-AUC: 0.962
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 19 | Train Loss: 0.0548 | Val ROC-AUC: 0.9620 | Val Profit: -130
model_6_batchnorm_i_dropout | valid epoch 20
ROC-AUC: 0.9068
Precision: 0.4167
Recall: 0.2381
F0.5-score: 0.3623
Profit: -230

Эпоха 20 | Train Loss: 0.0513 | Val ROC-AUC: 0.9068 | Val Profit: -230
model_6_batchnorm_i_dropout | valid epoch 21
ROC-AUC: 0.9551
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 21 | Train Loss: 0.1108 | Val ROC-AUC: 0.9551 | Val Profit: -625
model_6_batchnorm_i_dropout | valid epoch 22
ROC-AUC: 0.9565
Precision: 0.4048
Recall: 0.8095
F0.5-score: 0.4497
Profit: -560

Эпоха 22 | Train Loss: 0.2733 | Val ROC-AUC: 0.9565 | Val Profit: -560
model_6_batchnorm_i_dropout | valid epoch 23
ROC-AUC: 0.9581
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 23 | Train Loss: 0.1764 | Val ROC-AUC: 0.9581 | Val Profit: -200
model_6_batchnorm_i_dropout | valid epoch 24
ROC-AUC: 0.9696
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 24 | Train Loss: 0.1171 | Val ROC-AUC: 0.9696 | Val Profit: -215
model_6_batchnorm_i_dropout | valid epoch 25
ROC-AUC: 0.9689
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 25 | Train Loss: 0.0749 | Val ROC-AUC: 0.9689 | Val Profit: -170
model_6_batchnorm_i_dropout | valid epoch 26
ROC-AUC: 0.9679
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 26 | Train Loss: 0.0567 | Val ROC-AUC: 0.9679 | Val Profit: -190
model_6_batchnorm_i_dropout | valid epoch 27
ROC-AUC: 0.973
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 27 | Train Loss: 0.0423 | Val ROC-AUC: 0.9730 | Val Profit: -155
model_6_batchnorm_i_dropout | valid epoch 28
ROC-AUC: 0.9698
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 28 | Train Loss: 0.0356 | Val ROC-AUC: 0.9698 | Val Profit: -165
model_6_batchnorm_i_dropout | valid epoch 29
ROC-AUC: 0.9722
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 29 | Train Loss: 0.0291 | Val ROC-AUC: 0.9722 | Val Profit: -165
model_6_batchnorm_i_dropout | valid epoch 30
ROC-AUC: 0.9749
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 30 | Train Loss: 0.0253 | Val ROC-AUC: 0.9749 | Val Profit: -165

Лучшая эпоха для model_6_batchnorm_i_dropout: 30
Лучший ROC-AUC: 0.974916163648558
Train
ROC-AUC: 0.9804
Precision: 0.9565
Recall: 0.2651
F0.5-score: 0.6286
Profit: -220

Test
ROC-AUC: 0.9489
Precision: 0.8013
Recall: 0.2525
F0.5-score: 0.5585
Profit: -95860

In [662]:
train_metrics = evaluate_model(model_6, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_6, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9804
Precision: 0.9565
Recall: 0.2651
F0.5-score: 0.6286
Profit: -220

Test
ROC-AUC: 0.9489
Precision: 0.8013
Recall: 0.2525
F0.5-score: 0.5585
Profit: -95860

Если соединить 2 и дропаут и батчнорм вместе видим хорошее качество -- наш Profit поднялся до -95к

## model_7_leaky_relu

In [677]:
EPOCHS = 50
LR = 0.01
DROPOUT_COEF = 0.3
NEG_SLOPE = 0.03

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_7 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_7.parameters(), lr=LR)

config = {
    "model": "MLP_leaky_relu",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "dropout_coef": DROPOUT_COEF,
    "negative_slope": NEG_SLOPE,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_7)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_7_leaky_relu", config=config)
log_file = new_log_file()

model_7 = train_model(
    model=model_7,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_7_leaky_relu"
)
save_results(model_7, "model_7", log_file, run)

run.finish()

model_7_leaky_relu | valid epoch 1
ROC-AUC: 0.9484
Precision: 0.1391
Recall: 1.0
F0.5-score: 0.168
Profit: -3145

Эпоха 1 | Train Loss: 1.1772 | Val ROC-AUC: 0.9484 | Val Profit: -3145
model_7_leaky_relu | valid epoch 2
ROC-AUC: 0.9353
Precision: 0.1654
Recall: 1.0
F0.5-score: 0.1985
Profit: -2545

Эпоха 2 | Train Loss: 0.8285 | Val ROC-AUC: 0.9353 | Val Profit: -2545
model_7_leaky_relu | valid epoch 3
ROC-AUC: 0.9581
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 3 | Train Loss: 0.5045 | Val ROC-AUC: 0.9581 | Val Profit: -455
model_7_leaky_relu | valid epoch 4
ROC-AUC: 0.9319
Precision: 0.3208
Recall: 0.8095
F0.5-score: 0.3648
Profit: -835

Эпоха 4 | Train Loss: 0.3032 | Val ROC-AUC: 0.9319 | Val Profit: -835
model_7_leaky_relu | valid epoch 5
ROC-AUC: 0.9496
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 5 | Train Loss: 0.3013 | Val ROC-AUC: 0.9496 | Val Profit: -1030
model_7_leaky_relu | valid epoch 6
ROC-AUC: 0.928
Precision: 0.3659
Recall: 0.7143
F0.5-score: 0.4054
Profit: -605

Эпоха 6 | Train Loss: 0.2674 | Val ROC-AUC: 0.9280 | Val Profit: -605
model_7_leaky_relu | valid epoch 7
ROC-AUC: 0.921
Precision: 0.3462
Recall: 0.8571
F0.5-score: 0.393
Profit: -775

Эпоха 7 | Train Loss: 0.1801 | Val ROC-AUC: 0.9210 | Val Profit: -775
model_7_leaky_relu | valid epoch 8
ROC-AUC: 0.9567
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 8 | Train Loss: 0.1570 | Val ROC-AUC: 0.9567 | Val Profit: -485
model_7_leaky_relu | valid epoch 9
ROC-AUC: 0.9336
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 9 | Train Loss: 0.2354 | Val ROC-AUC: 0.9336 | Val Profit: -490
model_7_leaky_relu | valid epoch 10
ROC-AUC: 0.9583
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 10 | Train Loss: 0.2121 | Val ROC-AUC: 0.9583 | Val Profit: -780
model_7_leaky_relu | valid epoch 11
ROC-AUC: 0.9641
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 11 | Train Loss: 0.1355 | Val ROC-AUC: 0.9641 | Val Profit: -410
model_7_leaky_relu | valid epoch 12
ROC-AUC: 0.9689
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 12 | Train Loss: 0.0877 | Val ROC-AUC: 0.9689 | Val Profit: -195
model_7_leaky_relu | valid epoch 13
ROC-AUC: 0.9658
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 13 | Train Loss: 0.0599 | Val ROC-AUC: 0.9658 | Val Profit: -225
model_7_leaky_relu | valid epoch 14
ROC-AUC: 0.9658
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 14 | Train Loss: 0.0466 | Val ROC-AUC: 0.9658 | Val Profit: -185
model_7_leaky_relu | valid epoch 15
ROC-AUC: 0.9649
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 15 | Train Loss: 0.0379 | Val ROC-AUC: 0.9649 | Val Profit: -155
model_7_leaky_relu | valid epoch 16
ROC-AUC: 0.9618
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 16 | Train Loss: 0.0310 | Val ROC-AUC: 0.9618 | Val Profit: -155
model_7_leaky_relu | valid epoch 17
ROC-AUC: 0.9619
Precision: 0.2
Recall: 0.0476
F0.5-score: 0.122
Profit: -195

Эпоха 17 | Train Loss: 0.0272 | Val ROC-AUC: 0.9619 | Val Profit: -195
model_7_leaky_relu | valid epoch 18
ROC-AUC: 0.9619
Precision: 0.2
Recall: 0.0476
F0.5-score: 0.122
Profit: -195

Эпоха 18 | Train Loss: 0.0242 | Val ROC-AUC: 0.9619 | Val Profit: -195
model_7_leaky_relu | valid epoch 19
ROC-AUC: 0.9592
Precision: 0.2
Recall: 0.0476
F0.5-score: 0.122
Profit: -195

Эпоха 19 | Train Loss: 0.0222 | Val ROC-AUC: 0.9592 | Val Profit: -195
model_7_leaky_relu | valid epoch 20
ROC-AUC: 0.9557
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 20 | Train Loss: 0.0202 | Val ROC-AUC: 0.9557 | Val Profit: -180
model_7_leaky_relu | valid epoch 21
ROC-AUC: 0.9532
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 21 | Train Loss: 0.0179 | Val ROC-AUC: 0.9532 | Val Profit: -180
model_7_leaky_relu | valid epoch 22
ROC-AUC: 0.95
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 22 | Train Loss: 0.0150 | Val ROC-AUC: 0.9500 | Val Profit: -170
model_7_leaky_relu | valid epoch 23
ROC-AUC: 0.9549
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 23 | Train Loss: 0.0133 | Val ROC-AUC: 0.9549 | Val Profit: -170
model_7_leaky_relu | valid epoch 24
ROC-AUC: 0.9569
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 24 | Train Loss: 0.0127 | Val ROC-AUC: 0.9569 | Val Profit: -180
model_7_leaky_relu | valid epoch 25
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 25 | Train Loss: 0.0119 | Val ROC-AUC: 0.9598 | Val Profit: -155
model_7_leaky_relu | valid epoch 26
ROC-AUC: 0.9607
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0105 | Val ROC-AUC: 0.9607 | Val Profit: -130
model_7_leaky_relu | valid epoch 27
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0097 | Val ROC-AUC: 0.9596 | Val Profit: -130
model_7_leaky_relu | valid epoch 28
ROC-AUC: 0.9587
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0091 | Val ROC-AUC: 0.9587 | Val Profit: -130
model_7_leaky_relu | valid epoch 29
ROC-AUC: 0.9561
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 29 | Train Loss: 0.0086 | Val ROC-AUC: 0.9561 | Val Profit: -155
model_7_leaky_relu | valid epoch 30
ROC-AUC: 0.9537
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 30 | Train Loss: 0.0079 | Val ROC-AUC: 0.9537 | Val Profit: -155
model_7_leaky_relu | valid epoch 31
ROC-AUC: 0.9478
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 31 | Train Loss: 0.0072 | Val ROC-AUC: 0.9478 | Val Profit: -155
model_7_leaky_relu | valid epoch 32
ROC-AUC: 0.9493
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 32 | Train Loss: 0.0068 | Val ROC-AUC: 0.9493 | Val Profit: -155
model_7_leaky_relu | valid epoch 33
ROC-AUC: 0.9512
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 33 | Train Loss: 0.0064 | Val ROC-AUC: 0.9512 | Val Profit: -155
model_7_leaky_relu | valid epoch 34
ROC-AUC: 0.9531
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 34 | Train Loss: 0.0061 | Val ROC-AUC: 0.9531 | Val Profit: -155
model_7_leaky_relu | valid epoch 35
ROC-AUC: 0.954
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 35 | Train Loss: 0.0058 | Val ROC-AUC: 0.9540 | Val Profit: -145
model_7_leaky_relu | valid epoch 36
ROC-AUC: 0.9551
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 36 | Train Loss: 0.0053 | Val ROC-AUC: 0.9551 | Val Profit: -145
model_7_leaky_relu | valid epoch 37
ROC-AUC: 0.9576
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 37 | Train Loss: 0.0051 | Val ROC-AUC: 0.9576 | Val Profit: -155
model_7_leaky_relu | valid epoch 38
ROC-AUC: 0.9579
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 38 | Train Loss: 0.0049 | Val ROC-AUC: 0.9579 | Val Profit: -155
model_7_leaky_relu | valid epoch 39
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 39 | Train Loss: 0.0047 | Val ROC-AUC: 0.9584 | Val Profit: -155
model_7_leaky_relu | valid epoch 40
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 40 | Train Loss: 0.0045 | Val ROC-AUC: 0.9590 | Val Profit: -155
model_7_leaky_relu | valid epoch 41
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 41 | Train Loss: 0.0044 | Val ROC-AUC: 0.9594 | Val Profit: -155
model_7_leaky_relu | valid epoch 42
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 42 | Train Loss: 0.0042 | Val ROC-AUC: 0.9599 | Val Profit: -155
model_7_leaky_relu | valid epoch 43
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 43 | Train Loss: 0.0041 | Val ROC-AUC: 0.9599 | Val Profit: -155
model_7_leaky_relu | valid epoch 44
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 44 | Train Loss: 0.0040 | Val ROC-AUC: 0.9599 | Val Profit: -155
model_7_leaky_relu | valid epoch 45
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 45 | Train Loss: 0.0039 | Val ROC-AUC: 0.9599 | Val Profit: -155
model_7_leaky_relu | valid epoch 46
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 46 | Train Loss: 0.0038 | Val ROC-AUC: 0.9598 | Val Profit: -155
model_7_leaky_relu | valid epoch 47
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 47 | Train Loss: 0.0037 | Val ROC-AUC: 0.9596 | Val Profit: -155
model_7_leaky_relu | valid epoch 48
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 48 | Train Loss: 0.0036 | Val ROC-AUC: 0.9598 | Val Profit: -155
model_7_leaky_relu | valid epoch 49
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 49 | Train Loss: 0.0035 | Val ROC-AUC: 0.9599 | Val Profit: -155
model_7_leaky_relu | valid epoch 50
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 50 | Train Loss: 0.0034 | Val ROC-AUC: 0.9598 | Val Profit: -155

Лучшая эпоха для model_7_leaky_relu: 12
Лучший ROC-AUC: 0.9688799463447351
Train
ROC-AUC: 0.977
Precision: 0.6515
Recall: 0.5181
F0.5-score: 0.6196
Profit: -560

Test
ROC-AUC: 0.9631
Precision: 0.5724
Recall: 0.4502
F0.5-score: 0.5429
Profit: -211275

In [678]:
train_metrics = evaluate_model(model_7, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_7, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.977
Precision: 0.6515
Recall: 0.5181
F0.5-score: 0.6196
Profit: -560

Test
ROC-AUC: 0.9631
Precision: 0.5724
Recall: 0.4502
F0.5-score: 0.5429
Profit: -211275

Поменяв функцию активации с ReLu на LeakyRelu и поиграв с параметрами EPOCHS, DROPOUT_COEF и
NEG_SLOPE получилось добиться лучшего качества по Profit в -211к

Да, это лучше бейзлайна, но качество ухудшилось. 

Вывод: особого эффекта LeakyRelu не дал

## model_8_weight_decay

In [716]:
EPOCHS = 40
LR = 0.01
WEIGHT_DECAY=0.001
DROPOUT_COEF = 0.3

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_8 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_8.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

config = {
    "model": "MLP_weight_decay",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_8)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_8_weight_decay", config=config)
log_file = new_log_file()

model_8 = train_model(
    model=model_8,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_8_weight_decay"
)

save_results(model_8, "model_8", log_file, run)

run.finish()

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9199
Precision: 0.1105
Recall: 1.0
F0.5-score: 0.1344
Profit: -4120

Эпоха 1 | Train Loss: 1.2208 | Val ROC-AUC: 0.9199 | Val Profit: -4120
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9528
Precision: 0.1567
Recall: 1.0
F0.5-score: 0.1885
Profit: -2720

Эпоха 2 | Train Loss: 0.9239 | Val ROC-AUC: 0.9528 | Val Profit: -2720
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.963
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 3 | Train Loss: 0.6171 | Val ROC-AUC: 0.9630 | Val Profit: -755
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9427
Precision: 0.2778
Recall: 0.7143
F0.5-score: 0.3165
Profit: -930

Эпоха 4 | Train Loss: 0.4336 | Val ROC-AUC: 0.9427 | Val Profit: -930
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9199
Precision: 0.25
Recall: 0.5714
F0.5-score: 0.2817
Profit: -885

Эпоха 5 | Train Loss: 0.4106 | Val ROC-AUC: 0.9199 | Val Profit: -885
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.959
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 6 | Train Loss: 0.3184 | Val ROC-AUC: 0.9590 | Val Profit: -980
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9492
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 7 | Train Loss: 0.2681 | Val ROC-AUC: 0.9492 | Val Profit: -240
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9453
Precision: 0.375
Recall: 0.5714
F0.5-score: 0.4027
Profit: -485

Эпоха 8 | Train Loss: 0.1944 | Val ROC-AUC: 0.9453 | Val Profit: -485
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9687
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 9 | Train Loss: 0.2193 | Val ROC-AUC: 0.9687 | Val Profit: -400
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9713
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 10 | Train Loss: 0.1844 | Val ROC-AUC: 0.9713 | Val Profit: -500
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9388
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 11 | Train Loss: 0.1973 | Val ROC-AUC: 0.9388 | Val Profit: -220
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9147
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 12 | Train Loss: 0.1239 | Val ROC-AUC: 0.9147 | Val Profit: -140
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9626
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 13 | Train Loss: 0.0989 | Val ROC-AUC: 0.9626 | Val Profit: -160
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9725
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 14 | Train Loss: 0.0640 | Val ROC-AUC: 0.9725 | Val Profit: -85
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9628
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 15 | Train Loss: 0.0476 | Val ROC-AUC: 0.9628 | Val Profit: -100
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9471
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 16 | Train Loss: 0.0384 | Val ROC-AUC: 0.9471 | Val Profit: -110
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9671
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 17 | Train Loss: 0.0336 | Val ROC-AUC: 0.9671 | Val Profit: -110
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9667
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0298 | Val ROC-AUC: 0.9667 | Val Profit: -120
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9657
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 19 | Train Loss: 0.0272 | Val ROC-AUC: 0.9657 | Val Profit: -120
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9666
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 20 | Train Loss: 0.0259 | Val ROC-AUC: 0.9666 | Val Profit: -120
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9675
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0248 | Val ROC-AUC: 0.9675 | Val Profit: -120
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9683
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0240 | Val ROC-AUC: 0.9683 | Val Profit: -120
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0231 | Val ROC-AUC: 0.9679 | Val Profit: -130
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9701
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.0222 | Val ROC-AUC: 0.9701 | Val Profit: -130
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9679
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 25 | Train Loss: 0.0246 | Val ROC-AUC: 0.9679 | Val Profit: -120
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.925
Precision: 0.2931
Recall: 0.8095
F0.5-score: 0.336
Profit: -960

Эпоха 26 | Train Loss: 0.2365 | Val ROC-AUC: 0.9250 | Val Profit: -960
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9144
Precision: 0.254
Recall: 0.7619
F0.5-score: 0.293
Profit: -1120

Эпоха 27 | Train Loss: 0.9830 | Val ROC-AUC: 0.9144 | Val Profit: -1120
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9667
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 28 | Train Loss: 0.5370 | Val ROC-AUC: 0.9667 | Val Profit: -1070
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9679
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 29 | Train Loss: 0.3355 | Val ROC-AUC: 0.9679 | Val Profit: -665
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9683
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 30 | Train Loss: 0.2460 | Val ROC-AUC: 0.9683 | Val Profit: -270
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9639
Precision: 0.4231
Recall: 0.5238
F0.5-score: 0.44
Profit: -370

Эпоха 31 | Train Loss: 0.1825 | Val ROC-AUC: 0.9639 | Val Profit: -370
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9657
Precision: 0.4211
Recall: 0.381
F0.5-score: 0.4124
Profit: -300

Эпоха 32 | Train Loss: 0.1337 | Val ROC-AUC: 0.9657 | Val Profit: -300
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9659
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 33 | Train Loss: 0.0987 | Val ROC-AUC: 0.9659 | Val Profit: -205
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9655
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 34 | Train Loss: 0.0793 | Val ROC-AUC: 0.9655 | Val Profit: -180
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9682
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 35 | Train Loss: 0.0695 | Val ROC-AUC: 0.9682 | Val Profit: -130
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9677
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 36 | Train Loss: 0.0526 | Val ROC-AUC: 0.9677 | Val Profit: -140
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9639
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 37 | Train Loss: 0.0419 | Val ROC-AUC: 0.9639 | Val Profit: -150
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9643
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 38 | Train Loss: 0.0350 | Val ROC-AUC: 0.9643 | Val Profit: -150
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9649
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 39 | Train Loss: 0.0305 | Val ROC-AUC: 0.9649 | Val Profit: -150
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9638
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 40 | Train Loss: 0.0283 | Val ROC-AUC: 0.9638 | Val Profit: -135

Лучшая эпоха для model_8_weight_decay: 14
Лучший ROC-AUC: 0.9725016767270288
Train
ROC-AUC: 0.9611
Precision: 0.85
Recall: 0.2048
F0.5-score: 0.5215
Profit: -320

Test
ROC-AUC: 0.9449
Precision: 0.7599
Recall: 0.2423
F0.5-score: 0.5324
Profit: -106555

In [717]:
train_metrics = evaluate_model(model_8, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_8, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9611
Precision: 0.85
Recall: 0.2048
F0.5-score: 0.5215
Profit: -320

Test
ROC-AUC: 0.9449
Precision: 0.7599
Recall: 0.2423
F0.5-score: 0.5324
Profit: -106555

Наконец-то добавив регуляризацию видим, что качество значительно улучшилось относительно бейзлайна, но ухудшилось относительно эксперимента с batchnorm и dropout одновременно

При этом пришлось обратно вернуться к обычной RELU

## model_9_Focal_loss

In [698]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        targets = targets.float()

        bce_loss = nn.functional.binary_cross_entropy_with_logits(
            logits,
            targets,
            reduction="none"
        )

        probs = torch.sigmoid(logits)
        pt = torch.where(targets == 1, probs, 1 - probs)
        focal_weight = self.alpha * (1 - pt) ** self.gamma
        loss = focal_weight * bce_loss

        return loss.mean()

In [746]:
EPOCHS = 30
LR = 0.01
DROPOUT_COEF = 0.1
SEED = 42
WEIGHT_DECAY = 0.0001
ALPHA = 0.99
GAMMA = 2.0
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_9 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = FocalLoss(alpha=ALPHA, gamma=GAMMA)
optimizer = torch.optim.Adam(model_9.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

config = {
    "model": "MLP_focal_loss",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "alpha": ALPHA,
    "gamma": GAMMA,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_8)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_9_focal_loss", config=config)
log_file = new_log_file()

model_9 = train_model(
    model=model_9,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_9_Focal_loss"
)


save_results(model_9, "model_9", log_file, run)

run.finish()

/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9325
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0800 | Val ROC-AUC: 0.9325 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9219
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0371 | Val ROC-AUC: 0.9219 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9512
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0281 | Val ROC-AUC: 0.9512 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0292 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9552
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0258 | Val ROC-AUC: 0.9552 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9495
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0228 | Val ROC-AUC: 0.9495 | Val Profit: -105

/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/maxsafonov/gp-5/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9537
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0266 | Val ROC-AUC: 0.9537 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0216 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9658
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0206 | Val ROC-AUC: 0.9658 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0176 | Val ROC-AUC: 0.9661 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9353
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0200 | Val ROC-AUC: 0.9353 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9521
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 12 | Train Loss: 0.0163 | Val ROC-AUC: 0.9521 | Val Profit: -185
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.8778
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 13 | Train Loss: 0.0159 | Val ROC-AUC: 0.8778 | Val Profit: -350
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9757
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 14 | Train Loss: 0.0179 | Val ROC-AUC: 0.9757 | Val Profit: -160
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9482
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 15 | Train Loss: 0.0153 | Val ROC-AUC: 0.9482 | Val Profit: -130
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9679
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 16 | Train Loss: 0.0159 | Val ROC-AUC: 0.9679 | Val Profit: -265
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9808
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 17 | Train Loss: 0.0175 | Val ROC-AUC: 0.9808 | Val Profit: -140
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9779
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 18 | Train Loss: 0.0126 | Val ROC-AUC: 0.9779 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9683
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 19 | Train Loss: 0.0129 | Val ROC-AUC: 0.9683 | Val Profit: -375
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9671
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 20 | Train Loss: 0.0168 | Val ROC-AUC: 0.9671 | Val Profit: -220
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.971
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 21 | Train Loss: 0.0144 | Val ROC-AUC: 0.9710 | Val Profit: -150
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9297
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 22 | Train Loss: 0.0133 | Val ROC-AUC: 0.9297 | Val Profit: -135
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9721
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 23 | Train Loss: 0.0146 | Val ROC-AUC: 0.9721 | Val Profit: -200
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9349
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 24 | Train Loss: 0.0103 | Val ROC-AUC: 0.9349 | Val Profit: -180
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9364
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 25 | Train Loss: 0.0092 | Val ROC-AUC: 0.9364 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9662
Precision: 0.5
Recall: 0.7619
F0.5-score: 0.5369
Profit: -345

Эпоха 26 | Train Loss: 0.0180 | Val ROC-AUC: 0.9662 | Val Profit: -345
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9791
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 27 | Train Loss: 0.0163 | Val ROC-AUC: 0.9791 | Val Profit: -170
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9819
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 28 | Train Loss: 0.0123 | Val ROC-AUC: 0.9819 | Val Profit: -145
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9742
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 29 | Train Loss: 0.0091 | Val ROC-AUC: 0.9742 | Val Profit: -110
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9771
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 30 | Train Loss: 0.0075 | Val ROC-AUC: 0.9771 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9818913480885313
Train
ROC-AUC: 0.9734
Precision: 0.8125
Recall: 0.1566
F0.5-score: 0.4422
Profit: -360

Test
ROC-AUC: 0.969
Precision: 0.8491
Recall: 0.1888
F0.5-score: 0.4997
Profit: -93735

In [747]:
train_metrics = evaluate_model(model_9, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_9, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9734
Precision: 0.8125
Recall: 0.1566
F0.5-score: 0.4422
Profit: -360

Test
ROC-AUC: 0.969
Precision: 0.8491
Recall: 0.1888
F0.5-score: 0.4997
Profit: -93735

В этом эксперименте пробовали ментять функцию активации, но это особо не помогло. Использовал FocalLoss

Параметр альфа = вес класса 1. Поставил его побольше, так как у нас 1 в 17 раз меньше чем 0. Нам важны ошибки, которые модель допускает на 1. 

Параметр гамма = Насколько быстро модель забывает "легкие" нули и фокусируется на сложных границах между классами. Обычно ставят по умолчанию 2.

В случае FocalLoss мы мало штрафуем за уверенные ответы и сильно штрафуем за неуверенные. Отлично подходит для задач, когда сильный дизбаланс классов. 


Но в нашем случае это не дало сильного прироста эффекта. Получилось улучшить на 2к всего от нашего лучшего предыдущего эффекта. Но тем не менее эта архитектура наиболее эффективной получилась сейчас

# ансамбль ПОКА НЕ ТРОГАЛ

In [ ]:
import numpy as np

In [ ]:
def build_model():
    return nn.Sequential(
        nn.Linear(9, 64),
        nn.BatchNorm1d(64),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(64, 32),
        nn.BatchNorm1d(32),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(32, 1),
        )

In [ ]:
EPOCHS = 120
LR = 0.001
WEIGHT_DECAY = 1e-4
N_ENSEMBLE = 5

net = build_model()
opt = torch.optim.Adam(net.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

In [ ]:
loss_fn2 = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

In [ ]:
config = {
    "model": "Ensemble",
    "optimizer": str(opt.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "pos_weight": pos_weight,
    "loss": str(loss_fn2.__class__.__name__),
    "n_ensemble": N_ENSEMBLE,
    "architecture": str(net)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="ensemble", config=config)

In [ ]:
test_probs = []
logging.info("Запустили обучение моделей ансамбля")

np.random.seed(42)
seeds = np.random.randint(1, 525252, size=N_ENSEMBLE)
ensemble = []
for i in range(N_ENSEMBLE):
    seed = seeds[i]
    torch.manual_seed(seed)
    net = build_model()
    opt = torch.optim.Adam(net.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    logging.info(f"Запустили обучение модели {i+1}. Сид: {seed}")


    net.train()
    for epoch in range(1, EPOCHS + 1):
        epoch_loss = 0
        for xb, yb in train_loader:
            opt.zero_grad()
            loss = loss_fn2(net(xb), yb)
            loss.backward()
            epoch_loss += loss.item()
            opt.step()
        
        logging.info(f"эпоха: {epoch}, loss:  {round(epoch_loss, 4)}")
        wandb.log({"epoch": epoch, f"ensemble/{i}/train_loss": epoch_loss})
    
    ensemble.append(net.state_dict())

    net.eval()
    with torch.no_grad():
        test_probs.append(torch.sigmoid(net(X_test)).numpy())

    logging.info(f"Сеть {i} обучена")
    print("сеть", i, "обучена")

probs2 = np.mean(test_probs, axis=0)

In [ ]:
auc_score = roc_auc_score(y_true, probs2)
logging.info(f"На тесте ROC_AUC: {auc_score}")
auc_score

In [ ]:
pre_score = average_precision_score(y_true, probs2)
logging.info(f"На тесте Precision: {pre_score}")
pre_score

In [ ]:
results = wandb.Table(columns=['model', 'test/avg_roc_auc', 'test/avg_precision'])
results.add_data("ensemble", auc_score, pre_score)
wandb.log({"results": results})

In [ ]:
import pickle

pickle.dump(ensemble, open("models/model_fraud_ensemble.pkl", 'wb'))
logging.info("Сохранили веса моделей ансамбля в папку models")

In [ ]:
artifact = wandb.Artifact(name="model_fraud_ensemble.pkl", type="model", description="Ансамбль моделей для определения Фрода")

artifact.add_file("models/model_fraud_ensemble.pkl")
artifact.add_file(log_file)
run.log_artifact(artifact)

In [ ]:
run.finish()

In [36]:
wandb.finish()

In [608]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_auc_score, confusion_matrix
import numpy as np

k_values = [3, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15]

best_k = None
best_roc_auc = -1
best_knn = None

X_train_np = X_train.numpy()
y_train_np = y_train.numpy().ravel()

X_val_np = X_val.numpy()
y_val_np = y_val.numpy().ravel()

X_test_np = X_test.numpy()
y_test_np = y_test.numpy().ravel()

for k in k_values:
    knn = KNeighborsClassifier(
        n_neighbors=k,
        weights="distance"
    )

    knn.fit(X_train_np, y_train_np)

    val_probs = knn.predict_proba(X_val_np)[:, 1]
    val_roc_auc = roc_auc_score(y_val_np, val_probs)

    print(f"k={k} | val ROC-AUC={val_roc_auc:.4f}")

    if val_roc_auc > best_roc_auc:
        best_roc_auc = val_roc_auc
        best_k = k
        best_knn = knn

print("\nЛучший KNN")
print("-" * 30)
print("best k:", best_k)
print("best val ROC-AUC:", round(best_roc_auc, 4))

k=3 | val ROC-AUC=0.7783
k=5 | val ROC-AUC=0.8613
k=7 | val ROC-AUC=0.8891
k=8 | val ROC-AUC=0.9312
k=9 | val ROC-AUC=0.9356
k=10 | val ROC-AUC=0.9371
k=11 | val ROC-AUC=0.9336
k=12 | val ROC-AUC=0.9298
k=13 | val ROC-AUC=0.9272
k=14 | val ROC-AUC=0.9328
k=15 | val ROC-AUC=0.9313

Лучший KNN
------------------------------
best k: 10
best val ROC-AUC: 0.9371

In [609]:
threshold = 0.5

test_probs = best_knn.predict_proba(X_test_np)[:, 1]
test_pred = (test_probs >= threshold).astype(int)

tn, fp, fn, tp = confusion_matrix(y_test_np, test_pred).ravel()

test_profit = tp * 5 - fp * 25 - fn * 5
test_roc_auc = roc_auc_score(y_test_np, test_probs)

print("\nKNN на test")
print("-" * 30)
print("k:", best_k)
print("threshold:", threshold)
print("ROC-AUC:", round(test_roc_auc, 4))
print("Profit:", test_profit)
print("TN, FP, FN, TP:", tn, fp, fn, tp)

KNN на test
------------------------------
k: 10
threshold: 0.5
ROC-AUC: 0.8991
Profit: -130230
TN, FP, FN, TP: 473649 745 23024 703