Работа с табличными данными

In [1]:
import pandas as pd
import numpy as np
import copy
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch
from dotenv import load_dotenv
import wandb
import os
import logging
import time
import torch.nn as nn
import random
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import *
import pickle

In [2]:
df = pd.read_csv('dataset/train.csv', sep="|")
df

,trustLevel,totalScanTimeInSeconds,grandTotal,lineItemVoids,scansWithoutRegistration,quantityModifications,scannedLineItemsPerSecond,valuePerSecond,lineItemVoidsPerPosition,fraud
0,5,1054,54.70,7,0,3,0.027514,0.051898,0.241379,0
1,3,108,27.36,5,2,4,0.129630,0.253333,0.357143,0
2,3,1516,62.16,3,10,5,0.008575,0.041003,0.230769,0
3,6,1791,92.31,8,4,4,0.016192,0.051541,0.275862,0
4,5,430,81.53,3,7,2,0.062791,0.189605,0.111111,0
...,...,...,...,...,...,...,...,...,...,...
1874,1,321,76.03,8,7,2,0.071651,0.236854,0.347826,0
1875,1,397,41.89,5,5,0,0.065491,0.105516,0.192308,1
1876,4,316,41.83,5,8,1,0.094937,0.132373,0.166667,0
1877,2,685,62.68,1,6,2,0.035036,0.091504,0.041667,0
1878,4,1140,38.03,2,2,3,0.016667,0.033360,0.105263,0

In [3]:
df.dtypes

trustLevel                     int64
totalScanTimeInSeconds         int64
grandTotal                   float64
lineItemVoids                  int64
scansWithoutRegistration       int64
quantityModifications          int64
scannedLineItemsPerSecond    float64
valuePerSecond               float64
lineItemVoidsPerPosition     float64
fraud                          int64
dtype: object

In [4]:
df.isna().sum()

trustLevel                   0
totalScanTimeInSeconds       0
grandTotal                   0
lineItemVoids                0
scansWithoutRegistration     0
quantityModifications        0
scannedLineItemsPerSecond    0
valuePerSecond               0
lineItemVoidsPerPosition     0
fraud                        0
dtype: int64

In [5]:
df.fraud.value_counts()

fraud
0    1775
1     104
Name: count, dtype: int64

In [6]:
y = df["fraud"]
X = df.drop(columns=["fraud"])

In [7]:
df.describe()

,trustLevel,totalScanTimeInSeconds,grandTotal,lineItemVoids,scansWithoutRegistration,quantityModifications,scannedLineItemsPerSecond,valuePerSecond,lineItemVoidsPerPosition,fraud
count,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000
mean,3.401809,932.153273,50.864492,5.469931,4.904204,2.525279,0.058138,0.201746,0.745404,0.055349
std,1.709404,530.144640,28.940202,3.451169,3.139697,1.695472,0.278512,1.242135,1.327241,0.228720
min,1.000000,2.000000,0.010000,0.000000,0.000000,0.000000,0.000548,0.000007,0.000000,0.000000
25%,2.000000,474.500000,25.965000,2.000000,2.000000,1.000000,0.008384,0.027787,0.160000,0.000000
50%,3.000000,932.000000,51.210000,5.000000,5.000000,3.000000,0.016317,0.054498,0.350000,0.000000
75%,5.000000,1397.000000,77.285000,8.000000,8.000000,4.000000,0.032594,0.107313,0.666667,0.000000
max,6.000000,1831.000000,99.960000,11.000000,10.000000,5.000000,6.666667,37.870000,11.000000,1.000000

## Предобработка данных

In [8]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [9]:
X_train.shape

(1503, 9)

In [10]:
X_val.shape

(376, 9)

In [11]:
X_test = pd.read_csv("dataset/test.csv", sep="|")
X_test

,trustLevel,totalScanTimeInSeconds,grandTotal,lineItemVoids,scansWithoutRegistration,quantityModifications,scannedLineItemsPerSecond,valuePerSecond,lineItemVoidsPerPosition
0,4,467,88.48,4,8,4,0.014989,0.189465,0.571429
1,3,1004,58.99,7,6,1,0.026892,0.058755,0.259259
2,1,162,14.00,4,5,4,0.006173,0.086420,4.000000
3,5,532,84.79,9,3,4,0.026316,0.159380,0.642857
4,5,890,42.16,4,0,0,0.021348,0.047371,0.210526
...,...,...,...,...,...,...,...,...,...
498116,4,783,59.10,2,2,0,0.012771,0.075479,0.200000
498117,1,278,98.90,9,5,4,0.050360,0.355755,0.642857
498118,3,300,5.41,6,6,4,0.030000,0.018033,0.666667
498119,2,1524,33.97,2,5,3,0.005906,0.022290,0.222222
498120,3,1456,56.97,11,7,2,0.019231,0.039128,0.392857

In [12]:
y_test = pd.read_csv("dataset/DMC-2019-realclass.csv", sep="|")["fraud"]
y_test.value_counts()

fraud
0    474394
1     23727
Name: count, dtype: int64

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [14]:
X_train = torch.tensor(X_train, dtype=torch.float32)
X_val = torch.tensor(X_val, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)

In [15]:
y_train = torch.tensor(y_train.values, dtype=torch.float32).reshape(-1, 1)
y_val = torch.tensor(y_val.values, dtype=torch.float32).reshape(-1, 1)
y_test = torch.tensor(y_test.values, dtype=torch.float32).reshape(-1, 1)

In [16]:
BATCH_SIZE = 64

In [17]:
train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(TensorDataset(X_val, y_val), batch_size=256)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=1024)

вес для редкого класса, чтобы модель его не пропускала

In [18]:
n_pos = (y_train == 1).sum()
n_neg = (y_train == 0).sum()

In [19]:
pos_weight = n_neg / n_pos
pos_weight

tensor(17.1084)

## Подготовка

In [20]:
load_dotenv()

WANDB_API_KEY = os.getenv("WANDB_API_KEY")
WANDB_PROJECT = os.getenv("WANDB_PROJECT", "gp5")
WANDB_ENTITY = os.getenv("WANDB_ENTITY")

In [21]:
wandb.login(key=WANDB_API_KEY)

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /Users/katya/.netrc
wandb: Currently logged in as: gigantina-ru (gigantina-ru-hse-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [22]:
def stop_logging():
    logger = logging.getLogger()
    for handler in logger.handlers:
        handler.flush()
        handler.close()
        logger.removeHandler(handler)

def new_log_file():
    stop_logging()
    timestamp = str(time.time()).replace('.', '_')
    log_file = f'part_2_{timestamp}.log'
    logging.basicConfig(
        filename=log_file,
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        force=True
    )
    logging.info("Начал логгировать новый запуск")
    return log_file

In [23]:
def evaluate_model(model, X, y, threshold=0.5, name="dataset"):
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED) 

    model.eval()

    with torch.no_grad():
        logits = model(X)
        probs = torch.sigmoid(logits)

    y_true = y.numpy().ravel()
    y_prob = probs.numpy().ravel()
    y_pred = (y_prob > threshold).astype(int)

    roc_auc = roc_auc_score(y_true, y_prob)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f05 = fbeta_score(y_true, y_pred, beta=0.5)

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    profit = tp * 5 - fp * 25 - fn * 5

    print(name)
    print("ROC-AUC:", round(roc_auc, 4))
    print("Precision:", round(precision, 4))
    print("Recall:", round(recall, 4))
    print("F0.5-score:", round(f05, 4))
    print("Profit:", profit)
    print()

    return {
        "dataset": name,
        "threshold": threshold,
        "roc_auc": roc_auc,
        "precision": precision,
        "recall": recall,
        "f05": f05,
        "profit": profit
    }

In [24]:
def train_model(model, train_loader, X_valid, y_valid, loss_fn, optimizer, 
    epochs=30, threshold=0.5,model_name="model"):
    
    SEED = 42
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED) 

    best_metric = -10**9
    best_epoch = 0
    best_state = None

    history = []
    logging.info(f"Начали обучение {model_name}")

    for epoch in range(1, epochs + 1):
        model.train()
        epoch_loss = 0

        for xb, yb in train_loader:
            optimizer.zero_grad()
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        epoch_loss /= len(train_loader)

        valid_metrics = evaluate_model(model, X_valid, y_valid, threshold=threshold,
            name=f"{model_name} | valid epoch {epoch}")
            
        current_metric = valid_metrics["roc_auc"]
        
        if current_metric > best_metric:
            best_metric = current_metric
            best_epoch = epoch
            best_state = copy.deepcopy(model.state_dict())

        print(f"Эпоха {epoch} | " f"Train Loss: {epoch_loss:.4f} | " 
        f"Val ROC-AUC: {valid_metrics['roc_auc']:.4f} | " f"Val Profit: {valid_metrics['profit']}")
        
        
        logging.info(
            f"Эпоха {epoch} | "
            f"Train Loss: {epoch_loss:.4f} | "
            f"Val ROC-AUC: {valid_metrics['roc_auc']:.4f} | "
            f"Val Profit: {valid_metrics['profit']}"
        )

        wandb.log({
             f"{model_name}/train_loss": epoch_loss,
             f"{model_name}/valid_profit": valid_metrics["profit"],
             f"{model_name}/valid_roc_auc": valid_metrics["roc_auc"],
             f"{model_name}/valid_precision": valid_metrics["precision"],
             f"{model_name}/valid_recall": valid_metrics["recall"],
             f"{model_name}/valid_f05": valid_metrics["f05"],
         })

    model.load_state_dict(best_state)

    print()
    print(f"Лучшая эпоха для {model_name}: {best_epoch}")
    print(f"Лучший ROC-AUC: {best_metric}")
    logging.info("Закончили обучение")
    logging.info(f"Лучшая эпоха для {model_name}: {best_epoch}")
    logging.info(f"Лучший ROC-AUC: {best_metric}")

    return model

In [25]:
def save_results(model, name, log_file, run):
    train_metrics = evaluate_model(model, X_train, y_train, threshold=0.5, name="Train")
    test_metrics = evaluate_model(model, X_test, y_test, threshold=0.5, name="Test")
    pickle.dump(model.state_dict(), open(f"models/{name}.pkl", 'wb'))
    logging.info("Сохранили веса модели в папку models")

    metric_keys = list(train_metrics.keys())

    table = wandb.Table(columns=metric_keys)
    table.add_data(*[train_metrics[i] for i in metric_keys])
    table.add_data(*[test_metrics[i] for i in metric_keys])
    wandb.log({'results': table})
    artifact = wandb.Artifact(name=name, type="model", description=f"Тест логгирования модели: {name}")

    artifact.add_file(f"models/{name}.pkl")
    artifact.add_file(log_file)
    run.log_artifact(artifact)

## model_1_baseline

In [48]:
EPOCHS = 30
SEED = 42

Отключаем логирование на переборе гиперпараметров

In [49]:
wandb.init(mode="disabled")
results = []
for LR in [0.05, 0.03, 0.01, 0.005, 0.002, 0.0001]:
        random.seed(SEED)
        np.random.seed(SEED)
        torch.manual_seed(SEED) 

        model_1 = nn.Sequential(
            nn.Linear(9, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
        )

        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.Adam(model_1.parameters(), lr=LR)

        model_1 = train_model(
            model=model_1,
            train_loader=train_loader,
            X_valid=X_val,
            y_valid=y_val,
            loss_fn=loss_fn,
            optimizer=optimizer,
            epochs=EPOCHS,
            threshold=0.5,
            model_name="model_1_baseline"
        )

        val = evaluate_model(model_1, X_val, y_val, threshold=0.5, name="val")
        results.append({"lr": LR, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_1_baseline | valid epoch 1
ROC-AUC: 0.9363
Precision: 0.2769
Recall: 0.8571
F0.5-score: 0.3203
Profit: -1100

Эпоха 1 | Train Loss: 0.8771 | Val ROC-AUC: 0.9363 | Val Profit: -1100
model_1_baseline | valid epoch 2
ROC-AUC: 0.9608
Precision: 0.2019
Recall: 1.0
F0.5-score: 0.2403
Profit: -1970

Эпоха 2 | Train Loss: 0.6035 | Val ROC-AUC: 0.9608 | Val Profit: -1970
model_1_baseline | valid epoch 3
ROC-AUC: 0.972
Precision: 0.2283
Recall: 1.0
F0.5-score: 0.2699
Profit: -1670

Эпоха 3 | Train Loss: 0.4833 | Val ROC-AUC: 0.9720 | Val Profit: -1670
model_1_baseline | valid epoch 4
ROC-AUC: 0.9714
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 4 | Train Loss: 0.3636 | Val ROC-AUC: 0.9714 | Val Profit: -970
model_1_baseline | valid epoch 5
ROC-AUC: 0.9771
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 5 | Train Loss: 0.3314 | Val ROC-AUC: 0.9771 | Val Profit: -895
model_1_baseline | valid epoch 6
ROC-AUC: 0.9685
Precision: 0.3387
Recall: 1.0
F0.5-score: 0.3903
Profit: -920

Эпоха 6 | Train Loss: 0.2844 | Val ROC-AUC: 0.9685 | Val Profit: -920
model_1_baseline | valid epoch 7
ROC-AUC: 0.9752
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 7 | Train Loss: 0.3279 | Val ROC-AUC: 0.9752 | Val Profit: -1195
model_1_baseline | valid epoch 8
ROC-AUC: 0.9764
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 8 | Train Loss: 0.2850 | Val ROC-AUC: 0.9764 | Val Profit: -565
model_1_baseline | valid epoch 9
ROC-AUC: 0.9788
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 9 | Train Loss: 0.2545 | Val ROC-AUC: 0.9788 | Val Profit: -620
model_1_baseline | valid epoch 10
ROC-AUC: 0.9756
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 10 | Train Loss: 0.2344 | Val ROC-AUC: 0.9756 | Val Profit: -845
model_1_baseline | valid epoch 11
ROC-AUC: 0.9831
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 11 | Train Loss: 0.2292 | Val ROC-AUC: 0.9831 | Val Profit: -430
model_1_baseline | valid epoch 12
ROC-AUC: 0.9789
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 12 | Train Loss: 0.2582 | Val ROC-AUC: 0.9789 | Val Profit: -505
model_1_baseline | valid epoch 13
ROC-AUC: 0.9767
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 13 | Train Loss: 0.3783 | Val ROC-AUC: 0.9767 | Val Profit: -1120
model_1_baseline | valid epoch 14
ROC-AUC: 0.9823
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 14 | Train Loss: 0.3154 | Val ROC-AUC: 0.9823 | Val Profit: -845
model_1_baseline | valid epoch 15
ROC-AUC: 0.9828
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 15 | Train Loss: 0.2113 | Val ROC-AUC: 0.9828 | Val Profit: -465
model_1_baseline | valid epoch 16
ROC-AUC: 0.9839
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 16 | Train Loss: 0.2411 | Val ROC-AUC: 0.9839 | Val Profit: -630
model_1_baseline | valid epoch 17
ROC-AUC: 0.9882
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 17 | Train Loss: 0.1785 | Val ROC-AUC: 0.9882 | Val Profit: -355
model_1_baseline | valid epoch 18
ROC-AUC: 0.9855
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 18 | Train Loss: 0.1822 | Val ROC-AUC: 0.9855 | Val Profit: -380
model_1_baseline | valid epoch 19
ROC-AUC: 0.985
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 19 | Train Loss: 0.2223 | Val ROC-AUC: 0.9850 | Val Profit: -595
model_1_baseline | valid epoch 20
ROC-AUC: 0.9728
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 20 | Train Loss: 0.3345 | Val ROC-AUC: 0.9728 | Val Profit: -820
model_1_baseline | valid epoch 21
ROC-AUC: 0.9824
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 21 | Train Loss: 0.2270 | Val ROC-AUC: 0.9824 | Val Profit: -570
model_1_baseline | valid epoch 22
ROC-AUC: 0.9717
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 22 | Train Loss: 0.2771 | Val ROC-AUC: 0.9717 | Val Profit: -945
model_1_baseline | valid epoch 23
ROC-AUC: 0.985
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 23 | Train Loss: 0.2100 | Val ROC-AUC: 0.9850 | Val Profit: -455
model_1_baseline | valid epoch 24
ROC-AUC: 0.9748
Precision: 0.3958
Recall: 0.9048
F0.5-score: 0.446
Profit: -640

Эпоха 24 | Train Loss: 0.2260 | Val ROC-AUC: 0.9748 | Val Profit: -640
model_1_baseline | valid epoch 25
ROC-AUC: 0.9854
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 25 | Train Loss: 0.1999 | Val ROC-AUC: 0.9854 | Val Profit: -570
model_1_baseline | valid epoch 26
ROC-AUC: 0.9826
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 26 | Train Loss: 0.1467 | Val ROC-AUC: 0.9826 | Val Profit: -430
model_1_baseline | valid epoch 27
ROC-AUC: 0.967
Precision: 0.3125
Recall: 0.9524
F0.5-score: 0.361
Profit: -1005

Эпоха 27 | Train Loss: 0.2774 | Val ROC-AUC: 0.9670 | Val Profit: -1005
model_1_baseline | valid epoch 28
ROC-AUC: 0.9889
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 28 | Train Loss: 0.2561 | Val ROC-AUC: 0.9889 | Val Profit: -970
model_1_baseline | valid epoch 29
ROC-AUC: 0.9889
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 29 | Train Loss: 0.1821 | Val ROC-AUC: 0.9889 | Val Profit: -520
model_1_baseline | valid epoch 30
ROC-AUC: 0.9771
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 30 | Train Loss: 0.1428 | Val ROC-AUC: 0.9771 | Val Profit: -520

Лучшая эпоха для model_1_baseline: 29
Лучший ROC-AUC: 0.9888665325285044
val
ROC-AUC: 0.9889
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

model_1_baseline | valid epoch 1
ROC-AUC: 0.9355
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 1 | Train Loss: 1.0648 | Val ROC-AUC: 0.9355 | Val Profit: -1520
model_1_baseline | valid epoch 2
ROC-AUC: 0.9681
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 2 | Train Loss: 0.4834 | Val ROC-AUC: 0.9681 | Val Profit: -1245
model_1_baseline | valid epoch 3
ROC-AUC: 0.9658
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 3 | Train Loss: 0.3557 | Val ROC-AUC: 0.9658 | Val Profit: -1220
model_1_baseline | valid epoch 4
ROC-AUC: 0.9679
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 4 | Train Loss: 0.3364 | Val ROC-AUC: 0.9679 | Val Profit: -930
model_1_baseline | valid epoch 5
ROC-AUC: 0.9771
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 5 | Train Loss: 0.2914 | Val ROC-AUC: 0.9771 | Val Profit: -945
model_1_baseline | valid epoch 6
ROC-AUC: 0.9779
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 6 | Train Loss: 0.2680 | Val ROC-AUC: 0.9779 | Val Profit: -945
model_1_baseline | valid epoch 7
ROC-AUC: 0.9775
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 7 | Train Loss: 0.2516 | Val ROC-AUC: 0.9775 | Val Profit: -945
model_1_baseline | valid epoch 8
ROC-AUC: 0.982
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 8 | Train Loss: 0.2486 | Val ROC-AUC: 0.9820 | Val Profit: -745
model_1_baseline | valid epoch 9
ROC-AUC: 0.9839
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 9 | Train Loss: 0.1938 | Val ROC-AUC: 0.9839 | Val Profit: -290
model_1_baseline | valid epoch 10
ROC-AUC: 0.981
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 10 | Train Loss: 0.2820 | Val ROC-AUC: 0.9810 | Val Profit: -845
model_1_baseline | valid epoch 11
ROC-AUC: 0.984
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 11 | Train Loss: 0.2472 | Val ROC-AUC: 0.9840 | Val Profit: -695
model_1_baseline | valid epoch 12
ROC-AUC: 0.9859
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 12 | Train Loss: 0.2059 | Val ROC-AUC: 0.9859 | Val Profit: -570
model_1_baseline | valid epoch 13
ROC-AUC: 0.9883
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 13 | Train Loss: 0.1622 | Val ROC-AUC: 0.9883 | Val Profit: -670
model_1_baseline | valid epoch 14
ROC-AUC: 0.9863
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 14 | Train Loss: 0.1844 | Val ROC-AUC: 0.9863 | Val Profit: -770
model_1_baseline | valid epoch 15
ROC-AUC: 0.9862
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 15 | Train Loss: 0.2195 | Val ROC-AUC: 0.9862 | Val Profit: -695
model_1_baseline | valid epoch 16
ROC-AUC: 0.9832
Precision: 0.525
Recall: 1.0
F0.5-score: 0.5801
Profit: -370

Эпоха 16 | Train Loss: 0.1711 | Val ROC-AUC: 0.9832 | Val Profit: -370
model_1_baseline | valid epoch 17
ROC-AUC: 0.9795
Precision: 0.5
Recall: 1.0
F0.5-score: 0.5556
Profit: -420

Эпоха 17 | Train Loss: 0.1683 | Val ROC-AUC: 0.9795 | Val Profit: -420
model_1_baseline | valid epoch 18
ROC-AUC: 0.9854
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 18 | Train Loss: 0.1629 | Val ROC-AUC: 0.9854 | Val Profit: -470
model_1_baseline | valid epoch 19
ROC-AUC: 0.9838
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 19 | Train Loss: 0.1859 | Val ROC-AUC: 0.9838 | Val Profit: -695
model_1_baseline | valid epoch 20
ROC-AUC: 0.9844
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 20 | Train Loss: 0.2577 | Val ROC-AUC: 0.9844 | Val Profit: -430
model_1_baseline | valid epoch 21
ROC-AUC: 0.9823
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 21 | Train Loss: 0.2078 | Val ROC-AUC: 0.9823 | Val Profit: -530
model_1_baseline | valid epoch 22
ROC-AUC: 0.9907
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 22 | Train Loss: 0.1629 | Val ROC-AUC: 0.9907 | Val Profit: -520
model_1_baseline | valid epoch 23
ROC-AUC: 0.9897
Precision: 0.525
Recall: 1.0
F0.5-score: 0.5801
Profit: -370

Эпоха 23 | Train Loss: 0.1305 | Val ROC-AUC: 0.9897 | Val Profit: -370
model_1_baseline | valid epoch 24
ROC-AUC: 0.9905
Precision: 0.5
Recall: 1.0
F0.5-score: 0.5556
Profit: -420

Эпоха 24 | Train Loss: 0.1358 | Val ROC-AUC: 0.9905 | Val Profit: -420
model_1_baseline | valid epoch 25
ROC-AUC: 0.9921
Precision: 0.5385
Recall: 1.0
F0.5-score: 0.5932
Profit: -345

Эпоха 25 | Train Loss: 0.1242 | Val ROC-AUC: 0.9921 | Val Profit: -345
model_1_baseline | valid epoch 26
ROC-AUC: 0.9866
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 26 | Train Loss: 0.1149 | Val ROC-AUC: 0.9866 | Val Profit: -330
model_1_baseline | valid epoch 27
ROC-AUC: 0.9886
Precision: 0.5833
Recall: 1.0
F0.5-score: 0.6364
Profit: -270

Эпоха 27 | Train Loss: 0.1147 | Val ROC-AUC: 0.9886 | Val Profit: -270
model_1_baseline | valid epoch 28
ROC-AUC: 0.9858
Precision: 0.5833
Recall: 1.0
F0.5-score: 0.6364
Profit: -270

Эпоха 28 | Train Loss: 0.1174 | Val ROC-AUC: 0.9858 | Val Profit: -270
model_1_baseline | valid epoch 29
ROC-AUC: 0.9842
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 29 | Train Loss: 0.2133 | Val ROC-AUC: 0.9842 | Val Profit: -430
model_1_baseline | valid epoch 30
ROC-AUC: 0.9905
Precision: 0.5676
Recall: 1.0
F0.5-score: 0.6213
Profit: -295

Эпоха 30 | Train Loss: 0.1998 | Val ROC-AUC: 0.9905 | Val Profit: -295

Лучшая эпоха для model_1_baseline: 25
Лучший ROC-AUC: 0.9920858484238765
val
ROC-AUC: 0.9921
Precision: 0.5385
Recall: 1.0
F0.5-score: 0.5932
Profit: -345

model_1_baseline | valid epoch 1
ROC-AUC: 0.9411
Precision: 0.25
Recall: 0.0952
F0.5-score: 0.1887
Profit: -235

Эпоха 1 | Train Loss: 1.2482 | Val ROC-AUC: 0.9411 | Val Profit: -235
model_1_baseline | valid epoch 2
ROC-AUC: 0.9553
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 2 | Train Loss: 0.7541 | Val ROC-AUC: 0.9553 | Val Profit: -1770
model_1_baseline | valid epoch 3
ROC-AUC: 0.972
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 3 | Train Loss: 0.4640 | Val ROC-AUC: 0.9720 | Val Profit: -1420
model_1_baseline | valid epoch 4
ROC-AUC: 0.9728
Precision: 0.2625
Recall: 1.0
F0.5-score: 0.3079
Profit: -1370

Эпоха 4 | Train Loss: 0.3839 | Val ROC-AUC: 0.9728 | Val Profit: -1370
model_1_baseline | valid epoch 5
ROC-AUC: 0.972
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 5 | Train Loss: 0.3468 | Val ROC-AUC: 0.9720 | Val Profit: -1270
model_1_baseline | valid epoch 6
ROC-AUC: 0.9741
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 6 | Train Loss: 0.3189 | Val ROC-AUC: 0.9741 | Val Profit: -1220
model_1_baseline | valid epoch 7
ROC-AUC: 0.9738
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 7 | Train Loss: 0.2919 | Val ROC-AUC: 0.9738 | Val Profit: -1070
model_1_baseline | valid epoch 8
ROC-AUC: 0.9744
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 8 | Train Loss: 0.2605 | Val ROC-AUC: 0.9744 | Val Profit: -970
model_1_baseline | valid epoch 9
ROC-AUC: 0.9764
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 9 | Train Loss: 0.2485 | Val ROC-AUC: 0.9764 | Val Profit: -945
model_1_baseline | valid epoch 10
ROC-AUC: 0.9768
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 10 | Train Loss: 0.2287 | Val ROC-AUC: 0.9768 | Val Profit: -820
model_1_baseline | valid epoch 11
ROC-AUC: 0.9777
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 11 | Train Loss: 0.2115 | Val ROC-AUC: 0.9777 | Val Profit: -695
model_1_baseline | valid epoch 12
ROC-AUC: 0.9763
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 12 | Train Loss: 0.1939 | Val ROC-AUC: 0.9763 | Val Profit: -720
model_1_baseline | valid epoch 13
ROC-AUC: 0.9799
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 13 | Train Loss: 0.1913 | Val ROC-AUC: 0.9799 | Val Profit: -620
model_1_baseline | valid epoch 14
ROC-AUC: 0.9788
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 14 | Train Loss: 0.1819 | Val ROC-AUC: 0.9788 | Val Profit: -695
model_1_baseline | valid epoch 15
ROC-AUC: 0.9842
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 15 | Train Loss: 0.1805 | Val ROC-AUC: 0.9842 | Val Profit: -470
model_1_baseline | valid epoch 16
ROC-AUC: 0.9812
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 16 | Train Loss: 0.1615 | Val ROC-AUC: 0.9812 | Val Profit: -645
model_1_baseline | valid epoch 17
ROC-AUC: 0.9832
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 17 | Train Loss: 0.1667 | Val ROC-AUC: 0.9832 | Val Profit: -495
model_1_baseline | valid epoch 18
ROC-AUC: 0.9826
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 18 | Train Loss: 0.1447 | Val ROC-AUC: 0.9826 | Val Profit: -505
model_1_baseline | valid epoch 19
ROC-AUC: 0.9855
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 19 | Train Loss: 0.1497 | Val ROC-AUC: 0.9855 | Val Profit: -495
model_1_baseline | valid epoch 20
ROC-AUC: 0.9801
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 20 | Train Loss: 0.1397 | Val ROC-AUC: 0.9801 | Val Profit: -440
model_1_baseline | valid epoch 21
ROC-AUC: 0.9811
Precision: 0.4884
Recall: 1.0
F0.5-score: 0.544
Profit: -445

Эпоха 21 | Train Loss: 0.1537 | Val ROC-AUC: 0.9811 | Val Profit: -445
model_1_baseline | valid epoch 22
ROC-AUC: 0.9867
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 22 | Train Loss: 0.1514 | Val ROC-AUC: 0.9867 | Val Profit: -330
model_1_baseline | valid epoch 23
ROC-AUC: 0.9832
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 23 | Train Loss: 0.1205 | Val ROC-AUC: 0.9832 | Val Profit: -480
model_1_baseline | valid epoch 24
ROC-AUC: 0.986
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 24 | Train Loss: 0.1452 | Val ROC-AUC: 0.9860 | Val Profit: -570
model_1_baseline | valid epoch 25
ROC-AUC: 0.9867
Precision: 0.5385
Recall: 1.0
F0.5-score: 0.5932
Profit: -345

Эпоха 25 | Train Loss: 0.1412 | Val ROC-AUC: 0.9867 | Val Profit: -345
model_1_baseline | valid epoch 26
ROC-AUC: 0.9854
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 26 | Train Loss: 0.1226 | Val ROC-AUC: 0.9854 | Val Profit: -380
model_1_baseline | valid epoch 27
ROC-AUC: 0.9756
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 27 | Train Loss: 0.1269 | Val ROC-AUC: 0.9756 | Val Profit: -490
model_1_baseline | valid epoch 28
ROC-AUC: 0.9783
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 28 | Train Loss: 0.1541 | Val ROC-AUC: 0.9783 | Val Profit: -580
model_1_baseline | valid epoch 29
ROC-AUC: 0.9831
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

Эпоха 29 | Train Loss: 0.1602 | Val ROC-AUC: 0.9831 | Val Profit: -315
model_1_baseline | valid epoch 30
ROC-AUC: 0.9885
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 30 | Train Loss: 0.1275 | Val ROC-AUC: 0.9885 | Val Profit: -570

Лучшая эпоха для model_1_baseline: 30
Лучший ROC-AUC: 0.9884641180415827
val
ROC-AUC: 0.9885
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

model_1_baseline | valid epoch 1
ROC-AUC: 0.8977
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.2970 | Val ROC-AUC: 0.8977 | Val Profit: -105
model_1_baseline | valid epoch 2
ROC-AUC: 0.9392
Precision: 0.322
Recall: 0.9048
F0.5-score: 0.3696
Profit: -915

Эпоха 2 | Train Loss: 1.1195 | Val ROC-AUC: 0.9392 | Val Profit: -915

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_1_baseline | valid epoch 3
ROC-AUC: 0.9548
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 3 | Train Loss: 0.7432 | Val ROC-AUC: 0.9548 | Val Profit: -1620
model_1_baseline | valid epoch 4
ROC-AUC: 0.9651
Precision: 0.236
Recall: 1.0
F0.5-score: 0.2785
Profit: -1595

Эпоха 4 | Train Loss: 0.4980 | Val ROC-AUC: 0.9651 | Val Profit: -1595
model_1_baseline | valid epoch 5
ROC-AUC: 0.9671
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 5 | Train Loss: 0.4175 | Val ROC-AUC: 0.9671 | Val Profit: -1495
model_1_baseline | valid epoch 6
ROC-AUC: 0.9677
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 6 | Train Loss: 0.3743 | Val ROC-AUC: 0.9677 | Val Profit: -1345
model_1_baseline | valid epoch 7
ROC-AUC: 0.97
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 7 | Train Loss: 0.3403 | Val ROC-AUC: 0.9700 | Val Profit: -1245
model_1_baseline | valid epoch 8
ROC-AUC: 0.9724
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 8 | Train Loss: 0.3139 | Val ROC-AUC: 0.9724 | Val Profit: -1195
model_1_baseline | valid epoch 9
ROC-AUC: 0.9748
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 9 | Train Loss: 0.2896 | Val ROC-AUC: 0.9748 | Val Profit: -1145
model_1_baseline | valid epoch 10
ROC-AUC: 0.9761
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 10 | Train Loss: 0.2710 | Val ROC-AUC: 0.9761 | Val Profit: -1020
model_1_baseline | valid epoch 11
ROC-AUC: 0.9772
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 11 | Train Loss: 0.2535 | Val ROC-AUC: 0.9772 | Val Profit: -995
model_1_baseline | valid epoch 12
ROC-AUC: 0.9787
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 12 | Train Loss: 0.2384 | Val ROC-AUC: 0.9787 | Val Profit: -895
model_1_baseline | valid epoch 13
ROC-AUC: 0.9793
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 13 | Train Loss: 0.2254 | Val ROC-AUC: 0.9793 | Val Profit: -795
model_1_baseline | valid epoch 14
ROC-AUC: 0.9801
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 14 | Train Loss: 0.2125 | Val ROC-AUC: 0.9801 | Val Profit: -770
model_1_baseline | valid epoch 15
ROC-AUC: 0.9804
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 15 | Train Loss: 0.2021 | Val ROC-AUC: 0.9804 | Val Profit: -745
model_1_baseline | valid epoch 16
ROC-AUC: 0.9815
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 16 | Train Loss: 0.1917 | Val ROC-AUC: 0.9815 | Val Profit: -695
model_1_baseline | valid epoch 17
ROC-AUC: 0.9822
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 17 | Train Loss: 0.1817 | Val ROC-AUC: 0.9822 | Val Profit: -570
model_1_baseline | valid epoch 18
ROC-AUC: 0.9836
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 18 | Train Loss: 0.1746 | Val ROC-AUC: 0.9836 | Val Profit: -645
model_1_baseline | valid epoch 19
ROC-AUC: 0.984
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 19 | Train Loss: 0.1655 | Val ROC-AUC: 0.9840 | Val Profit: -495
model_1_baseline | valid epoch 20
ROC-AUC: 0.9843
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 20 | Train Loss: 0.1572 | Val ROC-AUC: 0.9843 | Val Profit: -470
model_1_baseline | valid epoch 21
ROC-AUC: 0.9846
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 21 | Train Loss: 0.1510 | Val ROC-AUC: 0.9846 | Val Profit: -470
model_1_baseline | valid epoch 22
ROC-AUC: 0.9848
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 22 | Train Loss: 0.1435 | Val ROC-AUC: 0.9848 | Val Profit: -470
model_1_baseline | valid epoch 23
ROC-AUC: 0.985
Precision: 0.5
Recall: 1.0
F0.5-score: 0.5556
Profit: -420

Эпоха 23 | Train Loss: 0.1391 | Val ROC-AUC: 0.9850 | Val Profit: -420
model_1_baseline | valid epoch 24
ROC-AUC: 0.9856
Precision: 0.4884
Recall: 1.0
F0.5-score: 0.544
Profit: -445

Эпоха 24 | Train Loss: 0.1336 | Val ROC-AUC: 0.9856 | Val Profit: -445
model_1_baseline | valid epoch 25
ROC-AUC: 0.9855
Precision: 0.5
Recall: 1.0
F0.5-score: 0.5556
Profit: -420

Эпоха 25 | Train Loss: 0.1268 | Val ROC-AUC: 0.9855 | Val Profit: -420
model_1_baseline | valid epoch 26
ROC-AUC: 0.9859
Precision: 0.5122
Recall: 1.0
F0.5-score: 0.5676
Profit: -395

Эпоха 26 | Train Loss: 0.1229 | Val ROC-AUC: 0.9859 | Val Profit: -395
model_1_baseline | valid epoch 27
ROC-AUC: 0.9862
Precision: 0.5122
Recall: 1.0
F0.5-score: 0.5676
Profit: -395

Эпоха 27 | Train Loss: 0.1194 | Val ROC-AUC: 0.9862 | Val Profit: -395
model_1_baseline | valid epoch 28
ROC-AUC: 0.9869
Precision: 0.5122
Recall: 1.0
F0.5-score: 0.5676
Profit: -395

Эпоха 28 | Train Loss: 0.1163 | Val ROC-AUC: 0.9869 | Val Profit: -395
model_1_baseline | valid epoch 29
ROC-AUC: 0.9874
Precision: 0.5122
Recall: 1.0
F0.5-score: 0.5676
Profit: -395

Эпоха 29 | Train Loss: 0.1121 | Val ROC-AUC: 0.9874 | Val Profit: -395
model_1_baseline | valid epoch 30
ROC-AUC: 0.9871
Precision: 0.5
Recall: 0.9524
F0.5-score: 0.5525
Profit: -405

Эпоха 30 | Train Loss: 0.1082 | Val ROC-AUC: 0.9871 | Val Profit: -405

Лучшая эпоха для model_1_baseline: 29
Лучший ROC-AUC: 0.9873910127431254
val
ROC-AUC: 0.9874
Precision: 0.5122
Recall: 1.0
F0.5-score: 0.5676
Profit: -395

model_1_baseline | valid epoch 1
ROC-AUC: 0.8626
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3201 | Val ROC-AUC: 0.8626 | Val Profit: -105
model_1_baseline | valid epoch 2
ROC-AUC: 0.8873
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 1.2826 | Val ROC-AUC: 0.8873 | Val Profit: -105
model_1_baseline | valid epoch 3
ROC-AUC: 0.9211
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 1.2138 | Val ROC-AUC: 0.9211 | Val Profit: -105
model_1_baseline | valid epoch 4
ROC-AUC: 0.9363
Precision: 0.3462
Recall: 0.8571
F0.5-score: 0.393
Profit: -775

Эпоха 4 | Train Loss: 1.0774 | Val ROC-AUC: 0.9363 | Val Profit: -775
model_1_baseline | valid epoch 5
ROC-AUC: 0.9477
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 5 | Train Loss: 0.8859 | Val ROC-AUC: 0.9477 | Val Profit: -1245
model_1_baseline | valid epoch 6
ROC-AUC: 0.9539
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 6 | Train Loss: 0.7036 | Val ROC-AUC: 0.9539 | Val Profit: -1495
model_1_baseline | valid epoch 7
ROC-AUC: 0.9591
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 7 | Train Loss: 0.5755 | Val ROC-AUC: 0.9591 | Val Profit: -1495
model_1_baseline | valid epoch 8
ROC-AUC: 0.9622
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 8 | Train Loss: 0.4992 | Val ROC-AUC: 0.9622 | Val Profit: -1470
model_1_baseline | valid epoch 9
ROC-AUC: 0.9657
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 9 | Train Loss: 0.4507 | Val ROC-AUC: 0.9657 | Val Profit: -1420
model_1_baseline | valid epoch 10
ROC-AUC: 0.9677
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 10 | Train Loss: 0.4160 | Val ROC-AUC: 0.9677 | Val Profit: -1420
model_1_baseline | valid epoch 11
ROC-AUC: 0.9693
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 11 | Train Loss: 0.3885 | Val ROC-AUC: 0.9693 | Val Profit: -1295
model_1_baseline | valid epoch 12
ROC-AUC: 0.9702
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 12 | Train Loss: 0.3652 | Val ROC-AUC: 0.9702 | Val Profit: -1170
model_1_baseline | valid epoch 13
ROC-AUC: 0.9704
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 13 | Train Loss: 0.3463 | Val ROC-AUC: 0.9704 | Val Profit: -1145
model_1_baseline | valid epoch 14
ROC-AUC: 0.9712
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 14 | Train Loss: 0.3299 | Val ROC-AUC: 0.9712 | Val Profit: -1120
model_1_baseline | valid epoch 15
ROC-AUC: 0.9728
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 15 | Train Loss: 0.3154 | Val ROC-AUC: 0.9728 | Val Profit: -1095
model_1_baseline | valid epoch 16
ROC-AUC: 0.9738
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 16 | Train Loss: 0.3025 | Val ROC-AUC: 0.9738 | Val Profit: -1045
model_1_baseline | valid epoch 17
ROC-AUC: 0.9745
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 17 | Train Loss: 0.2907 | Val ROC-AUC: 0.9745 | Val Profit: -1045
model_1_baseline | valid epoch 18
ROC-AUC: 0.976
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 18 | Train Loss: 0.2794 | Val ROC-AUC: 0.9760 | Val Profit: -995
model_1_baseline | valid epoch 19
ROC-AUC: 0.976
Precision: 0.3387
Recall: 1.0
F0.5-score: 0.3903
Profit: -920

Эпоха 19 | Train Loss: 0.2695 | Val ROC-AUC: 0.9760 | Val Profit: -920
model_1_baseline | valid epoch 20
ROC-AUC: 0.9763
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 20 | Train Loss: 0.2603 | Val ROC-AUC: 0.9763 | Val Profit: -845
model_1_baseline | valid epoch 21
ROC-AUC: 0.9763
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 21 | Train Loss: 0.2517 | Val ROC-AUC: 0.9763 | Val Profit: -845
model_1_baseline | valid epoch 22
ROC-AUC: 0.9768
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 22 | Train Loss: 0.2436 | Val ROC-AUC: 0.9768 | Val Profit: -845
model_1_baseline | valid epoch 23
ROC-AUC: 0.9771
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 23 | Train Loss: 0.2362 | Val ROC-AUC: 0.9771 | Val Profit: -795
model_1_baseline | valid epoch 24
ROC-AUC: 0.9768
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 24 | Train Loss: 0.2294 | Val ROC-AUC: 0.9768 | Val Profit: -745
model_1_baseline | valid epoch 25
ROC-AUC: 0.9776
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 25 | Train Loss: 0.2230 | Val ROC-AUC: 0.9776 | Val Profit: -720
model_1_baseline | valid epoch 26
ROC-AUC: 0.9776
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 26 | Train Loss: 0.2165 | Val ROC-AUC: 0.9776 | Val Profit: -720
model_1_baseline | valid epoch 27
ROC-AUC: 0.9787
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 27 | Train Loss: 0.2114 | Val ROC-AUC: 0.9787 | Val Profit: -705
model_1_baseline | valid epoch 28
ROC-AUC: 0.9788
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 28 | Train Loss: 0.2056 | Val ROC-AUC: 0.9788 | Val Profit: -705
model_1_baseline | valid epoch 29
ROC-AUC: 0.9788
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 29 | Train Loss: 0.2003 | Val ROC-AUC: 0.9788 | Val Profit: -705
model_1_baseline | valid epoch 30
ROC-AUC: 0.9791
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 30 | Train Loss: 0.1953 | Val ROC-AUC: 0.9791 | Val Profit: -705

Лучшая эпоха для model_1_baseline: 30
Лучший ROC-AUC: 0.9790744466800805
val
ROC-AUC: 0.9791
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

model_1_baseline | valid epoch 1
ROC-AUC: 0.6702
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3347 | Val ROC-AUC: 0.6702 | Val Profit: -105
model_1_baseline | valid epoch 2
ROC-AUC: 0.6936
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 1.3326 | Val ROC-AUC: 0.6936 | Val Profit: -105
model_1_baseline | valid epoch 3
ROC-AUC: 0.7123
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 1.3305 | Val ROC-AUC: 0.7123 | Val Profit: -105
model_1_baseline | valid epoch 4
ROC-AUC: 0.7319
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 1.3286 | Val ROC-AUC: 0.7319 | Val Profit: -105
model_1_baseline | valid epoch 5
ROC-AUC: 0.7497
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 1.3267 | Val ROC-AUC: 0.7497 | Val Profit: -105
model_1_baseline | valid epoch 6
ROC-AUC: 0.7667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 1.3249 | Val ROC-AUC: 0.7667 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_1_baseline | valid epoch 7
ROC-AUC: 0.7803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 1.3232 | Val ROC-AUC: 0.7803 | Val Profit: -105
model_1_baseline | valid epoch 8
ROC-AUC: 0.7918
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 1.3215 | Val ROC-AUC: 0.7918 | Val Profit: -105
model_1_baseline | valid epoch 9
ROC-AUC: 0.8013
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 1.3198 | Val ROC-AUC: 0.8013 | Val Profit: -105
model_1_baseline | valid epoch 10
ROC-AUC: 0.8097
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 1.3181 | Val ROC-AUC: 0.8097 | Val Profit: -105
model_1_baseline | valid epoch 11
ROC-AUC: 0.8193
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 1.3163 | Val ROC-AUC: 0.8193 | Val Profit: -105
model_1_baseline | valid epoch 12
ROC-AUC: 0.8284
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 1.3145 | Val ROC-AUC: 0.8284 | Val Profit: -105
model_1_baseline | valid epoch 13
ROC-AUC: 0.8347
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 1.3127 | Val ROC-AUC: 0.8347 | Val Profit: -105
model_1_baseline | valid epoch 14
ROC-AUC: 0.8406
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 1.3109 | Val ROC-AUC: 0.8406 | Val Profit: -105
model_1_baseline | valid epoch 15
ROC-AUC: 0.8451
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 1.3090 | Val ROC-AUC: 0.8451 | Val Profit: -105
model_1_baseline | valid epoch 16
ROC-AUC: 0.8492
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 1.3070 | Val ROC-AUC: 0.8492 | Val Profit: -105
model_1_baseline | valid epoch 17
ROC-AUC: 0.8534
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 1.3050 | Val ROC-AUC: 0.8534 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_1_baseline | valid epoch 18
ROC-AUC: 0.8565
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 1.3029 | Val ROC-AUC: 0.8565 | Val Profit: -105
model_1_baseline | valid epoch 19
ROC-AUC: 0.8596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 1.3007 | Val ROC-AUC: 0.8596 | Val Profit: -105
model_1_baseline | valid epoch 20
ROC-AUC: 0.8633
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 1.2985 | Val ROC-AUC: 0.8633 | Val Profit: -105
model_1_baseline | valid epoch 21
ROC-AUC: 0.8611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 1.2962 | Val ROC-AUC: 0.8611 | Val Profit: -105
model_1_baseline | valid epoch 22
ROC-AUC: 0.8636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 1.2938 | Val ROC-AUC: 0.8636 | Val Profit: -105
model_1_baseline | valid epoch 23
ROC-AUC: 0.8691
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 1.2913 | Val ROC-AUC: 0.8691 | Val Profit: -105
model_1_baseline | valid epoch 24
ROC-AUC: 0.8719
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 1.2887 | Val ROC-AUC: 0.8719 | Val Profit: -105
model_1_baseline | valid epoch 25
ROC-AUC: 0.8735
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 1.2860 | Val ROC-AUC: 0.8735 | Val Profit: -105
model_1_baseline | valid epoch 26
ROC-AUC: 0.8771
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 1.2832 | Val ROC-AUC: 0.8771 | Val Profit: -105
model_1_baseline | valid epoch 27
ROC-AUC: 0.8794
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 1.2802 | Val ROC-AUC: 0.8794 | Val Profit: -105
model_1_baseline | valid epoch 28
ROC-AUC: 0.8818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 1.2772 | Val ROC-AUC: 0.8818 | Val Profit: -105
model_1_baseline | valid epoch 29
ROC-AUC: 0.8842
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 1.2741 | Val ROC-AUC: 0.8842 | Val Profit: -105
model_1_baseline | valid epoch 30
ROC-AUC: 0.8848
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 1.2709 | Val ROC-AUC: 0.8848 | Val Profit: -105

Лучшая эпоха для model_1_baseline: 30
Лучший ROC-AUC: 0.8847753185781355
val
ROC-AUC: 0.8848
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [50]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.0001, 'profit': np.int64(-105), 'roc_auc': 0.8847753185781355}

In [51]:
LR = best["lr"]

In [52]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 

model_1 = nn.Sequential(
    nn.Linear(9, 16),
    nn.ReLU(),
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_1.parameters(), lr=LR)
config = {
    "model": "MLP",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_1)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_1_baseline", config=config)
log_file = new_log_file()

model_1 = train_model(
    model=model_1,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_1_baseline"
)

save_results(model_1, "model_1_baseline", log_file, run)

run.finish()

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_1_baseline | valid epoch 1
ROC-AUC: 0.6702
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3347 | Val ROC-AUC: 0.6702 | Val Profit: -105
model_1_baseline | valid epoch 2
ROC-AUC: 0.6936
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 1.3326 | Val ROC-AUC: 0.6936 | Val Profit: -105
model_1_baseline | valid epoch 3
ROC-AUC: 0.7123
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 1.3305 | Val ROC-AUC: 0.7123 | Val Profit: -105
model_1_baseline | valid epoch 4
ROC-AUC: 0.7319
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 1.3286 | Val ROC-AUC: 0.7319 | Val Profit: -105
model_1_baseline | valid epoch 5
ROC-AUC: 0.7497
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 1.3267 | Val ROC-AUC: 0.7497 | Val Profit: -105
model_1_baseline | valid epoch 6
ROC-AUC: 0.7667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 1.3249 | Val ROC-AUC: 0.7667 | Val Profit: -105
model_1_baseline | valid epoch 7
ROC-AUC: 0.7803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 1.3232 | Val ROC-AUC: 0.7803 | Val Profit: -105
model_1_baseline | valid epoch 8
ROC-AUC: 0.7918
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 1.3215 | Val ROC-AUC: 0.7918 | Val Profit: -105
model_1_baseline | valid epoch 9
ROC-AUC: 0.8013
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 1.3198 | Val ROC-AUC: 0.8013 | Val Profit: -105
model_1_baseline | valid epoch 10
ROC-AUC: 0.8097
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 1.3181 | Val ROC-AUC: 0.8097 | Val Profit: -105
model_1_baseline | valid epoch 11
ROC-AUC: 0.8193
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 1.3163 | Val ROC-AUC: 0.8193 | Val Profit: -105
model_1_baseline | valid epoch 12
ROC-AUC: 0.8284
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 1.3145 | Val ROC-AUC: 0.8284 | Val Profit: -105
model_1_baseline | valid epoch 13
ROC-AUC: 0.8347
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 1.3127 | Val ROC-AUC: 0.8347 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_1_baseline | valid epoch 14
ROC-AUC: 0.8406
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 1.3109 | Val ROC-AUC: 0.8406 | Val Profit: -105
model_1_baseline | valid epoch 15
ROC-AUC: 0.8451
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 1.3090 | Val ROC-AUC: 0.8451 | Val Profit: -105
model_1_baseline | valid epoch 16
ROC-AUC: 0.8492
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 1.3070 | Val ROC-AUC: 0.8492 | Val Profit: -105
model_1_baseline | valid epoch 17
ROC-AUC: 0.8534
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 1.3050 | Val ROC-AUC: 0.8534 | Val Profit: -105
model_1_baseline | valid epoch 18
ROC-AUC: 0.8565
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 1.3029 | Val ROC-AUC: 0.8565 | Val Profit: -105
model_1_baseline | valid epoch 19
ROC-AUC: 0.8596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 1.3007 | Val ROC-AUC: 0.8596 | Val Profit: -105
model_1_baseline | valid epoch 20
ROC-AUC: 0.8633
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 1.2985 | Val ROC-AUC: 0.8633 | Val Profit: -105
model_1_baseline | valid epoch 21
ROC-AUC: 0.8611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 1.2962 | Val ROC-AUC: 0.8611 | Val Profit: -105
model_1_baseline | valid epoch 22
ROC-AUC: 0.8636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 1.2938 | Val ROC-AUC: 0.8636 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_1_baseline | valid epoch 23
ROC-AUC: 0.8691
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 1.2913 | Val ROC-AUC: 0.8691 | Val Profit: -105
model_1_baseline | valid epoch 24
ROC-AUC: 0.8719
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 1.2887 | Val ROC-AUC: 0.8719 | Val Profit: -105
model_1_baseline | valid epoch 25
ROC-AUC: 0.8735
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 1.2860 | Val ROC-AUC: 0.8735 | Val Profit: -105
model_1_baseline | valid epoch 26
ROC-AUC: 0.8771
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 1.2832 | Val ROC-AUC: 0.8771 | Val Profit: -105
model_1_baseline | valid epoch 27
ROC-AUC: 0.8794
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 1.2802 | Val ROC-AUC: 0.8794 | Val Profit: -105
model_1_baseline | valid epoch 28
ROC-AUC: 0.8818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 1.2772 | Val ROC-AUC: 0.8818 | Val Profit: -105
model_1_baseline | valid epoch 29
ROC-AUC: 0.8842
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 1.2741 | Val ROC-AUC: 0.8842 | Val Profit: -105
model_1_baseline | valid epoch 30
ROC-AUC: 0.8848
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 1.2709 | Val ROC-AUC: 0.8848 | Val Profit: -105

Лучшая эпоха для model_1_baseline: 30
Лучший ROC-AUC: 0.8847753185781355
Train
ROC-AUC: 0.9065
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -415

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Test
ROC-AUC: 0.9032
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -118635

In [53]:
train_metrics = evaluate_model(model_1, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_1, X_test, y_test, threshold=0.5, name="Test")

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Train
ROC-AUC: 0.9065
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -415

Test
ROC-AUC: 0.9032
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -118635

Видно предупреждение в выводе о том, что модель не предсказала ни одного фрода. Получилась недообученная модель. Исходя из функции profit был выбран самый маленький lr, и модель с ним не успела обучиться

### Попробуем подобрать порог

In [34]:
with torch.no_grad():
    val_prob = torch.sigmoid(model(X_val)).numpy()

val_true = y_val.numpy()

NameError: name 'model' is not defined

In [ ]:
from sklearn.metrics import precision_recall_curve

target_recall = 0.90

prec, rec, thr = precision_recall_curve(val_true, val_prob)
best_threshold = thr[rec[:-1] >= target_recall].max()
logging.info(f"Подобрали порог {best_threshold}")
wandb.log({"best_threshold": best_threshold})
best_threshold

In [ ]:
y_pred = (y_prob > best_threshold).astype(int)

In [ ]:
pre_at_score = precision_score(y_true, y_pred)
#logging.info(f"На тесте Precision: {pre_at_score}")
pre_at_score

In [ ]:
rec_at_score = recall_score(y_true, y_pred)
#logging.info(f"На тесте Recall: {rec_at_score}")
rec_at_score

In [ ]:
import matplotlib.pyplot as plt

plt.plot(rec, prec)
plt.xlabel("recall")
plt.ylabel("precision")
plt.title("PR кривая")
plt.show()

In [ ]:
#import pickle

#pickle.dump(model.state_dict(), open("models/model_fraud_1.pkl", 'wb'))
#logging.info("Сохранили веса модели в папку models")

In [ ]:
#results = wandb.Table(columns=['model', 'test/roc_auc', 'test/precision', 'test/recall', 'test/recall_new_threshold', 'test/precision_new_threshold'])
#results.add_data("nn_baseline", auc_score, pre_score, rec_score, rec_at_score, pre_at_score)
#wandb.log({"results": results})

In [ ]:
#artifact = wandb.Artifact(name="model_fraud_1", type="model", description="Тест логгирования модели MLP")

#artifact.add_file("models/model_fraud_1.pkl")
#artifact.add_file(log_file)
#run.log_artifact(artifact)

In [ ]:
#run.finish()

## model_2_dop_sloi

In [54]:
EPOCHS = 30
SEED = 42

In [55]:
wandb.init(mode="disabled")
results = []
for LR in [0.05, 0.03, 0.01, 0.005, 0.002, 0.0001]:
        random.seed(SEED)
        np.random.seed(SEED)
        torch.manual_seed(SEED) 

        model_2 = nn.Sequential(
            nn.Linear(9, 32),
            nn.ReLU(),

            nn.Linear(32, 16),
            nn.ReLU(),

            nn.Linear(16, 8),
            nn.ReLU(),

            nn.Linear(8, 1)
        )

        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.Adam(model_2.parameters(), lr=LR)

        model_2 = train_model(
            model=model_2,
            train_loader=train_loader,
            X_valid=X_val,
            y_valid=y_val,
            loss_fn=loss_fn,
            optimizer=optimizer,
            epochs=EPOCHS,
            threshold=0.5,
            model_name="model_2_dop_sloi"
        )

        val = evaluate_model(model_2, X_val, y_val, threshold=0.5, name="val")
        results.append({"lr": LR, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.9133
Precision: 0.2346
Recall: 0.9048
F0.5-score: 0.2754
Profit: -1465

Эпоха 1 | Train Loss: 1.0974 | Val ROC-AUC: 0.9133 | Val Profit: -1465
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9355
Precision: 0.2879
Recall: 0.9048
F0.5-score: 0.3333
Profit: -1090

Эпоха 2 | Train Loss: 0.6756 | Val ROC-AUC: 0.9355 | Val Profit: -1090
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9292
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 3 | Train Loss: 0.5462 | Val ROC-AUC: 0.9292 | Val Profit: -1495
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9064
Precision: 0.2211
Recall: 1.0
F0.5-score: 0.2618
Profit: -1745

Эпоха 4 | Train Loss: 0.4843 | Val ROC-AUC: 0.9064 | Val Profit: -1745
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.862
Precision: 0.1544
Recall: 1.0
F0.5-score: 0.1858
Profit: -2770

Эпоха 5 | Train Loss: 0.5720 | Val ROC-AUC: 0.8620 | Val Profit: -2770
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.869
Precision: 0.1556
Recall: 1.0
F0.5-score: 0.1872
Profit: -2745

Эпоха 6 | Train Loss: 0.7874 | Val ROC-AUC: 0.8690 | Val Profit: -2745
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.893
Precision: 0.1892
Recall: 1.0
F0.5-score: 0.2258
Profit: -2145

Эпоха 7 | Train Loss: 0.7076 | Val ROC-AUC: 0.8930 | Val Profit: -2145
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9285
Precision: 0.2019
Recall: 1.0
F0.5-score: 0.2403
Profit: -1970

Эпоха 8 | Train Loss: 0.5352 | Val ROC-AUC: 0.9285 | Val Profit: -1970
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9324
Precision: 0.3148
Recall: 0.8095
F0.5-score: 0.3586
Profit: -860

Эпоха 9 | Train Loss: 0.4616 | Val ROC-AUC: 0.9324 | Val Profit: -860
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.9459
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 10 | Train Loss: 0.5356 | Val ROC-AUC: 0.9459 | Val Profit: -1470
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.9462
Precision: 0.2381
Recall: 0.9524
F0.5-score: 0.2801
Profit: -1505

Эпоха 11 | Train Loss: 0.4231 | Val ROC-AUC: 0.9462 | Val Profit: -1505
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.9488
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 12 | Train Loss: 0.4127 | Val ROC-AUC: 0.9488 | Val Profit: -1270
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9324
Precision: 0.2211
Recall: 1.0
F0.5-score: 0.2618
Profit: -1745

Эпоха 13 | Train Loss: 0.4404 | Val ROC-AUC: 0.9324 | Val Profit: -1745
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9518
Precision: 0.2625
Recall: 1.0
F0.5-score: 0.3079
Profit: -1370

Эпоха 14 | Train Loss: 0.4711 | Val ROC-AUC: 0.9518 | Val Profit: -1370
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9596
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 15 | Train Loss: 0.3770 | Val ROC-AUC: 0.9596 | Val Profit: -1120
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9662
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 16 | Train Loss: 0.2990 | Val ROC-AUC: 0.9662 | Val Profit: -820
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9596
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 17 | Train Loss: 0.3791 | Val ROC-AUC: 0.9596 | Val Profit: -930
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9716
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 18 | Train Loss: 0.2408 | Val ROC-AUC: 0.9716 | Val Profit: -555
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9359
Precision: 0.2703
Recall: 0.9524
F0.5-score: 0.3155
Profit: -1255

Эпоха 19 | Train Loss: 0.3314 | Val ROC-AUC: 0.9359 | Val Profit: -1255
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9569
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 20 | Train Loss: 0.5189 | Val ROC-AUC: 0.9569 | Val Profit: -1620
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9602
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 21 | Train Loss: 0.3443 | Val ROC-AUC: 0.9602 | Val Profit: -995
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9541
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 22 | Train Loss: 0.2894 | Val ROC-AUC: 0.9541 | Val Profit: -870
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9642
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 23 | Train Loss: 0.2778 | Val ROC-AUC: 0.9642 | Val Profit: -665
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9831
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 24 | Train Loss: 0.2730 | Val ROC-AUC: 0.9831 | Val Profit: -570
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.975
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 25 | Train Loss: 0.2123 | Val ROC-AUC: 0.9750 | Val Profit: -415
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9628
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 26 | Train Loss: 0.3200 | Val ROC-AUC: 0.9628 | Val Profit: -1045
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9699
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 27 | Train Loss: 0.2643 | Val ROC-AUC: 0.9699 | Val Profit: -615
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.978
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 28 | Train Loss: 0.2557 | Val ROC-AUC: 0.9780 | Val Profit: -490
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9774
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 29 | Train Loss: 0.1742 | Val ROC-AUC: 0.9774 | Val Profit: -290
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.9531
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 30 | Train Loss: 0.2040 | Val ROC-AUC: 0.9531 | Val Profit: -930

Лучшая эпоха для model_2_dop_sloi: 24
Лучший ROC-AUC: 0.9830985915492958
val
ROC-AUC: 0.9831
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.9555
Precision: 0.181
Recall: 1.0
F0.5-score: 0.2165
Profit: -2270

Эпоха 1 | Train Loss: 1.0414 | Val ROC-AUC: 0.9555 | Val Profit: -2270
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9513
Precision: 0.2273
Recall: 0.9524
F0.5-score: 0.2681
Profit: -1605

Эпоха 2 | Train Loss: 0.5532 | Val ROC-AUC: 0.9513 | Val Profit: -1605
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9714
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 3 | Train Loss: 0.3984 | Val ROC-AUC: 0.9714 | Val Profit: -945
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9663
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 4 | Train Loss: 0.3133 | Val ROC-AUC: 0.9663 | Val Profit: -780
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.9712
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 5 | Train Loss: 0.3060 | Val ROC-AUC: 0.9712 | Val Profit: -930
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.9733
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 6 | Train Loss: 0.3146 | Val ROC-AUC: 0.9733 | Val Profit: -665
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.9691
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 7 | Train Loss: 0.3097 | Val ROC-AUC: 0.9691 | Val Profit: -1145
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9746
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 8 | Train Loss: 0.2676 | Val ROC-AUC: 0.9746 | Val Profit: -870
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9749
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 9 | Train Loss: 0.2071 | Val ROC-AUC: 0.9749 | Val Profit: -580
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.9744
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 10 | Train Loss: 0.3642 | Val ROC-AUC: 0.9744 | Val Profit: -1095
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.984
Precision: 0.6129
Recall: 0.9048
F0.5-score: 0.6552
Profit: -215

Эпоха 11 | Train Loss: 0.2470 | Val ROC-AUC: 0.9840 | Val Profit: -215
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.959
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 12 | Train Loss: 0.3739 | Val ROC-AUC: 0.9590 | Val Profit: -1155
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9795
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 13 | Train Loss: 0.2662 | Val ROC-AUC: 0.9795 | Val Profit: -805
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9606
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 14 | Train Loss: 0.2341 | Val ROC-AUC: 0.9606 | Val Profit: -755
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9768
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 15 | Train Loss: 0.3102 | Val ROC-AUC: 0.9768 | Val Profit: -1120
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9775
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 16 | Train Loss: 0.2262 | Val ROC-AUC: 0.9775 | Val Profit: -570
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.981
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 17 | Train Loss: 0.2056 | Val ROC-AUC: 0.9810 | Val Profit: -995
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.983
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 18 | Train Loss: 0.2245 | Val ROC-AUC: 0.9830 | Val Profit: -570
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9811
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 19 | Train Loss: 0.1515 | Val ROC-AUC: 0.9811 | Val Profit: -520
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9852
Precision: 0.5556
Recall: 0.9524
F0.5-score: 0.6061
Profit: -305

Эпоха 20 | Train Loss: 0.1364 | Val ROC-AUC: 0.9852 | Val Profit: -305
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9852
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 21 | Train Loss: 0.1540 | Val ROC-AUC: 0.9852 | Val Profit: -505
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9673
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 22 | Train Loss: 0.3087 | Val ROC-AUC: 0.9673 | Val Profit: -980
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9624
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 23 | Train Loss: 0.3689 | Val ROC-AUC: 0.9624 | Val Profit: -1245
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9822
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 24 | Train Loss: 0.2604 | Val ROC-AUC: 0.9822 | Val Profit: -545
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9835
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 25 | Train Loss: 0.2206 | Val ROC-AUC: 0.9835 | Val Profit: -545
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.986
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 26 | Train Loss: 0.1535 | Val ROC-AUC: 0.9860 | Val Profit: -430
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9725
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 27 | Train Loss: 0.2189 | Val ROC-AUC: 0.9725 | Val Profit: -455
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9883
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 28 | Train Loss: 0.2265 | Val ROC-AUC: 0.9883 | Val Profit: -520
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.987
Precision: 0.5
Recall: 1.0
F0.5-score: 0.5556
Profit: -420

Эпоха 29 | Train Loss: 0.1531 | Val ROC-AUC: 0.9870 | Val Profit: -420
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.9877
Precision: 0.525
Recall: 1.0
F0.5-score: 0.5801
Profit: -370

Эпоха 30 | Train Loss: 0.1000 | Val ROC-AUC: 0.9877 | Val Profit: -370

Лучшая эпоха для model_2_dop_sloi: 28
Лучший ROC-AUC: 0.9883299798792757
val
ROC-AUC: 0.9883
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.9311
Precision: 0.3051
Recall: 0.8571
F0.5-score: 0.3502
Profit: -950

Эпоха 1 | Train Loss: 1.1825 | Val ROC-AUC: 0.9311 | Val Profit: -950
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9552
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 2 | Train Loss: 0.6270 | Val ROC-AUC: 0.9552 | Val Profit: -1120
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9502
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 3 | Train Loss: 0.4225 | Val ROC-AUC: 0.9502 | Val Profit: -1470
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9642
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 4 | Train Loss: 0.4105 | Val ROC-AUC: 0.9642 | Val Profit: -1155
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.9641
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 5 | Train Loss: 0.3026 | Val ROC-AUC: 0.9641 | Val Profit: -1020
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.9599
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 6 | Train Loss: 0.2684 | Val ROC-AUC: 0.9599 | Val Profit: -1105
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.9604
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 7 | Train Loss: 0.2346 | Val ROC-AUC: 0.9604 | Val Profit: -855
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9655
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 8 | Train Loss: 0.2385 | Val ROC-AUC: 0.9655 | Val Profit: -780
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9616
Precision: 0.4
Recall: 0.7619
F0.5-score: 0.442
Profit: -545

Эпоха 9 | Train Loss: 0.2673 | Val ROC-AUC: 0.9616 | Val Profit: -545
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.967
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 10 | Train Loss: 0.2220 | Val ROC-AUC: 0.9670 | Val Profit: -795
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.9667
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 11 | Train Loss: 0.2146 | Val ROC-AUC: 0.9667 | Val Profit: -690
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.9722
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 12 | Train Loss: 0.2322 | Val ROC-AUC: 0.9722 | Val Profit: -745
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9764
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 13 | Train Loss: 0.2764 | Val ROC-AUC: 0.9764 | Val Profit: -555
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9741
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 14 | Train Loss: 0.2126 | Val ROC-AUC: 0.9741 | Val Profit: -500
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9716
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 15 | Train Loss: 0.1698 | Val ROC-AUC: 0.9716 | Val Profit: -540
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9777
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 16 | Train Loss: 0.1524 | Val ROC-AUC: 0.9777 | Val Profit: -340
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9768
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 17 | Train Loss: 0.1288 | Val ROC-AUC: 0.9768 | Val Profit: -365
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9805
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 18 | Train Loss: 0.1281 | Val ROC-AUC: 0.9805 | Val Profit: -290
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9764
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 19 | Train Loss: 0.1899 | Val ROC-AUC: 0.9764 | Val Profit: -275
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9734
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 20 | Train Loss: 0.1419 | Val ROC-AUC: 0.9734 | Val Profit: -720
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9759
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 21 | Train Loss: 0.1684 | Val ROC-AUC: 0.9759 | Val Profit: -360
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9673
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 22 | Train Loss: 0.3742 | Val ROC-AUC: 0.9673 | Val Profit: -1020
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9745
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 23 | Train Loss: 0.2413 | Val ROC-AUC: 0.9745 | Val Profit: -620
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9846
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 24 | Train Loss: 0.1694 | Val ROC-AUC: 0.9846 | Val Profit: -520
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9854
Precision: 0.5556
Recall: 0.9524
F0.5-score: 0.6061
Profit: -305

Эпоха 25 | Train Loss: 0.1276 | Val ROC-AUC: 0.9854 | Val Profit: -305
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9885
Precision: 0.6296
Recall: 0.8095
F0.5-score: 0.6589
Profit: -185

Эпоха 26 | Train Loss: 0.0949 | Val ROC-AUC: 0.9885 | Val Profit: -185
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9877
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 27 | Train Loss: 0.0931 | Val ROC-AUC: 0.9877 | Val Profit: -330
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9842
Precision: 0.6207
Recall: 0.8571
F0.5-score: 0.6569
Profit: -200

Эпоха 28 | Train Loss: 0.1133 | Val ROC-AUC: 0.9842 | Val Profit: -200
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9693
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 29 | Train Loss: 0.3299 | Val ROC-AUC: 0.9693 | Val Profit: -1045
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.983
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 30 | Train Loss: 0.3053 | Val ROC-AUC: 0.9830 | Val Profit: -620

Лучшая эпоха для model_2_dop_sloi: 26
Лучший ROC-AUC: 0.9884641180415827
val
ROC-AUC: 0.9885
Precision: 0.6296
Recall: 0.8095
F0.5-score: 0.6589
Profit: -185

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.9408
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.2674 | Val ROC-AUC: 0.9408 | Val Profit: -105
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9333
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 2 | Train Loss: 0.9533 | Val ROC-AUC: 0.9333 | Val Profit: -1495
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9481
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 3 | Train Loss: 0.5693 | Val ROC-AUC: 0.9481 | Val Profit: -1545
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9599
Precision: 0.2593
Recall: 1.0
F0.5-score: 0.3043
Profit: -1395

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 4 | Train Loss: 0.4091 | Val ROC-AUC: 0.9599 | Val Profit: -1395
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.9616
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 5 | Train Loss: 0.3485 | Val ROC-AUC: 0.9616 | Val Profit: -1295
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.9544
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 6 | Train Loss: 0.3119 | Val ROC-AUC: 0.9544 | Val Profit: -1270
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.9531
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 7 | Train Loss: 0.2901 | Val ROC-AUC: 0.9531 | Val Profit: -1345
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9612
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 8 | Train Loss: 0.2719 | Val ROC-AUC: 0.9612 | Val Profit: -1120
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9646
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 9 | Train Loss: 0.2528 | Val ROC-AUC: 0.9646 | Val Profit: -805
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.9559
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 10 | Train Loss: 0.2717 | Val ROC-AUC: 0.9559 | Val Profit: -740
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.9696
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 11 | Train Loss: 0.2339 | Val ROC-AUC: 0.9696 | Val Profit: -745
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.9674
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 12 | Train Loss: 0.1995 | Val ROC-AUC: 0.9674 | Val Profit: -625
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9689
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 13 | Train Loss: 0.1791 | Val ROC-AUC: 0.9689 | Val Profit: -540
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9712
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 14 | Train Loss: 0.1614 | Val ROC-AUC: 0.9712 | Val Profit: -525
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9726
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 15 | Train Loss: 0.1444 | Val ROC-AUC: 0.9726 | Val Profit: -490
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9722
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 16 | Train Loss: 0.1229 | Val ROC-AUC: 0.9722 | Val Profit: -375
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9737
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 17 | Train Loss: 0.1105 | Val ROC-AUC: 0.9737 | Val Profit: -490
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9734
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 18 | Train Loss: 0.1017 | Val ROC-AUC: 0.9734 | Val Profit: -475
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9722
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 19 | Train Loss: 0.0963 | Val ROC-AUC: 0.9722 | Val Profit: -400
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9763
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 20 | Train Loss: 0.0903 | Val ROC-AUC: 0.9763 | Val Profit: -415
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9736
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 21 | Train Loss: 0.0943 | Val ROC-AUC: 0.9736 | Val Profit: -565
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9753
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 22 | Train Loss: 0.1045 | Val ROC-AUC: 0.9753 | Val Profit: -540
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9767
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 23 | Train Loss: 0.1244 | Val ROC-AUC: 0.9767 | Val Profit: -540
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9804
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 24 | Train Loss: 0.1050 | Val ROC-AUC: 0.9804 | Val Profit: -325
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9704
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 25 | Train Loss: 0.1297 | Val ROC-AUC: 0.9704 | Val Profit: -365
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9709
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 26 | Train Loss: 0.1584 | Val ROC-AUC: 0.9709 | Val Profit: -680
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9751
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 27 | Train Loss: 0.1787 | Val ROC-AUC: 0.9751 | Val Profit: -355
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9725
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 28 | Train Loss: 0.2029 | Val ROC-AUC: 0.9725 | Val Profit: -870
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9614
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 29 | Train Loss: 0.2377 | Val ROC-AUC: 0.9614 | Val Profit: -995
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.9693
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 30 | Train Loss: 0.2199 | Val ROC-AUC: 0.9693 | Val Profit: -485

Лучшая эпоха для model_2_dop_sloi: 24
Лучший ROC-AUC: 0.9804158283031522
val
ROC-AUC: 0.9804
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.908
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3020 | Val ROC-AUC: 0.9080 | Val Profit: -105
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9556
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 2 | Train Loss: 1.2293 | Val ROC-AUC: 0.9556 | Val Profit: -815
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9559
Precision: 0.2625
Recall: 1.0
F0.5-score: 0.3079
Profit: -1370

Эпоха 3 | Train Loss: 1.0194 | Val ROC-AUC: 0.9559 | Val Profit: -1370
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9568
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 4 | Train Loss: 0.7041 | Val ROC-AUC: 0.9568 | Val Profit: -1695
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.9606
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 5 | Train Loss: 0.4974 | Val ROC-AUC: 0.9606 | Val Profit: -1645
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.9622
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 6 | Train Loss: 0.4155 | Val ROC-AUC: 0.9622 | Val Profit: -1420
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.9632
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 7 | Train Loss: 0.3711 | Val ROC-AUC: 0.9632 | Val Profit: -1270
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9626
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 8 | Train Loss: 0.3370 | Val ROC-AUC: 0.9626 | Val Profit: -1195
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9631
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 9 | Train Loss: 0.3073 | Val ROC-AUC: 0.9631 | Val Profit: -1095

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.9643
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 10 | Train Loss: 0.2824 | Val ROC-AUC: 0.9643 | Val Profit: -995
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.9654
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 11 | Train Loss: 0.2611 | Val ROC-AUC: 0.9654 | Val Profit: -895
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.9666
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 12 | Train Loss: 0.2427 | Val ROC-AUC: 0.9666 | Val Profit: -830
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9678
Precision: 0.3585
Recall: 0.9048
F0.5-score: 0.4077
Profit: -765

Эпоха 13 | Train Loss: 0.2258 | Val ROC-AUC: 0.9678 | Val Profit: -765
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9689
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 14 | Train Loss: 0.2121 | Val ROC-AUC: 0.9689 | Val Profit: -740
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.969
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 15 | Train Loss: 0.1986 | Val ROC-AUC: 0.9690 | Val Profit: -715
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.97
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 16 | Train Loss: 0.1864 | Val ROC-AUC: 0.9700 | Val Profit: -690
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9704
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 17 | Train Loss: 0.1739 | Val ROC-AUC: 0.9704 | Val Profit: -590
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9709
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 18 | Train Loss: 0.1625 | Val ROC-AUC: 0.9709 | Val Profit: -565
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9728
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 19 | Train Loss: 0.1523 | Val ROC-AUC: 0.9728 | Val Profit: -515
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9734
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 20 | Train Loss: 0.1422 | Val ROC-AUC: 0.9734 | Val Profit: -505
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9752
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 21 | Train Loss: 0.1328 | Val ROC-AUC: 0.9752 | Val Profit: -480
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9753
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 22 | Train Loss: 0.1224 | Val ROC-AUC: 0.9753 | Val Profit: -430
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9763
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 23 | Train Loss: 0.1147 | Val ROC-AUC: 0.9763 | Val Profit: -390
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9765
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 24 | Train Loss: 0.1077 | Val ROC-AUC: 0.9765 | Val Profit: -415
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9771
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 25 | Train Loss: 0.1015 | Val ROC-AUC: 0.9771 | Val Profit: -390
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9771
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 26 | Train Loss: 0.0942 | Val ROC-AUC: 0.9771 | Val Profit: -390
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9776
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 27 | Train Loss: 0.0888 | Val ROC-AUC: 0.9776 | Val Profit: -365
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9788
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 28 | Train Loss: 0.0829 | Val ROC-AUC: 0.9788 | Val Profit: -365
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9783
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 29 | Train Loss: 0.0793 | Val ROC-AUC: 0.9783 | Val Profit: -365
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.9793
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 30 | Train Loss: 0.0742 | Val ROC-AUC: 0.9793 | Val Profit: -340

Лучшая эпоха для model_2_dop_sloi: 30
Лучший ROC-AUC: 0.9793427230046949
val
ROC-AUC: 0.9793
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.4915
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3122 | Val ROC-AUC: 0.4915 | Val Profit: -105
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.552
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 1.3108 | Val ROC-AUC: 0.5520 | Val Profit: -105
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.6055
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 1.3094 | Val ROC-AUC: 0.6055 | Val Profit: -105
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.6577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 1.3078 | Val ROC-AUC: 0.6577 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.7105
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 1.3061 | Val ROC-AUC: 0.7105 | Val Profit: -105
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.7498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 1.3044 | Val ROC-AUC: 0.7498 | Val Profit: -105
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.7851
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 1.3024 | Val ROC-AUC: 0.7851 | Val Profit: -105
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.8165
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 1.3002 | Val ROC-AUC: 0.8165 | Val Profit: -105
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.8377
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 1.2976 | Val ROC-AUC: 0.8377 | Val Profit: -105
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.8541
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 1.2946 | Val ROC-AUC: 0.8541 | Val Profit: -105
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.8731
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 1.2912 | Val ROC-AUC: 0.8731 | Val Profit: -105
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.8845
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 1.2874 | Val ROC-AUC: 0.8845 | Val Profit: -105
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.8956
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 1.2832 | Val ROC-AUC: 0.8956 | Val Profit: -105
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.904
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 1.2785 | Val ROC-AUC: 0.9040 | Val Profit: -105
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9113
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 1.2731 | Val ROC-AUC: 0.9113 | Val Profit: -95
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9172
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 16 | Train Loss: 1.2671 | Val ROC-AUC: 0.9172 | Val Profit: -125
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9226
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 17 | Train Loss: 1.2604 | Val ROC-AUC: 0.9226 | Val Profit: -160

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9302
Precision: 0.4333
Recall: 0.619
F0.5-score: 0.461
Profit: -400

Эпоха 18 | Train Loss: 1.2529 | Val ROC-AUC: 0.9302 | Val Profit: -400
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9341
Precision: 0.3659
Recall: 0.7143
F0.5-score: 0.4054
Profit: -605

Эпоха 19 | Train Loss: 1.2445 | Val ROC-AUC: 0.9341 | Val Profit: -605
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9374
Precision: 0.3462
Recall: 0.8571
F0.5-score: 0.393
Profit: -775

Эпоха 20 | Train Loss: 1.2353 | Val ROC-AUC: 0.9374 | Val Profit: -775
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9398
Precision: 0.3065
Recall: 0.9048
F0.5-score: 0.3532
Profit: -990

Эпоха 21 | Train Loss: 1.2251 | Val ROC-AUC: 0.9398 | Val Profit: -990
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9427
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 22 | Train Loss: 1.2141 | Val ROC-AUC: 0.9427 | Val Profit: -1065
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9453
Precision: 0.2676
Recall: 0.9048
F0.5-score: 0.3115
Profit: -1215

Эпоха 23 | Train Loss: 1.2023 | Val ROC-AUC: 0.9453 | Val Profit: -1215
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9476
Precision: 0.2568
Recall: 0.9048
F0.5-score: 0.2997
Profit: -1290

Эпоха 24 | Train Loss: 1.1896 | Val ROC-AUC: 0.9476 | Val Profit: -1290
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9496
Precision: 0.25
Recall: 0.9048
F0.5-score: 0.2923
Profit: -1340

Эпоха 25 | Train Loss: 1.1758 | Val ROC-AUC: 0.9496 | Val Profit: -1340
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9512
Precision: 0.2533
Recall: 0.9048
F0.5-score: 0.296
Profit: -1315

Эпоха 26 | Train Loss: 1.1608 | Val ROC-AUC: 0.9512 | Val Profit: -1315
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9524
Precision: 0.25
Recall: 0.9048
F0.5-score: 0.2923
Profit: -1340

Эпоха 27 | Train Loss: 1.1447 | Val ROC-AUC: 0.9524 | Val Profit: -1340
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9529
Precision: 0.2436
Recall: 0.9048
F0.5-score: 0.2853
Profit: -1390

Эпоха 28 | Train Loss: 1.1275 | Val ROC-AUC: 0.9529 | Val Profit: -1390
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9549
Precision: 0.2405
Recall: 0.9048
F0.5-score: 0.2819
Profit: -1415

Эпоха 29 | Train Loss: 1.1095 | Val ROC-AUC: 0.9549 | Val Profit: -1415
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.956
Precision: 0.2436
Recall: 0.9048
F0.5-score: 0.2853
Profit: -1390

Эпоха 30 | Train Loss: 1.0907 | Val ROC-AUC: 0.9560 | Val Profit: -1390

Лучшая эпоха для model_2_dop_sloi: 30
Лучший ROC-AUC: 0.9560026827632461
val
ROC-AUC: 0.956
Precision: 0.2436
Recall: 0.9048
F0.5-score: 0.2853
Profit: -1390

In [56]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.01, 'profit': np.int64(-185), 'roc_auc': 0.9884641180415827}

In [57]:
LR = best["lr"]

In [58]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_2 = nn.Sequential(
    nn.Linear(9, 32),
    nn.ReLU(),

    nn.Linear(32, 16),
    nn.ReLU(),

    nn.Linear(16, 8),
    nn.ReLU(),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_2.parameters(), lr=LR)

config = {
    "model": "MLP_added_layer",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_2)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_2_added_layers", config=config)
log_file = new_log_file()

model_2 = train_model(
    model=model_2,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_2_dop_sloi"
)

save_results(model_2, "model_2", log_file, run)

run.finish()

model_2_dop_sloi | valid epoch 1
ROC-AUC: 0.9311
Precision: 0.3051
Recall: 0.8571
F0.5-score: 0.3502
Profit: -950

Эпоха 1 | Train Loss: 1.1825 | Val ROC-AUC: 0.9311 | Val Profit: -950
model_2_dop_sloi | valid epoch 2
ROC-AUC: 0.9552
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 2 | Train Loss: 0.6270 | Val ROC-AUC: 0.9552 | Val Profit: -1120
model_2_dop_sloi | valid epoch 3
ROC-AUC: 0.9502
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 3 | Train Loss: 0.4225 | Val ROC-AUC: 0.9502 | Val Profit: -1470
model_2_dop_sloi | valid epoch 4
ROC-AUC: 0.9642
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 4 | Train Loss: 0.4105 | Val ROC-AUC: 0.9642 | Val Profit: -1155
model_2_dop_sloi | valid epoch 5
ROC-AUC: 0.9641
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 5 | Train Loss: 0.3026 | Val ROC-AUC: 0.9641 | Val Profit: -1020
model_2_dop_sloi | valid epoch 6
ROC-AUC: 0.9599
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 6 | Train Loss: 0.2684 | Val ROC-AUC: 0.9599 | Val Profit: -1105
model_2_dop_sloi | valid epoch 7
ROC-AUC: 0.9604
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 7 | Train Loss: 0.2346 | Val ROC-AUC: 0.9604 | Val Profit: -855
model_2_dop_sloi | valid epoch 8
ROC-AUC: 0.9655
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 8 | Train Loss: 0.2385 | Val ROC-AUC: 0.9655 | Val Profit: -780
model_2_dop_sloi | valid epoch 9
ROC-AUC: 0.9616
Precision: 0.4
Recall: 0.7619
F0.5-score: 0.442
Profit: -545

Эпоха 9 | Train Loss: 0.2673 | Val ROC-AUC: 0.9616 | Val Profit: -545
model_2_dop_sloi | valid epoch 10
ROC-AUC: 0.967
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 10 | Train Loss: 0.2220 | Val ROC-AUC: 0.9670 | Val Profit: -795
model_2_dop_sloi | valid epoch 11
ROC-AUC: 0.9667
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 11 | Train Loss: 0.2146 | Val ROC-AUC: 0.9667 | Val Profit: -690
model_2_dop_sloi | valid epoch 12
ROC-AUC: 0.9722
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 12 | Train Loss: 0.2322 | Val ROC-AUC: 0.9722 | Val Profit: -745
model_2_dop_sloi | valid epoch 13
ROC-AUC: 0.9764
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 13 | Train Loss: 0.2764 | Val ROC-AUC: 0.9764 | Val Profit: -555
model_2_dop_sloi | valid epoch 14
ROC-AUC: 0.9741
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 14 | Train Loss: 0.2126 | Val ROC-AUC: 0.9741 | Val Profit: -500
model_2_dop_sloi | valid epoch 15
ROC-AUC: 0.9716
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 15 | Train Loss: 0.1698 | Val ROC-AUC: 0.9716 | Val Profit: -540
model_2_dop_sloi | valid epoch 16
ROC-AUC: 0.9777
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 16 | Train Loss: 0.1524 | Val ROC-AUC: 0.9777 | Val Profit: -340
model_2_dop_sloi | valid epoch 17
ROC-AUC: 0.9768
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 17 | Train Loss: 0.1288 | Val ROC-AUC: 0.9768 | Val Profit: -365
model_2_dop_sloi | valid epoch 18
ROC-AUC: 0.9805
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 18 | Train Loss: 0.1281 | Val ROC-AUC: 0.9805 | Val Profit: -290
model_2_dop_sloi | valid epoch 19
ROC-AUC: 0.9764
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 19 | Train Loss: 0.1899 | Val ROC-AUC: 0.9764 | Val Profit: -275
model_2_dop_sloi | valid epoch 20
ROC-AUC: 0.9734
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 20 | Train Loss: 0.1419 | Val ROC-AUC: 0.9734 | Val Profit: -720
model_2_dop_sloi | valid epoch 21
ROC-AUC: 0.9759
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 21 | Train Loss: 0.1684 | Val ROC-AUC: 0.9759 | Val Profit: -360
model_2_dop_sloi | valid epoch 22
ROC-AUC: 0.9673
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 22 | Train Loss: 0.3742 | Val ROC-AUC: 0.9673 | Val Profit: -1020
model_2_dop_sloi | valid epoch 23
ROC-AUC: 0.9745
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 23 | Train Loss: 0.2413 | Val ROC-AUC: 0.9745 | Val Profit: -620
model_2_dop_sloi | valid epoch 24
ROC-AUC: 0.9846
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 24 | Train Loss: 0.1694 | Val ROC-AUC: 0.9846 | Val Profit: -520
model_2_dop_sloi | valid epoch 25
ROC-AUC: 0.9854
Precision: 0.5556
Recall: 0.9524
F0.5-score: 0.6061
Profit: -305

Эпоха 25 | Train Loss: 0.1276 | Val ROC-AUC: 0.9854 | Val Profit: -305
model_2_dop_sloi | valid epoch 26
ROC-AUC: 0.9885
Precision: 0.6296
Recall: 0.8095
F0.5-score: 0.6589
Profit: -185

Эпоха 26 | Train Loss: 0.0949 | Val ROC-AUC: 0.9885 | Val Profit: -185
model_2_dop_sloi | valid epoch 27
ROC-AUC: 0.9877
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 27 | Train Loss: 0.0931 | Val ROC-AUC: 0.9877 | Val Profit: -330
model_2_dop_sloi | valid epoch 28
ROC-AUC: 0.9842
Precision: 0.6207
Recall: 0.8571
F0.5-score: 0.6569
Profit: -200

Эпоха 28 | Train Loss: 0.1133 | Val ROC-AUC: 0.9842 | Val Profit: -200
model_2_dop_sloi | valid epoch 29
ROC-AUC: 0.9693
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 29 | Train Loss: 0.3299 | Val ROC-AUC: 0.9693 | Val Profit: -1045
model_2_dop_sloi | valid epoch 30
ROC-AUC: 0.983
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 30 | Train Loss: 0.3053 | Val ROC-AUC: 0.9830 | Val Profit: -620

Лучшая эпоха для model_2_dop_sloi: 26
Лучший ROC-AUC: 0.9884641180415827
Train
ROC-AUC: 0.9974
Precision: 0.7757
Recall: 1.0
F0.5-score: 0.8121
Profit: -185

Test
ROC-AUC: 0.9858
Precision: 0.6243
Recall: 0.8244
F0.5-score: 0.6561
Profit: -217335

In [59]:
train_metrics = evaluate_model(model_2, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_2, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9974
Precision: 0.7757
Recall: 1.0
F0.5-score: 0.8121
Profit: -185

Test
ROC-AUC: 0.9858
Precision: 0.6243
Recall: 0.8244
F0.5-score: 0.6561
Profit: -217335

Да, добавив всего 1 доп слой, видно, что модель стала находить зависимости. Precision и Recall больше не равны нулю. Profit равен -217335 (что однако хуже бейзлайна без предсказания фрода)

## model_3_bolshe_neyronov

In [61]:
EPOCHS = 30
SEED = 42

In [62]:
wandb.init(mode="disabled")
results = []
for LR in [0.05, 0.03, 0.01, 0.005, 0.002, 0.0001]:
        random.seed(SEED)
        np.random.seed(SEED)
        torch.manual_seed(SEED) 

        model_3 = nn.Sequential(
            nn.Linear(9, 32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
        )

        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.Adam(model_3.parameters(), lr=LR)

        model_3 = train_model(
            model=model_3,
            train_loader=train_loader,
            X_valid=X_val,
            y_valid=y_val,
            loss_fn=loss_fn,
            optimizer=optimizer,
            epochs=EPOCHS,
            threshold=0.5,
            model_name="model_3_bolshe_neyronov"
        )

        val = evaluate_model(model_3, X_val, y_val, threshold=0.5, name="val")
        results.append({"lr": LR, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_3_bolshe_neyronov | valid epoch 1
ROC-AUC: 0.9429
Precision: 0.2727
Recall: 0.8571
F0.5-score: 0.3158
Profit: -1125

Эпоха 1 | Train Loss: 0.8665 | Val ROC-AUC: 0.9429 | Val Profit: -1125
model_3_bolshe_neyronov | valid epoch 2
ROC-AUC: 0.9569
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 2 | Train Loss: 0.5109 | Val ROC-AUC: 0.9569 | Val Profit: -1445
model_3_bolshe_neyronov | valid epoch 3
ROC-AUC: 0.9693
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 3 | Train Loss: 0.4088 | Val ROC-AUC: 0.9693 | Val Profit: -830
model_3_bolshe_neyronov | valid epoch 4
ROC-AUC: 0.9698
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 4 | Train Loss: 0.3122 | Val ROC-AUC: 0.9698 | Val Profit: -680
model_3_bolshe_neyronov | valid epoch 5
ROC-AUC: 0.9689
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 5 | Train Loss: 0.2802 | Val ROC-AUC: 0.9689 | Val Profit: -895
model_3_bolshe_neyronov | valid epoch 6
ROC-AUC: 0.9777
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 6 | Train Loss: 0.4156 | Val ROC-AUC: 0.9777 | Val Profit: -1170
model_3_bolshe_neyronov | valid epoch 7
ROC-AUC: 0.9663
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 7 | Train Loss: 0.2786 | Val ROC-AUC: 0.9663 | Val Profit: -805
model_3_bolshe_neyronov | valid epoch 8
ROC-AUC: 0.971
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 8 | Train Loss: 0.2564 | Val ROC-AUC: 0.9710 | Val Profit: -805
model_3_bolshe_neyronov | valid epoch 9
ROC-AUC: 0.9755
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 9 | Train Loss: 0.3469 | Val ROC-AUC: 0.9755 | Val Profit: -805
model_3_bolshe_neyronov | valid epoch 10
ROC-AUC: 0.9635
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 10 | Train Loss: 0.2660 | Val ROC-AUC: 0.9635 | Val Profit: -740
model_3_bolshe_neyronov | valid epoch 11
ROC-AUC: 0.9819
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 11 | Train Loss: 0.2710 | Val ROC-AUC: 0.9819 | Val Profit: -970
model_3_bolshe_neyronov | valid epoch 12
ROC-AUC: 0.986
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 12 | Train Loss: 0.2001 | Val ROC-AUC: 0.9860 | Val Profit: -545
model_3_bolshe_neyronov | valid epoch 13
ROC-AUC: 0.9816
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 13 | Train Loss: 0.1818 | Val ROC-AUC: 0.9816 | Val Profit: -595
model_3_bolshe_neyronov | valid epoch 14
ROC-AUC: 0.9777
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 14 | Train Loss: 0.2694 | Val ROC-AUC: 0.9777 | Val Profit: -895
model_3_bolshe_neyronov | valid epoch 15
ROC-AUC: 0.9769
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 15 | Train Loss: 0.1675 | Val ROC-AUC: 0.9769 | Val Profit: -455
model_3_bolshe_neyronov | valid epoch 16
ROC-AUC: 0.9732
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 16 | Train Loss: 0.2361 | Val ROC-AUC: 0.9732 | Val Profit: -780
model_3_bolshe_neyronov | valid epoch 17
ROC-AUC: 0.9859
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 17 | Train Loss: 0.2336 | Val ROC-AUC: 0.9859 | Val Profit: -795
model_3_bolshe_neyronov | valid epoch 18
ROC-AUC: 0.9913
Precision: 0.6333
Recall: 0.9048
F0.5-score: 0.6738
Profit: -190

Эпоха 18 | Train Loss: 0.1523 | Val ROC-AUC: 0.9913 | Val Profit: -190
model_3_bolshe_neyronov | valid epoch 19
ROC-AUC: 0.9842
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 19 | Train Loss: 0.3790 | Val ROC-AUC: 0.9842 | Val Profit: -670
model_3_bolshe_neyronov | valid epoch 20
ROC-AUC: 0.9831
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 20 | Train Loss: 0.2070 | Val ROC-AUC: 0.9831 | Val Profit: -520
model_3_bolshe_neyronov | valid epoch 21
ROC-AUC: 0.9742
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 21 | Train Loss: 0.2471 | Val ROC-AUC: 0.9742 | Val Profit: -720
model_3_bolshe_neyronov | valid epoch 22
ROC-AUC: 0.9866
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 22 | Train Loss: 0.2382 | Val ROC-AUC: 0.9866 | Val Profit: -820
model_3_bolshe_neyronov | valid epoch 23
ROC-AUC: 0.984
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 23 | Train Loss: 0.2187 | Val ROC-AUC: 0.9840 | Val Profit: -770
model_3_bolshe_neyronov | valid epoch 24
ROC-AUC: 0.9869
Precision: 0.6129
Recall: 0.9048
F0.5-score: 0.6552
Profit: -215

Эпоха 24 | Train Loss: 0.1338 | Val ROC-AUC: 0.9869 | Val Profit: -215
model_3_bolshe_neyronov | valid epoch 25
ROC-AUC: 0.967
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 25 | Train Loss: 0.7114 | Val ROC-AUC: 0.9670 | Val Profit: -1420
model_3_bolshe_neyronov | valid epoch 26
ROC-AUC: 0.9828
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 26 | Train Loss: 0.2433 | Val ROC-AUC: 0.9828 | Val Profit: -300
model_3_bolshe_neyronov | valid epoch 27
ROC-AUC: 0.9859
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 27 | Train Loss: 0.2530 | Val ROC-AUC: 0.9859 | Val Profit: -695
model_3_bolshe_neyronov | valid epoch 28
ROC-AUC: 0.9856
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 28 | Train Loss: 0.1529 | Val ROC-AUC: 0.9856 | Val Profit: -495
model_3_bolshe_neyronov | valid epoch 29
ROC-AUC: 0.9917
Precision: 0.5556
Recall: 0.9524
F0.5-score: 0.6061
Profit: -305

Эпоха 29 | Train Loss: 0.1242 | Val ROC-AUC: 0.9917 | Val Profit: -305
model_3_bolshe_neyronov | valid epoch 30
ROC-AUC: 0.9858
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 30 | Train Loss: 0.2105 | Val ROC-AUC: 0.9858 | Val Profit: -495

Лучшая эпоха для model_3_bolshe_neyronov: 29
Лучший ROC-AUC: 0.991683433936955
val
ROC-AUC: 0.9917
Precision: 0.5556
Recall: 0.9524
F0.5-score: 0.6061
Profit: -305

model_3_bolshe_neyronov | valid epoch 1
ROC-AUC: 0.9425
Precision: 0.3208
Recall: 0.8095
F0.5-score: 0.3648
Profit: -835

Эпоха 1 | Train Loss: 0.7848 | Val ROC-AUC: 0.9425 | Val Profit: -835
model_3_bolshe_neyronov | valid epoch 2
ROC-AUC: 0.9611
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 2 | Train Loss: 0.4968 | Val ROC-AUC: 0.9611 | Val Profit: -1545
model_3_bolshe_neyronov | valid epoch 3
ROC-AUC: 0.9624
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 3 | Train Loss: 0.4067 | Val ROC-AUC: 0.9624 | Val Profit: -740
model_3_bolshe_neyronov | valid epoch 4
ROC-AUC: 0.958
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 4 | Train Loss: 0.3339 | Val ROC-AUC: 0.9580 | Val Profit: -1170
model_3_bolshe_neyronov | valid epoch 5
ROC-AUC: 0.9718
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 5 | Train Loss: 0.3615 | Val ROC-AUC: 0.9718 | Val Profit: -1155
model_3_bolshe_neyronov | valid epoch 6
ROC-AUC: 0.972
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 6 | Train Loss: 0.2756 | Val ROC-AUC: 0.9720 | Val Profit: -565
model_3_bolshe_neyronov | valid epoch 7
ROC-AUC: 0.9725
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 7 | Train Loss: 0.2521 | Val ROC-AUC: 0.9725 | Val Profit: -740
model_3_bolshe_neyronov | valid epoch 8
ROC-AUC: 0.9732
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 8 | Train Loss: 0.2765 | Val ROC-AUC: 0.9732 | Val Profit: -945
model_3_bolshe_neyronov | valid epoch 9
ROC-AUC: 0.9716
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 9 | Train Loss: 0.3105 | Val ROC-AUC: 0.9716 | Val Profit: -515
model_3_bolshe_neyronov | valid epoch 10
ROC-AUC: 0.9831
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 10 | Train Loss: 0.2751 | Val ROC-AUC: 0.9831 | Val Profit: -945
model_3_bolshe_neyronov | valid epoch 11
ROC-AUC: 0.9804
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 11 | Train Loss: 0.2582 | Val ROC-AUC: 0.9804 | Val Profit: -820
model_3_bolshe_neyronov | valid epoch 12
ROC-AUC: 0.9883
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 12 | Train Loss: 0.2549 | Val ROC-AUC: 0.9883 | Val Profit: -595
model_3_bolshe_neyronov | valid epoch 13
ROC-AUC: 0.9854
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 13 | Train Loss: 0.2123 | Val ROC-AUC: 0.9854 | Val Profit: -620
model_3_bolshe_neyronov | valid epoch 14
ROC-AUC: 0.9839
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 14 | Train Loss: 0.1595 | Val ROC-AUC: 0.9839 | Val Profit: -555
model_3_bolshe_neyronov | valid epoch 15
ROC-AUC: 0.9765
Precision: 0.5
Recall: 0.9524
F0.5-score: 0.5525
Profit: -405

Эпоха 15 | Train Loss: 0.1706 | Val ROC-AUC: 0.9765 | Val Profit: -405
model_3_bolshe_neyronov | valid epoch 16
ROC-AUC: 0.9767
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 16 | Train Loss: 0.2592 | Val ROC-AUC: 0.9767 | Val Profit: -805
model_3_bolshe_neyronov | valid epoch 17
ROC-AUC: 0.9843
Precision: 0.4884
Recall: 1.0
F0.5-score: 0.544
Profit: -445

Эпоха 17 | Train Loss: 0.2492 | Val ROC-AUC: 0.9843 | Val Profit: -445
model_3_bolshe_neyronov | valid epoch 18
ROC-AUC: 0.9898
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 18 | Train Loss: 0.1858 | Val ROC-AUC: 0.9898 | Val Profit: -545
model_3_bolshe_neyronov | valid epoch 19
ROC-AUC: 0.981
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 19 | Train Loss: 0.1527 | Val ROC-AUC: 0.9810 | Val Profit: -330
model_3_bolshe_neyronov | valid epoch 20
ROC-AUC: 0.9846
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 20 | Train Loss: 0.1828 | Val ROC-AUC: 0.9846 | Val Profit: -495
model_3_bolshe_neyronov | valid epoch 21
ROC-AUC: 0.9909
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 21 | Train Loss: 0.1633 | Val ROC-AUC: 0.9909 | Val Profit: -455
model_3_bolshe_neyronov | valid epoch 22
ROC-AUC: 0.9763
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 22 | Train Loss: 0.2053 | Val ROC-AUC: 0.9763 | Val Profit: -630
model_3_bolshe_neyronov | valid epoch 23
ROC-AUC: 0.987
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 23 | Train Loss: 0.1316 | Val ROC-AUC: 0.9870 | Val Profit: -355
model_3_bolshe_neyronov | valid epoch 24
ROC-AUC: 0.9882
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 24 | Train Loss: 0.1260 | Val ROC-AUC: 0.9882 | Val Profit: -430
model_3_bolshe_neyronov | valid epoch 25
ROC-AUC: 0.9852
Precision: 0.5
Recall: 0.9524
F0.5-score: 0.5525
Profit: -405

Эпоха 25 | Train Loss: 0.1543 | Val ROC-AUC: 0.9852 | Val Profit: -405
model_3_bolshe_neyronov | valid epoch 26
ROC-AUC: 0.9836
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 26 | Train Loss: 0.2196 | Val ROC-AUC: 0.9836 | Val Profit: -955
model_3_bolshe_neyronov | valid epoch 27
ROC-AUC: 0.9891
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 27 | Train Loss: 0.2305 | Val ROC-AUC: 0.9891 | Val Profit: -570
model_3_bolshe_neyronov | valid epoch 28
ROC-AUC: 0.9893
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 28 | Train Loss: 0.1144 | Val ROC-AUC: 0.9893 | Val Profit: -290
model_3_bolshe_neyronov | valid epoch 29
ROC-AUC: 0.9882
Precision: 0.6429
Recall: 0.8571
F0.5-score: 0.6767
Profit: -175

Эпоха 29 | Train Loss: 0.0967 | Val ROC-AUC: 0.9882 | Val Profit: -175
model_3_bolshe_neyronov | valid epoch 30
ROC-AUC: 0.9894
Precision: 0.6552
Recall: 0.9048
F0.5-score: 0.6934
Profit: -165

Эпоха 30 | Train Loss: 0.0758 | Val ROC-AUC: 0.9894 | Val Profit: -165

Лучшая эпоха для model_3_bolshe_neyronov: 21
Лучший ROC-AUC: 0.990878604963112
val
ROC-AUC: 0.9909
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

model_3_bolshe_neyronov | valid epoch 1
ROC-AUC: 0.9586
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 1 | Train Loss: 0.9062 | Val ROC-AUC: 0.9586 | Val Profit: -1520
model_3_bolshe_neyronov | valid epoch 2
ROC-AUC: 0.9599
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 2 | Train Loss: 0.4444 | Val ROC-AUC: 0.9599 | Val Profit: -1095
model_3_bolshe_neyronov | valid epoch 3
ROC-AUC: 0.9612
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 3 | Train Loss: 0.3691 | Val ROC-AUC: 0.9612 | Val Profit: -930
model_3_bolshe_neyronov | valid epoch 4
ROC-AUC: 0.9679
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 4 | Train Loss: 0.3041 | Val ROC-AUC: 0.9679 | Val Profit: -680
model_3_bolshe_neyronov | valid epoch 5
ROC-AUC: 0.9658
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 5 | Train Loss: 0.2697 | Val ROC-AUC: 0.9658 | Val Profit: -755
model_3_bolshe_neyronov | valid epoch 6
ROC-AUC: 0.969
Precision: 0.3333
Recall: 0.9524
F0.5-score: 0.3831
Profit: -905

Эпоха 6 | Train Loss: 0.2454 | Val ROC-AUC: 0.9690 | Val Profit: -905
model_3_bolshe_neyronov | valid epoch 7
ROC-AUC: 0.9714
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 7 | Train Loss: 0.2276 | Val ROC-AUC: 0.9714 | Val Profit: -425
model_3_bolshe_neyronov | valid epoch 8
ROC-AUC: 0.974
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 8 | Train Loss: 0.2453 | Val ROC-AUC: 0.9740 | Val Profit: -605
model_3_bolshe_neyronov | valid epoch 9
ROC-AUC: 0.9716
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 9 | Train Loss: 0.1928 | Val ROC-AUC: 0.9716 | Val Profit: -540
model_3_bolshe_neyronov | valid epoch 10
ROC-AUC: 0.973
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 10 | Train Loss: 0.1748 | Val ROC-AUC: 0.9730 | Val Profit: -720
model_3_bolshe_neyronov | valid epoch 11
ROC-AUC: 0.974
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 11 | Train Loss: 0.2044 | Val ROC-AUC: 0.9740 | Val Profit: -705
model_3_bolshe_neyronov | valid epoch 12
ROC-AUC: 0.967
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 12 | Train Loss: 0.1910 | Val ROC-AUC: 0.9670 | Val Profit: -490
model_3_bolshe_neyronov | valid epoch 13
ROC-AUC: 0.9714
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 13 | Train Loss: 0.1986 | Val ROC-AUC: 0.9714 | Val Profit: -720
model_3_bolshe_neyronov | valid epoch 14
ROC-AUC: 0.9687
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 14 | Train Loss: 0.2118 | Val ROC-AUC: 0.9687 | Val Profit: -490
model_3_bolshe_neyronov | valid epoch 15
ROC-AUC: 0.9751
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 15 | Train Loss: 0.1885 | Val ROC-AUC: 0.9751 | Val Profit: -480
model_3_bolshe_neyronov | valid epoch 16
ROC-AUC: 0.978
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 16 | Train Loss: 0.1764 | Val ROC-AUC: 0.9780 | Val Profit: -500
model_3_bolshe_neyronov | valid epoch 17
ROC-AUC: 0.9805
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 17 | Train Loss: 0.1284 | Val ROC-AUC: 0.9805 | Val Profit: -325
model_3_bolshe_neyronov | valid epoch 18
ROC-AUC: 0.9789
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 18 | Train Loss: 0.1074 | Val ROC-AUC: 0.9789 | Val Profit: -355
model_3_bolshe_neyronov | valid epoch 19
ROC-AUC: 0.9799
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 19 | Train Loss: 0.0962 | Val ROC-AUC: 0.9799 | Val Profit: -280
model_3_bolshe_neyronov | valid epoch 20
ROC-AUC: 0.98
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 20 | Train Loss: 0.0833 | Val ROC-AUC: 0.9800 | Val Profit: -290
model_3_bolshe_neyronov | valid epoch 21
ROC-AUC: 0.9783
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 21 | Train Loss: 0.0919 | Val ROC-AUC: 0.9783 | Val Profit: -355
model_3_bolshe_neyronov | valid epoch 22
ROC-AUC: 0.9785
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 22 | Train Loss: 0.0859 | Val ROC-AUC: 0.9785 | Val Profit: -245
model_3_bolshe_neyronov | valid epoch 23
ROC-AUC: 0.9832
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

Эпоха 23 | Train Loss: 0.1034 | Val ROC-AUC: 0.9832 | Val Profit: -205
model_3_bolshe_neyronov | valid epoch 24
ROC-AUC: 0.9759
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 24 | Train Loss: 0.1897 | Val ROC-AUC: 0.9759 | Val Profit: -655
model_3_bolshe_neyronov | valid epoch 25
ROC-AUC: 0.9765
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 25 | Train Loss: 0.2923 | Val ROC-AUC: 0.9765 | Val Profit: -580
model_3_bolshe_neyronov | valid epoch 26
ROC-AUC: 0.9851
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 26 | Train Loss: 0.1758 | Val ROC-AUC: 0.9851 | Val Profit: -330
model_3_bolshe_neyronov | valid epoch 27
ROC-AUC: 0.984
Precision: 0.5882
Recall: 0.9524
F0.5-score: 0.6369
Profit: -255

Эпоха 27 | Train Loss: 0.1093 | Val ROC-AUC: 0.9840 | Val Profit: -255
model_3_bolshe_neyronov | valid epoch 28
ROC-AUC: 0.9878
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

Эпоха 28 | Train Loss: 0.0932 | Val ROC-AUC: 0.9878 | Val Profit: -205
model_3_bolshe_neyronov | valid epoch 29
ROC-AUC: 0.9851
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 29 | Train Loss: 0.0811 | Val ROC-AUC: 0.9851 | Val Profit: -330
model_3_bolshe_neyronov | valid epoch 30
ROC-AUC: 0.9854
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

Эпоха 30 | Train Loss: 0.0716 | Val ROC-AUC: 0.9854 | Val Profit: -205

Лучшая эпоха для model_3_bolshe_neyronov: 28
Лучший ROC-AUC: 0.9877934272300469
val
ROC-AUC: 0.9878
Precision: 0.625
Recall: 0.9524
F0.5-score: 0.6711
Profit: -205

model_3_bolshe_neyronov | valid epoch 1
ROC-AUC: 0.9571
Precision: 0.1615
Recall: 1.0
F0.5-score: 0.1941
Profit: -2620

Эпоха 1 | Train Loss: 1.0990 | Val ROC-AUC: 0.9571 | Val Profit: -2620
model_3_bolshe_neyronov | valid epoch 2
ROC-AUC: 0.9622
Precision: 0.2234
Recall: 1.0
F0.5-score: 0.2645
Profit: -1720

Эпоха 2 | Train Loss: 0.5891 | Val ROC-AUC: 0.9622 | Val Profit: -1720
model_3_bolshe_neyronov | valid epoch 3
ROC-AUC: 0.9622
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 3 | Train Loss: 0.4419 | Val ROC-AUC: 0.9622 | Val Profit: -1345
model_3_bolshe_neyronov | valid epoch 4
ROC-AUC: 0.9653
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 4 | Train Loss: 0.3847 | Val ROC-AUC: 0.9653 | Val Profit: -1420
model_3_bolshe_neyronov | valid epoch 5
ROC-AUC: 0.9674
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 5 | Train Loss: 0.3440 | Val ROC-AUC: 0.9674 | Val Profit: -1320
model_3_bolshe_neyronov | valid epoch 6
ROC-AUC: 0.9659
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 6 | Train Loss: 0.3056 | Val ROC-AUC: 0.9659 | Val Profit: -1245
model_3_bolshe_neyronov | valid epoch 7
ROC-AUC: 0.9651
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 7 | Train Loss: 0.2743 | Val ROC-AUC: 0.9651 | Val Profit: -1145
model_3_bolshe_neyronov | valid epoch 8
ROC-AUC: 0.9673
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 8 | Train Loss: 0.2484 | Val ROC-AUC: 0.9673 | Val Profit: -995
model_3_bolshe_neyronov | valid epoch 9
ROC-AUC: 0.9685
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 9 | Train Loss: 0.2252 | Val ROC-AUC: 0.9685 | Val Profit: -855
model_3_bolshe_neyronov | valid epoch 10
ROC-AUC: 0.9702
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 10 | Train Loss: 0.2046 | Val ROC-AUC: 0.9702 | Val Profit: -780
model_3_bolshe_neyronov | valid epoch 11
ROC-AUC: 0.9736
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 11 | Train Loss: 0.1871 | Val ROC-AUC: 0.9736 | Val Profit: -680
model_3_bolshe_neyronov | valid epoch 12
ROC-AUC: 0.9764
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695

In [63]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.005, 'profit': np.int64(-150), 'roc_auc': 0.984842387659289}

In [64]:
LR = best["lr"]

In [65]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 

model_3 = nn.Sequential(
    nn.Linear(9, 32),
    nn.ReLU(),
    nn.Linear(32, 64),
    nn.ReLU(),
    nn.Linear(64, 1),
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_3.parameters(), lr=LR)

config = {
    "model": "MLP_added_neurons",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_3)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_3_more_neurons", config=config)
log_file = new_log_file()

model_3 = train_model(
    model=model_3,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_3_bolshe_neyronov"
)


save_results(model_3, "model_3", log_file, run)

run.finish()

model_3_bolshe_neyronov | valid epoch 1
ROC-AUC: 0.9571
Precision: 0.1615
Recall: 1.0
F0.5-score: 0.1941
Profit: -2620

Эпоха 1 | Train Loss: 1.0990 | Val ROC-AUC: 0.9571 | Val Profit: -2620
model_3_bolshe_neyronov | valid epoch 2
ROC-AUC: 0.9622
Precision: 0.2234
Recall: 1.0
F0.5-score: 0.2645
Profit: -1720

Эпоха 2 | Train Loss: 0.5891 | Val ROC-AUC: 0.9622 | Val Profit: -1720
model_3_bolshe_neyronov | valid epoch 3
ROC-AUC: 0.9622
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 3 | Train Loss: 0.4419 | Val ROC-AUC: 0.9622 | Val Profit: -1345
model_3_bolshe_neyronov | valid epoch 4
ROC-AUC: 0.9653
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 4 | Train Loss: 0.3847 | Val ROC-AUC: 0.9653 | Val Profit: -1420
model_3_bolshe_neyronov | valid epoch 5
ROC-AUC: 0.9674
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 5 | Train Loss: 0.3440 | Val ROC-AUC: 0.9674 | Val Profit: -1320
model_3_bolshe_neyronov | valid epoch 6
ROC-AUC: 0.9659
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 6 | Train Loss: 0.3056 | Val ROC-AUC: 0.9659 | Val Profit: -1245
model_3_bolshe_neyronov | valid epoch 7
ROC-AUC: 0.9651
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 7 | Train Loss: 0.2743 | Val ROC-AUC: 0.9651 | Val Profit: -1145
model_3_bolshe_neyronov | valid epoch 8
ROC-AUC: 0.9673
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 8 | Train Loss: 0.2484 | Val ROC-AUC: 0.9673 | Val Profit: -995
model_3_bolshe_neyronov | valid epoch 9
ROC-AUC: 0.9685
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 9 | Train Loss: 0.2252 | Val ROC-AUC: 0.9685 | Val Profit: -855
model_3_bolshe_neyronov | valid epoch 10
ROC-AUC: 0.9702
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 10 | Train Loss: 0.2046 | Val ROC-AUC: 0.9702 | Val Profit: -780
model_3_bolshe_neyronov | valid epoch 11
ROC-AUC: 0.9736
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 11 | Train Loss: 0.1871 | Val ROC-AUC: 0.9736 | Val Profit: -680
model_3_bolshe_neyronov | valid epoch 12
ROC-AUC: 0.9764
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 12 | Train Loss: 0.1705 | Val ROC-AUC: 0.9764 | Val Profit: -605
model_3_bolshe_neyronov | valid epoch 13
ROC-AUC: 0.9764
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 13 | Train Loss: 0.1553 | Val ROC-AUC: 0.9764 | Val Profit: -605
model_3_bolshe_neyronov | valid epoch 14
ROC-AUC: 0.9779
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 14 | Train Loss: 0.1464 | Val ROC-AUC: 0.9779 | Val Profit: -555
model_3_bolshe_neyronov | valid epoch 15
ROC-AUC: 0.9796
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 15 | Train Loss: 0.1309 | Val ROC-AUC: 0.9796 | Val Profit: -555
model_3_bolshe_neyronov | valid epoch 16
ROC-AUC: 0.9795
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 16 | Train Loss: 0.1200 | Val ROC-AUC: 0.9795 | Val Profit: -580
model_3_bolshe_neyronov | valid epoch 17
ROC-AUC: 0.9792
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 17 | Train Loss: 0.1107 | Val ROC-AUC: 0.9792 | Val Profit: -380
model_3_bolshe_neyronov | valid epoch 18
ROC-AUC: 0.9814
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 18 | Train Loss: 0.1029 | Val ROC-AUC: 0.9814 | Val Profit: -380
model_3_bolshe_neyronov | valid epoch 19
ROC-AUC: 0.9826
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 19 | Train Loss: 0.0951 | Val ROC-AUC: 0.9826 | Val Profit: -280
model_3_bolshe_neyronov | valid epoch 20
ROC-AUC: 0.9832
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 20 | Train Loss: 0.0842 | Val ROC-AUC: 0.9832 | Val Profit: -265
model_3_bolshe_neyronov | valid epoch 21
ROC-AUC: 0.9834
Precision: 0.6333
Recall: 0.9048
F0.5-score: 0.6738
Profit: -190

Эпоха 21 | Train Loss: 0.0731 | Val ROC-AUC: 0.9834 | Val Profit: -190
model_3_bolshe_neyronov | valid epoch 22
ROC-AUC: 0.9824
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 22 | Train Loss: 0.0675 | Val ROC-AUC: 0.9824 | Val Profit: -290
model_3_bolshe_neyronov | valid epoch 23
ROC-AUC: 0.9824
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 23 | Train Loss: 0.0645 | Val ROC-AUC: 0.9824 | Val Profit: -265
model_3_bolshe_neyronov | valid epoch 24
ROC-AUC: 0.9843
Precision: 0.6207
Recall: 0.8571
F0.5-score: 0.6569
Profit: -200

Эпоха 24 | Train Loss: 0.0582 | Val ROC-AUC: 0.9843 | Val Profit: -200
model_3_bolshe_neyronov | valid epoch 25
ROC-AUC: 0.9848
Precision: 0.6667
Recall: 0.8571
F0.5-score: 0.6977
Profit: -150

Эпоха 25 | Train Loss: 0.0520 | Val ROC-AUC: 0.9848 | Val Profit: -150
model_3_bolshe_neyronov | valid epoch 26
ROC-AUC: 0.9805
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 26 | Train Loss: 0.0631 | Val ROC-AUC: 0.9805 | Val Profit: -365
model_3_bolshe_neyronov | valid epoch 27
ROC-AUC: 0.9814
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 27 | Train Loss: 0.0687 | Val ROC-AUC: 0.9814 | Val Profit: -265
model_3_bolshe_neyronov | valid epoch 28
ROC-AUC: 0.9784
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 28 | Train Loss: 0.1127 | Val ROC-AUC: 0.9784 | Val Profit: -365
model_3_bolshe_neyronov | valid epoch 29
ROC-AUC: 0.9771
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 29 | Train Loss: 0.1032 | Val ROC-AUC: 0.9771 | Val Profit: -365
model_3_bolshe_neyronov | valid epoch 30
ROC-AUC: 0.984
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 30 | Train Loss: 0.1118 | Val ROC-AUC: 0.9840 | Val Profit: -280

Лучшая эпоха для model_3_bolshe_neyronov: 25
Лучший ROC-AUC: 0.984842387659289
Train
ROC-AUC: 0.9996
Precision: 0.8737
Recall: 1.0
F0.5-score: 0.8963
Profit: 115

Test
ROC-AUC: 0.9861
Precision: 0.6325
Recall: 0.8125
F0.5-score: 0.6618
Profit: -205930

In [66]:
train_metrics = evaluate_model(model_3, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_3, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9996
Precision: 0.8737
Recall: 1.0
F0.5-score: 0.8963
Profit: 115

Test
ROC-AUC: 0.9861
Precision: 0.6325
Recall: 0.8125
F0.5-score: 0.6618
Profit: -205930

Увеличение количества нейронов в 2 раза тоже улучшило качество. Однако profit все еще хуже бейзлайна

Из интересного, если увеличить колво нейронов в 4 раза, то качество станет хуже

## model_4_tolko_batchnorm

In [67]:
EPOCHS = 30
SEED = 42

In [68]:
wandb.init(mode="disabled")
results = []
for LR in [0.05, 0.03, 0.01, 0.005, 0.002, 0.0001]:
        random.seed(SEED)
        np.random.seed(SEED)
        torch.manual_seed(SEED) 

        model_4 = nn.Sequential(
            nn.Linear(9, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),

            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),

            nn.Linear(32, 16),
            nn.BatchNorm1d(16),
            nn.ReLU(),

            nn.Linear(16, 8),
            nn.BatchNorm1d(8),
            nn.ReLU(),

            nn.Linear(8, 1)
        )

        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.Adam(model_4.parameters(), lr=LR)

        model_4 = train_model(
            model=model_4,
            train_loader=train_loader,
            X_valid=X_val,
            y_valid=y_val,
            loss_fn=loss_fn,
            optimizer=optimizer,
            epochs=EPOCHS,
            threshold=0.5,
            model_name="model_4_tolko_batchnorm"
        )

        val = evaluate_model(model_4, X_val, y_val, threshold=0.5, name="val")
        results.append({"lr": LR, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_4_tolko_batchnorm | valid epoch 1
ROC-AUC: 0.9754
Precision: 0.1429
Recall: 1.0
F0.5-score: 0.1724
Profit: -3045

Эпоха 1 | Train Loss: 0.9049 | Val ROC-AUC: 0.9754 | Val Profit: -3045
model_4_tolko_batchnorm | valid epoch 2
ROC-AUC: 0.9616
Precision: 0.2143
Recall: 1.0
F0.5-score: 0.2542
Profit: -1820

Эпоха 2 | Train Loss: 0.4806 | Val ROC-AUC: 0.9616 | Val Profit: -1820
model_4_tolko_batchnorm | valid epoch 3
ROC-AUC: 0.9646
Precision: 0.181
Recall: 1.0
F0.5-score: 0.2165
Profit: -2270

Эпоха 3 | Train Loss: 0.5201 | Val ROC-AUC: 0.9646 | Val Profit: -2270
model_4_tolko_batchnorm | valid epoch 4
ROC-AUC: 0.9667
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 4 | Train Loss: 0.4696 | Val ROC-AUC: 0.9667 | Val Profit: -1645
model_4_tolko_batchnorm | valid epoch 5
ROC-AUC: 0.9683
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 5 | Train Loss: 0.3298 | Val ROC-AUC: 0.9683 | Val Profit: -335
model_4_tolko_batchnorm | valid epoch 6
ROC-AUC: 0.9698
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 6 | Train Loss: 0.3863 | Val ROC-AUC: 0.9698 | Val Profit: -1270
model_4_tolko_batchnorm | valid epoch 7
ROC-AUC: 0.9785
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 7 | Train Loss: 0.2890 | Val ROC-AUC: 0.9785 | Val Profit: -245
model_4_tolko_batchnorm | valid epoch 8
ROC-AUC: 0.9678
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 8 | Train Loss: 0.2599 | Val ROC-AUC: 0.9678 | Val Profit: -210
model_4_tolko_batchnorm | valid epoch 9
ROC-AUC: 0.9792
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 9 | Train Loss: 0.3821 | Val ROC-AUC: 0.9792 | Val Profit: -1770
model_4_tolko_batchnorm | valid epoch 10
ROC-AUC: 0.9751
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 10 | Train Loss: 0.2825 | Val ROC-AUC: 0.9751 | Val Profit: -280
model_4_tolko_batchnorm | valid epoch 11
ROC-AUC: 0.9696
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 11 | Train Loss: 0.2367 | Val ROC-AUC: 0.9696 | Val Profit: -70
model_4_tolko_batchnorm | valid epoch 12
ROC-AUC: 0.9697
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 12 | Train Loss: 0.2197 | Val ROC-AUC: 0.9697 | Val Profit: -355
model_4_tolko_batchnorm | valid epoch 13
ROC-AUC: 0.982
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 13 | Train Loss: 0.3439 | Val ROC-AUC: 0.9820 | Val Profit: -1320
model_4_tolko_batchnorm | valid epoch 14
ROC-AUC: 0.9757
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 14 | Train Loss: 0.2798 | Val ROC-AUC: 0.9757 | Val Profit: -250
model_4_tolko_batchnorm | valid epoch 15
ROC-AUC: 0.9713
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 15 | Train Loss: 0.2028 | Val ROC-AUC: 0.9713 | Val Profit: -185
model_4_tolko_batchnorm | valid epoch 16
ROC-AUC: 0.9745
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 16 | Train Loss: 0.2246 | Val ROC-AUC: 0.9745 | Val Profit: -275
model_4_tolko_batchnorm | valid epoch 17
ROC-AUC: 0.9709
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 17 | Train Loss: 0.1934 | Val ROC-AUC: 0.9709 | Val Profit: -245
model_4_tolko_batchnorm | valid epoch 18
ROC-AUC: 0.9654
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 18 | Train Loss: 0.1735 | Val ROC-AUC: 0.9654 | Val Profit: -360
model_4_tolko_batchnorm | valid epoch 19
ROC-AUC: 0.9847
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 19 | Train Loss: 0.3133 | Val ROC-AUC: 0.9847 | Val Profit: -1420
model_4_tolko_batchnorm | valid epoch 20
ROC-AUC: 0.9818
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 20 | Train Loss: 0.2643 | Val ROC-AUC: 0.9818 | Val Profit: -330
model_4_tolko_batchnorm | valid epoch 21
ROC-AUC: 0.9836
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.2132 | Val ROC-AUC: 0.9836 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 22
ROC-AUC: 0.9823
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.1639 | Val ROC-AUC: 0.9823 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 23
ROC-AUC: 0.981
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 23 | Train Loss: 0.1574 | Val ROC-AUC: 0.9810 | Val Profit: -245
model_4_tolko_batchnorm | valid epoch 24
ROC-AUC: 0.989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.1718 | Val ROC-AUC: 0.9890 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 25
ROC-AUC: 0.9843
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 25 | Train Loss: 0.2339 | Val ROC-AUC: 0.9843 | Val Profit: -1345
model_4_tolko_batchnorm | valid epoch 26
ROC-AUC: 0.9869
Precision: 0.525
Recall: 1.0
F0.5-score: 0.5801
Profit: -370

Эпоха 26 | Train Loss: 0.2472 | Val ROC-AUC: 0.9869 | Val Profit: -370
model_4_tolko_batchnorm | valid epoch 27
ROC-AUC: 0.9842
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 27 | Train Loss: 0.1877 | Val ROC-AUC: 0.9842 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 28
ROC-AUC: 0.9898
Precision: 1.0
Recall: 0.619
F0.5-score: 0.8904
Profit: 25

Эпоха 28 | Train Loss: 0.1950 | Val ROC-AUC: 0.9898 | Val Profit: 25
model_4_tolko_batchnorm | valid epoch 29
ROC-AUC: 0.9811
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 29 | Train Loss: 0.1958 | Val ROC-AUC: 0.9811 | Val Profit: -180
model_4_tolko_batchnorm | valid epoch 30
ROC-AUC: 0.9791
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 30 | Train Loss: 0.2084 | Val ROC-AUC: 0.9791 | Val Profit: -210

Лучшая эпоха для model_4_tolko_batchnorm: 28
Лучший ROC-AUC: 0.9898054996646546
val
ROC-AUC: 0.9898
Precision: 1.0
Recall: 0.619
F0.5-score: 0.8904
Profit: 25

model_4_tolko_batchnorm | valid epoch 1
ROC-AUC: 0.9592
Precision: 0.1489
Recall: 1.0
F0.5-score: 0.1795
Profit: -2895

Эпоха 1 | Train Loss: 0.9223 | Val ROC-AUC: 0.9592 | Val Profit: -2895
model_4_tolko_batchnorm | valid epoch 2
ROC-AUC: 0.9658
Precision: 0.1628
Recall: 1.0
F0.5-score: 0.1955
Profit: -2595

Эпоха 2 | Train Loss: 0.5851 | Val ROC-AUC: 0.9658 | Val Profit: -2595
model_4_tolko_batchnorm | valid epoch 3
ROC-AUC: 0.969
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 3 | Train Loss: 0.3617 | Val ROC-AUC: 0.9690 | Val Profit: -1520
model_4_tolko_batchnorm | valid epoch 4
ROC-AUC: 0.9647
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 4 | Train Loss: 0.3996 | Val ROC-AUC: 0.9647 | Val Profit: -1495
model_4_tolko_batchnorm | valid epoch 5
ROC-AUC: 0.9751
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 5 | Train Loss: 0.3029 | Val ROC-AUC: 0.9751 | Val Profit: -645
model_4_tolko_batchnorm | valid epoch 6
ROC-AUC: 0.9661
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 6 | Train Loss: 0.2794 | Val ROC-AUC: 0.9661 | Val Profit: -360
model_4_tolko_batchnorm | valid epoch 7
ROC-AUC: 0.9784
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 7 | Train Loss: 0.3187 | Val ROC-AUC: 0.9784 | Val Profit: -605
model_4_tolko_batchnorm | valid epoch 8
ROC-AUC: 0.9737
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 8 | Train Loss: 0.2582 | Val ROC-AUC: 0.9737 | Val Profit: -505
model_4_tolko_batchnorm | valid epoch 9
ROC-AUC: 0.9547
Precision: 0.274
Recall: 0.9524
F0.5-score: 0.3195
Profit: -1230

Эпоха 9 | Train Loss: 0.2962 | Val ROC-AUC: 0.9547 | Val Profit: -1230
model_4_tolko_batchnorm | valid epoch 10
ROC-AUC: 0.983
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 10 | Train Loss: 0.3120 | Val ROC-AUC: 0.9830 | Val Profit: -480
model_4_tolko_batchnorm | valid epoch 11
ROC-AUC: 0.9734
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 11 | Train Loss: 0.2022 | Val ROC-AUC: 0.9734 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 12
ROC-AUC: 0.9706
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 12 | Train Loss: 0.2434 | Val ROC-AUC: 0.9706 | Val Profit: -400
model_4_tolko_batchnorm | valid epoch 13
ROC-AUC: 0.9807
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 13 | Train Loss: 0.2216 | Val ROC-AUC: 0.9807 | Val Profit: -100
model_4_tolko_batchnorm | valid epoch 14
ROC-AUC: 0.9704
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 14 | Train Loss: 0.2613 | Val ROC-AUC: 0.9704 | Val Profit: -1295
model_4_tolko_batchnorm | valid epoch 15
ROC-AUC: 0.9626
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 15 | Train Loss: 0.2868 | Val ROC-AUC: 0.9626 | Val Profit: -690
model_4_tolko_batchnorm | valid epoch 16
ROC-AUC: 0.983
Precision: 0.5556
Recall: 0.9524
F0.5-score: 0.6061
Profit: -305

Эпоха 16 | Train Loss: 0.2548 | Val ROC-AUC: 0.9830 | Val Profit: -305
model_4_tolko_batchnorm | valid epoch 17
ROC-AUC: 0.9795
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 17 | Train Loss: 0.2000 | Val ROC-AUC: 0.9795 | Val Profit: -135
model_4_tolko_batchnorm | valid epoch 18
ROC-AUC: 0.9797
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.1520 | Val ROC-AUC: 0.9797 | Val Profit: -100
model_4_tolko_batchnorm | valid epoch 19
ROC-AUC: 0.9815
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 19 | Train Loss: 0.1461 | Val ROC-AUC: 0.9815 | Val Profit: -65
model_4_tolko_batchnorm | valid epoch 20
ROC-AUC: 0.9618
Precision: 0.1826
Recall: 1.0
F0.5-score: 0.2183
Profit: -2245

Эпоха 20 | Train Loss: 0.3765 | Val ROC-AUC: 0.9618 | Val Profit: -2245
model_4_tolko_batchnorm | valid epoch 21
ROC-AUC: 0.9702
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 21 | Train Loss: 0.3916 | Val ROC-AUC: 0.9702 | Val Profit: -1495
model_4_tolko_batchnorm | valid epoch 22
ROC-AUC: 0.9761
Precision: 0.3333
Recall: 0.9524
F0.5-score: 0.3831
Profit: -905

Эпоха 22 | Train Loss: 0.3143 | Val ROC-AUC: 0.9761 | Val Profit: -905
model_4_tolko_batchnorm | valid epoch 23
ROC-AUC: 0.9773
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 23 | Train Loss: 0.2553 | Val ROC-AUC: 0.9773 | Val Profit: -365
model_4_tolko_batchnorm | valid epoch 24
ROC-AUC: 0.9779
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 24 | Train Loss: 0.2272 | Val ROC-AUC: 0.9779 | Val Profit: -255
model_4_tolko_batchnorm | valid epoch 25
ROC-AUC: 0.9728
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 25 | Train Loss: 0.1819 | Val ROC-AUC: 0.9728 | Val Profit: -150
model_4_tolko_batchnorm | valid epoch 26
ROC-AUC: 0.9708
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 26 | Train Loss: 0.1669 | Val ROC-AUC: 0.9708 | Val Profit: -110
model_4_tolko_batchnorm | valid epoch 27
ROC-AUC: 0.9755
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 27 | Train Loss: 0.1549 | Val ROC-AUC: 0.9755 | Val Profit: -75
model_4_tolko_batchnorm | valid epoch 28
ROC-AUC: 0.9763
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 28 | Train Loss: 0.2170 | Val ROC-AUC: 0.9763 | Val Profit: -490
model_4_tolko_batchnorm | valid epoch 29
ROC-AUC: 0.981
Precision: 0.8235
Recall: 0.6667
F0.5-score: 0.7865
Profit: -40

Эпоха 29 | Train Loss: 0.1817 | Val ROC-AUC: 0.9810 | Val Profit: -40
model_4_tolko_batchnorm | valid epoch 30
ROC-AUC: 0.9615
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 30 | Train Loss: 0.1304 | Val ROC-AUC: 0.9615 | Val Profit: -80

Лучшая эпоха для model_4_tolko_batchnorm: 10
Лучший ROC-AUC: 0.9829644533869886
val
ROC-AUC: 0.983
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

model_4_tolko_batchnorm | valid epoch 1
ROC-AUC: 0.9533
Precision: 0.1355
Recall: 1.0
F0.5-score: 0.1638
Profit: -3245

Эпоха 1 | Train Loss: 0.9802 | Val ROC-AUC: 0.9533 | Val Profit: -3245
model_4_tolko_batchnorm | valid epoch 2
ROC-AUC: 0.9645
Precision: 0.2079
Recall: 1.0
F0.5-score: 0.2471
Profit: -1895

Эпоха 2 | Train Loss: 0.5630 | Val ROC-AUC: 0.9645 | Val Profit: -1895
model_4_tolko_batchnorm | valid epoch 3
ROC-AUC: 0.9598
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 3 | Train Loss: 0.4020 | Val ROC-AUC: 0.9598 | Val Profit: -1470
model_4_tolko_batchnorm | valid epoch 4
ROC-AUC: 0.9632
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 4 | Train Loss: 0.3919 | Val ROC-AUC: 0.9632 | Val Profit: -1470
model_4_tolko_batchnorm | valid epoch 5
ROC-AUC: 0.9767
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 5 | Train Loss: 0.3272 | Val ROC-AUC: 0.9767 | Val Profit: -845
model_4_tolko_batchnorm | valid epoch 6
ROC-AUC: 0.95
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 6 | Train Loss: 0.2325 | Val ROC-AUC: 0.9500 | Val Profit: -355
model_4_tolko_batchnorm | valid epoch 7
ROC-AUC: 0.9619
Precision: 0.2703
Recall: 0.9524
F0.5-score: 0.3155
Profit: -1255

Эпоха 7 | Train Loss: 0.3308 | Val ROC-AUC: 0.9619 | Val Profit: -1255
model_4_tolko_batchnorm | valid epoch 8
ROC-AUC: 0.9831
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 8 | Train Loss: 0.2934 | Val ROC-AUC: 0.9831 | Val Profit: -595
model_4_tolko_batchnorm | valid epoch 9
ROC-AUC: 0.9784
Precision: 0.7273
Recall: 0.7619
F0.5-score: 0.7339
Profit: -95

Эпоха 9 | Train Loss: 0.2199 | Val ROC-AUC: 0.9784 | Val Profit: -95
model_4_tolko_batchnorm | valid epoch 10
ROC-AUC: 0.9773
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 10 | Train Loss: 0.1722 | Val ROC-AUC: 0.9773 | Val Profit: -135
model_4_tolko_batchnorm | valid epoch 11
ROC-AUC: 0.9119
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 11 | Train Loss: 0.1376 | Val ROC-AUC: 0.9119 | Val Profit: -170
model_4_tolko_batchnorm | valid epoch 12
ROC-AUC: 0.9725
Precision: 0.2039
Recall: 1.0
F0.5-score: 0.2425
Profit: -1945

Эпоха 12 | Train Loss: 0.4236 | Val ROC-AUC: 0.9725 | Val Profit: -1945
model_4_tolko_batchnorm | valid epoch 13
ROC-AUC: 0.9738
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 13 | Train Loss: 0.2996 | Val ROC-AUC: 0.9738 | Val Profit: -770
model_4_tolko_batchnorm | valid epoch 14
ROC-AUC: 0.9733
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 14 | Train Loss: 0.2532 | Val ROC-AUC: 0.9733 | Val Profit: -505
model_4_tolko_batchnorm | valid epoch 15
ROC-AUC: 0.9728
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 15 | Train Loss: 0.2189 | Val ROC-AUC: 0.9728 | Val Profit: -215
model_4_tolko_batchnorm | valid epoch 16
ROC-AUC: 0.9767
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 16 | Train Loss: 0.2215 | Val ROC-AUC: 0.9767 | Val Profit: -265
model_4_tolko_batchnorm | valid epoch 17
ROC-AUC: 0.9755
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 17 | Train Loss: 0.1795 | Val ROC-AUC: 0.9755 | Val Profit: -205
model_4_tolko_batchnorm | valid epoch 18
ROC-AUC: 0.9764
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 18 | Train Loss: 0.1410 | Val ROC-AUC: 0.9764 | Val Profit: -120
model_4_tolko_batchnorm | valid epoch 19
ROC-AUC: 0.974
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 19 | Train Loss: 0.1280 | Val ROC-AUC: 0.9740 | Val Profit: -125
model_4_tolko_batchnorm | valid epoch 20
ROC-AUC: 0.9698
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 20 | Train Loss: 0.1437 | Val ROC-AUC: 0.9698 | Val Profit: -205
model_4_tolko_batchnorm | valid epoch 21
ROC-AUC: 0.9462
Precision: 0.2817
Recall: 0.9524
F0.5-score: 0.3279
Profit: -1180

Эпоха 21 | Train Loss: 0.3151 | Val ROC-AUC: 0.9462 | Val Profit: -1180
model_4_tolko_batchnorm | valid epoch 22
ROC-AUC: 0.969
Precision: 0.2703
Recall: 0.9524
F0.5-score: 0.3155
Profit: -1255

Эпоха 22 | Train Loss: 0.3298 | Val ROC-AUC: 0.9690 | Val Profit: -1255
model_4_tolko_batchnorm | valid epoch 23
ROC-AUC: 0.9788
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 23 | Train Loss: 0.3035 | Val ROC-AUC: 0.9788 | Val Profit: -630
model_4_tolko_batchnorm | valid epoch 24
ROC-AUC: 0.9783
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 24 | Train Loss: 0.2519 | Val ROC-AUC: 0.9783 | Val Profit: -375
model_4_tolko_batchnorm | valid epoch 25
ROC-AUC: 0.9775
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 25 | Train Loss: 0.2230 | Val ROC-AUC: 0.9775 | Val Profit: -285
model_4_tolko_batchnorm | valid epoch 26
ROC-AUC: 0.9776
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 26 | Train Loss: 0.2013 | Val ROC-AUC: 0.9776 | Val Profit: -230
model_4_tolko_batchnorm | valid epoch 27
ROC-AUC: 0.9769
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 27 | Train Loss: 0.1799 | Val ROC-AUC: 0.9769 | Val Profit: -115
model_4_tolko_batchnorm | valid epoch 28
ROC-AUC: 0.9752
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 28 | Train Loss: 0.1591 | Val ROC-AUC: 0.9752 | Val Profit: -105
model_4_tolko_batchnorm | valid epoch 29
ROC-AUC: 0.9746
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 29 | Train Loss: 0.1385 | Val ROC-AUC: 0.9746 | Val Profit: -165
model_4_tolko_batchnorm | valid epoch 30
ROC-AUC: 0.9741
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.1202 | Val ROC-AUC: 0.9741 | Val Profit: -100

Лучшая эпоха для model_4_tolko_batchnorm: 8
Лучший ROC-AUC: 0.9830985915492958
val
ROC-AUC: 0.9831
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

model_4_tolko_batchnorm | valid epoch 1
ROC-AUC: 0.9282
Precision: 0.1296
Recall: 1.0
F0.5-score: 0.157
Profit: -3420

Эпоха 1 | Train Loss: 1.1145 | Val ROC-AUC: 0.9282 | Val Profit: -3420
model_4_tolko_batchnorm | valid epoch 2
ROC-AUC: 0.9683
Precision: 0.2079
Recall: 1.0
F0.5-score: 0.2471
Profit: -1895

Эпоха 2 | Train Loss: 0.7320 | Val ROC-AUC: 0.9683 | Val Profit: -1895
model_4_tolko_batchnorm | valid epoch 3
ROC-AUC: 0.9654
Precision: 0.339
Recall: 0.9524
F0.5-score: 0.3891
Profit: -880

Эпоха 3 | Train Loss: 0.4923 | Val ROC-AUC: 0.9654 | Val Profit: -880
model_4_tolko_batchnorm | valid epoch 4
ROC-AUC: 0.9612
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 4 | Train Loss: 0.3991 | Val ROC-AUC: 0.9612 | Val Profit: -1020
model_4_tolko_batchnorm | valid epoch 5
ROC-AUC: 0.9635
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 5 | Train Loss: 0.3219 | Val ROC-AUC: 0.9635 | Val Profit: -815
model_4_tolko_batchnorm | valid epoch 6
ROC-AUC: 0.9241
Precision: 0.3659
Recall: 0.7143
F0.5-score: 0.4054
Profit: -605

Эпоха 6 | Train Loss: 0.2662 | Val ROC-AUC: 0.9241 | Val Profit: -605
model_4_tolko_batchnorm | valid epoch 7
ROC-AUC: 0.9689
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 7 | Train Loss: 0.3342 | Val ROC-AUC: 0.9689 | Val Profit: -1295
model_4_tolko_batchnorm | valid epoch 8
ROC-AUC: 0.9779
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 8 | Train Loss: 0.3449 | Val ROC-AUC: 0.9779 | Val Profit: -970
model_4_tolko_batchnorm | valid epoch 9
ROC-AUC: 0.9606
Precision: 0.3902
Recall: 0.7619
F0.5-score: 0.4324
Profit: -570

Эпоха 9 | Train Loss: 0.2326 | Val ROC-AUC: 0.9606 | Val Profit: -570
model_4_tolko_batchnorm | valid epoch 10
ROC-AUC: 0.9805
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 10 | Train Loss: 0.2392 | Val ROC-AUC: 0.9805 | Val Profit: -235
model_4_tolko_batchnorm | valid epoch 11
ROC-AUC: 0.9367
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 11 | Train Loss: 0.1669 | Val ROC-AUC: 0.9367 | Val Profit: -105
model_4_tolko_batchnorm | valid epoch 12
ROC-AUC: 0.9765
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870


In [69]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.05, 'profit': np.int64(25), 'roc_auc': 0.9898054996646546}

In [70]:
LR = best["lr"]

In [71]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_4 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),

    nn.Linear(8, 1)
)

config = {
    "model": "MLP_batchnorm_only",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_4)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_4_batchnorm_only", config=config)
log_file = new_log_file()

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_4.parameters(), lr=LR)

model_4 = train_model(
    model=model_4,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_4_tolko_batchnorm"
)


save_results(model_4, "model_4", log_file, run)

run.finish()

model_4_tolko_batchnorm | valid epoch 1
ROC-AUC: 0.9754
Precision: 0.1429
Recall: 1.0
F0.5-score: 0.1724
Profit: -3045

Эпоха 1 | Train Loss: 0.9049 | Val ROC-AUC: 0.9754 | Val Profit: -3045
model_4_tolko_batchnorm | valid epoch 2
ROC-AUC: 0.9616
Precision: 0.2143
Recall: 1.0
F0.5-score: 0.2542
Profit: -1820

Эпоха 2 | Train Loss: 0.4806 | Val ROC-AUC: 0.9616 | Val Profit: -1820
model_4_tolko_batchnorm | valid epoch 3
ROC-AUC: 0.9646
Precision: 0.181
Recall: 1.0
F0.5-score: 0.2165
Profit: -2270

Эпоха 3 | Train Loss: 0.5201 | Val ROC-AUC: 0.9646 | Val Profit: -2270
model_4_tolko_batchnorm | valid epoch 4
ROC-AUC: 0.9667
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 4 | Train Loss: 0.4696 | Val ROC-AUC: 0.9667 | Val Profit: -1645
model_4_tolko_batchnorm | valid epoch 5
ROC-AUC: 0.9683
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 5 | Train Loss: 0.3298 | Val ROC-AUC: 0.9683 | Val Profit: -335
model_4_tolko_batchnorm | valid epoch 6
ROC-AUC: 0.9698
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 6 | Train Loss: 0.3863 | Val ROC-AUC: 0.9698 | Val Profit: -1270
model_4_tolko_batchnorm | valid epoch 7
ROC-AUC: 0.9785
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 7 | Train Loss: 0.2890 | Val ROC-AUC: 0.9785 | Val Profit: -245
model_4_tolko_batchnorm | valid epoch 8
ROC-AUC: 0.9678
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 8 | Train Loss: 0.2599 | Val ROC-AUC: 0.9678 | Val Profit: -210
model_4_tolko_batchnorm | valid epoch 9
ROC-AUC: 0.9792
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 9 | Train Loss: 0.3821 | Val ROC-AUC: 0.9792 | Val Profit: -1770
model_4_tolko_batchnorm | valid epoch 10
ROC-AUC: 0.9751
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 10 | Train Loss: 0.2825 | Val ROC-AUC: 0.9751 | Val Profit: -280
model_4_tolko_batchnorm | valid epoch 11
ROC-AUC: 0.9696
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 11 | Train Loss: 0.2367 | Val ROC-AUC: 0.9696 | Val Profit: -70
model_4_tolko_batchnorm | valid epoch 12
ROC-AUC: 0.9697
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 12 | Train Loss: 0.2197 | Val ROC-AUC: 0.9697 | Val Profit: -355
model_4_tolko_batchnorm | valid epoch 13
ROC-AUC: 0.982
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 13 | Train Loss: 0.3439 | Val ROC-AUC: 0.9820 | Val Profit: -1320
model_4_tolko_batchnorm | valid epoch 14
ROC-AUC: 0.9757
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 14 | Train Loss: 0.2798 | Val ROC-AUC: 0.9757 | Val Profit: -250
model_4_tolko_batchnorm | valid epoch 15
ROC-AUC: 0.9713
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 15 | Train Loss: 0.2028 | Val ROC-AUC: 0.9713 | Val Profit: -185
model_4_tolko_batchnorm | valid epoch 16
ROC-AUC: 0.9745
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 16 | Train Loss: 0.2246 | Val ROC-AUC: 0.9745 | Val Profit: -275
model_4_tolko_batchnorm | valid epoch 17
ROC-AUC: 0.9709
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 17 | Train Loss: 0.1934 | Val ROC-AUC: 0.9709 | Val Profit: -245
model_4_tolko_batchnorm | valid epoch 18
ROC-AUC: 0.9654
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 18 | Train Loss: 0.1735 | Val ROC-AUC: 0.9654 | Val Profit: -360
model_4_tolko_batchnorm | valid epoch 19
ROC-AUC: 0.9847
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 19 | Train Loss: 0.3133 | Val ROC-AUC: 0.9847 | Val Profit: -1420
model_4_tolko_batchnorm | valid epoch 20
ROC-AUC: 0.9818
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 20 | Train Loss: 0.2643 | Val ROC-AUC: 0.9818 | Val Profit: -330
model_4_tolko_batchnorm | valid epoch 21
ROC-AUC: 0.9836
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.2132 | Val ROC-AUC: 0.9836 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 22
ROC-AUC: 0.9823
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.1639 | Val ROC-AUC: 0.9823 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 23
ROC-AUC: 0.981
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 23 | Train Loss: 0.1574 | Val ROC-AUC: 0.9810 | Val Profit: -245
model_4_tolko_batchnorm | valid epoch 24
ROC-AUC: 0.989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.1718 | Val ROC-AUC: 0.9890 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 25
ROC-AUC: 0.9843
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 25 | Train Loss: 0.2339 | Val ROC-AUC: 0.9843 | Val Profit: -1345
model_4_tolko_batchnorm | valid epoch 26
ROC-AUC: 0.9869
Precision: 0.525
Recall: 1.0
F0.5-score: 0.5801
Profit: -370

Эпоха 26 | Train Loss: 0.2472 | Val ROC-AUC: 0.9869 | Val Profit: -370
model_4_tolko_batchnorm | valid epoch 27
ROC-AUC: 0.9842
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 27 | Train Loss: 0.1877 | Val ROC-AUC: 0.9842 | Val Profit: -130
model_4_tolko_batchnorm | valid epoch 28
ROC-AUC: 0.9898
Precision: 1.0
Recall: 0.619
F0.5-score: 0.8904
Profit: 25

Эпоха 28 | Train Loss: 0.1950 | Val ROC-AUC: 0.9898 | Val Profit: 25
model_4_tolko_batchnorm | valid epoch 29
ROC-AUC: 0.9811
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 29 | Train Loss: 0.1958 | Val ROC-AUC: 0.9811 | Val Profit: -180
model_4_tolko_batchnorm | valid epoch 30
ROC-AUC: 0.9791
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 30 | Train Loss: 0.2084 | Val ROC-AUC: 0.9791 | Val Profit: -210

Лучшая эпоха для model_4_tolko_batchnorm: 28
Лучший ROC-AUC: 0.9898054996646546
Train
ROC-AUC: 0.9938
Precision: 0.8958
Recall: 0.5181
F0.5-score: 0.7818
Profit: -110

Test
ROC-AUC: 0.9831
Precision: 0.8104
Recall: 0.4949
F0.5-score: 0.7187
Profit: -69905

In [72]:
train_metrics = evaluate_model(model_4, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_4, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9938
Precision: 0.8958
Recall: 0.5181
F0.5-score: 0.7818
Profit: -110

Test
ROC-AUC: 0.9831
Precision: 0.8104
Recall: 0.4949
F0.5-score: 0.7187
Profit: -69905

Так как в предыдущие разы качество улучшилось с увеличением колво слоев, то теперь мы решили добавить колво слоев, а также после каждого слоя сделать только BatchNorm

Видно, что это сильно улучшило качество! И мы побили бейзлайн!

## model_5_tolko_dropout

In [86]:
EPOCHS = 40
SEED = 42

In [87]:
wandb.init(mode="disabled")
results = []
for LR in [0.01, 0.005, 0.001]:
    for DROPOUT_COEF in [0.05, 0.1, 0.015, 0.2, 0.025, 0.3]:
        random.seed(SEED)
        np.random.seed(SEED)
        torch.manual_seed(SEED) 

        model_5 = nn.Sequential(
            nn.Linear(9, 128),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(8, 1)
        )

        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.Adam(model_5.parameters(), lr=LR)
        model_5 = train_model(
            model=model_5,
            train_loader=train_loader,
            X_valid=X_val,
            y_valid=y_val,
            loss_fn=loss_fn,
            optimizer=optimizer,
            epochs=EPOCHS,
            threshold=0.5,
            model_name="model_5_tolko_dropout"
        )

        val = evaluate_model(model_5, X_val, y_val, threshold=0.5, name="val")
        results.append({"lr": LR, "dropout": DROPOUT_COEF, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9353
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 1 | Train Loss: 1.0889 | Val ROC-AUC: 0.9353 | Val Profit: -1545
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9204
Precision: 0.2121
Recall: 1.0
F0.5-score: 0.2518
Profit: -1845

Эпоха 2 | Train Loss: 0.8168 | Val ROC-AUC: 0.9204 | Val Profit: -1845
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9276
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 3 | Train Loss: 0.6146 | Val ROC-AUC: 0.9276 | Val Profit: -1065
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9619
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 4 | Train Loss: 0.4525 | Val ROC-AUC: 0.9619 | Val Profit: -705
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9322
Precision: 0.274
Recall: 0.9524
F0.5-score: 0.3195
Profit: -1230

Эпоха 5 | Train Loss: 0.4916 | Val ROC-AUC: 0.9322 | Val Profit: -1230
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9445
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 6 | Train Loss: 0.4179 | Val ROC-AUC: 0.9445 | Val Profit: -1270
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.937
Precision: 0.3393
Recall: 0.9048
F0.5-score: 0.3878
Profit: -840

Эпоха 7 | Train Loss: 0.3909 | Val ROC-AUC: 0.9370 | Val Profit: -840
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9488
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 8 | Train Loss: 0.3136 | Val ROC-AUC: 0.9488 | Val Profit: -1065
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.938
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 9 | Train Loss: 0.3940 | Val ROC-AUC: 0.9380 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9282
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 10 | Train Loss: 0.4950 | Val ROC-AUC: 0.9282 | Val Profit: -1695
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9497
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 11 | Train Loss: 0.4707 | Val ROC-AUC: 0.9497 | Val Profit: -1295
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9525
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 12 | Train Loss: 0.3307 | Val ROC-AUC: 0.9525 | Val Profit: -815
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9502
Precision: 0.3125
Recall: 0.9524
F0.5-score: 0.361
Profit: -1005

Эпоха 13 | Train Loss: 0.3081 | Val ROC-AUC: 0.9502 | Val Profit: -1005
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9374
Precision: 0.2899
Recall: 0.9524
F0.5-score: 0.3367
Profit: -1130

Эпоха 14 | Train Loss: 0.2911 | Val ROC-AUC: 0.9374 | Val Profit: -1130
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9525
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 15 | Train Loss: 0.3803 | Val ROC-AUC: 0.9525 | Val Profit: -1195
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.955
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 16 | Train Loss: 0.2807 | Val ROC-AUC: 0.9550 | Val Profit: -740
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9455
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 17 | Train Loss: 0.2472 | Val ROC-AUC: 0.9455 | Val Profit: -1045
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9304
Precision: 0.2879
Recall: 0.9048
F0.5-score: 0.3333
Profit: -1090

Эпоха 18 | Train Loss: 0.3117 | Val ROC-AUC: 0.9304 | Val Profit: -1090
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9501
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 19 | Train Loss: 0.2843 | Val ROC-AUC: 0.9501 | Val Profit: -1105
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9536
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 20 | Train Loss: 0.3270 | Val ROC-AUC: 0.9536 | Val Profit: -930
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9513
Precision: 0.3333
Recall: 0.8095
F0.5-score: 0.3778
Profit: -785

Эпоха 21 | Train Loss: 0.2647 | Val ROC-AUC: 0.9513 | Val Profit: -785
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9788
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 22 | Train Loss: 0.2027 | Val ROC-AUC: 0.9788 | Val Profit: -470
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9612
Precision: 0.3393
Recall: 0.9048
F0.5-score: 0.3878
Profit: -840

Эпоха 23 | Train Loss: 0.2232 | Val ROC-AUC: 0.9612 | Val Profit: -840
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9691
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 24 | Train Loss: 0.2559 | Val ROC-AUC: 0.9691 | Val Profit: -770
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9657
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 25 | Train Loss: 0.2455 | Val ROC-AUC: 0.9657 | Val Profit: -590
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.976
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 26 | Train Loss: 0.1683 | Val ROC-AUC: 0.9760 | Val Profit: -480
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9714
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 27 | Train Loss: 0.1263 | Val ROC-AUC: 0.9714 | Val Profit: -360
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9744
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 28 | Train Loss: 0.1667 | Val ROC-AUC: 0.9744 | Val Profit: -360
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9647
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 29 | Train Loss: 0.1422 | Val ROC-AUC: 0.9647 | Val Profit: -680
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9514
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 30 | Train Loss: 0.3527 | Val ROC-AUC: 0.9514 | Val Profit: -1270
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9697
Precision: 0.4048
Recall: 0.8095
F0.5-score: 0.4497
Profit: -560

Эпоха 31 | Train Loss: 0.2395 | Val ROC-AUC: 0.9697 | Val Profit: -560
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9753
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 32 | Train Loss: 0.1658 | Val ROC-AUC: 0.9753 | Val Profit: -235
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9777
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 33 | Train Loss: 0.1288 | Val ROC-AUC: 0.9777 | Val Profit: -390
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9819
Precision: 0.6154
Recall: 0.7619
F0.5-score: 0.64
Profit: -195

Эпоха 34 | Train Loss: 0.1049 | Val ROC-AUC: 0.9819 | Val Profit: -195
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9816
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 35 | Train Loss: 0.1030 | Val ROC-AUC: 0.9816 | Val Profit: -290
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9815
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 36 | Train Loss: 0.0783 | Val ROC-AUC: 0.9815 | Val Profit: -245
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9803
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 37 | Train Loss: 0.0584 | Val ROC-AUC: 0.9803 | Val Profit: -225
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9839
Precision: 0.6923
Recall: 0.8571
F0.5-score: 0.72
Profit: -125

Эпоха 38 | Train Loss: 0.0686 | Val ROC-AUC: 0.9839 | Val Profit: -125
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9451
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 39 | Train Loss: 0.2849 | Val ROC-AUC: 0.9451 | Val Profit: -1045
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9759
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 40 | Train Loss: 0.3263 | Val ROC-AUC: 0.9759 | Val Profit: -745

Лучшая эпоха для model_5_tolko_dropout: 38
Лучший ROC-AUC: 0.9839034205231387
val
ROC-AUC: 0.9839
Precision: 0.6923
Recall: 0.8571
F0.5-score: 0.72
Profit: -125

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.8844
Precision: 0.1944
Recall: 1.0
F0.5-score: 0.2318
Profit: -2070

Эпоха 1 | Train Loss: 1.1128 | Val ROC-AUC: 0.8844 | Val Profit: -2070
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9249
Precision: 0.1909
Recall: 1.0
F0.5-score: 0.2278
Profit: -2120

Эпоха 2 | Train Loss: 0.8482 | Val ROC-AUC: 0.9249 | Val Profit: -2120
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9371
Precision: 0.3409
Recall: 0.7143
F0.5-score: 0.3807
Profit: -680

Эпоха 3 | Train Loss: 0.5357 | Val ROC-AUC: 0.9371 | Val Profit: -680
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9647
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 4 | Train Loss: 0.4602 | Val ROC-AUC: 0.9647 | Val Profit: -1095
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9548
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 5 | Train Loss: 0.3578 | Val ROC-AUC: 0.9548 | Val Profit: -980
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9603
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 6 | Train Loss: 0.3530 | Val ROC-AUC: 0.9603 | Val Profit: -1145
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9717
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 7 | Train Loss: 0.2863 | Val ROC-AUC: 0.9717 | Val Profit: -720
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9627
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 8 | Train Loss: 0.2870 | Val ROC-AUC: 0.9627 | Val Profit: -1045
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9573
Precision: 0.2564
Recall: 0.9524
F0.5-score: 0.3003
Profit: -1355

Эпоха 9 | Train Loss: 0.3138 | Val ROC-AUC: 0.9573 | Val Profit: -1355
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9685
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 10 | Train Loss: 0.3002 | Val ROC-AUC: 0.9685 | Val Profit: -705
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9702
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 11 | Train Loss: 0.3421 | Val ROC-AUC: 0.9702 | Val Profit: -1695
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9654
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 12 | Train Loss: 0.3801 | Val ROC-AUC: 0.9654 | Val Profit: -1620
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9449
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 13 | Train Loss: 0.3507 | Val ROC-AUC: 0.9449 | Val Profit: -1070
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9646
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 14 | Train Loss: 0.2399 | Val ROC-AUC: 0.9646 | Val Profit: -855
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9642
Precision: 0.3276
Recall: 0.9048
F0.5-score: 0.3755
Profit: -890

Эпоха 15 | Train Loss: 0.2530 | Val ROC-AUC: 0.9642 | Val Profit: -890
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9659
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 16 | Train Loss: 0.2640 | Val ROC-AUC: 0.9659 | Val Profit: -1155
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9744
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 17 | Train Loss: 0.2818 | Val ROC-AUC: 0.9744 | Val Profit: -855
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9649
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 18 | Train Loss: 0.2071 | Val ROC-AUC: 0.9649 | Val Profit: -1145
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9714
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 19 | Train Loss: 0.2320 | Val ROC-AUC: 0.9714 | Val Profit: -555
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9705
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 20 | Train Loss: 0.1820 | Val ROC-AUC: 0.9705 | Val Profit: -1030
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.958
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 21 | Train Loss: 0.3510 | Val ROC-AUC: 0.9580 | Val Profit: -1070
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9632
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 22 | Train Loss: 0.2271 | Val ROC-AUC: 0.9632 | Val Profit: -930
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.976
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 23 | Train Loss: 0.2228 | Val ROC-AUC: 0.9760 | Val Profit: -555
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9602
Precision: 0.3125
Recall: 0.9524
F0.5-score: 0.361
Profit: -1005

Эпоха 24 | Train Loss: 0.2022 | Val ROC-AUC: 0.9602 | Val Profit: -1005
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9623
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 25 | Train Loss: 0.2185 | Val ROC-AUC: 0.9623 | Val Profit: -540
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9737
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 26 | Train Loss: 0.1544 | Val ROC-AUC: 0.9737 | Val Profit: -370
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9795
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 27 | Train Loss: 0.3110 | Val ROC-AUC: 0.9795 | Val Profit: -1320
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9811
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 28 | Train Loss: 0.3520 | Val ROC-AUC: 0.9811 | Val Profit: -1270
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9748
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 29 | Train Loss: 0.2220 | Val ROC-AUC: 0.9748 | Val Profit: -695
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9716
Precision: 0.3958
Recall: 0.9048
F0.5-score: 0.446
Profit: -640

Эпоха 30 | Train Loss: 0.1955 | Val ROC-AUC: 0.9716 | Val Profit: -640
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9701
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 31 | Train Loss: 0.1344 | Val ROC-AUC: 0.9701 | Val Profit: -280
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.974
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 32 | Train Loss: 0.3711 | Val ROC-AUC: 0.9740 | Val Profit: -795
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9824
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 33 | Train Loss: 0.2064 | Val ROC-AUC: 0.9824 | Val Profit: -490
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9736
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 34 | Train Loss: 0.2243 | Val ROC-AUC: 0.9736 | Val Profit: -465
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9779
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 35 | Train Loss: 0.1993 | Val ROC-AUC: 0.9779 | Val Profit: -720
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9755
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 36 | Train Loss: 0.1880 | Val ROC-AUC: 0.9755 | Val Profit: -680
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9634
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 37 | Train Loss: 0.3797 | Val ROC-AUC: 0.9634 | Val Profit: -995
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9698
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 38 | Train Loss: 0.3070 | Val ROC-AUC: 0.9698 | Val Profit: -780
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9706
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 39 | Train Loss: 0.1656 | Val ROC-AUC: 0.9706 | Val Profit: -390
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9679
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 40 | Train Loss: 0.1520 | Val ROC-AUC: 0.9679 | Val Profit: -480

Лучшая эпоха для model_5_tolko_dropout: 33
Лучший ROC-AUC: 0.98242790073776
val
ROC-AUC: 0.9824
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9345
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 1 | Train Loss: 1.0554 | Val ROC-AUC: 0.9345 | Val Profit: -1520
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9062
Precision: 0.1667
Recall: 0.9524
F0.5-score: 0.1996
Profit: -2405

Эпоха 2 | Train Loss: 0.7797 | Val ROC-AUC: 0.9062 | Val Profit: -2405
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9356
Precision: 0.2128
Recall: 0.9524
F0.5-score: 0.2519
Profit: -1755

Эпоха 3 | Train Loss: 0.6145 | Val ROC-AUC: 0.9356 | Val Profit: -1755
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9591
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 4 | Train Loss: 0.3970 | Val ROC-AUC: 0.9591 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9616
Precision: 0.2564
Recall: 0.9524
F0.5-score: 0.3003
Profit: -1355

Эпоха 5 | Train Loss: 0.3886 | Val ROC-AUC: 0.9616 | Val Profit: -1355
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9576
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 6 | Train Loss: 0.3770 | Val ROC-AUC: 0.9576 | Val Profit: -1120
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9674
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 7 | Train Loss: 0.3175 | Val ROC-AUC: 0.9674 | Val Profit: -1055
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9753
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 8 | Train Loss: 0.3206 | Val ROC-AUC: 0.9753 | Val Profit: -1545
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9571
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 9 | Train Loss: 0.3688 | Val ROC-AUC: 0.9571 | Val Profit: -930
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9673
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 10 | Train Loss: 0.2870 | Val ROC-AUC: 0.9673 | Val Profit: -740
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9665
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 11 | Train Loss: 0.2552 | Val ROC-AUC: 0.9665 | Val Profit: -1220
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9716
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 12 | Train Loss: 0.2389 | Val ROC-AUC: 0.9716 | Val Profit: -440
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9734
Precision: 0.1875
Recall: 1.0
F0.5-score: 0.2239
Profit: -2170

Эпоха 13 | Train Loss: 0.4645 | Val ROC-AUC: 0.9734 | Val Profit: -2170
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9608
Precision: 0.178
Recall: 1.0
F0.5-score: 0.213
Profit: -2320

Эпоха 14 | Train Loss: 0.5501 | Val ROC-AUC: 0.9608 | Val Profit: -2320
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9616
Precision: 0.3269
Recall: 0.8095
F0.5-score: 0.3712
Profit: -810

Эпоха 15 | Train Loss: 0.3878 | Val ROC-AUC: 0.9616 | Val Profit: -810
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9749
Precision: 0.2778
Recall: 0.9524
F0.5-score: 0.3236
Profit: -1205

Эпоха 16 | Train Loss: 0.3916 | Val ROC-AUC: 0.9749 | Val Profit: -1205
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9781
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 17 | Train Loss: 0.3085 | Val ROC-AUC: 0.9781 | Val Profit: -555
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9627
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 18 | Train Loss: 0.3231 | Val ROC-AUC: 0.9627 | Val Profit: -1270
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9681
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 19 | Train Loss: 0.3211 | Val ROC-AUC: 0.9681 | Val Profit: -1020
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9654
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 20 | Train Loss: 0.3260 | Val ROC-AUC: 0.9654 | Val Profit: -1495
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9696
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 21 | Train Loss: 0.2994 | Val ROC-AUC: 0.9696 | Val Profit: -1245
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9701
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 22 | Train Loss: 0.2113 | Val ROC-AUC: 0.9701 | Val Profit: -855
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9751
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 23 | Train Loss: 0.1659 | Val ROC-AUC: 0.9751 | Val Profit: -480

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9649
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 7 | Train Loss: 0.3045 | Val ROC-AUC: 0.9649 | Val Profit: -615
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9634
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 8 | Train Loss: 0.2563 | Val ROC-AUC: 0.9634 | Val Profit: -655
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9619
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 9 | Train Loss: 0.2621 | Val ROC-AUC: 0.9619 | Val Profit: -895
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9686
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 10 | Train Loss: 0.2376 | Val ROC-AUC: 0.9686 | Val Profit: -680
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9596
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 11 | Train Loss: 0.2943 | Val ROC-AUC: 0.9596 | Val Profit: -1065
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9591
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 12 | Train Loss: 0.3189 | Val ROC-AUC: 0.9591 | Val Profit: -1420
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9651
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 13 | Train Loss: 0.2749 | Val ROC-AUC: 0.9651 | Val Profit: -730
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9565
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 14 | Train Loss: 0.1901 | Val ROC-AUC: 0.9565 | Val Profit: -730
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9694
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 15 | Train Loss: 0.2581 | Val ROC-AUC: 0.9694 | Val Profit: -690
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.971
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 16 | Train Loss: 0.2034 | Val ROC-AUC: 0.9710 | Val Profit: -845
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.959
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 17 | Train Loss: 0.2395 | Val ROC-AUC: 0.9590 | Val Profit: -815
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9675
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 18 | Train Loss: 0.1728 | Val ROC-AUC: 0.9675 | Val Profit: -580
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9687
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 19 | Train Loss: 0.1519 | Val ROC-AUC: 0.9687 | Val Profit: -565
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9641
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 20 | Train Loss: 0.1862 | Val ROC-AUC: 0.9641 | Val Profit: -425
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.971
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 21 | Train Loss: 0.2361 | Val ROC-AUC: 0.9710 | Val Profit: -805
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9708
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 22 | Train Loss: 0.1852 | Val ROC-AUC: 0.9708 | Val Profit: -665
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9748
Precision: 0.4595
Recall: 0.8095
F0.5-score: 0.503
Profit: -435

Эпоха 23 | Train Loss: 0.1492 | Val ROC-AUC: 0.9748 | Val Profit: -435
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9641
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 24 | Train Loss: 0.1257 | Val ROC-AUC: 0.9641 | Val Profit: -455
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9643
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 25 | Train Loss: 0.1342 | Val ROC-AUC: 0.9643 | Val Profit: -690
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.958
Precision: 0.3462
Recall: 0.8571
F0.5-score: 0.393
Profit: -775

Эпоха 26 | Train Loss: 0.1953 | Val ROC-AUC: 0.9580 | Val Profit: -775
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9717
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 27 | Train Loss: 0.2700 | Val ROC-AUC: 0.9717 | Val Profit: -1155
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9665
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 28 | Train Loss: 0.2837 | Val ROC-AUC: 0.9665 | Val Profit: -730
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9744
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 29 | Train Loss: 0.1484 | Val ROC-AUC: 0.9744 | Val Profit: -480
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9603
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 30 | Train Loss: 0.1599 | Val ROC-AUC: 0.9603 | Val Profit: -625
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.952
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 31 | Train Loss: 0.4534 | Val ROC-AUC: 0.9520 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9705
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 32 | Train Loss: 0.2620 | Val ROC-AUC: 0.9705 | Val Profit: -845
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9657
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 33 | Train Loss: 0.2023 | Val ROC-AUC: 0.9657 | Val Profit: -845
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9734
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 34 | Train Loss: 0.1975 | Val ROC-AUC: 0.9734 | Val Profit: -415
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9681
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 35 | Train Loss: 0.1600 | Val ROC-AUC: 0.9681 | Val Profit: -1045
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9469
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 36 | Train Loss: 0.3558 | Val ROC-AUC: 0.9469 | Val Profit: -945
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.963
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 37 | Train Loss: 0.1981 | Val ROC-AUC: 0.9630 | Val Profit: -360
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9677
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 38 | Train Loss: 0.1688 | Val ROC-AUC: 0.9677 | Val Profit: -500
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9681
Precision: 0.4828
Recall: 0.6667
F0.5-score: 0.5109
Profit: -340

Эпоха 39 | Train Loss: 0.1276 | Val ROC-AUC: 0.9681 | Val Profit: -340
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9698
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 40 | Train Loss: 0.1164 | Val ROC-AUC: 0.9698 | Val Profit: -190

Лучшая эпоха для model_5_tolko_dropout: 23
Лучший ROC-AUC: 0.9747820254862508
val
ROC-AUC: 0.9748
Precision: 0.4595
Recall: 0.8095
F0.5-score: 0.503
Profit: -435

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.892
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 1 | Train Loss: 1.2162 | Val ROC-AUC: 0.8920 | Val Profit: -1520
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9376
Precision: 0.2532
Recall: 0.9524
F0.5-score: 0.2967
Profit: -1380

Эпоха 2 | Train Loss: 0.7844 | Val ROC-AUC: 0.9376 | Val Profit: -1380
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9437
Precision: 0.2639
Recall: 0.9048
F0.5-score: 0.3074
Profit: -1240

Эпоха 3 | Train Loss: 0.5414 | Val ROC-AUC: 0.9437 | Val Profit: -1240
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9564
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 4 | Train Loss: 0.4717 | Val ROC-AUC: 0.9564 | Val Profit: -1295
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9674
Precision: 0.1826
Recall: 1.0
F0.5-score: 0.2183
Profit: -2245

Эпоха 5 | Train Loss: 0.5297 | Val ROC-AUC: 0.9674 | Val Profit: -2245
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9567
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 6 | Train Loss: 0.4926 | Val ROC-AUC: 0.9567 | Val Profit: -1695
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.941
Precision: 0.2564
Recall: 0.9524
F0.5-score: 0.3003
Profit: -1355

Эпоха 7 | Train Loss: 0.4099 | Val ROC-AUC: 0.9410 | Val Profit: -1355
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9636
Precision: 0.2079
Recall: 1.0
F0.5-score: 0.2471
Profit: -1895

Эпоха 8 | Train Loss: 0.4174 | Val ROC-AUC: 0.9636 | Val Profit: -1895
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9667
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 9 | Train Loss: 0.4221 | Val ROC-AUC: 0.9667 | Val Profit: -1470
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9614
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 10 | Train Loss: 0.3073 | Val ROC-AUC: 0.9614 | Val Profit: -755
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9702
Precision: 0.3443
Recall: 1.0
F0.5-score: 0.3962
Profit: -895

Эпоха 11 | Train Loss: 0.2637 | Val ROC-AUC: 0.9702 | Val Profit: -895
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9568
Precision: 0.383
Recall: 0.8571
F0.5-score: 0.4306
Profit: -650

Эпоха 12 | Train Loss: 0.2553 | Val ROC-AUC: 0.9568 | Val Profit: -650
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9659
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 13 | Train Loss: 0.2774 | Val ROC-AUC: 0.9659 | Val Profit: -1345
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9649
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 14 | Train Loss: 0.3677 | Val ROC-AUC: 0.9649 | Val Profit: -1045
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.963
Precision: 0.3333
Recall: 0.9524
F0.5-score: 0.3831
Profit: -905

Эпоха 15 | Train Loss: 0.2461 | Val ROC-AUC: 0.9630 | Val Profit: -905
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9581
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 16 | Train Loss: 0.2669 | Val ROC-AUC: 0.9581 | Val Profit: -955
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9608
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 17 | Train Loss: 0.2604 | Val ROC-AUC: 0.9608 | Val Profit: -780
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.965
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 18 | Train Loss: 0.1890 | Val ROC-AUC: 0.9650 | Val Profit: -525
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9624
Precision: 0.4242
Recall: 0.6667
F0.5-score: 0.4575
Profit: -440

Эпоха 19 | Train Loss: 0.1451 | Val ROC-AUC: 0.9624 | Val Profit: -440
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9661
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 20 | Train Loss: 0.1613 | Val ROC-AUC: 0.9661 | Val Profit: -450
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9555
Precision: 0.3958
Recall: 0.9048
F0.5-score: 0.446
Profit: -640

Эпоха 21 | Train Loss: 0.2282 | Val ROC-AUC: 0.9555 | Val Profit: -640
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9649
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 22 | Train Loss: 0.1489 | Val ROC-AUC: 0.9649 | Val Profit: -395
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9651
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 23 | Train Loss: 0.1191 | Val ROC-AUC: 0.9651 | Val Profit: -375
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9653
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 24 | Train Loss: 0.0999 | Val ROC-AUC: 0.9653 | Val Profit: -295
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9675
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 25 | Train Loss: 0.1254 | Val ROC-AUC: 0.9675 | Val Profit: -385
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9667
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 26 | Train Loss: 0.1234 | Val ROC-AUC: 0.9667 | Val Profit: -310
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9697
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 27 | Train Loss: 0.1170 | Val ROC-AUC: 0.9697 | Val Profit: -295
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9713
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 28 | Train Loss: 0.0954 | Val ROC-AUC: 0.9713 | Val Profit: -300
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9602
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 29 | Train Loss: 0.1645 | Val ROC-AUC: 0.9602 | Val Profit: -565
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9571
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 30 | Train Loss: 0.3040 | Val ROC-AUC: 0.9571 | Val Profit: -1195
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9674
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 31 | Train Loss: 0.2970 | Val ROC-AUC: 0.9674 | Val Profit: -1120
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9624
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 32 | Train Loss: 0.2270 | Val ROC-AUC: 0.9624 | Val Profit: -525
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.965
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 33 | Train Loss: 0.2363 | Val ROC-AUC: 0.9650 | Val Profit: -970
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.943
Precision: 0.3333
Recall: 0.9524
F0.5-score: 0.3831
Profit: -905

Эпоха 34 | Train Loss: 0.3290 | Val ROC-AUC: 0.9430 | Val Profit: -905
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9653
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 35 | Train Loss: 0.2426 | Val ROC-AUC: 0.9653 | Val Profit: -680
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9635
Precision: 0.383
Recall: 0.8571
F0.5-score: 0.4306
Profit: -650

Эпоха 36 | Train Loss: 0.1595 | Val ROC-AUC: 0.9635 | Val Profit: -650
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9654
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 37 | Train Loss: 0.1441 | Val ROC-AUC: 0.9654 | Val Profit: -605
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9662
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 38 | Train Loss: 0.1169 | Val ROC-AUC: 0.9662 | Val Profit: -420
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9696
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 39 | Train Loss: 0.0865 | Val ROC-AUC: 0.9696 | Val Profit: -265
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9697
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 40 | Train Loss: 0.0698 | Val ROC-AUC: 0.9697 | Val Profit: -250

Лучшая эпоха для model_5_tolko_dropout: 28
Лучший ROC-AUC: 0.9712944332662643
val
ROC-AUC: 0.9713
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9375
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 1 | Train Loss: 1.1719 | Val ROC-AUC: 0.9375 | Val Profit: -1030
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9333
Precision: 0.1909
Recall: 1.0
F0.5-score: 0.2278
Profit: -2120

Эпоха 2 | Train Loss: 0.7785 | Val ROC-AUC: 0.9333 | Val Profit: -2120
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9586
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 3 | Train Loss: 0.5299 | Val ROC-AUC: 0.9586 | Val Profit: -1495
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9518
Precision: 0.2039
Recall: 1.0
F0.5-score: 0.2425
Profit: -1945

Эпоха 4 | Train Loss: 0.5074 | Val ROC-AUC: 0.9518 | Val Profit: -1945
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9549
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 5 | Train Loss: 0.4923 | Val ROC-AUC: 0.9549 | Val Profit: -1620
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9524
Precision: 0.2714
Recall: 0.9048
F0.5-score: 0.3156
Profit: -1190

Эпоха 6 | Train Loss: 0.3864 | Val ROC-AUC: 0.9524 | Val Profit: -1190
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9632
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 7 | Train Loss: 0.3827 | Val ROC-AUC: 0.9632 | Val Profit: -1195
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9551
Precision: 0.2879
Recall: 0.9048
F0.5-score: 0.3333
Profit: -1090

Эпоха 8 | Train Loss: 0.3089 | Val ROC-AUC: 0.9551 | Val Profit: -1090
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9673
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 9 | Train Loss: 0.2616 | Val ROC-AUC: 0.9673 | Val Profit: -740
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9646
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 10 | Train Loss: 0.2828 | Val ROC-AUC: 0.9646 | Val Profit: -805
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9622
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 11 | Train Loss: 0.2415 | Val ROC-AUC: 0.9622 | Val Profit: -940
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9579
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 12 | Train Loss: 0.2131 | Val ROC-AUC: 0.9579 | Val Profit: -615
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9657
Precision: 0.4091
Recall: 0.8571
F0.5-score: 0.4569
Profit: -575

Эпоха 13 | Train Loss: 0.2279 | Val ROC-AUC: 0.9657 | Val Profit: -575
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.963
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 14 | Train Loss: 0.1923 | Val ROC-AUC: 0.9630 | Val Profit: -945
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9641
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 15 | Train Loss: 0.3091 | Val ROC-AUC: 0.9641 | Val Profit: -1095
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9687
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 16 | Train Loss: 0.2899 | Val ROC-AUC: 0.9687 | Val Profit: -995
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9646
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 17 | Train Loss: 0.2232 | Val ROC-AUC: 0.9646 | Val Profit: -1055
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9641
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 18 | Train Loss: 0.2441 | Val ROC-AUC: 0.9641 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9661
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 19 | Train Loss: 0.2098 | Val ROC-AUC: 0.9661 | Val Profit: -955
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9636
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 20 | Train Loss: 0.2164 | Val ROC-AUC: 0.9636 | Val Profit: -615
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9446
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 21 | Train Loss: 0.1939 | Val ROC-AUC: 0.9446 | Val Profit: -1065
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9705
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 22 | Train Loss: 0.3508 | Val ROC-AUC: 0.9705 | Val Profit: -1245
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9756
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 23 | Train Loss: 0.2177 | Val ROC-AUC: 0.9756 | Val Profit: -615
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9738
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 24 | Train Loss: 0.1664 | Val ROC-AUC: 0.9738 | Val Profit: -515
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9709
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 25 | Train Loss: 0.1635 | Val ROC-AUC: 0.9709 | Val Profit: -1020
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9634
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 26 | Train Loss: 0.2715 | Val ROC-AUC: 0.9634 | Val Profit: -1220
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9729
Precision: 0.3585
Recall: 0.9048
F0.5-score: 0.4077
Profit: -765

Эпоха 27 | Train Loss: 0.2298 | Val ROC-AUC: 0.9729 | Val Profit: -765
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9767
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 28 | Train Loss: 0.1426 | Val ROC-AUC: 0.9767 | Val Profit: -385
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9653
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 29 | Train Loss: 0.2551 | Val ROC-AUC: 0.9653 | Val Profit: -1220

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9557
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 8 | Train Loss: 0.3170 | Val ROC-AUC: 0.9557 | Val Profit: -715
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9612
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 9 | Train Loss: 0.3091 | Val ROC-AUC: 0.9612 | Val Profit: -815
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9584
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 10 | Train Loss: 0.3011 | Val ROC-AUC: 0.9584 | Val Profit: -525
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.959
Precision: 0.4
Recall: 0.8571
F0.5-score: 0.4478
Profit: -600

Эпоха 11 | Train Loss: 0.2782 | Val ROC-AUC: 0.9590 | Val Profit: -600
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9623
Precision: 0.339
Recall: 0.9524
F0.5-score: 0.3891
Profit: -880

Эпоха 12 | Train Loss: 0.2890 | Val ROC-AUC: 0.9623 | Val Profit: -880
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9608
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 13 | Train Loss: 0.2659 | Val ROC-AUC: 0.9608 | Val Profit: -955
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9619
Precision: 0.3393
Recall: 0.9048
F0.5-score: 0.3878
Profit: -840

Эпоха 14 | Train Loss: 0.2377 | Val ROC-AUC: 0.9619 | Val Profit: -840
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9586
Precision: 0.3115
Recall: 0.9048
F0.5-score: 0.3585
Profit: -965

Эпоха 15 | Train Loss: 0.2238 | Val ROC-AUC: 0.9586 | Val Profit: -965
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9618
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 16 | Train Loss: 0.2517 | Val ROC-AUC: 0.9618 | Val Profit: -930
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9643
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 17 | Train Loss: 0.2643 | Val ROC-AUC: 0.9643 | Val Profit: -855
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9587
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 18 | Train Loss: 0.2394 | Val ROC-AUC: 0.9587 | Val Profit: -740
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9469
Precision: 0.3333
Recall: 0.619
F0.5-score: 0.3672
Profit: -625

Эпоха 19 | Train Loss: 0.2706 | Val ROC-AUC: 0.9469 | Val Profit: -625
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9549
Precision: 0.3488
Recall: 0.7143
F0.5-score: 0.3886
Profit: -655

Эпоха 20 | Train Loss: 0.2203 | Val ROC-AUC: 0.9549 | Val Profit: -655
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9615
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 21 | Train Loss: 0.1722 | Val ROC-AUC: 0.9615 | Val Profit: -525
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9584
Precision: 0.3947
Recall: 0.7143
F0.5-score: 0.4335
Profit: -530

Эпоха 22 | Train Loss: 0.1560 | Val ROC-AUC: 0.9584 | Val Profit: -530
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9612
Precision: 0.4474
Recall: 0.8095
F0.5-score: 0.4913
Profit: -460

Эпоха 23 | Train Loss: 0.1420 | Val ROC-AUC: 0.9612 | Val Profit: -460
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9571
Precision: 0.4103
Recall: 0.7619
F0.5-score: 0.452
Profit: -520

Эпоха 24 | Train Loss: 0.1371 | Val ROC-AUC: 0.9571 | Val Profit: -520
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9607
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 25 | Train Loss: 0.1332 | Val ROC-AUC: 0.9607 | Val Profit: -445
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9586
Precision: 0.4412
Recall: 0.7143
F0.5-score: 0.4777
Profit: -430

Эпоха 26 | Train Loss: 0.1155 | Val ROC-AUC: 0.9586 | Val Profit: -430
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9634
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 27 | Train Loss: 0.1139 | Val ROC-AUC: 0.9634 | Val Profit: -295
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9595
Precision: 0.4688
Recall: 0.7143
F0.5-score: 0.5034
Profit: -380

Эпоха 28 | Train Loss: 0.1075 | Val ROC-AUC: 0.9595 | Val Profit: -380
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9651
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 29 | Train Loss: 0.1241 | Val ROC-AUC: 0.9651 | Val Profit: -395
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9598
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 30 | Train Loss: 0.1142 | Val ROC-AUC: 0.9598 | Val Profit: -455
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9673
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 31 | Train Loss: 0.2384 | Val ROC-AUC: 0.9673 | Val Profit: -805
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9663
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 32 | Train Loss: 0.1837 | Val ROC-AUC: 0.9663 | Val Profit: -655
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9573
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 33 | Train Loss: 0.1513 | Val ROC-AUC: 0.9573 | Val Profit: -615
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9603
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 34 | Train Loss: 0.1464 | Val ROC-AUC: 0.9603 | Val Profit: -445
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9635
Precision: 0.4828
Recall: 0.6667
F0.5-score: 0.5109
Profit: -340

Эпоха 35 | Train Loss: 0.1091 | Val ROC-AUC: 0.9635 | Val Profit: -340
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9624
Precision: 0.4516
Recall: 0.6667
F0.5-score: 0.4828
Profit: -390

Эпоха 36 | Train Loss: 0.0878 | Val ROC-AUC: 0.9624 | Val Profit: -390
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9631
Precision: 0.4828
Recall: 0.6667
F0.5-score: 0.5109
Profit: -340

Эпоха 37 | Train Loss: 0.0808 | Val ROC-AUC: 0.9631 | Val Profit: -340
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9634
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 38 | Train Loss: 0.0741 | Val ROC-AUC: 0.9634 | Val Profit: -350
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9635
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 39 | Train Loss: 0.0687 | Val ROC-AUC: 0.9635 | Val Profit: -325
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9632
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 40 | Train Loss: 0.0656 | Val ROC-AUC: 0.9632 | Val Profit: -320

Лучшая эпоха для model_5_tolko_dropout: 31
Лучший ROC-AUC: 0.967270288397049
val
ROC-AUC: 0.9673
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9337
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3091 | Val ROC-AUC: 0.9337 | Val Profit: -105
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9559
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 2 | Train Loss: 1.2627 | Val ROC-AUC: 0.9559 | Val Profit: -625
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9178
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 3 | Train Loss: 1.0696 | Val ROC-AUC: 0.9178 | Val Profit: -1345

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9443
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 4 | Train Loss: 0.8444 | Val ROC-AUC: 0.9443 | Val Profit: -1445
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9454
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 5 | Train Loss: 0.6099 | Val ROC-AUC: 0.9454 | Val Profit: -1445
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9612
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 6 | Train Loss: 0.4329 | Val ROC-AUC: 0.9612 | Val Profit: -1245
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9592
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 7 | Train Loss: 0.3569 | Val ROC-AUC: 0.9592 | Val Profit: -955
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9502
Precision: 0.3333
Recall: 0.9048
F0.5-score: 0.3815
Profit: -865

Эпоха 8 | Train Loss: 0.3153 | Val ROC-AUC: 0.9502 | Val Profit: -865
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9555
Precision: 0.3393
Recall: 0.9048
F0.5-score: 0.3878
Profit: -840

Эпоха 9 | Train Loss: 0.2828 | Val ROC-AUC: 0.9555 | Val Profit: -840
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9553
Precision: 0.3953
Recall: 0.8095
F0.5-score: 0.4404
Profit: -585

Эпоха 10 | Train Loss: 0.2453 | Val ROC-AUC: 0.9553 | Val Profit: -585
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9563
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 11 | Train Loss: 0.2102 | Val ROC-AUC: 0.9563 | Val Profit: -625
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9526
Precision: 0.3714
Recall: 0.619
F0.5-score: 0.4037
Profit: -525

Эпоха 12 | Train Loss: 0.1869 | Val ROC-AUC: 0.9526 | Val Profit: -525
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9564
Precision: 0.4103
Recall: 0.7619
F0.5-score: 0.452
Profit: -520

Эпоха 13 | Train Loss: 0.1698 | Val ROC-AUC: 0.9564 | Val Profit: -520
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9537
Precision: 0.3889
Recall: 0.6667
F0.5-score: 0.4242
Profit: -515

Эпоха 14 | Train Loss: 0.1554 | Val ROC-AUC: 0.9537 | Val Profit: -515
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9531
Precision: 0.4138
Recall: 0.5714
F0.5-score: 0.438
Profit: -410

Эпоха 15 | Train Loss: 0.1437 | Val ROC-AUC: 0.9531 | Val Profit: -410
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9577
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 16 | Train Loss: 0.1293 | Val ROC-AUC: 0.9577 | Val Profit: -335
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.954
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 17 | Train Loss: 0.1389 | Val ROC-AUC: 0.9540 | Val Profit: -335
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9614
Precision: 0.4828
Recall: 0.6667
F0.5-score: 0.5109
Profit: -340

Эпоха 18 | Train Loss: 0.1153 | Val ROC-AUC: 0.9614 | Val Profit: -340
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9632
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 19 | Train Loss: 0.1134 | Val ROC-AUC: 0.9632 | Val Profit: -225
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9614
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 20 | Train Loss: 0.1222 | Val ROC-AUC: 0.9614 | Val Profit: -300
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9571
Precision: 0.3696
Recall: 0.8095
F0.5-score: 0.4146
Profit: -660

Эпоха 21 | Train Loss: 0.1328 | Val ROC-AUC: 0.9571 | Val Profit: -660
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.956
Precision: 0.4333
Recall: 0.619
F0.5-score: 0.461
Profit: -400

Эпоха 22 | Train Loss: 0.2082 | Val ROC-AUC: 0.9560 | Val Profit: -400
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9604
Precision: 0.4688
Recall: 0.7143
F0.5-score: 0.5034
Profit: -380

Эпоха 23 | Train Loss: 0.0951 | Val ROC-AUC: 0.9604 | Val Profit: -380
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9569
Precision: 0.4474
Recall: 0.8095
F0.5-score: 0.4913
Profit: -460

Эпоха 24 | Train Loss: 0.0876 | Val ROC-AUC: 0.9569 | Val Profit: -460
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9616
Precision: 0.4186
Recall: 0.8571
F0.5-score: 0.4663
Profit: -550

Эпоха 25 | Train Loss: 0.0969 | Val ROC-AUC: 0.9616 | Val Profit: -550
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9686
Precision: 0.3953
Recall: 0.8095
F0.5-score: 0.4404
Profit: -585

Эпоха 26 | Train Loss: 0.0882 | Val ROC-AUC: 0.9686 | Val Profit: -585
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9608
Precision: 0.425
Recall: 0.8095
F0.5-score: 0.4696
Profit: -510

Эпоха 27 | Train Loss: 0.0824 | Val ROC-AUC: 0.9608 | Val Profit: -510
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.962
Precision: 0.4474
Recall: 0.8095
F0.5-score: 0.4913
Profit: -460

Эпоха 28 | Train Loss: 0.0714 | Val ROC-AUC: 0.9620 | Val Profit: -460
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9665
Precision: 0.4688
Recall: 0.7143
F0.5-score: 0.5034
Profit: -380

Эпоха 29 | Train Loss: 0.0679 | Val ROC-AUC: 0.9665 | Val Profit: -380
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9619
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 30 | Train Loss: 0.0735 | Val ROC-AUC: 0.9619 | Val Profit: -325
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9599
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 31 | Train Loss: 0.0499 | Val ROC-AUC: 0.9599 | Val Profit: -255
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9636
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 32 | Train Loss: 0.0508 | Val ROC-AUC: 0.9636 | Val Profit: -195
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9596
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 33 | Train Loss: 0.0514 | Val ROC-AUC: 0.9596 | Val Profit: -230
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9619
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 34 | Train Loss: 0.0436 | Val ROC-AUC: 0.9619 | Val Profit: -325
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9632
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 35 | Train Loss: 0.0312 | Val ROC-AUC: 0.9632 | Val Profit: -235
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9627
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 36 | Train Loss: 0.0272 | Val ROC-AUC: 0.9627 | Val Profit: -205
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9638
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 37 | Train Loss: 0.0251 | Val ROC-AUC: 0.9638 | Val Profit: -205
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9635
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 38 | Train Loss: 0.0229 | Val ROC-AUC: 0.9635 | Val Profit: -195
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.963
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 39 | Train Loss: 0.0217 | Val ROC-AUC: 0.9630 | Val Profit: -205
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9624
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 40 | Train Loss: 0.0196 | Val ROC-AUC: 0.9624 | Val Profit: -190

Лучшая эпоха для model_5_tolko_dropout: 26
Лучший ROC-AUC: 0.9686116700201207
val
ROC-AUC: 0.9686
Precision: 0.3953
Recall: 0.8095
F0.5-score: 0.4404
Profit: -585

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9383
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3083 | Val ROC-AUC: 0.9383 | Val Profit: -105
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9433
Precision: 0.3902
Recall: 0.7619
F0.5-score: 0.4324
Profit: -570

Эпоха 2 | Train Loss: 1.2522 | Val ROC-AUC: 0.9433 | Val Profit: -570
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9539
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 3 | Train Loss: 1.0285 | Val ROC-AUC: 0.9539 | Val Profit: -980
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9368
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 4 | Train Loss: 0.7984 | Val ROC-AUC: 0.9368 | Val Profit: -1345
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9471
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 5 | Train Loss: 0.5768 | Val ROC-AUC: 0.9471 | Val Profit: -1445
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9581
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 6 | Train Loss: 0.3948 | Val ROC-AUC: 0.9581 | Val Profit: -1295
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9595
Precision: 0.3016
Recall: 0.9048
F0.5-score: 0.348
Profit: -1015

Эпоха 7 | Train Loss: 0.3458 | Val ROC-AUC: 0.9595 | Val Profit: -1015
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9591
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 8 | Train Loss: 0.3238 | Val ROC-AUC: 0.9591 | Val Profit: -940

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9612
Precision: 0.3393
Recall: 0.9048
F0.5-score: 0.3878
Profit: -840

Эпоха 9 | Train Loss: 0.2917 | Val ROC-AUC: 0.9612 | Val Profit: -840
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9581
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 10 | Train Loss: 0.2605 | Val ROC-AUC: 0.9581 | Val Profit: -665
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9596
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 11 | Train Loss: 0.2367 | Val ROC-AUC: 0.9596 | Val Profit: -540
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9591
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 12 | Train Loss: 0.2132 | Val ROC-AUC: 0.9591 | Val Profit: -590
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.96
Precision: 0.4474
Recall: 0.8095
F0.5-score: 0.4913
Profit: -460

Эпоха 13 | Train Loss: 0.2048 | Val ROC-AUC: 0.9600 | Val Profit: -460
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.962
Precision: 0.3958
Recall: 0.9048
F0.5-score: 0.446
Profit: -640

Эпоха 14 | Train Loss: 0.2028 | Val ROC-AUC: 0.9620 | Val Profit: -640
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9611
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 15 | Train Loss: 0.2202 | Val ROC-AUC: 0.9611 | Val Profit: -450
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9624
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 16 | Train Loss: 0.1933 | Val ROC-AUC: 0.9624 | Val Profit: -425
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9646
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 17 | Train Loss: 0.1787 | Val ROC-AUC: 0.9646 | Val Profit: -425
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9655
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 18 | Train Loss: 0.1765 | Val ROC-AUC: 0.9655 | Val Profit: -540
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9657
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 19 | Train Loss: 0.1613 | Val ROC-AUC: 0.9657 | Val Profit: -500
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9636
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 20 | Train Loss: 0.1708 | Val ROC-AUC: 0.9636 | Val Profit: -565
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9669
Precision: 0.4
Recall: 0.8571
F0.5-score: 0.4478
Profit: -600

Эпоха 21 | Train Loss: 0.1618 | Val ROC-AUC: 0.9669 | Val Profit: -600
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9657
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 22 | Train Loss: 0.1551 | Val ROC-AUC: 0.9657 | Val Profit: -680
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9694
Precision: 0.4091
Recall: 0.8571
F0.5-score: 0.4569
Profit: -575

Эпоха 23 | Train Loss: 0.1620 | Val ROC-AUC: 0.9694 | Val Profit: -575
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.969
Precision: 0.3333
Recall: 0.9524
F0.5-score: 0.3831
Profit: -905

Эпоха 24 | Train Loss: 0.1715 | Val ROC-AUC: 0.9690 | Val Profit: -905
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9638
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 25 | Train Loss: 0.1611 | Val ROC-AUC: 0.9638 | Val Profit: -715
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9653
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 26 | Train Loss: 0.1503 | Val ROC-AUC: 0.9653 | Val Profit: -780
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9674
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 27 | Train Loss: 0.1600 | Val ROC-AUC: 0.9674 | Val Profit: -715
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9643
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 28 | Train Loss: 0.1472 | Val ROC-AUC: 0.9643 | Val Profit: -730
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9702
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 29 | Train Loss: 0.1722 | Val ROC-AUC: 0.9702 | Val Profit: -615
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9704
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 30 | Train Loss: 0.1698 | Val ROC-AUC: 0.9704 | Val Profit: -565
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9671
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 31 | Train Loss: 0.1246 | Val ROC-AUC: 0.9671 | Val Profit: -450
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9702
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 32 | Train Loss: 0.1129 | Val ROC-AUC: 0.9702 | Val Profit: -450
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9683
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 33 | Train Loss: 0.1081 | Val ROC-AUC: 0.9683 | Val Profit: -375
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9693
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 34 | Train Loss: 0.0870 | Val ROC-AUC: 0.9693 | Val Profit: -350
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9701
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 35 | Train Loss: 0.0833 | Val ROC-AUC: 0.9701 | Val Profit: -325
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9724
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 36 | Train Loss: 0.0873 | Val ROC-AUC: 0.9724 | Val Profit: -375
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9698
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 37 | Train Loss: 0.0996 | Val ROC-AUC: 0.9698 | Val Profit: -440
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9773
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 38 | Train Loss: 0.1147 | Val ROC-AUC: 0.9773 | Val Profit: -440
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9667
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 39 | Train Loss: 0.1249 | Val ROC-AUC: 0.9667 | Val Profit: -475
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9718
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 40 | Train Loss: 0.1166 | Val ROC-AUC: 0.9718 | Val Profit: -565

Лучшая эпоха для model_5_tolko_dropout: 38
Лучший ROC-AUC: 0.9773306505700872
val
ROC-AUC: 0.9773
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9026
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3108 | Val ROC-AUC: 0.9026 | Val Profit: -105
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9502
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 2 | Train Loss: 1.2790 | Val ROC-AUC: 0.9502 | Val Profit: -420
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9485
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 3 | Train Loss: 1.1307 | Val ROC-AUC: 0.9485 | Val Profit: -1065
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9427
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 4 | Train Loss: 0.8866 | Val ROC-AUC: 0.9427 | Val Profit: -1320

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9508
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 5 | Train Loss: 0.6292 | Val ROC-AUC: 0.9508 | Val Profit: -1220
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9522
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 6 | Train Loss: 0.4478 | Val ROC-AUC: 0.9522 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9608
Precision: 0.3333
Recall: 0.9048
F0.5-score: 0.3815
Profit: -865

Эпоха 7 | Train Loss: 0.3738 | Val ROC-AUC: 0.9608 | Val Profit: -865
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9586
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 8 | Train Loss: 0.3796 | Val ROC-AUC: 0.9586 | Val Profit: -665
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9568
Precision: 0.4118
Recall: 0.6667
F0.5-score: 0.4459
Profit: -465

Эпоха 9 | Train Loss: 0.3441 | Val ROC-AUC: 0.9568 | Val Profit: -465
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9673
Precision: 0.4
Recall: 0.8571
F0.5-score: 0.4478
Profit: -600

Эпоха 10 | Train Loss: 0.3381 | Val ROC-AUC: 0.9673 | Val Profit: -600
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.958
Precision: 0.3696
Recall: 0.8095
F0.5-score: 0.4146
Profit: -660

Эпоха 11 | Train Loss: 0.2644 | Val ROC-AUC: 0.9580 | Val Profit: -660
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9541
Precision: 0.425
Recall: 0.8095
F0.5-score: 0.4696
Profit: -510

Эпоха 12 | Train Loss: 0.2283 | Val ROC-AUC: 0.9541 | Val Profit: -510
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9545
Precision: 0.4138
Recall: 0.5714
F0.5-score: 0.438
Profit: -410

Эпоха 13 | Train Loss: 0.2148 | Val ROC-AUC: 0.9545 | Val Profit: -410
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9563
Precision: 0.4231
Recall: 0.5238
F0.5-score: 0.44
Profit: -370

Эпоха 14 | Train Loss: 0.1877 | Val ROC-AUC: 0.9563 | Val Profit: -370
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9552
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 15 | Train Loss: 0.1763 | Val ROC-AUC: 0.9552 | Val Profit: -345
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9575
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 16 | Train Loss: 0.1682 | Val ROC-AUC: 0.9575 | Val Profit: -445
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9532
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 17 | Train Loss: 0.1605 | Val ROC-AUC: 0.9532 | Val Profit: -625
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9543
Precision: 0.4
Recall: 0.7619
F0.5-score: 0.442
Profit: -545

Эпоха 18 | Train Loss: 0.1518 | Val ROC-AUC: 0.9543 | Val Profit: -545
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9551
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 19 | Train Loss: 0.1423 | Val ROC-AUC: 0.9551 | Val Profit: -310
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9561
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 20 | Train Loss: 0.1156 | Val ROC-AUC: 0.9561 | Val Profit: -295
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9531
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 21 | Train Loss: 0.1045 | Val ROC-AUC: 0.9531 | Val Profit: -360
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9539
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 22 | Train Loss: 0.1020 | Val ROC-AUC: 0.9539 | Val Profit: -280
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9547
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 23 | Train Loss: 0.0901 | Val ROC-AUC: 0.9547 | Val Profit: -245
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9561
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 24 | Train Loss: 0.0837 | Val ROC-AUC: 0.9561 | Val Profit: -220
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9559
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 25 | Train Loss: 0.0799 | Val ROC-AUC: 0.9559 | Val Profit: -335
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9565
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 26 | Train Loss: 0.0905 | Val ROC-AUC: 0.9565 | Val Profit: -265
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9586
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 27 | Train Loss: 0.0712 | Val ROC-AUC: 0.9586 | Val Profit: -205
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9586
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 28 | Train Loss: 0.0651 | Val ROC-AUC: 0.9586 | Val Profit: -230
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9564
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 29 | Train Loss: 0.0627 | Val ROC-AUC: 0.9564 | Val Profit: -245
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9559
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 30 | Train Loss: 0.0619 | Val ROC-AUC: 0.9559 | Val Profit: -155
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9575
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 31 | Train Loss: 0.0573 | Val ROC-AUC: 0.9575 | Val Profit: -205
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9584
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 32 | Train Loss: 0.0545 | Val ROC-AUC: 0.9584 | Val Profit: -180
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9581
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 33 | Train Loss: 0.0529 | Val ROC-AUC: 0.9581 | Val Profit: -180
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9583
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 34 | Train Loss: 0.0519 | Val ROC-AUC: 0.9583 | Val Profit: -180
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9583
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 35 | Train Loss: 0.0511 | Val ROC-AUC: 0.9583 | Val Profit: -180
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9584
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 36 | Train Loss: 0.0503 | Val ROC-AUC: 0.9584 | Val Profit: -180
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9583
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 37 | Train Loss: 0.0497 | Val ROC-AUC: 0.9583 | Val Profit: -155
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9579
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 38 | Train Loss: 0.0489 | Val ROC-AUC: 0.9579 | Val Profit: -155
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9576
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 39 | Train Loss: 0.0463 | Val ROC-AUC: 0.9576 | Val Profit: -140
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9611
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 40 | Train Loss: 0.0454 | Val ROC-AUC: 0.9611 | Val Profit: -220

Лучшая эпоха для model_5_tolko_dropout: 10
Лучший ROC-AUC: 0.967270288397049
val
ROC-AUC: 0.9673
Precision: 0.4
Recall: 0.8571
F0.5-score: 0.4478
Profit: -600

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9304
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3087 | Val ROC-AUC: 0.9304 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.947
Precision: 0.3902
Recall: 0.7619
F0.5-score: 0.4324
Profit: -570

Эпоха 2 | Train Loss: 1.2556 | Val ROC-AUC: 0.9470 | Val Profit: -570
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9521
Precision: 0.2899
Recall: 0.9524
F0.5-score: 0.3367
Profit: -1130

Эпоха 3 | Train Loss: 1.0387 | Val ROC-AUC: 0.9521 | Val Profit: -1130
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9317
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 4 | Train Loss: 0.8100 | Val ROC-AUC: 0.9317 | Val Profit: -1445
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9423
Precision: 0.274
Recall: 0.9524
F0.5-score: 0.3195
Profit: -1230

Эпоха 5 | Train Loss: 0.6128 | Val ROC-AUC: 0.9423 | Val Profit: -1230
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9517
Precision: 0.2879
Recall: 0.9048
F0.5-score: 0.3333
Profit: -1090

Эпоха 6 | Train Loss: 0.4255 | Val ROC-AUC: 0.9517 | Val Profit: -1090
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.956
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 7 | Train Loss: 0.3588 | Val ROC-AUC: 0.9560 | Val Profit: -940
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9568
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 8 | Train Loss: 0.3134 | Val ROC-AUC: 0.9568 | Val Profit: -715
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.956
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 9 | Train Loss: 0.2820 | Val ROC-AUC: 0.9560 | Val Profit: -815
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9555
Precision: 0.4091
Recall: 0.8571
F0.5-score: 0.4569
Profit: -575

Эпоха 10 | Train Loss: 0.2680 | Val ROC-AUC: 0.9555 | Val Profit: -575
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9524
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 11 | Train Loss: 0.2382 | Val ROC-AUC: 0.9524 | Val Profit: -615
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9577
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 12 | Train Loss: 0.2228 | Val ROC-AUC: 0.9577 | Val Profit: -525
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9528
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 13 | Train Loss: 0.2001 | Val ROC-AUC: 0.9528 | Val Profit: -525
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.9586
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 14 | Train Loss: 0.1930 | Val ROC-AUC: 0.9586 | Val Profit: -500
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9598
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 15 | Train Loss: 0.1915 | Val ROC-AUC: 0.9598 | Val Profit: -475
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9586
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 16 | Train Loss: 0.2043 | Val ROC-AUC: 0.9586 | Val Profit: -715
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.961
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 17 | Train Loss: 0.2418 | Val ROC-AUC: 0.9610 | Val Profit: -1070
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9577
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 18 | Train Loss: 0.2388 | Val ROC-AUC: 0.9577 | Val Profit: -1155
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9606
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 19 | Train Loss: 0.2400 | Val ROC-AUC: 0.9606 | Val Profit: -1220
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9635
Precision: 0.3958
Recall: 0.9048
F0.5-score: 0.446
Profit: -640

Эпоха 20 | Train Loss: 0.2495 | Val ROC-AUC: 0.9635 | Val Profit: -640
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9654
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 21 | Train Loss: 0.1607 | Val ROC-AUC: 0.9654 | Val Profit: -630
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9666
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 22 | Train Loss: 0.1572 | Val ROC-AUC: 0.9666 | Val Profit: -515
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9655
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 23 | Train Loss: 0.1385 | Val ROC-AUC: 0.9655 | Val Profit: -500
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9632
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 24 | Train Loss: 0.1297 | Val ROC-AUC: 0.9632 | Val Profit: -475
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9635
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 25 | Train Loss: 0.1254 | Val ROC-AUC: 0.9635 | Val Profit: -400
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9653
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 26 | Train Loss: 0.1210 | Val ROC-AUC: 0.9653 | Val Profit: -450
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9642
Precision: 0.4516
Recall: 0.6667
F0.5-score: 0.4828
Profit: -390

Эпоха 27 | Train Loss: 0.1157 | Val ROC-AUC: 0.9642 | Val Profit: -390
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9647
Precision: 0.4412
Recall: 0.7143
F0.5-score: 0.4777
Profit: -430

Эпоха 28 | Train Loss: 0.1126 | Val ROC-AUC: 0.9647 | Val Profit: -430
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9663
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 29 | Train Loss: 0.0928 | Val ROC-AUC: 0.9663 | Val Profit: -375
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9674
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 30 | Train Loss: 0.0882 | Val ROC-AUC: 0.9674 | Val Profit: -330
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9675
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 31 | Train Loss: 0.0872 | Val ROC-AUC: 0.9675 | Val Profit: -330
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9713
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 32 | Train Loss: 0.0810 | Val ROC-AUC: 0.9713 | Val Profit: -280
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9717
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 33 | Train Loss: 0.0809 | Val ROC-AUC: 0.9717 | Val Profit: -330
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9701
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 34 | Train Loss: 0.0775 | Val ROC-AUC: 0.9701 | Val Profit: -280
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9741
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 35 | Train Loss: 0.0743 | Val ROC-AUC: 0.9741 | Val Profit: -350
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9734
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 36 | Train Loss: 0.0739 | Val ROC-AUC: 0.9734 | Val Profit: -285
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9752
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 37 | Train Loss: 0.0827 | Val ROC-AUC: 0.9752 | Val Profit: -300
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9753
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 38 | Train Loss: 0.0718 | Val ROC-AUC: 0.9753 | Val Profit: -400
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9725
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 39 | Train Loss: 0.0702 | Val ROC-AUC: 0.9725 | Val Profit: -360
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9741
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 40 | Train Loss: 0.0673 | Val ROC-AUC: 0.9741 | Val Profit: -285

Лучшая эпоха для model_5_tolko_dropout: 38
Лучший ROC-AUC: 0.9753185781354795
val
ROC-AUC: 0.9753
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.8951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 1.3107 | Val ROC-AUC: 0.8951 | Val Profit: -105
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9378
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 1.2916 | Val ROC-AUC: 0.9378 | Val Profit: -105
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9599
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 3 | Train Loss: 1.1944 | Val ROC-AUC: 0.9599 | Val Profit: -445
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.952
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 4 | Train Loss: 1.0006 | Val ROC-AUC: 0.9520 | Val Profit: -525
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9504
Precision: 0.3617
Recall: 0.8095
F0.5-score: 0.4067
Profit: -685

Эпоха 5 | Train Loss: 0.8070 | Val ROC-AUC: 0.9504 | Val Profit: -685
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9586
Precision: 0.3778
Recall: 0.8095
F0.5-score: 0.4229
Profit: -635

Эпоха 6 | Train Loss: 0.5830 | Val ROC-AUC: 0.9586 | Val Profit: -635

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.963
Precision: 0.3519
Recall: 0.9048
F0.5-score: 0.4008
Profit: -790

Эпоха 7 | Train Loss: 0.4533 | Val ROC-AUC: 0.9630 | Val Profit: -790
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9604
Precision: 0.3387
Recall: 1.0
F0.5-score: 0.3903
Profit: -920

Эпоха 8 | Train Loss: 0.4002 | Val ROC-AUC: 0.9604 | Val Profit: -920
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.961
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 9 | Train Loss: 0.3737 | Val ROC-AUC: 0.9610 | Val Profit: -590
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9615
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 10 | Train Loss: 0.3062 | Val ROC-AUC: 0.9615 | Val Profit: -325
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9604
Precision: 0.4
Recall: 0.6667
F0.5-score: 0.4348
Profit: -490

Эпоха 11 | Train Loss: 0.2362 | Val ROC-AUC: 0.9604 | Val Profit: -490
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9622
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 12 | Train Loss: 0.2143 | Val ROC-AUC: 0.9622 | Val Profit: -325
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9618
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 13 | Train Loss: 0.1873 | Val ROC-AUC: 0.9618 | Val Profit: -285
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.96
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 14 | Train Loss: 0.1703 | Val ROC-AUC: 0.9600 | Val Profit: -230
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.962
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 15 | Train Loss: 0.1553 | Val ROC-AUC: 0.9620 | Val Profit: -310
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9631
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 16 | Train Loss: 0.1369 | Val ROC-AUC: 0.9631 | Val Profit: -255
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.962
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 17 | Train Loss: 0.1255 | Val ROC-AUC: 0.9620 | Val Profit: -215
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.961
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 18 | Train Loss: 0.1148 | Val ROC-AUC: 0.9610 | Val Profit: -215
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9611
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 19 | Train Loss: 0.1075 | Val ROC-AUC: 0.9611 | Val Profit: -215
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9612
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 20 | Train Loss: 0.1032 | Val ROC-AUC: 0.9612 | Val Profit: -255
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9608
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 21 | Train Loss: 0.1001 | Val ROC-AUC: 0.9608 | Val Profit: -165
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9608
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 22 | Train Loss: 0.0972 | Val ROC-AUC: 0.9608 | Val Profit: -190
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9603
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 23 | Train Loss: 0.0949 | Val ROC-AUC: 0.9603 | Val Profit: -190
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9602
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 24 | Train Loss: 0.0930 | Val ROC-AUC: 0.9602 | Val Profit: -165
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9596
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 25 | Train Loss: 0.0905 | Val ROC-AUC: 0.9596 | Val Profit: -175
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9598
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 26 | Train Loss: 0.0881 | Val ROC-AUC: 0.9598 | Val Profit: -170
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9619
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 27 | Train Loss: 0.0864 | Val ROC-AUC: 0.9619 | Val Profit: -215
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9607
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 28 | Train Loss: 0.0828 | Val ROC-AUC: 0.9607 | Val Profit: -240
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.959
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 29 | Train Loss: 0.0786 | Val ROC-AUC: 0.9590 | Val Profit: -170
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9598
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 30 | Train Loss: 0.0752 | Val ROC-AUC: 0.9598 | Val Profit: -175
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.96
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 31 | Train Loss: 0.0734 | Val ROC-AUC: 0.9600 | Val Profit: -170
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9604
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 32 | Train Loss: 0.0714 | Val ROC-AUC: 0.9604 | Val Profit: -170
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9602
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 33 | Train Loss: 0.0704 | Val ROC-AUC: 0.9602 | Val Profit: -170
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9607
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 34 | Train Loss: 0.0695 | Val ROC-AUC: 0.9607 | Val Profit: -170
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9607
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 35 | Train Loss: 0.0688 | Val ROC-AUC: 0.9607 | Val Profit: -170
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.961
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 36 | Train Loss: 0.0682 | Val ROC-AUC: 0.9610 | Val Profit: -170
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.961
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 37 | Train Loss: 0.0675 | Val ROC-AUC: 0.9610 | Val Profit: -170
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9608
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 38 | Train Loss: 0.0670 | Val ROC-AUC: 0.9608 | Val Profit: -170
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9595
Precision: 0.4545
Recall: 0.4762
F0.5-score: 0.4587
Profit: -305

Эпоха 39 | Train Loss: 0.0665 | Val ROC-AUC: 0.9595 | Val Profit: -305
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9591
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 40 | Train Loss: 0.0698 | Val ROC-AUC: 0.9591 | Val Profit: -170

Лучшая эпоха для model_5_tolko_dropout: 16
Лучший ROC-AUC: 0.9631120053655264
val
ROC-AUC: 0.9631
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

In [88]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.005, 'dropout': 0.015, 'profit': np.int64(-80), 'roc_auc': 0.9856472166331322}

In [89]:
LR = best["lr"]
DROPOUT_COEF = best["dropout"]

In [90]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_5 = nn.Sequential(
    nn.Linear(9, 128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_5.parameters(), lr=LR)

config = {
    "model": "MLP_dropout_only",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "dropout_coef": DROPOUT_COEF,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_5)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_5_dropout_only", config=config)
log_file = new_log_file()

model_5 = train_model(
    model=model_5,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_5_tolko_dropout"
)

save_results(model_5, "model_5", log_file, run)

run.finish()

model_5_tolko_dropout | valid epoch 1
ROC-AUC: 0.9375
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 1 | Train Loss: 1.1719 | Val ROC-AUC: 0.9375 | Val Profit: -1030
model_5_tolko_dropout | valid epoch 2
ROC-AUC: 0.9333
Precision: 0.1909
Recall: 1.0
F0.5-score: 0.2278
Profit: -2120

Эпоха 2 | Train Loss: 0.7785 | Val ROC-AUC: 0.9333 | Val Profit: -2120
model_5_tolko_dropout | valid epoch 3
ROC-AUC: 0.9586
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 3 | Train Loss: 0.5299 | Val ROC-AUC: 0.9586 | Val Profit: -1495
model_5_tolko_dropout | valid epoch 4
ROC-AUC: 0.9518
Precision: 0.2039
Recall: 1.0
F0.5-score: 0.2425
Profit: -1945

Эпоха 4 | Train Loss: 0.5074 | Val ROC-AUC: 0.9518 | Val Profit: -1945
model_5_tolko_dropout | valid epoch 5
ROC-AUC: 0.9549
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 5 | Train Loss: 0.4923 | Val ROC-AUC: 0.9549 | Val Profit: -1620
model_5_tolko_dropout | valid epoch 6
ROC-AUC: 0.9524
Precision: 0.2714
Recall: 0.9048
F0.5-score: 0.3156
Profit: -1190

Эпоха 6 | Train Loss: 0.3864 | Val ROC-AUC: 0.9524 | Val Profit: -1190
model_5_tolko_dropout | valid epoch 7
ROC-AUC: 0.9632
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 7 | Train Loss: 0.3827 | Val ROC-AUC: 0.9632 | Val Profit: -1195
model_5_tolko_dropout | valid epoch 8
ROC-AUC: 0.9551
Precision: 0.2879
Recall: 0.9048
F0.5-score: 0.3333
Profit: -1090

Эпоха 8 | Train Loss: 0.3089 | Val ROC-AUC: 0.9551 | Val Profit: -1090
model_5_tolko_dropout | valid epoch 9
ROC-AUC: 0.9673
Precision: 0.3654
Recall: 0.9048
F0.5-score: 0.4148
Profit: -740

Эпоха 9 | Train Loss: 0.2616 | Val ROC-AUC: 0.9673 | Val Profit: -740
model_5_tolko_dropout | valid epoch 10
ROC-AUC: 0.9646
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 10 | Train Loss: 0.2828 | Val ROC-AUC: 0.9646 | Val Profit: -805
model_5_tolko_dropout | valid epoch 11
ROC-AUC: 0.9622
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 11 | Train Loss: 0.2415 | Val ROC-AUC: 0.9622 | Val Profit: -940
model_5_tolko_dropout | valid epoch 12
ROC-AUC: 0.9579
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 12 | Train Loss: 0.2131 | Val ROC-AUC: 0.9579 | Val Profit: -615
model_5_tolko_dropout | valid epoch 13
ROC-AUC: 0.9657
Precision: 0.4091
Recall: 0.8571
F0.5-score: 0.4569
Profit: -575

Эпоха 13 | Train Loss: 0.2279 | Val ROC-AUC: 0.9657 | Val Profit: -575
model_5_tolko_dropout | valid epoch 14
ROC-AUC: 0.963
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 14 | Train Loss: 0.1923 | Val ROC-AUC: 0.9630 | Val Profit: -945
model_5_tolko_dropout | valid epoch 15
ROC-AUC: 0.9641
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 15 | Train Loss: 0.3091 | Val ROC-AUC: 0.9641 | Val Profit: -1095
model_5_tolko_dropout | valid epoch 16
ROC-AUC: 0.9687
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 16 | Train Loss: 0.2899 | Val ROC-AUC: 0.9687 | Val Profit: -995
model_5_tolko_dropout | valid epoch 17
ROC-AUC: 0.9646
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 17 | Train Loss: 0.2232 | Val ROC-AUC: 0.9646 | Val Profit: -1055
model_5_tolko_dropout | valid epoch 18
ROC-AUC: 0.9641
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 18 | Train Loss: 0.2441 | Val ROC-AUC: 0.9641 | Val Profit: -1170
model_5_tolko_dropout | valid epoch 19
ROC-AUC: 0.9661
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 19 | Train Loss: 0.2098 | Val ROC-AUC: 0.9661 | Val Profit: -955
model_5_tolko_dropout | valid epoch 20
ROC-AUC: 0.9636
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 20 | Train Loss: 0.2164 | Val ROC-AUC: 0.9636 | Val Profit: -615
model_5_tolko_dropout | valid epoch 21
ROC-AUC: 0.9446
Precision: 0.2923
Recall: 0.9048
F0.5-score: 0.3381
Profit: -1065

Эпоха 21 | Train Loss: 0.1939 | Val ROC-AUC: 0.9446 | Val Profit: -1065
model_5_tolko_dropout | valid epoch 22
ROC-AUC: 0.9705
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 22 | Train Loss: 0.3508 | Val ROC-AUC: 0.9705 | Val Profit: -1245
model_5_tolko_dropout | valid epoch 23
ROC-AUC: 0.9756
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 23 | Train Loss: 0.2177 | Val ROC-AUC: 0.9756 | Val Profit: -615
model_5_tolko_dropout | valid epoch 24
ROC-AUC: 0.9738
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 24 | Train Loss: 0.1664 | Val ROC-AUC: 0.9738 | Val Profit: -515
model_5_tolko_dropout | valid epoch 25
ROC-AUC: 0.9709
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 25 | Train Loss: 0.1635 | Val ROC-AUC: 0.9709 | Val Profit: -1020
model_5_tolko_dropout | valid epoch 26
ROC-AUC: 0.9634
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 26 | Train Loss: 0.2715 | Val ROC-AUC: 0.9634 | Val Profit: -1220
model_5_tolko_dropout | valid epoch 27
ROC-AUC: 0.9729
Precision: 0.3585
Recall: 0.9048
F0.5-score: 0.4077
Profit: -765

Эпоха 27 | Train Loss: 0.2298 | Val ROC-AUC: 0.9729 | Val Profit: -765
model_5_tolko_dropout | valid epoch 28
ROC-AUC: 0.9767
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 28 | Train Loss: 0.1426 | Val ROC-AUC: 0.9767 | Val Profit: -385
model_5_tolko_dropout | valid epoch 29
ROC-AUC: 0.9653
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 29 | Train Loss: 0.2551 | Val ROC-AUC: 0.9653 | Val Profit: -1220
model_5_tolko_dropout | valid epoch 30
ROC-AUC: 0.9586
Precision: 0.2778
Recall: 0.9524
F0.5-score: 0.3236
Profit: -1205

Эпоха 30 | Train Loss: 0.2924 | Val ROC-AUC: 0.9586 | Val Profit: -1205
model_5_tolko_dropout | valid epoch 31
ROC-AUC: 0.9722
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 31 | Train Loss: 0.2056 | Val ROC-AUC: 0.9722 | Val Profit: -690
model_5_tolko_dropout | valid epoch 32
ROC-AUC: 0.9783
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 32 | Train Loss: 0.1468 | Val ROC-AUC: 0.9783 | Val Profit: -465
model_5_tolko_dropout | valid epoch 33
ROC-AUC: 0.9788
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 33 | Train Loss: 0.1231 | Val ROC-AUC: 0.9788 | Val Profit: -480
model_5_tolko_dropout | valid epoch 34
ROC-AUC: 0.9655
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 34 | Train Loss: 0.1473 | Val ROC-AUC: 0.9655 | Val Profit: -590
model_5_tolko_dropout | valid epoch 35
ROC-AUC: 0.9638
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 35 | Train Loss: 0.2314 | Val ROC-AUC: 0.9638 | Val Profit: -590
model_5_tolko_dropout | valid epoch 36
ROC-AUC: 0.9769
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 36 | Train Loss: 0.1539 | Val ROC-AUC: 0.9769 | Val Profit: -530
model_5_tolko_dropout | valid epoch 37
ROC-AUC: 0.9779
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 37 | Train Loss: 0.1165 | Val ROC-AUC: 0.9779 | Val Profit: -400
model_5_tolko_dropout | valid epoch 38
ROC-AUC: 0.9788
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 38 | Train Loss: 0.0989 | Val ROC-AUC: 0.9788 | Val Profit: -245
model_5_tolko_dropout | valid epoch 39
ROC-AUC: 0.9827
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 39 | Train Loss: 0.0786 | Val ROC-AUC: 0.9827 | Val Profit: -145
model_5_tolko_dropout | valid epoch 40
ROC-AUC: 0.9856
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

Эпоха 40 | Train Loss: 0.0913 | Val ROC-AUC: 0.9856 | Val Profit: -80

Лучшая эпоха для model_5_tolko_dropout: 40
Лучший ROC-AUC: 0.9856472166331322
Train
ROC-AUC: 0.9959
Precision: 0.8642
Recall: 0.8434
F0.5-score: 0.86
Profit: 10

Test
ROC-AUC: 0.9804
Precision: 0.7128
Recall: 0.6384
F0.5-score: 0.6966
Profit: -119740

In [91]:
train_metrics = evaluate_model(model_5, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_5, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9959
Precision: 0.8642
Recall: 0.8434
F0.5-score: 0.86
Profit: 10

Test
ROC-AUC: 0.9804
Precision: 0.7128
Recall: 0.6384
F0.5-score: 0.6966
Profit: -119740

В этом эксперименте добавили только dropout и подбирали его коэффициент перебором. Лучшее качество получилось при dropout = 0.015

Увеличение колво эпох не улучшило ситуацию с переобучением

Это чуть хуже бейзлайна, но батчнорм показал себя лучше, чем дропаут в этом эксперименте

## model_6_batchnorm_i_dropout

In [92]:
EPOCHS = 30
SEED = 42

In [93]:
wandb.init(mode="disabled")
results = []
for LR in [0.01, 0.005, 0.001]:
    for DROPOUT_COEF in [0.05, 0.1, 0.015, 0.2, 0.025, 0.3]:
        random.seed(SEED)
        np.random.seed(SEED)
        torch.manual_seed(SEED) 

        model_6 = nn.Sequential(
            nn.Linear(9, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(64, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(32, 16),
            nn.BatchNorm1d(16),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(16, 8),
            nn.BatchNorm1d(8),
            nn.ReLU(),
            nn.Dropout(DROPOUT_COEF),

            nn.Linear(8, 1)
        )

        loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        optimizer = torch.optim.Adam(model_6.parameters(), lr=LR)
        model_6 = train_model(
            model=model_6,
            train_loader=train_loader,
            X_valid=X_val,
            y_valid=y_val,
            loss_fn=loss_fn,
            optimizer=optimizer,
            epochs=EPOCHS,
            threshold=0.5,
            model_name="model_6_batchnorm_i_dropout"
        )

        val = evaluate_model(model_6, X_val, y_val, threshold=0.5, name="val")
        results.append({"lr": LR, "dropout": DROPOUT_COEF, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_6_batchnorm_i_dropout | valid epoch 1
ROC-AUC: 0.9635
Precision: 0.1346
Recall: 1.0
F0.5-score: 0.1628
Profit: -3270

Эпоха 1 | Train Loss: 1.0119 | Val ROC-AUC: 0.9635 | Val Profit: -3270
model_6_batchnorm_i_dropout | valid epoch 2
ROC-AUC: 0.9581
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 2 | Train Loss: 0.5804 | Val ROC-AUC: 0.9581 | Val Profit: -1645
model_6_batchnorm_i_dropout | valid epoch 3
ROC-AUC: 0.9683
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 3 | Train Loss: 0.3780 | Val ROC-AUC: 0.9683 | Val Profit: -1270
model_6_batchnorm_i_dropout | valid epoch 4
ROC-AUC: 0.9602
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 4 | Train Loss: 0.3449 | Val ROC-AUC: 0.9602 | Val Profit: -995
model_6_batchnorm_i_dropout | valid epoch 5
ROC-AUC: 0.9347
Precision: 0.2647
Recall: 0.8571
F0.5-score: 0.3072
Profit: -1175

Эпоха 5 | Train Loss: 0.3749 | Val ROC-AUC: 0.9347 | Val Profit: -1175
model_6_batchnorm_i_dropout | valid epoch 6
ROC-AUC: 0.9701
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 6 | Train Loss: 0.3203 | Val ROC-AUC: 0.9701 | Val Profit: -1070
model_6_batchnorm_i_dropout | valid epoch 7
ROC-AUC: 0.9768
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 7 | Train Loss: 0.2549 | Val ROC-AUC: 0.9768 | Val Profit: -530
model_6_batchnorm_i_dropout | valid epoch 8
ROC-AUC: 0.9792
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 8 | Train Loss: 0.1697 | Val ROC-AUC: 0.9792 | Val Profit: -280
model_6_batchnorm_i_dropout | valid epoch 9
ROC-AUC: 0.9465
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 9 | Train Loss: 0.1356 | Val ROC-AUC: 0.9465 | Val Profit: -150
model_6_batchnorm_i_dropout | valid epoch 10
ROC-AUC: 0.9669
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 10 | Train Loss: 0.2840 | Val ROC-AUC: 0.9669 | Val Profit: -1445
model_6_batchnorm_i_dropout | valid epoch 11
ROC-AUC: 0.9588
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 11 | Train Loss: 0.4201 | Val ROC-AUC: 0.9588 | Val Profit: -1770
model_6_batchnorm_i_dropout | valid epoch 12
ROC-AUC: 0.9761
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 12 | Train Loss: 0.3356 | Val ROC-AUC: 0.9761 | Val Profit: -970
model_6_batchnorm_i_dropout | valid epoch 13
ROC-AUC: 0.978
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 13 | Train Loss: 0.2493 | Val ROC-AUC: 0.9780 | Val Profit: -670
model_6_batchnorm_i_dropout | valid epoch 14
ROC-AUC: 0.9386
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 14 | Train Loss: 0.1931 | Val ROC-AUC: 0.9386 | Val Profit: -270
model_6_batchnorm_i_dropout | valid epoch 15
ROC-AUC: 0.934
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 15 | Train Loss: 0.1456 | Val ROC-AUC: 0.9340 | Val Profit: -465
model_6_batchnorm_i_dropout | valid epoch 16
ROC-AUC: 0.9771
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 16 | Train Loss: 0.1473 | Val ROC-AUC: 0.9771 | Val Profit: -205
model_6_batchnorm_i_dropout | valid epoch 17
ROC-AUC: 0.9753
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 17 | Train Loss: 0.1196 | Val ROC-AUC: 0.9753 | Val Profit: -260
model_6_batchnorm_i_dropout | valid epoch 18
ROC-AUC: 0.8912
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 18 | Train Loss: 0.0962 | Val ROC-AUC: 0.8912 | Val Profit: -125
model_6_batchnorm_i_dropout | valid epoch 19
ROC-AUC: 0.8991
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 19 | Train Loss: 0.1465 | Val ROC-AUC: 0.8991 | Val Profit: -150
model_6_batchnorm_i_dropout | valid epoch 20
ROC-AUC: 0.8736
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 20 | Train Loss: 0.0787 | Val ROC-AUC: 0.8736 | Val Profit: -100
model_6_batchnorm_i_dropout | valid epoch 21
ROC-AUC: 0.8294
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 21 | Train Loss: 0.0619 | Val ROC-AUC: 0.8294 | Val Profit: -90
model_6_batchnorm_i_dropout | valid epoch 22
ROC-AUC: 0.8443
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 22 | Train Loss: 0.0477 | Val ROC-AUC: 0.8443 | Val Profit: -105
model_6_batchnorm_i_dropout | valid epoch 23
ROC-AUC: 0.9403
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 23 | Train Loss: 0.1142 | Val ROC-AUC: 0.9403 | Val Profit: -450
model_6_batchnorm_i_dropout | valid epoch 24
ROC-AUC: 0.9548
Precision: 0.2667
Recall: 0.9524
F0.5-score: 0.3115
Profit: -1280

Эпоха 24 | Train Loss: 0.4151 | Val ROC-AUC: 0.9548 | Val Profit: -1280
model_6_batchnorm_i_dropout | valid epoch 25
ROC-AUC: 0.9661
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 25 | Train Loss: 0.3765 | Val ROC-AUC: 0.9661 | Val Profit: -1120
model_6_batchnorm_i_dropout | valid epoch 26
ROC-AUC: 0.9737
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 26 | Train Loss: 0.2274 | Val ROC-AUC: 0.9737 | Val Profit: -400
model_6_batchnorm_i_dropout | valid epoch 27
ROC-AUC: 0.9737
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 27 | Train Loss: 0.1691 | Val ROC-AUC: 0.9737 | Val Profit: -335
model_6_batchnorm_i_dropout | valid epoch 28
ROC-AUC: 0.8412
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 28 | Train Loss: 0.1238 | Val ROC-AUC: 0.8412 | Val Profit: -180
model_6_batchnorm_i_dropout | valid epoch 29
ROC-AUC: 0.9422
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 29 | Train Loss: 0.1029 | Val ROC-AUC: 0.9422 | Val Profit: -200
model_6_batchnorm_i_dropout | valid epoch 30
ROC-AUC: 0.9744
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 30 | Train Loss: 0.1387 | Val ROC-AUC: 0.9744 | Val Profit: -415

Лучшая эпоха для model_6_batchnorm_i_dropout: 8
Лучший ROC-AUC: 0.9792085848423876
val
ROC-AUC: 0.9792
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

model_6_batchnorm_i_dropout | valid epoch 1
ROC-AUC: 0.9386
Precision: 0.1186
Recall: 1.0
F0.5-score: 0.144
Profit: -3795

Эпоха 1 | Train Loss: 1.2003 | Val ROC-AUC: 0.9386 | Val Profit: -3795
model_6_batchnorm_i_dropout | valid epoch 2
ROC-AUC: 0.9673
Precision: 0.168
Recall: 1.0
F0.5-score: 0.2015
Profit: -2495

Эпоха 2 | Train Loss: 0.7723 | Val ROC-AUC: 0.9673 | Val Profit: -2495
model_6_batchnorm_i_dropout | valid epoch 3
ROC-AUC: 0.9674
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 3 | Train Loss: 0.4746 | Val ROC-AUC: 0.9674 | Val Profit: -995
model_6_batchnorm_i_dropout | valid epoch 4
ROC-AUC: 0.9779
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 4 | Train Loss: 0.3837 | Val ROC-AUC: 0.9779 | Val Profit: -995
model_6_batchnorm_i_dropout | valid epoch 5
ROC-AUC: 0.9587
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 5 | Train Loss: 0.3644 | Val ROC-AUC: 0.9587 | Val Profit: -1170
model_6_batchnorm_i_dropout | valid epoch 6
ROC-AUC: 0.9729
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 6 | Train Loss: 0.2865 | Val ROC-AUC: 0.9729 | Val Profit: -505
model_6_batchnorm_i_dropout | valid epoch 7
ROC-AUC: 0.9697
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 7 | Train Loss: 0.3021 | Val ROC-AUC: 0.9697 | Val Profit: -945
model_6_batchnorm_i_dropout | valid epoch 8
ROC-AUC: 0.9764
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 8 | Train Loss: 0.2535 | Val ROC-AUC: 0.9764 | Val Profit: -265
model_6_batchnorm_i_dropout | valid epoch 9
ROC-AUC: 0.9793
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 9 | Train Loss: 0.1644 | Val ROC-AUC: 0.9793 | Val Profit: -245
model_6_batchnorm_i_dropout | valid epoch 10
ROC-AUC: 0.9572
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 10 | Train Loss: 0.1972 | Val ROC-AUC: 0.9572 | Val Profit: -970
model_6_batchnorm_i_dropout | valid epoch 11
ROC-AUC: 0.9763
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 11 | Train Loss: 0.2817 | Val ROC-AUC: 0.9763 | Val Profit: -845
model_6_batchnorm_i_dropout | valid epoch 12
ROC-AUC: 0.973
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 12 | Train Loss: 0.2167 | Val ROC-AUC: 0.9730 | Val Profit: -295
model_6_batchnorm_i_dropout | valid epoch 13
ROC-AUC: 0.9799
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 13 | Train Loss: 0.1707 | Val ROC-AUC: 0.9799 | Val Profit: -340
model_6_batchnorm_i_dropout | valid epoch 14
ROC-AUC: 0.974
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 14 | Train Loss: 0.1709 | Val ROC-AUC: 0.9740 | Val Profit: -145
model_6_batchnorm_i_dropout | valid epoch 15
ROC-AUC: 0.9717
Precision: 0.5185
Recall: 0.6667
F0.5-score: 0.5426
Profit: -290

Эпоха 15 | Train Loss: 0.1230 | Val ROC-AUC: 0.9717 | Val Profit: -290
model_6_batchnorm_i_dropout | valid epoch 16
ROC-AUC: 0.8687
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 16 | Train Loss: 0.1058 | Val ROC-AUC: 0.8687 | Val Profit: -180
model_6_batchnorm_i_dropout | valid epoch 17
ROC-AUC: 0.9619
Precision: 0.7778
Recall: 0.6667
F0.5-score: 0.7527
Profit: -65

Эпоха 17 | Train Loss: 0.0751 | Val ROC-AUC: 0.9619 | Val Profit: -65
model_6_batchnorm_i_dropout | valid epoch 18
ROC-AUC: 0.9548
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 18 | Train Loss: 0.3302 | Val ROC-AUC: 0.9548 | Val Profit: -1120
model_6_batchnorm_i_dropout | valid epoch 19
ROC-AUC: 0.9725
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 19 | Train Loss: 0.2887 | Val ROC-AUC: 0.9725 | Val Profit: -565
model_6_batchnorm_i_dropout | valid epoch 20
ROC-AUC: 0.9717
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 20 | Train Loss: 0.1575 | Val ROC-AUC: 0.9717 | Val Profit: -330
model_6_batchnorm_i_dropout | valid epoch 21
ROC-AUC: 0.9716
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 21 | Train Loss: 0.1321 | Val ROC-AUC: 0.9716 | Val Profit: -205
model_6_batchnorm_i_dropout | valid epoch 22
ROC-AUC: 0.9734
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 22 | Train Loss: 0.1099 | Val ROC-AUC: 0.9734 | Val Profit: -135
model_6_batchnorm_i_dropout | valid epoch 23
ROC-AUC: 0.9599
Precision: 0.3636
Recall: 0.1905
F0.5-score: 0.3077
Profit: -240

Эпоха 23 | Train Loss: 0.0823 | Val ROC-AUC: 0.9599 | Val Profit: -240
model_6_batchnorm_i_dropout | valid epoch 24
ROC-AUC: 0.9687
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 24 | Train Loss: 0.0797 | Val ROC-AUC: 0.9687 | Val Profit: -205
model_6_batchnorm_i_dropout | valid epoch 25
ROC-AUC: 0.9722
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 25 | Train Loss: 0.0641 | Val ROC-AUC: 0.9722 | Val Profit: -135
model_6_batchnorm_i_dropout | valid epoch 26
ROC-AUC: 0.9753
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 26 | Train Loss: 0.0517 | Val ROC-AUC: 0.9753 | Val Profit: -170
model_6_batchnorm_i_dropout | valid epoch 27
ROC-AUC: 0.9729
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 27 | Train Loss: 0.0546 | Val ROC-AUC: 0.9729 | Val Profit: -185
model_6_batchnorm_i_dropout | valid epoch 28
ROC-AUC: 0.9789
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 28 | Train Loss: 0.2057 | Val ROC-AUC: 0.9789 | Val Profit: -455
model_6_batchnorm_i_dropout | valid epoch 29
ROC-AUC: 0.969
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 29 | Train Loss: 0.3019 | Val ROC-AUC: 0.9690 | Val Profit: -680
model_6_batchnorm_i_dropout | valid epoch 30
ROC-AUC: 0.9728
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 30 | Train Loss: 0.1858 | Val ROC-AUC: 0.9728 | Val Profit: -245

Лучшая эпоха для model_6_batchnorm_i_dropout: 13
Лучший ROC-AUC: 0.9798792756539236
val
ROC-AUC: 0.9799
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

model_6_batchnorm_i_dropout | valid epoch 1
ROC-AUC: 0.9466
Precision: 0.1313
Recall: 1.0
F0.5-score: 0.1589
Profit: -3370

Эпоха 1 | Train Loss: 1.0749 | Val ROC-AUC: 0.9466 | Val Profit: -3370
model_6_batchnorm_i_dropout | valid epoch 2
ROC-AUC: 0.9548
Precision: 0.2
Recall: 1.0
F0.5-score: 0.2381
Profit: -1995

Эпоха 2 | Train Loss: 0.6102 | Val ROC-AUC: 0.9548 | Val Profit: -1995
model_6_batchnorm_i_dropout | valid epoch 3
ROC-AUC: 0.9608
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 3 | Train Loss: 0.4140 | Val ROC-AUC: 0.9608 | Val Profit: -1645
model_6_batchnorm_i_dropout | valid epoch 4
ROC-AUC: 0.9547
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 4 | Train Loss: 0.3417 | Val ROC-AUC: 0.9547 | Val Profit: -1030
model_6_batchnorm_i_dropout | valid epoch 5
ROC-AUC: 0.9694
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 5 | Train Loss: 0.3134 | Val ROC-AUC: 0.9694 | Val Profit: -830
model_6_batchnorm_i_dropout | valid epoch 6
ROC-AUC: 0.9725
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 6 | Train Loss: 0.2568 | Val ROC-AUC: 0.9725 | Val Profit: -490
model_6_batchnorm_i_dropout | valid epoch 7
ROC-AUC: 0.9547
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 7 | Train Loss: 0.3211 | Val ROC-AUC: 0.9547 | Val Profit: -980
model_6_batchnorm_i_dropout | valid epoch 8
ROC-AUC: 0.9753
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 8 | Train Loss: 0.2775 | Val ROC-AUC: 0.9753 | Val Profit: -695
model_6_batchnorm_i_dropout | valid epoch 9
ROC-AUC: 0.9738
Precision: 0.425
Recall: 0.8095
F0.5-score: 0.4696
Profit: -510

Эпоха 9 | Train Loss: 0.2132 | Val ROC-AUC: 0.9738 | Val Profit: -510
model_6_batchnorm_i_dropout | valid epoch 10
ROC-AUC: 0.9788
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 10 | Train Loss: 0.1965 | Val ROC-AUC: 0.9788 | Val Profit: -410
model_6_batchnorm_i_dropout | valid epoch 11
ROC-AUC: 0.982
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 11 | Train Loss: 0.2246 | Val ROC-AUC: 0.9820 | Val Profit: -350
model_6_batchnorm_i_dropout | valid epoch 12
ROC-AUC: 0.9705
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 12 | Train Loss: 0.2432 | Val ROC-AUC: 0.9705 | Val Profit: -995
model_6_batchnorm_i_dropout | valid epoch 13
ROC-AUC: 0.9793
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 13 | Train Loss: 0.3483 | Val ROC-AUC: 0.9793 | Val Profit: -820
model_6_batchnorm_i_dropout | valid epoch 14
ROC-AUC: 0.9745
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 14 | Train Loss: 0.2560 | Val ROC-AUC: 0.9745 | Val Profit: -380
model_6_batchnorm_i_dropout | valid epoch 15
ROC-AUC: 0.9771
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 15 | Train Loss: 0.1810 | Val ROC-AUC: 0.9771 | Val Profit: -140
model_6_batchnorm_i_dropout | valid epoch 16
ROC-AUC: 0.9551
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 16 | Train Loss: 0.1754 | Val ROC-AUC: 0.9551 | Val Profit: -290
model_6_batchnorm_i_dropout | valid epoch 17
ROC-AUC: 0.9818
Precision: 0.6207
Recall: 0.8571
F0.5-score: 0.6569
Profit: -200

Эпоха 17 | Train Loss: 0.2243 | Val ROC-AUC: 0.9818 | Val Profit: -200
model_6_batchnorm_i_dropout | valid epoch 18
ROC-AUC: 0.9771
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

Эпоха 18 | Train Loss: 0.1587 | Val ROC-AUC: 0.9771 | Val Profit: -80
model_6_batchnorm_i_dropout | valid epoch 19
ROC-AUC: 0.9561
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 19 | Train Loss: 0.1428 | Val ROC-AUC: 0.9561 | Val Profit: -90
model_6_batchnorm_i_dropout | valid epoch 20
ROC-AUC: 0.9748
Precision: 0.5938
Recall: 0.9048
F0.5-score: 0.6376
Profit: -240

Эпоха 20 | Train Loss: 0.1268 | Val ROC-AUC: 0.9748 | Val Profit: -240
model_6_batchnorm_i_dropout | valid epoch 21
ROC-AUC: 0.9755
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 21 | Train Loss: 0.1788 | Val ROC-AUC: 0.9755 | Val Profit: -280
model_6_batchnorm_i_dropout | valid epoch 22
ROC-AUC: 0.9726
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 22 | Train Loss: 0.1419 | Val ROC-AUC: 0.9726 | Val Profit: -115
model_6_batchnorm_i_dropout | valid epoch 23
ROC-AUC: 0.9687
Precision: 0.8
Recall: 0.5714
F0.5-score: 0.7407
Profit: -60

Эпоха 23 | Train Loss: 0.0910 | Val ROC-AUC: 0.9687 | Val Profit: -60
model_6_batchnorm_i_dropout | valid epoch 24
ROC-AUC: 0.9608
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 24 | Train Loss: 0.1342 | Val ROC-AUC: 0.9608 | Val Profit: -995
model_6_batchnorm_i_dropout | valid epoch 25
ROC-AUC: 0.9741
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 25 | Train Loss: 0.3372 | Val ROC-AUC: 0.9741 | Val Profit: -930
model_6_batchnorm_i_dropout | valid epoch 26
ROC-AUC: 0.971
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 26 | Train Loss: 0.2151 | Val ROC-AUC: 0.9710 | Val Profit: -245
model_6_batchnorm_i_dropout | valid epoch 27
ROC-AUC: 0.9702
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 27 | Train Loss: 0.1545 | Val ROC-AUC: 0.9702 | Val Profit: -90
model_6_batchnorm_i_dropout | valid epoch 28
ROC-AUC: 0.9741
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 28 | Train Loss: 0.1202 | Val ROC-AUC: 0.9741 | Val Profit: -135
model_6_batchnorm_i_dropout | valid epoch 29
ROC-AUC: 0.9732
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 29 | Train Loss: 0.1024 | Val ROC-AUC: 0.9732 | Val Profit: -125
model_6_batchnorm_i_dropout | valid epoch 30
ROC-AUC: 0.9704
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 30 | Train Loss: 0.1005 | Val ROC-AUC: 0.9704 | Val Profit: -150

Лучшая эпоха для model_6_batchnorm_i_dropout: 11
Лучший ROC-AUC: 0.9820254862508383
val
ROC-AUC: 0.982
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

model_6_batchnorm_i_dropout | valid epoch 1
ROC-AUC: 0.9455
Precision: 0.1346
Recall: 1.0
F0.5-score: 0.1628
Profit: -3270

Эпоха 1 | Train Loss: 1.1858 | Val ROC-AUC: 0.9455 | Val Profit: -3270
model_6_batchnorm_i_dropout | valid epoch 2
ROC-AUC: 0.9384
Precision: 0.1556
Recall: 1.0
F0.5-score: 0.1872
Profit: -2745

Эпоха 2 | Train Loss: 0.7990 | Val ROC-AUC: 0.9384 | Val Profit: -2745
model_6_batchnorm_i_dropout | valid epoch 3
ROC-AUC: 0.9526
Precision: 0.3065
Recall: 0.9048
F0.5-score: 0.3532
Profit: -990

Эпоха 3 | Train Loss: 0.5094 | Val ROC-AUC: 0.9526 | Val Profit: -990
model_6_batchnorm_i_dropout | valid epoch 4
ROC-AUC: 0.8451
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 4 | Train Loss: 0.2892 | Val ROC-AUC: 0.8451 | Val Profit: -370
model_6_batchnorm_i_dropout | valid epoch 5
ROC-AUC: 0.9541
Precision: 0.2143
Recall: 1.0
F0.5-score: 0.2542
Profit: -1820

Эпоха 5 | Train Loss: 0.5101 | Val ROC-AUC: 0.9541 | Val Profit: -1820
model_6_batchnorm_i_dropout | valid epoch 6
ROC-AUC: 0.9671
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 6 | Train Loss: 0.4013 | Val ROC-AUC: 0.9671 | Val Profit: -1295
model_6_batchnorm_i_dropout | valid epoch 7
ROC-AUC: 0.9667
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 7 | Train Loss: 0.2584 | Val ROC-AUC: 0.9667 | Val Profit: -565
model_6_batchnorm_i_dropout | valid epoch 8
ROC-AUC: 0.9594
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 8 | Train Loss: 0.1666 | Val ROC-AUC: 0.9594 | Val Profit: -420
model_6_batchnorm_i_dropout | valid epoch 9
ROC-AUC: 0.9623
Precision: 0.4545
Recall: 0.7143
F0.5-score: 0.4902
Profit: -405

Эпоха 9 | Train Loss: 0.1174 | Val ROC-AUC: 0.9623 | Val Profit: -405
model_6_batchnorm_i_dropout | valid epoch 10
ROC-AUC: 0.9518
Precision: 0.4

In [94]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.005, 'dropout': 0.015, 'profit': np.int64(-30), 'roc_auc': 0.9830985915492958}

In [95]:
LR = best["lr"]
DROPOUT_COEF = best["dropout"]

In [96]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_6 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_6.parameters(), lr=LR)

config = {
    "model": "MLP_batchnorm_dropout",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "dropout_coef": DROPOUT_COEF,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_6)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_6_batchnorm_dropout", config=config)
log_file = new_log_file()

model_6 = train_model(
    model=model_6,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_6_batchnorm_i_dropout"
)


save_results(model_6, "model_6", log_file, run)

run.finish()

model_6_batchnorm_i_dropout | valid epoch 1
ROC-AUC: 0.9485
Precision: 0.1469
Recall: 1.0
F0.5-score: 0.1771
Profit: -2945

Эпоха 1 | Train Loss: 1.1451 | Val ROC-AUC: 0.9485 | Val Profit: -2945
model_6_batchnorm_i_dropout | valid epoch 2
ROC-AUC: 0.9693
Precision: 0.1927
Recall: 1.0
F0.5-score: 0.2298
Profit: -2095

Эпоха 2 | Train Loss: 0.7664 | Val ROC-AUC: 0.9693 | Val Profit: -2095
model_6_batchnorm_i_dropout | valid epoch 3
ROC-AUC: 0.9646
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 3 | Train Loss: 0.5423 | Val ROC-AUC: 0.9646 | Val Profit: -1095
model_6_batchnorm_i_dropout | valid epoch 4
ROC-AUC: 0.9732
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 4 | Train Loss: 0.3972 | Val ROC-AUC: 0.9732 | Val Profit: -655
model_6_batchnorm_i_dropout | valid epoch 5
ROC-AUC: 0.9626
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 5 | Train Loss: 0.2974 | Val ROC-AUC: 0.9626 | Val Profit: -555
model_6_batchnorm_i_dropout | valid epoch 6
ROC-AUC: 0.9718
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 6 | Train Loss: 0.3404 | Val ROC-AUC: 0.9718 | Val Profit: -1145
model_6_batchnorm_i_dropout | valid epoch 7
ROC-AUC: 0.9736
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 7 | Train Loss: 0.4079 | Val ROC-AUC: 0.9736 | Val Profit: -1620
model_6_batchnorm_i_dropout | valid epoch 8
ROC-AUC: 0.9722
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 8 | Train Loss: 0.3298 | Val ROC-AUC: 0.9722 | Val Profit: -720
model_6_batchnorm_i_dropout | valid epoch 9
ROC-AUC: 0.9677
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 9 | Train Loss: 0.2459 | Val ROC-AUC: 0.9677 | Val Profit: -255
model_6_batchnorm_i_dropout | valid epoch 10
ROC-AUC: 0.9716
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 10 | Train Loss: 0.2086 | Val ROC-AUC: 0.9716 | Val Profit: -205
model_6_batchnorm_i_dropout | valid epoch 11
ROC-AUC: 0.9763
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 11 | Train Loss: 0.1760 | Val ROC-AUC: 0.9763 | Val Profit: -135
model_6_batchnorm_i_dropout | valid epoch 12
ROC-AUC: 0.9696
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 12 | Train Loss: 0.2911 | Val ROC-AUC: 0.9696 | Val Profit: -945
model_6_batchnorm_i_dropout | valid epoch 13
ROC-AUC: 0.9709
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 13 | Train Loss: 0.3203 | Val ROC-AUC: 0.9709 | Val Profit: -820
model_6_batchnorm_i_dropout | valid epoch 14
ROC-AUC: 0.9738
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 14 | Train Loss: 0.2266 | Val ROC-AUC: 0.9738 | Val Profit: -340
model_6_batchnorm_i_dropout | valid epoch 15
ROC-AUC: 0.9781
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 15 | Train Loss: 0.1719 | Val ROC-AUC: 0.9781 | Val Profit: -180
model_6_batchnorm_i_dropout | valid epoch 16
ROC-AUC: 0.9612
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 16 | Train Loss: 0.1251 | Val ROC-AUC: 0.9612 | Val Profit: -100
model_6_batchnorm_i_dropout | valid epoch 17
ROC-AUC: 0.9657
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 17 | Train Loss: 0.1833 | Val ROC-AUC: 0.9657 | Val Profit: -615
model_6_batchnorm_i_dropout | valid epoch 18
ROC-AUC: 0.965
Precision: 0.3333
Recall: 0.9048
F0.5-score: 0.3815
Profit: -865

Эпоха 18 | Train Loss: 0.2917 | Val ROC-AUC: 0.9650 | Val Profit: -865
model_6_batchnorm_i_dropout | valid epoch 19
ROC-AUC: 0.9773
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 19 | Train Loss: 0.2318 | Val ROC-AUC: 0.9773 | Val Profit: -425
model_6_batchnorm_i_dropout | valid epoch 20
ROC-AUC: 0.9725
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 20 | Train Loss: 0.1851 | Val ROC-AUC: 0.9725 | Val Profit: -230
model_6_batchnorm_i_dropout | valid epoch 21
ROC-AUC: 0.9728
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 21 | Train Loss: 0.1525 | Val ROC-AUC: 0.9728 | Val Profit: -105
model_6_batchnorm_i_dropout | valid epoch 22
ROC-AUC: 0.9734
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 22 | Train Loss: 0.1264 | Val ROC-AUC: 0.9734 | Val Profit: -90
model_6_batchnorm_i_dropout | valid epoch 23
ROC-AUC: 0.9791
Precision: 0.8235
Recall: 0.6667
F0.5-score: 0.7865
Profit: -40

Эпоха 23 | Train Loss: 0.1028 | Val ROC-AUC: 0.9791 | Val Profit: -40
model_6_batchnorm_i_dropout | valid epoch 24
ROC-AUC: 0.9831
Precision: 0.8333
Recall: 0.7143
F0.5-score: 0.8065
Profit: -30

Эпоха 24 | Train Loss: 0.0892 | Val ROC-AUC: 0.9831 | Val Profit: -30
model_6_batchnorm_i_dropout | valid epoch 25
ROC-AUC: 0.9547
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 25 | Train Loss: 0.1564 | Val ROC-AUC: 0.9547 | Val Profit: -370
model_6_batchnorm_i_dropout | valid epoch 26
ROC-AUC: 0.9814
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 26 | Train Loss: 0.1326 | Val ROC-AUC: 0.9814 | Val Profit: -145
model_6_batchnorm_i_dropout | valid epoch 27
ROC-AUC: 0.9729
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 27 | Train Loss: 0.0863 | Val ROC-AUC: 0.9729 | Val Profit: -120
model_6_batchnorm_i_dropout | valid epoch 28
ROC-AUC: 0.9804
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 28 | Train Loss: 0.0675 | Val ROC-AUC: 0.9804 | Val Profit: -95
model_6_batchnorm_i_dropout | valid epoch 29
ROC-AUC: 0.9671
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 29 | Train Loss: 0.0621 | Val ROC-AUC: 0.9671 | Val Profit: -145
model_6_batchnorm_i_dropout | valid epoch 30
ROC-AUC: 0.8916
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 30 | Train Loss: 0.0554 | Val ROC-AUC: 0.8916 | Val Profit: -175

Лучшая эпоха для model_6_batchnorm_i_dropout: 24
Лучший ROC-AUC: 0.9830985915492958
Train
ROC-AUC: 0.9948
Precision: 0.8852
Recall: 0.6506
F0.5-score: 0.8257
Profit: -50

Test
ROC-AUC: 0.9803
Precision: 0.778
Recall: 0.5243
F0.5-score: 0.7094
Profit: -82975

In [97]:
train_metrics = evaluate_model(model_6, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_6, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9948
Precision: 0.8852
Recall: 0.6506
F0.5-score: 0.8257
Profit: -50

Test
ROC-AUC: 0.9803
Precision: 0.778
Recall: 0.5243
F0.5-score: 0.7094
Profit: -82975

Если соединить 2 и дропаут и батчнорм вместе, то качество получается хорошим. Но оно хуже, чем только при использовании batchnorm

## model_7_leaky_relu

In [104]:
EPOCHS = 30
SEED = 42

In [105]:
wandb.init(mode="disabled")
results = []
for LR in [0.01, 0.005, 0.001]:
    for DROPOUT_COEF in [0, 0.05, 0.01, 0.015, 0.2, 0.025, 0.3]:
        for NEG_SLOPE in [0.01, 0.03, 0.05, 0.1]:
            random.seed(SEED)
            np.random.seed(SEED)
            torch.manual_seed(SEED) 

            model_7 = nn.Sequential(
                nn.Linear(9, 128),
                nn.BatchNorm1d(128),
                nn.LeakyReLU(negative_slope=NEG_SLOPE),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(128, 64),
                nn.BatchNorm1d(64),
                nn.LeakyReLU(negative_slope=NEG_SLOPE),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(64, 32),
                nn.BatchNorm1d(32),
                nn.LeakyReLU(negative_slope=NEG_SLOPE),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(32, 16),
                nn.BatchNorm1d(16),
                nn.LeakyReLU(negative_slope=NEG_SLOPE),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(16, 8),
                nn.BatchNorm1d(8),
                nn.LeakyReLU(negative_slope=NEG_SLOPE),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(8, 1)
            )

            loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
            optimizer = torch.optim.Adam(model_7.parameters(), lr=LR)
            model_7 = train_model(
                model=model_7,
                train_loader=train_loader,
                X_valid=X_val,
                y_valid=y_val,
                loss_fn=loss_fn,
                optimizer=optimizer,
                epochs=EPOCHS,
                threshold=0.5,
                model_name="model_7_leaky_relu"
            )

            val = evaluate_model(model_7, X_val, y_val, threshold=0.5, name="val")
            results.append({"lr": LR, "dropout": DROPOUT_COEF, "neg_slope": NEG_SLOPE, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_7_leaky_relu | valid epoch 1
ROC-AUC: 0.9438
Precision: 0.1364
Recall: 1.0
F0.5-score: 0.1648
Profit: -3220

Эпоха 1 | Train Loss: 1.0457 | Val ROC-AUC: 0.9438 | Val Profit: -3220
model_7_leaky_relu | valid epoch 2
ROC-AUC: 0.9632
Precision: 0.2165
Recall: 1.0
F0.5-score: 0.2567
Profit: -1795

Эпоха 2 | Train Loss: 0.5750 | Val ROC-AUC: 0.9632 | Val Profit: -1795
model_7_leaky_relu | valid epoch 3
ROC-AUC: 0.9537
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 3 | Train Loss: 0.3804 | Val ROC-AUC: 0.9537 | Val Profit: -1145
model_7_leaky_relu | valid epoch 4
ROC-AUC: 0.9576
Precision: 0.241
Recall: 0.9524
F0.5-score: 0.2833
Profit: -1480

Эпоха 4 | Train Loss: 0.3889 | Val ROC-AUC: 0.9576 | Val Profit: -1480
model_7_leaky_relu | valid epoch 5
ROC-AUC: 0.9757
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 5 | Train Loss: 0.3124 | Val ROC-AUC: 0.9757 | Val Profit: -440
model_7_leaky_relu | valid epoch 6
ROC-AUC: 0.9733
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 6 | Train Loss: 0.3073 | Val ROC-AUC: 0.9733 | Val Profit: -955
model_7_leaky_relu | valid epoch 7
ROC-AUC: 0.9429
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 7 | Train Loss: 0.2510 | Val ROC-AUC: 0.9429 | Val Profit: -430
model_7_leaky_relu | valid epoch 8
ROC-AUC: 0.9704
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 8 | Train Loss: 0.2378 | Val ROC-AUC: 0.9704 | Val Profit: -325
model_7_leaky_relu | valid epoch 9
ROC-AUC: 0.9712
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 9 | Train Loss: 0.2623 | Val ROC-AUC: 0.9712 | Val Profit: -870
model_7_leaky_relu | valid epoch 10
ROC-AUC: 0.9808
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 10 | Train Loss: 0.2393 | Val ROC-AUC: 0.9808 | Val Profit: -415
model_7_leaky_relu | valid epoch 11
ROC-AUC: 0.9095
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 11 | Train Loss: 0.1650 | Val ROC-AUC: 0.9095 | Val Profit: -155
model_7_leaky_relu | valid epoch 12
ROC-AUC: 0.9572
Precision: 0.3016
Recall: 0.9048
F0.5-score: 0.348
Profit: -1015

Эпоха 12 | Train Loss: 0.2538 | Val ROC-AUC: 0.9572 | Val Profit: -1015
model_7_leaky_relu | valid epoch 13
ROC-AUC: 0.9787
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 13 | Train Loss: 0.3807 | Val ROC-AUC: 0.9787 | Val Profit: -670
model_7_leaky_relu | valid epoch 14
ROC-AUC: 0.9788
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 14 | Train Loss: 0.2300 | Val ROC-AUC: 0.9788 | Val Profit: -310
model_7_leaky_relu | valid epoch 15
ROC-AUC: 0.9775
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 15 | Train Loss: 0.1756 | Val ROC-AUC: 0.9775 | Val Profit: -155
model_7_leaky_relu | valid epoch 16
ROC-AUC: 0.9509
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 16 | Train Loss: 0.1566 | Val ROC-AUC: 0.9509 | Val Profit: -90
model_7_leaky_relu | valid epoch 17
ROC-AUC: 0.9233
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 17 | Train Loss: 0.1389 | Val ROC-AUC: 0.9233 | Val Profit: -45
model_7_leaky_relu | valid epoch 18
ROC-AUC: 0.9775
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 18 | Train Loss: 0.2423 | Val ROC-AUC: 0.9775 | Val Profit: -1055
model_7_leaky_relu | valid epoch 19
ROC-AUC: 0.9795
Precision: 0.339
Recall: 0.9524
F0.5-score: 0.3891
Profit: -880

Эпоха 19 | Train Loss: 0.2728 | Val ROC-AUC: 0.9795 | Val Profit: -880
model_7_leaky_relu | valid epoch 20
ROC-AUC: 0.9776
Precision: 0.5
Recall: 0.9524
F0.5-score: 0.5525
Profit: -405

Эпоха 20 | Train Loss: 0.2255 | Val ROC-AUC: 0.9776 | Val Profit: -405
model_7_leaky_relu | valid epoch 21
ROC-AUC: 0.9787
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 21 | Train Loss: 0.1868 | Val ROC-AUC: 0.9787 | Val Profit: -235
model_7_leaky_relu | valid epoch 22
ROC-AUC: 0.9795
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 22 | Train Loss: 0.1436 | Val ROC-AUC: 0.9795 | Val Profit: -90
model_7_leaky_relu | valid epoch 23
ROC-AUC: 0.9376
Precision: 0.8889
Recall: 0.381
F0.5-score: 0.7018
Profit: -50

Эпоха 23 | Train Loss: 0.1164 | Val ROC-AUC: 0.9376 | Val Profit: -50
model_7_leaky_relu | valid epoch 24
ROC-AUC: 0.9646
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 24 | Train Loss: 0.1080 | Val ROC-AUC: 0.9646 | Val Profit: -200
model_7_leaky_relu | valid epoch 25
ROC-AUC: 0.9667
Precision: 0.375
Recall: 0.8571
F0.5-score: 0.4225
Profit: -675

Эпоха 25 | Train Loss: 0.3615 | Val ROC-AUC: 0.9667 | Val Profit: -675
model_7_leaky_relu | valid epoch 26
ROC-AUC: 0.9808
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 26 | Train Loss: 0.2318 | Val ROC-AUC: 0.9808 | Val Profit: -275
model_7_leaky_relu | valid epoch 27
ROC-AUC: 0.9781
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 27 | Train Loss: 0.1780 | Val ROC-AUC: 0.9781 | Val Profit: -150
model_7_leaky_relu | valid epoch 28
ROC-AUC: 0.9874
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 28 | Train Loss: 0.1370 | Val ROC-AUC: 0.9874 | Val Profit: -65
model_7_leaky_relu | valid epoch 29
ROC-AUC: 0.9824
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 29 | Train Loss: 0.1024 | Val ROC-AUC: 0.9824 | Val Profit: -95
model_7_leaky_relu | valid epoch 30
ROC-AUC: 0.9804
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 30 | Train Loss: 0.0980 | Val ROC-AUC: 0.9804 | Val Profit: -85

Лучшая эпоха для model_7_leaky_relu: 28
Лучший ROC-AUC: 0.9873910127431254
val
ROC-AUC: 0.9874
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

model_7_leaky_relu | valid epoch 1
ROC-AUC: 0.9446
Precision: 0.1265
Recall: 1.0
F0.5-score: 0.1533
Profit: -3520

Эпоха 1 | Train Loss: 1.0538 | Val ROC-AUC: 0.9446 | Val Profit: -3520
model_7_leaky_relu | valid epoch 2
ROC-AUC: 0.9575
Precision: 0.2143
Recall: 1.0
F0.5-score: 0.2542
Profit: -1820

Эпоха 2 | Train Loss: 0.6059 | Val ROC-AUC: 0.9575 | Val Profit: -1820
model_7_leaky_relu | valid epoch 3
ROC-AUC: 0.9545
Precision: 0.2593
Recall: 1.0
F0.5-score: 0.3043
Profit: -1395

Эпоха 3 | Train Loss: 0.4251 | Val ROC-AUC: 0.9545 | Val Profit: -1395
model_7_leaky_relu | valid epoch 4
ROC-AUC: 0.9701
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 4 | Train Loss: 0.3319 | Val ROC-AUC: 0.9701 | Val Profit: -755
model_7_leaky_relu | valid epoch 5
ROC-AUC: 0.9736
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 5 | Train Loss: 0.3541 | Val ROC-AUC: 0.9736 | Val Profit: -1520
model_7_leaky_relu | valid epoch 6
ROC-AUC: 0.9751
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 6 | Train Loss: 0.3334 | Val ROC-AUC: 0.9751 | Val Profit: -770
model_7_leaky_relu | valid epoch 7
ROC-AUC: 0.9728
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 7 | Train Loss: 0.2437 | Val ROC-AUC: 0.9728 | Val Profit: -305
model_7_leaky_relu | valid epoch 8
ROC-AUC: 0.971
Precision: 0.2593
Recall: 1.0
F0.5-score: 0.3043
Profit: -1395

Эпоха 8 | Train Loss: 0.2835 | Val ROC-AUC: 0.9710 | Val Profit: -1395
model_7_leaky_relu | valid epoch 9
ROC-AUC: 0.9788
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 9 | Train Loss: 0.3155 | Val ROC-AUC: 0.9788 | Val Profit: -1045
model_7_leaky_relu | valid epoch 10
ROC-AUC: 0.9736
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 10 | Train Loss: 0.2393 | Val ROC-AUC: 0.9736 | Val Profit: -450
model_7_leaky_relu | valid epoch 11
ROC-AUC: 0.9792
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 11 | Train Loss: 0.1867 | Val ROC-AUC: 0.9792 | Val Profit: -105
model_7_leaky_relu | valid epoch 12
ROC-AUC: 0.9696
Precision: 0.4186
Recall: 0.8571
F0.5-score: 0.4663
Profit: -550

Эпоха 12 | Train Loss: 0.1922 | Val ROC-AUC: 0.9696 | Val Profit: -550
model_7_leaky_relu | valid epoch 13
ROC-AUC: 0.9823
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 13 | Train Loss: 0.2546 | Val ROC-AUC: 0.9823 | Val Profit: -580
model_7_leaky_relu | valid epoch 14
ROC-AUC: 0.974
Precision: 0.3387
Recall: 1.0
F0.5-score: 0.3903
Profit: -920

Эпоха 14 | Train Loss: 0.3246 | Val ROC-AUC: 0.9740 | Val Profit: -920
model_7_leaky_relu | valid epoch 15
ROC-AUC: 0.9808
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 15 | Train Loss: 0.2690 | Val ROC-AUC: 0.9808 | Val Profit: -430
model_7_leaky_relu | valid epoch 16
ROC-AUC: 0.98
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 16 | Train Loss: 0.1923 | Val ROC-AUC: 0.9800 | Val Profit: -190
model_7_leaky_relu | valid epoch 17
ROC-AUC: 0.9805
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 17 | Train Loss: 0.1524 | Val ROC-AUC: 0.9805 | Val Profit: -90
model_7_leaky_relu | valid epoch 18
ROC-AUC: 0.9721
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 18 | Train Loss: 0.1241 | Val ROC-AUC: 0.9721 | Val Profit: -55
model_7_leaky_relu | valid epoch 19
ROC-AUC: 0.9634
Precision: 0.2703
Recall: 0.9524
F0.5-score: 0.3155
Profit: -1255

Эпоха 19 | Train Loss: 0.3078 | Val ROC-AUC: 0.9634 | Val Profit: -1255
model_7_leaky_relu | valid epoch 20
ROC-AUC: 0.9732
Precision: 0.2703
Recall: 0.9524
F0.5-score: 0.3155
Profit: -1255

Эпоха 20 | Train Loss: 0.3403 | Val ROC-AUC: 0.9732 | Val Profit: -1255
model_7_leaky_relu | valid epoch 21
ROC-AUC: 0.9796
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 21 | Train Loss: 0.2812 | Val ROC-AUC: 0.9796 | Val Profit: -830
model_7_leaky_relu | valid epoch 22
ROC-AUC: 0.9788
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 22 | Train Loss: 0.2498 | Val ROC-AUC: 0.9788 | Val Profit: -410
model_7_leaky_relu | valid epoch 23
ROC-AUC: 0.9796
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 23 | Train Loss: 0.2463 | Val ROC-AUC: 0.9796 | Val Profit: -440
model_7_leaky_relu | valid epoch 24
ROC-AUC: 0.9784
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 24 | Train Loss: 0.2096 | Val ROC-AUC: 0.9784 | Val Profit: -310
model_7_leaky_relu | valid epoch 25
ROC-AUC: 0.978
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 25 | Train Loss: 0.1855 | Val ROC-AUC: 0.9780 | Val Profit: -170
model_7_leaky_relu | valid epoch 26
ROC-AUC: 0.9771
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 26 | Train Loss: 0.1618 | Val ROC-AUC: 0.9771 | Val Profit: -105
model_7_leaky_relu | valid epoch 27
ROC-AUC: 0.9763
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 27 | Train Loss: 0.1384 | Val ROC-AUC: 0.9763 | Val Profit: -70
model_7_leaky_relu | valid epoch 28
ROC-AUC: 0.9784
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 28 | Train Loss: 0.1196 | Val ROC-AUC: 0.9784 | Val Profit: -85
model_7_leaky_relu | valid epoch 29
ROC-AUC: 0.981
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 29 | Train Loss: 0.1280 | Val ROC-AUC: 0.9810 | Val Profit: -365
model_7_leaky_relu | valid epoch 30
ROC-AUC: 0.978
Precision: 0.2985
Recall: 0.9524
F0.5-score: 0.346
Profit: -1080

Эпоха 30 | Train Loss: 0.3055 | Val ROC-AUC: 0.9780 | Val Profit: -1080

Лучшая эпоха для model_7_leaky_relu: 13
Лучший ROC-AUC: 0.9822937625754526
val
ROC-AUC: 0.9823
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

model_7_leaky_relu | valid epoch 1
ROC-AUC: 0.9555
Precision: 0.1321
Recall: 1.0
F0.5-score: 0.1598
Profit: -3345

Эпоха 1 | Train Loss: 1.0574 | Val ROC-AUC: 0.9555 | Val Profit: -3345
model_7_leaky_relu | valid epoch 2
ROC-AUC: 0.9638
Precision: 0.21
Recall: 1.0
F0.5-score: 0.2494
Profit: -1870

Эпоха 2 | Train Loss: 0.5854 | Val ROC-AUC: 0.9638 | Val Profit: -1870
model_7_leaky_relu | valid epoch 3
ROC-AUC: 0.9533
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 3 | Train Loss: 0.4370 | Val ROC-AUC: 0.9533 | Val Profit: -1695
model_7_leaky_relu | valid epoch 4
ROC-AUC: 0.9518
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 4 | Train Loss: 0.3834 | Val ROC-AUC: 0.9518 | Val Profit: -1145
model_7_leaky_relu | valid epoch 5
ROC-AUC: 0.9606
Precision: 0.2985
Recall: 0.9524
F0.5-score: 0.346
Profit: -1080

Эпоха 5 | Train Loss: 0.3585 | Val ROC-AUC: 0.9606 | Val Profit: -1080
model_7_leaky_relu | valid epoch 6
ROC-AUC: 0.9673
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 6 | Train Loss: 0.2780 | Val ROC-AUC: 0.9673 | Val Profit: -485
model_7_leaky_relu | valid epoch 7
ROC-AUC: 0.9785
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 7 | Train Loss: 0.2673 | Val ROC-AUC: 0.9785 | Val Profit: -570
model_7_leaky_relu | valid epoch 8
ROC-AUC: 0.9718
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 8 | Train Loss: 0.3099 | Val ROC-AUC: 0.9718 | Val Profit: -930
model_7_leaky_relu | valid epoch 9
ROC-AUC: 0.9749
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 9 | Train Loss: 0.3070 | Val ROC-AUC: 0.9749 | Val Profit: -630
model_7_leaky_relu | valid epoch 10
ROC-AUC: 0.9785
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 10 | Train Loss: 0.2071 | Val ROC-AUC: 0.9785 | Val Profit: -230
model_7_leaky_relu | valid epoch 11
ROC-AUC: 0.978
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 11 | Train Loss: 0.1819 | Val ROC-AUC: 0.9780 | Val Profit: -230
model_7_leaky_relu | valid epoch 12
ROC-AUC: 0.9694
Precision: 0.4324
Recall: 0.7619
F0.5-score: 0.4734
Profit: -470

Эпоха 12 | Train Loss: 0.2323 | Val ROC-AUC: 0.9694 | Val Profit: -470
model_7_leaky_relu | valid epoch 13
ROC-AUC: 0.9791
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 13 | Train Loss: 0.1873 | Val ROC-AUC: 0.9791 | Val Profit: -175
model_7_leaky_relu | valid epoch 14
ROC-AUC: 0.9742
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 14 | Train Loss: 0.1343 | Val ROC-AUC: 0.9742 | Val Profit: -95
model_7_leaky_relu | valid epoch 15
ROC-AUC: 0.9673
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 15 | Train Loss: 0.1107 | Val ROC-AUC: 0.9673 | Val Profit: -110
model_7_leaky_relu | valid epoch 16
ROC-AUC: 0.9779
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 16 | Train Loss: 0.1168 | Val ROC-AUC: 0.9779 | Val Profit: -335
model_7_leaky_relu | valid epoch 17
ROC-AUC: 0.9494
Precision: 0.2857
Recall: 0.9524
F0.5-score: 0.3322
Profit: -1155

Эпоха 17 | Train Loss: 0.2966 | Val ROC-AUC: 0.9494 | Val Profit: -1155
model_7_leaky_relu | valid epoch 18
ROC-AUC: 0.9779
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 18 | Train Loss: 0.3236 | Val ROC-AUC: 0.9779 | Val Profit: -290
model_7_leaky_relu | valid epoch 19
ROC-AUC: 0.971
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 19 | Train Loss: 0.2743 | Val ROC-AUC: 0.9710 | Val Profit: -805
model_7_leaky_relu | valid epoch 20
ROC-AUC: 0.9742
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

Эпоха 20 | Train Loss: 0.2422 | Val ROC-AUC: 0.9742 | Val Profit: -315
model_7_leaky_relu | valid epoch 21
ROC-AUC: 0.9793
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 21 | Train Loss: 0.1994 | Val ROC-AUC: 0.9793 | Val Profit: -180
model_7_leaky_relu | valid epoch 22
ROC-AUC: 0.9608
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 22 | Train Loss: 0.1422 | Val ROC-AUC: 0.9608 | Val Profit: -95
model_7_leaky_relu | valid epoch 23
ROC-AUC: 0.9459
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 23 | Train Loss: 0.1224 | Val ROC-AUC: 0.9459 | Val Profit: -140
model_7_leaky_relu | valid epoch 24
ROC-AUC: 0.9548
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 24 | Train Loss: 0.1205 | Val ROC-AUC: 0.9548 | Val Profit: -50
model_7_leaky_relu | valid epoch 25
ROC-AUC: 0.9748
Precision: 0.21
Recall: 1.0
F0.5-score: 0.2494
Profit: -1870

Эпоха 25 | Train Loss: 0.4649 | Val ROC-AUC: 0.9748 | Val Profit: -1870
model_7_leaky_relu | valid epoch 26
ROC-AUC: 0.9686
Precision: 0.2703
Recall: 0.9524
F0.5-score: 0.3155
Profit: -1255

Эпоха 26 | Train Loss: 0.3295 | Val ROC-AUC: 0.9686 | Val Profit: -1255
model_7_leaky_relu | valid epoch 27
ROC-AUC: 0.9733
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 27 | Train Loss: 0.2774 | Val ROC-AUC: 0.9733 | Val Profit: -480
model_7_leaky_relu | valid epoch 28
ROC-AUC: 0.9748
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 28 | Train Loss: 0.2272 | Val ROC-AUC: 0.9748 | Val Profit: -275
model_7_leaky_relu | valid epoch 29
ROC-AUC: 0.9753
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 29 | Train Loss: 0.1962 | Val ROC-AUC: 0.9753 | Val Profit: -215
model_7_leaky_relu | valid epoch 30
ROC-AUC: 0.9765
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 30 | Train Loss: 0.1954 | Val ROC-AUC: 0.9765 | Val Profit: -270

Лучшая эпоха для model_7_leaky_relu: 21
Лучший ROC-AUC: 0.9793427230046948
val
ROC-AUC: 0.9793
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

model_7_leaky_relu | valid epoch 1
ROC-AUC: 0.9512
Precision: 0.1296
Recall: 1.0
F0.5-score: 0.157
Profit: -3420

Эпоха 1 | Train Loss: 1.0221 | Val ROC-AUC: 0.9512 | Val Profit: -3420
model_7_leaky_relu | valid epoch 2
ROC-AUC: 0.9504
Precision: 0.1765
Recall: 1.0
F0.5-score: 0.2113
Profit: -2345

Эпоха 2 | Train Loss: 0.5962 | Val ROC-AUC: 0.9504 | Val Profit: -2345
model_7_leaky_relu | valid epoch 3
ROC-AUC: 0.9564
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 3 | Train Loss: 0.4459 | Val ROC-AUC: 0.9564 | Val Profit: -1645
model_7_leaky_relu | valid epoch 4
ROC-AUC: 0.97
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 4 | Train Loss: 0.3797 | Val ROC-AUC: 0.9700 | Val Profit: -1420
model_7_leaky_relu | valid epoch 5
ROC-AUC: 0.9691
Precision: 0.3387
Recall: 1.0
F0.5-score: 0.3903
Profit: -920

Эпоха 5 | Train Loss: 0.3236 | Val ROC-AUC: 0.9691 | Val Profit: -920
model_7_leaky_relu | valid epoch 6
ROC-AUC: 0.9741
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 6 | Train Loss: 0.2619 | Val ROC-AUC: 0.9741 | Val Profit: -275
model_7_leaky_relu | valid epoch 7
ROC-AUC: 0.9779
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 7 | Train Loss: 0.2440 | Val ROC-AUC: 0.9779 | Val Profit: -475
model_7_leaky_relu | valid epoch 8
ROC-AUC: 0.9647
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 8 | Train Loss: 0.2066 | Val ROC-AUC: 0.9647 | Val Profit: -295
model_7_leaky_relu | valid epoch 9
ROC-AUC: 0.9661
Precision: 0.2234
Recall: 1.0
F0.5-score: 0.2645
Profit: -1720

Эпоха 9 | Train Loss: 0.4036 | Val ROC-AUC: 0.9661 | Val Profit: -1720
model_7_leaky_relu | valid epoch 10
ROC-AUC: 0.9671
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 10 | Train Loss: 0.3165 | Val ROC-AUC: 0.9671 | Val Profit: -1145
model_7_leaky_relu | valid epoch 11
ROC-AUC: 0.9781
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 11 | Train Loss: 0.2473 | Val ROC-AUC: 0.9781 | Val Profit: -440
model_7_leaky_relu | valid epoch 12
ROC-AUC: 0.9765
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 12 | Train Loss: 0.2018 | Val ROC-AUC: 0.9765 | Val Profit: -245
model_7_leaky_relu | valid epoch 13
ROC-AUC: 0.9787
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 13 | Train Loss: 0.1770 | Val ROC-AUC: 0.9787 | Val Profit: -100
model_7_leaky_relu | valid epoch 14
ROC-AUC: 0.9823
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 14 | Train Loss: 0.1498 | Val ROC-AUC: 0.9823 | Val Profit: -50
model_7_leaky_relu | valid epoch 15

In [106]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.01, 'dropout': 0.015, 'neg_slope': 0.1, 'profit': np.int64(-55), 'roc_auc': 0.9849765258215962}

In [107]:
LR = best["lr"]
DROPOUT_COEF = best["dropout"]
NEG_SLOPE = best["neg_slope"]

In [108]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_7 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.LeakyReLU(negative_slope=NEG_SLOPE),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_7.parameters(), lr=LR)

config = {
    "model": "MLP_leaky_relu",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "dropout_coef": DROPOUT_COEF,
    "negative_slope": NEG_SLOPE,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_7)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_7_leaky_relu", config=config)
log_file = new_log_file()

model_7 = train_model(
    model=model_7,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_7_leaky_relu"
)
save_results(model_7, "model_7", log_file, run)

run.finish()

model_7_leaky_relu | valid epoch 1
ROC-AUC: 0.9434
Precision: 0.1373
Recall: 1.0
F0.5-score: 0.1659
Profit: -3195

Эпоха 1 | Train Loss: 1.0064 | Val ROC-AUC: 0.9434 | Val Profit: -3195
model_7_leaky_relu | valid epoch 2
ROC-AUC: 0.9572
Precision: 0.1875
Recall: 1.0
F0.5-score: 0.2239
Profit: -2170

Эпоха 2 | Train Loss: 0.5595 | Val ROC-AUC: 0.9572 | Val Profit: -2170
model_7_leaky_relu | valid epoch 3
ROC-AUC: 0.9509
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 3 | Train Loss: 0.4192 | Val ROC-AUC: 0.9509 | Val Profit: -1345
model_7_leaky_relu | valid epoch 4
ROC-AUC: 0.965
Precision: 0.2121
Recall: 1.0
F0.5-score: 0.2518
Profit: -1845

Эпоха 4 | Train Loss: 0.4338 | Val ROC-AUC: 0.9650 | Val Profit: -1845
model_7_leaky_relu | valid epoch 5
ROC-AUC: 0.9734
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 5 | Train Loss: 0.3231 | Val ROC-AUC: 0.9734 | Val Profit: -755
model_7_leaky_relu | valid epoch 6
ROC-AUC: 0.9675
Precision: 0.4375
Recall: 0.6667
F0.5-score: 0.4698
Profit: -415

Эпоха 6 | Train Loss: 0.2518 | Val ROC-AUC: 0.9675 | Val Profit: -415
model_7_leaky_relu | valid epoch 7
ROC-AUC: 0.967
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 7 | Train Loss: 0.2869 | Val ROC-AUC: 0.9670 | Val Profit: -805
model_7_leaky_relu | valid epoch 8
ROC-AUC: 0.9744
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 8 | Train Loss: 0.2407 | Val ROC-AUC: 0.9744 | Val Profit: -430
model_7_leaky_relu | valid epoch 9
ROC-AUC: 0.9286
Precision: 0.274
Recall: 0.9524
F0.5-score: 0.3195
Profit: -1230

Эпоха 9 | Train Loss: 0.3077 | Val ROC-AUC: 0.9286 | Val Profit: -1230
model_7_leaky_relu | valid epoch 10
ROC-AUC: 0.9677
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 10 | Train Loss: 0.4135 | Val ROC-AUC: 0.9677 | Val Profit: -1295
model_7_leaky_relu | valid epoch 11
ROC-AUC: 0.9718
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 11 | Train Loss: 0.2735 | Val ROC-AUC: 0.9718 | Val Profit: -520
model_7_leaky_relu | valid epoch 12
ROC-AUC: 0.9705
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 12 | Train Loss: 0.2154 | Val ROC-AUC: 0.9705 | Val Profit: -305
model_7_leaky_relu | valid epoch 13
ROC-AUC: 0.9779
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 13 | Train Loss: 0.1781 | Val ROC-AUC: 0.9779 | Val Profit: -115
model_7_leaky_relu | valid epoch 14
ROC-AUC: 0.9772
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 14 | Train Loss: 0.1440 | Val ROC-AUC: 0.9772 | Val Profit: -95
model_7_leaky_relu | valid epoch 15
ROC-AUC: 0.985
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 15 | Train Loss: 0.1155 | Val ROC-AUC: 0.9850 | Val Profit: -55
model_7_leaky_relu | valid epoch 16
ROC-AUC: 0.9748
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 16 | Train Loss: 0.1095 | Val ROC-AUC: 0.9748 | Val Profit: -340
model_7_leaky_relu | valid epoch 17
ROC-AUC: 0.9838
Precision: 0.5
Recall: 1.0
F0.5-score: 0.5556
Profit: -420

Эпоха 17 | Train Loss: 0.2011 | Val ROC-AUC: 0.9838 | Val Profit: -420
model_7_leaky_relu | valid epoch 18
ROC-AUC: 0.9812
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 18 | Train Loss: 0.1528 | Val ROC-AUC: 0.9812 | Val Profit: -125
model_7_leaky_relu | valid epoch 19
ROC-AUC: 0.9827
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 19 | Train Loss: 0.1092 | Val ROC-AUC: 0.9827 | Val Profit: -115
model_7_leaky_relu | valid epoch 20
ROC-AUC: 0.9832
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 20 | Train Loss: 0.0820 | Val ROC-AUC: 0.9832 | Val Profit: -130
model_7_leaky_relu | valid epoch 21
ROC-AUC: 0.97
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 21 | Train Loss: 0.1499 | Val ROC-AUC: 0.9700 | Val Profit: -805
model_7_leaky_relu | valid epoch 22
ROC-AUC: 0.9607
Precision: 0.3077
Recall: 0.9524
F0.5-score: 0.3559
Profit: -1030

Эпоха 22 | Train Loss: 0.3504 | Val ROC-AUC: 0.9607 | Val Profit: -1030
model_7_leaky_relu | valid epoch 23
ROC-AUC: 0.9764
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 23 | Train Loss: 0.2449 | Val ROC-AUC: 0.9764 | Val Profit: -570
model_7_leaky_relu | valid epoch 24
ROC-AUC: 0.9745
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 24 | Train Loss: 0.2025 | Val ROC-AUC: 0.9745 | Val Profit: -190
model_7_leaky_relu | valid epoch 25
ROC-AUC: 0.9716
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 25 | Train Loss: 0.1623 | Val ROC-AUC: 0.9716 | Val Profit: -175
model_7_leaky_relu | valid epoch 26
ROC-AUC: 0.9717
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 26 | Train Loss: 0.1378 | Val ROC-AUC: 0.9717 | Val Profit: -145
model_7_leaky_relu | valid epoch 27
ROC-AUC: 0.9734
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 27 | Train Loss: 0.1125 | Val ROC-AUC: 0.9734 | Val Profit: -190
model_7_leaky_relu | valid epoch 28
ROC-AUC: 0.9745
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 28 | Train Loss: 0.0883 | Val ROC-AUC: 0.9745 | Val Profit: -175
model_7_leaky_relu | valid epoch 29
ROC-AUC: 0.9834
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 29 | Train Loss: 0.0737 | Val ROC-AUC: 0.9834 | Val Profit: -125
model_7_leaky_relu | valid epoch 30
ROC-AUC: 0.985
Precision: 0.6333
Recall: 0.9048
F0.5-score: 0.6738
Profit: -190

Эпоха 30 | Train Loss: 0.0818 | Val ROC-AUC: 0.9850 | Val Profit: -190

Лучшая эпоха для model_7_leaky_relu: 15
Лучший ROC-AUC: 0.9849765258215962
Train
ROC-AUC: 0.9943
Precision: 0.9
Recall: 0.4337
F0.5-score: 0.7407
Profit: -155

Test
ROC-AUC: 0.9785
Precision: 0.8168
Recall: 0.3803
F0.5-score: 0.6643
Profit: -79005

In [109]:
train_metrics = evaluate_model(model_7, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_7, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9943
Precision: 0.9
Recall: 0.4337
F0.5-score: 0.7407
Profit: -155

Test
ROC-AUC: 0.9785
Precision: 0.8168
Recall: 0.3803
F0.5-score: 0.6643
Profit: -79005

Поменяли функцию активации с ReLU на LeakyReLU и перебрали LR, DROPOUT_COEF и NEG_SLOPE. Получилось добиться лучшего качества по Profit в -79к

Да, это лучше бейзлайна, но качество ухудшилось. 

Вывод: особого эффекта LeakyRelu не дал

## model_8_weight_decay

In [137]:
EPOCHS = 40
SEED = 42

In [138]:
wandb.init(mode="disabled")
results = []
for LR in [0.01, 0.005, 0.001]:
    for DROPOUT_COEF in [0, 0.05, 0.01, 0.015, 0.2, 0.025, 0.3]:
        for WEIGHT_DECAY in [0.0001, 0.001, 0.01]:
            random.seed(SEED)
            np.random.seed(SEED)
            torch.manual_seed(SEED) 

            model_8 = nn.Sequential(
                nn.Linear(9, 128),
                nn.BatchNorm1d(128),
                nn.ReLU(),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(128, 64),
                nn.BatchNorm1d(64),
                nn.ReLU(),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(64, 32),
                nn.BatchNorm1d(32),
                nn.ReLU(),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(32, 16),
                nn.BatchNorm1d(16),
                nn.ReLU(),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(16, 8),
                nn.BatchNorm1d(8),
                nn.ReLU(),
                nn.Dropout(DROPOUT_COEF),

                nn.Linear(8, 1)
            )

            loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
            optimizer = torch.optim.Adam(model_8.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
            model_8 = train_model(
                model=model_8,
                train_loader=train_loader,
                X_valid=X_val,
                y_valid=y_val,
                loss_fn=loss_fn,
                optimizer=optimizer,
                epochs=EPOCHS,
                threshold=0.5,
                model_name="model_8_weight_decay"
            )

            val = evaluate_model(model_8, X_val, y_val, threshold=0.5, name="val")
            results.append({"lr": LR, "dropout": DROPOUT_COEF, "weight_decay": WEIGHT_DECAY, "profit": val["profit"], "roc_auc": val["roc_auc"]})

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9522
Precision: 0.1235
Recall: 1.0
F0.5-score: 0.1498
Profit: -3620

Эпоха 1 | Train Loss: 1.0011 | Val ROC-AUC: 0.9522 | Val Profit: -3620
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9606
Precision: 0.2165
Recall: 1.0
F0.5-score: 0.2567
Profit: -1795

Эпоха 2 | Train Loss: 0.5483 | Val ROC-AUC: 0.9606 | Val Profit: -1795
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9645
Precision: 0.2386
Recall: 1.0
F0.5-score: 0.2815
Profit: -1570

Эпоха 3 | Train Loss: 0.4441 | Val ROC-AUC: 0.9645 | Val Profit: -1570
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9634
Precision: 0.3585
Recall: 0.9048
F0.5-score: 0.4077
Profit: -765

Эпоха 4 | Train Loss: 0.3131 | Val ROC-AUC: 0.9634 | Val Profit: -765
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9638
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 5 | Train Loss: 0.3646 | Val ROC-AUC: 0.9638 | Val Profit: -820
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9718
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 6 | Train Loss: 0.3187 | Val ROC-AUC: 0.9718 | Val Profit: -1095
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9755
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 7 | Train Loss: 0.2580 | Val ROC-AUC: 0.9755 | Val Profit: -305
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9384
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 8 | Train Loss: 0.1968 | Val ROC-AUC: 0.9384 | Val Profit: -95
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9528
Precision: 0.2632
Recall: 0.9524
F0.5-score: 0.3077
Profit: -1305

Эпоха 9 | Train Loss: 0.2939 | Val ROC-AUC: 0.9528 | Val Profit: -1305
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9732
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 10 | Train Loss: 0.3572 | Val ROC-AUC: 0.9732 | Val Profit: -1270
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9772
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 11 | Train Loss: 0.2889 | Val ROC-AUC: 0.9772 | Val Profit: -845
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9784
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 12 | Train Loss: 0.2583 | Val ROC-AUC: 0.9784 | Val Profit: -390
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9785
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 13 | Train Loss: 0.2025 | Val ROC-AUC: 0.9785 | Val Profit: -280
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9362
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 14 | Train Loss: 0.1705 | Val ROC-AUC: 0.9362 | Val Profit: -145
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9054
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 15 | Train Loss: 0.1393 | Val ROC-AUC: 0.9054 | Val Profit: -155
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9643
Precision: 0.3279
Recall: 0.9524
F0.5-score: 0.3774
Profit: -930

Эпоха 16 | Train Loss: 0.2111 | Val ROC-AUC: 0.9643 | Val Profit: -930
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9805
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 17 | Train Loss: 0.4157 | Val ROC-AUC: 0.9805 | Val Profit: -945
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9792
Precision: 0.5588
Recall: 0.9048
F0.5-score: 0.6051
Profit: -290

Эпоха 18 | Train Loss: 0.2368 | Val ROC-AUC: 0.9792 | Val Profit: -290
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9796
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 19 | Train Loss: 0.1626 | Val ROC-AUC: 0.9796 | Val Profit: -105
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9792
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.1375 | Val ROC-AUC: 0.9792 | Val Profit: -125
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9764
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 21 | Train Loss: 0.1513 | Val ROC-AUC: 0.9764 | Val Profit: -170
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9784
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 22 | Train Loss: 0.1853 | Val ROC-AUC: 0.9784 | Val Profit: -310
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.98
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 23 | Train Loss: 0.1439 | Val ROC-AUC: 0.9800 | Val Profit: -75
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9702
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 24 | Train Loss: 0.1116 | Val ROC-AUC: 0.9702 | Val Profit: -130
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9634
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 25 | Train Loss: 0.1247 | Val ROC-AUC: 0.9634 | Val Profit: -220
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9635
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 26 | Train Loss: 0.1713 | Val ROC-AUC: 0.9635 | Val Profit: -225
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9738
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 27 | Train Loss: 0.2092 | Val ROC-AUC: 0.9738 | Val Profit: -430
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9736
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 28 | Train Loss: 0.1940 | Val ROC-AUC: 0.9736 | Val Profit: -325
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9686
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 29 | Train Loss: 0.2158 | Val ROC-AUC: 0.9686 | Val Profit: -355
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9751
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 30 | Train Loss: 0.1689 | Val ROC-AUC: 0.9751 | Val Profit: -160
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 31 | Train Loss: 0.1110 | Val ROC-AUC: 0.9670 | Val Profit: -130
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9748
Precision: 0.6296
Recall: 0.8095
F0.5-score: 0.6589
Profit: -185

Эпоха 32 | Train Loss: 0.1225 | Val ROC-AUC: 0.9748 | Val Profit: -185
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9755
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 33 | Train Loss: 0.1386 | Val ROC-AUC: 0.9755 | Val Profit: -140
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9763
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 34 | Train Loss: 0.1025 | Val ROC-AUC: 0.9763 | Val Profit: -125
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9874
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 35 | Train Loss: 0.0959 | Val ROC-AUC: 0.9874 | Val Profit: -85
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9881
Precision: 0.6667
Recall: 0.8571
F0.5-score: 0.6977
Profit: -150

Эпоха 36 | Train Loss: 0.1674 | Val ROC-AUC: 0.9881 | Val Profit: -150
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9713
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 37 | Train Loss: 0.3114 | Val ROC-AUC: 0.9713 | Val Profit: -705
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.985
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 38 | Train Loss: 0.2620 | Val ROC-AUC: 0.9850 | Val Profit: -415
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9865
Precision: 0.7273
Recall: 0.7619
F0.5-score: 0.7339
Profit: -95

Эпоха 39 | Train Loss: 0.1788 | Val ROC-AUC: 0.9865 | Val Profit: -95
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9865
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 40 | Train Loss: 0.1323 | Val ROC-AUC: 0.9865 | Val Profit: -45

Лучшая эпоха для model_8_weight_decay: 36
Лучший ROC-AUC: 0.9880617035546614
val
ROC-AUC: 0.9881
Precision: 0.6667
Recall: 0.8571
F0.5-score: 0.6977
Profit: -150

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9547
Precision: 0.1296
Recall: 1.0
F0.5-score: 0.157
Profit: -3420

Эпоха 1 | Train Loss: 0.9796 | Val ROC-AUC: 0.9547 | Val Profit: -3420
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9635
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 2 | Train Loss: 0.5444 | Val ROC-AUC: 0.9635 | Val Profit: -1645
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9528
Precision: 0.2019
Recall: 1.0
F0.5-score: 0.2403
Profit: -1970

Эпоха 3 | Train Loss: 0.4725 | Val ROC-AUC: 0.9528 | Val Profit: -1970
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9702
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 4 | Train Loss: 0.3871 | Val ROC-AUC: 0.9702 | Val Profit: -1270
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9712
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 5 | Train Loss: 0.2986 | Val ROC-AUC: 0.9712 | Val Profit: -440
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9732
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 6 | Train Loss: 0.3034 | Val ROC-AUC: 0.9732 | Val Profit: -1045
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9728
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 7 | Train Loss: 0.2781 | Val ROC-AUC: 0.9728 | Val Profit: -705
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9746
Precision: 0.2386
Recall: 1.0
F0.5-score: 0.2815
Profit: -1570

Эпоха 8 | Train Loss: 0.3819 | Val ROC-AUC: 0.9746 | Val Profit: -1570
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9756
Precision: 0.3387
Recall: 1.0
F0.5-score: 0.3903
Profit: -920

Эпоха 9 | Train Loss: 0.3265 | Val ROC-AUC: 0.9756 | Val Profit: -920
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9757
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 10 | Train Loss: 0.2465 | Val ROC-AUC: 0.9757 | Val Profit: -305
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9724
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 11 | Train Loss: 0.2158 | Val ROC-AUC: 0.9724 | Val Profit: -210
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9759
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 12 | Train Loss: 0.2098 | Val ROC-AUC: 0.9759 | Val Profit: -150
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9425
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 13 | Train Loss: 0.1679 | Val ROC-AUC: 0.9425 | Val Profit: -155
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.976
Precision: 0.1963
Recall: 1.0
F0.5-score: 0.2339
Profit: -2045

Эпоха 14 | Train Loss: 0.4054 | Val ROC-AUC: 0.9760 | Val Profit: -2045
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9753
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 15 | Train Loss: 0.3467 | Val ROC-AUC: 0.9753 | Val Profit: -1245
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9815
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 16 | Train Loss: 0.2749 | Val ROC-AUC: 0.9815 | Val Profit: -425
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9804
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 17 | Train Loss: 0.2282 | Val ROC-AUC: 0.9804 | Val Profit: -205
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9803
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 18 | Train Loss: 0.2021 | Val ROC-AUC: 0.9803 | Val Profit: -90
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9827
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 19 | Train Loss: 0.1767 | Val ROC-AUC: 0.9827 | Val Profit: -70
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9823
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 20 | Train Loss: 0.1566 | Val ROC-AUC: 0.9823 | Val Profit: -125
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9812
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 21 | Train Loss: 0.1534 | Val ROC-AUC: 0.9812 | Val Profit: -120
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9717
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 22 | Train Loss: 0.2574 | Val ROC-AUC: 0.9717 | Val Profit: -830
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9828
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 23 | Train Loss: 0.3256 | Val ROC-AUC: 0.9828 | Val Profit: -1320
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9791
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 24 | Train Loss: 0.2330 | Val ROC-AUC: 0.9791 | Val Profit: -365
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9799
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 25 | Train Loss: 0.1998 | Val ROC-AUC: 0.9799 | Val Profit: -100
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9733
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 26 | Train Loss: 0.1619 | Val ROC-AUC: 0.9733 | Val Profit: -110
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9311
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.1411 | Val ROC-AUC: 0.9311 | Val Profit: -120
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9804
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 28 | Train Loss: 0.1348 | Val ROC-AUC: 0.9804 | Val Profit: -120
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9843
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 29 | Train Loss: 0.1255 | Val ROC-AUC: 0.9843 | Val Profit: -110
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9669
Precision: 0.2234
Recall: 1.0
F0.5-score: 0.2645
Profit: -1720

Эпоха 30 | Train Loss: 0.6960 | Val ROC-AUC: 0.9669 | Val Profit: -1720
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9751
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 31 | Train Loss: 0.3937 | Val ROC-AUC: 0.9751 | Val Profit: -475
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9749
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 32 | Train Loss: 0.3043 | Val ROC-AUC: 0.9749 | Val Profit: -225
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9836
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 33 | Train Loss: 0.3400 | Val ROC-AUC: 0.9836 | Val Profit: -670
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9824
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 34 | Train Loss: 0.2403 | Val ROC-AUC: 0.9824 | Val Profit: -430
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9816
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 35 | Train Loss: 0.1971 | Val ROC-AUC: 0.9816 | Val Profit: -105
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9791
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 36 | Train Loss: 0.1750 | Val ROC-AUC: 0.9791 | Val Profit: -150
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9799
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 37 | Train Loss: 0.1535 | Val ROC-AUC: 0.9799 | Val Profit: -105
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9712
Precision: 0.3167
Recall: 0.9048
F0.5-score: 0.364
Profit: -940

Эпоха 38 | Train Loss: 0.2810 | Val ROC-AUC: 0.9712 | Val Profit: -940
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9797
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 39 | Train Loss: 0.2299 | Val ROC-AUC: 0.9797 | Val Profit: -505
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9805
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

Эпоха 40 | Train Loss: 0.1874 | Val ROC-AUC: 0.9805 | Val Profit: -80

Лучшая эпоха для model_8_weight_decay: 29
Лучший ROC-AUC: 0.9843058350100604
val
ROC-AUC: 0.9843
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9565
Precision: 0.1409
Recall: 1.0
F0.5-score: 0.1702
Profit: -3095

Эпоха 1 | Train Loss: 1.0012 | Val ROC-AUC: 0.9565 | Val Profit: -3095
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9649
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 2 | Train Loss: 0.5795 | Val ROC-AUC: 0.9649 | Val Profit: -1445
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9619
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 3 | Train Loss: 0.4459 | Val ROC-AUC: 0.9619 | Val Profit: -1295
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9567
Precision: 0.339
Recall: 0.9524
F0.5-score: 0.3891
Profit: -880

Эпоха 4 | Train Loss: 0.4118 | Val ROC-AUC: 0.9567 | Val Profit: -880
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9788
Precision: 0.5161
Recall: 0.7619
F0.5-score: 0.5517
Profit: -320

Эпоха 5 | Train Loss: 0.4575 | Val ROC-AUC: 0.9788 | Val Profit: -320
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9728
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 6 | Train Loss: 0.3329 | Val ROC-AUC: 0.9728 | Val Profit: -210
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.967
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 7 | Train Loss: 0.3354 | Val ROC-AUC: 0.9670 | Val Profit: -285
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9801
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 8 | Train Loss: 0.3747 | Val ROC-AUC: 0.9801 | Val Profit: -280

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.2918 | Val ROC-AUC: 0.9795 | Val Profit: -105
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9805
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 10 | Train Loss: 0.2954 | Val ROC-AUC: 0.9805 | Val Profit: -210
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9624
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 11 | Train Loss: 0.2974 | Val ROC-AUC: 0.9624 | Val Profit: -185
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9681
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 12 | Train Loss: 0.3128 | Val ROC-AUC: 0.9681 | Val Profit: -1020
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9791
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 13 | Train Loss: 0.3064 | Val ROC-AUC: 0.9791 | Val Profit: -140

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9764
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.2854 | Val ROC-AUC: 0.9764 | Val Profit: -105
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9855
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 15 | Train Loss: 0.2496 | Val ROC-AUC: 0.9855 | Val Profit: -95
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9708
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 16 | Train Loss: 0.3036 | Val ROC-AUC: 0.9708 | Val Profit: -1545
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9765
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 17 | Train Loss: 0.2606 | Val ROC-AUC: 0.9765 | Val Profit: -175
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9768
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 18 | Train Loss: 0.2449 | Val ROC-AUC: 0.9768 | Val Profit: -270
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9784
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 19 | Train Loss: 0.2331 | Val ROC-AUC: 0.9784 | Val Profit: -255
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9741
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 20 | Train Loss: 0.2914 | Val ROC-AUC: 0.9741 | Val Profit: -730
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9847
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 21 | Train Loss: 0.2614 | Val ROC-AUC: 0.9847 | Val Profit: -75
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9746
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 22 | Train Loss: 0.2715 | Val ROC-AUC: 0.9746 | Val Profit: -390
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9741
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 23 | Train Loss: 0.2378 | Val ROC-AUC: 0.9741 | Val Profit: -100
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9761
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 24 | Train Loss: 0.2436 | Val ROC-AUC: 0.9761 | Val Profit: -215
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.8826
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 25 | Train Loss: 0.2384 | Val ROC-AUC: 0.8826 | Val Profit: -140
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.976
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 26 | Train Loss: 0.2496 | Val ROC-AUC: 0.9760 | Val Profit: -215
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9781
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 27 | Train Loss: 0.2653 | Val ROC-AUC: 0.9781 | Val Profit: -355
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9772
Precision: 0.5758
Recall: 0.9048
F0.5-score: 0.6209
Profit: -265

Эпоха 28 | Train Loss: 0.2764 | Val ROC-AUC: 0.9772 | Val Profit: -265
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9383
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 29 | Train Loss: 0.2113 | Val ROC-AUC: 0.9383 | Val Profit: -85
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.981
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 30 | Train Loss: 0.2184 | Val ROC-AUC: 0.9810 | Val Profit: -260
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9689
Precision: 0.6
Recall: 0.8571
F0.5-score: 0.6383
Profit: -225

Эпоха 31 | Train Loss: 0.2401 | Val ROC-AUC: 0.9689 | Val Profit: -225
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9775
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 32 | Train Loss: 0.2533 | Val ROC-AUC: 0.9775 | Val Profit: -245
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9847
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 33 | Train Loss: 0.2309 | Val ROC-AUC: 0.9847 | Val Profit: -65
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.956
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 34 | Train Loss: 0.2148 | Val ROC-AUC: 0.9560 | Val Profit: -275
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9804
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 35 | Train Loss: 0.2614 | Val ROC-AUC: 0.9804 | Val Profit: -330
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9804
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 36 | Train Loss: 0.2398 | Val ROC-AUC: 0.9804 | Val Profit: -80
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9771
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 37 | Train Loss: 0.2133 | Val ROC-AUC: 0.9771 | Val Profit: -85
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9673
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 38 | Train Loss: 0.2386 | Val ROC-AUC: 0.9673 | Val Profit: -595
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9844
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 39 | Train Loss: 0.2898 | Val ROC-AUC: 0.9844 | Val Profit: -385
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9856
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 40 | Train Loss: 0.2238 | Val ROC-AUC: 0.9856 | Val Profit: -105

Лучшая эпоха для model_8_weight_decay: 40
Лучший ROC-AUC: 0.9856472166331322
val
ROC-AUC: 0.9856
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9536
Precision: 0.1257
Recall: 1.0
F0.5-score: 0.1524
Profit: -3545

Эпоха 1 | Train Loss: 1.0513 | Val ROC-AUC: 0.9536 | Val Profit: -3545
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9666
Precision: 0.2039
Recall: 1.0
F0.5-score: 0.2425
Profit: -1945

Эпоха 2 | Train Loss: 0.6071 | Val ROC-AUC: 0.9666 | Val Profit: -1945
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9552
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 3 | Train Loss: 0.4490 | Val ROC-AUC: 0.9552 | Val Profit: -1770

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9544
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 4 | Train Loss: 0.4185 | Val ROC-AUC: 0.9544 | Val Profit: -1495
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9746
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 5 | Train Loss: 0.3964 | Val ROC-AUC: 0.9746 | Val Profit: -1345
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9779
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 6 | Train Loss: 0.2742 | Val ROC-AUC: 0.9779 | Val Profit: -365
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9631
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 7 | Train Loss: 0.2025 | Val ROC-AUC: 0.9631 | Val Profit: -190
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9721
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 8 | Train Loss: 0.2415 | Val ROC-AUC: 0.9721 | Val Profit: -1420
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9492
Precision: 0.2597
Recall: 0.9524
F0.5-score: 0.304
Profit: -1330

Эпоха 9 | Train Loss: 0.3911 | Val ROC-AUC: 0.9492 | Val Profit: -1330
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9744
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 10 | Train Loss: 0.3050 | Val ROC-AUC: 0.9744 | Val Profit: -770
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9721
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 11 | Train Loss: 0.2283 | Val ROC-AUC: 0.9721 | Val Profit: -425
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9718
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 12 | Train Loss: 0.1791 | Val ROC-AUC: 0.9718 | Val Profit: -230
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9755
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 13 | Train Loss: 0.1310 | Val ROC-AUC: 0.9755 | Val Profit: -150
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9367
Precision: 0.4324
Recall: 0.7619
F0.5-score: 0.4734
Profit: -470

Эпоха 14 | Train Loss: 0.1316 | Val ROC-AUC: 0.9367 | Val Profit: -470
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9513
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 15 | Train Loss: 0.3014 | Val ROC-AUC: 0.9513 | Val Profit: -1445
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.973
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 16 | Train Loss: 0.3363 | Val ROC-AUC: 0.9730 | Val Profit: -1045
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9721
Precision: 0.5
Recall: 0.9524
F0.5-score: 0.5525
Profit: -405

Эпоха 17 | Train Loss: 0.2399 | Val ROC-AUC: 0.9721 | Val Profit: -405
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9771
Precision: 0.5
Recall: 0.9048
F0.5-score: 0.5491
Profit: -390

Эпоха 18 | Train Loss: 0.1998 | Val ROC-AUC: 0.9771 | Val Profit: -390
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9732
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 19 | Train Loss: 0.1689 | Val ROC-AUC: 0.9732 | Val Profit: -220
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9783
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 20 | Train Loss: 0.1237 | Val ROC-AUC: 0.9783 | Val Profit: -190
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9573
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 21 | Train Loss: 0.0932 | Val ROC-AUC: 0.9573 | Val Profit: -160
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9791
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 22 | Train Loss: 0.0705 | Val ROC-AUC: 0.9791 | Val Profit: -115
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9764
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 23 | Train Loss: 0.0641 | Val ROC-AUC: 0.9764 | Val Profit: -155
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9579
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 24 | Train Loss: 0.0888 | Val ROC-AUC: 0.9579 | Val Profit: -140
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9791
Precision: 0.4
Recall: 0.9524
F0.5-score: 0.4525
Profit: -655

Эпоха 25 | Train Loss: 0.1024 | Val ROC-AUC: 0.9791 | Val Profit: -655
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9795
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 26 | Train Loss: 0.4715 | Val ROC-AUC: 0.9795 | Val Profit: -1470
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9746
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 27 | Train Loss: 0.2330 | Val ROC-AUC: 0.9746 | Val Profit: -495
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9736
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 28 | Train Loss: 0.1658 | Val ROC-AUC: 0.9736 | Val Profit: -300
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9736
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 29 | Train Loss: 0.1280 | Val ROC-AUC: 0.9736 | Val Profit: -280
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9741
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 30 | Train Loss: 0.1068 | Val ROC-AUC: 0.9741 | Val Profit: -235
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9748
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 31 | Train Loss: 0.0800 | Val ROC-AUC: 0.9748 | Val Profit: -205
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9763
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 32 | Train Loss: 0.0613 | Val ROC-AUC: 0.9763 | Val Profit: -185
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9751
Precision: 0.6364
Recall: 0.6667
F0.5-score: 0.6422
Profit: -165

Эпоха 33 | Train Loss: 0.0500 | Val ROC-AUC: 0.9751 | Val Profit: -165
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9771
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 34 | Train Loss: 0.0434 | Val ROC-AUC: 0.9771 | Val Profit: -225
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9767
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 35 | Train Loss: 0.0423 | Val ROC-AUC: 0.9767 | Val Profit: -155
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9771
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 36 | Train Loss: 0.0326 | Val ROC-AUC: 0.9771 | Val Profit: -195
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9791
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 37 | Train Loss: 0.0272 | Val ROC-AUC: 0.9791 | Val Profit: -155
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9777
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 38 | Train Loss: 0.0280 | Val ROC-AUC: 0.9777 | Val Profit: -135
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9427
Precision: 0.3333
Recall: 0.8095
F0.5-score: 0.3778
Profit: -785

Эпоха 39 | Train Loss: 0.0362 | Val ROC-AUC: 0.9427 | Val Profit: -785
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.97
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 40 | Train Loss: 0.4237 | Val ROC-AUC: 0.9700 | Val Profit: -1420

Лучшая эпоха для model_8_weight_decay: 26
Лучший ROC-AUC: 0.9794768611670019
val
ROC-AUC: 0.9795
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9622
Precision: 0.1273
Recall: 1.0
F0.5-score: 0.1542
Profit: -3495

Эпоха 1 | Train Loss: 1.0058 | Val ROC-AUC: 0.9622 | Val Profit: -3495
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9657
Precision: 0.2258
Recall: 1.0
F0.5-score: 0.2672
Profit: -1695

Эпоха 2 | Train Loss: 0.5798 | Val ROC-AUC: 0.9657 | Val Profit: -1695
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9686
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 3 | Train Loss: 0.4038 | Val ROC-AUC: 0.9686 | Val Profit: -1445
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9561
Precision: 0.3051
Recall: 0.8571
F0.5-score: 0.3502
Profit: -950

Эпоха 4 | Train Loss: 0.3253 | Val ROC-AUC: 0.9561 | Val Profit: -950
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9682
Precision: 0.2165
Recall: 1.0
F0.5-score: 0.2567
Profit: -1795

Эпоха 5 | Train Loss: 0.4456 | Val ROC-AUC: 0.9682 | Val Profit: -1795
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9752
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 6 | Train Loss: 0.3011 | Val ROC-AUC: 0.9752 | Val Profit: -795
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9788
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 7 | Train Loss: 0.2445 | Val ROC-AUC: 0.9788 | Val Profit: -440
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.895
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 8 | Train Loss: 0.1815 | Val ROC-AUC: 0.8950 | Val Profit: -120
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9634
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 9 | Train Loss: 0.3750 | Val ROC-AUC: 0.9634 | Val Profit: -1320
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.978
Precision: 0.4651
Recall: 0.9524
F0.5-score: 0.5181
Profit: -480

Эпоха 10 | Train Loss: 0.2532 | Val ROC-AUC: 0.9780 | Val Profit: -480
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9804
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 11 | Train Loss: 0.1850 | Val ROC-AUC: 0.9804 | Val Profit: -230
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9783
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 12 | Train Loss: 0.1691 | Val ROC-AUC: 0.9783 | Val Profit: -350
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9588
Precision: 0.4333
Recall: 0.619
F0.5-score: 0.461
Profit: -400

Эпоха 13 | Train Loss: 0.1384 | Val ROC-AUC: 0.9588 | Val Profit: -400
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9846
Precision: 0.6129
Recall: 0.9048
F0.5-score: 0.6552
Profit: -215

Эпоха 14 | Train Loss: 0.1549 | Val ROC-AUC: 0.9846 | Val Profit: -215
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9751
Precision: 0.2763
Recall: 1.0
F0.5-score: 0.3231
Profit: -1270

Эпоха 15 | Train Loss: 0.3515 | Val ROC-AUC: 0.9751 | Val Profit: -1270
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9797
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 16 | Train Loss: 0.2515 | Val ROC-AUC: 0.9797 | Val Profit: -545
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9827
Precision: 0.5938
Recall: 0.9048
F0.5-score: 0.6376
Profit: -240

Эпоха 17 | Train Loss: 0.1802 | Val ROC-AUC: 0.9827 | Val Profit: -240
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9799
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 18 | Train Loss: 0.1376 | Val ROC-AUC: 0.9799 | Val Profit: -125
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.983
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 19 | Train Loss: 0.0965 | Val ROC-AUC: 0.9830 | Val Profit: -100
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9792
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 20 | Train Loss: 0.0758 | Val ROC-AUC: 0.9792 | Val Profit: -140
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9619
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 21 | Train Loss: 0.1869 | Val ROC-AUC: 0.9619 | Val Profit: -815
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9775
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 22 | Train Loss: 0.3043 | Val ROC-AUC: 0.9775 | Val Profit: -1055
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.981
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 23 | Train Loss: 0.2513 | Val ROC-AUC: 0.9810 | Val Profit: -355
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9759
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 24 | Train Loss: 0.1704 | Val ROC-AUC: 0.9759 | Val Profit: -180
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9744
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 25 | Train Loss: 0.1316 | Val ROC-AUC: 0.9744 | Val Profit: -185
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9826
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 26 | Train Loss: 0.0985 | Val ROC-AUC: 0.9826 | Val Profit: -50
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9783
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 27 | Train Loss: 0.0956 | Val ROC-AUC: 0.9783 | Val Profit: -125
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9755
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 28 | Train Loss: 0.0815 | Val ROC-AUC: 0.9755 | Val Profit: -185
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9535
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 29 | Train Loss: 0.0626 | Val ROC-AUC: 0.9535 | Val Profit: -155
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9818
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 30 | Train Loss: 0.0895 | Val ROC-AUC: 0.9818 | Val Profit: -455
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9764
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 31 | Train Loss: 0.1720 | Val ROC-AUC: 0.9764 | Val Profit: -730
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9781
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 32 | Train Loss: 0.2186 | Val ROC-AUC: 0.9781 | Val Profit: -340
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9733
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 33 | Train Loss: 0.1505 | Val ROC-AUC: 0.9733 | Val Profit: -245
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9797
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 34 | Train Loss: 0.1259 | Val ROC-AUC: 0.9797 | Val Profit: -110
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9785
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

Эпоха 35 | Train Loss: 0.0940 | Val ROC-AUC: 0.9785 | Val Profit: -130
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9439
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 36 | Train Loss: 0.1116 | Val ROC-AUC: 0.9439 | Val Profit: -350
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9801
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 37 | Train Loss: 0.1487 | Val ROC-AUC: 0.9801 | Val Profit: -260
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9759
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 38 | Train Loss: 0.1207 | Val ROC-AUC: 0.9759 | Val Profit: -200
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9484
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 39 | Train Loss: 0.0736 | Val ROC-AUC: 0.9484 | Val Profit: -175
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.8649
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 40 | Train Loss: 0.0498 | Val ROC-AUC: 0.8649 | Val Profit: -170

Лучшая эпоха для model_8_weight_decay: 14
Лучший ROC-AUC: 0.9845741113346748
val
ROC-AUC: 0.9846
Precision: 0.6129
Recall: 0.9048
F0.5-score: 0.6552
Profit: -215

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.96
Precision: 0.1329
Recall: 1.0
F0.5-score: 0.1608
Profit: -3320

Эпоха 1 | Train Loss: 1.0365 | Val ROC-AUC: 0.9600 | Val Profit: -3320
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9521
Precision: 0.236
Recall: 1.0
F0.5-score: 0.2785
Profit: -1595

Эпоха 2 | Train Loss: 0.6346 | Val ROC-AUC: 0.9521 | Val Profit: -1595
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9636
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 3 | Train Loss: 0.4421 | Val ROC-AUC: 0.9636 | Val Profit: -945
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9702
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 4 | Train Loss: 0.3854 | Val ROC-AUC: 0.9702 | Val Profit: -1045
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9541
Precision: 0.3725
Recall: 0.9048
F0.5-score: 0.4222
Profit: -715

Эпоха 5 | Train Loss: 0.3260 | Val ROC-AUC: 0.9541 | Val Profit: -715
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9616
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 6 | Train Loss: 0.3977 | Val ROC-AUC: 0.9616 | Val Profit: -1105
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9773
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 7 | Train Loss: 0.3170 | Val ROC-AUC: 0.9773 | Val Profit: -365
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9599
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 8 | Train Loss: 0.3227 | Val ROC-AUC: 0.9599 | Val Profit: -680
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9801
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 9 | Train Loss: 0.2858 | Val ROC-AUC: 0.9801 | Val Profit: -355
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.98
Precision: 0.6154
Recall: 0.7619
F0.5-score: 0.64
Profit: -195

Эпоха 10 | Train Loss: 0.2614 | Val ROC-AUC: 0.9800 | Val Profit: -195
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9763
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 11 | Train Loss: 0.2118 | Val ROC-AUC: 0.9763 | Val Profit: -110
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9732
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 12 | Train Loss: 0.2193 | Val ROC-AUC: 0.9732 | Val Profit: -705
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9709
Precision: 0.2079
Recall: 1.0
F0.5-score: 0.2471
Profit: -1895

Эпоха 13 | Train Loss: 0.3840 | Val ROC-AUC: 0.9709 | Val Profit: -1895
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9764
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 14 | Train Loss: 0.3076 | Val ROC-AUC: 0.9764 | Val Profit: -620
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9761
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 15 | Train Loss: 0.2408 | Val ROC-AUC: 0.9761 | Val Profit: -145
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9746
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 16 | Train Loss: 0.2095 | Val ROC-AUC: 0.9746 | Val Profit: -125
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9655
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 17 | Train Loss: 0.2066 | Val ROC-AUC: 0.9655 | Val Profit: -280
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9755
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 18 | Train Loss: 0.2956 | Val ROC-AUC: 0.9755 | Val Profit: -780
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9805
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 19 | Train Loss: 0.2577 | Val ROC-AUC: 0.9805 | Val Profit: -190
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9799
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 20 | Train Loss: 0.1739 | Val ROC-AUC: 0.9799 | Val Profit: -155
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.918
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 21 | Train Loss: 0.1244 | Val ROC-AUC: 0.9180 | Val Profit: -145
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.984
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 22 | Train Loss: 0.2259 | Val ROC-AUC: 0.9840 | Val Profit: -670
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9757
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 23 | Train Loss: 0.2396 | Val ROC-AUC: 0.9757 | Val Profit: -425
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9362
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 24 | Train Loss: 0.1931 | Val ROC-AUC: 0.9362 | Val Profit: -140
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9363
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 25 | Train Loss: 0.1567 | Val ROC-AUC: 0.9363 | Val Profit: -135
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9669
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 26 | Train Loss: 0.2059 | Val ROC-AUC: 0.9669 | Val Profit: -450
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9789
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470


/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 29
ROC-AUC: 0.8853
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 29 | Train Loss: 0.1852 | Val ROC-AUC: 0.8853 | Val Profit: -160
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9773
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 30 | Train Loss: 0.2133 | Val ROC-AUC: 0.9773 | Val Profit: -520
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9793
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 31 | Train Loss: 0.2327 | Val ROC-AUC: 0.9793 | Val Profit: -310
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9783
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 32 | Train Loss: 0.2378 | Val ROC-AUC: 0.9783 | Val Profit: -440
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9808
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 33 | Train Loss: 0.2862 | Val ROC-AUC: 0.9808 | Val Profit: -630

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9395
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 34 | Train Loss: 0.2086 | Val ROC-AUC: 0.9395 | Val Profit: -105
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9757
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 35 | Train Loss: 0.1631 | Val ROC-AUC: 0.9757 | Val Profit: -230
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9733
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 36 | Train Loss: 0.1946 | Val ROC-AUC: 0.9733 | Val Profit: -95
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9763
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 37 | Train Loss: 0.2325 | Val ROC-AUC: 0.9763 | Val Profit: -705
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9847
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 38 | Train Loss: 0.2212 | Val ROC-AUC: 0.9847 | Val Profit: -225
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9812
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 39 | Train Loss: 0.1902 | Val ROC-AUC: 0.9812 | Val Profit: -115
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.937
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 40 | Train Loss: 0.1923 | Val ROC-AUC: 0.9370 | Val Profit: -180

Лучшая эпоха для model_8_weight_decay: 23
Лучший ROC-AUC: 0.987122736418511
val
ROC-AUC: 0.9871
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9592
Precision: 0.1329
Recall: 1.0
F0.5-score: 0.1608
Profit: -3320

Эпоха 1 | Train Loss: 1.0617 | Val ROC-AUC: 0.9592 | Val Profit: -3320
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9653
Precision: 0.2019
Recall: 1.0
F0.5-score: 0.2403
Profit: -1970

Эпоха 2 | Train Loss: 0.5881 | Val ROC-AUC: 0.9653 | Val Profit: -1970
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9694
Precision: 0.2386
Recall: 1.0
F0.5-score: 0.2815
Profit: -1570

Эпоха 3 | Train Loss: 0.3971 | Val ROC-AUC: 0.9694 | Val Profit: -1570
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9653
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 4 | Train Loss: 0.3613 | Val ROC-AUC: 0.9653 | Val Profit: -970
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9713
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 5 | Train Loss: 0.3069 | Val ROC-AUC: 0.9713 | Val Profit: -605
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9683
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 6 | Train Loss: 0.2606 | Val ROC-AUC: 0.9683 | Val Profit: -420
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9641
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 7 | Train Loss: 0.2579 | Val ROC-AUC: 0.9641 | Val Profit: -705
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.969
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 8 | Train Loss: 0.2826 | Val ROC-AUC: 0.9690 | Val Profit: -770
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.886
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 9 | Train Loss: 0.2007 | Val ROC-AUC: 0.8860 | Val Profit: -180
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9657
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 10 | Train Loss: 0.2491 | Val ROC-AUC: 0.9657 | Val Profit: -1145
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9714
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 11 | Train Loss: 0.3132 | Val ROC-AUC: 0.9714 | Val Profit: -1020
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9793
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 12 | Train Loss: 0.2258 | Val ROC-AUC: 0.9793 | Val Profit: -380
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9506
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 13 | Train Loss: 0.1746 | Val ROC-AUC: 0.9506 | Val Profit: -335
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9812
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 14 | Train Loss: 0.2100 | Val ROC-AUC: 0.9812 | Val Profit: -280
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9812
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 15 | Train Loss: 0.1674 | Val ROC-AUC: 0.9812 | Val Profit: -105
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.969
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 16 | Train Loss: 0.1353 | Val ROC-AUC: 0.9690 | Val Profit: -70
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9789
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 17 | Train Loss: 0.1765 | Val ROC-AUC: 0.9789 | Val Profit: -670
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9771
Precision: 0.2625
Recall: 1.0
F0.5-score: 0.3079
Profit: -1370

Эпоха 18 | Train Loss: 0.3286 | Val ROC-AUC: 0.9771 | Val Profit: -1370
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9763
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 19 | Train Loss: 0.2781 | Val ROC-AUC: 0.9763 | Val Profit: -680
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9784
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 20 | Train Loss: 0.2247 | Val ROC-AUC: 0.9784 | Val Profit: -455
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9771
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 21 | Train Loss: 0.1805 | Val ROC-AUC: 0.9771 | Val Profit: -280
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9433
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 22 | Train Loss: 0.1624 | Val ROC-AUC: 0.9433 | Val Profit: -230
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9388
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 23 | Train Loss: 0.1335 | Val ROC-AUC: 0.9388 | Val Profit: -70
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.978
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 24 | Train Loss: 0.1073 | Val ROC-AUC: 0.9780 | Val Profit: -180
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9839
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 25 | Train Loss: 0.4255 | Val ROC-AUC: 0.9839 | Val Profit: -870
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.982
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 26 | Train Loss: 0.2969 | Val ROC-AUC: 0.9820 | Val Profit: -770
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9847
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 27 | Train Loss: 0.2370 | Val ROC-AUC: 0.9847 | Val Profit: -280
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9835
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

Эпоха 28 | Train Loss: 0.1875 | Val ROC-AUC: 0.9835 | Val Profit: -130
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.8876
Precision: 0.9091
Recall: 0.4762
F0.5-score: 0.7692
Profit: -30

Эпоха 29 | Train Loss: 0.1501 | Val ROC-AUC: 0.8876 | Val Profit: -30
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.906
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 30 | Train Loss: 0.1495 | Val ROC-AUC: 0.9060 | Val Profit: -190
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9195
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 31 | Train Loss: 0.1224 | Val ROC-AUC: 0.9195 | Val Profit: -90
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.7353
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 32 | Train Loss: 0.1004 | Val ROC-AUC: 0.7353 | Val Profit: -85
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.8742
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 33 | Train Loss: 0.0952 | Val ROC-AUC: 0.8742 | Val Profit: -245
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.8685
Precision: 0.8571
Recall: 0.5714
F0.5-score: 0.7792
Profit: -35

Эпоха 34 | Train Loss: 0.1073 | Val ROC-AUC: 0.8685 | Val Profit: -35
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9666
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 35 | Train Loss: 0.1756 | Val ROC-AUC: 0.9666 | Val Profit: -1045
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9801
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 36 | Train Loss: 0.2371 | Val ROC-AUC: 0.9801 | Val Profit: -995
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9823
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 37 | Train Loss: 0.2154 | Val ROC-AUC: 0.9823 | Val Profit: -430
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9808
Precision: 0.6
Recall: 0.8571
F0.5-score: 0.6383
Profit: -225

Эпоха 38 | Train Loss: 0.1712 | Val ROC-AUC: 0.9808 | Val Profit: -225
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.98
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 39 | Train Loss: 0.1461 | Val ROC-AUC: 0.9800 | Val Profit: -170
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9795
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 40 | Train Loss: 0.1263 | Val ROC-AUC: 0.9795 | Val Profit: -115

Лучшая эпоха для model_8_weight_decay: 27
Лучший ROC-AUC: 0.9847082494969819
val
ROC-AUC: 0.9847
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9529
Precision: 0.1193
Recall: 1.0
F0.5-score: 0.1448
Profit: -3770

Эпоха 1 | Train Loss: 1.0941 | Val ROC-AUC: 0.9529 | Val Profit: -3770
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9646
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 2 | Train Loss: 0.6075 | Val ROC-AUC: 0.9646 | Val Profit: -1620
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9665
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 3 | Train Loss: 0.3864 | Val ROC-AUC: 0.9665 | Val Profit: -1470
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9624
Precision: 0.2381
Recall: 0.9524
F0.5-score: 0.2801
Profit: -1505

Эпоха 4 | Train Loss: 0.4117 | Val ROC-AUC: 0.9624 | Val Profit: -1505
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9459
Precision: 0.2985
Recall: 0.9524
F0.5-score: 0.346
Profit: -1080

Эпоха 5 | Train Loss: 0.3266 | Val ROC-AUC: 0.9459 | Val Profit: -1080
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9755
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 6 | Train Loss: 0.3962 | Val ROC-AUC: 0.9755 | Val Profit: -1120
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.967
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 7 | Train Loss: 0.3012 | Val ROC-AUC: 0.9670 | Val Profit: -425
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.974
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 8 | Train Loss: 0.2344 | Val ROC-AUC: 0.9740 | Val Profit: -110
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.974
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 9 | Train Loss: 0.1951 | Val ROC-AUC: 0.9740 | Val Profit: -260
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9469
Precision: 0.2639
Recall: 0.9048
F0.5-score: 0.3074
Profit: -1240

Эпоха 10 | Train Loss: 0.3780 | Val ROC-AUC: 0.9469 | Val Profit: -1240
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9772
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 11 | Train Loss: 0.3356 | Val ROC-AUC: 0.9772 | Val Profit: -1145
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9779
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 12 | Train Loss: 0.2836 | Val ROC-AUC: 0.9779 | Val Profit: -330
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9765
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 13 | Train Loss: 0.2342 | Val ROC-AUC: 0.9765 | Val Profit: -240
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9725
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 14 | Train Loss: 0.2060 | Val ROC-AUC: 0.9725 | Val Profit: -255
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9761
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 15 | Train Loss: 0.2148 | Val ROC-AUC: 0.9761 | Val Profit: -140
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9834
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 16 | Train Loss: 0.1532 | Val ROC-AUC: 0.9834 | Val Profit: -95
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9737
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 17 | Train Loss: 0.1787 | Val ROC-AUC: 0.9737 | Val Profit: -555
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9412
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 18 | Train Loss: 0.1762 | Val ROC-AUC: 0.9412 | Val Profit: -85
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9651
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 19 | Train Loss: 0.3070 | Val ROC-AUC: 0.9651 | Val Profit: -1055
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.981
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 20 | Train Loss: 0.2387 | Val ROC-AUC: 0.9810 | Val Profit: -455
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9769
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 21 | Train Loss: 0.1920 | Val ROC-AUC: 0.9769 | Val Profit: -125
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9769
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 22 | Train Loss: 0.1558 | Val ROC-AUC: 0.9769 | Val Profit: -110
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9415
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 23 | Train Loss: 0.1311 | Val ROC-AUC: 0.9415 | Val Profit: -85
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9446
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.1014 | Val ROC-AUC: 0.9446 | Val Profit: -130
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9736
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 25 | Train Loss: 0.1137 | Val ROC-AUC: 0.9736 | Val Profit: -180
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9812
Precision: 0.2386
Recall: 1.0
F0.5-score: 0.2815
Profit: -1570

Эпоха 26 | Train Loss: 0.4239 | Val ROC-AUC: 0.9812 | Val Profit: -1570
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9822
Precision: 0.4762
Recall: 0.9524
F0.5-score: 0.5291
Profit: -455

Эпоха 27 | Train Loss: 0.2664 | Val ROC-AUC: 0.9822 | Val Profit: -455
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9779
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 28 | Train Loss: 0.1962 | Val ROC-AUC: 0.9779 | Val Profit: -95
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9761
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 29 | Train Loss: 0.1833 | Val ROC-AUC: 0.9761 | Val Profit: -100
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9819
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.1448 | Val ROC-AUC: 0.9819 | Val Profit: -130
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9493
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 31 | Train Loss: 0.1244 | Val ROC-AUC: 0.9493 | Val Profit: -135
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9852
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 32 | Train Loss: 0.1249 | Val ROC-AUC: 0.9852 | Val Profit: -280
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9679
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 33 | Train Loss: 0.2205 | Val ROC-AUC: 0.9679 | Val Profit: -420
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9839
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

Эпоха 34 | Train Loss: 0.1940 | Val ROC-AUC: 0.9839 | Val Profit: -130
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9384
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 35 | Train Loss: 0.1533 | Val ROC-AUC: 0.9384 | Val Profit: -155
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9781
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 36 | Train Loss: 0.1103 | Val ROC-AUC: 0.9781 | Val Profit: -125
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9364
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 37 | Train Loss: 0.0910 | Val ROC-AUC: 0.9364 | Val Profit: -135
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.8236
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 38 | Train Loss: 0.0917 | Val ROC-AUC: 0.8236 | Val Profit: -155
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9653
Precision: 0.178
Recall: 1.0
F0.5-score: 0.213
Profit: -2320

Эпоха 39 | Train Loss: 0.3587 | Val ROC-AUC: 0.9653 | Val Profit: -2320
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9733
Precision: 0.2658
Recall: 1.0
F0.5-score: 0.3116
Profit: -1345

Эпоха 40 | Train Loss: 0.3798 | Val ROC-AUC: 0.9733 | Val Profit: -1345

Лучшая эпоха для model_8_weight_decay: 32
Лучший ROC-AUC: 0.9852448021462106
val
ROC-AUC: 0.9852
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9362
Precision: 0.1214
Recall: 1.0
F0.5-score: 0.1473
Profit: -3695

Эпоха 1 | Train Loss: 1.1236 | Val ROC-AUC: 0.9362 | Val Profit: -3695
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.961
Precision: 0.2079
Recall: 1.0
F0.5-score: 0.2471
Profit: -1895

Эпоха 2 | Train Loss: 0.6831 | Val ROC-AUC: 0.9610 | Val Profit: -1895
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.969
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 3 | Train Loss: 0.4711 | Val ROC-AUC: 0.9690 | Val Profit: -945
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9541
Precision: 0.3125
Recall: 0.9524
F0.5-score: 0.361
Profit: -1005

Эпоха 4 | Train Loss: 0.4232 | Val ROC-AUC: 0.9541 | Val Profit: -1005
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9635
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 5 | Train Loss: 0.3760 | Val ROC-AUC: 0.9635 | Val Profit: -795
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.967
Precision: 0.3125
Recall: 0.9524
F0.5-score: 0.361
Profit: -1005

Эпоха 6 | Train Loss: 0.3946 | Val ROC-AUC: 0.9670 | Val Profit: -1005
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9759
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 7 | Train Loss: 0.3621 | Val ROC-AUC: 0.9759 | Val Profit: -770
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9752
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 8 | Train Loss: 0.3294 | Val ROC-AUC: 0.9752 | Val Profit: -100
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9486
Precision: 0.3684
Recall: 0.3333
F0.5-score: 0.3608
Profit: -335

Эпоха 9 | Train Loss: 0.2603 | Val ROC-AUC: 0.9486 | Val Profit: -335
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9759
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 10 | Train Loss: 0.3531 | Val ROC-AUC: 0.9759 | Val Profit: -1020
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9784
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 11 | Train Loss: 0.3022 | Val ROC-AUC: 0.9784 | Val Profit: -215
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9725
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 12 | Train Loss: 0.2690 | Val ROC-AUC: 0.9725 | Val Profit: -110
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9816
Precision: 0.2308
Recall: 1.0
F0.5-score: 0.2727
Profit: -1645

Эпоха 13 | Train Loss: 0.3773 | Val ROC-AUC: 0.9816 | Val Profit: -1645
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9716
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 14 | Train Loss: 0.3417 | Val ROC-AUC: 0.9716 | Val Profit: -795
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.978
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 15 | Train Loss: 0.2859 | Val ROC-AUC: 0.9780 | Val Profit: -185
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9669
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 16 | Train Loss: 0.2511 | Val ROC-AUC: 0.9669 | Val Profit: -160
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9645
Precision: 0.3333

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9606
Precision: 0.236
Recall: 1.0
F0.5-score: 0.2785
Profit: -1595

Эпоха 12 | Train Loss: 0.2782 | Val ROC-AUC: 0.9606 | Val Profit: -1595
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.982
Precision: 0.1765
Recall: 1.0
F0.5-score: 0.2113
Profit: -2345

Эпоха 13 | Train Loss: 0.4029 | Val ROC-AUC: 0.9820 | Val Profit: -2345
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9797
Precision: 0.5161
Recall: 0.7619
F0.5-score: 0.5517
Profit: -320

Эпоха 14 | Train Loss: 0.3016 | Val ROC-AUC: 0.9797 | Val Profit: -320
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9783
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 15 | Train Loss: 0.2391 | Val ROC-AUC: 0.9783 | Val Profit: -130
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.969
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 16 | Train Loss: 0.2109 | Val ROC-AUC: 0.9690 | Val Profit: -295
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9744
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 17 | Train Loss: 0.2296 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.982
Precision: 0.3
Recall: 1.0
F0.5-score: 0.3488
Profit: -1120

Эпоха 18 | Train Loss: 0.2832 | Val ROC-AUC: 0.9820 | Val Profit: -1120
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.976
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 19 | Train Loss: 0.2991 | Val ROC-AUC: 0.9760 | Val Profit: -370
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9742
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 20 | Train Loss: 0.2088 | Val ROC-AUC: 0.9742 | Val Profit: -95
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9673
Precision: 0.3958
Recall: 0.9048
F0.5-score: 0.446
Profit: -640

Эпоха 21 | Train Loss: 0.2134 | Val ROC-AUC: 0.9673 | Val Profit: -640
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9789
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 22 | Train Loss: 0.2414 | Val ROC-AUC: 0.9789 | Val Profit: -770
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.1933 | Val ROC-AUC: 0.9738 | Val Profit: -130
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9804
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 24 | Train Loss: 0.1993 | Val ROC-AUC: 0.9804 | Val Profit: -645
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9654
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 25 | Train Loss: 0.2435 | Val ROC-AUC: 0.9654 | Val Profit: -1020
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9783
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 26 | Train Loss: 0.3239 | Val ROC-AUC: 0.9783 | Val Profit: -870
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9777
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 27 | Train Loss: 0.2644 | Val ROC-AUC: 0.9777 | Val Profit: -115
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9702
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 28 | Train Loss: 0.1988 | Val ROC-AUC: 0.9702 | Val Profit: -355
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9666
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 29 | Train Loss: 0.1903 | Val ROC-AUC: 0.9666 | Val Profit: -135
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9755
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 30 | Train Loss: 0.2740 | Val ROC-AUC: 0.9755 | Val Profit: -1070
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9733
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 31 | Train Loss: 0.2226 | Val ROC-AUC: 0.9733 | Val Profit: -330
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9686
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 32 | Train Loss: 0.1966 | Val ROC-AUC: 0.9686 | Val Profit: -160
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9687
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 33 | Train Loss: 0.1587 | Val ROC-AUC: 0.9687 | Val Profit: -155
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9773
Precision: 0.2593
Recall: 1.0
F0.5-score: 0.3043
Profit: -1395

Эпоха 34 | Train Loss: 0.2367 | Val ROC-AUC: 0.9773 | Val Profit: -1395
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9788
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 35 | Train Loss: 0.2483 | Val ROC-AUC: 0.9788 | Val Profit: -680
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9771
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 36 | Train Loss: 0.2046 | Val ROC-AUC: 0.9771 | Val Profit: -95
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9741
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 37 | Train Loss: 0.1705 | Val ROC-AUC: 0.9741 | Val Profit: -135
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9713
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 38 | Train Loss: 0.1852 | Val ROC-AUC: 0.9713 | Val Profit: -420
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9807
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 39 | Train Loss: 0.2267 | Val ROC-AUC: 0.9807 | Val Profit: -330
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9696
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 40 | Train Loss: 0.1840 | Val ROC-AUC: 0.9696 | Val Profit: -175

Лучшая эпоха для model_8_weight_decay: 13
Лучший ROC-AUC: 0.9820254862508383
val
ROC-AUC: 0.982
Precision: 0.1765
Recall: 1.0
F0.5-score: 0.2113
Profit: -2345

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9158
Precision: 0.1149
Recall: 0.9524
F0.5-score: 0.1395
Profit: -3755

Эпоха 1 | Train Loss: 1.2070 | Val ROC-AUC: 0.9158 | Val Profit: -3755
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9583
Precision: 0.1556
Recall: 1.0
F0.5-score: 0.1872
Profit: -2745

Эпоха 2 | Train Loss: 0.8375 | Val ROC-AUC: 0.9583 | Val Profit: -2745
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9473
Precision: 0.3226
Recall: 0.9524
F0.5-score: 0.3717
Profit: -955

Эпоха 3 | Train Loss: 0.5605 | Val ROC-AUC: 0.9473 | Val Profit: -955
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9352
Precision: 0.3462
Recall: 0.4286
F0.5-score: 0.36
Profit: -440

Эпоха 4 | Train Loss: 0.3913 | Val ROC-AUC: 0.9352 | Val Profit: -440
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9551
Precision: 0.303
Recall: 0.9524
F0.5-score: 0.3509
Profit: -1055

Эпоха 5 | Train Loss: 0.3289 | Val ROC-AUC: 0.9551 | Val Profit: -1055
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9694
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 6 | Train Loss: 0.3747 | Val ROC-AUC: 0.9694 | Val Profit: -1195
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9502
Precision: 0.375
Recall: 0.8571
F0.5-score: 0.4225
Profit: -675

Эпоха 7 | Train Loss: 0.2415 | Val ROC-AUC: 0.9502 | Val Profit: -675
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9516
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 8 | Train Loss: 0.1532 | Val ROC-AUC: 0.9516 | Val Profit: -300
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9614
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 9 | Train Loss: 0.1316 | Val ROC-AUC: 0.9614 | Val Profit: -335
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9586
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 10 | Train Loss: 0.0754 | Val ROC-AUC: 0.9586 | Val Profit: -235
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9657
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 11 | Train Loss: 0.0530 | Val ROC-AUC: 0.9657 | Val Profit: -105
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9551
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 12 | Train Loss: 0.0425 | Val ROC-AUC: 0.9551 | Val Profit: -120
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9497
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 13 | Train Loss: 0.0352 | Val ROC-AUC: 0.9497 | Val Profit: -100
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9525
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 14 | Train Loss: 0.0306 | Val ROC-AUC: 0.9525 | Val Profit: -100
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9478
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 15 | Train Loss: 0.0276 | Val ROC-AUC: 0.9478 | Val Profit: -100
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9476
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 16 | Train Loss: 0.0258 | Val ROC-AUC: 0.9476 | Val Profit: -100
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9478
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 17 | Train Loss: 0.0249 | Val ROC-AUC: 0.9478 | Val Profit: -100
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9485
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.0242 | Val ROC-AUC: 0.9485 | Val Profit: -100
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9488
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 19 | Train Loss: 0.0236 | Val ROC-AUC: 0.9488 | Val Profit: -100
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9482
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 20 | Train Loss: 0.0231 | Val ROC-AUC: 0.9482 | Val Profit: -125
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9477
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0227 | Val ROC-AUC: 0.9477 | Val Profit: -125
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9476
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0223 | Val ROC-AUC: 0.9476 | Val Profit: -125
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9478
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0220 | Val ROC-AUC: 0.9478 | Val Profit: -125
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.948
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 24 | Train Loss: 0.0217 | Val ROC-AUC: 0.9480 | Val Profit: -125
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.948
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 25 | Train Loss: 0.0214 | Val ROC-AUC: 0.9480 | Val Profit: -125
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9482
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 26 | Train Loss: 0.0211 | Val ROC-AUC: 0.9482 | Val Profit: -125
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9486
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 27 | Train Loss: 0.0208 | Val ROC-AUC: 0.9486 | Val Profit: -135
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9492
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 28 | Train Loss: 0.0205 | Val ROC-AUC: 0.9492 | Val Profit: -135
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9492
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 29 | Train Loss: 0.0202 | Val ROC-AUC: 0.9492 | Val Profit: -135
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.95
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 30 | Train Loss: 0.0199 | Val ROC-AUC: 0.9500 | Val Profit: -135
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9514
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 31 | Train Loss: 0.0195 | Val ROC-AUC: 0.9514 | Val Profit: -135
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9512
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 32 | Train Loss: 0.0190 | Val ROC-AUC: 0.9512 | Val Profit: -135
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.952
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 33 | Train Loss: 0.0184 | Val ROC-AUC: 0.9520 | Val Profit: -135
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9525
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 34 | Train Loss: 0.0177 | Val ROC-AUC: 0.9525 | Val Profit: -135
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.952
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 35 | Train Loss: 0.0171 | Val ROC-AUC: 0.9520 | Val Profit: -135
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9548
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 36 | Train Loss: 0.0165 | Val ROC-AUC: 0.9548 | Val Profit: -135
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9549
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 37 | Train Loss: 0.0162 | Val ROC-AUC: 0.9549 | Val Profit: -135
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9532
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 38 | Train Loss: 0.0159 | Val ROC-AUC: 0.9532 | Val Profit: -135
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9533
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 39 | Train Loss: 0.0157 | Val ROC-AUC: 0.9533 | Val Profit: -135
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9536
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 40 | Train Loss: 0.0155 | Val ROC-AUC: 0.9536 | Val Profit: -135

Лучшая эпоха для model_8_weight_decay: 6
Лучший ROC-AUC: 0.9694164989939638
val
ROC-AUC: 0.9694
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9019
Precision: 0.116
Recall: 1.0
F0.5-score: 0.1409
Profit: -3895

Эпоха 1 | Train Loss: 1.2191 | Val ROC-AUC: 0.9019 | Val Profit: -3895
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9606
Precision: 0.1489
Recall: 1.0
F0.5-score: 0.1795
Profit: -2895

Эпоха 2 | Train Loss: 0.9144 | Val ROC-AUC: 0.9606 | Val Profit: -2895
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9583
Precision: 0.3175
Recall: 0.9524
F0.5-score: 0.3663
Profit: -980

Эпоха 3 | Train Loss: 0.6415 | Val ROC-AUC: 0.9583 | Val Profit: -980
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9418
Precision: 0.3571
Recall: 0.7143
F0.5-score: 0.3968
Profit: -630

Эпоха 4 | Train Loss: 0.4406 | Val ROC-AUC: 0.9418 | Val Profit: -630
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9307
Precision: 0.2963
Recall: 0.7619
F0.5-score: 0.3376
Profit: -895

Эпоха 5 | Train Loss: 0.3741 | Val ROC-AUC: 0.9307 | Val Profit: -895
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9641
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 6 | Train Loss: 0.2625 | Val ROC-AUC: 0.9641 | Val Profit: -475
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9619
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 7 | Train Loss: 0.2683 | Val ROC-AUC: 0.9619 | Val Profit: -370
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9013
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 8 | Train Loss: 0.2307 | Val ROC-AUC: 0.9013 | Val Profit: -385
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9619
Precision: 0.4186
Recall: 0.8571
F0.5-score: 0.4663
Profit: -550

Эпоха 9 | Train Loss: 0.3038 | Val ROC-AUC: 0.9619 | Val Profit: -550
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9643
Precision: 0.4286
Recall: 0.2857
F0.5-score: 0.3896
Profit: -245

Эпоха 10 | Train Loss: 0.1942 | Val ROC-AUC: 0.9643 | Val Profit: -245
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9705
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 11 | Train Loss: 0.1043 | Val ROC-AUC: 0.9705 | Val Profit: -180
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9581
Precision: 0.4444
Recall: 0.381
F0.5-score: 0.4301
Profit: -275

Эпоха 12 | Train Loss: 0.0736 | Val ROC-AUC: 0.9581 | Val Profit: -275
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9563
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 13 | Train Loss: 0.0698 | Val ROC-AUC: 0.9563 | Val Profit: -95
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9646
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 14 | Train Loss: 0.0440 | Val ROC-AUC: 0.9646 | Val Profit: -175
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9612
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0363 | Val ROC-AUC: 0.9612 | Val Profit: -95
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.934
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 16 | Train Loss: 0.0306 | Val ROC-AUC: 0.9340 | Val Profit: -95
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9379
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 17 | Train Loss: 0.0268 | Val ROC-AUC: 0.9379 | Val Profit: -95
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9465
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 18 | Train Loss: 0.0246 | Val ROC-AUC: 0.9465 | Val Profit: -95
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9439
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 19 | Train Loss: 0.0221 | Val ROC-AUC: 0.9439 | Val Profit: -95
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9474
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 20 | Train Loss: 0.0207 | Val ROC-AUC: 0.9474 | Val Profit: -120
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9348
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0200 | Val ROC-AUC: 0.9348 | Val Profit: -120
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9404
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0190 | Val ROC-AUC: 0.9404 | Val Profit: -120
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9423
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.0184 | Val ROC-AUC: 0.9423 | Val Profit: -120
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9484
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.0180 | Val ROC-AUC: 0.9484 | Val Profit: -120
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9324
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 25 | Train Loss: 0.0178 | Val ROC-AUC: 0.9324 | Val Profit: -120
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.95
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0180 | Val ROC-AUC: 0.9500 | Val Profit: -130
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9666
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 27 | Train Loss: 0.1257 | Val ROC-AUC: 0.9666 | Val Profit: -830
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.8954
Precision: 0.1579
Recall: 1.0
F0.5-score: 0.1899
Profit: -2695

Эпоха 28 | Train Loss: 0.9973 | Val ROC-AUC: 0.8954 | Val Profit: -2695
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9473
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 29 | Train Loss: 0.5160 | Val ROC-AUC: 0.9473 | Val Profit: -1020
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9604
Precision: 0.4255
Recall: 0.9524
F0.5-score: 0.4785
Profit: -580

Эпоха 30 | Train Loss: 0.3089 | Val ROC-AUC: 0.9604 | Val Profit: -580
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9543
Precision: 0.3462
Recall: 0.4286
F0.5-score: 0.36
Profit: -440

Эпоха 31 | Train Loss: 0.2198 | Val ROC-AUC: 0.9543 | Val Profit: -440
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.958
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 32 | Train Loss: 0.1574 | Val ROC-AUC: 0.9580 | Val Profit: -235
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9616
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 33 | Train Loss: 0.1109 | Val ROC-AUC: 0.9616 | Val Profit: -160
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9368
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 34 | Train Loss: 0.0838 | Val ROC-AUC: 0.9368 | Val Profit: -145
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9245
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 35 | Train Loss: 0.0574 | Val ROC-AUC: 0.9245 | Val Profit: -145
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9414
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9749
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 31 | Train Loss: 0.2109 | Val ROC-AUC: 0.9749 | Val Profit: -185
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9781
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 32 | Train Loss: 0.1754 | Val ROC-AUC: 0.9781 | Val Profit: -110
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.981
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 33 | Train Loss: 0.1331 | Val ROC-AUC: 0.9810 | Val Profit: -120
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9701
Precision: 0.2333
Recall: 1.0
F0.5-score: 0.2756
Profit: -1620

Эпоха 34 | Train Loss: 0.2358 | Val ROC-AUC: 0.9701 | Val Profit: -1620
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9783
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 35 | Train Loss: 0.2729 | Val ROC-AUC: 0.9783 | Val Profit: -330
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9763
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 36 | Train Loss: 0.2140 | Val ROC-AUC: 0.9763 | Val Profit: -190
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9801
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 37 | Train Loss: 0.1842 | Val ROC-AUC: 0.9801 | Val Profit: -130
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9795
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 38 | Train Loss: 0.1575 | Val ROC-AUC: 0.9795 | Val Profit: -90
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9654
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 39 | Train Loss: 0.2268 | Val ROC-AUC: 0.9654 | Val Profit: -1045
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9761
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 40 | Train Loss: 0.2411 | Val ROC-AUC: 0.9761 | Val Profit: -425

Лучшая эпоха для model_8_weight_decay: 13
Лучший ROC-AUC: 0.9856472166331322
val
ROC-AUC: 0.9856
Precision: 0.6154
Recall: 0.7619
F0.5-score: 0.64
Profit: -195

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.94
Precision: 0.1313
Recall: 1.0
F0.5-score: 0.1589
Profit: -3370

Эпоха 1 | Train Loss: 1.1679 | Val ROC-AUC: 0.9400 | Val Profit: -3370
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9677
Precision: 0.1694
Recall: 1.0
F0.5-score: 0.2031
Profit: -2470

Эпоха 2 | Train Loss: 0.7964 | Val ROC-AUC: 0.9677 | Val Profit: -2470
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9728
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 3 | Train Loss: 0.5545 | Val ROC-AUC: 0.9728 | Val Profit: -1195
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9623
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 4 | Train Loss: 0.3818 | Val ROC-AUC: 0.9623 | Val Profit: -500
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.962
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 5 | Train Loss: 0.3719 | Val ROC-AUC: 0.9620 | Val Profit: -1170
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9596
Precision: 0.4222
Recall: 0.9048
F0.5-score: 0.4726
Profit: -565

Эпоха 6 | Train Loss: 0.3138 | Val ROC-AUC: 0.9596 | Val Profit: -565
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9708
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 7 | Train Loss: 0.2528 | Val ROC-AUC: 0.9708 | Val Profit: -615
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9734
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 8 | Train Loss: 0.3680 | Val ROC-AUC: 0.9734 | Val Profit: -1470
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9701
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 9 | Train Loss: 0.3148 | Val ROC-AUC: 0.9701 | Val Profit: -720
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9748
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 10 | Train Loss: 0.2133 | Val ROC-AUC: 0.9748 | Val Profit: -210
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9698
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 11 | Train Loss: 0.1418 | Val ROC-AUC: 0.9698 | Val Profit: -100
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9775
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 12 | Train Loss: 0.1265 | Val ROC-AUC: 0.9775 | Val Profit: -465
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9425
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 13 | Train Loss: 0.1242 | Val ROC-AUC: 0.9425 | Val Profit: -105
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9772
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 14 | Train Loss: 0.1331 | Val ROC-AUC: 0.9772 | Val Profit: -630
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9696
Precision: 0.3846
Recall: 0.9524
F0.5-score: 0.4367
Profit: -705

Эпоха 15 | Train Loss: 0.2449 | Val ROC-AUC: 0.9696 | Val Profit: -705
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9781
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 16 | Train Loss: 0.2489 | Val ROC-AUC: 0.9781 | Val Profit: -795
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9757
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 17 | Train Loss: 0.1846 | Val ROC-AUC: 0.9757 | Val Profit: -415
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.974
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 18 | Train Loss: 0.1257 | Val ROC-AUC: 0.9740 | Val Profit: -205
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9686
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 19 | Train Loss: 0.0841 | Val ROC-AUC: 0.9686 | Val Profit: -80
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9704
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 20 | Train Loss: 0.0574 | Val ROC-AUC: 0.9704 | Val Profit: -100
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9572
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 21 | Train Loss: 0.0455 | Val ROC-AUC: 0.9572 | Val Profit: -110
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9286
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 22 | Train Loss: 0.0385 | Val ROC-AUC: 0.9286 | Val Profit: -110
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9434
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 23 | Train Loss: 0.0350 | Val ROC-AUC: 0.9434 | Val Profit: -185
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9111
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 24 | Train Loss: 0.0313 | Val ROC-AUC: 0.9111 | Val Profit: -110
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9198
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 25 | Train Loss: 0.0266 | Val ROC-AUC: 0.9198 | Val Profit: -100
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.938
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 26 | Train Loss: 0.0296 | Val ROC-AUC: 0.9380 | Val Profit: -75
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.973
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 27 | Train Loss: 0.0430 | Val ROC-AUC: 0.9730 | Val Profit: -325
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9105
Precision: 0.3415
Recall: 0.6667
F0.5-score: 0.3784
Profit: -640

Эпоха 28 | Train Loss: 0.1044 | Val ROC-AUC: 0.9105 | Val Profit: -640
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.967
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 29 | Train Loss: 0.3114 | Val ROC-AUC: 0.9670 | Val Profit: -1095
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9771
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 30 | Train Loss: 0.2790 | Val ROC-AUC: 0.9771 | Val Profit: -525
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9787
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 31 | Train Loss: 0.1815 | Val ROC-AUC: 0.9787 | Val Profit: -300
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9789
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 32 | Train Loss: 0.1323 | Val ROC-AUC: 0.9789 | Val Profit: -110
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9438
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 33 | Train Loss: 0.0966 | Val ROC-AUC: 0.9438 | Val Profit: -105
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9789
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 34 | Train Loss: 0.1022 | Val ROC-AUC: 0.9789 | Val Profit: -215
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9455
Precision: 0.8333
Recall: 0.7143
F0.5-score: 0.8065
Profit: -30

Эпоха 35 | Train Loss: 0.0916 | Val ROC-AUC: 0.9455 | Val Profit: -30
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9421
Precision: 0.875
Recall: 0.6667
F0.5-score: 0.8235
Profit: -15

Эпоха 36 | Train Loss: 0.0573 | Val ROC-AUC: 0.9421 | Val Profit: -15
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.8693
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 37 | Train Loss: 0.0709 | Val ROC-AUC: 0.8693 | Val Profit: -85
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9302
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 38 | Train Loss: 0.0700 | Val ROC-AUC: 0.9302 | Val Profit: -160
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.8939
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 39 | Train Loss: 0.0473 | Val ROC-AUC: 0.8939 | Val Profit: -80
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.851
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 40 | Train Loss: 0.0366 | Val ROC-AUC: 0.8510 | Val Profit: -145

Лучшая эпоха для model_8_weight_decay: 32
Лучший ROC-AUC: 0.9789403085177734
val
ROC-AUC: 0.9789
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9481
Precision: 0.1321
Recall: 1.0
F0.5-score: 0.1598
Profit: -3345

Эпоха 1 | Train Loss: 1.1800 | Val ROC-AUC: 0.9481 | Val Profit: -3345
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9685
Precision: 0.1707
Recall: 1.0
F0.5-score: 0.2047
Profit: -2445

Эпоха 2 | Train Loss: 0.8055 | Val ROC-AUC: 0.9685 | Val Profit: -2445
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9701
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 3 | Train Loss: 0.5566 | Val ROC-AUC: 0.9701 | Val Profit: -1195
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9702
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 4 | Train Loss: 0.3967 | Val ROC-AUC: 0.9702 | Val Profit: -680
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9805
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 5 | Train Loss: 0.2932 | Val ROC-AUC: 0.9805 | Val Profit: -770
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9462
Precision: 0.3016
Recall: 0.9048
F0.5-score: 0.348
Profit: -1015

Эпоха 6 | Train Loss: 0.3140 | Val ROC-AUC: 0.9462 | Val Profit: -1015
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9557
Precision: 0.253
Recall: 1.0
F0.5-score: 0.2975
Profit: -1445

Эпоха 7 | Train Loss: 0.3919 | Val ROC-AUC: 0.9557 | Val Profit: -1445
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9708
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 8 | Train Loss: 0.3018 | Val ROC-AUC: 0.9708 | Val Profit: -830
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.8351
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 9 | Train Loss: 0.1848 | Val ROC-AUC: 0.8351 | Val Profit: -190
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9151
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 10 | Train Loss: 0.1292 | Val ROC-AUC: 0.9151 | Val Profit: -235
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9641
Precision: 0.3488
Recall: 0.7143
F0.5-score: 0.3886
Profit: -655

Эпоха 11 | Train Loss: 0.2298 | Val ROC-AUC: 0.9641 | Val Profit: -655
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9649
Precision: 0.34
Recall: 0.8095
F0.5-score: 0.3846
Profit: -760

Эпоха 12 | Train Loss: 0.2594 | Val ROC-AUC: 0.9649 | Val Profit: -760
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.932
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 13 | Train Loss: 0.2060 | Val ROC-AUC: 0.9320 | Val Profit: -170
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9411
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 14 | Train Loss: 0.1318 | Val ROC-AUC: 0.9411 | Val Profit: -150
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.8798
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 15 | Train Loss: 0.1057 | Val ROC-AUC: 0.8798 | Val Profit: -160
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9729
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 16 | Train Loss: 0.1910 | Val ROC-AUC: 0.9729 | Val Profit: -780
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9498
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 17 | Train Loss: 0.1545 | Val ROC-AUC: 0.9498 | Val Profit: -325
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9317
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 18 | Train Loss: 0.1173 | Val ROC-AUC: 0.9317 | Val Profit: -190
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9781
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 19 | Train Loss: 0.1229 | Val ROC-AUC: 0.9781 | Val Profit: -415
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.976
Precision: 0.6364
Recall: 0.6667
F0.5-score: 0.6422
Profit: -165

Эпоха 20 | Train Loss: 0.1036 | Val ROC-AUC: 0.9760 | Val Profit: -165
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9787
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 21 | Train Loss: 0.0726 | Val ROC-AUC: 0.9787 | Val Profit: -180
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9716
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 22 | Train Loss: 0.0583 | Val ROC-AUC: 0.9716 | Val Profit: -170
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.969
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 23 | Train Loss: 0.0402 | Val ROC-AUC: 0.9690 | Val Profit: -140
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9394
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 24 | Train Loss: 0.0344 | Val ROC-AUC: 0.9394 | Val Profit: -165
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9379
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 25 | Train Loss: 0.0299 | Val ROC-AUC: 0.9379 | Val Profit: -125
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9386
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 26 | Train Loss: 0.0254 | Val ROC-AUC: 0.9386 | Val Profit: -145
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9344
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 27 | Train Loss: 0.0235 | Val ROC-AUC: 0.9344 | Val Profit: -155
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9324
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 28 | Train Loss: 0.0219 | Val ROC-AUC: 0.9324 | Val Profit: -155
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9309
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 29 | Train Loss: 0.0208 | Val ROC-AUC: 0.9309 | Val Profit: -155
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9288
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 30 | Train Loss: 0.0199 | Val ROC-AUC: 0.9288 | Val Profit: -180
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9849
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 31 | Train Loss: 0.2002 | Val ROC-AUC: 0.9849 | Val Profit: -1045
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9726
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 32 | Train Loss: 0.3328 | Val ROC-AUC: 0.9726 | Val Profit: -1245
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9761
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 33 | Train Loss: 0.2385 | Val ROC-AUC: 0.9761 | Val Profit: -545
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9771
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 34 | Train Loss: 0.1696 | Val ROC-AUC: 0.9771 | Val Profit: -245
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9669
Precision: 0.3953
Recall: 0.8095
F0.5-score: 0.4404
Profit: -585

Эпоха 35 | Train Loss: 0.1568 | Val ROC-AUC: 0.9669 | Val Profit: -585
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9745
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 36 | Train Loss: 0.1479 | Val ROC-AUC: 0.9745 | Val Profit: -220
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.976
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 37 | Train Loss: 0.0992 | Val ROC-AUC: 0.9760 | Val Profit: -190
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9788
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 38 | Train Loss: 0.0767 | Val ROC-AUC: 0.9788 | Val Profit: -175
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9737
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 39 | Train Loss: 0.0801 | Val ROC-AUC: 0.9737 | Val Profit: -205
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9779
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 40 | Train Loss: 0.0814 | Val ROC-AUC: 0.9779 | Val Profit: -150

Лучшая эпоха для model_8_weight_decay: 31
Лучший ROC-AUC: 0.9849094567404426
val
ROC-AUC: 0.9849
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.91
Precision: 0.125
Recall: 1.0
F0.5-score: 0.1515
Profit: -3570

Эпоха 1 | Train Loss: 1.1935 | Val ROC-AUC: 0.9100 | Val Profit: -3570
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9596
Precision: 0.1858
Recall: 1.0
F0.5-score: 0.222
Profit: -2195

Эпоха 2 | Train Loss: 0.8304 | Val ROC-AUC: 0.9596 | Val Profit: -2195
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9594
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 3 | Train Loss: 0.5726 | Val ROC-AUC: 0.9594 | Val Profit: -1495
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9643
Precision: 0.3529
Recall: 0.8571
F0.5-score: 0.4
Profit: -750

Эпоха 4 | Train Loss: 0.4161 | Val ROC-AUC: 0.9643 | Val Profit: -750
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9581
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 5 | Train Loss: 0.4076 | Val ROC-AUC: 0.9581 | Val Profit: -780
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9641
Precision: 0.2625
Recall: 1.0
F0.5-score: 0.3079
Profit: -1370

Эпоха 6 | Train Loss: 0.4327 | Val ROC-AUC: 0.9641 | Val Profit: -1370
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9738
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 7 | Train Loss: 0.3665 | Val ROC-AUC: 0.9738 | Val Profit: -970
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9614
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 8 | Train Loss: 0.3158 | Val ROC-AUC: 0.9614 | Val Profit: -455
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9818
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 9 | Train Loss: 0.2578 | Val ROC-AUC: 0.9818 | Val Profit: -235
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9728
Precision: 0.4082
Recall: 0.9524
F0.5-score: 0.4608
Profit: -630

Эпоха 10 | Train Loss: 0.2476 | Val ROC-AUC: 0.9728 | Val Profit: -630
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9783
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 11 | Train Loss: 0.2493 | Val ROC-AUC: 0.9783 | Val Profit: -415
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.883
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 12 | Train Loss: 0.1881 | Val ROC-AUC: 0.8830 | Val Profit: -165
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.8798
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 13 | Train Loss: 0.1476 | Val ROC-AUC: 0.8798 | Val Profit: -375
model_8_weight_decay | valid epoch 14

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9818
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

Эпоха 32 | Train Loss: 0.1916 | Val ROC-AUC: 0.9818 | Val Profit: -315
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9619
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 33 | Train Loss: 0.2404 | Val ROC-AUC: 0.9619 | Val Profit: -420
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9722
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 34 | Train Loss: 0.2438 | Val ROC-AUC: 0.9722 | Val Profit: -325
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9838
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 35 | Train Loss: 0.2121 | Val ROC-AUC: 0.9838 | Val Profit: -220
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.985
Precision: 0.9
Recall: 0.4286
F0.5-score: 0.7377
Profit: -40

Эпоха 36 | Train Loss: 0.1679 | Val ROC-AUC: 0.9850 | Val Profit: -40

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 37
ROC-AUC: 0.939
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 37 | Train Loss: 0.1302 | Val ROC-AUC: 0.9390 | Val Profit: -105
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.8451
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 38 | Train Loss: 0.1204 | Val ROC-AUC: 0.8451 | Val Profit: -110
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9653
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 39 | Train Loss: 0.2697 | Val ROC-AUC: 0.9653 | Val Profit: -1320
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.981
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 40 | Train Loss: 0.2274 | Val ROC-AUC: 0.9810 | Val Profit: -220

Лучшая эпоха для model_8_weight_decay: 36
Лучший ROC-AUC: 0.9849765258215962
val
ROC-AUC: 0.985
Precision: 0.9
Recall: 0.4286
F0.5-score: 0.7377
Profit: -40

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9382
Precision: 0.1373
Recall: 1.0
F0.5-score: 0.1659
Profit: -3195

Эпоха 1 | Train Loss: 1.1442 | Val ROC-AUC: 0.9382 | Val Profit: -3195
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9584
Precision: 0.1615
Recall: 1.0
F0.5-score: 0.1941
Profit: -2620

Эпоха 2 | Train Loss: 0.7962 | Val ROC-AUC: 0.9584 | Val Profit: -2620
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9661
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 3 | Train Loss: 0.5473 | Val ROC-AUC: 0.9661 | Val Profit: -870
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9628
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 4 | Train Loss: 0.3916 | Val ROC-AUC: 0.9628 | Val Profit: -780
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9724
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 5 | Train Loss: 0.3228 | Val ROC-AUC: 0.9724 | Val Profit: -400
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9713
Precision: 0.35
Recall: 1.0
F0.5-score: 0.4023
Profit: -870

Эпоха 6 | Train Loss: 0.2954 | Val ROC-AUC: 0.9713 | Val Profit: -870
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9686
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 7 | Train Loss: 0.3789 | Val ROC-AUC: 0.9686 | Val Profit: -855
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9659
Precision: 0.4375
Recall: 0.6667
F0.5-score: 0.4698
Profit: -415

Эпоха 8 | Train Loss: 0.2651 | Val ROC-AUC: 0.9659 | Val Profit: -415
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9669
Precision: 0.439
Recall: 0.8571
F0.5-score: 0.4865
Profit: -500

Эпоха 9 | Train Loss: 0.2527 | Val ROC-AUC: 0.9669 | Val Profit: -500
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9773
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 10 | Train Loss: 0.2189 | Val ROC-AUC: 0.9773 | Val Profit: -255
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9675
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 11 | Train Loss: 0.1778 | Val ROC-AUC: 0.9675 | Val Profit: -200
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9678
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 12 | Train Loss: 0.3219 | Val ROC-AUC: 0.9678 | Val Profit: -1170
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9729
Precision: 0.3704
Recall: 0.9524
F0.5-score: 0.4219
Profit: -755

Эпоха 13 | Train Loss: 0.2673 | Val ROC-AUC: 0.9729 | Val Profit: -755
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9728
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 14 | Train Loss: 0.2144 | Val ROC-AUC: 0.9728 | Val Profit: -270
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9737
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 15 | Train Loss: 0.1493 | Val ROC-AUC: 0.9737 | Val Profit: -90
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9654
Precision: 0.7778
Recall: 0.6667
F0.5-score: 0.7527
Profit: -65

Эпоха 16 | Train Loss: 0.1127 | Val ROC-AUC: 0.9654 | Val Profit: -65
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.981
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 17 | Train Loss: 0.1314 | Val ROC-AUC: 0.9810 | Val Profit: -365
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9649
Precision: 0.3231
Recall: 1.0
F0.5-score: 0.3737
Profit: -995

Эпоха 18 | Train Loss: 0.3208 | Val ROC-AUC: 0.9649 | Val Profit: -995
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9769
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 19 | Train Loss: 0.2437 | Val ROC-AUC: 0.9769 | Val Profit: -430
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9799
Precision: 0.6
Recall: 0.8571
F0.5-score: 0.6383
Profit: -225

Эпоха 20 | Train Loss: 0.1753 | Val ROC-AUC: 0.9799 | Val Profit: -225
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9791
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 21 | Train Loss: 0.1298 | Val ROC-AUC: 0.9791 | Val Profit: -130
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9696
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 22 | Train Loss: 0.1084 | Val ROC-AUC: 0.9696 | Val Profit: -185
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9759
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 23 | Train Loss: 0.1428 | Val ROC-AUC: 0.9759 | Val Profit: -555
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.9658
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 24 | Train Loss: 0.1909 | Val ROC-AUC: 0.9658 | Val Profit: -280
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9422
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 25 | Train Loss: 0.1569 | Val ROC-AUC: 0.9422 | Val Profit: -215
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.8998
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 26 | Train Loss: 0.1138 | Val ROC-AUC: 0.8998 | Val Profit: -165
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.8172
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 27 | Train Loss: 0.0894 | Val ROC-AUC: 0.8172 | Val Profit: -125
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9627
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 28 | Train Loss: 0.0925 | Val ROC-AUC: 0.9627 | Val Profit: -180
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9843
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

Эпоха 29 | Train Loss: 0.1974 | Val ROC-AUC: 0.9843 | Val Profit: -355
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9697
Precision: 0.6129
Recall: 0.9048
F0.5-score: 0.6552
Profit: -215

Эпоха 30 | Train Loss: 0.1656 | Val ROC-AUC: 0.9697 | Val Profit: -215
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9687
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 31 | Train Loss: 0.1974 | Val ROC-AUC: 0.9687 | Val Profit: -325
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9801
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 32 | Train Loss: 0.1900 | Val ROC-AUC: 0.9801 | Val Profit: -360
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9742
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 33 | Train Loss: 0.1410 | Val ROC-AUC: 0.9742 | Val Profit: -190
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9602
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 34 | Train Loss: 0.0884 | Val ROC-AUC: 0.9602 | Val Profit: -100
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9188
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 35 | Train Loss: 0.0615 | Val ROC-AUC: 0.9188 | Val Profit: -120
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.8484
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 36 | Train Loss: 0.0529 | Val ROC-AUC: 0.8484 | Val Profit: -80
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9805
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 37 | Train Loss: 0.1257 | Val ROC-AUC: 0.9805 | Val Profit: -795
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9531
Precision: 0.3455
Recall: 0.9048
F0.5-score: 0.3942
Profit: -815

Эпоха 38 | Train Loss: 0.2758 | Val ROC-AUC: 0.9531 | Val Profit: -815
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9787
Precision: 0.4524
Recall: 0.9048
F0.5-score: 0.5026
Profit: -490

Эпоха 39 | Train Loss: 0.2756 | Val ROC-AUC: 0.9787 | Val Profit: -490
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9772
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 40 | Train Loss: 0.2048 | Val ROC-AUC: 0.9772 | Val Profit: -380

Лучшая эпоха для model_8_weight_decay: 29
Лучший ROC-AUC: 0.9843058350100604
val
ROC-AUC: 0.9843
Precision: 0.5263
Recall: 0.9524
F0.5-score: 0.578
Profit: -355

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9253
Precision: 0.1221
Recall: 1.0
F0.5-score: 0.1481
Profit: -3670

Эпоха 1 | Train Loss: 1.1444 | Val ROC-AUC: 0.9253 | Val Profit: -3670
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9654
Precision: 0.1826
Recall: 1.0
F0.5-score: 0.2183
Profit: -2245

Эпоха 2 | Train Loss: 0.7547 | Val ROC-AUC: 0.9654 | Val Profit: -2245
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9696
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 3 | Train Loss: 0.5158 | Val ROC-AUC: 0.9696 | Val Profit: -1020
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9761
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 4 | Train Loss: 0.3838 | Val ROC-AUC: 0.9761 | Val Profit: -1020
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.974
Precision: 0.3134
Recall: 1.0
F0.5-score: 0.3633
Profit: -1045

Эпоха 5 | Train Loss: 0.3685 | Val ROC-AUC: 0.9740 | Val Profit: -1045
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9696
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 6 | Train Loss: 0.2885 | Val ROC-AUC: 0.9696 | Val Profit: -730
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9745
Precision: 0.3559
Recall: 1.0
F0.5-score: 0.4086
Profit: -845

Эпоха 7 | Train Loss: 0.3408 | Val ROC-AUC: 0.9745 | Val Profit: -845
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9576
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 8 | Train Loss: 0.2501 | Val ROC-AUC: 0.9576 | Val Profit: -615
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9654
Precision: 0.5
Recall: 0.7619
F0.5-score: 0.5369
Profit: -345

Эпоха 9 | Train Loss: 0.2484 | Val ROC-AUC: 0.9654 | Val Profit: -345
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9568
Precision: 0.2941
Recall: 0.9524
F0.5-score: 0.3413
Profit: -1105

Эпоха 10 | Train Loss: 0.3446 | Val ROC-AUC: 0.9568 | Val Profit: -1105
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9667
Precision: 0.3448
Recall: 0.9524
F0.5-score: 0.3953
Profit: -855

Эпоха 11 | Train Loss: 0.3554 | Val ROC-AUC: 0.9667 | Val Profit: -855
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.973
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 12 | Train Loss: 0.2394 | Val ROC-AUC: 0.9730 | Val Profit: -410
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9767
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 13 | Train Loss: 0.1680 | Val ROC-AUC: 0.9767 | Val Profit: -235
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.978
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 14 | Train Loss: 0.1613 | Val ROC-AUC: 0.9780 | Val Profit: -105
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.9713
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 15 | Train Loss: 0.2062 | Val ROC-AUC: 0.9713 | Val Profit: -445
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9745
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 16 | Train Loss: 0.1781 | Val ROC-AUC: 0.9745 | Val Profit: -190
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9669
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 17 | Train Loss: 0.1490 | Val ROC-AUC: 0.9669 | Val Profit: -190
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9722
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 18 | Train Loss: 0.2005 | Val ROC-AUC: 0.9722 | Val Profit: -665
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9729
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 19 | Train Loss: 0.2509 | Val ROC-AUC: 0.9729 | Val Profit: -530
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9769
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 20 | Train Loss: 0.1990 | Val ROC-AUC: 0.9769 | Val Profit: -255
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9502
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 21 | Train Loss: 0.1354 | Val ROC-AUC: 0.9502 | Val Profit: -125
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.9779
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

Эпоха 22 | Train Loss: 0.1062 | Val ROC-AUC: 0.9779 | Val Profit: -130
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.9787
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 23 | Train Loss: 0.1525 | Val ROC-AUC: 0.9787 | Val Profit: -145
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.941
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 24 | Train Loss: 0.0967 | Val ROC-AUC: 0.9410 | Val Profit: -145
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9302
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 25 | Train Loss: 0.0738 | Val ROC-AUC: 0.9302 | Val Profit: -125
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.97
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 26 | Train Loss: 0.1751 | Val ROC-AUC: 0.9700 | Val Profit: -770
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9753
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 27 | Train Loss: 0.2486 | Val ROC-AUC: 0.9753 | Val Profit: -780
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9801
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 28 | Train Loss: 0.2290 | Val ROC-AUC: 0.9801 | Val Profit: -380
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9777
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 29 | Train Loss: 0.1630 | Val ROC-AUC: 0.9777 | Val Profit: -300
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9796
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 30 | Train Loss: 0.1243 | Val ROC-AUC: 0.9796 | Val Profit: -205
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.9777
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 31 | Train Loss: 0.0986 | Val ROC-AUC: 0.9777 | Val Profit: -240
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9496
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 32 | Train Loss: 0.0825 | Val ROC-AUC: 0.9496 | Val Profit: -110
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9767
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 33 | Train Loss: 0.0788 | Val ROC-AUC: 0.9767 | Val Profit: -115
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9725
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 34 | Train Loss: 0.0832 | Val ROC-AUC: 0.9725 | Val Profit: -115
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9052
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 35 | Train Loss: 0.0843 | Val ROC-AUC: 0.9052 | Val Profit: -345
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.9805
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

Эпоха 36 | Train Loss: 0.3767 | Val ROC-AUC: 0.9805 | Val Profit: -1295
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9791
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 37 | Train Loss: 0.2626 | Val ROC-AUC: 0.9791 | Val Profit: -530
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.9759
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 38 | Train Loss: 0.1885 | Val ROC-AUC: 0.9759 | Val Profit: -340
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9726
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 39 | Train Loss: 0.1986 | Val ROC-AUC: 0.9726 | Val Profit: -280
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9738
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 40 | Train Loss: 0.1547 | Val ROC-AUC: 0.9738 | Val Profit: -225

Лучшая эпоха для model_8_weight_decay: 36
Лучший ROC-AUC: 0.9805499664654594
val
ROC-AUC: 0.9805
Precision: 0.2727
Recall: 1.0
F0.5-score: 0.3191
Profit: -1295

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9378
Precision: 0.1235
Recall: 1.0
F0.5-score: 0.1498
Profit: -3620

Эпоха 1 | Train Loss: 1.1601 | Val ROC-AUC: 0.9378 | Val Profit: -3620
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9657
Precision: 0.1892
Recall: 1.0
F0.5-score: 0.2258
Profit: -2145

Эпоха 2 | Train Loss: 0.7908 | Val ROC-AUC: 0.9657 | Val Profit: -2145
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9713
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 3 | Train Loss: 0.5261 | Val ROC-AUC: 0.9713 | Val Profit: -440
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.9547
Precision: 0.2386
Recall: 1.0
F0.5-score: 0.2815
Profit: -1570

Эпоха 4 | Train Loss: 0.4875 | Val ROC-AUC: 0.9547 | Val Profit: -1570
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9716
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 5 | Train Loss: 0.3943 | Val ROC-AUC: 0.9716 | Val Profit: -645
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9709
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 6 | Train Loss: 0.3021 | Val ROC-AUC: 0.9709 | Val Profit: -425
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9746
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 7 | Train Loss: 0.2919 | Val ROC-AUC: 0.9746 | Val Profit: -215
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9544
Precision: 0.3673
Recall: 0.8571
F0.5-score: 0.4147
Profit: -700

Эпоха 8 | Train Loss: 0.2584 | Val ROC-AUC: 0.9544 | Val Profit: -700
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9718
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 9 | Train Loss: 0.3206 | Val ROC-AUC: 0.9718 | Val Profit: -1095
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9742
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 10 | Train Loss: 0.3019 | Val ROC-AUC: 0.9742 | Val Profit: -245
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.8959
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 11 | Train Loss: 0.2146 | Val ROC-AUC: 0.8959 | Val Profit: -115
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9539
Precision: 0.3051
Recall: 0.8571
F0.5-score: 0.3502
Profit: -950

Эпоха 12 | Train Loss: 0.2168 | Val ROC-AUC: 0.9539 | Val Profit: -950
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.971
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 13 | Train Loss: 0.3612 | Val ROC-AUC: 0.9710 | Val Profit: -770
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9734
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 14 | Train Loss: 0.2621 | Val ROC-AUC: 0.9734 | Val Profit: -330
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.8702
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 15 | Train Loss: 0.2072 | Val ROC-AUC: 0.8702 | Val Profit: -250
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9736
Precision: 0.2632
Recall: 0.9524
F0.5-score: 0.3077
Profit: -1305

Эпоха 16 | Train Loss: 0.2918 | Val ROC-AUC: 0.9736 | Val Profit: -1305
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.982
Precision: 0.3962
Recall: 1.0
F0.5-score: 0.4506
Profit: -695

Эпоха 17 | Train Loss: 0.2709 | Val ROC-AUC: 0.9820 | Val Profit: -695
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9738
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 18 | Train Loss: 0.2252 | Val ROC-AUC: 0.9738 | Val Profit: -200
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.962
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 19 | Train Loss: 0.1793 | Val ROC-AUC: 0.9620 | Val Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 21
ROC-AUC: 0.8596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.1883 | Val ROC-AUC: 0.8596 | Val Profit: -105
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.8535
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.1739 | Val ROC-AUC: 0.8535 | Val Profit: -120
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.8416
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.1624 | Val ROC-AUC: 0.8416 | Val Profit: -130
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.866
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.1476 | Val ROC-AUC: 0.8660 | Val Profit: -120
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.8644
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 25 | Train Loss: 0.1378 | Val ROC-AUC: 0.8644 | Val Profit: -155
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.8629
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 26 | Train Loss: 0.1291 | Val ROC-AUC: 0.8629 | Val Profit: -155
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.8441
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.1220 | Val ROC-AUC: 0.8441 | Val Profit: -130
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.8728
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 28 | Train Loss: 0.1128 | Val ROC-AUC: 0.8728 | Val Profit: -155
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.8535
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.1085 | Val ROC-AUC: 0.8535 | Val Profit: -105
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.8499
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.1021 | Val ROC-AUC: 0.8499 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 31
ROC-AUC: 0.8424
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 31 | Train Loss: 0.0960 | Val ROC-AUC: 0.8424 | Val Profit: -155
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.8453
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 32 | Train Loss: 0.0914 | Val ROC-AUC: 0.8453 | Val Profit: -130
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.8569
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 33 | Train Loss: 0.0892 | Val ROC-AUC: 0.8569 | Val Profit: -130
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.8339
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 34 | Train Loss: 0.0855 | Val ROC-AUC: 0.8339 | Val Profit: -130
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.8354
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 35 | Train Loss: 0.0837 | Val ROC-AUC: 0.8354 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 36
ROC-AUC: 0.8468
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 36 | Train Loss: 0.0806 | Val ROC-AUC: 0.8468 | Val Profit: -105
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.83
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 37 | Train Loss: 0.0778 | Val ROC-AUC: 0.8300 | Val Profit: -130
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.8378
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 38 | Train Loss: 0.0731 | Val ROC-AUC: 0.8378 | Val Profit: -130
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.8278
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 39 | Train Loss: 0.0703 | Val ROC-AUC: 0.8278 | Val Profit: -130
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.8381
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 40 | Train Loss: 0.0674 | Val ROC-AUC: 0.8381 | Val Profit: -130

Лучшая эпоха для model_8_weight_decay: 11
Лучший ROC-AUC: 0.924748490945674
val
ROC-AUC: 0.9247
Precision: 0.4286
Recall: 0.4286
F0.5-score: 0.4286
Profit: -315

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.4897
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -430

Эпоха 1 | Train Loss: 1.3259 | Val ROC-AUC: 0.4897 | Val Profit: -430
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.7045
Precision: 0.0882
Recall: 0.2857
F0.5-score: 0.1024
Profit: -1595

Эпоха 2 | Train Loss: 1.2260 | Val ROC-AUC: 0.7045 | Val Profit: -1595
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.8102
Precision: 0.1351
Recall: 0.7143
F0.5-score: 0.1613
Profit: -2355

Эпоха 3 | Train Loss: 1.1578 | Val ROC-AUC: 0.8102 | Val Profit: -2355
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.8504
Precision: 0.1509
Recall: 0.7619
F0.5-score: 0.1798
Profit: -2195

Эпоха 4 | Train Loss: 1.0900 | Val ROC-AUC: 0.8504 | Val Profit: -2195
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9131
Precision: 0.1782
Recall: 0.8571
F0.5-score: 0.2118
Profit: -2000

Эпоха 5 | Train Loss: 0.9975 | Val ROC-AUC: 0.9131 | Val Profit: -2000
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9229
Precision: 0.2152
Recall: 0.8095
F0.5-score: 0.2522
Profit: -1485

Эпоха 6 | Train Loss: 0.9017 | Val ROC-AUC: 0.9229 | Val Profit: -1485
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9164
Precision: 0.254
Recall: 0.7619
F0.5-score: 0.293
Profit: -1120

Эпоха 7 | Train Loss: 0.8051 | Val ROC-AUC: 0.9164 | Val Profit: -1120
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9074
Precision: 0.2941
Recall: 0.7143
F0.5-score: 0.3333
Profit: -855

Эпоха 8 | Train Loss: 0.7181 | Val ROC-AUC: 0.9074 | Val Profit: -855
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.8985
Precision: 0.3429
Recall: 0.5714
F0.5-score: 0.3727
Profit: -560

Эпоха 9 | Train Loss: 0.6421 | Val ROC-AUC: 0.8985 | Val Profit: -560
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9002
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 10 | Train Loss: 0.5797 | Val ROC-AUC: 0.9002 | Val Profit: -310
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.8867
Precision: 0.3913
Recall: 0.4286
F0.5-score: 0.3982
Profit: -365

Эпоха 11 | Train Loss: 0.5230 | Val ROC-AUC: 0.8867 | Val Profit: -365
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.8888
Precision: 0.4118
Recall: 0.3333
F0.5-score: 0.3933
Profit: -285

Эпоха 12 | Train Loss: 0.4692 | Val ROC-AUC: 0.8888 | Val Profit: -285
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9191
Precision: 0.4375
Recall: 0.3333
F0.5-score: 0.4118
Profit: -260

Эпоха 13 | Train Loss: 0.4218 | Val ROC-AUC: 0.9191 | Val Profit: -260
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.8897
Precision: 0.3636
Recall: 0.1905
F0.5-score: 0.3077
Profit: -240

Эпоха 14 | Train Loss: 0.3846 | Val ROC-AUC: 0.8897 | Val Profit: -240
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.8943
Precision: 0.3846
Recall: 0.2381
F0.5-score: 0.3425
Profit: -255

Эпоха 15 | Train Loss: 0.3529 | Val ROC-AUC: 0.8943 | Val Profit: -255
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.875
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 16 | Train Loss: 0.3120 | Val ROC-AUC: 0.8750 | Val Profit: -225
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.8816
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 17 | Train Loss: 0.2754 | Val ROC-AUC: 0.8816 | Val Profit: -225
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.8614
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 18 | Train Loss: 0.2472 | Val ROC-AUC: 0.8614 | Val Profit: -200
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.8743
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 19 | Train Loss: 0.2293 | Val ROC-AUC: 0.8743 | Val Profit: -225
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.8511
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 20 | Train Loss: 0.2046 | Val ROC-AUC: 0.8511 | Val Profit: -150
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.8357
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 21 | Train Loss: 0.1881 | Val ROC-AUC: 0.8357 | Val Profit: -200
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.8361
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 22 | Train Loss: 0.1712 | Val ROC-AUC: 0.8361 | Val Profit: -150
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.8374
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 23 | Train Loss: 0.1575 | Val ROC-AUC: 0.8374 | Val Profit: -175
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.8245
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 24 | Train Loss: 0.1475 | Val ROC-AUC: 0.8245 | Val Profit: -160
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.8245
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 25 | Train Loss: 0.1412 | Val ROC-AUC: 0.8245 | Val Profit: -180
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.8468
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 26 | Train Loss: 0.1395 | Val ROC-AUC: 0.8468 | Val Profit: -160
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.8744
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 27 | Train Loss: 0.2036 | Val ROC-AUC: 0.8744 | Val Profit: -190
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.8691
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 28 | Train Loss: 0.2304 | Val ROC-AUC: 0.8691 | Val Profit: -225
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.8693
Precision: 0.4167
Recall: 0.2381
F0.5-score: 0.3623
Profit: -230

Эпоха 29 | Train Loss: 0.1661 | Val ROC-AUC: 0.8693 | Val Profit: -230
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.8224
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 30 | Train Loss: 0.1431 | Val ROC-AUC: 0.8224 | Val Profit: -175
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.8558
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 31 | Train Loss: 0.1157 | Val ROC-AUC: 0.8558 | Val Profit: -175
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.8362
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 32 | Train Loss: 0.1012 | Val ROC-AUC: 0.8362 | Val Profit: -175
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.8359
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 33 | Train Loss: 0.0911 | Val ROC-AUC: 0.8359 | Val Profit: -185
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.831
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 34 | Train Loss: 0.0840 | Val ROC-AUC: 0.8310 | Val Profit: -185
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.831
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 35 | Train Loss: 0.0775 | Val ROC-AUC: 0.8310 | Val Profit: -185
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.8428
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 36 | Train Loss: 0.0729 | Val ROC-AUC: 0.8428 | Val Profit: -160
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.8315
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 37 | Train Loss: 0.0690 | Val ROC-AUC: 0.8315 | Val Profit: -185
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.8378
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 38 | Train Loss: 0.0658 | Val ROC-AUC: 0.8378 | Val Profit: -160
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.8298
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 39 | Train Loss: 0.0635 | Val ROC-AUC: 0.8298 | Val Profit: -160
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.8271
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 40 | Train Loss: 0.0610 | Val ROC-AUC: 0.8271 | Val Profit: -135

Лучшая эпоха для model_8_weight_decay: 6
Лучший ROC-AUC: 0.9228705566733736
val
ROC-AUC: 0.9229
Precision: 0.2152
Recall: 0.8095
F0.5-score: 0.2522
Profit: -1485

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.4527
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -380

Эпоха 1 | Train Loss: 1.3267 | Val ROC-AUC: 0.4527 | Val Profit: -380
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.6469
Precision: 0.0725
Recall: 0.2381
F0.5-score: 0.0842
Profit: -1655

Эпоха 2 | Train Loss: 1.2279 | Val ROC-AUC: 0.6469 | Val Profit: -1655
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.7608
Precision: 0.1188
Recall: 0.5714
F0.5-score: 0.1412
Profit: -2210

Эпоха 3 | Train Loss: 1.1604 | Val ROC-AUC: 0.7608 | Val Profit: -2210
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.8396
Precision: 0.1619
Recall: 0.8095
F0.5-score: 0.1927
Profit: -2135

Эпоха 4 | Train Loss: 1.0841 | Val ROC-AUC: 0.8396 | Val Profit: -2135
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.871
Precision: 0.1649
Recall: 0.7619
F0.5-score: 0.1956
Profit: -1970

Эпоха 5 | Train Loss: 1.0004 | Val ROC-AUC: 0.8710 | Val Profit: -1970
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9093
Precision: 0.2
Recall: 0.8571
F0.5-score: 0.2362
Profit: -1725

Эпоха 6 | Train Loss: 0.9149 | Val ROC-AUC: 0.9093 | Val Profit: -1725
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9252
Precision: 0.25
Recall: 0.8571
F0.5-score: 0.2913
Profit: -1275

Эпоха 7 | Train Loss: 0.8286 | Val ROC-AUC: 0.9252 | Val Profit: -1275
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9243
Precision: 0.2581
Recall: 0.7619
F0.5-score: 0.2974
Profit: -1095

Эпоха 8 | Train Loss: 0.7506 | Val ROC-AUC: 0.9243 | Val Profit: -1095
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9308
Precision: 0.375
Recall: 0.7143
F0.5-score: 0.4144
Profit: -580

Эпоха 9 | Train Loss: 0.6802 | Val ROC-AUC: 0.9308 | Val Profit: -580
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9227
Precision: 0.3448
Recall: 0.4762
F0.5-score: 0.365
Profit: -480

Эпоха 10 | Train Loss: 0.6126 | Val ROC-AUC: 0.9227 | Val Profit: -480
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9194
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 11 | Train Loss: 0.5535 | Val ROC-AUC: 0.9194 | Val Profit: -250
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.918
Precision: 0.4444
Recall: 0.381
F0.5-score: 0.4301
Profit: -275

Эпоха 12 | Train Loss: 0.4963 | Val ROC-AUC: 0.9180 | Val Profit: -275
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.8943
Precision: 0.3
Recall: 0.1429
F0.5-score: 0.2459
Profit: -250

Эпоха 13 | Train Loss: 0.4500 | Val ROC-AUC: 0.8943 | Val Profit: -250
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.9281
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 14 | Train Loss: 0.3943 | Val ROC-AUC: 0.9281 | Val Profit: -205
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.8983
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 15 | Train Loss: 0.3478 | Val ROC-AUC: 0.8983 | Val Profit: -120
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.8971
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 16 | Train Loss: 0.3037 | Val ROC-AUC: 0.8971 | Val Profit: -170
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.8962
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 17 | Train Loss: 0.2751 | Val ROC-AUC: 0.8962 | Val Profit: -120
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.8822
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 18 | Train Loss: 0.2467 | Val ROC-AUC: 0.8822 | Val Profit: -170
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.8803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.2227 | Val ROC-AUC: 0.8803 | Val Profit: -105
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.8877
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 20 | Train Loss: 0.2062 | Val ROC-AUC: 0.8877 | Val Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 21
ROC-AUC: 0.8506
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 21 | Train Loss: 0.1867 | Val ROC-AUC: 0.8506 | Val Profit: -170
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.8966
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.1733 | Val ROC-AUC: 0.8966 | Val Profit: -105
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.8307
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.1890 | Val ROC-AUC: 0.8307 | Val Profit: -120
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.8688
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.1735 | Val ROC-AUC: 0.8688 | Val Profit: -130
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.8498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.1511 | Val ROC-AUC: 0.8498 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 26
ROC-AUC: 0.8879
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 26 | Train Loss: 0.1518 | Val ROC-AUC: 0.8879 | Val Profit: -135
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.8317
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 27 | Train Loss: 0.1402 | Val ROC-AUC: 0.8317 | Val Profit: -95
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.9093
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 28 | Train Loss: 0.1217 | Val ROC-AUC: 0.9093 | Val Profit: -145
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.8712
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 29 | Train Loss: 0.1274 | Val ROC-AUC: 0.8712 | Val Profit: -155
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.8322
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.1018 | Val ROC-AUC: 0.8322 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 31
ROC-AUC: 0.861
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 31 | Train Loss: 0.0906 | Val ROC-AUC: 0.8610 | Val Profit: -105
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.8598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 32 | Train Loss: 0.0866 | Val ROC-AUC: 0.8598 | Val Profit: -105
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9092
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 33 | Train Loss: 0.0786 | Val ROC-AUC: 0.9092 | Val Profit: -145
model_8_weight_decay | valid epoch 34
ROC-AUC: 0.8177
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 34 | Train Loss: 0.0778 | Val ROC-AUC: 0.8177 | Val Profit: -105
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.8463
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 35 | Train Loss: 0.0764 | Val ROC-AUC: 0.8463 | Val Profit: -130
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.877
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 36 | Train Loss: 0.0760 | Val ROC-AUC: 0.8770 | Val Profit: -145
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.9052
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 37 | Train Loss: 0.0963 | Val ROC-AUC: 0.9052 | Val Profit: -105
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.8451
Precision: 0.3571
Recall: 0.2381
F0.5-score: 0.3247
Profit: -280

Эпоха 38 | Train Loss: 0.2158 | Val ROC-AUC: 0.8451 | Val Profit: -280
model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9347
Precision: 0.3684
Recall: 0.3333
F0.5-score: 0.3608
Profit: -335

Эпоха 39 | Train Loss: 0.3114 | Val ROC-AUC: 0.9347 | Val Profit: -335
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.9049
Precision: 0.3529
Recall: 0.2857
F0.5-score: 0.3371
Profit: -320

Эпоха 40 | Train Loss: 0.3621 | Val ROC-AUC: 0.9049 | Val Profit: -320

Лучшая эпоха для model_8_weight_decay: 39
Лучший ROC-AUC: 0.9346747149564051
val
ROC-AUC: 0.9347
Precision: 0.3684
Recall: 0.3333
F0.5-score: 0.3608
Profit: -335

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [139]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.005, 'dropout': 0.01, 'weight_decay': 0.01, 'profit': np.int64(-40), 'roc_auc': 0.9849765258215962}

In [140]:
LR = best["lr"]
WEIGHT_DECAY = best["weight_decay"]
DROPOUT_COEF = best["dropout"]

In [141]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_8 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model_8.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

config = {
    "model": "MLP_weight_decay",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_8)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_8_weight_decay", config=config)
log_file = new_log_file()

model_8 = train_model(
    model=model_8,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_8_weight_decay"
)

save_results(model_8, "model_8", log_file, run)

run.finish()

model_8_weight_decay | valid epoch 1
ROC-AUC: 0.9437
Precision: 0.1765
Recall: 1.0
F0.5-score: 0.2113
Profit: -2345

Эпоха 1 | Train Loss: 1.1563 | Val ROC-AUC: 0.9437 | Val Profit: -2345
model_8_weight_decay | valid epoch 2
ROC-AUC: 0.9596
Precision: 0.2283
Recall: 1.0
F0.5-score: 0.2699
Profit: -1670

Эпоха 2 | Train Loss: 0.8362 | Val ROC-AUC: 0.9596 | Val Profit: -1670
model_8_weight_decay | valid epoch 3
ROC-AUC: 0.9736
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 3 | Train Loss: 0.5543 | Val ROC-AUC: 0.9736 | Val Profit: -1020
model_8_weight_decay | valid epoch 4
ROC-AUC: 0.96
Precision: 0.2838
Recall: 1.0
F0.5-score: 0.3312
Profit: -1220

Эпоха 4 | Train Loss: 0.4349 | Val ROC-AUC: 0.9600 | Val Profit: -1220
model_8_weight_decay | valid epoch 5
ROC-AUC: 0.9583
Precision: 0.2632
Recall: 0.9524
F0.5-score: 0.3077
Profit: -1305

Эпоха 5 | Train Loss: 0.4016 | Val ROC-AUC: 0.9583 | Val Profit: -1305
model_8_weight_decay | valid epoch 6
ROC-AUC: 0.9671
Precision: 0.2817
Recall: 0.9524
F0.5-score: 0.3279
Profit: -1180

Эпоха 6 | Train Loss: 0.4002 | Val ROC-AUC: 0.9671 | Val Profit: -1180
model_8_weight_decay | valid epoch 7
ROC-AUC: 0.9717
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 7 | Train Loss: 0.3131 | Val ROC-AUC: 0.9717 | Val Profit: -615
model_8_weight_decay | valid epoch 8
ROC-AUC: 0.9565
Precision: 0.3721
Recall: 0.7619
F0.5-score: 0.4145
Profit: -620

Эпоха 8 | Train Loss: 0.2761 | Val ROC-AUC: 0.9565 | Val Profit: -620
model_8_weight_decay | valid epoch 9
ROC-AUC: 0.9679
Precision: 0.3333
Recall: 1.0
F0.5-score: 0.3846
Profit: -945

Эпоха 9 | Train Loss: 0.3244 | Val ROC-AUC: 0.9679 | Val Profit: -945
model_8_weight_decay | valid epoch 10
ROC-AUC: 0.9736
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 10 | Train Loss: 0.2680 | Val ROC-AUC: 0.9736 | Val Profit: -295
model_8_weight_decay | valid epoch 11
ROC-AUC: 0.9728
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 11 | Train Loss: 0.1923 | Val ROC-AUC: 0.9728 | Val Profit: -185
model_8_weight_decay | valid epoch 12
ROC-AUC: 0.9718
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 12 | Train Loss: 0.2170 | Val ROC-AUC: 0.9718 | Val Profit: -180
model_8_weight_decay | valid epoch 13
ROC-AUC: 0.9785
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 13 | Train Loss: 0.2386 | Val ROC-AUC: 0.9785 | Val Profit: -325
model_8_weight_decay | valid epoch 14
ROC-AUC: 0.974
Precision: 0.3818
Recall: 1.0
F0.5-score: 0.4357
Profit: -745

Эпоха 14 | Train Loss: 0.2964 | Val ROC-AUC: 0.9740 | Val Profit: -745
model_8_weight_decay | valid epoch 15
ROC-AUC: 0.974
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 15 | Train Loss: 0.2528 | Val ROC-AUC: 0.9740 | Val Profit: -220
model_8_weight_decay | valid epoch 16
ROC-AUC: 0.9706
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 16 | Train Loss: 0.2130 | Val ROC-AUC: 0.9706 | Val Profit: -255
model_8_weight_decay | valid epoch 17
ROC-AUC: 0.9796
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 17 | Train Loss: 0.2019 | Val ROC-AUC: 0.9796 | Val Profit: -130
model_8_weight_decay | valid epoch 18
ROC-AUC: 0.9828
Precision: 0.4468
Recall: 1.0
F0.5-score: 0.5024
Profit: -545

Эпоха 18 | Train Loss: 0.1964 | Val ROC-AUC: 0.9828 | Val Profit: -545
model_8_weight_decay | valid epoch 19
ROC-AUC: 0.9682
Precision: 0.2561
Recall: 1.0
F0.5-score: 0.3009
Profit: -1420

Эпоха 19 | Train Loss: 0.3311 | Val ROC-AUC: 0.9682 | Val Profit: -1420
model_8_weight_decay | valid epoch 20
ROC-AUC: 0.9771
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 20 | Train Loss: 0.2605 | Val ROC-AUC: 0.9771 | Val Profit: -310
model_8_weight_decay | valid epoch 21
ROC-AUC: 0.9764
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 21 | Train Loss: 0.2250 | Val ROC-AUC: 0.9764 | Val Profit: -190
model_8_weight_decay | valid epoch 22
ROC-AUC: 0.98
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.1828 | Val ROC-AUC: 0.9800 | Val Profit: -115
model_8_weight_decay | valid epoch 23
ROC-AUC: 0.8915
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 23 | Train Loss: 0.1491 | Val ROC-AUC: 0.8915 | Val Profit: -100
model_8_weight_decay | valid epoch 24
ROC-AUC: 0.981
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 24 | Train Loss: 0.2886 | Val ROC-AUC: 0.9810 | Val Profit: -1495
model_8_weight_decay | valid epoch 25
ROC-AUC: 0.9781
Precision: 0.2958
Recall: 1.0
F0.5-score: 0.3443
Profit: -1145

Эпоха 25 | Train Loss: 0.2802 | Val ROC-AUC: 0.9781 | Val Profit: -1145
model_8_weight_decay | valid epoch 26
ROC-AUC: 0.9777
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 26 | Train Loss: 0.2730 | Val ROC-AUC: 0.9777 | Val Profit: -325
model_8_weight_decay | valid epoch 27
ROC-AUC: 0.9773
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 27 | Train Loss: 0.2232 | Val ROC-AUC: 0.9773 | Val Profit: -210
model_8_weight_decay | valid epoch 28
ROC-AUC: 0.974
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 28 | Train Loss: 0.1875 | Val ROC-AUC: 0.9740 | Val Profit: -240
model_8_weight_decay | valid epoch 29
ROC-AUC: 0.9345
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 29 | Train Loss: 0.1874 | Val ROC-AUC: 0.9345 | Val Profit: -130
model_8_weight_decay | valid epoch 30
ROC-AUC: 0.9804
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 30 | Train Loss: 0.1546 | Val ROC-AUC: 0.9804 | Val Profit: -175
model_8_weight_decay | valid epoch 31
ROC-AUC: 0.8339
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 31 | Train Loss: 0.1467 | Val ROC-AUC: 0.8339 | Val Profit: -105
model_8_weight_decay | valid epoch 32
ROC-AUC: 0.9818
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

Эпоха 32 | Train Loss: 0.1916 | Val ROC-AUC: 0.9818 | Val Profit: -315
model_8_weight_decay | valid epoch 33
ROC-AUC: 0.9619
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 33 | Train Loss: 0.2404 | Val ROC-AUC: 0.9619 | Val Profit: -420

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 34
ROC-AUC: 0.9722
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 34 | Train Loss: 0.2438 | Val ROC-AUC: 0.9722 | Val Profit: -325
model_8_weight_decay | valid epoch 35
ROC-AUC: 0.9838
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 35 | Train Loss: 0.2121 | Val ROC-AUC: 0.9838 | Val Profit: -220
model_8_weight_decay | valid epoch 36
ROC-AUC: 0.985
Precision: 0.9
Recall: 0.4286
F0.5-score: 0.7377
Profit: -40

Эпоха 36 | Train Loss: 0.1679 | Val ROC-AUC: 0.9850 | Val Profit: -40
model_8_weight_decay | valid epoch 37
ROC-AUC: 0.939
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 37 | Train Loss: 0.1302 | Val ROC-AUC: 0.9390 | Val Profit: -105
model_8_weight_decay | valid epoch 38
ROC-AUC: 0.8451
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 38 | Train Loss: 0.1204 | Val ROC-AUC: 0.8451 | Val Profit: -110

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_8_weight_decay | valid epoch 39
ROC-AUC: 0.9653
Precision: 0.2692
Recall: 1.0
F0.5-score: 0.3153
Profit: -1320

Эпоха 39 | Train Loss: 0.2697 | Val ROC-AUC: 0.9653 | Val Profit: -1320
model_8_weight_decay | valid epoch 40
ROC-AUC: 0.981
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 40 | Train Loss: 0.2274 | Val ROC-AUC: 0.9810 | Val Profit: -220

Лучшая эпоха для model_8_weight_decay: 36
Лучший ROC-AUC: 0.9849765258215962
Train
ROC-AUC: 0.9922
Precision: 0.9032
Recall: 0.3373
F0.5-score: 0.6763
Profit: -210

Test
ROC-AUC: 0.9654
Precision: 0.8359
Recall: 0.3623
F0.5-score: 0.6627
Profit: -74865

In [142]:
train_metrics = evaluate_model(model_8, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_8, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9922
Precision: 0.9032
Recall: 0.3373
F0.5-score: 0.6763
Profit: -210

Test
ROC-AUC: 0.9654
Precision: 0.8359
Recall: 0.3623
F0.5-score: 0.6627
Profit: -74865

Добавив регуляризацию видим, что качество улучшилось относительно бейзлайна, практически на уровне чистого batchnorm

При этом пришлось обратно вернуться к обычной RELU

## model_9_Focal_loss

In [143]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        targets = targets.float()

        bce_loss = nn.functional.binary_cross_entropy_with_logits(
            logits,
            targets,
            reduction="none"
        )

        probs = torch.sigmoid(logits)
        pt = torch.where(targets == 1, probs, 1 - probs)
        focal_weight = self.alpha * (1 - pt) ** self.gamma
        loss = focal_weight * bce_loss

        return loss.mean()

In [144]:
EPOCHS = 30
SEED = 42

In [145]:
wandb.init(mode="disabled")
results = []
for LR in [0.01, 0.005]:
    for GAMMA in [1.0, 2.0, 3.0]:
        for ALPHA in [0.25, 0.5, 0.99]:
            for DROPOUT_COEF in [0.0, 0.1, 0.2]:
                for WEIGHT_DECAY in [0.0, 0.0001, 0.001]:
                    random.seed(SEED)
                    np.random.seed(SEED)
                    torch.manual_seed(SEED) 

                    model_9 = nn.Sequential(
                        nn.Linear(9, 128),
                        nn.BatchNorm1d(128),
                        nn.ReLU(),
                        nn.Dropout(DROPOUT_COEF),

                        nn.Linear(128, 64),
                        nn.BatchNorm1d(64),
                        nn.ReLU(),
                        nn.Dropout(DROPOUT_COEF),

                        nn.Linear(64, 32),
                        nn.BatchNorm1d(32),
                        nn.ReLU(),
                        nn.Dropout(DROPOUT_COEF),

                        nn.Linear(32, 16),
                        nn.BatchNorm1d(16),
                        nn.ReLU(),
                        nn.Dropout(DROPOUT_COEF),

                        nn.Linear(16, 8),
                        nn.BatchNorm1d(8),
                        nn.ReLU(),
                        nn.Dropout(DROPOUT_COEF),

                        nn.Linear(8, 1)
                    )

                    loss_fn = FocalLoss(alpha=ALPHA, gamma=GAMMA)
                    optimizer = torch.optim.Adam(model_9.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
                    model_9 = train_model(
                        model=model_9,
                        train_loader=train_loader,
                        X_valid=X_val,
                        y_valid=y_val,
                        loss_fn=loss_fn,
                        optimizer=optimizer,
                        epochs=EPOCHS,
                        threshold=0.5,
                        model_name="model_9_Focal_loss"
                    )
                    val = evaluate_model(model_9, X_val, y_val, threshold=0.5, name="val")
                    results.append({"lr": LR, "gamma": GAMMA, "alpha": ALPHA, "dropout": DROPOUT_COEF, "weight_decay": WEIGHT_DECAY, "profit": val["profit"], "roc_auc": val["roc_auc"]})

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9077
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0425 | Val ROC-AUC: 0.9077 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9442
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0178 | Val ROC-AUC: 0.9442 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9665
Precision: 0.3953
Recall: 0.8095
F0.5-score: 0.4404
Profit: -585

Эпоха 3 | Train Loss: 0.0136 | Val ROC-AUC: 0.9665 | Val Profit: -585
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9685
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 4 | Train Loss: 0.0118 | Val ROC-AUC: 0.9685 | Val Profit: -375
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9639
Precision: 0.5
Recall: 0.7619
F0.5-score: 0.5369
Profit: -345

Эпоха 5 | Train Loss: 0.0114 | Val ROC-AUC: 0.9639 | Val Profit: -345
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9722
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 6 | Train Loss: 0.0110 | Val ROC-AUC: 0.9722 | Val Profit: -280
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9836
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 7 | Train Loss: 0.0108 | Val ROC-AUC: 0.9836 | Val Profit: -95
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.984
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 8 | Train Loss: 0.0094 | Val ROC-AUC: 0.9840 | Val Profit: -100
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9808
Precision: 0.6538
Recall: 0.8095
F0.5-score: 0.68
Profit: -160

Эпоха 9 | Train Loss: 0.0097 | Val ROC-AUC: 0.9808 | Val Profit: -160
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9775
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 10 | Train Loss: 0.0093 | Val ROC-AUC: 0.9775 | Val Profit: -175
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9799
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 11 | Train Loss: 0.0084 | Val ROC-AUC: 0.9799 | Val Profit: -110
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9789
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 12 | Train Loss: 0.0078 | Val ROC-AUC: 0.9789 | Val Profit: -170
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9734
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 13 | Train Loss: 0.0059 | Val ROC-AUC: 0.9734 | Val Profit: -145
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9795
Precision: 0.4375
Recall: 1.0
F0.5-score: 0.493
Profit: -570

Эпоха 14 | Train Loss: 0.0076 | Val ROC-AUC: 0.9795 | Val Profit: -570
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9803
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 15 | Train Loss: 0.0086 | Val ROC-AUC: 0.9803 | Val Profit: -75
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9801
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 16 | Train Loss: 0.0074 | Val ROC-AUC: 0.9801 | Val Profit: -115
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9749
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 17 | Train Loss: 0.0060 | Val ROC-AUC: 0.9749 | Val Profit: -155
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9752
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 18 | Train Loss: 0.0058 | Val ROC-AUC: 0.9752 | Val Profit: -85
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9865
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 19 | Train Loss: 0.0069 | Val ROC-AUC: 0.9865 | Val Profit: -85
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9462
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 20 | Train Loss: 0.0072 | Val ROC-AUC: 0.9462 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9622
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0058 | Val ROC-AUC: 0.9622 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9879
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.0039 | Val ROC-AUC: 0.9879 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9865
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 23 | Train Loss: 0.0043 | Val ROC-AUC: 0.9865 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9117
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 24 | Train Loss: 0.0057 | Val ROC-AUC: 0.9117 | Val Profit: -115
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9333
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 25 | Train Loss: 0.0050 | Val ROC-AUC: 0.9333 | Val Profit: -100
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9653
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 26 | Train Loss: 0.0039 | Val ROC-AUC: 0.9653 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9895
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 27 | Train Loss: 0.0031 | Val ROC-AUC: 0.9895 | Val Profit: -85
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9915
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 28 | Train Loss: 0.0032 | Val ROC-AUC: 0.9915 | Val Profit: -55
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9635
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 29 | Train Loss: 0.0054 | Val ROC-AUC: 0.9635 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9205
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0038 | Val ROC-AUC: 0.9205 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9915492957746479
val
ROC-AUC: 0.9915
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9203
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0423 | Val ROC-AUC: 0.9203 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9427
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0177 | Val ROC-AUC: 0.9427 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0147 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9439
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0145 | Val ROC-AUC: 0.9439 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0134 | Val ROC-AUC: 0.9725 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9697
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0120 | Val ROC-AUC: 0.9697 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.963
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0115 | Val ROC-AUC: 0.9630 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0119 | Val ROC-AUC: 0.9670 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9472
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0110 | Val ROC-AUC: 0.9472 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0131 | Val ROC-AUC: 0.9665 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0109 | Val ROC-AUC: 0.9665 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9792
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0116 | Val ROC-AUC: 0.9792 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0106 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9796
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 14 | Train Loss: 0.0107 | Val ROC-AUC: 0.9796 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9755
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 15 | Train Loss: 0.0101 | Val ROC-AUC: 0.9755 | Val Profit: -120
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.978
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 16 | Train Loss: 0.0106 | Val ROC-AUC: 0.9780 | Val Profit: -145
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.871
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 17 | Train Loss: 0.0120 | Val ROC-AUC: 0.8710 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.8871
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0106 | Val ROC-AUC: 0.8871 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9763
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 19 | Train Loss: 0.0118 | Val ROC-AUC: 0.9763 | Val Profit: -175
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9767
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 20 | Train Loss: 0.0101 | Val ROC-AUC: 0.9767 | Val Profit: -155
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9807
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 21 | Train Loss: 0.0105 | Val ROC-AUC: 0.9807 | Val Profit: -100
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0093 | Val ROC-AUC: 0.9655 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9728
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 23 | Train Loss: 0.0091 | Val ROC-AUC: 0.9728 | Val Profit: -270
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9714
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 24 | Train Loss: 0.0124 | Val ROC-AUC: 0.9714 | Val Profit: -240
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9776
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 25 | Train Loss: 0.0102 | Val ROC-AUC: 0.9776 | Val Profit: -45
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9764
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 26 | Train Loss: 0.0101 | Val ROC-AUC: 0.9764 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9816
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 27 | Train Loss: 0.0106 | Val ROC-AUC: 0.9816 | Val Profit: -100
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0092 | Val ROC-AUC: 0.9765 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9799
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0086 | Val ROC-AUC: 0.9799 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.983
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 30 | Train Loss: 0.0092 | Val ROC-AUC: 0.9830 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.9829644533869886
val
ROC-AUC: 0.983
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9123
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0421 | Val ROC-AUC: 0.9123 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9626
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0186 | Val ROC-AUC: 0.9626 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.949
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0152 | Val ROC-AUC: 0.9490 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9718
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0147 | Val ROC-AUC: 0.9718 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9716
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0134 | Val ROC-AUC: 0.9716 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9714
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0120 | Val ROC-AUC: 0.9714 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0126 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9748
Precision: 0.3774
Recall: 0.9524
F0.5-score: 0.4292
Profit: -730

Эпоха 8 | Train Loss: 0.0124 | Val ROC-AUC: 0.9748 | Val Profit: -730
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.972
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 9 | Train Loss: 0.0122 | Val ROC-AUC: 0.9720 | Val Profit: -95
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9783
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 10 | Train Loss: 0.0120 | Val ROC-AUC: 0.9783 | Val Profit: -250
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9785
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 11 | Train Loss: 0.0114 | Val ROC-AUC: 0.9785 | Val Profit: -140
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9824
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0112 | Val ROC-AUC: 0.9824 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.87
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0159 | Val ROC-AUC: 0.8700 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9085
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0136 | Val ROC-AUC: 0.9085 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0135 | Val ROC-AUC: 0.9785 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9479
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0130 | Val ROC-AUC: 0.9479 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0130 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9763
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0123 | Val ROC-AUC: 0.9763 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9848
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0121 | Val ROC-AUC: 0.9848 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.938
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0122 | Val ROC-AUC: 0.9380 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0118 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0121 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9886
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0116 | Val ROC-AUC: 0.9886 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9846
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 24 | Train Loss: 0.0110 | Val ROC-AUC: 0.9846 | Val Profit: -85
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9846
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0112 | Val ROC-AUC: 0.9846 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9859
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0114 | Val ROC-AUC: 0.9859 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9909
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0109 | Val ROC-AUC: 0.9909 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9879
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0105 | Val ROC-AUC: 0.9879 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9898
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0113 | Val ROC-AUC: 0.9898 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9894
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 30 | Train Loss: 0.0105 | Val ROC-AUC: 0.9894 | Val Profit: -65

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.990878604963112
val
ROC-AUC: 0.9909
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.918
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0458 | Val ROC-AUC: 0.9180 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9089
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0194 | Val ROC-AUC: 0.9089 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9545
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0150 | Val ROC-AUC: 0.9545 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9551
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0119 | Val ROC-AUC: 0.9551 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0121 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9281
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 6 | Train Loss: 0.0126 | Val ROC-AUC: 0.9281 | Val Profit: -155
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9693
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 7 | Train Loss: 0.0108 | Val ROC-AUC: 0.9693 | Val Profit: -300
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9728
Precision: 0.5161
Recall: 0.7619
F0.5-score: 0.5517
Profit: -320

Эпоха 8 | Train Loss: 0.0093 | Val ROC-AUC: 0.9728 | Val Profit: -320
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.981
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 9 | Train Loss: 0.0070 | Val ROC-AUC: 0.9810 | Val Profit: -140
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.965
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 10 | Train Loss: 0.0082 | Val ROC-AUC: 0.9650 | Val Profit: -200
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9539
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 11 | Train Loss: 0.0065 | Val ROC-AUC: 0.9539 | Val Profit: -270
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9734
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 12 | Train Loss: 0.0067 | Val ROC-AUC: 0.9734 | Val Profit: -200
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9683
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 13 | Train Loss: 0.0049 | Val ROC-AUC: 0.9683 | Val Profit: -135
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9634
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 14 | Train Loss: 0.0044 | Val ROC-AUC: 0.9634 | Val Profit: -130
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.963
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 15 | Train Loss: 0.0033 | Val ROC-AUC: 0.9630 | Val Profit: -190
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9755
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 16 | Train Loss: 0.0055 | Val ROC-AUC: 0.9755 | Val Profit: -245
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9803
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 17 | Train Loss: 0.0041 | Val ROC-AUC: 0.9803 | Val Profit: -75
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9408
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 18 | Train Loss: 0.0029 | Val ROC-AUC: 0.9408 | Val Profit: -140
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9729
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 19 | Train Loss: 0.0025 | Val ROC-AUC: 0.9729 | Val Profit: -160
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9341
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 20 | Train Loss: 0.0028 | Val ROC-AUC: 0.9341 | Val Profit: -115
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9725
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 21 | Train Loss: 0.0043 | Val ROC-AUC: 0.9725 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.918
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 22 | Train Loss: 0.0035 | Val ROC-AUC: 0.9180 | Val Profit: -160
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9717
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 23 | Train Loss: 0.0032 | Val ROC-AUC: 0.9717 | Val Profit: -170
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9706
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 24 | Train Loss: 0.0027 | Val ROC-AUC: 0.9706 | Val Profit: -240
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.962
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 25 | Train Loss: 0.0034 | Val ROC-AUC: 0.9620 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9691
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 26 | Train Loss: 0.0031 | Val ROC-AUC: 0.9691 | Val Profit: -145
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9659
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 27 | Train Loss: 0.0026 | Val ROC-AUC: 0.9659 | Val Profit: -140
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.956
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 28 | Train Loss: 0.0021 | Val ROC-AUC: 0.9560 | Val Profit: -185
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9602
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 29 | Train Loss: 0.0022 | Val ROC-AUC: 0.9602 | Val Profit: -175
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9785
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 30 | Train Loss: 0.0012 | Val ROC-AUC: 0.9785 | Val Profit: -145

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9809523809523809
val
ROC-AUC: 0.981
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.917
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0455 | Val ROC-AUC: 0.9170 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9572
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 2 | Train Loss: 0.0203 | Val ROC-AUC: 0.9572 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9494
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0152 | Val ROC-AUC: 0.9494 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0129 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9423
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0133 | Val ROC-AUC: 0.9423 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9576
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0138 | Val ROC-AUC: 0.9576 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9723
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0125 | Val ROC-AUC: 0.9723 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0107 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9681
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0103 | Val ROC-AUC: 0.9681 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.8557
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0093 | Val ROC-AUC: 0.8557 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9512
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0095 | Val ROC-AUC: 0.9512 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9542
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0113 | Val ROC-AUC: 0.9542 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0118 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9628
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 14 | Train Loss: 0.0091 | Val ROC-AUC: 0.9628 | Val Profit: -140
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9768
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 15 | Train Loss: 0.0080 | Val ROC-AUC: 0.9768 | Val Profit: -125
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9755
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 16 | Train Loss: 0.0084 | Val ROC-AUC: 0.9755 | Val Profit: -125
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9805
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 17 | Train Loss: 0.0070 | Val ROC-AUC: 0.9805 | Val Profit: -80
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.932
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 18 | Train Loss: 0.0070 | Val ROC-AUC: 0.9320 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9718
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 19 | Train Loss: 0.0074 | Val ROC-AUC: 0.9718 | Val Profit: -205
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9777
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 20 | Train Loss: 0.0065 | Val ROC-AUC: 0.9777 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9302
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 21 | Train Loss: 0.0066 | Val ROC-AUC: 0.9302 | Val Profit: -160
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9789
Precision: 0.6364
Recall: 0.6667
F0.5-score: 0.6422
Profit: -165

Эпоха 22 | Train Loss: 0.0084 | Val ROC-AUC: 0.9789 | Val Profit: -165
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9714
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 23 | Train Loss: 0.0070 | Val ROC-AUC: 0.9714 | Val Profit: -80
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8828
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0053 | Val ROC-AUC: 0.8828 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.831
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0045 | Val ROC-AUC: 0.8310 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9708
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 26 | Train Loss: 0.0049 | Val ROC-AUC: 0.9708 | Val Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9796
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 27 | Train Loss: 0.0054 | Val ROC-AUC: 0.9796 | Val Profit: -110
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.97
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 28 | Train Loss: 0.0051 | Val ROC-AUC: 0.9700 | Val Profit: -150
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9759
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 29 | Train Loss: 0.0058 | Val ROC-AUC: 0.9759 | Val Profit: -215
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9753
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 30 | Train Loss: 0.0054 | Val ROC-AUC: 0.9753 | Val Profit: -155

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.9805499664654593
val
ROC-AUC: 0.9805
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9241
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 1 | Train Loss: 0.0466 | Val ROC-AUC: 0.9241 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0221 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9391
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0183 | Val ROC-AUC: 0.9391 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0160 | Val ROC-AUC: 0.9670 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9587
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0149 | Val ROC-AUC: 0.9587 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0143 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9664
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0133 | Val ROC-AUC: 0.9664 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0131 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0129 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9799
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0125 | Val ROC-AUC: 0.9799 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9701
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0119 | Val ROC-AUC: 0.9701 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0115 | Val ROC-AUC: 0.9689 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9726
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0117 | Val ROC-AUC: 0.9726 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9627
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0117 | Val ROC-AUC: 0.9627 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9728
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0113 | Val ROC-AUC: 0.9728 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0108 | Val ROC-AUC: 0.9655 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0108 | Val ROC-AUC: 0.9738 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9761
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.0117 | Val ROC-AUC: 0.9761 | Val Profit: -100

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9614
Precision: 0.42
Recall: 1.0
F0.5-score: 0.4751
Profit: -620

Эпоха 19 | Train Loss: 0.0119 | Val ROC-AUC: 0.9614 | Val Profit: -620
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0104 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0098 | Val ROC-AUC: 0.9791 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9574
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 22 | Train Loss: 0.0105 | Val ROC-AUC: 0.9574 | Val Profit: -280
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9801
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 23 | Train Loss: 0.0110 | Val ROC-AUC: 0.9801 | Val Profit: -160
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0100 | Val ROC-AUC: 0.9748 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9708
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 25 | Train Loss: 0.0095 | Val ROC-AUC: 0.9708 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9769
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0094 | Val ROC-AUC: 0.9769 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.974
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 27 | Train Loss: 0.0096 | Val ROC-AUC: 0.9740 | Val Profit: -240
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9755
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 28 | Train Loss: 0.0092 | Val ROC-AUC: 0.9755 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9824
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0083 | Val ROC-AUC: 0.9824 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9685
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 30 | Train Loss: 0.0084 | Val ROC-AUC: 0.9685 | Val Profit: -300

Лучшая эпоха для model_9_Focal_loss: 29
Лучший ROC-AUC: 0.9824279007377599
val
ROC-AUC: 0.9824
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 1 | Train Loss: 0.0472 | Val ROC-AUC: 0.9411 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0209 | Val ROC-AUC: 0.9510 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9512
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0154 | Val ROC-AUC: 0.9512 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0126 | Val ROC-AUC: 0.9563 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9622
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0113 | Val ROC-AUC: 0.9622 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0106 | Val ROC-AUC: 0.9594 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9367
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0105 | Val ROC-AUC: 0.9367 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9249
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0099 | Val ROC-AUC: 0.9249 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9239
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0101 | Val ROC-AUC: 0.9239 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9539
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0104 | Val ROC-AUC: 0.9539 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9697
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0085 | Val ROC-AUC: 0.9697 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0073 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9657
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 13 | Train Loss: 0.0069 | Val ROC-AUC: 0.9657 | Val Profit: -95
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.87
Precision: 0.2857
Recall: 0.0952
F0.5-score: 0.2041
Profit: -210

Эпоха 14 | Train Loss: 0.0071 | Val ROC-AUC: 0.8700 | Val Profit: -210
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9545
Precision: 0.4
Recall: 0.4762
F0.5-score: 0.4132
Profit: -380

Эпоха 15 | Train Loss: 0.0078 | Val ROC-AUC: 0.9545 | Val Profit: -380
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9537
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 16 | Train Loss: 0.0077 | Val ROC-AUC: 0.9537 | Val Profit: -355
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9462
Precision: 0.4
Recall: 0.2857
F0.5-score: 0.3704
Profit: -270

Эпоха 17 | Train Loss: 0.0068 | Val ROC-AUC: 0.9462 | Val Profit: -270
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9331
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 18 | Train Loss: 0.0056 | Val ROC-AUC: 0.9331 | Val Profit: -85
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9516
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 19 | Train Loss: 0.0042 | Val ROC-AUC: 0.9516 | Val Profit: -65
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9127
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 20 | Train Loss: 0.0038 | Val ROC-AUC: 0.9127 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9421
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 21 | Train Loss: 0.0036 | Val ROC-AUC: 0.9421 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0031 | Val ROC-AUC: 0.8812 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.893
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0029 | Val ROC-AUC: 0.8930 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.896
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.0028 | Val ROC-AUC: 0.8960 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.8985
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 25 | Train Loss: 0.0027 | Val ROC-AUC: 0.8985 | Val Profit: -90
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9108
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 26 | Train Loss: 0.0026 | Val ROC-AUC: 0.9108 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9112
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 27 | Train Loss: 0.0025 | Val ROC-AUC: 0.9112 | Val Profit: -115
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9099
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 28 | Train Loss: 0.0024 | Val ROC-AUC: 0.9099 | Val Profit: -90
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9089
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 29 | Train Loss: 0.0023 | Val ROC-AUC: 0.9089 | Val Profit: -90
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9078
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 30 | Train Loss: 0.0023 | Val ROC-AUC: 0.9078 | Val Profit: -90

Лучшая эпоха для model_9_Focal_loss: 12
Лучший ROC-AUC: 0.9709590878604963
val
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9325
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0475 | Val ROC-AUC: 0.9325 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9568
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0219 | Val ROC-AUC: 0.9568 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.936
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0157 | Val ROC-AUC: 0.9360 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9528
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0139 | Val ROC-AUC: 0.9528 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0126 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9586
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0113 | Val ROC-AUC: 0.9586 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9101
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0120 | Val ROC-AUC: 0.9101 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9352
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0119 | Val ROC-AUC: 0.9352 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0107 | Val ROC-AUC: 0.9544 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0095 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.8893
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0091 | Val ROC-AUC: 0.8893 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8878
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0092 | Val ROC-AUC: 0.8878 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9632
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0104 | Val ROC-AUC: 0.9632 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9712
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 14 | Train Loss: 0.0101 | Val ROC-AUC: 0.9712 | Val Profit: -100
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9637
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 15 | Train Loss: 0.0082 | Val ROC-AUC: 0.9637 | Val Profit: -140
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9746
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 16 | Train Loss: 0.0069 | Val ROC-AUC: 0.9746 | Val Profit: -150
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9741
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 17 | Train Loss: 0.0063 | Val ROC-AUC: 0.9741 | Val Profit: -170
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9673
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0059 | Val ROC-AUC: 0.9673 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9426
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 19 | Train Loss: 0.0062 | Val ROC-AUC: 0.9426 | Val Profit: -210
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9666
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 20 | Train Loss: 0.0062 | Val ROC-AUC: 0.9666 | Val Profit: -275
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.8922
Precision: 0.32
Recall: 0.381
F0.5-score: 0.3306
Profit: -450

Эпоха 21 | Train Loss: 0.0084 | Val ROC-AUC: 0.8922 | Val Profit: -450
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9702
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 22 | Train Loss: 0.0088 | Val ROC-AUC: 0.9702 | Val Profit: -360
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9718
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 23 | Train Loss: 0.0081 | Val ROC-AUC: 0.9718 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9575
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 24 | Train Loss: 0.0058 | Val ROC-AUC: 0.9575 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0059 | Val ROC-AUC: 0.9748 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9654
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 26 | Train Loss: 0.0043 | Val ROC-AUC: 0.9654 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9594
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 27 | Train Loss: 0.0043 | Val ROC-AUC: 0.9594 | Val Profit: -265
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.963
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 28 | Train Loss: 0.0048 | Val ROC-AUC: 0.9630 | Val Profit: -175
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9634
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 29 | Train Loss: 0.0044 | Val ROC-AUC: 0.9634 | Val Profit: -135
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9665
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0037 | Val ROC-AUC: 0.9665 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9747820254862507
val
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8601
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0487 | Val ROC-AUC: 0.8601 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9305
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0242 | Val ROC-AUC: 0.9305 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9387
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0187 | Val ROC-AUC: 0.9387 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9311
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0171 | Val ROC-AUC: 0.9311 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0163 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.8989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0146 | Val ROC-AUC: 0.8989 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.8802
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0131 | Val ROC-AUC: 0.8802 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9673
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0125 | Val ROC-AUC: 0.9673 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0128 | Val ROC-AUC: 0.9608 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9352
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0138 | Val ROC-AUC: 0.9352 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9591
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0147 | Val ROC-AUC: 0.9591 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0124 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0116 | Val ROC-AUC: 0.9543 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9658
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0118 | Val ROC-AUC: 0.9658 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0105 | Val ROC-AUC: 0.9730 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0109 | Val ROC-AUC: 0.9516 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0114 | Val ROC-AUC: 0.8967 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9659
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0117 | Val ROC-AUC: 0.9659 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9641
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0098 | Val ROC-AUC: 0.9641 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9662
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 20 | Train Loss: 0.0096 | Val ROC-AUC: 0.9662 | Val Profit: -185
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.959
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 21 | Train Loss: 0.0099 | Val ROC-AUC: 0.9590 | Val Profit: -115
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9681
Precision: 0.4865
Recall: 0.8571
F0.5-score: 0.5325
Profit: -400

Эпоха 22 | Train Loss: 0.0100 | Val ROC-AUC: 0.9681 | Val Profit: -400
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9659
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 23 | Train Loss: 0.0095 | Val ROC-AUC: 0.9659 | Val Profit: -285
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9702
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 24 | Train Loss: 0.0103 | Val ROC-AUC: 0.9702 | Val Profit: -200
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9665
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 25 | Train Loss: 0.0101 | Val ROC-AUC: 0.9665 | Val Profit: -160
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9687
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 26 | Train Loss: 0.0086 | Val ROC-AUC: 0.9687 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0078 | Val ROC-AUC: 0.9725 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9547
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 28 | Train Loss: 0.0097 | Val ROC-AUC: 0.9547 | Val Profit: -190

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9679
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 29 | Train Loss: 0.0093 | Val ROC-AUC: 0.9679 | Val Profit: -170
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.96
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 30 | Train Loss: 0.0097 | Val ROC-AUC: 0.9600 | Val Profit: -215

Лучшая эпоха для model_9_Focal_loss: 15
Лучший ROC-AUC: 0.9730382293762575
val
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9288
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0849 | Val ROC-AUC: 0.9288 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9164
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0374 | Val ROC-AUC: 0.9164 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0292 | Val ROC-AUC: 0.9610 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9653
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 4 | Train Loss: 0.0250 | Val ROC-AUC: 0.9653 | Val Profit: -385
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9761
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 5 | Train Loss: 0.0197 | Val ROC-AUC: 0.9761 | Val Profit: -350
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9649
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 6 | Train Loss: 0.0202 | Val ROC-AUC: 0.9649 | Val Profit: -245
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9781
Precision: 0.6538
Recall: 0.8095
F0.5-score: 0.68
Profit: -160

Эпоха 7 | Train Loss: 0.0183 | Val ROC-AUC: 0.9781 | Val Profit: -160
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9767
Precision: 0.6538
Recall: 0.8095
F0.5-score: 0.68
Profit: -160

Эпоха 8 | Train Loss: 0.0205 | Val ROC-AUC: 0.9767 | Val Profit: -160
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9795
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 9 | Train Loss: 0.0202 | Val ROC-AUC: 0.9795 | Val Profit: -240
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9757
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 10 | Train Loss: 0.0185 | Val ROC-AUC: 0.9757 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9679
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 11 | Train Loss: 0.0156 | Val ROC-AUC: 0.9679 | Val Profit: -100
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9673
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 12 | Train Loss: 0.0159 | Val ROC-AUC: 0.9673 | Val Profit: -90
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9734
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 13 | Train Loss: 0.0186 | Val ROC-AUC: 0.9734 | Val Profit: -130
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9824
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 14 | Train Loss: 0.0135 | Val ROC-AUC: 0.9824 | Val Profit: -60
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9784
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 15 | Train Loss: 0.0141 | Val ROC-AUC: 0.9784 | Val Profit: -115
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9852
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 16 | Train Loss: 0.0108 | Val ROC-AUC: 0.9852 | Val Profit: -90
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.982
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 17 | Train Loss: 0.0119 | Val ROC-AUC: 0.9820 | Val Profit: -65
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9721
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 18 | Train Loss: 0.0128 | Val ROC-AUC: 0.9721 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9651
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 19 | Train Loss: 0.0133 | Val ROC-AUC: 0.9651 | Val Profit: -100
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9697
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 20 | Train Loss: 0.0106 | Val ROC-AUC: 0.9697 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.967
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 21 | Train Loss: 0.0109 | Val ROC-AUC: 0.9670 | Val Profit: -140
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9549
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.0109 | Val ROC-AUC: 0.9549 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9729
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 23 | Train Loss: 0.0103 | Val ROC-AUC: 0.9729 | Val Profit: -160
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9459
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 24 | Train Loss: 0.0113 | Val ROC-AUC: 0.9459 | Val Profit: -165
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9797
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 25 | Train Loss: 0.0120 | Val ROC-AUC: 0.9797 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.97
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 26 | Train Loss: 0.0115 | Val ROC-AUC: 0.9700 | Val Profit: -70
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9594
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 27 | Train Loss: 0.0097 | Val ROC-AUC: 0.9594 | Val Profit: -70
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9473
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 28 | Train Loss: 0.0125 | Val ROC-AUC: 0.9473 | Val Profit: -85
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9329
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0081 | Val ROC-AUC: 0.9329 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9696
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 30 | Train Loss: 0.0078 | Val ROC-AUC: 0.9696 | Val Profit: -55

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9852448021462106
val
ROC-AUC: 0.9852
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8946
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0846 | Val ROC-AUC: 0.8946 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9201
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0368 | Val ROC-AUC: 0.9201 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9583
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0299 | Val ROC-AUC: 0.9583 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9383
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0267 | Val ROC-AUC: 0.9383 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9442
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0296 | Val ROC-AUC: 0.9442 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9726
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0260 | Val ROC-AUC: 0.9726 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9215
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0221 | Val ROC-AUC: 0.9215 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0241 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0235 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9822
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0217 | Val ROC-AUC: 0.9822 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9107
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0219 | Val ROC-AUC: 0.9107 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9797
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0262 | Val ROC-AUC: 0.9797 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9115
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0201 | Val ROC-AUC: 0.9115 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9756
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0201 | Val ROC-AUC: 0.9756 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9764
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 15 | Train Loss: 0.0220 | Val ROC-AUC: 0.9764 | Val Profit: -150
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9846
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 16 | Train Loss: 0.0203 | Val ROC-AUC: 0.9846 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9722
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 17 | Train Loss: 0.0187 | Val ROC-AUC: 0.9722 | Val Profit: -120
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.927
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0174 | Val ROC-AUC: 0.9270 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9435
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0174 | Val ROC-AUC: 0.9435 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9763
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 20 | Train Loss: 0.0179 | Val ROC-AUC: 0.9763 | Val Profit: -275
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9813
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 21 | Train Loss: 0.0201 | Val ROC-AUC: 0.9813 | Val Profit: -100
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9812
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 22 | Train Loss: 0.0177 | Val ROC-AUC: 0.9812 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9437
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0177 | Val ROC-AUC: 0.9437 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9657
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 24 | Train Loss: 0.0171 | Val ROC-AUC: 0.9657 | Val Profit: -70
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9832
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 25 | Train Loss: 0.0197 | Val ROC-AUC: 0.9832 | Val Profit: -80
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.986
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 26 | Train Loss: 0.0169 | Val ROC-AUC: 0.9860 | Val Profit: -85
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.93
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0165 | Val ROC-AUC: 0.9300 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9784
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 28 | Train Loss: 0.0167 | Val ROC-AUC: 0.9784 | Val Profit: -175
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.98
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0155 | Val ROC-AUC: 0.9800 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9812
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 30 | Train Loss: 0.0171 | Val ROC-AUC: 0.9812 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9859825620389
val
ROC-AUC: 0.986
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9288
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0842 | Val ROC-AUC: 0.9288 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.8895
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0373 | Val ROC-AUC: 0.8895 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9678
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0324 | Val ROC-AUC: 0.9678 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9504
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0313 | Val ROC-AUC: 0.9504 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9603
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0293 | Val ROC-AUC: 0.9603 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0293 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.8986
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0282 | Val ROC-AUC: 0.8986 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0300 | Val ROC-AUC: 0.9599 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9532
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0267 | Val ROC-AUC: 0.9532 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0275 | Val ROC-AUC: 0.9803 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9626
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0273 | Val ROC-AUC: 0.9626 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9781
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0270 | Val ROC-AUC: 0.9781 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0254 | Val ROC-AUC: 0.9650 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0244 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0250 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0247 | Val ROC-AUC: 0.9812 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9814
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0236 | Val ROC-AUC: 0.9814 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9867
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0234 | Val ROC-AUC: 0.9867 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.981
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0211 | Val ROC-AUC: 0.9810 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9847
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 20 | Train Loss: 0.0233 | Val ROC-AUC: 0.9847 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9882
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0216 | Val ROC-AUC: 0.9882 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.984
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0207 | Val ROC-AUC: 0.9840 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9847
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 23 | Train Loss: 0.0209 | Val ROC-AUC: 0.9847 | Val Profit: -95
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9898
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0210 | Val ROC-AUC: 0.9898 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9889
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0196 | Val ROC-AUC: 0.9889 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9874
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 26 | Train Loss: 0.0207 | Val ROC-AUC: 0.9874 | Val Profit: -75
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9891
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0209 | Val ROC-AUC: 0.9891 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9869
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0195 | Val ROC-AUC: 0.9869 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9889
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 29 | Train Loss: 0.0187 | Val ROC-AUC: 0.9889 | Val Profit: -50
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9918
Precision: 0.8667
Recall: 0.619
F0.5-score: 0.8025
Profit: -25

Эпоха 30 | Train Loss: 0.0203 | Val ROC-AUC: 0.9918 | Val Profit: -25

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.9918175720992621
val
ROC-AUC: 0.9918
Precision: 0.8667
Recall: 0.619
F0.5-score: 0.8025
Profit: -25

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9112
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0915 | Val ROC-AUC: 0.9112 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9194
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0382 | Val ROC-AUC: 0.9194 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.956
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0283 | Val ROC-AUC: 0.9560 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0273 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9592
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0241 | Val ROC-AUC: 0.9592 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9643
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 6 | Train Loss: 0.0217 | Val ROC-AUC: 0.9643 | Val Profit: -310
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9673
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 7 | Train Loss: 0.0181 | Val ROC-AUC: 0.9673 | Val Profit: -235
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9624
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 8 | Train Loss: 0.0159 | Val ROC-AUC: 0.9624 | Val Profit: -230
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9785
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 9 | Train Loss: 0.0142 | Val ROC-AUC: 0.9785 | Val Profit: -260
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9257
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 10 | Train Loss: 0.0134 | Val ROC-AUC: 0.9257 | Val Profit: -230
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9698
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 11 | Train Loss: 0.0151 | Val ROC-AUC: 0.9698 | Val Profit: -225
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9537
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 12 | Train Loss: 0.0107 | Val ROC-AUC: 0.9537 | Val Profit: -310
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9639
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 13 | Train Loss: 0.0111 | Val ROC-AUC: 0.9639 | Val Profit: -165
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9733
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 14 | Train Loss: 0.0106 | Val ROC-AUC: 0.9733 | Val Profit: -230
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9533
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 15 | Train Loss: 0.0095 | Val ROC-AUC: 0.9533 | Val Profit: -145
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.8596
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 16 | Train Loss: 0.0065 | Val ROC-AUC: 0.8596 | Val Profit: -185
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9691
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 17 | Train Loss: 0.0098 | Val ROC-AUC: 0.9691 | Val Profit: -215
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9178
Precision: 0.3
Recall: 0.1429
F0.5-score: 0.2459
Profit: -250

Эпоха 18 | Train Loss: 0.0059 | Val ROC-AUC: 0.9178 | Val Profit: -250
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.8212
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 19 | Train Loss: 0.0048 | Val ROC-AUC: 0.8212 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9203
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 20 | Train Loss: 0.0046 | Val ROC-AUC: 0.9203 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.8612
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 21 | Train Loss: 0.0055 | Val ROC-AUC: 0.8612 | Val Profit: -165
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9726
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 22 | Train Loss: 0.0049 | Val ROC-AUC: 0.9726 | Val Profit: -235
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8237
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 23 | Train Loss: 0.0058 | Val ROC-AUC: 0.8237 | Val Profit: -155
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8597
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 24 | Train Loss: 0.0038 | Val ROC-AUC: 0.8597 | Val Profit: -60
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9056
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 25 | Train Loss: 0.0054 | Val ROC-AUC: 0.9056 | Val Profit: -235
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9738
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 26 | Train Loss: 0.0087 | Val ROC-AUC: 0.9738 | Val Profit: -210
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9088
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 27 | Train Loss: 0.0088 | Val ROC-AUC: 0.9088 | Val Profit: -200
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9302
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 28 | Train Loss: 0.0061 | Val ROC-AUC: 0.9302 | Val Profit: -240
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.6656
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0064 | Val ROC-AUC: 0.6656 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8306
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 30 | Train Loss: 0.0038 | Val ROC-AUC: 0.8306 | Val Profit: -150

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9785378940308518
val
ROC-AUC: 0.9785
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9249
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0915 | Val ROC-AUC: 0.9249 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9495
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0377 | Val ROC-AUC: 0.9495 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9439
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0279 | Val ROC-AUC: 0.9439 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9392
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0280 | Val ROC-AUC: 0.9392 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9427
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0239 | Val ROC-AUC: 0.9427 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9393
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0258 | Val ROC-AUC: 0.9393 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0222 | Val ROC-AUC: 0.9667 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9702
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0209 | Val ROC-AUC: 0.9702 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9649
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0218 | Val ROC-AUC: 0.9649 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9623
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0190 | Val ROC-AUC: 0.9623 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9286
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0179 | Val ROC-AUC: 0.9286 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9612
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0173 | Val ROC-AUC: 0.9612 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9526
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 13 | Train Loss: 0.0156 | Val ROC-AUC: 0.9526 | Val Profit: -215
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.956
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 14 | Train Loss: 0.0258 | Val ROC-AUC: 0.9560 | Val Profit: -605
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9771
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 15 | Train Loss: 0.0201 | Val ROC-AUC: 0.9771 | Val Profit: -120
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9706
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 16 | Train Loss: 0.0170 | Val ROC-AUC: 0.9706 | Val Profit: -230
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 17 | Train Loss: 0.0185 | Val ROC-AUC: 0.9812 | Val Profit: -130
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.975
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 18 | Train Loss: 0.0155 | Val ROC-AUC: 0.9750 | Val Profit: -175
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.978
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 19 | Train Loss: 0.0139 | Val ROC-AUC: 0.9780 | Val Profit: -110
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9705
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 20 | Train Loss: 0.0126 | Val ROC-AUC: 0.9705 | Val Profit: -210
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9704
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 21 | Train Loss: 0.0139 | Val ROC-AUC: 0.9704 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9649
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 22 | Train Loss: 0.0154 | Val ROC-AUC: 0.9649 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9719
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 23 | Train Loss: 0.0149 | Val ROC-AUC: 0.9719 | Val Profit: -190
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9767
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 24 | Train Loss: 0.0129 | Val ROC-AUC: 0.9767 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9785
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 25 | Train Loss: 0.0103 | Val ROC-AUC: 0.9785 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9378
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 26 | Train Loss: 0.0092 | Val ROC-AUC: 0.9378 | Val Profit: -80
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9154
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 27 | Train Loss: 0.0101 | Val ROC-AUC: 0.9154 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9641
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 28 | Train Loss: 0.0084 | Val ROC-AUC: 0.9641 | Val Profit: -205
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9418
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 29 | Train Loss: 0.0112 | Val ROC-AUC: 0.9418 | Val Profit: -160
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9661
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 30 | Train Loss: 0.0096 | Val ROC-AUC: 0.9661 | Val Profit: -175

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.9812206572769953
val
ROC-AUC: 0.9812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9521
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0918 | Val ROC-AUC: 0.9521 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0393 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9604
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0318 | Val ROC-AUC: 0.9604 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0307 | Val ROC-AUC: 0.9598 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0287 | Val ROC-AUC: 0.9543 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9713
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0256 | Val ROC-AUC: 0.9713 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9674
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0245 | Val ROC-AUC: 0.9674 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9447
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0248 | Val ROC-AUC: 0.9447 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0241 | Val ROC-AUC: 0.9730 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9784
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0235 | Val ROC-AUC: 0.9784 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0225 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0220 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9647
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0212 | Val ROC-AUC: 0.9647 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9741
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0198 | Val ROC-AUC: 0.9741 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.98
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0219 | Val ROC-AUC: 0.9800 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9744
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 16 | Train Loss: 0.0209 | Val ROC-AUC: 0.9744 | Val Profit: -95
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 17 | Train Loss: 0.0194 | Val ROC-AUC: 0.9696 | Val Profit: -130
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9749
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0165 | Val ROC-AUC: 0.9749 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9622
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 19 | Train Loss: 0.0188 | Val ROC-AUC: 0.9622 | Val Profit: -325
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 20 | Train Loss: 0.0182 | Val ROC-AUC: 0.9737 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9726
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0187 | Val ROC-AUC: 0.9726 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9746
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 22 | Train Loss: 0.0190 | Val ROC-AUC: 0.9746 | Val Profit: -215
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9807
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0178 | Val ROC-AUC: 0.9807 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0159 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9763
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0144 | Val ROC-AUC: 0.9763 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0148 | Val ROC-AUC: 0.9773 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0161 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9663
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 28 | Train Loss: 0.0151 | Val ROC-AUC: 0.9663 | Val Profit: -115
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9704
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 29 | Train Loss: 0.0163 | Val ROC-AUC: 0.9704 | Val Profit: -150
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0139 | Val ROC-AUC: 0.9745 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9806841046277666

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

val
ROC-AUC: 0.9807
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9184
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0958 | Val ROC-AUC: 0.9184 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.94
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0423 | Val ROC-AUC: 0.9400 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9573
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0294 | Val ROC-AUC: 0.9573 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9634
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0250 | Val ROC-AUC: 0.9634 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.943
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0241 | Val ROC-AUC: 0.9430 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9474
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0244 | Val ROC-AUC: 0.9474 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0207 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9645
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0176 | Val ROC-AUC: 0.9645 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.8318
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0161 | Val ROC-AUC: 0.8318 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9417
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0173 | Val ROC-AUC: 0.9417 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0172 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9569
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 12 | Train Loss: 0.0168 | Val ROC-AUC: 0.9569 | Val Profit: -140
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.8829
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0152 | Val ROC-AUC: 0.8829 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9713
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 14 | Train Loss: 0.0138 | Val ROC-AUC: 0.9713 | Val Profit: -130
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9639
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 15 | Train Loss: 0.0130 | Val ROC-AUC: 0.9639 | Val Profit: -190
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9791
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 16 | Train Loss: 0.0106 | Val ROC-AUC: 0.9791 | Val Profit: -135
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9765
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 17 | Train Loss: 0.0107 | Val ROC-AUC: 0.9765 | Val Profit: -155
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9733
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 18 | Train Loss: 0.0094 | Val ROC-AUC: 0.9733 | Val Profit: -60
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9753
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 19 | Train Loss: 0.0086 | Val ROC-AUC: 0.9753 | Val Profit: -125
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9571
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 20 | Train Loss: 0.0074 | Val ROC-AUC: 0.9571 | Val Profit: -90
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9702
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 21 | Train Loss: 0.0064 | Val ROC-AUC: 0.9702 | Val Profit: -90
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9627
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 22 | Train Loss: 0.0060 | Val ROC-AUC: 0.9627 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9658
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 23 | Train Loss: 0.0056 | Val ROC-AUC: 0.9658 | Val Profit: -115
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9679
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 24 | Train Loss: 0.0053 | Val ROC-AUC: 0.9679 | Val Profit: -125
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9682
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 25 | Train Loss: 0.0051 | Val ROC-AUC: 0.9682 | Val Profit: -125
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9682
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 26 | Train Loss: 0.0049 | Val ROC-AUC: 0.9682 | Val Profit: -125
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9683
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 27 | Train Loss: 0.0048 | Val ROC-AUC: 0.9683 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9685
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 28 | Train Loss: 0.0046 | Val ROC-AUC: 0.9685 | Val Profit: -125
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9682
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 29 | Train Loss: 0.0045 | Val ROC-AUC: 0.9682 | Val Profit: -125
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9682
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 30 | Train Loss: 0.0044 | Val ROC-AUC: 0.9682 | Val Profit: -125

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9791415157612341
val
ROC-AUC: 0.9791
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0943 | Val ROC-AUC: 0.8785 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9481
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0403 | Val ROC-AUC: 0.9481 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0306 | Val ROC-AUC: 0.9602 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0259 | Val ROC-AUC: 0.9543 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.8924
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0243 | Val ROC-AUC: 0.8924 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0232 | Val ROC-AUC: 0.9555 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0205 | Val ROC-AUC: 0.9575 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0193 | Val ROC-AUC: 0.9685 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.95
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0195 | Val ROC-AUC: 0.9500 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9606
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0166 | Val ROC-AUC: 0.9606 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.8785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0149 | Val ROC-AUC: 0.8785 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9578
Precision: 0.4194
Recall: 0.619
F0.5-score: 0.4483
Profit: -425

Эпоха 12 | Train Loss: 0.0164 | Val ROC-AUC: 0.9578 | Val Profit: -425
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9586
Precision: 0.4348
Recall: 0.4762
F0.5-score: 0.4425
Profit: -330

Эпоха 13 | Train Loss: 0.0157 | Val ROC-AUC: 0.9586 | Val Profit: -330

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9528
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 14 | Train Loss: 0.0166 | Val ROC-AUC: 0.9528 | Val Profit: -320
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9457
Precision: 0.4138
Recall: 0.5714
F0.5-score: 0.438
Profit: -410

Эпоха 15 | Train Loss: 0.0167 | Val ROC-AUC: 0.9457 | Val Profit: -410
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9565
Precision: 0.4054
Recall: 0.7143
F0.5-score: 0.4438
Profit: -505

Эпоха 16 | Train Loss: 0.0209 | Val ROC-AUC: 0.9565 | Val Profit: -505
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9179
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 17 | Train Loss: 0.0164 | Val ROC-AUC: 0.9179 | Val Profit: -170
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.967
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 18 | Train Loss: 0.0127 | Val ROC-AUC: 0.9670 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9612
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 19 | Train Loss: 0.0105 | Val ROC-AUC: 0.9612 | Val Profit: -125
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9451
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 20 | Train Loss: 0.0103 | Val ROC-AUC: 0.9451 | Val Profit: -225
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9412
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 21 | Train Loss: 0.0101 | Val ROC-AUC: 0.9412 | Val Profit: -265
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9591
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 22 | Train Loss: 0.0123 | Val ROC-AUC: 0.9591 | Val Profit: -375
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9571
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 23 | Train Loss: 0.0107 | Val ROC-AUC: 0.9571 | Val Profit: -185
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.875
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 24 | Train Loss: 0.0125 | Val ROC-AUC: 0.8750 | Val Profit: -175
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9266
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 25 | Train Loss: 0.0093 | Val ROC-AUC: 0.9266 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9315
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 26 | Train Loss: 0.0071 | Val ROC-AUC: 0.9315 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9542
Precision: 0.4348
Recall: 0.4762
F0.5-score: 0.4425
Profit: -330

Эпоха 27 | Train Loss: 0.0088 | Val ROC-AUC: 0.9542 | Val Profit: -330
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9683
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 28 | Train Loss: 0.0087 | Val ROC-AUC: 0.9683 | Val Profit: -170
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9243
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 29 | Train Loss: 0.0078 | Val ROC-AUC: 0.9243 | Val Profit: -220
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8869
Precision: 0.4286
Recall: 0.4286
F0.5-score: 0.4286
Profit: -315

Эпоха 30 | Train Loss: 0.0063 | Val ROC-AUC: 0.8869 | Val Profit: -315

Лучшая эпоха для model_9_Focal_loss: 8
Лучший ROC-AUC: 0.9684775318578136
val
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0964 | Val ROC-AUC: 0.8669 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9539
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0458 | Val ROC-AUC: 0.9539 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0330 | Val ROC-AUC: 0.9742 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9121
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0295 | Val ROC-AUC: 0.9121 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9632
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0297 | Val ROC-AUC: 0.9632 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0269 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9722
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0291 | Val ROC-AUC: 0.9722 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0259 | Val ROC-AUC: 0.9596 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0243 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9551
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0227 | Val ROC-AUC: 0.9551 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0221 | Val ROC-AUC: 0.9616 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9729
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0229 | Val ROC-AUC: 0.9729 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9691
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0229 | Val ROC-AUC: 0.9691 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0222 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0213 | Val ROC-AUC: 0.9679 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9732
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0187 | Val ROC-AUC: 0.9732 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9579
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 17 | Train Loss: 0.0198 | Val ROC-AUC: 0.9579 | Val Profit: -110
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9571
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 18 | Train Loss: 0.0196 | Val ROC-AUC: 0.9571 | Val Profit: -125

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9677
Precision: 0.4444
Recall: 0.9524
F0.5-score: 0.4975
Profit: -530

Эпоха 19 | Train Loss: 0.0198 | Val ROC-AUC: 0.9677 | Val Profit: -530
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9803
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.0200 | Val ROC-AUC: 0.9803 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9759
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0163 | Val ROC-AUC: 0.9759 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9768
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0152 | Val ROC-AUC: 0.9768 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0154 | Val ROC-AUC: 0.9689 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9787
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 24 | Train Loss: 0.0160 | Val ROC-AUC: 0.9787 | Val Profit: -85
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9755
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 25 | Train Loss: 0.0158 | Val ROC-AUC: 0.9755 | Val Profit: -225
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9606
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 26 | Train Loss: 0.0166 | Val ROC-AUC: 0.9606 | Val Profit: -165
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0157 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9704
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 28 | Train Loss: 0.0164 | Val ROC-AUC: 0.9704 | Val Profit: -360

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9738
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 29 | Train Loss: 0.0146 | Val ROC-AUC: 0.9738 | Val Profit: -150
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9732
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 30 | Train Loss: 0.0163 | Val ROC-AUC: 0.9732 | Val Profit: -65

Лучшая эпоха для model_9_Focal_loss: 20
Лучший ROC-AUC: 0.980281690140845
val
ROC-AUC: 0.9803
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.912
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1678 | Val ROC-AUC: 0.9120 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9592
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0753 | Val ROC-AUC: 0.9592 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9693
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0585 | Val ROC-AUC: 0.9693 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9671
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 4 | Train Loss: 0.0452 | Val ROC-AUC: 0.9671 | Val Profit: -265
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.97
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 5 | Train Loss: 0.0418 | Val ROC-AUC: 0.9700 | Val Profit: -485
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9665
Precision: 0.5161
Recall: 0.7619
F0.5-score: 0.5517
Profit: -320

Эпоха 6 | Train Loss: 0.0481 | Val ROC-AUC: 0.9665 | Val Profit: -320
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9756
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 7 | Train Loss: 0.0470 | Val ROC-AUC: 0.9756 | Val Profit: -245
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9718
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 8 | Train Loss: 0.0368 | Val ROC-AUC: 0.9718 | Val Profit: -185
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9635
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 9 | Train Loss: 0.0392 | Val ROC-AUC: 0.9635 | Val Profit: -100
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9838
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

Эпоха 10 | Train Loss: 0.0381 | Val ROC-AUC: 0.9838 | Val Profit: -80
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9783
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 11 | Train Loss: 0.0297 | Val ROC-AUC: 0.9783 | Val Profit: -130
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9683
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 12 | Train Loss: 0.0236 | Val ROC-AUC: 0.9683 | Val Profit: -135
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9819
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 13 | Train Loss: 0.0224 | Val ROC-AUC: 0.9819 | Val Profit: -70
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9805
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 14 | Train Loss: 0.0261 | Val ROC-AUC: 0.9805 | Val Profit: -260
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9836
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 15 | Train Loss: 0.0354 | Val ROC-AUC: 0.9836 | Val Profit: -85
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9835
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 16 | Train Loss: 0.0278 | Val ROC-AUC: 0.9835 | Val Profit: -130
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 17 | Train Loss: 0.0165 | Val ROC-AUC: 0.9608 | Val Profit: -130
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9807
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 18 | Train Loss: 0.0140 | Val ROC-AUC: 0.9807 | Val Profit: -110
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9867
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 19 | Train Loss: 0.0215 | Val ROC-AUC: 0.9867 | Val Profit: -330
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9839
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 20 | Train Loss: 0.0333 | Val ROC-AUC: 0.9839 | Val Profit: -90
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9866
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 21 | Train Loss: 0.0226 | Val ROC-AUC: 0.9866 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9781
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 22 | Train Loss: 0.0167 | Val ROC-AUC: 0.9781 | Val Profit: -90
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9789
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 23 | Train Loss: 0.0143 | Val ROC-AUC: 0.9789 | Val Profit: -80
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9685
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 24 | Train Loss: 0.0239 | Val ROC-AUC: 0.9685 | Val Profit: -420
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9783
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 25 | Train Loss: 0.0346 | Val ROC-AUC: 0.9783 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9781
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 26 | Train Loss: 0.0214 | Val ROC-AUC: 0.9781 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9757
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 27 | Train Loss: 0.0148 | Val ROC-AUC: 0.9757 | Val Profit: -180
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9839
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 28 | Train Loss: 0.0109 | Val ROC-AUC: 0.9839 | Val Profit: -90
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9434
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 29 | Train Loss: 0.0096 | Val ROC-AUC: 0.9434 | Val Profit: -160
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9848
Precision: 0.9167
Recall: 0.5238
F0.5-score: 0.7971
Profit: -20

Эпоха 30 | Train Loss: 0.0126 | Val ROC-AUC: 0.9848 | Val Profit: -20

Лучшая эпоха для model_9_Focal_loss: 19
Лучший ROC-AUC: 0.9867203219315895
val
ROC-AUC: 0.9867
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.927
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1675 | Val ROC-AUC: 0.9270 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0724 | Val ROC-AUC: 0.9411 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9533
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0559 | Val ROC-AUC: 0.9533 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9654
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0541 | Val ROC-AUC: 0.9654 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9418
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0495 | Val ROC-AUC: 0.9418 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0470 | Val ROC-AUC: 0.9602 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0428 | Val ROC-AUC: 0.9752 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9547
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0451 | Val ROC-AUC: 0.9547 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0457 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0454 | Val ROC-AUC: 0.9679 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0449 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9811
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0416 | Val ROC-AUC: 0.9811 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9446
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0386 | Val ROC-AUC: 0.9446 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9714
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 14 | Train Loss: 0.0401 | Val ROC-AUC: 0.9714 | Val Profit: -150
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9288
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 15 | Train Loss: 0.0408 | Val ROC-AUC: 0.9288 | Val Profit: -130
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.95
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 16 | Train Loss: 0.0366 | Val ROC-AUC: 0.9500 | Val Profit: -110
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9771
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 17 | Train Loss: 0.0383 | Val ROC-AUC: 0.9771 | Val Profit: -180
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9504
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 18 | Train Loss: 0.0367 | Val ROC-AUC: 0.9504 | Val Profit: -110
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9699
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 19 | Train Loss: 0.0354 | Val ROC-AUC: 0.9699 | Val Profit: -100
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9742
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 20 | Train Loss: 0.0353 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.981
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 21 | Train Loss: 0.0335 | Val ROC-AUC: 0.9810 | Val Profit: -65
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9538
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 22 | Train Loss: 0.0361 | Val ROC-AUC: 0.9538 | Val Profit: -140
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.96
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 23 | Train Loss: 0.0352 | Val ROC-AUC: 0.9600 | Val Profit: -140
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9706
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 24 | Train Loss: 0.0331 | Val ROC-AUC: 0.9706 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.976
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 25 | Train Loss: 0.0339 | Val ROC-AUC: 0.9760 | Val Profit: -180
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9292
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 26 | Train Loss: 0.0368 | Val ROC-AUC: 0.9292 | Val Profit: -120
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9812
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 27 | Train Loss: 0.0301 | Val ROC-AUC: 0.9812 | Val Profit: -100
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9697
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 28 | Train Loss: 0.0295 | Val ROC-AUC: 0.9697 | Val Profit: -145
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9811
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 29 | Train Loss: 0.0355 | Val ROC-AUC: 0.9811 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9772
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 30 | Train Loss: 0.0302 | Val ROC-AUC: 0.9772 | Val Profit: -90

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9812206572769953
val
ROC-AUC: 0.9812
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9281
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1660 | Val ROC-AUC: 0.9281 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9488
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0719 | Val ROC-AUC: 0.9488 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9457
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0632 | Val ROC-AUC: 0.9457 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9659
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0576 | Val ROC-AUC: 0.9659 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0518 | Val ROC-AUC: 0.9599 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0503 | Val ROC-AUC: 0.9636 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.8885
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0469 | Val ROC-AUC: 0.8885 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0492 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9362
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0622 | Val ROC-AUC: 0.9362 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9767
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0549 | Val ROC-AUC: 0.9767 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9728
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0509 | Val ROC-AUC: 0.9728 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9732
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0458 | Val ROC-AUC: 0.9732 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0506 | Val ROC-AUC: 0.9795 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0456 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.974
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0459 | Val ROC-AUC: 0.9740 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9695
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0442 | Val ROC-AUC: 0.9695 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9756
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 17 | Train Loss: 0.0433 | Val ROC-AUC: 0.9756 | Val Profit: -135

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9646
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0402 | Val ROC-AUC: 0.9646 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9539
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0511 | Val ROC-AUC: 0.9539 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9842
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0475 | Val ROC-AUC: 0.9842 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9687
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 21 | Train Loss: 0.0395 | Val ROC-AUC: 0.9687 | Val Profit: -155
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9869
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0412 | Val ROC-AUC: 0.9869 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.973
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 23 | Train Loss: 0.0435 | Val ROC-AUC: 0.9730 | Val Profit: -115
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0401 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9832
Precision: 0.6667
Recall: 0.8571
F0.5-score: 0.6977
Profit: -150

Эпоха 25 | Train Loss: 0.0372 | Val ROC-AUC: 0.9832 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.982
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0406 | Val ROC-AUC: 0.9820 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9807
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0373 | Val ROC-AUC: 0.9807 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9866
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0379 | Val ROC-AUC: 0.9866 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9807
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 29 | Train Loss: 0.0356 | Val ROC-AUC: 0.9807 | Val Profit: -115
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9889
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0365 | Val ROC-AUC: 0.9889 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.9888665325285044
val
ROC-AUC: 0.9889
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9182
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1817 | Val ROC-AUC: 0.9182 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0752 | Val ROC-AUC: 0.9344 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9339
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0559 | Val ROC-AUC: 0.9339 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9321
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0509 | Val ROC-AUC: 0.9321 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0521 | Val ROC-AUC: 0.9563 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0446 | Val ROC-AUC: 0.9685 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9573
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0398 | Val ROC-AUC: 0.9573 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9717
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0357 | Val ROC-AUC: 0.9717 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0421 | Val ROC-AUC: 0.9675 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0352 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9659
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0340 | Val ROC-AUC: 0.9659 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9631
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 12 | Train Loss: 0.0310 | Val ROC-AUC: 0.9631 | Val Profit: -165

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9053
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0274 | Val ROC-AUC: 0.9053 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9273
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 14 | Train Loss: 0.0216 | Val ROC-AUC: 0.9273 | Val Profit: -85
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9205
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 15 | Train Loss: 0.0216 | Val ROC-AUC: 0.9205 | Val Profit: -145
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9681
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 16 | Train Loss: 0.0219 | Val ROC-AUC: 0.9681 | Val Profit: -450
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 17 | Train Loss: 0.0302 | Val ROC-AUC: 0.9772 | Val Profit: -140
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9139
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 18 | Train Loss: 0.0281 | Val ROC-AUC: 0.9139 | Val Profit: -385
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9641
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 19 | Train Loss: 0.0290 | Val ROC-AUC: 0.9641 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9561
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 20 | Train Loss: 0.0244 | Val ROC-AUC: 0.9561 | Val Profit: -185
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9709
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0229 | Val ROC-AUC: 0.9709 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.945
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 22 | Train Loss: 0.0164 | Val ROC-AUC: 0.9450 | Val Profit: -140
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8491
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 23 | Train Loss: 0.0137 | Val ROC-AUC: 0.8491 | Val Profit: -155
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8378
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 24 | Train Loss: 0.0130 | Val ROC-AUC: 0.8378 | Val Profit: -190
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9371
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 25 | Train Loss: 0.0132 | Val ROC-AUC: 0.9371 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0112 | Val ROC-AUC: 0.8160 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.8068
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0098 | Val ROC-AUC: 0.8068 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8624
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0093 | Val ROC-AUC: 0.8624 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.866
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0088 | Val ROC-AUC: 0.8660 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8664
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0085 | Val ROC-AUC: 0.8664 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.9771965124077799
val
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9049
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1853 | Val ROC-AUC: 0.9049 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9211
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0818 | Val ROC-AUC: 0.9211 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9437
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0618 | Val ROC-AUC: 0.9437 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9427
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0531 | Val ROC-AUC: 0.9427 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9581
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0510 | Val ROC-AUC: 0.9581 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0471 | Val ROC-AUC: 0.9679 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9654
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0441 | Val ROC-AUC: 0.9654 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0392 | Val ROC-AUC: 0.9689 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0366 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0324 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0377 | Val ROC-AUC: 0.9653 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9726
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0362 | Val ROC-AUC: 0.9726 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9691
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 13 | Train Loss: 0.0295 | Val ROC-AUC: 0.9691 | Val Profit: -125
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9659
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 14 | Train Loss: 0.0278 | Val ROC-AUC: 0.9659 | Val Profit: -195
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9689
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 15 | Train Loss: 0.0363 | Val ROC-AUC: 0.9689 | Val Profit: -350
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9535
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 16 | Train Loss: 0.0334 | Val ROC-AUC: 0.9535 | Val Profit: -335
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9649
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 17 | Train Loss: 0.0315 | Val ROC-AUC: 0.9649 | Val Profit: -170
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9704
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 18 | Train Loss: 0.0284 | Val ROC-AUC: 0.9704 | Val Profit: -190
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0246 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9545
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 20 | Train Loss: 0.0193 | Val ROC-AUC: 0.9545 | Val Profit: -145
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9664
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 21 | Train Loss: 0.0191 | Val ROC-AUC: 0.9664 | Val Profit: -155

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9763
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 22 | Train Loss: 0.0269 | Val ROC-AUC: 0.9763 | Val Profit: -220
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9738
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 23 | Train Loss: 0.0223 | Val ROC-AUC: 0.9738 | Val Profit: -165
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9658
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 24 | Train Loss: 0.0243 | Val ROC-AUC: 0.9658 | Val Profit: -150
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9622
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 25 | Train Loss: 0.0148 | Val ROC-AUC: 0.9622 | Val Profit: -140
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9518
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 26 | Train Loss: 0.0129 | Val ROC-AUC: 0.9518 | Val Profit: -170
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9654
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 27 | Train Loss: 0.0157 | Val ROC-AUC: 0.9654 | Val Profit: -385
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9693
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 28 | Train Loss: 0.0198 | Val ROC-AUC: 0.9693 | Val Profit: -250
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9649
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 29 | Train Loss: 0.0193 | Val ROC-AUC: 0.9649 | Val Profit: -300
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9568
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 30 | Train Loss: 0.0219 | Val ROC-AUC: 0.9568 | Val Profit: -210

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9774647887323944
val
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9128
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 1 | Train Loss: 0.1849 | Val ROC-AUC: 0.9128 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9127
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0823 | Val ROC-AUC: 0.9127 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0698 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9476
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0543 | Val ROC-AUC: 0.9476 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9624
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0521 | Val ROC-AUC: 0.9624 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9618
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0489 | Val ROC-AUC: 0.9618 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9199
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0444 | Val ROC-AUC: 0.9199 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0471 | Val ROC-AUC: 0.9575 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9573
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0487 | Val ROC-AUC: 0.9573 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9493
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0460 | Val ROC-AUC: 0.9493 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9647
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0489 | Val ROC-AUC: 0.9647 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0461 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9749
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0399 | Val ROC-AUC: 0.9749 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0392 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9797
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0400 | Val ROC-AUC: 0.9797 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9748
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 16 | Train Loss: 0.0366 | Val ROC-AUC: 0.9748 | Val Profit: -60
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9319
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0333 | Val ROC-AUC: 0.9319 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9769
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 18 | Train Loss: 0.0351 | Val ROC-AUC: 0.9769 | Val Profit: -195
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9701
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0350 | Val ROC-AUC: 0.9701 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.977
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 20 | Train Loss: 0.0367 | Val ROC-AUC: 0.9770 | Val Profit: -250
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9801
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 21 | Train Loss: 0.0361 | Val ROC-AUC: 0.9801 | Val Profit: -90
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9755
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 22 | Train Loss: 0.0318 | Val ROC-AUC: 0.9755 | Val Profit: -195
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9786
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 23 | Train Loss: 0.0311 | Val ROC-AUC: 0.9786 | Val Profit: -100
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9787
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0286 | Val ROC-AUC: 0.9787 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9781
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 25 | Train Loss: 0.0238 | Val ROC-AUC: 0.9781 | Val Profit: -185

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9641
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 26 | Train Loss: 0.0276 | Val ROC-AUC: 0.9641 | Val Profit: -145
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9729
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 27 | Train Loss: 0.0400 | Val ROC-AUC: 0.9729 | Val Profit: -285
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9756
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 28 | Train Loss: 0.0280 | Val ROC-AUC: 0.9756 | Val Profit: -125
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9772
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 29 | Train Loss: 0.0232 | Val ROC-AUC: 0.9772 | Val Profit: -180
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9226
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0233 | Val ROC-AUC: 0.9226 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 21
Лучший ROC-AUC: 0.9801475519785379
val
ROC-AUC: 0.9801
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9209
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1896 | Val ROC-AUC: 0.9209 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9501
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0828 | Val ROC-AUC: 0.9501 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9328
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0631 | Val ROC-AUC: 0.9328 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9558
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0531 | Val ROC-AUC: 0.9558 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9686
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0484 | Val ROC-AUC: 0.9686 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0403 | Val ROC-AUC: 0.9575 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9364
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0387 | Val ROC-AUC: 0.9364 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9592
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0345 | Val ROC-AUC: 0.9592 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9623
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0322 | Val ROC-AUC: 0.9623 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9504
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0306 | Val ROC-AUC: 0.9504 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9501
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 11 | Train Loss: 0.0274 | Val ROC-AUC: 0.9501 | Val Profit: -215
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9708
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 12 | Train Loss: 0.0275 | Val ROC-AUC: 0.9708 | Val Profit: -260
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9627
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 13 | Train Loss: 0.0243 | Val ROC-AUC: 0.9627 | Val Profit: -230
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9124
Precision: 0.3636
Recall: 0.1905
F0.5-score: 0.3077
Profit: -240

Эпоха 14 | Train Loss: 0.0233 | Val ROC-AUC: 0.9124 | Val Profit: -240
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.872
Precision: 0.3158
Recall: 0.2857
F0.5-score: 0.3093
Profit: -370

Эпоха 15 | Train Loss: 0.0242 | Val ROC-AUC: 0.8720 | Val Profit: -370
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9404
Precision: 0.3721
Recall: 0.7619
F0.5-score: 0.4145
Profit: -620

Эпоха 16 | Train Loss: 0.0302 | Val ROC-AUC: 0.9404 | Val Profit: -620
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9404
Precision: 0.3488
Recall: 0.7143
F0.5-score: 0.3886
Profit: -655

Эпоха 17 | Train Loss: 0.0363 | Val ROC-AUC: 0.9404 | Val Profit: -655
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9663
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 18 | Train Loss: 0.0317 | Val ROC-AUC: 0.9663 | Val Profit: -110
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9725
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 19 | Train Loss: 0.0214 | Val ROC-AUC: 0.9725 | Val Profit: -160
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9752
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 20 | Train Loss: 0.0156 | Val ROC-AUC: 0.9752 | Val Profit: -85
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9751
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 21 | Train Loss: 0.0129 | Val ROC-AUC: 0.9751 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9746
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 22 | Train Loss: 0.0119 | Val ROC-AUC: 0.9746 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9749
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 23 | Train Loss: 0.0112 | Val ROC-AUC: 0.9749 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9759
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 24 | Train Loss: 0.0106 | Val ROC-AUC: 0.9759 | Val Profit: -65
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9742
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 25 | Train Loss: 0.0100 | Val ROC-AUC: 0.9742 | Val Profit: -65
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9744
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 26 | Train Loss: 0.0095 | Val ROC-AUC: 0.9744 | Val Profit: -65
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9755
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 27 | Train Loss: 0.0091 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9754
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 28 | Train Loss: 0.0088 | Val ROC-AUC: 0.9754 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9755
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 29 | Train Loss: 0.0085 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9757
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 30 | Train Loss: 0.0083 | Val ROC-AUC: 0.9757 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9758551307847083
val
ROC-AUC: 0.9759
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9194
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1902 | Val ROC-AUC: 0.9194 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9339
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0828 | Val ROC-AUC: 0.9339 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0600 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9178
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0532 | Val ROC-AUC: 0.9178 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9659
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0467 | Val ROC-AUC: 0.9659 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9486
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0426 | Val ROC-AUC: 0.9486 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9733
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0416 | Val ROC-AUC: 0.9733 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9486
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0399 | Val ROC-AUC: 0.9486 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.94
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0419 | Val ROC-AUC: 0.9400 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9687
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0412 | Val ROC-AUC: 0.9687 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9486
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0372 | Val ROC-AUC: 0.9486 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9194
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0322 | Val ROC-AUC: 0.9194 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9601
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 13 | Train Loss: 0.0293 | Val ROC-AUC: 0.9601 | Val Profit: -205
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9579
Precision: 0.4324
Recall: 0.7619
F0.5-score: 0.4734
Profit: -470

Эпоха 14 | Train Loss: 0.0292 | Val ROC-AUC: 0.9579 | Val Profit: -470
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9333
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 15 | Train Loss: 0.0294 | Val ROC-AUC: 0.9333 | Val Profit: -150
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9592
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 16 | Train Loss: 0.0235 | Val ROC-AUC: 0.9592 | Val Profit: -200
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8771
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 17 | Train Loss: 0.0202 | Val ROC-AUC: 0.8771 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9009
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 18 | Train Loss: 0.0174 | Val ROC-AUC: 0.9009 | Val Profit: -140
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.8414
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0157 | Val ROC-AUC: 0.8414 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8689
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.0141 | Val ROC-AUC: 0.8689 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9179
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 21 | Train Loss: 0.0131 | Val ROC-AUC: 0.9179 | Val Profit: -150
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9256
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 22 | Train Loss: 0.0122 | Val ROC-AUC: 0.9256 | Val Profit: -185
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9602
Precision: 0.4545
Recall: 0.4762
F0.5-score: 0.4587
Profit: -305

Эпоха 23 | Train Loss: 0.0121 | Val ROC-AUC: 0.9602 | Val Profit: -305
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9657
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 24 | Train Loss: 0.0168 | Val ROC-AUC: 0.9657 | Val Profit: -265
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9529
Precision: 0.4667
Recall: 0.6667
F0.5-score: 0.4965
Profit: -365

Эпоха 25 | Train Loss: 0.0245 | Val ROC-AUC: 0.9529 | Val Profit: -365
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9498
Precision: 0.3276
Recall: 0.9048
F0.5-score: 0.3755
Profit: -890

Эпоха 26 | Train Loss: 0.0302 | Val ROC-AUC: 0.9498 | Val Profit: -890
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9732
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 27 | Train Loss: 0.0330 | Val ROC-AUC: 0.9732 | Val Profit: -80
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9579
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 28 | Train Loss: 0.0299 | Val ROC-AUC: 0.9579 | Val Profit: -270
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.967
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 29 | Train Loss: 0.0223 | Val ROC-AUC: 0.9670 | Val Profit: -165
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9701
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 30 | Train Loss: 0.0160 | Val ROC-AUC: 0.9701 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 7
Лучший ROC-AUC: 0.973306505700872
val
ROC-AUC: 0.9733
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9038
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1903 | Val ROC-AUC: 0.9038 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9091
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0862 | Val ROC-AUC: 0.9091 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9309
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0666 | Val ROC-AUC: 0.9309 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0591 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.931
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0570 | Val ROC-AUC: 0.9310 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9421
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0540 | Val ROC-AUC: 0.9421 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9638
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0461 | Val ROC-AUC: 0.9638 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9285
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0442 | Val ROC-AUC: 0.9285 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9261
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0512 | Val ROC-AUC: 0.9261 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9526
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0472 | Val ROC-AUC: 0.9526 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9222
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0414 | Val ROC-AUC: 0.9222 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9788
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0414 | Val ROC-AUC: 0.9788 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0374 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0310 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9607
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0302 | Val ROC-AUC: 0.9607 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9694
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 16 | Train Loss: 0.0311 | Val ROC-AUC: 0.9694 | Val Profit: -155
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9648
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 17 | Train Loss: 0.0416 | Val ROC-AUC: 0.9648 | Val Profit: -720
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9666
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 18 | Train Loss: 0.0356 | Val ROC-AUC: 0.9666 | Val Profit: -210
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9746
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 19 | Train Loss: 0.0297 | Val ROC-AUC: 0.9746 | Val Profit: -120
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9776
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 20 | Train Loss: 0.0248 | Val ROC-AUC: 0.9776 | Val Profit: -90

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9714
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0205 | Val ROC-AUC: 0.9714 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9532
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 22 | Train Loss: 0.0209 | Val ROC-AUC: 0.9532 | Val Profit: -205
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9716
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 23 | Train Loss: 0.0280 | Val ROC-AUC: 0.9716 | Val Profit: -305
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9559
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 24 | Train Loss: 0.0319 | Val ROC-AUC: 0.9559 | Val Profit: -385
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9639
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 25 | Train Loss: 0.0268 | Val ROC-AUC: 0.9639 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9602
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 26 | Train Loss: 0.0211 | Val ROC-AUC: 0.9602 | Val Profit: -125
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9686
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 27 | Train Loss: 0.0201 | Val ROC-AUC: 0.9686 | Val Profit: -65
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9658
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 28 | Train Loss: 0.0171 | Val ROC-AUC: 0.9658 | Val Profit: -160
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9679
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 29 | Train Loss: 0.0225 | Val ROC-AUC: 0.9679 | Val Profit: -275
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9744
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 30 | Train Loss: 0.0296 | Val ROC-AUC: 0.9744 | Val Profit: -450

Лучшая эпоха для model_9_Focal_loss: 12
Лучший ROC-AUC: 0.9788061703554661
val
ROC-AUC: 0.9788
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9508
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0180 | Val ROC-AUC: 0.9508 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9663
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 2 | Train Loss: 0.0083 | Val ROC-AUC: 0.9663 | Val Profit: -305
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9612
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 3 | Train Loss: 0.0069 | Val ROC-AUC: 0.9612 | Val Profit: -625
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9579
Precision: 0.4043
Recall: 0.9048
F0.5-score: 0.4545
Profit: -615

Эпоха 4 | Train Loss: 0.0065 | Val ROC-AUC: 0.9579 | Val Profit: -615
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9742
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 5 | Train Loss: 0.0057 | Val ROC-AUC: 0.9742 | Val Profit: -280
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9704
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 6 | Train Loss: 0.0054 | Val ROC-AUC: 0.9704 | Val Profit: -325
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9755
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 7 | Train Loss: 0.0056 | Val ROC-AUC: 0.9755 | Val Profit: -155
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9721
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 8 | Train Loss: 0.0043 | Val ROC-AUC: 0.9721 | Val Profit: -165
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9737
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 9 | Train Loss: 0.0044 | Val ROC-AUC: 0.9737 | Val Profit: -125
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9775
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 10 | Train Loss: 0.0043 | Val ROC-AUC: 0.9775 | Val Profit: -100
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9772
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 11 | Train Loss: 0.0038 | Val ROC-AUC: 0.9772 | Val Profit: -215
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9745
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 12 | Train Loss: 0.0041 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9797
Precision: 0.7273
Recall: 0.7619
F0.5-score: 0.7339
Profit: -95

Эпоха 13 | Train Loss: 0.0041 | Val ROC-AUC: 0.9797 | Val Profit: -95
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9753
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 14 | Train Loss: 0.0037 | Val ROC-AUC: 0.9753 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9803
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

Эпоха 15 | Train Loss: 0.0038 | Val ROC-AUC: 0.9803 | Val Profit: -80
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9866
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 16 | Train Loss: 0.0034 | Val ROC-AUC: 0.9866 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9751
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 17 | Train Loss: 0.0027 | Val ROC-AUC: 0.9751 | Val Profit: -120
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9803
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 18 | Train Loss: 0.0027 | Val ROC-AUC: 0.9803 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9714
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 19 | Train Loss: 0.0036 | Val ROC-AUC: 0.9714 | Val Profit: -100
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9383
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 20 | Train Loss: 0.0026 | Val ROC-AUC: 0.9383 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9804
Precision: 0.4565
Recall: 1.0
F0.5-score: 0.5122
Profit: -520

Эпоха 21 | Train Loss: 0.0028 | Val ROC-AUC: 0.9804 | Val Profit: -520
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9722
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 22 | Train Loss: 0.0042 | Val ROC-AUC: 0.9722 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9843
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0030 | Val ROC-AUC: 0.9843 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9827
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0024 | Val ROC-AUC: 0.9827 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9901
Precision: 0.8571
Recall: 0.5714
F0.5-score: 0.7792
Profit: -35

Эпоха 25 | Train Loss: 0.0021 | Val ROC-AUC: 0.9901 | Val Profit: -35

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9744
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 26 | Train Loss: 0.0033 | Val ROC-AUC: 0.9744 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9632
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0026 | Val ROC-AUC: 0.9632 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9753
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 28 | Train Loss: 0.0025 | Val ROC-AUC: 0.9753 | Val Profit: -155
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9683
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 29 | Train Loss: 0.0015 | Val ROC-AUC: 0.9683 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.94
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 30 | Train Loss: 0.0017 | Val ROC-AUC: 0.9400 | Val Profit: -170

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9900737759892689
val
ROC-AUC: 0.9901
Precision: 0.8571
Recall: 0.5714
F0.5-score: 0.7792
Profit: -35

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9552
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0178 | Val ROC-AUC: 0.9552 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9532
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 2 | Train Loss: 0.0086 | Val ROC-AUC: 0.9532 | Val Profit: -95
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9604
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 3 | Train Loss: 0.0070 | Val ROC-AUC: 0.9604 | Val Profit: -200
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9595
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 4 | Train Loss: 0.0060 | Val ROC-AUC: 0.9595 | Val Profit: -170

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9657
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 5 | Train Loss: 0.0062 | Val ROC-AUC: 0.9657 | Val Profit: -420
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9788
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 6 | Train Loss: 0.0062 | Val ROC-AUC: 0.9788 | Val Profit: -130
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9755
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 7 | Train Loss: 0.0060 | Val ROC-AUC: 0.9755 | Val Profit: -100
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9773
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 8 | Train Loss: 0.0066 | Val ROC-AUC: 0.9773 | Val Profit: -100
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9822
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0056 | Val ROC-AUC: 0.9822 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9838
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0056 | Val ROC-AUC: 0.9838 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9873
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0052 | Val ROC-AUC: 0.9873 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9831
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0047 | Val ROC-AUC: 0.9831 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9839
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 13 | Train Loss: 0.0052 | Val ROC-AUC: 0.9839 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9886
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0049 | Val ROC-AUC: 0.9886 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.985
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0049 | Val ROC-AUC: 0.9850 | Val Profit: -95
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9865
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0047 | Val ROC-AUC: 0.9865 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9873
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 17 | Train Loss: 0.0046 | Val ROC-AUC: 0.9873 | Val Profit: -85
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.987
Precision: 0.7895
Recall: 0.7143
F0.5-score: 0.7732
Profit: -55

Эпоха 18 | Train Loss: 0.0050 | Val ROC-AUC: 0.9870 | Val Profit: -55
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9914
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0047 | Val ROC-AUC: 0.9914 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9846
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0044 | Val ROC-AUC: 0.9846 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9885
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0045 | Val ROC-AUC: 0.9885 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9824
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 22 | Train Loss: 0.0042 | Val ROC-AUC: 0.9824 | Val Profit: -80
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9905
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 23 | Train Loss: 0.0046 | Val ROC-AUC: 0.9905 | Val Profit: -75
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9843
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 24 | Train Loss: 0.0045 | Val ROC-AUC: 0.9843 | Val Profit: -85

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9828
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0039 | Val ROC-AUC: 0.9828 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9776
Precision: 0.5405
Recall: 0.9524
F0.5-score: 0.5917
Profit: -330

Эпоха 26 | Train Loss: 0.0044 | Val ROC-AUC: 0.9776 | Val Profit: -330
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9887
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 27 | Train Loss: 0.0045 | Val ROC-AUC: 0.9887 | Val Profit: -45
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9934
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0046 | Val ROC-AUC: 0.9934 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9889
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0038 | Val ROC-AUC: 0.9889 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9761
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 30 | Train Loss: 0.0039 | Val ROC-AUC: 0.9761 | Val Profit: -210

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9934272300469483
val
ROC-AUC: 0.9934
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9532
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0181 | Val ROC-AUC: 0.9532 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9398
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0091 | Val ROC-AUC: 0.9398 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9467
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0083 | Val ROC-AUC: 0.9467 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.8781
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0078 | Val ROC-AUC: 0.8781 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9751
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0078 | Val ROC-AUC: 0.9751 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0071 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9673
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0075 | Val ROC-AUC: 0.9673 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9796
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0070 | Val ROC-AUC: 0.9796 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9741
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 9 | Train Loss: 0.0065 | Val ROC-AUC: 0.9741 | Val Profit: -410

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0065 | Val ROC-AUC: 0.9803 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9818
Precision: 0.6154
Recall: 0.7619
F0.5-score: 0.64
Profit: -195

Эпоха 11 | Train Loss: 0.0062 | Val ROC-AUC: 0.9818 | Val Profit: -195
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9815
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 12 | Train Loss: 0.0060 | Val ROC-AUC: 0.9815 | Val Profit: -255
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9824
Precision: 0.3043
Recall: 1.0
F0.5-score: 0.3535
Profit: -1095

Эпоха 13 | Train Loss: 0.0059 | Val ROC-AUC: 0.9824 | Val Profit: -1095
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9848
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0058 | Val ROC-AUC: 0.9848 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9854
Precision: 0.3182
Recall: 1.0
F0.5-score: 0.3684
Profit: -1020

Эпоха 15 | Train Loss: 0.0058 | Val ROC-AUC: 0.9854 | Val Profit: -1020
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9865
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 16 | Train Loss: 0.0058 | Val ROC-AUC: 0.9865 | Val Profit: -340
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9856
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0057 | Val ROC-AUC: 0.9856 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9851
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0060 | Val ROC-AUC: 0.9851 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9889
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0054 | Val ROC-AUC: 0.9889 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9899
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 20 | Train Loss: 0.0055 | Val ROC-AUC: 0.9899 | Val Profit: -75
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9889
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 21 | Train Loss: 0.0054 | Val ROC-AUC: 0.9889 | Val Profit: -45
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9911
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0054 | Val ROC-AUC: 0.9911 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9882
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0050 | Val ROC-AUC: 0.9882 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9865
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 24 | Train Loss: 0.0052 | Val ROC-AUC: 0.9865 | Val Profit: -470

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9887
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0053 | Val ROC-AUC: 0.9887 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9792
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 26 | Train Loss: 0.0055 | Val ROC-AUC: 0.9792 | Val Profit: -155
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0056 | Val ROC-AUC: 0.9812 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9881
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0053 | Val ROC-AUC: 0.9881 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9899
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0052 | Val ROC-AUC: 0.9899 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9889
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0053 | Val ROC-AUC: 0.9889 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9911468812877264
val
ROC-AUC: 0.9911
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.925
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0202 | Val ROC-AUC: 0.9250 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9296
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0093 | Val ROC-AUC: 0.9296 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9539
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0073 | Val ROC-AUC: 0.9539 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9527
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0064 | Val ROC-AUC: 0.9527 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.8901
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0062 | Val ROC-AUC: 0.8901 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0061 | Val ROC-AUC: 0.9510 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9302
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0065 | Val ROC-AUC: 0.9302 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9588
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0059 | Val ROC-AUC: 0.9588 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.962
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0052 | Val ROC-AUC: 0.9620 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0045 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9362
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0049 | Val ROC-AUC: 0.9362 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9194
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 12 | Train Loss: 0.0037 | Val ROC-AUC: 0.9194 | Val Profit: -225
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9186
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 13 | Train Loss: 0.0036 | Val ROC-AUC: 0.9186 | Val Profit: -145
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9724
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 14 | Train Loss: 0.0034 | Val ROC-AUC: 0.9724 | Val Profit: -270
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9492
Precision: 0.3721
Recall: 0.7619
F0.5-score: 0.4145
Profit: -620

Эпоха 15 | Train Loss: 0.0044 | Val ROC-AUC: 0.9492 | Val Profit: -620
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9721
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 16 | Train Loss: 0.0046 | Val ROC-AUC: 0.9721 | Val Profit: -230
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9752
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 17 | Train Loss: 0.0034 | Val ROC-AUC: 0.9752 | Val Profit: -80
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9092
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 18 | Train Loss: 0.0028 | Val ROC-AUC: 0.9092 | Val Profit: -145
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9357
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 19 | Train Loss: 0.0023 | Val ROC-AUC: 0.9357 | Val Profit: -165
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.7624
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 20 | Train Loss: 0.0025 | Val ROC-AUC: 0.7624 | Val Profit: -195
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9552
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 21 | Train Loss: 0.0035 | Val ROC-AUC: 0.9552 | Val Profit: -245
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9315
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 22 | Train Loss: 0.0025 | Val ROC-AUC: 0.9315 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9659
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 23 | Train Loss: 0.0023 | Val ROC-AUC: 0.9659 | Val Profit: -285
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9232
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 24 | Train Loss: 0.0029 | Val ROC-AUC: 0.9232 | Val Profit: -220
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.929
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 25 | Train Loss: 0.0026 | Val ROC-AUC: 0.9290 | Val Profit: -190
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9274
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 26 | Train Loss: 0.0019 | Val ROC-AUC: 0.9274 | Val Profit: -80
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9288
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 27 | Train Loss: 0.0014 | Val ROC-AUC: 0.9288 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8919
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0014 | Val ROC-AUC: 0.8919 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9443
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 29 | Train Loss: 0.0010 | Val ROC-AUC: 0.9443 | Val Profit: -85
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9319
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 30 | Train Loss: 0.0009 | Val ROC-AUC: 0.9319 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.9751844399731724
val
ROC-AUC: 0.9752
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9111
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0212 | Val ROC-AUC: 0.9111 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9407
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0104 | Val ROC-AUC: 0.9407 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9388
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0087 | Val ROC-AUC: 0.9388 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.928
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0072 | Val ROC-AUC: 0.9280 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9378
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0083 | Val ROC-AUC: 0.9378 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9686
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0070 | Val ROC-AUC: 0.9686 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0066 | Val ROC-AUC: 0.9675 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0058 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9457
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0055 | Val ROC-AUC: 0.9457 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9561
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0059 | Val ROC-AUC: 0.9561 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.974
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0063 | Val ROC-AUC: 0.9740 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.972
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0054 | Val ROC-AUC: 0.9720 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9807
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0050 | Val ROC-AUC: 0.9807 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.975
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 14 | Train Loss: 0.0049 | Val ROC-AUC: 0.9750 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9638
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 15 | Train Loss: 0.0048 | Val ROC-AUC: 0.9638 | Val Profit: -170
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9745
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 16 | Train Loss: 0.0050 | Val ROC-AUC: 0.9745 | Val Profit: -115
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9789
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 17 | Train Loss: 0.0051 | Val ROC-AUC: 0.9789 | Val Profit: -135
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9602
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 18 | Train Loss: 0.0046 | Val ROC-AUC: 0.9602 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9759
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 19 | Train Loss: 0.0043 | Val ROC-AUC: 0.9759 | Val Profit: -190
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.976
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0035 | Val ROC-AUC: 0.9760 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9477
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 21 | Train Loss: 0.0028 | Val ROC-AUC: 0.9477 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.972
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 22 | Train Loss: 0.0034 | Val ROC-AUC: 0.9720 | Val Profit: -325

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9691
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 23 | Train Loss: 0.0040 | Val ROC-AUC: 0.9691 | Val Profit: -160
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9699
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 24 | Train Loss: 0.0047 | Val ROC-AUC: 0.9699 | Val Profit: -275
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9689
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 25 | Train Loss: 0.0039 | Val ROC-AUC: 0.9689 | Val Profit: -140
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0032 | Val ROC-AUC: 0.9661 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0027 | Val ROC-AUC: 0.9737 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9667
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 28 | Train Loss: 0.0027 | Val ROC-AUC: 0.9667 | Val Profit: -240
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9742
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 29 | Train Loss: 0.0039 | Val ROC-AUC: 0.9742 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9805
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 30 | Train Loss: 0.0034 | Val ROC-AUC: 0.9805 | Val Profit: -75

Лучшая эпоха для model_9_Focal_loss: 13
Лучший ROC-AUC: 0.9806841046277666
val
ROC-AUC: 0.9807
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9312
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0204 | Val ROC-AUC: 0.9312 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 2 | Train Loss: 0.0107 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0085 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0081 | Val ROC-AUC: 0.9610 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0082 | Val ROC-AUC: 0.9685 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0084 | Val ROC-AUC: 0.9665 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9718
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0077 | Val ROC-AUC: 0.9718 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0071 | Val ROC-AUC: 0.9667 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9648
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0072 | Val ROC-AUC: 0.9648 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9382
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0067 | Val ROC-AUC: 0.9382 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0071 | Val ROC-AUC: 0.9671 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0066 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0064 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0060 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0062 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9751
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0064 | Val ROC-AUC: 0.9751 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9747
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0062 | Val ROC-AUC: 0.9747 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9797
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0063 | Val ROC-AUC: 0.9797 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9771
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 19 | Train Loss: 0.0055 | Val ROC-AUC: 0.9771 | Val Profit: -165
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9765
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 20 | Train Loss: 0.0061 | Val ROC-AUC: 0.9765 | Val Profit: -135
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9607
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 21 | Train Loss: 0.0061 | Val ROC-AUC: 0.9607 | Val Profit: -165
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9666
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 22 | Train Loss: 0.0055 | Val ROC-AUC: 0.9666 | Val Profit: -195
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9793
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0056 | Val ROC-AUC: 0.9793 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0053 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9796
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 25 | Train Loss: 0.0057 | Val ROC-AUC: 0.9796 | Val Profit: -100
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9797
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 26 | Train Loss: 0.0058 | Val ROC-AUC: 0.9797 | Val Profit: -210

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0059 | Val ROC-AUC: 0.9803 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9768
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 28 | Train Loss: 0.0051 | Val ROC-AUC: 0.9768 | Val Profit: -155
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9198
Precision: 0.3667
Recall: 0.5238
F0.5-score: 0.3901
Profit: -470

Эпоха 29 | Train Loss: 0.0054 | Val ROC-AUC: 0.9198 | Val Profit: -470
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9775
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 30 | Train Loss: 0.0062 | Val ROC-AUC: 0.9775 | Val Profit: -160

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9802816901408451
val
ROC-AUC: 0.9803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 1 | Train Loss: 0.0218 | Val ROC-AUC: 0.8602 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9507
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0104 | Val ROC-AUC: 0.9507 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0079 | Val ROC-AUC: 0.9567 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0069 | Val ROC-AUC: 0.9594 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9641
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0063 | Val ROC-AUC: 0.9641 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9592
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0053 | Val ROC-AUC: 0.9592 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9333
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0054 | Val ROC-AUC: 0.9333 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9512
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0052 | Val ROC-AUC: 0.9512 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0043 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9584
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 10 | Train Loss: 0.0037 | Val ROC-AUC: 0.9584 | Val Profit: -135
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9704
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 11 | Train Loss: 0.0037 | Val ROC-AUC: 0.9704 | Val Profit: -175
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9314
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 12 | Train Loss: 0.0031 | Val ROC-AUC: 0.9314 | Val Profit: -190
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.962
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 13 | Train Loss: 0.0028 | Val ROC-AUC: 0.9620 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.954
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 14 | Train Loss: 0.0033 | Val ROC-AUC: 0.9540 | Val Profit: -230
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9555
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 15 | Train Loss: 0.0031 | Val ROC-AUC: 0.9555 | Val Profit: -180
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9573
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 16 | Train Loss: 0.0031 | Val ROC-AUC: 0.9573 | Val Profit: -255
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9506
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 17 | Train Loss: 0.0025 | Val ROC-AUC: 0.9506 | Val Profit: -120
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9742
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 18 | Train Loss: 0.0024 | Val ROC-AUC: 0.9742 | Val Profit: -90
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.974
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 19 | Train Loss: 0.0019 | Val ROC-AUC: 0.9740 | Val Profit: -70
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9804
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 20 | Train Loss: 0.0017 | Val ROC-AUC: 0.9804 | Val Profit: -115
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9104
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 21 | Train Loss: 0.0020 | Val ROC-AUC: 0.9104 | Val Profit: -150
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8093
Precision: 0.3871
Recall: 0.5714
F0.5-score: 0.4138
Profit: -460

Эпоха 22 | Train Loss: 0.0022 | Val ROC-AUC: 0.8093 | Val Profit: -460
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9672
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 23 | Train Loss: 0.0046 | Val ROC-AUC: 0.9672 | Val Profit: -350
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9171
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 24 | Train Loss: 0.0035 | Val ROC-AUC: 0.9171 | Val Profit: -200
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9678
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 25 | Train Loss: 0.0031 | Val ROC-AUC: 0.9678 | Val Profit: -395
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9662
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 26 | Train Loss: 0.0021 | Val ROC-AUC: 0.9662 | Val Profit: -110
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9623
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 27 | Train Loss: 0.0015 | Val ROC-AUC: 0.9623 | Val Profit: -115
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9598
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 28 | Train Loss: 0.0014 | Val ROC-AUC: 0.9598 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9594
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 29 | Train Loss: 0.0013 | Val ROC-AUC: 0.9594 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9623
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 30 | Train Loss: 0.0012 | Val ROC-AUC: 0.9623 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 20
Лучший ROC-AUC: 0.9804158283031522
val
ROC-AUC: 0.9804
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0213 | Val ROC-AUC: 0.8818 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9431
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0102 | Val ROC-AUC: 0.9431 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9565
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0074 | Val ROC-AUC: 0.9565 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9433
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0082 | Val ROC-AUC: 0.9433 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9682
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0076 | Val ROC-AUC: 0.9682 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9654
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0065 | Val ROC-AUC: 0.9654 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9487
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0058 | Val ROC-AUC: 0.9487 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9566
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0069 | Val ROC-AUC: 0.9566 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9713
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0059 | Val ROC-AUC: 0.9713 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0049 | Val ROC-AUC: 0.9698 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0045 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9428
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 12 | Train Loss: 0.0047 | Val ROC-AUC: 0.9428 | Val Profit: -205
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9459
Precision: 0.3929
Recall: 0.5238
F0.5-score: 0.4135
Profit: -420

Эпоха 13 | Train Loss: 0.0053 | Val ROC-AUC: 0.9459 | Val Profit: -420
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.971
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 14 | Train Loss: 0.0048 | Val ROC-AUC: 0.9710 | Val Profit: -375
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9569
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 15 | Train Loss: 0.0054 | Val ROC-AUC: 0.9569 | Val Profit: -265
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.973
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 16 | Train Loss: 0.0046 | Val ROC-AUC: 0.9730 | Val Profit: -135
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9724
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 17 | Train Loss: 0.0034 | Val ROC-AUC: 0.9724 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.969
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 18 | Train Loss: 0.0029 | Val ROC-AUC: 0.9690 | Val Profit: -145
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9333
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 19 | Train Loss: 0.0027 | Val ROC-AUC: 0.9333 | Val Profit: -110
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9327
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 20 | Train Loss: 0.0023 | Val ROC-AUC: 0.9327 | Val Profit: -160
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.939
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 21 | Train Loss: 0.0024 | Val ROC-AUC: 0.9390 | Val Profit: -180
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9749
Precision: 0.4857
Recall: 0.8095
F0.5-score: 0.528
Profit: -385

Эпоха 22 | Train Loss: 0.0037 | Val ROC-AUC: 0.9749 | Val Profit: -385
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9709
Precision: 0.5
Recall: 0.6667
F0.5-score: 0.5263
Profit: -315

Эпоха 23 | Train Loss: 0.0055 | Val ROC-AUC: 0.9709 | Val Profit: -315
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9478
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 24 | Train Loss: 0.0037 | Val ROC-AUC: 0.9478 | Val Profit: -65
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9784
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 25 | Train Loss: 0.0025 | Val ROC-AUC: 0.9784 | Val Profit: -115
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9696
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 26 | Train Loss: 0.0028 | Val ROC-AUC: 0.9696 | Val Profit: -190
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9767
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 27 | Train Loss: 0.0029 | Val ROC-AUC: 0.9767 | Val Profit: -195
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9655
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 28 | Train Loss: 0.0027 | Val ROC-AUC: 0.9655 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9783
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 29 | Train Loss: 0.0025 | Val ROC-AUC: 0.9783 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.976
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 30 | Train Loss: 0.0023 | Val ROC-AUC: 0.9760 | Val Profit: -190

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9784037558685446
val
ROC-AUC: 0.9784
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0212 | Val ROC-AUC: 0.9513 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9058
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0110 | Val ROC-AUC: 0.9058 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9451
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0098 | Val ROC-AUC: 0.9451 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9081
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0088 | Val ROC-AUC: 0.9081 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9323
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0081 | Val ROC-AUC: 0.9323 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9595
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0077 | Val ROC-AUC: 0.9595 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9528
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0078 | Val ROC-AUC: 0.9528 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9449
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0077 | Val ROC-AUC: 0.9449 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9528
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0071 | Val ROC-AUC: 0.9528 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0073 | Val ROC-AUC: 0.9571 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9623
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0072 | Val ROC-AUC: 0.9623 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0072 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9227
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0071 | Val ROC-AUC: 0.9227 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9304
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0078 | Val ROC-AUC: 0.9304 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0071 | Val ROC-AUC: 0.9725 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0057 | Val ROC-AUC: 0.9655 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9433
Precision: 0.3469
Recall: 0.8095
F0.5-score: 0.3917
Profit: -735

Эпоха 17 | Train Loss: 0.0068 | Val ROC-AUC: 0.9433 | Val Profit: -735
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0073 | Val ROC-AUC: 0.9670 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.969
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0061 | Val ROC-AUC: 0.9690 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0063 | Val ROC-AUC: 0.9555 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0059 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9662
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0059 | Val ROC-AUC: 0.9662 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9579
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0057 | Val ROC-AUC: 0.9579 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9734
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0061 | Val ROC-AUC: 0.9734 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9797
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 25 | Train Loss: 0.0058 | Val ROC-AUC: 0.9797 | Val Profit: -65
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9696
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 26 | Train Loss: 0.0059 | Val ROC-AUC: 0.9696 | Val Profit: -355
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9687
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0061 | Val ROC-AUC: 0.9687 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9722
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 28 | Train Loss: 0.0057 | Val ROC-AUC: 0.9722 | Val Profit: -140
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9663
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 29 | Train Loss: 0.0054 | Val ROC-AUC: 0.9663 | Val Profit: -185
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9635
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 30 | Train Loss: 0.0058 | Val ROC-AUC: 0.9635 | Val Profit: -145

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9797451374916164
val
ROC-AUC: 0.9797
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.928
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0359 | Val ROC-AUC: 0.9280 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.965
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 2 | Train Loss: 0.0163 | Val ROC-AUC: 0.9650 | Val Profit: -200
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9685
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 3 | Train Loss: 0.0133 | Val ROC-AUC: 0.9685 | Val Profit: -525
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9631
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 4 | Train Loss: 0.0142 | Val ROC-AUC: 0.9631 | Val Profit: -355

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9746
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 5 | Train Loss: 0.0121 | Val ROC-AUC: 0.9746 | Val Profit: -240
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9728
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 6 | Train Loss: 0.0110 | Val ROC-AUC: 0.9728 | Val Profit: -175
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9679
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 7 | Train Loss: 0.0099 | Val ROC-AUC: 0.9679 | Val Profit: -270
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9681
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 8 | Train Loss: 0.0099 | Val ROC-AUC: 0.9681 | Val Profit: -90
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9737
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 9 | Train Loss: 0.0089 | Val ROC-AUC: 0.9737 | Val Profit: -135
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.981
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 10 | Train Loss: 0.0081 | Val ROC-AUC: 0.9810 | Val Profit: -170
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9563
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 11 | Train Loss: 0.0078 | Val ROC-AUC: 0.9563 | Val Profit: -125
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9675
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 12 | Train Loss: 0.0075 | Val ROC-AUC: 0.9675 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9877
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 13 | Train Loss: 0.0078 | Val ROC-AUC: 0.9877 | Val Profit: -140
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.982
Precision: 0.6552
Recall: 0.9048
F0.5-score: 0.6934
Profit: -165

Эпоха 14 | Train Loss: 0.0089 | Val ROC-AUC: 0.9820 | Val Profit: -165

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0083 | Val ROC-AUC: 0.9543 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9722
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 16 | Train Loss: 0.0059 | Val ROC-AUC: 0.9722 | Val Profit: -165
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9804
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 17 | Train Loss: 0.0068 | Val ROC-AUC: 0.9804 | Val Profit: -90
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9759
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 18 | Train Loss: 0.0074 | Val ROC-AUC: 0.9759 | Val Profit: -210
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9619
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 19 | Train Loss: 0.0075 | Val ROC-AUC: 0.9619 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9826
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 20 | Train Loss: 0.0050 | Val ROC-AUC: 0.9826 | Val Profit: -45
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9669
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 21 | Train Loss: 0.0048 | Val ROC-AUC: 0.9669 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9298
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 22 | Train Loss: 0.0055 | Val ROC-AUC: 0.9298 | Val Profit: -185
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9855
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 23 | Train Loss: 0.0061 | Val ROC-AUC: 0.9855 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9878
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 24 | Train Loss: 0.0045 | Val ROC-AUC: 0.9878 | Val Profit: -80
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9681
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 25 | Train Loss: 0.0050 | Val ROC-AUC: 0.9681 | Val Profit: -115
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8987
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 26 | Train Loss: 0.0059 | Val ROC-AUC: 0.8987 | Val Profit: -70
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9576
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 27 | Train Loss: 0.0043 | Val ROC-AUC: 0.9576 | Val Profit: -85
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9225
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 28 | Train Loss: 0.0040 | Val ROC-AUC: 0.9225 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8867
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 29 | Train Loss: 0.0035 | Val ROC-AUC: 0.8867 | Val Profit: -145
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9724
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 30 | Train Loss: 0.0027 | Val ROC-AUC: 0.9724 | Val Profit: -50

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9877934272300469
val
ROC-AUC: 0.9878
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8919
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0358 | Val ROC-AUC: 0.8919 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9494
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 2 | Train Loss: 0.0167 | Val ROC-AUC: 0.9494 | Val Profit: -320
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9604
Precision: 0.4375
Recall: 0.6667
F0.5-score: 0.4698
Profit: -415

Эпоха 3 | Train Loss: 0.0138 | Val ROC-AUC: 0.9604 | Val Profit: -415
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.973
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 4 | Train Loss: 0.0112 | Val ROC-AUC: 0.9730 | Val Profit: -185

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9751
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 5 | Train Loss: 0.0106 | Val ROC-AUC: 0.9751 | Val Profit: -245
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9742
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 6 | Train Loss: 0.0094 | Val ROC-AUC: 0.9742 | Val Profit: -215
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9673
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 7 | Train Loss: 0.0089 | Val ROC-AUC: 0.9673 | Val Profit: -130
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9824
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 8 | Train Loss: 0.0094 | Val ROC-AUC: 0.9824 | Val Profit: -160
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9606
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 9 | Train Loss: 0.0094 | Val ROC-AUC: 0.9606 | Val Profit: -220
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9712
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 10 | Train Loss: 0.0114 | Val ROC-AUC: 0.9712 | Val Profit: -195
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0095 | Val ROC-AUC: 0.9516 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9759
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 12 | Train Loss: 0.0098 | Val ROC-AUC: 0.9759 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.974
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 13 | Train Loss: 0.0083 | Val ROC-AUC: 0.9740 | Val Profit: -120
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9576
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 14 | Train Loss: 0.0079 | Val ROC-AUC: 0.9576 | Val Profit: -125

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.923
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0083 | Val ROC-AUC: 0.9230 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9262
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 16 | Train Loss: 0.0079 | Val ROC-AUC: 0.9262 | Val Profit: -85
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9678
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 17 | Train Loss: 0.0093 | Val ROC-AUC: 0.9678 | Val Profit: -275
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9788
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 18 | Train Loss: 0.0092 | Val ROC-AUC: 0.9788 | Val Profit: -90
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9878
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0090 | Val ROC-AUC: 0.9878 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9874
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 20 | Train Loss: 0.0082 | Val ROC-AUC: 0.9874 | Val Profit: -60
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9808
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0083 | Val ROC-AUC: 0.9808 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.7329
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0071 | Val ROC-AUC: 0.7329 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9814
Precision: 0.5938
Recall: 0.9048
F0.5-score: 0.6376
Profit: -240

Эпоха 23 | Train Loss: 0.0085 | Val ROC-AUC: 0.9814 | Val Profit: -240
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9788
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 24 | Train Loss: 0.0096 | Val ROC-AUC: 0.9788 | Val Profit: -75
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9842
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0084 | Val ROC-AUC: 0.9842 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9832
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 26 | Train Loss: 0.0067 | Val ROC-AUC: 0.9832 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.8975
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0063 | Val ROC-AUC: 0.8975 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9846
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 28 | Train Loss: 0.0064 | Val ROC-AUC: 0.9846 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9289
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 29 | Train Loss: 0.0065 | Val ROC-AUC: 0.9289 | Val Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9839
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 30 | Train Loss: 0.0072 | Val ROC-AUC: 0.9839 | Val Profit: -275

Лучшая эпоха для model_9_Focal_loss: 19
Лучший ROC-AUC: 0.987793427230047
val
ROC-AUC: 0.9878
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9337
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0356 | Val ROC-AUC: 0.9337 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9496
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0176 | Val ROC-AUC: 0.9496 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0171 | Val ROC-AUC: 0.9555 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9697
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 4 | Train Loss: 0.0153 | Val ROC-AUC: 0.9697 | Val Profit: -100

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9753
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0133 | Val ROC-AUC: 0.9753 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9764
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0124 | Val ROC-AUC: 0.9764 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9842
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0118 | Val ROC-AUC: 0.9842 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9776
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0117 | Val ROC-AUC: 0.9776 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9822
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 9 | Train Loss: 0.0114 | Val ROC-AUC: 0.9822 | Val Profit: -285

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9815
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 10 | Train Loss: 0.0111 | Val ROC-AUC: 0.9815 | Val Profit: -100
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9779
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0111 | Val ROC-AUC: 0.9779 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9822
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0109 | Val ROC-AUC: 0.9822 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9862
Precision: 0.6
Recall: 0.8571
F0.5-score: 0.6383
Profit: -225

Эпоха 13 | Train Loss: 0.0108 | Val ROC-AUC: 0.9862 | Val Profit: -225
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9878
Precision: 0.375
Recall: 1.0
F0.5-score: 0.4286
Profit: -770

Эпоха 14 | Train Loss: 0.0110 | Val ROC-AUC: 0.9878 | Val Profit: -770

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9883
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0106 | Val ROC-AUC: 0.9883 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9844
Precision: 0.6429
Recall: 0.8571
F0.5-score: 0.6767
Profit: -175

Эпоха 16 | Train Loss: 0.0105 | Val ROC-AUC: 0.9844 | Val Profit: -175
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9859
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 17 | Train Loss: 0.0110 | Val ROC-AUC: 0.9859 | Val Profit: -250
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9835
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0108 | Val ROC-AUC: 0.9835 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9824
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 19 | Train Loss: 0.0109 | Val ROC-AUC: 0.9824 | Val Profit: -90

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9852
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 20 | Train Loss: 0.0098 | Val ROC-AUC: 0.9852 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9894
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0109 | Val ROC-AUC: 0.9894 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9882
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 22 | Train Loss: 0.0098 | Val ROC-AUC: 0.9882 | Val Profit: -65
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9903
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 23 | Train Loss: 0.0101 | Val ROC-AUC: 0.9903 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9886
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0105 | Val ROC-AUC: 0.9886 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9933
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0103 | Val ROC-AUC: 0.9933 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9852
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 26 | Train Loss: 0.0093 | Val ROC-AUC: 0.9852 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9866
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0108 | Val ROC-AUC: 0.9866 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9704
Precision: 0.5
Recall: 0.6667
F0.5-score: 0.5263
Profit: -315

Эпоха 28 | Train Loss: 0.0105 | Val ROC-AUC: 0.9704 | Val Profit: -315

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9909
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0115 | Val ROC-AUC: 0.9909 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9522
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 30 | Train Loss: 0.0107 | Val ROC-AUC: 0.9522 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9932930918846412
val
ROC-AUC: 0.9933
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.931
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0404 | Val ROC-AUC: 0.9310 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.927
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0181 | Val ROC-AUC: 0.9270 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9292
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0144 | Val ROC-AUC: 0.9292 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.948
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0132 | Val ROC-AUC: 0.9480 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9471
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0135 | Val ROC-AUC: 0.9471 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0111 | Val ROC-AUC: 0.9544 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9415
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0116 | Val ROC-AUC: 0.9415 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9656
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0104 | Val ROC-AUC: 0.9656 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0080 | Val ROC-AUC: 0.9698 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9451
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 10 | Train Loss: 0.0082 | Val ROC-AUC: 0.9451 | Val Profit: -175
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.8948
Precision: 0.4231
Recall: 0.5238
F0.5-score: 0.44
Profit: -370

Эпоха 11 | Train Loss: 0.0082 | Val ROC-AUC: 0.8948 | Val Profit: -370
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9714
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 12 | Train Loss: 0.0098 | Val ROC-AUC: 0.9714 | Val Profit: -230
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9537
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 13 | Train Loss: 0.0071 | Val ROC-AUC: 0.9537 | Val Profit: -195
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9274
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 14 | Train Loss: 0.0066 | Val ROC-AUC: 0.9274 | Val Profit: -200
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9516
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 15 | Train Loss: 0.0060 | Val ROC-AUC: 0.9516 | Val Profit: -280
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9527
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 16 | Train Loss: 0.0056 | Val ROC-AUC: 0.9527 | Val Profit: -165
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9712
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 17 | Train Loss: 0.0057 | Val ROC-AUC: 0.9712 | Val Profit: -300
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.87
Precision: 0.4
Recall: 0.5714
F0.5-score: 0.4255
Profit: -435

Эпоха 18 | Train Loss: 0.0067 | Val ROC-AUC: 0.8700 | Val Profit: -435
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9454
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 19 | Train Loss: 0.0091 | Val ROC-AUC: 0.9454 | Val Profit: -375
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9344
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 20 | Train Loss: 0.0067 | Val ROC-AUC: 0.9344 | Val Profit: -140
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9223
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 21 | Train Loss: 0.0069 | Val ROC-AUC: 0.9223 | Val Profit: -285
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9289
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 22 | Train Loss: 0.0066 | Val ROC-AUC: 0.9289 | Val Profit: -355
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9711
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 23 | Train Loss: 0.0056 | Val ROC-AUC: 0.9711 | Val Profit: -140
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9707
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 24 | Train Loss: 0.0039 | Val ROC-AUC: 0.9707 | Val Profit: -60
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9742
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 25 | Train Loss: 0.0032 | Val ROC-AUC: 0.9742 | Val Profit: -140
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9785
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 26 | Train Loss: 0.0033 | Val ROC-AUC: 0.9785 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9395
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 27 | Train Loss: 0.0026 | Val ROC-AUC: 0.9395 | Val Profit: -170
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.976
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 28 | Train Loss: 0.0028 | Val ROC-AUC: 0.9760 | Val Profit: -115
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9327
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 29 | Train Loss: 0.0019 | Val ROC-AUC: 0.9327 | Val Profit: -145
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9467
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 30 | Train Loss: 0.0017 | Val ROC-AUC: 0.9467 | Val Profit: -155

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9785378940308518
val
ROC-AUC: 0.9785
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9219
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0411 | Val ROC-AUC: 0.9219 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9435
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0199 | Val ROC-AUC: 0.9435 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.949
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 3 | Train Loss: 0.0164 | Val ROC-AUC: 0.9490 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9586
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0140 | Val ROC-AUC: 0.9586 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0124 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.942
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0120 | Val ROC-AUC: 0.9420 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.924
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0127 | Val ROC-AUC: 0.9240 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0124 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0105 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0097 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.837
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0095 | Val ROC-AUC: 0.8370 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9445
Precision: 0.3617
Recall: 0.8095
F0.5-score: 0.4067
Profit: -685

Эпоха 12 | Train Loss: 0.0113 | Val ROC-AUC: 0.9445 | Val Profit: -685

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.971
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 13 | Train Loss: 0.0098 | Val ROC-AUC: 0.9710 | Val Profit: -200
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9693
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 14 | Train Loss: 0.0083 | Val ROC-AUC: 0.9693 | Val Profit: -195
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9227
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0079 | Val ROC-AUC: 0.9227 | Val Profit: -95
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9364
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 16 | Train Loss: 0.0076 | Val ROC-AUC: 0.9364 | Val Profit: -95
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9655
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 17 | Train Loss: 0.0082 | Val ROC-AUC: 0.9655 | Val Profit: -225
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.97
Precision: 0.5
Recall: 0.8571
F0.5-score: 0.5455
Profit: -375

Эпоха 18 | Train Loss: 0.0096 | Val ROC-AUC: 0.9700 | Val Profit: -375
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9629
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 19 | Train Loss: 0.0097 | Val ROC-AUC: 0.9629 | Val Profit: -225
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9764
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 20 | Train Loss: 0.0081 | Val ROC-AUC: 0.9764 | Val Profit: -195
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0066 | Val ROC-AUC: 0.9685 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9682
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 22 | Train Loss: 0.0056 | Val ROC-AUC: 0.9682 | Val Profit: -155
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.972
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 23 | Train Loss: 0.0047 | Val ROC-AUC: 0.9720 | Val Profit: -180
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9745
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 24 | Train Loss: 0.0046 | Val ROC-AUC: 0.9745 | Val Profit: -190
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9701
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 25 | Train Loss: 0.0065 | Val ROC-AUC: 0.9701 | Val Profit: -335
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9707
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 26 | Train Loss: 0.0068 | Val ROC-AUC: 0.9707 | Val Profit: -210
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9682
Precision: 0.4167
Recall: 0.2381
F0.5-score: 0.3623
Profit: -230

Эпоха 27 | Train Loss: 0.0077 | Val ROC-AUC: 0.9682 | Val Profit: -230
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9742
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 28 | Train Loss: 0.0053 | Val ROC-AUC: 0.9742 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9706
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 29 | Train Loss: 0.0044 | Val ROC-AUC: 0.9706 | Val Profit: -80
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9756
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 30 | Train Loss: 0.0052 | Val ROC-AUC: 0.9756 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 20
Лучший ROC-AUC: 0.9763916834339369
val
ROC-AUC: 0.9764
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9233
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0405 | Val ROC-AUC: 0.9233 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9426
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 2 | Train Loss: 0.0204 | Val ROC-AUC: 0.9426 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9371
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0179 | Val ROC-AUC: 0.9371 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9223
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0185 | Val ROC-AUC: 0.9223 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9492
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0157 | Val ROC-AUC: 0.9492 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9674
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0158 | Val ROC-AUC: 0.9674 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9726
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0146 | Val ROC-AUC: 0.9726 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9691
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0133 | Val ROC-AUC: 0.9691 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9626
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0125 | Val ROC-AUC: 0.9626 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9682
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0115 | Val ROC-AUC: 0.9682 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0121 | Val ROC-AUC: 0.9698 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9647
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0122 | Val ROC-AUC: 0.9647 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9727
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0121 | Val ROC-AUC: 0.9727 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9666
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0114 | Val ROC-AUC: 0.9666 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0102 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9698
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 16 | Train Loss: 0.0110 | Val ROC-AUC: 0.9698 | Val Profit: -95
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9681
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 17 | Train Loss: 0.0105 | Val ROC-AUC: 0.9681 | Val Profit: -245
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.969
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0096 | Val ROC-AUC: 0.9690 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.936
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 19 | Train Loss: 0.0120 | Val ROC-AUC: 0.9360 | Val Profit: -250
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9795
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 20 | Train Loss: 0.0110 | Val ROC-AUC: 0.9795 | Val Profit: -110

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9789
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0093 | Val ROC-AUC: 0.9789 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9776
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 22 | Train Loss: 0.0095 | Val ROC-AUC: 0.9776 | Val Profit: -155
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9746
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0094 | Val ROC-AUC: 0.9746 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9746
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0085 | Val ROC-AUC: 0.9746 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9748
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 25 | Train Loss: 0.0087 | Val ROC-AUC: 0.9748 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9785
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 26 | Train Loss: 0.0092 | Val ROC-AUC: 0.9785 | Val Profit: -295
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9797
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 27 | Train Loss: 0.0091 | Val ROC-AUC: 0.9797 | Val Profit: -245
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0100 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9769
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0083 | Val ROC-AUC: 0.9769 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9643
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 30 | Train Loss: 0.0090 | Val ROC-AUC: 0.9643 | Val Profit: -590

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9797451374916163
val
ROC-AUC: 0.9797
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0435 | Val ROC-AUC: 0.8616 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9404
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0214 | Val ROC-AUC: 0.9404 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9565
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0163 | Val ROC-AUC: 0.9565 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9447
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0137 | Val ROC-AUC: 0.9447 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9578
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0120 | Val ROC-AUC: 0.9578 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9693
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0106 | Val ROC-AUC: 0.9693 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9714
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0109 | Val ROC-AUC: 0.9714 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0098 | Val ROC-AUC: 0.9596 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9553
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0087 | Val ROC-AUC: 0.9553 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.956
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0090 | Val ROC-AUC: 0.9560 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9675
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 11 | Train Loss: 0.0086 | Val ROC-AUC: 0.9675 | Val Profit: -230
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9529
Precision: 0.3636
Recall: 0.381
F0.5-score: 0.367
Profit: -375

Эпоха 12 | Train Loss: 0.0077 | Val ROC-AUC: 0.9529 | Val Profit: -375
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9064
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 13 | Train Loss: 0.0063 | Val ROC-AUC: 0.9064 | Val Profit: -125
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9321
Precision: 0.4146
Recall: 0.8095
F0.5-score: 0.4595
Profit: -535

Эпоха 14 | Train Loss: 0.0071 | Val ROC-AUC: 0.9321 | Val Profit: -535
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9576
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 15 | Train Loss: 0.0080 | Val ROC-AUC: 0.9576 | Val Profit: -320
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9647
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 16 | Train Loss: 0.0071 | Val ROC-AUC: 0.9647 | Val Profit: -145
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8885
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 17 | Train Loss: 0.0052 | Val ROC-AUC: 0.8885 | Val Profit: -120
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9076
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 18 | Train Loss: 0.0057 | Val ROC-AUC: 0.9076 | Val Profit: -90
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9604
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 19 | Train Loss: 0.0043 | Val ROC-AUC: 0.9604 | Val Profit: -185
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.917
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 20 | Train Loss: 0.0037 | Val ROC-AUC: 0.9170 | Val Profit: -155
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.8892
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0032 | Val ROC-AUC: 0.8892 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8794
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 22 | Train Loss: 0.0030 | Val ROC-AUC: 0.8794 | Val Profit: -140
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8896
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 23 | Train Loss: 0.0028 | Val ROC-AUC: 0.8896 | Val Profit: -140
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8926
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 24 | Train Loss: 0.0027 | Val ROC-AUC: 0.8926 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.8877
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 25 | Train Loss: 0.0027 | Val ROC-AUC: 0.8877 | Val Profit: -140
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.89
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 26 | Train Loss: 0.0026 | Val ROC-AUC: 0.8900 | Val Profit: -165
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.8907
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 27 | Train Loss: 0.0026 | Val ROC-AUC: 0.8907 | Val Profit: -165
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8912
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 28 | Train Loss: 0.0026 | Val ROC-AUC: 0.8912 | Val Profit: -165
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8916
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 29 | Train Loss: 0.0025 | Val ROC-AUC: 0.8916 | Val Profit: -165
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8915
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 30 | Train Loss: 0.0025 | Val ROC-AUC: 0.8915 | Val Profit: -190

Лучшая эпоха для model_9_Focal_loss: 7
Лучший ROC-AUC: 0.9714285714285714
val
ROC-AUC: 0.9714
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8759
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0439 | Val ROC-AUC: 0.8759 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9487
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0210 | Val ROC-AUC: 0.9487 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9408
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0162 | Val ROC-AUC: 0.9408 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9003
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0137 | Val ROC-AUC: 0.9003 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9443
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0134 | Val ROC-AUC: 0.9443 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9367
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0141 | Val ROC-AUC: 0.9367 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9508
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0138 | Val ROC-AUC: 0.9508 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9663
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0115 | Val ROC-AUC: 0.9663 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9536
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0104 | Val ROC-AUC: 0.9536 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9508
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0098 | Val ROC-AUC: 0.9508 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9494
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0082 | Val ROC-AUC: 0.9494 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9655
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 12 | Train Loss: 0.0072 | Val ROC-AUC: 0.9655 | Val Profit: -230
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9154
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 13 | Train Loss: 0.0067 | Val ROC-AUC: 0.9154 | Val Profit: -135
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9665
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 14 | Train Loss: 0.0059 | Val ROC-AUC: 0.9665 | Val Profit: -230
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9618
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 15 | Train Loss: 0.0067 | Val ROC-AUC: 0.9618 | Val Profit: -245
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.8981
Precision: 0.4444
Recall: 0.381
F0.5-score: 0.4301
Profit: -275

Эпоха 16 | Train Loss: 0.0085 | Val ROC-AUC: 0.8981 | Val Profit: -275
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.936
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 17 | Train Loss: 0.0073 | Val ROC-AUC: 0.9360 | Val Profit: -185
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9565
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 18 | Train Loss: 0.0066 | Val ROC-AUC: 0.9565 | Val Profit: -170
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9666
Precision: 0.4375
Recall: 0.3333
F0.5-score: 0.4118
Profit: -260

Эпоха 19 | Train Loss: 0.0063 | Val ROC-AUC: 0.9666 | Val Profit: -260
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9588
Precision: 0.4688
Recall: 0.7143
F0.5-score: 0.5034
Profit: -380

Эпоха 20 | Train Loss: 0.0068 | Val ROC-AUC: 0.9588 | Val Profit: -380
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9532
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 21 | Train Loss: 0.0087 | Val ROC-AUC: 0.9532 | Val Profit: -665
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9547
Precision: 0.383
Recall: 0.8571
F0.5-score: 0.4306
Profit: -650

Эпоха 22 | Train Loss: 0.0104 | Val ROC-AUC: 0.9547 | Val Profit: -650
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9736
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 23 | Train Loss: 0.0083 | Val ROC-AUC: 0.9736 | Val Profit: -115
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9726
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 24 | Train Loss: 0.0060 | Val ROC-AUC: 0.9726 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9602
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 25 | Train Loss: 0.0043 | Val ROC-AUC: 0.9602 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9632
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 26 | Train Loss: 0.0037 | Val ROC-AUC: 0.9632 | Val Profit: -170
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.958
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 27 | Train Loss: 0.0032 | Val ROC-AUC: 0.9580 | Val Profit: -115
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9619
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 28 | Train Loss: 0.0028 | Val ROC-AUC: 0.9619 | Val Profit: -155
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9595
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 29 | Train Loss: 0.0026 | Val ROC-AUC: 0.9595 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9298
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 30 | Train Loss: 0.0025 | Val ROC-AUC: 0.9298 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9735747820254863
val
ROC-AUC: 0.9736
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9074
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0428 | Val ROC-AUC: 0.9074 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9366
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0228 | Val ROC-AUC: 0.9366 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.8895
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0184 | Val ROC-AUC: 0.8895 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9643
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0175 | Val ROC-AUC: 0.9643 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9663
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0144 | Val ROC-AUC: 0.9663 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.929
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0144 | Val ROC-AUC: 0.9290 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9622
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0151 | Val ROC-AUC: 0.9622 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9654
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0135 | Val ROC-AUC: 0.9654 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0122 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0142 | Val ROC-AUC: 0.9616 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9701
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0129 | Val ROC-AUC: 0.9701 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0110 | Val ROC-AUC: 0.9683 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0106 | Val ROC-AUC: 0.9661 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9754
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0115 | Val ROC-AUC: 0.9754 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9669
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 15 | Train Loss: 0.0112 | Val ROC-AUC: 0.9669 | Val Profit: -165
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9698
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 16 | Train Loss: 0.0113 | Val ROC-AUC: 0.9698 | Val Profit: -185
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.951
Precision: 0.4167
Recall: 0.2381
F0.5-score: 0.3623
Profit: -230

Эпоха 17 | Train Loss: 0.0118 | Val ROC-AUC: 0.9510 | Val Profit: -230
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9755
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 18 | Train Loss: 0.0115 | Val ROC-AUC: 0.9755 | Val Profit: -110
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9667
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 19 | Train Loss: 0.0093 | Val ROC-AUC: 0.9667 | Val Profit: -180
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9732
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 20 | Train Loss: 0.0102 | Val ROC-AUC: 0.9732 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9717
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 21 | Train Loss: 0.0103 | Val ROC-AUC: 0.9717 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9724
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0100 | Val ROC-AUC: 0.9724 | Val Profit: -125
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9632
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 23 | Train Loss: 0.0110 | Val ROC-AUC: 0.9632 | Val Profit: -245
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.969
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 24 | Train Loss: 0.0114 | Val ROC-AUC: 0.9690 | Val Profit: -375
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9734
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0102 | Val ROC-AUC: 0.9734 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9686
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 26 | Train Loss: 0.0093 | Val ROC-AUC: 0.9686 | Val Profit: -190
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9812
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 27 | Train Loss: 0.0095 | Val ROC-AUC: 0.9812 | Val Profit: -100
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9468
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 28 | Train Loss: 0.0099 | Val ROC-AUC: 0.9468 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9708
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 29 | Train Loss: 0.0131 | Val ROC-AUC: 0.9708 | Val Profit: -720
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9768
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 30 | Train Loss: 0.0126 | Val ROC-AUC: 0.9768 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9812206572769954
val
ROC-AUC: 0.9812
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9403
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0708 | Val ROC-AUC: 0.9403 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.934
Precision: 0.3333
Recall: 0.1905
F0.5-score: 0.2899
Profit: -265

Эпоха 2 | Train Loss: 0.0318 | Val ROC-AUC: 0.9340 | Val Profit: -265

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9663
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 3 | Train Loss: 0.0285 | Val ROC-AUC: 0.9663 | Val Profit: -440
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9757
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 4 | Train Loss: 0.0224 | Val ROC-AUC: 0.9757 | Val Profit: -465
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9696
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 5 | Train Loss: 0.0210 | Val ROC-AUC: 0.9696 | Val Profit: -350
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9651
Precision: 0.4146
Recall: 0.8095
F0.5-score: 0.4595
Profit: -535

Эпоха 6 | Train Loss: 0.0210 | Val ROC-AUC: 0.9651 | Val Profit: -535
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9745
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 7 | Train Loss: 0.0193 | Val ROC-AUC: 0.9745 | Val Profit: -200
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9801
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 8 | Train Loss: 0.0203 | Val ROC-AUC: 0.9801 | Val Profit: -75
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9768
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 9 | Train Loss: 0.0184 | Val ROC-AUC: 0.9768 | Val Profit: -100
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9745
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 10 | Train Loss: 0.0177 | Val ROC-AUC: 0.9745 | Val Profit: -125
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9579
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 11 | Train Loss: 0.0129 | Val ROC-AUC: 0.9579 | Val Profit: -90
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9832
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 12 | Train Loss: 0.0139 | Val ROC-AUC: 0.9832 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9783
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 13 | Train Loss: 0.0198 | Val ROC-AUC: 0.9783 | Val Profit: -135
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9805
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 14 | Train Loss: 0.0150 | Val ROC-AUC: 0.9805 | Val Profit: -130
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9838
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 15 | Train Loss: 0.0127 | Val ROC-AUC: 0.9838 | Val Profit: -130
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9796
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 16 | Train Loss: 0.0131 | Val ROC-AUC: 0.9796 | Val Profit: -115
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9657
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 17 | Train Loss: 0.0138 | Val ROC-AUC: 0.9657 | Val Profit: -175
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9788
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 18 | Train Loss: 0.0168 | Val ROC-AUC: 0.9788 | Val Profit: -90
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9559
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 19 | Train Loss: 0.0123 | Val ROC-AUC: 0.9559 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9241
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 20 | Train Loss: 0.0107 | Val ROC-AUC: 0.9241 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.8944
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 21 | Train Loss: 0.0111 | Val ROC-AUC: 0.8944 | Val Profit: -155
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8858
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 22 | Train Loss: 0.0115 | Val ROC-AUC: 0.8858 | Val Profit: -135
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8176
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.0075 | Val ROC-AUC: 0.8176 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9769
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 24 | Train Loss: 0.0130 | Val ROC-AUC: 0.9769 | Val Profit: -285
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.98
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 25 | Train Loss: 0.0137 | Val ROC-AUC: 0.9800 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.978
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 26 | Train Loss: 0.0088 | Val ROC-AUC: 0.9780 | Val Profit: -175
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9883
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 27 | Train Loss: 0.0096 | Val ROC-AUC: 0.9883 | Val Profit: -45
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9834
Precision: 0.8
Recall: 0.5714
F0.5-score: 0.7407
Profit: -60

Эпоха 28 | Train Loss: 0.0163 | Val ROC-AUC: 0.9834 | Val Profit: -60
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0119 | Val ROC-AUC: 0.9742 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.982
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 30 | Train Loss: 0.0087 | Val ROC-AUC: 0.9820 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9883299798792756
val
ROC-AUC: 0.9883
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9319
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0710 | Val ROC-AUC: 0.9319 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9559
Precision: 0.4516
Recall: 0.6667
F0.5-score: 0.4828
Profit: -390

Эпоха 2 | Train Loss: 0.0334 | Val ROC-AUC: 0.9559 | Val Profit: -390

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.961
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 3 | Train Loss: 0.0275 | Val ROC-AUC: 0.9610 | Val Profit: -445
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9653
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 4 | Train Loss: 0.0256 | Val ROC-AUC: 0.9653 | Val Profit: -215
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9631
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 5 | Train Loss: 0.0205 | Val ROC-AUC: 0.9631 | Val Profit: -165
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9708
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 6 | Train Loss: 0.0207 | Val ROC-AUC: 0.9708 | Val Profit: -325
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9717
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 7 | Train Loss: 0.0203 | Val ROC-AUC: 0.9717 | Val Profit: -170
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9553
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 8 | Train Loss: 0.0188 | Val ROC-AUC: 0.9553 | Val Profit: -135
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9785
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 9 | Train Loss: 0.0214 | Val ROC-AUC: 0.9785 | Val Profit: -170
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9834
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 10 | Train Loss: 0.0198 | Val ROC-AUC: 0.9834 | Val Profit: -80
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9871
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 11 | Train Loss: 0.0169 | Val ROC-AUC: 0.9871 | Val Profit: -95
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9811
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 12 | Train Loss: 0.0183 | Val ROC-AUC: 0.9811 | Val Profit: -135
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9765
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 13 | Train Loss: 0.0155 | Val ROC-AUC: 0.9765 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9752
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 14 | Train Loss: 0.0169 | Val ROC-AUC: 0.9752 | Val Profit: -110
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.984
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 15 | Train Loss: 0.0156 | Val ROC-AUC: 0.9840 | Val Profit: -60
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9799
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 16 | Train Loss: 0.0160 | Val ROC-AUC: 0.9799 | Val Profit: -305
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9828
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 17 | Train Loss: 0.0192 | Val ROC-AUC: 0.9828 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.971
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0183 | Val ROC-AUC: 0.9710 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9851
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 19 | Train Loss: 0.0156 | Val ROC-AUC: 0.9851 | Val Profit: -110
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 20 | Train Loss: 0.0154 | Val ROC-AUC: 0.9555 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9411
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0125 | Val ROC-AUC: 0.9411 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9749
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 22 | Train Loss: 0.0137 | Val ROC-AUC: 0.9749 | Val Profit: -275
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9852
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0169 | Val ROC-AUC: 0.9852 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.983
Precision: 1.0
Recall: 0.2381
F0.5-score: 0.6098
Profit: -55

Эпоха 24 | Train Loss: 0.0147 | Val ROC-AUC: 0.9830 | Val Profit: -55
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9573
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 25 | Train Loss: 0.0134 | Val ROC-AUC: 0.9573 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9693
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 26 | Train Loss: 0.0155 | Val ROC-AUC: 0.9693 | Val Profit: -210
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0156 | Val ROC-AUC: 0.9755 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9784
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0142 | Val ROC-AUC: 0.9784 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9447
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 29 | Train Loss: 0.0119 | Val ROC-AUC: 0.9447 | Val Profit: -155
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.881
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 30 | Train Loss: 0.0115 | Val ROC-AUC: 0.8810 | Val Profit: -155

Лучшая эпоха для model_9_Focal_loss: 11
Лучший ROC-AUC: 0.9871227364185111
val
ROC-AUC: 0.9871
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9284
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0707 | Val ROC-AUC: 0.9284 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9412
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0366 | Val ROC-AUC: 0.9412 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9525
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0295 | Val ROC-AUC: 0.9525 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9669
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 4 | Train Loss: 0.0292 | Val ROC-AUC: 0.9669 | Val Profit: -160
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9581
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0268 | Val ROC-AUC: 0.9581 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9348
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0236 | Val ROC-AUC: 0.9348 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9696
Precision: 0.4545
Recall: 0.7143
F0.5-score: 0.4902
Profit: -405

Эпоха 7 | Train Loss: 0.0264 | Val ROC-AUC: 0.9696 | Val Profit: -405

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9797
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0233 | Val ROC-AUC: 0.9797 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9753
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0219 | Val ROC-AUC: 0.9753 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9734
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0247 | Val ROC-AUC: 0.9734 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0228 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9795
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 12 | Train Loss: 0.0209 | Val ROC-AUC: 0.9795 | Val Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9804
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 13 | Train Loss: 0.0214 | Val ROC-AUC: 0.9804 | Val Profit: -145
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0211 | Val ROC-AUC: 0.9752 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9848
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0201 | Val ROC-AUC: 0.9848 | Val Profit: -95
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9875
Precision: 0.6129
Recall: 0.9048
F0.5-score: 0.6552
Profit: -215

Эпоха 16 | Train Loss: 0.0193 | Val ROC-AUC: 0.9875 | Val Profit: -215
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9858
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0184 | Val ROC-AUC: 0.9858 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9878
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0204 | Val ROC-AUC: 0.9878 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9838
Precision: 0.6071
Recall: 0.8095
F0.5-score: 0.6391
Profit: -210

Эпоха 19 | Train Loss: 0.0204 | Val ROC-AUC: 0.9838 | Val Profit: -210
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9863
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 20 | Train Loss: 0.0183 | Val ROC-AUC: 0.9863 | Val Profit: -50
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9913
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0194 | Val ROC-AUC: 0.9913 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9847
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0181 | Val ROC-AUC: 0.9847 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9834
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0173 | Val ROC-AUC: 0.9834 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9875
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0188 | Val ROC-AUC: 0.9875 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9902
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0178 | Val ROC-AUC: 0.9902 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9856
Precision: 0.4773
Recall: 1.0
F0.5-score: 0.533
Profit: -470

Эпоха 26 | Train Loss: 0.0187 | Val ROC-AUC: 0.9856 | Val Profit: -470
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.987
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0186 | Val ROC-AUC: 0.9870 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9843
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0176 | Val ROC-AUC: 0.9843 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9859
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0185 | Val ROC-AUC: 0.9859 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9839
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.0170 | Val ROC-AUC: 0.9839 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 21
Лучший ROC-AUC: 0.9912810194500334
val
ROC-AUC: 0.9913
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9313
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0796 | Val ROC-AUC: 0.9313 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9219
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0363 | Val ROC-AUC: 0.9219 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9375
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0284 | Val ROC-AUC: 0.9375 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9307
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0260 | Val ROC-AUC: 0.9307 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0256 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9278
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0274 | Val ROC-AUC: 0.9278 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9554
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0268 | Val ROC-AUC: 0.9554 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0227 | Val ROC-AUC: 0.9555 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0220 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0178 | Val ROC-AUC: 0.9675 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9734
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 11 | Train Loss: 0.0156 | Val ROC-AUC: 0.9734 | Val Profit: -165
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9302
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 12 | Train Loss: 0.0133 | Val ROC-AUC: 0.9302 | Val Profit: -150

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9305
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 13 | Train Loss: 0.0139 | Val ROC-AUC: 0.9305 | Val Profit: -250
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9544
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 14 | Train Loss: 0.0149 | Val ROC-AUC: 0.9544 | Val Profit: -250
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.8795
Precision: 0.3548
Recall: 0.5238
F0.5-score: 0.3793
Profit: -495

Эпоха 15 | Train Loss: 0.0166 | Val ROC-AUC: 0.8795 | Val Profit: -495
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9297
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 16 | Train Loss: 0.0221 | Val ROC-AUC: 0.9297 | Val Profit: -150
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9647
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 17 | Train Loss: 0.0165 | Val ROC-AUC: 0.9647 | Val Profit: -235
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9614
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 18 | Train Loss: 0.0140 | Val ROC-AUC: 0.9614 | Val Profit: -155
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9632
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 19 | Train Loss: 0.0112 | Val ROC-AUC: 0.9632 | Val Profit: -135
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9677
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 20 | Train Loss: 0.0087 | Val ROC-AUC: 0.9677 | Val Profit: -285
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9254
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 21 | Train Loss: 0.0087 | Val ROC-AUC: 0.9254 | Val Profit: -210
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9241
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 22 | Train Loss: 0.0117 | Val ROC-AUC: 0.9241 | Val Profit: -155
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9716
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 23 | Train Loss: 0.0084 | Val ROC-AUC: 0.9716 | Val Profit: -165
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9278
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 24 | Train Loss: 0.0070 | Val ROC-AUC: 0.9278 | Val Profit: -165
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9706
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 25 | Train Loss: 0.0126 | Val ROC-AUC: 0.9706 | Val Profit: -275
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9403
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 26 | Train Loss: 0.0093 | Val ROC-AUC: 0.9403 | Val Profit: -160
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9316
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 27 | Train Loss: 0.0064 | Val ROC-AUC: 0.9316 | Val Profit: -135
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9142
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 28 | Train Loss: 0.0061 | Val ROC-AUC: 0.9142 | Val Profit: -170
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8903
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0048 | Val ROC-AUC: 0.8903 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9309
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 30 | Train Loss: 0.0039 | Val ROC-AUC: 0.9309 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 11
Лучший ROC-AUC: 0.9734406438631791
val
ROC-AUC: 0.9734
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9146
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0799 | Val ROC-AUC: 0.9146 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9331
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0382 | Val ROC-AUC: 0.9331 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9505
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0324 | Val ROC-AUC: 0.9505 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9239
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0321 | Val ROC-AUC: 0.9239 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9607
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0271 | Val ROC-AUC: 0.9607 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9384
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0268 | Val ROC-AUC: 0.9384 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0232 | Val ROC-AUC: 0.9730 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0193 | Val ROC-AUC: 0.9679 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9607
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0182 | Val ROC-AUC: 0.9607 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0181 | Val ROC-AUC: 0.9748 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9586
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 11 | Train Loss: 0.0186 | Val ROC-AUC: 0.9586 | Val Profit: -185
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9714
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 12 | Train Loss: 0.0178 | Val ROC-AUC: 0.9714 | Val Profit: -280
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9626
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 13 | Train Loss: 0.0211 | Val ROC-AUC: 0.9626 | Val Profit: -275
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.973
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 14 | Train Loss: 0.0174 | Val ROC-AUC: 0.9730 | Val Profit: -210
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9354
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 15 | Train Loss: 0.0137 | Val ROC-AUC: 0.9354 | Val Profit: -145
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.972
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 16 | Train Loss: 0.0110 | Val ROC-AUC: 0.9720 | Val Profit: -190
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9335
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 17 | Train Loss: 0.0156 | Val ROC-AUC: 0.9335 | Val Profit: -100
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9683
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 18 | Train Loss: 0.0136 | Val ROC-AUC: 0.9683 | Val Profit: -440
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9708
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 19 | Train Loss: 0.0151 | Val ROC-AUC: 0.9708 | Val Profit: -125
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9539
Precision: 0.425
Recall: 0.8095
F0.5-score: 0.4696
Profit: -510

Эпоха 20 | Train Loss: 0.0124 | Val ROC-AUC: 0.9539 | Val Profit: -510
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.976
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 21 | Train Loss: 0.0174 | Val ROC-AUC: 0.9760 | Val Profit: -135
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9387
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 22 | Train Loss: 0.0165 | Val ROC-AUC: 0.9387 | Val Profit: -335
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9753
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 23 | Train Loss: 0.0143 | Val ROC-AUC: 0.9753 | Val Profit: -75
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.0118 | Val ROC-AUC: 0.9773 | Val Profit: -130
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9356
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0082 | Val ROC-AUC: 0.9356 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8584
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 26 | Train Loss: 0.0068 | Val ROC-AUC: 0.8584 | Val Profit: -120
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9286
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 27 | Train Loss: 0.0067 | Val ROC-AUC: 0.9286 | Val Profit: -135
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9697
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 28 | Train Loss: 0.0130 | Val ROC-AUC: 0.9697 | Val Profit: -240
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9724
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 29 | Train Loss: 0.0128 | Val ROC-AUC: 0.9724 | Val Profit: -180
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9823
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0098 | Val ROC-AUC: 0.9823 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.9822937625754526
val
ROC-AUC: 0.9823
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9407
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0821 | Val ROC-AUC: 0.9407 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9288
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0369 | Val ROC-AUC: 0.9288 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0343 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9117
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0298 | Val ROC-AUC: 0.9117 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9614
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0286 | Val ROC-AUC: 0.9614 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0268 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9363
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0257 | Val ROC-AUC: 0.9363 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9569
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0278 | Val ROC-AUC: 0.9569 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0244 | Val ROC-AUC: 0.9738 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0225 | Val ROC-AUC: 0.9775 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0230 | Val ROC-AUC: 0.9650 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0234 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9677
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0215 | Val ROC-AUC: 0.9677 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 14 | Train Loss: 0.0192 | Val ROC-AUC: 0.9710 | Val Profit: -130
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.972
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 15 | Train Loss: 0.0181 | Val ROC-AUC: 0.9720 | Val Profit: -120
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9661
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 16 | Train Loss: 0.0174 | Val ROC-AUC: 0.9661 | Val Profit: -100
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.971
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 17 | Train Loss: 0.0200 | Val ROC-AUC: 0.9710 | Val Profit: -230
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9767
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 18 | Train Loss: 0.0221 | Val ROC-AUC: 0.9767 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9737
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 19 | Train Loss: 0.0165 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.976
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 20 | Train Loss: 0.0151 | Val ROC-AUC: 0.9760 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9749
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 21 | Train Loss: 0.0184 | Val ROC-AUC: 0.9749 | Val Profit: -190
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9764
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0153 | Val ROC-AUC: 0.9764 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9651
Precision: 0.425
Recall: 0.8095
F0.5-score: 0.4696
Profit: -510

Эпоха 23 | Train Loss: 0.0178 | Val ROC-AUC: 0.9651 | Val Profit: -510
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9763
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 24 | Train Loss: 0.0195 | Val ROC-AUC: 0.9763 | Val Profit: -165
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0148 | Val ROC-AUC: 0.9791 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9718
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0124 | Val ROC-AUC: 0.9718 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9731
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 27 | Train Loss: 0.0143 | Val ROC-AUC: 0.9731 | Val Profit: -275
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9761
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 28 | Train Loss: 0.0168 | Val ROC-AUC: 0.9761 | Val Profit: -160
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9765
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 29 | Train Loss: 0.0131 | Val ROC-AUC: 0.9765 | Val Profit: -205
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9745
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0125 | Val ROC-AUC: 0.9745 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9790744466800805
val
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0859 | Val ROC-AUC: 0.8679 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.918
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0413 | Val ROC-AUC: 0.9180 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0321 | Val ROC-AUC: 0.9344 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9252
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0253 | Val ROC-AUC: 0.9252 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9376
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0273 | Val ROC-AUC: 0.9376 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9587
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0239 | Val ROC-AUC: 0.9587 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0220 | Val ROC-AUC: 0.9555 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0191 | Val ROC-AUC: 0.9602 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.96
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0155 | Val ROC-AUC: 0.9600 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9412
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 10 | Train Loss: 0.0145 | Val ROC-AUC: 0.9412 | Val Profit: -130
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.954
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 11 | Train Loss: 0.0124 | Val ROC-AUC: 0.9540 | Val Profit: -220
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.929
Precision: 0.3333
Recall: 0.2381
F0.5-score: 0.3086
Profit: -305

Эпоха 12 | Train Loss: 0.0123 | Val ROC-AUC: 0.9290 | Val Profit: -305
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9371
Precision: 0.3929
Recall: 0.5238
F0.5-score: 0.4135
Profit: -420

Эпоха 13 | Train Loss: 0.0158 | Val ROC-AUC: 0.9371 | Val Profit: -420
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9539
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 14 | Train Loss: 0.0167 | Val ROC-AUC: 0.9539 | Val Profit: -375
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9488
Precision: 0.375
Recall: 0.2857
F0.5-score: 0.3529
Profit: -295

Эпоха 15 | Train Loss: 0.0130 | Val ROC-AUC: 0.9488 | Val Profit: -295
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9564
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 16 | Train Loss: 0.0135 | Val ROC-AUC: 0.9564 | Val Profit: -485
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9363
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 17 | Train Loss: 0.0188 | Val ROC-AUC: 0.9363 | Val Profit: -190
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9657
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 18 | Train Loss: 0.0158 | Val ROC-AUC: 0.9657 | Val Profit: -245
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9336
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 19 | Train Loss: 0.0100 | Val ROC-AUC: 0.9336 | Val Profit: -155
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9571
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 20 | Train Loss: 0.0091 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9463
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 21 | Train Loss: 0.0079 | Val ROC-AUC: 0.9463 | Val Profit: -140
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9033
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 22 | Train Loss: 0.0065 | Val ROC-AUC: 0.9033 | Val Profit: -190
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.91
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 23 | Train Loss: 0.0060 | Val ROC-AUC: 0.9100 | Val Profit: -195
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9158
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 24 | Train Loss: 0.0056 | Val ROC-AUC: 0.9158 | Val Profit: -195
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9151
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 25 | Train Loss: 0.0055 | Val ROC-AUC: 0.9151 | Val Profit: -195
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9179
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 26 | Train Loss: 0.0053 | Val ROC-AUC: 0.9179 | Val Profit: -195
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9203
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 27 | Train Loss: 0.0052 | Val ROC-AUC: 0.9203 | Val Profit: -195
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9178
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 28 | Train Loss: 0.0051 | Val ROC-AUC: 0.9178 | Val Profit: -195
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9174
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 29 | Train Loss: 0.0051 | Val ROC-AUC: 0.9174 | Val Profit: -195
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.917
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 30 | Train Loss: 0.0050 | Val ROC-AUC: 0.9170 | Val Profit: -195

Лучшая эпоха для model_9_Focal_loss: 18
Лучший ROC-AUC: 0.9656606304493628
val
ROC-AUC: 0.9657
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9197
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0883 | Val ROC-AUC: 0.9197 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9047
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0441 | Val ROC-AUC: 0.9047 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9423
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0324 | Val ROC-AUC: 0.9423 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9349
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0308 | Val ROC-AUC: 0.9349 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0289 | Val ROC-AUC: 0.9544 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0261 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9485
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0245 | Val ROC-AUC: 0.9485 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0234 | Val ROC-AUC: 0.9608 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0238 | Val ROC-AUC: 0.9650 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0217 | Val ROC-AUC: 0.9555 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9454
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0191 | Val ROC-AUC: 0.9454 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0170 | Val ROC-AUC: 0.9730 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.94
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 13 | Train Loss: 0.0180 | Val ROC-AUC: 0.9400 | Val Profit: -185
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9675
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 14 | Train Loss: 0.0148 | Val ROC-AUC: 0.9675 | Val Profit: -270
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9644
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 15 | Train Loss: 0.0135 | Val ROC-AUC: 0.9644 | Val Profit: -90
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9606
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 16 | Train Loss: 0.0124 | Val ROC-AUC: 0.9606 | Val Profit: -115
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9662
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 17 | Train Loss: 0.0116 | Val ROC-AUC: 0.9662 | Val Profit: -285
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9465
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 18 | Train Loss: 0.0110 | Val ROC-AUC: 0.9465 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9642
Precision: 0.4348
Recall: 0.9524
F0.5-score: 0.4878
Profit: -555

Эпоха 19 | Train Loss: 0.0147 | Val ROC-AUC: 0.9642 | Val Profit: -555
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.974
Precision: 0.5
Recall: 0.7619
F0.5-score: 0.5369
Profit: -345

Эпоха 20 | Train Loss: 0.0147 | Val ROC-AUC: 0.9740 | Val Profit: -345
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9751
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 21 | Train Loss: 0.0119 | Val ROC-AUC: 0.9751 | Val Profit: -225
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9281
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 22 | Train Loss: 0.0110 | Val ROC-AUC: 0.9281 | Val Profit: -70
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9698
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 23 | Train Loss: 0.0085 | Val ROC-AUC: 0.9698 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9632
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 24 | Train Loss: 0.0087 | Val ROC-AUC: 0.9632 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9745
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 25 | Train Loss: 0.0132 | Val ROC-AUC: 0.9745 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.976
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 26 | Train Loss: 0.0125 | Val ROC-AUC: 0.9760 | Val Profit: -200
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9467
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 27 | Train Loss: 0.0083 | Val ROC-AUC: 0.9467 | Val Profit: -65
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9459
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 28 | Train Loss: 0.0069 | Val ROC-AUC: 0.9459 | Val Profit: -185
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9449
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 29 | Train Loss: 0.0064 | Val ROC-AUC: 0.9449 | Val Profit: -80
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9363
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 30 | Train Loss: 0.0056 | Val ROC-AUC: 0.9363 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9759892689470154
val
ROC-AUC: 0.976
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.926
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0878 | Val ROC-AUC: 0.9260 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9408
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0444 | Val ROC-AUC: 0.9408 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9408
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0336 | Val ROC-AUC: 0.9408 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9359
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0303 | Val ROC-AUC: 0.9359 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9315
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0320 | Val ROC-AUC: 0.9315 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9174
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0291 | Val ROC-AUC: 0.9174 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9565
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0274 | Val ROC-AUC: 0.9565 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9368
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0259 | Val ROC-AUC: 0.9368 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0304 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9531
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0278 | Val ROC-AUC: 0.9531 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9618
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0232 | Val ROC-AUC: 0.9618 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0218 | Val ROC-AUC: 0.9602 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0220 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0234 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9697
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0185 | Val ROC-AUC: 0.9697 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9635
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 16 | Train Loss: 0.0193 | Val ROC-AUC: 0.9635 | Val Profit: -305
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9726
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 17 | Train Loss: 0.0195 | Val ROC-AUC: 0.9726 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9477
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 18 | Train Loss: 0.0188 | Val ROC-AUC: 0.9477 | Val Profit: -180
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9749
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 19 | Train Loss: 0.0182 | Val ROC-AUC: 0.9749 | Val Profit: -80
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9708
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 20 | Train Loss: 0.0158 | Val ROC-AUC: 0.9708 | Val Profit: -95
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9671
Precision: 0.45
Recall: 0.8571
F0.5-score: 0.4972
Profit: -475

Эпоха 21 | Train Loss: 0.0242 | Val ROC-AUC: 0.9671 | Val Profit: -475
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9773
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 22 | Train Loss: 0.0218 | Val ROC-AUC: 0.9773 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 23 | Train Loss: 0.0149 | Val ROC-AUC: 0.9667 | Val Profit: -155
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9509
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 24 | Train Loss: 0.0134 | Val ROC-AUC: 0.9509 | Val Profit: -135
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9673
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0141 | Val ROC-AUC: 0.9673 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9729
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 26 | Train Loss: 0.0155 | Val ROC-AUC: 0.9729 | Val Profit: -270
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9634
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 27 | Train Loss: 0.0161 | Val ROC-AUC: 0.9634 | Val Profit: -155
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9671
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 28 | Train Loss: 0.0132 | Val ROC-AUC: 0.9671 | Val Profit: -225
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9729
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 29 | Train Loss: 0.0119 | Val ROC-AUC: 0.9729 | Val Profit: -190
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.97
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 30 | Train Loss: 0.0142 | Val ROC-AUC: 0.9700 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9773306505700872
val
ROC-AUC: 0.9773
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0082 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9646
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 2 | Train Loss: 0.0041 | Val ROC-AUC: 0.9646 | Val Profit: -420
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9445
Precision: 0.3721
Recall: 0.7619
F0.5-score: 0.4145
Profit: -620

Эпоха 3 | Train Loss: 0.0036 | Val ROC-AUC: 0.9445 | Val Profit: -620
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9675
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 4 | Train Loss: 0.0035 | Val ROC-AUC: 0.9675 | Val Profit: -420
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9638
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 5 | Train Loss: 0.0028 | Val ROC-AUC: 0.9638 | Val Profit: -410
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9759
Precision: 0.6364
Recall: 0.6667
F0.5-score: 0.6422
Profit: -165

Эпоха 6 | Train Loss: 0.0028 | Val ROC-AUC: 0.9759 | Val Profit: -165
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9716
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 7 | Train Loss: 0.0028 | Val ROC-AUC: 0.9716 | Val Profit: -235
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9746
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 8 | Train Loss: 0.0022 | Val ROC-AUC: 0.9746 | Val Profit: -230
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.978
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 9 | Train Loss: 0.0024 | Val ROC-AUC: 0.9780 | Val Profit: -95
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9792
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 10 | Train Loss: 0.0021 | Val ROC-AUC: 0.9792 | Val Profit: -160
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9834
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 11 | Train Loss: 0.0020 | Val ROC-AUC: 0.9834 | Val Profit: -150
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9616
Precision: 0.3519
Recall: 0.9048
F0.5-score: 0.4008
Profit: -790

Эпоха 12 | Train Loss: 0.0027 | Val ROC-AUC: 0.9616 | Val Profit: -790
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9799
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 13 | Train Loss: 0.0032 | Val ROC-AUC: 0.9799 | Val Profit: -90
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9804
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 14 | Train Loss: 0.0024 | Val ROC-AUC: 0.9804 | Val Profit: -110
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9783
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 15 | Train Loss: 0.0040 | Val ROC-AUC: 0.9783 | Val Profit: -415
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9804
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 16 | Train Loss: 0.0027 | Val ROC-AUC: 0.9804 | Val Profit: -80
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9828
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 17 | Train Loss: 0.0021 | Val ROC-AUC: 0.9828 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9807
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0020 | Val ROC-AUC: 0.9807 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9828
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0017 | Val ROC-AUC: 0.9828 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9791
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 20 | Train Loss: 0.0016 | Val ROC-AUC: 0.9791 | Val Profit: -135
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9764
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 21 | Train Loss: 0.0018 | Val ROC-AUC: 0.9764 | Val Profit: -165
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9808
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 22 | Train Loss: 0.0021 | Val ROC-AUC: 0.9808 | Val Profit: -140
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9783
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 23 | Train Loss: 0.0016 | Val ROC-AUC: 0.9783 | Val Profit: -145
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 24 | Train Loss: 0.0013 | Val ROC-AUC: 0.9775 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9842
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 25 | Train Loss: 0.0013 | Val ROC-AUC: 0.9842 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9698
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 26 | Train Loss: 0.0018 | Val ROC-AUC: 0.9698 | Val Profit: -210
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9792
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0016 | Val ROC-AUC: 0.9792 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9714
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 28 | Train Loss: 0.0011 | Val ROC-AUC: 0.9714 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.973
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 29 | Train Loss: 0.0010 | Val ROC-AUC: 0.9730 | Val Profit: -85
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9787
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 30 | Train Loss: 0.0011 | Val ROC-AUC: 0.9787 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9841716968477532
val
ROC-AUC: 0.9842
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9088
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0082 | Val ROC-AUC: 0.9088 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0044 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9309
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0038 | Val ROC-AUC: 0.9309 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9654
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 4 | Train Loss: 0.0040 | Val ROC-AUC: 0.9654 | Val Profit: -170
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0035 | Val ROC-AUC: 0.9685 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9677
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0031 | Val ROC-AUC: 0.9677 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9709
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0028 | Val ROC-AUC: 0.9709 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9708
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 8 | Train Loss: 0.0030 | Val ROC-AUC: 0.9708 | Val Profit: -135
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9792
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0029 | Val ROC-AUC: 0.9792 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0028 | Val ROC-AUC: 0.9785 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9777
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0028 | Val ROC-AUC: 0.9777 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.972
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0026 | Val ROC-AUC: 0.9720 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9835
Precision: 0.7
Recall: 0.6667
F0.5-score: 0.6931
Profit: -115

Эпоха 13 | Train Loss: 0.0026 | Val ROC-AUC: 0.9835 | Val Profit: -115
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.96
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 14 | Train Loss: 0.0027 | Val ROC-AUC: 0.9600 | Val Profit: -95
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9701
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 15 | Train Loss: 0.0030 | Val ROC-AUC: 0.9701 | Val Profit: -300

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9867
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0028 | Val ROC-AUC: 0.9867 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.6441
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0024 | Val ROC-AUC: 0.6441 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9856
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 18 | Train Loss: 0.0030 | Val ROC-AUC: 0.9856 | Val Profit: -75
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9874
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 19 | Train Loss: 0.0023 | Val ROC-AUC: 0.9874 | Val Profit: -70
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9749
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 20 | Train Loss: 0.0024 | Val ROC-AUC: 0.9749 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9728
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 21 | Train Loss: 0.0029 | Val ROC-AUC: 0.9728 | Val Profit: -220
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0028 | Val ROC-AUC: 0.9890 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9832
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0021 | Val ROC-AUC: 0.9832 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9824
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 24 | Train Loss: 0.0023 | Val ROC-AUC: 0.9824 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9834
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0021 | Val ROC-AUC: 0.9834 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9881
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 26 | Train Loss: 0.0021 | Val ROC-AUC: 0.9881 | Val Profit: -45
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9851
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 27 | Train Loss: 0.0023 | Val ROC-AUC: 0.9851 | Val Profit: -95
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9827
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 28 | Train Loss: 0.0022 | Val ROC-AUC: 0.9827 | Val Profit: -95
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9855
Precision: 0.4118
Recall: 1.0
F0.5-score: 0.4667
Profit: -645

Эпоха 29 | Train Loss: 0.0021 | Val ROC-AUC: 0.9855 | Val Profit: -645
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9819
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0022 | Val ROC-AUC: 0.9819 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9890006706908115
val
ROC-AUC: 0.989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9261
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0084 | Val ROC-AUC: 0.9261 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9674
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0051 | Val ROC-AUC: 0.9674 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9588
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0047 | Val ROC-AUC: 0.9588 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9461
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0050 | Val ROC-AUC: 0.9461 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9489
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0047 | Val ROC-AUC: 0.9489 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0043 | Val ROC-AUC: 0.9661 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0040 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9736
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0037 | Val ROC-AUC: 0.9736 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9751
Precision: 0.1927
Recall: 1.0
F0.5-score: 0.2298
Profit: -2095

Эпоха 9 | Train Loss: 0.0040 | Val ROC-AUC: 0.9751 | Val Profit: -2095
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0035 | Val ROC-AUC: 0.9738 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9738
Precision: 0.2283
Recall: 1.0
F0.5-score: 0.2699
Profit: -1670

Эпоха 11 | Train Loss: 0.0037 | Val ROC-AUC: 0.9738 | Val Profit: -1670
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0035 | Val ROC-AUC: 0.9738 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9753
Precision: 0.2188
Recall: 1.0
F0.5-score: 0.2593
Profit: -1770

Эпоха 13 | Train Loss: 0.0036 | Val ROC-AUC: 0.9753 | Val Profit: -1770
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0033 | Val ROC-AUC: 0.9791 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9792
Precision: 0.2471
Recall: 1.0
F0.5-score: 0.2909
Profit: -1495

Эпоха 15 | Train Loss: 0.0034 | Val ROC-AUC: 0.9792 | Val Profit: -1495

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0034 | Val ROC-AUC: 0.9795 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9776
Precision: 0.3088
Recall: 1.0
F0.5-score: 0.3584
Profit: -1070

Эпоха 17 | Train Loss: 0.0033 | Val ROC-AUC: 0.9776 | Val Profit: -1070
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9771
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 18 | Train Loss: 0.0033 | Val ROC-AUC: 0.9771 | Val Profit: -425
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.971
Precision: 0.2917
Recall: 1.0
F0.5-score: 0.3398
Profit: -1170

Эпоха 19 | Train Loss: 0.0035 | Val ROC-AUC: 0.9710 | Val Profit: -1170
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9819
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0033 | Val ROC-AUC: 0.9819 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9799
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0034 | Val ROC-AUC: 0.9799 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9847
Precision: 0.5128
Recall: 0.9524
F0.5-score: 0.565
Profit: -380

Эпоха 22 | Train Loss: 0.0031 | Val ROC-AUC: 0.9847 | Val Profit: -380
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9777
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0032 | Val ROC-AUC: 0.9777 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9859
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 24 | Train Loss: 0.0031 | Val ROC-AUC: 0.9859 | Val Profit: -595
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9869
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0030 | Val ROC-AUC: 0.9869 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.98
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 26 | Train Loss: 0.0030 | Val ROC-AUC: 0.9800 | Val Profit: -65
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.98
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0030 | Val ROC-AUC: 0.9800 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9878
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

Эпоха 28 | Train Loss: 0.0032 | Val ROC-AUC: 0.9878 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.978
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 29 | Train Loss: 0.0030 | Val ROC-AUC: 0.9780 | Val Profit: -190
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9835
Precision: 0.3889
Recall: 1.0
F0.5-score: 0.443
Profit: -720

Эпоха 30 | Train Loss: 0.0032 | Val ROC-AUC: 0.9835 | Val Profit: -720

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9877934272300468
val
ROC-AUC: 0.9878
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.901
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0094 | Val ROC-AUC: 0.9010 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9356
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0046 | Val ROC-AUC: 0.9356 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0040 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0037 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9568
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0034 | Val ROC-AUC: 0.9568 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9457
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0035 | Val ROC-AUC: 0.9457 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9568
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0030 | Val ROC-AUC: 0.9568 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0026 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9552
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0023 | Val ROC-AUC: 0.9552 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.926
Precision: 0.4545
Recall: 0.4762
F0.5-score: 0.4587
Profit: -305

Эпоха 10 | Train Loss: 0.0026 | Val ROC-AUC: 0.9260 | Val Profit: -305

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9517
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 11 | Train Loss: 0.0022 | Val ROC-AUC: 0.9517 | Val Profit: -220
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9573
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 12 | Train Loss: 0.0023 | Val ROC-AUC: 0.9573 | Val Profit: -455
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9677
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 13 | Train Loss: 0.0020 | Val ROC-AUC: 0.9677 | Val Profit: -170
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 14 | Train Loss: 0.0017 | Val ROC-AUC: 0.9563 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9163
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 15 | Train Loss: 0.0015 | Val ROC-AUC: 0.9163 | Val Profit: -85
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9537
Precision: 0.3939
Recall: 0.619
F0.5-score: 0.4248
Profit: -475

Эпоха 16 | Train Loss: 0.0016 | Val ROC-AUC: 0.9537 | Val Profit: -475
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9501
Precision: 0.4211
Recall: 0.7619
F0.5-score: 0.4624
Profit: -495

Эпоха 17 | Train Loss: 0.0027 | Val ROC-AUC: 0.9501 | Val Profit: -495
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9643
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 18 | Train Loss: 0.0023 | Val ROC-AUC: 0.9643 | Val Profit: -260
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9665
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 19 | Train Loss: 0.0018 | Val ROC-AUC: 0.9665 | Val Profit: -135
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.97
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.0019 | Val ROC-AUC: 0.9700 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9533
Precision: 0.4545
Recall: 0.4762
F0.5-score: 0.4587
Profit: -305

Эпоха 21 | Train Loss: 0.0018 | Val ROC-AUC: 0.9533 | Val Profit: -305
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9655
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 22 | Train Loss: 0.0015 | Val ROC-AUC: 0.9655 | Val Profit: -220
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9513
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 23 | Train Loss: 0.0014 | Val ROC-AUC: 0.9513 | Val Profit: -325
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9738
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 24 | Train Loss: 0.0020 | Val ROC-AUC: 0.9738 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9455
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 25 | Train Loss: 0.0014 | Val ROC-AUC: 0.9455 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9305
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0010 | Val ROC-AUC: 0.9305 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9666
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 27 | Train Loss: 0.0009 | Val ROC-AUC: 0.9666 | Val Profit: -90
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9285
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0008 | Val ROC-AUC: 0.9285 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8946
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0006 | Val ROC-AUC: 0.8946 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9192
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 30 | Train Loss: 0.0007 | Val ROC-AUC: 0.9192 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.973775989268947
val
ROC-AUC: 0.9738
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9329
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0097 | Val ROC-AUC: 0.9329 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9451
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0048 | Val ROC-AUC: 0.9451 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9586
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0042 | Val ROC-AUC: 0.9586 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9522
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0041 | Val ROC-AUC: 0.9522 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9578
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0039 | Val ROC-AUC: 0.9578 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9522
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0036 | Val ROC-AUC: 0.9522 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0041 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9703
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0035 | Val ROC-AUC: 0.9703 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.976
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0032 | Val ROC-AUC: 0.9760 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.96
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0028 | Val ROC-AUC: 0.9600 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9753
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0028 | Val ROC-AUC: 0.9753 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9688
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0026 | Val ROC-AUC: 0.9688 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9582
Precision: 0.4211
Recall: 0.7619
F0.5-score: 0.4624
Profit: -495

Эпоха 13 | Train Loss: 0.0030 | Val ROC-AUC: 0.9582 | Val Profit: -495
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9705
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 14 | Train Loss: 0.0029 | Val ROC-AUC: 0.9705 | Val Profit: -85
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9661
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 15 | Train Loss: 0.0023 | Val ROC-AUC: 0.9661 | Val Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0024 | Val ROC-AUC: 0.9706 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9699
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 17 | Train Loss: 0.0025 | Val ROC-AUC: 0.9699 | Val Profit: -300
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9676
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 18 | Train Loss: 0.0027 | Val ROC-AUC: 0.9676 | Val Profit: -410
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0026 | Val ROC-AUC: 0.9765 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0019 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.971
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 21 | Train Loss: 0.0018 | Val ROC-AUC: 0.9710 | Val Profit: -175
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9787
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 22 | Train Loss: 0.0020 | Val ROC-AUC: 0.9787 | Val Profit: -215
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9724
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 23 | Train Loss: 0.0020 | Val ROC-AUC: 0.9724 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 24 | Train Loss: 0.0020 | Val ROC-AUC: 0.9772 | Val Profit: -115
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9641
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 25 | Train Loss: 0.0021 | Val ROC-AUC: 0.9641 | Val Profit: -485
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9787
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 26 | Train Loss: 0.0024 | Val ROC-AUC: 0.9787 | Val Profit: -120
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9768
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0017 | Val ROC-AUC: 0.9768 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9702
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0015 | Val ROC-AUC: 0.9702 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9748
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 29 | Train Loss: 0.0024 | Val ROC-AUC: 0.9748 | Val Profit: -285
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9759
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0018 | Val ROC-AUC: 0.9759 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9786720321931589
val
ROC-AUC: 0.9787
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.929
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0096 | Val ROC-AUC: 0.9290 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9445
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0056 | Val ROC-AUC: 0.9445 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0052 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9537
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0047 | Val ROC-AUC: 0.9537 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0044 | Val ROC-AUC: 0.9655 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0043 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0043 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0041 | Val ROC-AUC: 0.9665 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0041 | Val ROC-AUC: 0.9675 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.938
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0038 | Val ROC-AUC: 0.9380 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9502
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0039 | Val ROC-AUC: 0.9502 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9324
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0039 | Val ROC-AUC: 0.9324 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.978
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0039 | Val ROC-AUC: 0.9780 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9688
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0037 | Val ROC-AUC: 0.9688 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9358
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0036 | Val ROC-AUC: 0.9358 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0036 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9141
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0040 | Val ROC-AUC: 0.9141 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9808
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0038 | Val ROC-AUC: 0.9808 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9763
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0035 | Val ROC-AUC: 0.9763 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0032 | Val ROC-AUC: 0.9748 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9296
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0037 | Val ROC-AUC: 0.9296 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9772
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0037 | Val ROC-AUC: 0.9772 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9787
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0033 | Val ROC-AUC: 0.9787 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.978
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0032 | Val ROC-AUC: 0.9780 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0033 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0034 | Val ROC-AUC: 0.9765 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0035 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9463
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0038 | Val ROC-AUC: 0.9463 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0035 | Val ROC-AUC: 0.9742 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0034 | Val ROC-AUC: 0.9773 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 18
Лучший ROC-AUC: 0.9808182427900738
val
ROC-AUC: 0.9808
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8787
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0104 | Val ROC-AUC: 0.8787 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9306
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0056 | Val ROC-AUC: 0.9306 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.952
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0042 | Val ROC-AUC: 0.9520 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9471
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0038 | Val ROC-AUC: 0.9471 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0032 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9171
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0038 | Val ROC-AUC: 0.9171 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9559
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0038 | Val ROC-AUC: 0.9559 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9192
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0031 | Val ROC-AUC: 0.9192 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9358
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0027 | Val ROC-AUC: 0.9358 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9559
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0027 | Val ROC-AUC: 0.9559 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9528
Precision: 0.4211
Recall: 0.381
F0.5-score: 0.4124
Profit: -300

Эпоха 11 | Train Loss: 0.0022 | Val ROC-AUC: 0.9528 | Val Profit: -300
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9512
Precision: 0.4118
Recall: 0.3333
F0.5-score: 0.3933
Profit: -285

Эпоха 12 | Train Loss: 0.0026 | Val ROC-AUC: 0.9512 | Val Profit: -285
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.959
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 13 | Train Loss: 0.0020 | Val ROC-AUC: 0.9590 | Val Profit: -270
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.973
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 14 | Train Loss: 0.0018 | Val ROC-AUC: 0.9730 | Val Profit: -150
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9581
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 15 | Train Loss: 0.0015 | Val ROC-AUC: 0.9581 | Val Profit: -170
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9635
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 16 | Train Loss: 0.0013 | Val ROC-AUC: 0.9635 | Val Profit: -175
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9675
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 17 | Train Loss: 0.0011 | Val ROC-AUC: 0.9675 | Val Profit: -135
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9608
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 18 | Train Loss: 0.0015 | Val ROC-AUC: 0.9608 | Val Profit: -325
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9642
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 19 | Train Loss: 0.0017 | Val ROC-AUC: 0.9642 | Val Profit: -170
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9678
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 20 | Train Loss: 0.0012 | Val ROC-AUC: 0.9678 | Val Profit: -205
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9694
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 21 | Train Loss: 0.0010 | Val ROC-AUC: 0.9694 | Val Profit: -115
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9714
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 22 | Train Loss: 0.0009 | Val ROC-AUC: 0.9714 | Val Profit: -90
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.971
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 23 | Train Loss: 0.0007 | Val ROC-AUC: 0.9710 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9671
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 24 | Train Loss: 0.0007 | Val ROC-AUC: 0.9671 | Val Profit: -125
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9717
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 25 | Train Loss: 0.0006 | Val ROC-AUC: 0.9717 | Val Profit: -115
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9547
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 26 | Train Loss: 0.0008 | Val ROC-AUC: 0.9547 | Val Profit: -195
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9702
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 27 | Train Loss: 0.0010 | Val ROC-AUC: 0.9702 | Val Profit: -210
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9608
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 28 | Train Loss: 0.0013 | Val ROC-AUC: 0.9608 | Val Profit: -170
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9639
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 29 | Train Loss: 0.0012 | Val ROC-AUC: 0.9639 | Val Profit: -265
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9231
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 30 | Train Loss: 0.0010 | Val ROC-AUC: 0.9231 | Val Profit: -155

Лучшая эпоха для model_9_Focal_loss: 14
Лучший ROC-AUC: 0.9730382293762575
val
ROC-AUC: 0.973
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0106 | Val ROC-AUC: 0.8795 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9391
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0057 | Val ROC-AUC: 0.9391 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9533
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 3 | Train Loss: 0.0046 | Val ROC-AUC: 0.9533 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9469
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0037 | Val ROC-AUC: 0.9469 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9387
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 5 | Train Loss: 0.0041 | Val ROC-AUC: 0.9387 | Val Profit: -135
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9662
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 6 | Train Loss: 0.0040 | Val ROC-AUC: 0.9662 | Val Profit: -115
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0031 | Val ROC-AUC: 0.9655 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9018
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0024 | Val ROC-AUC: 0.9018 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9588
Precision: 0.2
Recall: 0.0476
F0.5-score: 0.122
Profit: -195

Эпоха 9 | Train Loss: 0.0023 | Val ROC-AUC: 0.9588 | Val Profit: -195
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9543
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 10 | Train Loss: 0.0022 | Val ROC-AUC: 0.9543 | Val Profit: -180
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9619
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 11 | Train Loss: 0.0027 | Val ROC-AUC: 0.9619 | Val Profit: -250
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8366
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 12 | Train Loss: 0.0021 | Val ROC-AUC: 0.8366 | Val Profit: -115
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9524
Precision: 0.4333
Recall: 0.619
F0.5-score: 0.461
Profit: -400

Эпоха 13 | Train Loss: 0.0030 | Val ROC-AUC: 0.9524 | Val Profit: -400
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9737
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 14 | Train Loss: 0.0031 | Val ROC-AUC: 0.9737 | Val Profit: -100
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9659
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0022 | Val ROC-AUC: 0.9659 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 16 | Train Loss: 0.0017 | Val ROC-AUC: 0.9665 | Val Profit: -155
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0016 | Val ROC-AUC: 0.9679 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9618
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 18 | Train Loss: 0.0024 | Val ROC-AUC: 0.9618 | Val Profit: -385
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9706
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 19 | Train Loss: 0.0017 | Val ROC-AUC: 0.9706 | Val Profit: -95
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0014 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9571
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 21 | Train Loss: 0.0010 | Val ROC-AUC: 0.9571 | Val Profit: -185
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9649
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.0009 | Val ROC-AUC: 0.9649 | Val Profit: -115

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9659
Precision: 0.25
Recall: 1.0
F0.5-score: 0.2941
Profit: -1470

Эпоха 23 | Train Loss: 0.0018 | Val ROC-AUC: 0.9659 | Val Profit: -1470
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9513
Precision: 0.4048
Recall: 0.8095
F0.5-score: 0.4497
Profit: -560

Эпоха 24 | Train Loss: 0.0029 | Val ROC-AUC: 0.9513 | Val Profit: -560
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9751
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 25 | Train Loss: 0.0023 | Val ROC-AUC: 0.9751 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.969
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 26 | Train Loss: 0.0017 | Val ROC-AUC: 0.9690 | Val Profit: -160
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 27 | Train Loss: 0.0011 | Val ROC-AUC: 0.9584 | Val Profit: -155
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9563
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 28 | Train Loss: 0.0008 | Val ROC-AUC: 0.9563 | Val Profit: -125
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9552
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 29 | Train Loss: 0.0010 | Val ROC-AUC: 0.9552 | Val Profit: -135
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9639
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 30 | Train Loss: 0.0029 | Val ROC-AUC: 0.9639 | Val Profit: -395

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9750503018108652
val
ROC-AUC: 0.9751
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9231
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0099 | Val ROC-AUC: 0.9231 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9446
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 2 | Train Loss: 0.0057 | Val ROC-AUC: 0.9446 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9457
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0052 | Val ROC-AUC: 0.9457 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9463
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0049 | Val ROC-AUC: 0.9463 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9583
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0043 | Val ROC-AUC: 0.9583 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0043 | Val ROC-AUC: 0.9665 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0040 | Val ROC-AUC: 0.9498 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.96
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0043 | Val ROC-AUC: 0.9600 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9639
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0047 | Val ROC-AUC: 0.9639 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9526
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0041 | Val ROC-AUC: 0.9526 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0039 | Val ROC-AUC: 0.9599 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0039 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9446
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0036 | Val ROC-AUC: 0.9446 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9717
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0037 | Val ROC-AUC: 0.9717 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9663
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0036 | Val ROC-AUC: 0.9663 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0038 | Val ROC-AUC: 0.9596 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9591
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0039 | Val ROC-AUC: 0.9591 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9643
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0036 | Val ROC-AUC: 0.9643 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0039 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0037 | Val ROC-AUC: 0.9616 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9703
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0036 | Val ROC-AUC: 0.9703 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0033 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9647
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0035 | Val ROC-AUC: 0.9647 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0036 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9711
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0037 | Val ROC-AUC: 0.9711 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9734
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0035 | Val ROC-AUC: 0.9734 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0037 | Val ROC-AUC: 0.9510 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0037 | Val ROC-AUC: 0.9748 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9714
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0034 | Val ROC-AUC: 0.9714 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0034 | Val ROC-AUC: 0.9498 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9747820254862509
val
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9311
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0162 | Val ROC-AUC: 0.9311 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9518
Precision: 0.4118
Recall: 0.6667
F0.5-score: 0.4459
Profit: -465

Эпоха 2 | Train Loss: 0.0085 | Val ROC-AUC: 0.9518 | Val Profit: -465
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9618
Precision: 0.4091
Recall: 0.8571
F0.5-score: 0.4569
Profit: -575

Эпоха 3 | Train Loss: 0.0081 | Val ROC-AUC: 0.9618 | Val Profit: -575
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9722
Precision: 0.5143
Recall: 0.8571
F0.5-score: 0.559
Profit: -350

Эпоха 4 | Train Loss: 0.0073 | Val ROC-AUC: 0.9722 | Val Profit: -350
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9721
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 5 | Train Loss: 0.0064 | Val ROC-AUC: 0.9721 | Val Profit: -190
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9742
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 6 | Train Loss: 0.0057 | Val ROC-AUC: 0.9742 | Val Profit: -230
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.972
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 7 | Train Loss: 0.0054 | Val ROC-AUC: 0.9720 | Val Profit: -130
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9779
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 8 | Train Loss: 0.0043 | Val ROC-AUC: 0.9779 | Val Profit: -140
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9785
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 9 | Train Loss: 0.0045 | Val ROC-AUC: 0.9785 | Val Profit: -145
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9784
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 10 | Train Loss: 0.0045 | Val ROC-AUC: 0.9784 | Val Profit: -145
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9775
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 11 | Train Loss: 0.0045 | Val ROC-AUC: 0.9775 | Val Profit: -135
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9732
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 12 | Train Loss: 0.0045 | Val ROC-AUC: 0.9732 | Val Profit: -175
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9769
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 13 | Train Loss: 0.0040 | Val ROC-AUC: 0.9769 | Val Profit: -120
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9596
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 14 | Train Loss: 0.0033 | Val ROC-AUC: 0.9596 | Val Profit: -100
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9779
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 15 | Train Loss: 0.0043 | Val ROC-AUC: 0.9779 | Val Profit: -145
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9568
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 16 | Train Loss: 0.0039 | Val ROC-AUC: 0.9568 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9461
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 17 | Train Loss: 0.0035 | Val ROC-AUC: 0.9461 | Val Profit: -250
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9736
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 18 | Train Loss: 0.0038 | Val ROC-AUC: 0.9736 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9839
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 19 | Train Loss: 0.0031 | Val ROC-AUC: 0.9839 | Val Profit: -80
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.981
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.0029 | Val ROC-AUC: 0.9810 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9681
Precision: 0.4828
Recall: 0.6667
F0.5-score: 0.5109
Profit: -340

Эпоха 21 | Train Loss: 0.0039 | Val ROC-AUC: 0.9681 | Val Profit: -340
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9765
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 22 | Train Loss: 0.0049 | Val ROC-AUC: 0.9765 | Val Profit: -205
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9847
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 23 | Train Loss: 0.0038 | Val ROC-AUC: 0.9847 | Val Profit: -65
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9785
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 24 | Train Loss: 0.0030 | Val ROC-AUC: 0.9785 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0026 | Val ROC-AUC: 0.9650 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9399
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0020 | Val ROC-AUC: 0.9399 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9627
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 27 | Train Loss: 0.0019 | Val ROC-AUC: 0.9627 | Val Profit: -100
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9761
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 28 | Train Loss: 0.0029 | Val ROC-AUC: 0.9761 | Val Profit: -135
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9357
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 29 | Train Loss: 0.0030 | Val ROC-AUC: 0.9357 | Val Profit: -110
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9669
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0021 | Val ROC-AUC: 0.9669 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9847082494969819
val
ROC-AUC: 0.9847
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0164 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9458
Precision: 0.4
Recall: 0.1905
F0.5-score: 0.3279
Profit: -215

Эпоха 2 | Train Loss: 0.0089 | Val ROC-AUC: 0.9458 | Val Profit: -215
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9382
Precision: 0.3333
Recall: 0.1905
F0.5-score: 0.2899
Profit: -265

Эпоха 3 | Train Loss: 0.0078 | Val ROC-AUC: 0.9382 | Val Profit: -265
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9686
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 4 | Train Loss: 0.0069 | Val ROC-AUC: 0.9686 | Val Profit: -125
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9709
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 5 | Train Loss: 0.0060 | Val ROC-AUC: 0.9709 | Val Profit: -135
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9722
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 6 | Train Loss: 0.0060 | Val ROC-AUC: 0.9722 | Val Profit: -125
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.629
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0046 | Val ROC-AUC: 0.6290 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.956
Precision: 0.3556
Recall: 0.7619
F0.5-score: 0.398
Profit: -670

Эпоха 8 | Train Loss: 0.0057 | Val ROC-AUC: 0.9560 | Val Profit: -670
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9732
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0063 | Val ROC-AUC: 0.9732 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9689
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 10 | Train Loss: 0.0057 | Val ROC-AUC: 0.9689 | Val Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9752
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 11 | Train Loss: 0.0048 | Val ROC-AUC: 0.9752 | Val Profit: -100
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8884
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 12 | Train Loss: 0.0048 | Val ROC-AUC: 0.8884 | Val Profit: -145
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9756
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 13 | Train Loss: 0.0057 | Val ROC-AUC: 0.9756 | Val Profit: -120
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9791
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 14 | Train Loss: 0.0051 | Val ROC-AUC: 0.9791 | Val Profit: -70
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9647
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0046 | Val ROC-AUC: 0.9647 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0045 | Val ROC-AUC: 0.9752 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.981
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 17 | Train Loss: 0.0049 | Val ROC-AUC: 0.9810 | Val Profit: -90
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9822
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 18 | Train Loss: 0.0054 | Val ROC-AUC: 0.9822 | Val Profit: -85
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9863
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0049 | Val ROC-AUC: 0.9863 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.7779
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0040 | Val ROC-AUC: 0.7779 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9756
Precision: 0.3281
Recall: 1.0
F0.5-score: 0.3791
Profit: -970

Эпоха 21 | Train Loss: 0.0060 | Val ROC-AUC: 0.9756 | Val Profit: -970
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9843
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0053 | Val ROC-AUC: 0.9843 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.984
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0044 | Val ROC-AUC: 0.9840 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9789
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0049 | Val ROC-AUC: 0.9789 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.982
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0042 | Val ROC-AUC: 0.9820 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9828
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0045 | Val ROC-AUC: 0.9828 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9805
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0041 | Val ROC-AUC: 0.9805 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.982
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 28 | Train Loss: 0.0044 | Val ROC-AUC: 0.9820 | Val Profit: -95
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9815
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0040 | Val ROC-AUC: 0.9815 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.978
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 30 | Train Loss: 0.0049 | Val ROC-AUC: 0.9780 | Val Profit: -260

Лучшая эпоха для model_9_Focal_loss: 19
Лучший ROC-AUC: 0.986317907444668
val
ROC-AUC: 0.9863
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.928
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0167 | Val ROC-AUC: 0.9280 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9439
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0103 | Val ROC-AUC: 0.9439 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0083 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9595
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0085 | Val ROC-AUC: 0.9595 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0088 | Val ROC-AUC: 0.9706 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0082 | Val ROC-AUC: 0.9513 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9704
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 7 | Train Loss: 0.0080 | Val ROC-AUC: 0.9704 | Val Profit: -525
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9757
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0069 | Val ROC-AUC: 0.9757 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9573
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0063 | Val ROC-AUC: 0.9573 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0065 | Val ROC-AUC: 0.9765 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9787
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 11 | Train Loss: 0.0058 | Val ROC-AUC: 0.9787 | Val Profit: -130
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9826
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0059 | Val ROC-AUC: 0.9826 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9858
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0058 | Val ROC-AUC: 0.9858 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9824
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 14 | Train Loss: 0.0061 | Val ROC-AUC: 0.9824 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9869
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0058 | Val ROC-AUC: 0.9869 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9836
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 16 | Train Loss: 0.0056 | Val ROC-AUC: 0.9836 | Val Profit: -45
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9882
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0054 | Val ROC-AUC: 0.9882 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9823
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 18 | Train Loss: 0.0057 | Val ROC-AUC: 0.9823 | Val Profit: -605
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.986
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 19 | Train Loss: 0.0058 | Val ROC-AUC: 0.9860 | Val Profit: -75
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9895
Precision: 0.2877
Recall: 1.0
F0.5-score: 0.3355
Profit: -1195

Эпоха 20 | Train Loss: 0.0061 | Val ROC-AUC: 0.9895 | Val Profit: -1195

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9815
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0061 | Val ROC-AUC: 0.9815 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9852
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 22 | Train Loss: 0.0062 | Val ROC-AUC: 0.9852 | Val Profit: -65
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9885
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0055 | Val ROC-AUC: 0.9885 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9906
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0056 | Val ROC-AUC: 0.9906 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9918
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0052 | Val ROC-AUC: 0.9918 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.992
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0053 | Val ROC-AUC: 0.9920 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9925
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 27 | Train Loss: 0.0055 | Val ROC-AUC: 0.9925 | Val Profit: -820
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9905
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0054 | Val ROC-AUC: 0.9905 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.991
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0052 | Val ROC-AUC: 0.9910 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9895
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0055 | Val ROC-AUC: 0.9895 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9924882629107981
val
ROC-AUC: 0.9925
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9187
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0194 | Val ROC-AUC: 0.9187 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.953
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0101 | Val ROC-AUC: 0.9530 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9486
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0079 | Val ROC-AUC: 0.9486 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0068 | Val ROC-AUC: 0.9594 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0069 | Val ROC-AUC: 0.9555 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0065 | Val ROC-AUC: 0.9575 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9356
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0072 | Val ROC-AUC: 0.9356 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9415
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0074 | Val ROC-AUC: 0.9415 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0062 | Val ROC-AUC: 0.9636 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0049 | Val ROC-AUC: 0.9411 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9336
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0044 | Val ROC-AUC: 0.9336 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9646
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 12 | Train Loss: 0.0041 | Val ROC-AUC: 0.9646 | Val Profit: -110
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9651
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 13 | Train Loss: 0.0047 | Val ROC-AUC: 0.9651 | Val Profit: -485
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.96
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 14 | Train Loss: 0.0048 | Val ROC-AUC: 0.9600 | Val Profit: -185
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9647
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 15 | Train Loss: 0.0040 | Val ROC-AUC: 0.9647 | Val Profit: -185
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9654
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 16 | Train Loss: 0.0032 | Val ROC-AUC: 0.9654 | Val Profit: -130
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9635
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 17 | Train Loss: 0.0029 | Val ROC-AUC: 0.9635 | Val Profit: -90
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9521
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 18 | Train Loss: 0.0028 | Val ROC-AUC: 0.9521 | Val Profit: -270
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9728
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 19 | Train Loss: 0.0040 | Val ROC-AUC: 0.9728 | Val Profit: -155
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9451
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 20 | Train Loss: 0.0035 | Val ROC-AUC: 0.9451 | Val Profit: -205
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.917
Precision: 0.3871
Recall: 0.5714
F0.5-score: 0.4138
Profit: -460

Эпоха 21 | Train Loss: 0.0033 | Val ROC-AUC: 0.9170 | Val Profit: -460
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9072
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0038 | Val ROC-AUC: 0.9072 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9801
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 23 | Train Loss: 0.0024 | Val ROC-AUC: 0.9801 | Val Profit: -85
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9775
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 24 | Train Loss: 0.0025 | Val ROC-AUC: 0.9775 | Val Profit: -100
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.967
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 25 | Train Loss: 0.0020 | Val ROC-AUC: 0.9670 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9476
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 26 | Train Loss: 0.0017 | Val ROC-AUC: 0.9476 | Val Profit: -90
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9104
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 27 | Train Loss: 0.0020 | Val ROC-AUC: 0.9104 | Val Profit: -140
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9002
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0014 | Val ROC-AUC: 0.9002 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8802
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 29 | Train Loss: 0.0018 | Val ROC-AUC: 0.8802 | Val Profit: -160
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9494
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 30 | Train Loss: 0.0014 | Val ROC-AUC: 0.9494 | Val Profit: -85

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9800804828973843
val
ROC-AUC: 0.9801
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8994
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0199 | Val ROC-AUC: 0.8994 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.8955
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0107 | Val ROC-AUC: 0.8955 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9428
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0088 | Val ROC-AUC: 0.9428 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9296
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0077 | Val ROC-AUC: 0.9296 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0084 | Val ROC-AUC: 0.9611 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9635
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0079 | Val ROC-AUC: 0.9635 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9532
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 7 | Train Loss: 0.0068 | Val ROC-AUC: 0.9532 | Val Profit: -140
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9653
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 8 | Train Loss: 0.0054 | Val ROC-AUC: 0.9653 | Val Profit: -215
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9623
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 9 | Train Loss: 0.0050 | Val ROC-AUC: 0.9623 | Val Profit: -220
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9728
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 10 | Train Loss: 0.0049 | Val ROC-AUC: 0.9728 | Val Profit: -125
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9752
Precision: 0.5294
Recall: 0.8571
F0.5-score: 0.5732
Profit: -325

Эпоха 11 | Train Loss: 0.0050 | Val ROC-AUC: 0.9752 | Val Profit: -325
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9742
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 12 | Train Loss: 0.0043 | Val ROC-AUC: 0.9742 | Val Profit: -115
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9736
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 13 | Train Loss: 0.0037 | Val ROC-AUC: 0.9736 | Val Profit: -200
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9804
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 14 | Train Loss: 0.0040 | Val ROC-AUC: 0.9804 | Val Profit: -130
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9781
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0032 | Val ROC-AUC: 0.9781 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.981
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

Эпоха 16 | Train Loss: 0.0037 | Val ROC-AUC: 0.9810 | Val Profit: -430
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9564
Precision: 0.3721
Recall: 0.7619
F0.5-score: 0.4145
Profit: -620

Эпоха 17 | Train Loss: 0.0062 | Val ROC-AUC: 0.9564 | Val Profit: -620
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9777
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 18 | Train Loss: 0.0050 | Val ROC-AUC: 0.9777 | Val Profit: -95
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9784
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0038 | Val ROC-AUC: 0.9784 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0032 | Val ROC-AUC: 0.9791 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9756
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0026 | Val ROC-AUC: 0.9756 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9752
Precision: 0.4872
Recall: 0.9048
F0.5-score: 0.5367
Profit: -415

Эпоха 22 | Train Loss: 0.0029 | Val ROC-AUC: 0.9752 | Val Profit: -415
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9696
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 23 | Train Loss: 0.0034 | Val ROC-AUC: 0.9696 | Val Profit: -235
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9718
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 24 | Train Loss: 0.0041 | Val ROC-AUC: 0.9718 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9742
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 25 | Train Loss: 0.0039 | Val ROC-AUC: 0.9742 | Val Profit: -70
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9788
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 26 | Train Loss: 0.0046 | Val ROC-AUC: 0.9788 | Val Profit: -65
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9804
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0033 | Val ROC-AUC: 0.9804 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9382
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 28 | Train Loss: 0.0023 | Val ROC-AUC: 0.9382 | Val Profit: -145
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9058
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 29 | Train Loss: 0.0021 | Val ROC-AUC: 0.9058 | Val Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.976
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 30 | Train Loss: 0.0020 | Val ROC-AUC: 0.9760 | Val Profit: -145

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.980952380952381
val
ROC-AUC: 0.981
Precision: 0.4878
Recall: 0.9524
F0.5-score: 0.5405
Profit: -430

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0204 | Val ROC-AUC: 0.8755 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9496
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0114 | Val ROC-AUC: 0.9496 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9398
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0093 | Val ROC-AUC: 0.9398 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.956
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0101 | Val ROC-AUC: 0.9560 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.941
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0085 | Val ROC-AUC: 0.9410 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0081 | Val ROC-AUC: 0.9544 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.96
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0072 | Val ROC-AUC: 0.9600 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0076 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9332
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0077 | Val ROC-AUC: 0.9332 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9631
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0070 | Val ROC-AUC: 0.9631 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9715
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0074 | Val ROC-AUC: 0.9715 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9757
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0069 | Val ROC-AUC: 0.9757 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9684
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0070 | Val ROC-AUC: 0.9684 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9763
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0064 | Val ROC-AUC: 0.9763 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0061 | Val ROC-AUC: 0.9752 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9779
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0066 | Val ROC-AUC: 0.9779 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9493
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0062 | Val ROC-AUC: 0.9493 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0058 | Val ROC-AUC: 0.9725 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9634
Precision: 0.4038
Recall: 1.0
F0.5-score: 0.4585
Profit: -670

Эпоха 19 | Train Loss: 0.0058 | Val ROC-AUC: 0.9634 | Val Profit: -670
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9771
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0057 | Val ROC-AUC: 0.9771 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9721
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0058 | Val ROC-AUC: 0.9721 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0059 | Val ROC-AUC: 0.9816 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9736
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0053 | Val ROC-AUC: 0.9736 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9599
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 24 | Train Loss: 0.0065 | Val ROC-AUC: 0.9599 | Val Profit: -680
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9808
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 25 | Train Loss: 0.0059 | Val ROC-AUC: 0.9808 | Val Profit: -80
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9811
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0053 | Val ROC-AUC: 0.9811 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9819
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 27 | Train Loss: 0.0058 | Val ROC-AUC: 0.9819 | Val Profit: -90

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9808
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0050 | Val ROC-AUC: 0.9808 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9757
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 29 | Train Loss: 0.0055 | Val ROC-AUC: 0.9757 | Val Profit: -245
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9793
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0051 | Val ROC-AUC: 0.9793 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9818913480885312
val
ROC-AUC: 0.9819
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8716
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0201 | Val ROC-AUC: 0.8716 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0104 | Val ROC-AUC: 0.9268 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0081 | Val ROC-AUC: 0.9567 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.95
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0076 | Val ROC-AUC: 0.9500 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.8805
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0070 | Val ROC-AUC: 0.8805 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9504
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0068 | Val ROC-AUC: 0.9504 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9632
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0057 | Val ROC-AUC: 0.9632 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0049 | Val ROC-AUC: 0.9698 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9256
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0061 | Val ROC-AUC: 0.9256 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9666
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0056 | Val ROC-AUC: 0.9666 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.972
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 11 | Train Loss: 0.0044 | Val ROC-AUC: 0.9720 | Val Profit: -180
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9682
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 12 | Train Loss: 0.0042 | Val ROC-AUC: 0.9682 | Val Profit: -125
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9646
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 13 | Train Loss: 0.0037 | Val ROC-AUC: 0.9646 | Val Profit: -260
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9557
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 14 | Train Loss: 0.0035 | Val ROC-AUC: 0.9557 | Val Profit: -360
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9731
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 15 | Train Loss: 0.0030 | Val ROC-AUC: 0.9731 | Val Profit: -180
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9713
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 16 | Train Loss: 0.0027 | Val ROC-AUC: 0.9713 | Val Profit: -235
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9594
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 17 | Train Loss: 0.0022 | Val ROC-AUC: 0.9594 | Val Profit: -215
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9669
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 18 | Train Loss: 0.0023 | Val ROC-AUC: 0.9669 | Val Profit: -165
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9661
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 19 | Train Loss: 0.0021 | Val ROC-AUC: 0.9661 | Val Profit: -200
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9535
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 20 | Train Loss: 0.0019 | Val ROC-AUC: 0.9535 | Val Profit: -200
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.97
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 21 | Train Loss: 0.0017 | Val ROC-AUC: 0.9700 | Val Profit: -185
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9742
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 22 | Train Loss: 0.0015 | Val ROC-AUC: 0.9742 | Val Profit: -180
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9738
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 23 | Train Loss: 0.0015 | Val ROC-AUC: 0.9738 | Val Profit: -180
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9738
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 24 | Train Loss: 0.0014 | Val ROC-AUC: 0.9738 | Val Profit: -170
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9736
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 25 | Train Loss: 0.0014 | Val ROC-AUC: 0.9736 | Val Profit: -170
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9728
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 26 | Train Loss: 0.0014 | Val ROC-AUC: 0.9728 | Val Profit: -170
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9729
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 27 | Train Loss: 0.0014 | Val ROC-AUC: 0.9729 | Val Profit: -170
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9729
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 28 | Train Loss: 0.0014 | Val ROC-AUC: 0.9729 | Val Profit: -170
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9726
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 29 | Train Loss: 0.0014 | Val ROC-AUC: 0.9726 | Val Profit: -170
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9725
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 30 | Train Loss: 0.0014 | Val ROC-AUC: 0.9725 | Val Profit: -170

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9742454728370221
val
ROC-AUC: 0.9742
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9383
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0213 | Val ROC-AUC: 0.9383 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.932
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0117 | Val ROC-AUC: 0.9320 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9615
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0090 | Val ROC-AUC: 0.9615 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9541
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0074 | Val ROC-AUC: 0.9541 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9415
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0073 | Val ROC-AUC: 0.9415 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9326
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0082 | Val ROC-AUC: 0.9326 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0072 | Val ROC-AUC: 0.9661 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.96
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0062 | Val ROC-AUC: 0.9600 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0056 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9327
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0068 | Val ROC-AUC: 0.9327 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9331
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0065 | Val ROC-AUC: 0.9331 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9104
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0071 | Val ROC-AUC: 0.9104 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9674
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0056 | Val ROC-AUC: 0.9674 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9632
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0050 | Val ROC-AUC: 0.9632 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9313
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 15 | Train Loss: 0.0042 | Val ROC-AUC: 0.9313 | Val Profit: -150
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9709
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 16 | Train Loss: 0.0038 | Val ROC-AUC: 0.9709 | Val Profit: -180
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9302
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 17 | Train Loss: 0.0037 | Val ROC-AUC: 0.9302 | Val Profit: -185
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9409
Precision: 0.3889
Recall: 0.3333
F0.5-score: 0.3763
Profit: -310

Эпоха 18 | Train Loss: 0.0038 | Val ROC-AUC: 0.9409 | Val Profit: -310
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.951
Precision: 0.3913
Recall: 0.8571
F0.5-score: 0.439
Profit: -625

Эпоха 19 | Train Loss: 0.0051 | Val ROC-AUC: 0.9510 | Val Profit: -625
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.971
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 20 | Train Loss: 0.0047 | Val ROC-AUC: 0.9710 | Val Profit: -210
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9742
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 21 | Train Loss: 0.0035 | Val ROC-AUC: 0.9742 | Val Profit: -65
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9611
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 22 | Train Loss: 0.0036 | Val ROC-AUC: 0.9611 | Val Profit: -210
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9517
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 23 | Train Loss: 0.0047 | Val ROC-AUC: 0.9517 | Val Profit: -265
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9733
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 24 | Train Loss: 0.0038 | Val ROC-AUC: 0.9733 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9734
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 25 | Train Loss: 0.0030 | Val ROC-AUC: 0.9734 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9776
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 26 | Train Loss: 0.0030 | Val ROC-AUC: 0.9776 | Val Profit: -70
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9698
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 27 | Train Loss: 0.0025 | Val ROC-AUC: 0.9698 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.7685
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 28 | Train Loss: 0.0023 | Val ROC-AUC: 0.7685 | Val Profit: -135
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.959
Precision: 0.3509
Recall: 0.9524
F0.5-score: 0.4016
Profit: -830

Эпоха 29 | Train Loss: 0.0033 | Val ROC-AUC: 0.9590 | Val Profit: -830
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9759
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 30 | Train Loss: 0.0041 | Val ROC-AUC: 0.9759 | Val Profit: -180

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9775989268947015
val
ROC-AUC: 0.9776
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8381
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0211 | Val ROC-AUC: 0.8381 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9366
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0121 | Val ROC-AUC: 0.9366 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9579
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0097 | Val ROC-AUC: 0.9579 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.8899
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0090 | Val ROC-AUC: 0.8899 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9297
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0089 | Val ROC-AUC: 0.9297 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9586
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0082 | Val ROC-AUC: 0.9586 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9638
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0077 | Val ROC-AUC: 0.9638 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0064 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9439
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0061 | Val ROC-AUC: 0.9439 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9518
Precision: 0.3333
Recall: 0.619
F0.5-score: 0.3672
Profit: -625

Эпоха 10 | Train Loss: 0.0071 | Val ROC-AUC: 0.9518 | Val Profit: -625
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9404
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 11 | Train Loss: 0.0059 | Val ROC-AUC: 0.9404 | Val Profit: -185
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9598
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 12 | Train Loss: 0.0060 | Val ROC-AUC: 0.9598 | Val Profit: -75
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9577
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 13 | Train Loss: 0.0062 | Val ROC-AUC: 0.9577 | Val Profit: -665
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0062 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9415
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0056 | Val ROC-AUC: 0.9415 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9595
Precision: 0.4667
Recall: 0.6667
F0.5-score: 0.4965
Profit: -365

Эпоха 16 | Train Loss: 0.0058 | Val ROC-AUC: 0.9595 | Val Profit: -365

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0066 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0053 | Val ROC-AUC: 0.9752 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9696
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 19 | Train Loss: 0.0070 | Val ROC-AUC: 0.9696 | Val Profit: -125
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9415
Precision: 0.3636
Recall: 0.5714
F0.5-score: 0.3922
Profit: -510

Эпоха 20 | Train Loss: 0.0061 | Val ROC-AUC: 0.9415 | Val Profit: -510
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9749
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 21 | Train Loss: 0.0071 | Val ROC-AUC: 0.9749 | Val Profit: -165
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9706
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 22 | Train Loss: 0.0054 | Val ROC-AUC: 0.9706 | Val Profit: -95
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.972
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0049 | Val ROC-AUC: 0.9720 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9827
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 24 | Train Loss: 0.0048 | Val ROC-AUC: 0.9827 | Val Profit: -65
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9734
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0046 | Val ROC-AUC: 0.9734 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9793
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 26 | Train Loss: 0.0063 | Val ROC-AUC: 0.9793 | Val Profit: -250
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9789
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0058 | Val ROC-AUC: 0.9789 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9751
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 28 | Train Loss: 0.0052 | Val ROC-AUC: 0.9751 | Val Profit: -95
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9726
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 29 | Train Loss: 0.0051 | Val ROC-AUC: 0.9726 | Val Profit: -100
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9783
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0053 | Val ROC-AUC: 0.9783 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9826961770623742
val
ROC-AUC: 0.9827
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9127
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0327 | Val ROC-AUC: 0.9127 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9406
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0167 | Val ROC-AUC: 0.9406 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.931
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0150 | Val ROC-AUC: 0.9310 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9657
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0152 | Val ROC-AUC: 0.9657 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0136 | Val ROC-AUC: 0.9636 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0132 | Val ROC-AUC: 0.9344 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0134 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0116 | Val ROC-AUC: 0.9675 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9767
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0103 | Val ROC-AUC: 0.9767 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9742
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 10 | Train Loss: 0.0117 | Val ROC-AUC: 0.9742 | Val Profit: -90
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9612
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 11 | Train Loss: 0.0112 | Val ROC-AUC: 0.9612 | Val Profit: -345
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9776
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 12 | Train Loss: 0.0097 | Val ROC-AUC: 0.9776 | Val Profit: -95
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9756
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 13 | Train Loss: 0.0086 | Val ROC-AUC: 0.9756 | Val Profit: -155
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9791
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 14 | Train Loss: 0.0076 | Val ROC-AUC: 0.9791 | Val Profit: -170
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9773
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 15 | Train Loss: 0.0090 | Val ROC-AUC: 0.9773 | Val Profit: -85
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9757
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 16 | Train Loss: 0.0098 | Val ROC-AUC: 0.9757 | Val Profit: -215
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9694
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 17 | Train Loss: 0.0085 | Val ROC-AUC: 0.9694 | Val Profit: -110
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9816
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 18 | Train Loss: 0.0085 | Val ROC-AUC: 0.9816 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9575
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 19 | Train Loss: 0.0075 | Val ROC-AUC: 0.9575 | Val Profit: -135
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9654
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 20 | Train Loss: 0.0058 | Val ROC-AUC: 0.9654 | Val Profit: -135
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9673
Precision: 0.3922
Recall: 0.9524
F0.5-score: 0.4444
Profit: -680

Эпоха 21 | Train Loss: 0.0081 | Val ROC-AUC: 0.9673 | Val Profit: -680
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9728
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 22 | Train Loss: 0.0119 | Val ROC-AUC: 0.9728 | Val Profit: -275
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9649
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 23 | Train Loss: 0.0086 | Val ROC-AUC: 0.9649 | Val Profit: -195
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9419
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 24 | Train Loss: 0.0081 | Val ROC-AUC: 0.9419 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9694
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 25 | Train Loss: 0.0096 | Val ROC-AUC: 0.9694 | Val Profit: -605
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9781
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 26 | Train Loss: 0.0101 | Val ROC-AUC: 0.9781 | Val Profit: -125
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9834
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 27 | Train Loss: 0.0081 | Val ROC-AUC: 0.9834 | Val Profit: -95
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9777
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0073 | Val ROC-AUC: 0.9777 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9824
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0060 | Val ROC-AUC: 0.9824 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9751
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.0052 | Val ROC-AUC: 0.9751 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9833668678739101
val
ROC-AUC: 0.9834
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9587
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 1 | Train Loss: 0.0323 | Val ROC-AUC: 0.9587 | Val Profit: -110
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9355
Precision: 0.3016
Recall: 0.9048
F0.5-score: 0.348
Profit: -1015

Эпоха 2 | Train Loss: 0.0162 | Val ROC-AUC: 0.9355 | Val Profit: -1015
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9624
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 3 | Train Loss: 0.0143 | Val ROC-AUC: 0.9624 | Val Profit: -180
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9709
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 4 | Train Loss: 0.0130 | Val ROC-AUC: 0.9709 | Val Profit: -335
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9713
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 5 | Train Loss: 0.0114 | Val ROC-AUC: 0.9713 | Val Profit: -95
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9681
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 6 | Train Loss: 0.0102 | Val ROC-AUC: 0.9681 | Val Profit: -245
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9632
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 7 | Train Loss: 0.0113 | Val ROC-AUC: 0.9632 | Val Profit: -320
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9765
Precision: 0.475
Recall: 0.9048
F0.5-score: 0.5249
Profit: -440

Эпоха 8 | Train Loss: 0.0120 | Val ROC-AUC: 0.9765 | Val Profit: -440
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9777
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 9 | Train Loss: 0.0115 | Val ROC-AUC: 0.9777 | Val Profit: -225
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9779
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 10 | Train Loss: 0.0097 | Val ROC-AUC: 0.9779 | Val Profit: -120
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9759
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 11 | Train Loss: 0.0097 | Val ROC-AUC: 0.9759 | Val Profit: -130
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9781
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 12 | Train Loss: 0.0101 | Val ROC-AUC: 0.9781 | Val Profit: -95
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 13 | Train Loss: 0.0094 | Val ROC-AUC: 0.9772 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9779
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 14 | Train Loss: 0.0139 | Val ROC-AUC: 0.9779 | Val Profit: -160
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9799
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 15 | Train Loss: 0.0101 | Val ROC-AUC: 0.9799 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.97
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0084 | Val ROC-AUC: 0.9700 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9836
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0085 | Val ROC-AUC: 0.9836 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9776
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 18 | Train Loss: 0.0078 | Val ROC-AUC: 0.9776 | Val Profit: -155
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9615
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 19 | Train Loss: 0.0081 | Val ROC-AUC: 0.9615 | Val Profit: -210
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0109 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9763
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0084 | Val ROC-AUC: 0.9763 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9816
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 22 | Train Loss: 0.0115 | Val ROC-AUC: 0.9816 | Val Profit: -235
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9818
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 23 | Train Loss: 0.0107 | Val ROC-AUC: 0.9818 | Val Profit: -100
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.0079 | Val ROC-AUC: 0.9752 | Val Profit: -130
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0079 | Val ROC-AUC: 0.9706 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9789
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0076 | Val ROC-AUC: 0.9789 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9842
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 27 | Train Loss: 0.0073 | Val ROC-AUC: 0.9842 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9638
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 28 | Train Loss: 0.0094 | Val ROC-AUC: 0.9638 | Val Profit: -235
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0091 | Val ROC-AUC: 0.9818 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9826
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0074 | Val ROC-AUC: 0.9826 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9841716968477532
val
ROC-AUC: 0.9842
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9379
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0326 | Val ROC-AUC: 0.9379 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9229
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0176 | Val ROC-AUC: 0.9229 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9451
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 3 | Train Loss: 0.0168 | Val ROC-AUC: 0.9451 | Val Profit: -95
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0141 | Val ROC-AUC: 0.9730 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0143 | Val ROC-AUC: 0.9744 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9505
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0159 | Val ROC-AUC: 0.9505 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0142 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9776
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0128 | Val ROC-AUC: 0.9776 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9784
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0125 | Val ROC-AUC: 0.9784 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9779
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 10 | Train Loss: 0.0117 | Val ROC-AUC: 0.9779 | Val Profit: -95
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9823
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 11 | Train Loss: 0.0113 | Val ROC-AUC: 0.9823 | Val Profit: -80
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9755
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 12 | Train Loss: 0.0125 | Val ROC-AUC: 0.9755 | Val Profit: -200
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9815
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0107 | Val ROC-AUC: 0.9815 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9788
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0110 | Val ROC-AUC: 0.9788 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9844
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0103 | Val ROC-AUC: 0.9844 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9822
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 16 | Train Loss: 0.0106 | Val ROC-AUC: 0.9822 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.978
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 17 | Train Loss: 0.0104 | Val ROC-AUC: 0.9780 | Val Profit: -205
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9844
Precision: 0.2143
Recall: 1.0
F0.5-score: 0.2542
Profit: -1820

Эпоха 18 | Train Loss: 0.0129 | Val ROC-AUC: 0.9844 | Val Profit: -1820
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.982
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0108 | Val ROC-AUC: 0.9820 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.982
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0106 | Val ROC-AUC: 0.9820 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9854
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0095 | Val ROC-AUC: 0.9854 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0107 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9867
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0105 | Val ROC-AUC: 0.9867 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.986
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 24 | Train Loss: 0.0095 | Val ROC-AUC: 0.9860 | Val Profit: -85
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9858
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0094 | Val ROC-AUC: 0.9858 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9895
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 26 | Train Loss: 0.0095 | Val ROC-AUC: 0.9895 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9768
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0100 | Val ROC-AUC: 0.9768 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.982
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0103 | Val ROC-AUC: 0.9820 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9887
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0100 | Val ROC-AUC: 0.9887 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9901
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0100 | Val ROC-AUC: 0.9901 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.990073775989269

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

val
ROC-AUC: 0.9901
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9188
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0383 | Val ROC-AUC: 0.9188 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9468
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0200 | Val ROC-AUC: 0.9468 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0157 | Val ROC-AUC: 0.9543 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9604
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0126 | Val ROC-AUC: 0.9604 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9539
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0121 | Val ROC-AUC: 0.9539 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9276
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0134 | Val ROC-AUC: 0.9276 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9119
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0156 | Val ROC-AUC: 0.9119 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9395
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0140 | Val ROC-AUC: 0.9395 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9163
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0107 | Val ROC-AUC: 0.9163 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0094 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9516
Precision: 0.2727
Recall: 0.1429
F0.5-score: 0.2308
Profit: -275

Эпоха 11 | Train Loss: 0.0085 | Val ROC-AUC: 0.9516 | Val Profit: -275
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9317
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 12 | Train Loss: 0.0079 | Val ROC-AUC: 0.9317 | Val Profit: -185
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9256
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 13 | Train Loss: 0.0070 | Val ROC-AUC: 0.9256 | Val Profit: -180
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9666
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 14 | Train Loss: 0.0073 | Val ROC-AUC: 0.9666 | Val Profit: -145
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9326
Precision: 0.4
Recall: 0.381
F0.5-score: 0.396
Profit: -325

Эпоха 15 | Train Loss: 0.0063 | Val ROC-AUC: 0.9326 | Val Profit: -325
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9286
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 16 | Train Loss: 0.0065 | Val ROC-AUC: 0.9286 | Val Profit: -205
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9421
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 17 | Train Loss: 0.0065 | Val ROC-AUC: 0.9421 | Val Profit: -280
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9231
Precision: 0.4242
Recall: 0.6667
F0.5-score: 0.4575
Profit: -440

Эпоха 18 | Train Loss: 0.0071 | Val ROC-AUC: 0.9231 | Val Profit: -440
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9671
Precision: 0.5714
Recall: 0.7619
F0.5-score: 0.6015
Profit: -245

Эпоха 19 | Train Loss: 0.0094 | Val ROC-AUC: 0.9671 | Val Profit: -245
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.969
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 20 | Train Loss: 0.0096 | Val ROC-AUC: 0.9690 | Val Profit: -310
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9201
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 21 | Train Loss: 0.0070 | Val ROC-AUC: 0.9201 | Val Profit: -215
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8165
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 22 | Train Loss: 0.0059 | Val ROC-AUC: 0.8165 | Val Profit: -110
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9489
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 23 | Train Loss: 0.0073 | Val ROC-AUC: 0.9489 | Val Profit: -260
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9631
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 24 | Train Loss: 0.0079 | Val ROC-AUC: 0.9631 | Val Profit: -135
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9745
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 25 | Train Loss: 0.0059 | Val ROC-AUC: 0.9745 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9091
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0041 | Val ROC-AUC: 0.9091 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9679
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 27 | Train Loss: 0.0031 | Val ROC-AUC: 0.9679 | Val Profit: -70
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9337
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 28 | Train Loss: 0.0029 | Val ROC-AUC: 0.9337 | Val Profit: -170
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9223
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 29 | Train Loss: 0.0035 | Val ROC-AUC: 0.9223 | Val Profit: -150
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.941
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 30 | Train Loss: 0.0033 | Val ROC-AUC: 0.9410 | Val Profit: -75

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9745137491616365
val
ROC-AUC: 0.9745
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8868
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0383 | Val ROC-AUC: 0.8868 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9305
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0221 | Val ROC-AUC: 0.9305 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9315
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0177 | Val ROC-AUC: 0.9315 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9335
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 4 | Train Loss: 0.0161 | Val ROC-AUC: 0.9335 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9631
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0153 | Val ROC-AUC: 0.9631 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0154 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9654
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0133 | Val ROC-AUC: 0.9654 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9662
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0124 | Val ROC-AUC: 0.9662 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9644
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0126 | Val ROC-AUC: 0.9644 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0118 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9649
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0102 | Val ROC-AUC: 0.9649 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9658
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 12 | Train Loss: 0.0094 | Val ROC-AUC: 0.9658 | Val Profit: -45
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.8975
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 13 | Train Loss: 0.0079 | Val ROC-AUC: 0.8975 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.948
Precision: 0.3636
Recall: 0.9524
F0.5-score: 0.4149
Profit: -780

Эпоха 14 | Train Loss: 0.0084 | Val ROC-AUC: 0.9480 | Val Profit: -780
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9693
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 15 | Train Loss: 0.0118 | Val ROC-AUC: 0.9693 | Val Profit: -265
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9618
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 16 | Train Loss: 0.0107 | Val ROC-AUC: 0.9618 | Val Profit: -180
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9685
Precision: 0.4667
Recall: 0.6667
F0.5-score: 0.4965
Profit: -365

Эпоха 17 | Train Loss: 0.0094 | Val ROC-AUC: 0.9685 | Val Profit: -365
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9791
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 18 | Train Loss: 0.0081 | Val ROC-AUC: 0.9791 | Val Profit: -90
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9732
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 19 | Train Loss: 0.0063 | Val ROC-AUC: 0.9732 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8429
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 20 | Train Loss: 0.0059 | Val ROC-AUC: 0.8429 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9508
Precision: 0.425
Recall: 0.8095
F0.5-score: 0.4696
Profit: -510

Эпоха 21 | Train Loss: 0.0063 | Val ROC-AUC: 0.9508 | Val Profit: -510
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9783
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 22 | Train Loss: 0.0098 | Val ROC-AUC: 0.9783 | Val Profit: -335
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9755
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 23 | Train Loss: 0.0067 | Val ROC-AUC: 0.9755 | Val Profit: -165
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.912
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 24 | Train Loss: 0.0055 | Val ROC-AUC: 0.9120 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9427
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 25 | Train Loss: 0.0050 | Val ROC-AUC: 0.9427 | Val Profit: -135
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9748
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 26 | Train Loss: 0.0052 | Val ROC-AUC: 0.9748 | Val Profit: -240
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9771
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 27 | Train Loss: 0.0062 | Val ROC-AUC: 0.9771 | Val Profit: -155
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9791
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 28 | Train Loss: 0.0057 | Val ROC-AUC: 0.9791 | Val Profit: -200
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9785
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0049 | Val ROC-AUC: 0.9785 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.956
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 30 | Train Loss: 0.0082 | Val ROC-AUC: 0.9560 | Val Profit: -240

Лучшая эпоха для model_9_Focal_loss: 18
Лучший ROC-AUC: 0.9790744466800805
val
ROC-AUC: 0.9791
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9082
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0391 | Val ROC-AUC: 0.9082 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9371
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0198 | Val ROC-AUC: 0.9371 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9174
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0185 | Val ROC-AUC: 0.9174 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9297
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0170 | Val ROC-AUC: 0.9297 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9631
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0164 | Val ROC-AUC: 0.9631 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9627
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0153 | Val ROC-AUC: 0.9627 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9704
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0150 | Val ROC-AUC: 0.9704 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9757
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0130 | Val ROC-AUC: 0.9757 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0126 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9733
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0130 | Val ROC-AUC: 0.9733 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0119 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0114 | Val ROC-AUC: 0.9748 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9718
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 13 | Train Loss: 0.0112 | Val ROC-AUC: 0.9718 | Val Profit: -95
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9563
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 14 | Train Loss: 0.0108 | Val ROC-AUC: 0.9563 | Val Profit: -420
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9769
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 15 | Train Loss: 0.0132 | Val ROC-AUC: 0.9769 | Val Profit: -140
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0115 | Val ROC-AUC: 0.9765 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0101 | Val ROC-AUC: 0.9765 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9745
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 18 | Train Loss: 0.0100 | Val ROC-AUC: 0.9745 | Val Profit: -145
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0091 | Val ROC-AUC: 0.9785 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.971
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 20 | Train Loss: 0.0108 | Val ROC-AUC: 0.9710 | Val Profit: -330
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9768
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0113 | Val ROC-AUC: 0.9768 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9756
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 22 | Train Loss: 0.0091 | Val ROC-AUC: 0.9756 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9748
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 23 | Train Loss: 0.0090 | Val ROC-AUC: 0.9748 | Val Profit: -95
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0087 | Val ROC-AUC: 0.9791 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9791
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 25 | Train Loss: 0.0081 | Val ROC-AUC: 0.9791 | Val Profit: -90
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9791
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 26 | Train Loss: 0.0091 | Val ROC-AUC: 0.9791 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9753
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 27 | Train Loss: 0.0093 | Val ROC-AUC: 0.9753 | Val Profit: -230
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9717
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 28 | Train Loss: 0.0098 | Val ROC-AUC: 0.9717 | Val Profit: -125
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9714
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 29 | Train Loss: 0.0109 | Val ROC-AUC: 0.9714 | Val Profit: -260
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9698
Precision: 0.3684
Recall: 1.0
F0.5-score: 0.4217
Profit: -795

Эпоха 30 | Train Loss: 0.0135 | Val ROC-AUC: 0.9698 | Val Profit: -795

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9790744466800805
val
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8715
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0405 | Val ROC-AUC: 0.8715 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.927
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0217 | Val ROC-AUC: 0.9270 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9529
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0173 | Val ROC-AUC: 0.9529 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9601
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0140 | Val ROC-AUC: 0.9601 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9431
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0126 | Val ROC-AUC: 0.9431 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9064
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0122 | Val ROC-AUC: 0.9064 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9627
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0113 | Val ROC-AUC: 0.9627 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9375
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0097 | Val ROC-AUC: 0.9375 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9422
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 9 | Train Loss: 0.0094 | Val ROC-AUC: 0.9422 | Val Profit: -350
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9477
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 10 | Train Loss: 0.0111 | Val ROC-AUC: 0.9477 | Val Profit: -395
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9558
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 11 | Train Loss: 0.0082 | Val ROC-AUC: 0.9558 | Val Profit: -125
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9606
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 12 | Train Loss: 0.0067 | Val ROC-AUC: 0.9606 | Val Profit: -185
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9746
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 13 | Train Loss: 0.0064 | Val ROC-AUC: 0.9746 | Val Profit: -90
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9486
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 14 | Train Loss: 0.0054 | Val ROC-AUC: 0.9486 | Val Profit: -135
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9671
Precision: 0.4839
Recall: 0.7143
F0.5-score: 0.5172
Profit: -355

Эпоха 15 | Train Loss: 0.0058 | Val ROC-AUC: 0.9671 | Val Profit: -355
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9755
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 16 | Train Loss: 0.0057 | Val ROC-AUC: 0.9755 | Val Profit: -100
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9603
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 17 | Train Loss: 0.0045 | Val ROC-AUC: 0.9603 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9041
Precision: 0.3824
Recall: 0.619
F0.5-score: 0.414
Profit: -500

Эпоха 18 | Train Loss: 0.0062 | Val ROC-AUC: 0.9041 | Val Profit: -500
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9807
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 19 | Train Loss: 0.0070 | Val ROC-AUC: 0.9807 | Val Profit: -150
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9775
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 20 | Train Loss: 0.0052 | Val ROC-AUC: 0.9775 | Val Profit: -135
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.971
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 21 | Train Loss: 0.0056 | Val ROC-AUC: 0.9710 | Val Profit: -175
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9048
Precision: 0.3704
Recall: 0.4762
F0.5-score: 0.3876
Profit: -430

Эпоха 22 | Train Loss: 0.0056 | Val ROC-AUC: 0.9048 | Val Profit: -430
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9356
Precision: 1.0
Recall: 0.381
F0.5-score: 0.7547
Profit: -25

Эпоха 23 | Train Loss: 0.0058 | Val ROC-AUC: 0.9356 | Val Profit: -25
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.939
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 24 | Train Loss: 0.0034 | Val ROC-AUC: 0.9390 | Val Profit: -115
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9379
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 25 | Train Loss: 0.0025 | Val ROC-AUC: 0.9379 | Val Profit: -65
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9382
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 26 | Train Loss: 0.0021 | Val ROC-AUC: 0.9382 | Val Profit: -60
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9382
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 27 | Train Loss: 0.0022 | Val ROC-AUC: 0.9382 | Val Profit: -75
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9349
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 28 | Train Loss: 0.0019 | Val ROC-AUC: 0.9349 | Val Profit: -60
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9362
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 29 | Train Loss: 0.0016 | Val ROC-AUC: 0.9362 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9364
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 30 | Train Loss: 0.0016 | Val ROC-AUC: 0.9364 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 19
Лучший ROC-AUC: 0.9806841046277666
val
ROC-AUC: 0.9807
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9142
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0412 | Val ROC-AUC: 0.9142 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9365
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0231 | Val ROC-AUC: 0.9365 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9489
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0171 | Val ROC-AUC: 0.9489 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0149 | Val ROC-AUC: 0.9596 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9355
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0131 | Val ROC-AUC: 0.9355 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9304
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0137 | Val ROC-AUC: 0.9304 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0126 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9446
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0137 | Val ROC-AUC: 0.9446 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0133 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0118 | Val ROC-AUC: 0.9667 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.905
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0100 | Val ROC-AUC: 0.9050 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9685
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0126 | Val ROC-AUC: 0.9685 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9719
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 13 | Train Loss: 0.0107 | Val ROC-AUC: 0.9719 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9663
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 14 | Train Loss: 0.0089 | Val ROC-AUC: 0.9663 | Val Profit: -140
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9352
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 15 | Train Loss: 0.0079 | Val ROC-AUC: 0.9352 | Val Profit: -120
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9299
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 16 | Train Loss: 0.0068 | Val ROC-AUC: 0.9299 | Val Profit: -115
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9681
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 17 | Train Loss: 0.0066 | Val ROC-AUC: 0.9681 | Val Profit: -370
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9197
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 18 | Train Loss: 0.0095 | Val ROC-AUC: 0.9197 | Val Profit: -295
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9421
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 19 | Train Loss: 0.0070 | Val ROC-AUC: 0.9421 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9366
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 20 | Train Loss: 0.0064 | Val ROC-AUC: 0.9366 | Val Profit: -175
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9155
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 21 | Train Loss: 0.0099 | Val ROC-AUC: 0.9155 | Val Profit: -385
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9299
Precision: 0.2941
Recall: 0.4762
F0.5-score: 0.3185
Profit: -605

Эпоха 22 | Train Loss: 0.0099 | Val ROC-AUC: 0.9299 | Val Profit: -605
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9763
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 23 | Train Loss: 0.0083 | Val ROC-AUC: 0.9763 | Val Profit: -145
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.976
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 24 | Train Loss: 0.0073 | Val ROC-AUC: 0.9760 | Val Profit: -130
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9698
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 25 | Train Loss: 0.0060 | Val ROC-AUC: 0.9698 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9315
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 26 | Train Loss: 0.0047 | Val ROC-AUC: 0.9315 | Val Profit: -80
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9731
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 27 | Train Loss: 0.0046 | Val ROC-AUC: 0.9731 | Val Profit: -110
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9773
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 28 | Train Loss: 0.0046 | Val ROC-AUC: 0.9773 | Val Profit: -175
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8858
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 29 | Train Loss: 0.0045 | Val ROC-AUC: 0.8858 | Val Profit: -135
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.7404
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 30 | Train Loss: 0.0037 | Val ROC-AUC: 0.7404 | Val Profit: -150

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9772635814889337
val
ROC-AUC: 0.9773
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9256
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 1 | Train Loss: 0.0416 | Val ROC-AUC: 0.9256 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9418
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0223 | Val ROC-AUC: 0.9418 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9348
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0196 | Val ROC-AUC: 0.9348 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.8968
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0166 | Val ROC-AUC: 0.8968 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9374
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0153 | Val ROC-AUC: 0.9374 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0133 | Val ROC-AUC: 0.9543 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9659
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 7 | Train Loss: 0.0130 | Val ROC-AUC: 0.9659 | Val Profit: -205
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9682
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 8 | Train Loss: 0.0133 | Val ROC-AUC: 0.9682 | Val Profit: -175
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0126 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.8999
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0096 | Val ROC-AUC: 0.8999 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9116
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0094 | Val ROC-AUC: 0.9116 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9457
Precision: 0.3889
Recall: 0.6667
F0.5-score: 0.4242
Profit: -515

Эпоха 12 | Train Loss: 0.0114 | Val ROC-AUC: 0.9457 | Val Profit: -515
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.959
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 13 | Train Loss: 0.0115 | Val ROC-AUC: 0.9590 | Val Profit: -285
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9736
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0102 | Val ROC-AUC: 0.9736 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9612
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 15 | Train Loss: 0.0084 | Val ROC-AUC: 0.9612 | Val Profit: -255
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9767
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 16 | Train Loss: 0.0115 | Val ROC-AUC: 0.9767 | Val Profit: -100
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9769
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0089 | Val ROC-AUC: 0.9769 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9705
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 18 | Train Loss: 0.0083 | Val ROC-AUC: 0.9705 | Val Profit: -185
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9635
Precision: 0.413
Recall: 0.9048
F0.5-score: 0.4634
Profit: -590

Эпоха 19 | Train Loss: 0.0102 | Val ROC-AUC: 0.9635 | Val Profit: -590
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9682
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 20 | Train Loss: 0.0121 | Val ROC-AUC: 0.9682 | Val Profit: -215

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.969
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0096 | Val ROC-AUC: 0.9690 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0067 | Val ROC-AUC: 0.9548 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9412
Precision: 0.2951
Recall: 0.8571
F0.5-score: 0.3396
Profit: -1000

Эпоха 23 | Train Loss: 0.0124 | Val ROC-AUC: 0.9412 | Val Profit: -1000
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9752
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 24 | Train Loss: 0.0106 | Val ROC-AUC: 0.9752 | Val Profit: -305
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9772
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0086 | Val ROC-AUC: 0.9772 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9832
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 26 | Train Loss: 0.0077 | Val ROC-AUC: 0.9832 | Val Profit: -45
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9805
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 27 | Train Loss: 0.0074 | Val ROC-AUC: 0.9805 | Val Profit: -85
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9706
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 28 | Train Loss: 0.0065 | Val ROC-AUC: 0.9706 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9722
Precision: 0.3571
Recall: 0.9524
F0.5-score: 0.4082
Profit: -805

Эпоха 29 | Train Loss: 0.0103 | Val ROC-AUC: 0.9722 | Val Profit: -805
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.969
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0101 | Val ROC-AUC: 0.9690 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9832327297116029
val
ROC-AUC: 0.9832
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9217
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0535 | Val ROC-AUC: 0.9217 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0275 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0176 | Val ROC-AUC: 0.9689 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9659
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 4 | Train Loss: 0.0133 | Val ROC-AUC: 0.9659 | Val Profit: -150
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9669
Precision: 0.5185
Recall: 0.6667
F0.5-score: 0.5426
Profit: -290

Эпоха 5 | Train Loss: 0.0117 | Val ROC-AUC: 0.9669 | Val Profit: -290
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9755
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 6 | Train Loss: 0.0110 | Val ROC-AUC: 0.9755 | Val Profit: -270
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9645
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 7 | Train Loss: 0.0098 | Val ROC-AUC: 0.9645 | Val Profit: -170
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9781
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 8 | Train Loss: 0.0081 | Val ROC-AUC: 0.9781 | Val Profit: -110
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9746
Precision: 0.625
Recall: 0.7143
F0.5-score: 0.641
Profit: -180

Эпоха 9 | Train Loss: 0.0079 | Val ROC-AUC: 0.9746 | Val Profit: -180
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.952
Precision: 0.4167
Recall: 0.4762
F0.5-score: 0.4274
Profit: -355

Эпоха 10 | Train Loss: 0.0078 | Val ROC-AUC: 0.9520 | Val Profit: -355
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.965
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 11 | Train Loss: 0.0073 | Val ROC-AUC: 0.9650 | Val Profit: -165
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9305
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 12 | Train Loss: 0.0056 | Val ROC-AUC: 0.9305 | Val Profit: -165
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9447
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 13 | Train Loss: 0.0055 | Val ROC-AUC: 0.9447 | Val Profit: -155
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9712
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 14 | Train Loss: 0.0084 | Val ROC-AUC: 0.9712 | Val Profit: -280
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9702
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 15 | Train Loss: 0.0086 | Val ROC-AUC: 0.9702 | Val Profit: -110
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9706
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 16 | Train Loss: 0.0064 | Val ROC-AUC: 0.9706 | Val Profit: -85
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.984
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

Эпоха 17 | Train Loss: 0.0061 | Val ROC-AUC: 0.9840 | Val Profit: -80
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9718
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 18 | Train Loss: 0.0063 | Val ROC-AUC: 0.9718 | Val Profit: -115
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9662
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 19 | Train Loss: 0.0038 | Val ROC-AUC: 0.9662 | Val Profit: -115
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9701
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 20 | Train Loss: 0.0045 | Val ROC-AUC: 0.9701 | Val Profit: -220
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9395
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 21 | Train Loss: 0.0059 | Val ROC-AUC: 0.9395 | Val Profit: -70
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9599
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0042 | Val ROC-AUC: 0.9599 | Val Profit: -125
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9367
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 23 | Train Loss: 0.0033 | Val ROC-AUC: 0.9367 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9227
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 24 | Train Loss: 0.0031 | Val ROC-AUC: 0.9227 | Val Profit: -135
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9636
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 25 | Train Loss: 0.0029 | Val ROC-AUC: 0.9636 | Val Profit: -155
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9785
Precision: 0.8571
Recall: 0.5714
F0.5-score: 0.7792
Profit: -35

Эпоха 26 | Train Loss: 0.0019 | Val ROC-AUC: 0.9785 | Val Profit: -35
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9556
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 27 | Train Loss: 0.0030 | Val ROC-AUC: 0.9556 | Val Profit: -175
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9298
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 28 | Train Loss: 0.0028 | Val ROC-AUC: 0.9298 | Val Profit: -90
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9357
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 29 | Train Loss: 0.0030 | Val ROC-AUC: 0.9357 | Val Profit: -170
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9687
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 30 | Train Loss: 0.0041 | Val ROC-AUC: 0.9687 | Val Profit: -60

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.984037558685446
val
ROC-AUC: 0.984
Precision: 0.75
Recall: 0.7143
F0.5-score: 0.7426
Profit: -80

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9296
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0532 | Val ROC-AUC: 0.9296 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0278 | Val ROC-AUC: 0.9636 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0181 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9596
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 4 | Train Loss: 0.0150 | Val ROC-AUC: 0.9596 | Val Profit: -180

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9618
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 5 | Train Loss: 0.0140 | Val ROC-AUC: 0.9618 | Val Profit: -85
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9658
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 6 | Train Loss: 0.0117 | Val ROC-AUC: 0.9658 | Val Profit: -350
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9592
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 7 | Train Loss: 0.0109 | Val ROC-AUC: 0.9592 | Val Profit: -255
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9565
Precision: 0.4688
Recall: 0.7143
F0.5-score: 0.5034
Profit: -380

Эпоха 8 | Train Loss: 0.0095 | Val ROC-AUC: 0.9565 | Val Profit: -380
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 9 | Train Loss: 0.0112 | Val ROC-AUC: 0.9772 | Val Profit: -140
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9764
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 10 | Train Loss: 0.0107 | Val ROC-AUC: 0.9764 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9706
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 11 | Train Loss: 0.0096 | Val ROC-AUC: 0.9706 | Val Profit: -120
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9062
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0084 | Val ROC-AUC: 0.9062 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9839
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 13 | Train Loss: 0.0080 | Val ROC-AUC: 0.9839 | Val Profit: -70
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9736
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 14 | Train Loss: 0.0075 | Val ROC-AUC: 0.9736 | Val Profit: -125

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.985
Precision: 0.7895
Recall: 0.7143
F0.5-score: 0.7732
Profit: -55

Эпоха 15 | Train Loss: 0.0093 | Val ROC-AUC: 0.9850 | Val Profit: -55
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9796
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 16 | Train Loss: 0.0080 | Val ROC-AUC: 0.9796 | Val Profit: -125
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9734
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 17 | Train Loss: 0.0083 | Val ROC-AUC: 0.9734 | Val Profit: -145
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.976
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.0080 | Val ROC-AUC: 0.9760 | Val Profit: -100
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9429
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 19 | Train Loss: 0.0062 | Val ROC-AUC: 0.9429 | Val Profit: -95
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9431
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 20 | Train Loss: 0.0068 | Val ROC-AUC: 0.9431 | Val Profit: -80
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9784
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 21 | Train Loss: 0.0077 | Val ROC-AUC: 0.9784 | Val Profit: -310
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9787
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 22 | Train Loss: 0.0091 | Val ROC-AUC: 0.9787 | Val Profit: -70
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8212
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0061 | Val ROC-AUC: 0.8212 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9665
Precision: 0.7778
Recall: 0.6667
F0.5-score: 0.7527
Profit: -65

Эпоха 24 | Train Loss: 0.0063 | Val ROC-AUC: 0.9665 | Val Profit: -65
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9677
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 25 | Train Loss: 0.0072 | Val ROC-AUC: 0.9677 | Val Profit: -180
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9749
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 26 | Train Loss: 0.0065 | Val ROC-AUC: 0.9749 | Val Profit: -160
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9567
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 27 | Train Loss: 0.0065 | Val ROC-AUC: 0.9567 | Val Profit: -100
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9421
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 28 | Train Loss: 0.0072 | Val ROC-AUC: 0.9421 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8231
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 29 | Train Loss: 0.0064 | Val ROC-AUC: 0.8231 | Val Profit: -125
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8854
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 30 | Train Loss: 0.0053 | Val ROC-AUC: 0.8854 | Val Profit: -155

Лучшая эпоха для model_9_Focal_loss: 15
Лучший ROC-AUC: 0.9849765258215962
val
ROC-AUC: 0.985
Precision: 0.7895
Recall: 0.7143
F0.5-score: 0.7732
Profit: -55

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.937
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0534 | Val ROC-AUC: 0.9370 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9011
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0282 | Val ROC-AUC: 0.9011 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9702
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0186 | Val ROC-AUC: 0.9702 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9649
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0155 | Val ROC-AUC: 0.9649 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9649
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 5 | Train Loss: 0.0142 | Val ROC-AUC: 0.9649 | Val Profit: -165
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0126 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9509
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 7 | Train Loss: 0.0143 | Val ROC-AUC: 0.9509 | Val Profit: -290
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0135 | Val ROC-AUC: 0.9738 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 9 | Train Loss: 0.0116 | Val ROC-AUC: 0.9513 | Val Profit: -130
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9791
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0108 | Val ROC-AUC: 0.9791 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9751
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 11 | Train Loss: 0.0115 | Val ROC-AUC: 0.9751 | Val Profit: -135
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9764
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 12 | Train Loss: 0.0117 | Val ROC-AUC: 0.9764 | Val Profit: -130
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0097 | Val ROC-AUC: 0.9812 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9822
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0099 | Val ROC-AUC: 0.9822 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.982
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0106 | Val ROC-AUC: 0.9820 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9721
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 16 | Train Loss: 0.0101 | Val ROC-AUC: 0.9721 | Val Profit: -155
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9803
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 17 | Train Loss: 0.0113 | Val ROC-AUC: 0.9803 | Val Profit: -205
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9827
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 18 | Train Loss: 0.0103 | Val ROC-AUC: 0.9827 | Val Profit: -75
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9761
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 19 | Train Loss: 0.0096 | Val ROC-AUC: 0.9761 | Val Profit: -95
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9767
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0098 | Val ROC-AUC: 0.9767 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9757
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 21 | Train Loss: 0.0095 | Val ROC-AUC: 0.9757 | Val Profit: -145
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9755
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 22 | Train Loss: 0.0091 | Val ROC-AUC: 0.9755 | Val Profit: -135
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9736
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0087 | Val ROC-AUC: 0.9736 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9816
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 24 | Train Loss: 0.0106 | Val ROC-AUC: 0.9816 | Val Profit: -145
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9843
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 25 | Train Loss: 0.0087 | Val ROC-AUC: 0.9843 | Val Profit: -90
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9371
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0092 | Val ROC-AUC: 0.9371 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.974
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 27 | Train Loss: 0.0086 | Val ROC-AUC: 0.9740 | Val Profit: -155
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9759
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0099 | Val ROC-AUC: 0.9759 | Val Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9879
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0109 | Val ROC-AUC: 0.9879 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9822
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0088 | Val ROC-AUC: 0.9822 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 29
Лучший ROC-AUC: 0.987927565392354
val
ROC-AUC: 0.9879
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9395
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0564 | Val ROC-AUC: 0.9395 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.939
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0297 | Val ROC-AUC: 0.9390 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9578
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 3 | Train Loss: 0.0185 | Val ROC-AUC: 0.9578 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9541
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0147 | Val ROC-AUC: 0.9541 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9658
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0127 | Val ROC-AUC: 0.9658 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9569
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0123 | Val ROC-AUC: 0.9569 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0115 | Val ROC-AUC: 0.9544 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0103 | Val ROC-AUC: 0.9268 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9312
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0100 | Val ROC-AUC: 0.9312 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9604
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0096 | Val ROC-AUC: 0.9604 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9284
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0097 | Val ROC-AUC: 0.9284 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0080 | Val ROC-AUC: 0.9602 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0088 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.8509
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0074 | Val ROC-AUC: 0.8509 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9673
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0067 | Val ROC-AUC: 0.9673 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9396
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0066 | Val ROC-AUC: 0.9396 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9111
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 17 | Train Loss: 0.0060 | Val ROC-AUC: 0.9111 | Val Profit: -155
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9616
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 18 | Train Loss: 0.0055 | Val ROC-AUC: 0.9616 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9096
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 19 | Train Loss: 0.0052 | Val ROC-AUC: 0.9096 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8963
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 20 | Train Loss: 0.0048 | Val ROC-AUC: 0.8963 | Val Profit: -135
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9214
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0046 | Val ROC-AUC: 0.9214 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9195
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.0043 | Val ROC-AUC: 0.9195 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9033
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0041 | Val ROC-AUC: 0.9033 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9036
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 24 | Train Loss: 0.0039 | Val ROC-AUC: 0.9036 | Val Profit: -125
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9049
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 25 | Train Loss: 0.0037 | Val ROC-AUC: 0.9049 | Val Profit: -125
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9061
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 26 | Train Loss: 0.0035 | Val ROC-AUC: 0.9061 | Val Profit: -125
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9108
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 27 | Train Loss: 0.0034 | Val ROC-AUC: 0.9108 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9123
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 28 | Train Loss: 0.0032 | Val ROC-AUC: 0.9123 | Val Profit: -125
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.912
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 29 | Train Loss: 0.0031 | Val ROC-AUC: 0.9120 | Val Profit: -125
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9316
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 30 | Train Loss: 0.0030 | Val ROC-AUC: 0.9316 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 15
Лучший ROC-AUC: 0.967270288397049
val
ROC-AUC: 0.9673
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0572 | Val ROC-AUC: 0.8989 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.934
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0304 | Val ROC-AUC: 0.9340 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0193 | Val ROC-AUC: 0.9498 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9117
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0151 | Val ROC-AUC: 0.9117 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0132 | Val ROC-AUC: 0.9411 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9382
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0130 | Val ROC-AUC: 0.9382 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9618
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0116 | Val ROC-AUC: 0.9618 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0118 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.949
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0119 | Val ROC-AUC: 0.9490 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9265
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0104 | Val ROC-AUC: 0.9265 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0090 | Val ROC-AUC: 0.9594 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9132
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0086 | Val ROC-AUC: 0.9132 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.8989
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0080 | Val ROC-AUC: 0.8989 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0089 | Val ROC-AUC: 0.9689 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0094 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9751
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 16 | Train Loss: 0.0084 | Val ROC-AUC: 0.9751 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9321
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0079 | Val ROC-AUC: 0.9321 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9542
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0095 | Val ROC-AUC: 0.9542 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9195
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 19 | Train Loss: 0.0082 | Val ROC-AUC: 0.9195 | Val Profit: -240
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8911
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 20 | Train Loss: 0.0079 | Val ROC-AUC: 0.8911 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.7795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0066 | Val ROC-AUC: 0.7795 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9689
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.0060 | Val ROC-AUC: 0.9689 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.7948
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 23 | Train Loss: 0.0055 | Val ROC-AUC: 0.7948 | Val Profit: -85
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8427
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 24 | Train Loss: 0.0053 | Val ROC-AUC: 0.8427 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9056
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 25 | Train Loss: 0.0047 | Val ROC-AUC: 0.9056 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8899
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 26 | Train Loss: 0.0050 | Val ROC-AUC: 0.8899 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.973
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 27 | Train Loss: 0.0056 | Val ROC-AUC: 0.9730 | Val Profit: -255
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.972
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 28 | Train Loss: 0.0054 | Val ROC-AUC: 0.9720 | Val Profit: -165
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8449
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 29 | Train Loss: 0.0058 | Val ROC-AUC: 0.8449 | Val Profit: -140
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9687
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 30 | Train Loss: 0.0056 | Val ROC-AUC: 0.9687 | Val Profit: -125

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9750503018108652
val
ROC-AUC: 0.9751
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8814
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0571 | Val ROC-AUC: 0.8814 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9009
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0309 | Val ROC-AUC: 0.9009 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9467
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0212 | Val ROC-AUC: 0.9467 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9307
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0180 | Val ROC-AUC: 0.9307 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0158 | Val ROC-AUC: 0.9580 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9058
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0149 | Val ROC-AUC: 0.9058 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9614
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0144 | Val ROC-AUC: 0.9614 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9695
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0138 | Val ROC-AUC: 0.9695 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9638
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0148 | Val ROC-AUC: 0.9638 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9678
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0128 | Val ROC-AUC: 0.9678 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0113 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9477
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0123 | Val ROC-AUC: 0.9477 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9739
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0129 | Val ROC-AUC: 0.9739 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0111 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9731
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0111 | Val ROC-AUC: 0.9731 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0104 | Val ROC-AUC: 0.9706 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9634
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0110 | Val ROC-AUC: 0.9634 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0102 | Val ROC-AUC: 0.9773 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9709
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0096 | Val ROC-AUC: 0.9709 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0110 | Val ROC-AUC: 0.9773 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9719
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0098 | Val ROC-AUC: 0.9719 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9722
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0098 | Val ROC-AUC: 0.9722 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0090 | Val ROC-AUC: 0.9816 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0098 | Val ROC-AUC: 0.9755 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9677
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0094 | Val ROC-AUC: 0.9677 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9741
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0083 | Val ROC-AUC: 0.9741 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.7505
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0078 | Val ROC-AUC: 0.7505 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.97
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 28 | Train Loss: 0.0090 | Val ROC-AUC: 0.9700 | Val Profit: -280
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9744
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 29 | Train Loss: 0.0090 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9628
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 30 | Train Loss: 0.0091 | Val ROC-AUC: 0.9628 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9816230717639168
val
ROC-AUC: 0.9816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8339
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0587 | Val ROC-AUC: 0.8339 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0319 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.962
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0193 | Val ROC-AUC: 0.9620 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9503
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0141 | Val ROC-AUC: 0.9503 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0131 | Val ROC-AUC: 0.9698 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9501
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0112 | Val ROC-AUC: 0.9501 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9551
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0101 | Val ROC-AUC: 0.9551 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9355
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0093 | Val ROC-AUC: 0.9355 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9629
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0091 | Val ROC-AUC: 0.9629 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9471
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0083 | Val ROC-AUC: 0.9471 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9625
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0078 | Val ROC-AUC: 0.9625 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9309
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 12 | Train Loss: 0.0069 | Val ROC-AUC: 0.9309 | Val Profit: -95
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9599
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 13 | Train Loss: 0.0061 | Val ROC-AUC: 0.9599 | Val Profit: -135
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9508
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 14 | Train Loss: 0.0047 | Val ROC-AUC: 0.9508 | Val Profit: -125
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.954
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 15 | Train Loss: 0.0046 | Val ROC-AUC: 0.9540 | Val Profit: -300
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.978
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 16 | Train Loss: 0.0053 | Val ROC-AUC: 0.9780 | Val Profit: -205
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9702
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 17 | Train Loss: 0.0063 | Val ROC-AUC: 0.9702 | Val Profit: -155
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9535
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0037 | Val ROC-AUC: 0.9535 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9713
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 19 | Train Loss: 0.0023 | Val ROC-AUC: 0.9713 | Val Profit: -110
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9725
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 20 | Train Loss: 0.0023 | Val ROC-AUC: 0.9725 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9697
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0017 | Val ROC-AUC: 0.9697 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9634
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 22 | Train Loss: 0.0013 | Val ROC-AUC: 0.9634 | Val Profit: -110
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9572
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 23 | Train Loss: 0.0012 | Val ROC-AUC: 0.9572 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9555
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 24 | Train Loss: 0.0011 | Val ROC-AUC: 0.9555 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9555
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 25 | Train Loss: 0.0011 | Val ROC-AUC: 0.9555 | Val Profit: -110
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9539
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 26 | Train Loss: 0.0010 | Val ROC-AUC: 0.9539 | Val Profit: -110
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9532
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 27 | Train Loss: 0.0010 | Val ROC-AUC: 0.9532 | Val Profit: -110
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9526
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 28 | Train Loss: 0.0010 | Val ROC-AUC: 0.9526 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.951
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 29 | Train Loss: 0.0010 | Val ROC-AUC: 0.9510 | Val Profit: -110
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9505
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 30 | Train Loss: 0.0010 | Val ROC-AUC: 0.9505 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9780013413816231
val
ROC-AUC: 0.978
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9041
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0584 | Val ROC-AUC: 0.9041 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.94
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0313 | Val ROC-AUC: 0.9400 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9298
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0196 | Val ROC-AUC: 0.9298 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0153 | Val ROC-AUC: 0.9498 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9217
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0130 | Val ROC-AUC: 0.9217 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9549
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0114 | Val ROC-AUC: 0.9549 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9433
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0110 | Val ROC-AUC: 0.9433 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.964
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0109 | Val ROC-AUC: 0.9640 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0099 | Val ROC-AUC: 0.9513 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9473
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0095 | Val ROC-AUC: 0.9473 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9066
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0092 | Val ROC-AUC: 0.9066 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8893
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0080 | Val ROC-AUC: 0.8893 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9658
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0086 | Val ROC-AUC: 0.9658 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9469
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0083 | Val ROC-AUC: 0.9469 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9489
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0079 | Val ROC-AUC: 0.9489 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0087 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9382
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0071 | Val ROC-AUC: 0.9382 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.925
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0087 | Val ROC-AUC: 0.9250 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9535
Precision: 0.6364
Recall: 0.6667
F0.5-score: 0.6422
Profit: -165

Эпоха 19 | Train Loss: 0.0072 | Val ROC-AUC: 0.9535 | Val Profit: -165
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.963
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 20 | Train Loss: 0.0066 | Val ROC-AUC: 0.9630 | Val Profit: -100
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9381
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 21 | Train Loss: 0.0061 | Val ROC-AUC: 0.9381 | Val Profit: -95
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9315
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 22 | Train Loss: 0.0056 | Val ROC-AUC: 0.9315 | Val Profit: -165
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9427
Precision: 0.4118
Recall: 0.6667
F0.5-score: 0.4459
Profit: -465

Эпоха 23 | Train Loss: 0.0059 | Val ROC-AUC: 0.9427 | Val Profit: -465
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9569
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 24 | Train Loss: 0.0066 | Val ROC-AUC: 0.9569 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9569
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 25 | Train Loss: 0.0072 | Val ROC-AUC: 0.9569 | Val Profit: -205
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.947
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 26 | Train Loss: 0.0074 | Val ROC-AUC: 0.9470 | Val Profit: -140
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9447
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 27 | Train Loss: 0.0055 | Val ROC-AUC: 0.9447 | Val Profit: -85
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9681
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 28 | Train Loss: 0.0045 | Val ROC-AUC: 0.9681 | Val Profit: -90
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9578
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 29 | Train Loss: 0.0038 | Val ROC-AUC: 0.9578 | Val Profit: -125
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9649
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 30 | Train Loss: 0.0035 | Val ROC-AUC: 0.9649 | Val Profit: -80

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9695506371562709
val
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9357
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0583 | Val ROC-AUC: 0.9357 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9447
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0317 | Val ROC-AUC: 0.9447 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9422
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0216 | Val ROC-AUC: 0.9422 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9337
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0186 | Val ROC-AUC: 0.9337 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9466
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0165 | Val ROC-AUC: 0.9466 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9638
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0155 | Val ROC-AUC: 0.9638 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0135 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.954
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0120 | Val ROC-AUC: 0.9540 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0128 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0137 | Val ROC-AUC: 0.9610 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.97
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0117 | Val ROC-AUC: 0.9700 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0107 | Val ROC-AUC: 0.9598 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9347
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0102 | Val ROC-AUC: 0.9347 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0110 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0131 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9628
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0118 | Val ROC-AUC: 0.9628 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9686
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0100 | Val ROC-AUC: 0.9686 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9514
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0097 | Val ROC-AUC: 0.9514 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9699
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0107 | Val ROC-AUC: 0.9699 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9728
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0097 | Val ROC-AUC: 0.9728 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9681
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0093 | Val ROC-AUC: 0.9681 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9702
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0093 | Val ROC-AUC: 0.9702 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9646
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0091 | Val ROC-AUC: 0.9646 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0101 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0104 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0090 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9673
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0078 | Val ROC-AUC: 0.9673 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9796
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 28 | Train Loss: 0.0078 | Val ROC-AUC: 0.9796 | Val Profit: -65
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9733
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 29 | Train Loss: 0.0088 | Val ROC-AUC: 0.9733 | Val Profit: -250
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.972
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 30 | Train Loss: 0.0091 | Val ROC-AUC: 0.9720 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9796109993293093
val
ROC-AUC: 0.9796
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9226
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1070 | Val ROC-AUC: 0.9226 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9586
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0548 | Val ROC-AUC: 0.9586 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9734
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0355 | Val ROC-AUC: 0.9734 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9596
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 4 | Train Loss: 0.0269 | Val ROC-AUC: 0.9596 | Val Profit: -225
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9525
Precision: 0.4412
Recall: 0.7143
F0.5-score: 0.4777
Profit: -430

Эпоха 5 | Train Loss: 0.0249 | Val ROC-AUC: 0.9525 | Val Profit: -430
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9697
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 6 | Train Loss: 0.0211 | Val ROC-AUC: 0.9697 | Val Profit: -190
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9634
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 7 | Train Loss: 0.0188 | Val ROC-AUC: 0.9634 | Val Profit: -360
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9649
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 8 | Train Loss: 0.0192 | Val ROC-AUC: 0.9649 | Val Profit: -310
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9643
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 9 | Train Loss: 0.0192 | Val ROC-AUC: 0.9643 | Val Profit: -210
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9804
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 10 | Train Loss: 0.0176 | Val ROC-AUC: 0.9804 | Val Profit: -95
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9712
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 11 | Train Loss: 0.0156 | Val ROC-AUC: 0.9712 | Val Profit: -95
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9549
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 12 | Train Loss: 0.0123 | Val ROC-AUC: 0.9549 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9602
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 13 | Train Loss: 0.0138 | Val ROC-AUC: 0.9602 | Val Profit: -150
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9714
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 14 | Train Loss: 0.0128 | Val ROC-AUC: 0.9714 | Val Profit: -100
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9791
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 15 | Train Loss: 0.0137 | Val ROC-AUC: 0.9791 | Val Profit: -155
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9575
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 16 | Train Loss: 0.0137 | Val ROC-AUC: 0.9575 | Val Profit: -130
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9721
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 17 | Train Loss: 0.0115 | Val ROC-AUC: 0.9721 | Val Profit: -135
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9489
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 18 | Train Loss: 0.0086 | Val ROC-AUC: 0.9489 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9581
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 19 | Train Loss: 0.0092 | Val ROC-AUC: 0.9581 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9489
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 20 | Train Loss: 0.0074 | Val ROC-AUC: 0.9489 | Val Profit: -65
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9738
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 21 | Train Loss: 0.0088 | Val ROC-AUC: 0.9738 | Val Profit: -255
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9583
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 22 | Train Loss: 0.0136 | Val ROC-AUC: 0.9583 | Val Profit: -140
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.885
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 23 | Train Loss: 0.0097 | Val ROC-AUC: 0.8850 | Val Profit: -115
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9276
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 24 | Train Loss: 0.0089 | Val ROC-AUC: 0.9276 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.8613
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 25 | Train Loss: 0.0057 | Val ROC-AUC: 0.8613 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8978
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 26 | Train Loss: 0.0058 | Val ROC-AUC: 0.8978 | Val Profit: -185
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9618
Precision: 0.4
Recall: 0.1905
F0.5-score: 0.3279
Profit: -215

Эпоха 27 | Train Loss: 0.0071 | Val ROC-AUC: 0.9618 | Val Profit: -215
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8643
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 28 | Train Loss: 0.0067 | Val ROC-AUC: 0.8643 | Val Profit: -145
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.7852
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 29 | Train Loss: 0.0038 | Val ROC-AUC: 0.7852 | Val Profit: -160
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9146
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 30 | Train Loss: 0.0046 | Val ROC-AUC: 0.9146 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 10
Лучший ROC-AUC: 0.9804158283031522
val
ROC-AUC: 0.9804
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9231
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1072 | Val ROC-AUC: 0.9231 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9678
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0553 | Val ROC-AUC: 0.9678 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9587
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0360 | Val ROC-AUC: 0.9587 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.939
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0277 | Val ROC-AUC: 0.9390 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9603
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 5 | Train Loss: 0.0240 | Val ROC-AUC: 0.9603 | Val Profit: -220
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.974
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 6 | Train Loss: 0.0249 | Val ROC-AUC: 0.9740 | Val Profit: -285
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.962
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 7 | Train Loss: 0.0235 | Val ROC-AUC: 0.9620 | Val Profit: -275
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9682
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 8 | Train Loss: 0.0208 | Val ROC-AUC: 0.9682 | Val Profit: -130
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9702
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 9 | Train Loss: 0.0177 | Val ROC-AUC: 0.9702 | Val Profit: -120
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9591
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 10 | Train Loss: 0.0179 | Val ROC-AUC: 0.9591 | Val Profit: -360
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9689
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 11 | Train Loss: 0.0187 | Val ROC-AUC: 0.9689 | Val Profit: -135
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9722
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 12 | Train Loss: 0.0172 | Val ROC-AUC: 0.9722 | Val Profit: -55
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9737
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 13 | Train Loss: 0.0162 | Val ROC-AUC: 0.9737 | Val Profit: -180
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9561
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 14 | Train Loss: 0.0145 | Val ROC-AUC: 0.9561 | Val Profit: -160
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9068
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 15 | Train Loss: 0.0128 | Val ROC-AUC: 0.9068 | Val Profit: -160
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9804
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 16 | Train Loss: 0.0095 | Val ROC-AUC: 0.9804 | Val Profit: -100
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9512
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 17 | Train Loss: 0.0094 | Val ROC-AUC: 0.9512 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.8408
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.0123 | Val ROC-AUC: 0.8408 | Val Profit: -100
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9763
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 19 | Train Loss: 0.0120 | Val ROC-AUC: 0.9763 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9736
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 20 | Train Loss: 0.0158 | Val ROC-AUC: 0.9736 | Val Profit: -205
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9789
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 21 | Train Loss: 0.0127 | Val ROC-AUC: 0.9789 | Val Profit: -145
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 22 | Train Loss: 0.0093 | Val ROC-AUC: 0.8973 | Val Profit: -155
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8991
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 23 | Train Loss: 0.0097 | Val ROC-AUC: 0.8991 | Val Profit: -205
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.981
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 24 | Train Loss: 0.0153 | Val ROC-AUC: 0.9810 | Val Profit: -90
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.976
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 25 | Train Loss: 0.0116 | Val ROC-AUC: 0.9760 | Val Profit: -170
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9526
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 26 | Train Loss: 0.0110 | Val ROC-AUC: 0.9526 | Val Profit: -135
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9072
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 27 | Train Loss: 0.0111 | Val ROC-AUC: 0.9072 | Val Profit: -95
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.7984
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 28 | Train Loss: 0.0094 | Val ROC-AUC: 0.7984 | Val Profit: -135
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9349
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 29 | Train Loss: 0.0080 | Val ROC-AUC: 0.9349 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9207
Precision: 0.2857
Recall: 0.0952
F0.5-score: 0.2041
Profit: -210

Эпоха 30 | Train Loss: 0.0061 | Val ROC-AUC: 0.9207 | Val Profit: -210

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9809523809523809
val
ROC-AUC: 0.981
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9345
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1072 | Val ROC-AUC: 0.9345 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9427
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0563 | Val ROC-AUC: 0.9427 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0384 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9508
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0323 | Val ROC-AUC: 0.9508 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9628
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0304 | Val ROC-AUC: 0.9628 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9772
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 6 | Train Loss: 0.0262 | Val ROC-AUC: 0.9772 | Val Profit: -170
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9733
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 7 | Train Loss: 0.0259 | Val ROC-AUC: 0.9733 | Val Profit: -110
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9728
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 8 | Train Loss: 0.0237 | Val ROC-AUC: 0.9728 | Val Profit: -320
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0209 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9694
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 10 | Train Loss: 0.0197 | Val ROC-AUC: 0.9694 | Val Profit: -95
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9815
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 11 | Train Loss: 0.0179 | Val ROC-AUC: 0.9815 | Val Profit: -140

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9773
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 12 | Train Loss: 0.0195 | Val ROC-AUC: 0.9773 | Val Profit: -145
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.959
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 13 | Train Loss: 0.0194 | Val ROC-AUC: 0.9590 | Val Profit: -135
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9702
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 14 | Train Loss: 0.0209 | Val ROC-AUC: 0.9702 | Val Profit: -135
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9781
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0210 | Val ROC-AUC: 0.9781 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9811
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 16 | Train Loss: 0.0192 | Val ROC-AUC: 0.9811 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9803
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 17 | Train Loss: 0.0185 | Val ROC-AUC: 0.9803 | Val Profit: -130
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9831
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 18 | Train Loss: 0.0187 | Val ROC-AUC: 0.9831 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9769
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0181 | Val ROC-AUC: 0.9769 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9811
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.0186 | Val ROC-AUC: 0.9811 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.984
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 21 | Train Loss: 0.0193 | Val ROC-AUC: 0.9840 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9828
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 22 | Train Loss: 0.0169 | Val ROC-AUC: 0.9828 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9717
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 23 | Train Loss: 0.0170 | Val ROC-AUC: 0.9717 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9899
Precision: 0.6538
Recall: 0.8095
F0.5-score: 0.68
Profit: -160

Эпоха 24 | Train Loss: 0.0194 | Val ROC-AUC: 0.9899 | Val Profit: -160
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9815
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0158 | Val ROC-AUC: 0.9815 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9816
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 26 | Train Loss: 0.0164 | Val ROC-AUC: 0.9816 | Val Profit: -135
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9775
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0154 | Val ROC-AUC: 0.9775 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9796
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 28 | Train Loss: 0.0164 | Val ROC-AUC: 0.9796 | Val Profit: -145
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.984
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0161 | Val ROC-AUC: 0.9840 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9796
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 30 | Train Loss: 0.0145 | Val ROC-AUC: 0.9796 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9899396378269618
val
ROC-AUC: 0.9899
Precision: 0.6538
Recall: 0.8095
F0.5-score: 0.68
Profit: -160

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.941
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1129 | Val ROC-AUC: 0.9410 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9409
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0593 | Val ROC-AUC: 0.9409 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9634
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0371 | Val ROC-AUC: 0.9634 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9429
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0293 | Val ROC-AUC: 0.9429 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0249 | Val ROC-AUC: 0.9590 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9505
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0227 | Val ROC-AUC: 0.9505 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9713
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0224 | Val ROC-AUC: 0.9713 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0200 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9646
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0183 | Val ROC-AUC: 0.9646 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9665
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0182 | Val ROC-AUC: 0.9665 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9729
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0164 | Val ROC-AUC: 0.9729 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9426
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0153 | Val ROC-AUC: 0.9426 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9638
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0171 | Val ROC-AUC: 0.9638 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.952
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0172 | Val ROC-AUC: 0.9520 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0158 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9003
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0137 | Val ROC-AUC: 0.9003 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.948
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 17 | Train Loss: 0.0130 | Val ROC-AUC: 0.9480 | Val Profit: -120
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9671
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 18 | Train Loss: 0.0122 | Val ROC-AUC: 0.9671 | Val Profit: -95
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.911
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 19 | Train Loss: 0.0118 | Val ROC-AUC: 0.9110 | Val Profit: -170
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.917
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 20 | Train Loss: 0.0101 | Val ROC-AUC: 0.9170 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9086
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0093 | Val ROC-AUC: 0.9086 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9349
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 22 | Train Loss: 0.0087 | Val ROC-AUC: 0.9349 | Val Profit: -110
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8879
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 23 | Train Loss: 0.0082 | Val ROC-AUC: 0.8879 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9422
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 24 | Train Loss: 0.0079 | Val ROC-AUC: 0.9422 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.896
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 25 | Train Loss: 0.0077 | Val ROC-AUC: 0.8960 | Val Profit: -125
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9575
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 26 | Train Loss: 0.0075 | Val ROC-AUC: 0.9575 | Val Profit: -165
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9038
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 27 | Train Loss: 0.0072 | Val ROC-AUC: 0.9038 | Val Profit: -155
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9616
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 28 | Train Loss: 0.0104 | Val ROC-AUC: 0.9616 | Val Profit: -215
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9697
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 29 | Train Loss: 0.0092 | Val ROC-AUC: 0.9697 | Val Profit: -80
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8413
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 30 | Train Loss: 0.0088 | Val ROC-AUC: 0.8413 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 11
Лучший ROC-AUC: 0.9729040912139504
val
ROC-AUC: 0.9729
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.923
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1131 | Val ROC-AUC: 0.9230 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9352
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0594 | Val ROC-AUC: 0.9352 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.964
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0373 | Val ROC-AUC: 0.9640 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9486
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0289 | Val ROC-AUC: 0.9486 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9572
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0260 | Val ROC-AUC: 0.9572 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9415
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0247 | Val ROC-AUC: 0.9415 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9509
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0233 | Val ROC-AUC: 0.9509 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9569
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0223 | Val ROC-AUC: 0.9569 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0203 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0196 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9724
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0181 | Val ROC-AUC: 0.9724 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8932
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0181 | Val ROC-AUC: 0.8932 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9603
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0175 | Val ROC-AUC: 0.9603 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9555
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0165 | Val ROC-AUC: 0.9555 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0146 | Val ROC-AUC: 0.9596 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9529
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0141 | Val ROC-AUC: 0.9529 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9398
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0142 | Val ROC-AUC: 0.9398 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9688
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 18 | Train Loss: 0.0185 | Val ROC-AUC: 0.9688 | Val Profit: -325
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9545
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 19 | Train Loss: 0.0162 | Val ROC-AUC: 0.9545 | Val Profit: -225
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9665
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 20 | Train Loss: 0.0146 | Val ROC-AUC: 0.9665 | Val Profit: -240
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.971
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 21 | Train Loss: 0.0145 | Val ROC-AUC: 0.9710 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9371
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 22 | Train Loss: 0.0114 | Val ROC-AUC: 0.9371 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8459
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0104 | Val ROC-AUC: 0.8459 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8465
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 24 | Train Loss: 0.0102 | Val ROC-AUC: 0.8465 | Val Profit: -145
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9231
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 25 | Train Loss: 0.0098 | Val ROC-AUC: 0.9231 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.7983
Precision: 0.2692
Recall: 0.3333
F0.5-score: 0.28
Profit: -510

Эпоха 26 | Train Loss: 0.0107 | Val ROC-AUC: 0.7983 | Val Profit: -510
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9653
Precision: 0.4286
Recall: 0.2857
F0.5-score: 0.3896
Profit: -245

Эпоха 27 | Train Loss: 0.0127 | Val ROC-AUC: 0.9653 | Val Profit: -245
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9592
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 28 | Train Loss: 0.0149 | Val ROC-AUC: 0.9592 | Val Profit: -220
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.925
Precision: 0.3125
Recall: 0.2381
F0.5-score: 0.2941
Profit: -330

Эпоха 29 | Train Loss: 0.0129 | Val ROC-AUC: 0.9250 | Val Profit: -330
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9447
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 30 | Train Loss: 0.0117 | Val ROC-AUC: 0.9447 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 11
Лучший ROC-AUC: 0.9723675385647216
val
ROC-AUC: 0.9724
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8693
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1140 | Val ROC-AUC: 0.8693 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0612 | Val ROC-AUC: 0.9516 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0412 | Val ROC-AUC: 0.9510 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9624
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0350 | Val ROC-AUC: 0.9624 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0301 | Val ROC-AUC: 0.9577 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9633
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0276 | Val ROC-AUC: 0.9633 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.945
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0266 | Val ROC-AUC: 0.9450 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9678
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0247 | Val ROC-AUC: 0.9678 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9662
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0234 | Val ROC-AUC: 0.9662 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9588
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0224 | Val ROC-AUC: 0.9588 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0223 | Val ROC-AUC: 0.9567 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9502
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0246 | Val ROC-AUC: 0.9502 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0217 | Val ROC-AUC: 0.9655 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9252
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0192 | Val ROC-AUC: 0.9252 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.8812
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0180 | Val ROC-AUC: 0.8812 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0235 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9532
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0192 | Val ROC-AUC: 0.9532 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9309
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0166 | Val ROC-AUC: 0.9309 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0185 | Val ROC-AUC: 0.9675 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9517
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0198 | Val ROC-AUC: 0.9517 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0203 | Val ROC-AUC: 0.9795 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9733
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0173 | Val ROC-AUC: 0.9733 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9764
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0152 | Val ROC-AUC: 0.9764 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9722
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.0141 | Val ROC-AUC: 0.9722 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9689
Precision: 0.4375
Recall: 0.3333
F0.5-score: 0.4118
Profit: -260

Эпоха 25 | Train Loss: 0.0146 | Val ROC-AUC: 0.9689 | Val Profit: -260
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9498
Precision: 0.4
Recall: 0.381
F0.5-score: 0.396
Profit: -325

Эпоха 26 | Train Loss: 0.0162 | Val ROC-AUC: 0.9498 | Val Profit: -325
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9775
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 27 | Train Loss: 0.0183 | Val ROC-AUC: 0.9775 | Val Profit: -140
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9746
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 28 | Train Loss: 0.0193 | Val ROC-AUC: 0.9746 | Val Profit: -185
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9749
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0159 | Val ROC-AUC: 0.9749 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9734
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 30 | Train Loss: 0.0147 | Val ROC-AUC: 0.9734 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 21
Лучший ROC-AUC: 0.9794768611670019
val
ROC-AUC: 0.9795
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8357
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1174 | Val ROC-AUC: 0.8357 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0635 | Val ROC-AUC: 0.9616 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0397 | Val ROC-AUC: 0.9616 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9386
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0304 | Val ROC-AUC: 0.9386 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9639
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0250 | Val ROC-AUC: 0.9639 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9615
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0237 | Val ROC-AUC: 0.9615 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9466
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0205 | Val ROC-AUC: 0.9466 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9282
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0186 | Val ROC-AUC: 0.9282 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9281
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0175 | Val ROC-AUC: 0.9281 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9645
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0174 | Val ROC-AUC: 0.9645 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0161 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0154 | Val ROC-AUC: 0.9610 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9516
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 13 | Train Loss: 0.0142 | Val ROC-AUC: 0.9516 | Val Profit: -140
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9587
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 14 | Train Loss: 0.0115 | Val ROC-AUC: 0.9587 | Val Profit: -160
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9392
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 15 | Train Loss: 0.0092 | Val ROC-AUC: 0.9392 | Val Profit: -120
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9556
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 16 | Train Loss: 0.0066 | Val ROC-AUC: 0.9556 | Val Profit: -130
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9521
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 17 | Train Loss: 0.0056 | Val ROC-AUC: 0.9521 | Val Profit: -140
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.8107
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0044 | Val ROC-AUC: 0.8107 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9451
Precision: 0.4118
Recall: 0.3333
F0.5-score: 0.3933
Profit: -285

Эпоха 19 | Train Loss: 0.0041 | Val ROC-AUC: 0.9451 | Val Profit: -285
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.967
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 20 | Train Loss: 0.0031 | Val ROC-AUC: 0.9670 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9614
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 21 | Train Loss: 0.0026 | Val ROC-AUC: 0.9614 | Val Profit: -95
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9494
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 22 | Train Loss: 0.0024 | Val ROC-AUC: 0.9494 | Val Profit: -135
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.949
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 23 | Train Loss: 0.0022 | Val ROC-AUC: 0.9490 | Val Profit: -160
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9488
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 24 | Train Loss: 0.0021 | Val ROC-AUC: 0.9488 | Val Profit: -160
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9455
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 25 | Train Loss: 0.0021 | Val ROC-AUC: 0.9455 | Val Profit: -160
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9438
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 26 | Train Loss: 0.0020 | Val ROC-AUC: 0.9438 | Val Profit: -160
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9415
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 27 | Train Loss: 0.0020 | Val ROC-AUC: 0.9415 | Val Profit: -160
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9324
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 28 | Train Loss: 0.0019 | Val ROC-AUC: 0.9324 | Val Profit: -160
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.925
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 29 | Train Loss: 0.0020 | Val ROC-AUC: 0.9250 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9388
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 30 | Train Loss: 0.0019 | Val ROC-AUC: 0.9388 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 11
Лучший ROC-AUC: 0.9683433936955064
val
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8413
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1174 | Val ROC-AUC: 0.8413 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9474
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0621 | Val ROC-AUC: 0.9474 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9639
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0389 | Val ROC-AUC: 0.9639 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9603
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0296 | Val ROC-AUC: 0.9603 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0266 | Val ROC-AUC: 0.9344 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.954
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0251 | Val ROC-AUC: 0.9540 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9353
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 7 | Train Loss: 0.0213 | Val ROC-AUC: 0.9353 | Val Profit: -125
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9329
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 8 | Train Loss: 0.0149 | Val ROC-AUC: 0.9329 | Val Profit: -185
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9708
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 9 | Train Loss: 0.0119 | Val ROC-AUC: 0.9708 | Val Profit: -125
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9659
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 10 | Train Loss: 0.0094 | Val ROC-AUC: 0.9659 | Val Profit: -150
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9023
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 11 | Train Loss: 0.0073 | Val ROC-AUC: 0.9023 | Val Profit: -155
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9227
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 12 | Train Loss: 0.0081 | Val ROC-AUC: 0.9227 | Val Profit: -290
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9021
Precision: 0.3462
Recall: 0.4286
F0.5-score: 0.36
Profit: -440

Эпоха 13 | Train Loss: 0.0109 | Val ROC-AUC: 0.9021 | Val Profit: -440
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9336
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 14 | Train Loss: 0.0115 | Val ROC-AUC: 0.9336 | Val Profit: -115
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9474
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 15 | Train Loss: 0.0080 | Val ROC-AUC: 0.9474 | Val Profit: -90
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9339
Precision: 0.4444
Recall: 0.381
F0.5-score: 0.4301
Profit: -275

Эпоха 16 | Train Loss: 0.0102 | Val ROC-AUC: 0.9339 | Val Profit: -275
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.943
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 17 | Train Loss: 0.0079 | Val ROC-AUC: 0.9430 | Val Profit: -225
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9611
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 18 | Train Loss: 0.0069 | Val ROC-AUC: 0.9611 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9087
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 19 | Train Loss: 0.0044 | Val ROC-AUC: 0.9087 | Val Profit: -120
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9305
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 20 | Train Loss: 0.0033 | Val ROC-AUC: 0.9305 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.929
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0029 | Val ROC-AUC: 0.9290 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9349
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0028 | Val ROC-AUC: 0.9349 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9386
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.0026 | Val ROC-AUC: 0.9386 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9421
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.0026 | Val ROC-AUC: 0.9421 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9467
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 25 | Train Loss: 0.0025 | Val ROC-AUC: 0.9467 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9504
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 26 | Train Loss: 0.0024 | Val ROC-AUC: 0.9504 | Val Profit: -120
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9387
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0024 | Val ROC-AUC: 0.9387 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9459
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0024 | Val ROC-AUC: 0.9459 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9509
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 29 | Train Loss: 0.0023 | Val ROC-AUC: 0.9509 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9524
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0023 | Val ROC-AUC: 0.9524 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9707578806170356
val
ROC-AUC: 0.9708
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9254
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1165 | Val ROC-AUC: 0.9254 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9502
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0626 | Val ROC-AUC: 0.9502 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9207
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0399 | Val ROC-AUC: 0.9207 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9505
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0328 | Val ROC-AUC: 0.9505 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0289 | Val ROC-AUC: 0.9516 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0266 | Val ROC-AUC: 0.9563 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9526
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0240 | Val ROC-AUC: 0.9526 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9441
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0219 | Val ROC-AUC: 0.9441 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9625
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0221 | Val ROC-AUC: 0.9625 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9509
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0226 | Val ROC-AUC: 0.9509 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9591
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0214 | Val ROC-AUC: 0.9591 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9273
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0206 | Val ROC-AUC: 0.9273 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.8816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0197 | Val ROC-AUC: 0.8816 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9607
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0212 | Val ROC-AUC: 0.9607 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0199 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9697
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0198 | Val ROC-AUC: 0.9697 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9674
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0215 | Val ROC-AUC: 0.9674 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9626
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0189 | Val ROC-AUC: 0.9626 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9641
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0180 | Val ROC-AUC: 0.9641 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8701
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0169 | Val ROC-AUC: 0.8701 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0167 | Val ROC-AUC: 0.9670 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9304
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0162 | Val ROC-AUC: 0.9304 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.96
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 23 | Train Loss: 0.0168 | Val ROC-AUC: 0.9600 | Val Profit: -90

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9637
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 24 | Train Loss: 0.0165 | Val ROC-AUC: 0.9637 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9167
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0152 | Val ROC-AUC: 0.9167 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9493
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 26 | Train Loss: 0.0156 | Val ROC-AUC: 0.9493 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9433
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 27 | Train Loss: 0.0139 | Val ROC-AUC: 0.9433 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9239
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0131 | Val ROC-AUC: 0.9239 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.936
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 29 | Train Loss: 0.0112 | Val ROC-AUC: 0.9360 | Val Profit: -155
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9704
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0108 | Val ROC-AUC: 0.9704 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.970355466130114
val
ROC-AUC: 0.9704
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9227
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2122 | Val ROC-AUC: 0.9227 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9477
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1098 | Val ROC-AUC: 0.9477 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9606
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0735 | Val ROC-AUC: 0.9606 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9681
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0567 | Val ROC-AUC: 0.9681 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9725
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 5 | Train Loss: 0.0471 | Val ROC-AUC: 0.9725 | Val Profit: -265
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.961
Precision: 0.5161
Recall: 0.7619
F0.5-score: 0.5517
Profit: -320

Эпоха 6 | Train Loss: 0.0438 | Val ROC-AUC: 0.9610 | Val Profit: -320
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9773
Precision: 0.5862
Recall: 0.8095
F0.5-score: 0.6204
Profit: -235

Эпоха 7 | Train Loss: 0.0373 | Val ROC-AUC: 0.9773 | Val Profit: -235
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9103
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 8 | Train Loss: 0.0370 | Val ROC-AUC: 0.9103 | Val Profit: -200
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9577
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 9 | Train Loss: 0.0350 | Val ROC-AUC: 0.9577 | Val Profit: -210
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9776
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 10 | Train Loss: 0.0279 | Val ROC-AUC: 0.9776 | Val Profit: -230
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9308
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 11 | Train Loss: 0.0320 | Val ROC-AUC: 0.9308 | Val Profit: -250
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9274
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 12 | Train Loss: 0.0321 | Val ROC-AUC: 0.9274 | Val Profit: -170
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9221
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 13 | Train Loss: 0.0273 | Val ROC-AUC: 0.9221 | Val Profit: -145
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9657
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 14 | Train Loss: 0.0283 | Val ROC-AUC: 0.9657 | Val Profit: -85
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9792
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 15 | Train Loss: 0.0271 | Val ROC-AUC: 0.9792 | Val Profit: -80
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9367
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 16 | Train Loss: 0.0270 | Val ROC-AUC: 0.9367 | Val Profit: -145
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9708
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 17 | Train Loss: 0.0228 | Val ROC-AUC: 0.9708 | Val Profit: -145
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9702
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 18 | Train Loss: 0.0174 | Val ROC-AUC: 0.9702 | Val Profit: -150
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9394
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 19 | Train Loss: 0.0177 | Val ROC-AUC: 0.9394 | Val Profit: -45
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8802
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 20 | Train Loss: 0.0223 | Val ROC-AUC: 0.8802 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9791
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 21 | Train Loss: 0.0225 | Val ROC-AUC: 0.9791 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9759
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 22 | Train Loss: 0.0177 | Val ROC-AUC: 0.9759 | Val Profit: -65
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9738
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 23 | Train Loss: 0.0127 | Val ROC-AUC: 0.9738 | Val Profit: -95
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9245
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 24 | Train Loss: 0.0114 | Val ROC-AUC: 0.9245 | Val Profit: -165
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9686
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 25 | Train Loss: 0.0110 | Val ROC-AUC: 0.9686 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9573
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 26 | Train Loss: 0.0059 | Val ROC-AUC: 0.9573 | Val Profit: -200
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9266
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 27 | Train Loss: 0.0047 | Val ROC-AUC: 0.9266 | Val Profit: -135
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9235
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 28 | Train Loss: 0.0028 | Val ROC-AUC: 0.9235 | Val Profit: -150
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9258
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 29 | Train Loss: 0.0029 | Val ROC-AUC: 0.9258 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9573
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 30 | Train Loss: 0.0047 | Val ROC-AUC: 0.9573 | Val Profit: -180

Лучшая эпоха для model_9_Focal_loss: 15
Лучший ROC-AUC: 0.9792085848423876
val
ROC-AUC: 0.9792
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8924
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 1 | Train Loss: 0.2120 | Val ROC-AUC: 0.8924 | Val Profit: -120
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9439
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 2 | Train Loss: 0.1075 | Val ROC-AUC: 0.9439 | Val Profit: -80
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.949
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 3 | Train Loss: 0.0708 | Val ROC-AUC: 0.9490 | Val Profit: -145
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9678
Precision: 0.4615
Recall: 0.8571
F0.5-score: 0.5085
Profit: -450

Эпоха 4 | Train Loss: 0.0585 | Val ROC-AUC: 0.9678 | Val Profit: -450
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9666
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 5 | Train Loss: 0.0493 | Val ROC-AUC: 0.9666 | Val Profit: -160
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9466
Precision: 0.4
Recall: 0.5714
F0.5-score: 0.4255
Profit: -435

Эпоха 6 | Train Loss: 0.0464 | Val ROC-AUC: 0.9466 | Val Profit: -435
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.961
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 7 | Train Loss: 0.0420 | Val ROC-AUC: 0.9610 | Val Profit: -140
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9791
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 8 | Train Loss: 0.0388 | Val ROC-AUC: 0.9791 | Val Profit: -135
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9852
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

Эпоха 9 | Train Loss: 0.0363 | Val ROC-AUC: 0.9852 | Val Profit: -85
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9718
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 10 | Train Loss: 0.0336 | Val ROC-AUC: 0.9718 | Val Profit: -115
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9726
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 11 | Train Loss: 0.0314 | Val ROC-AUC: 0.9726 | Val Profit: -165
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.963
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 12 | Train Loss: 0.0301 | Val ROC-AUC: 0.9630 | Val Profit: -180
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9092
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 13 | Train Loss: 0.0304 | Val ROC-AUC: 0.9092 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9822
Precision: 0.4667
Recall: 1.0
F0.5-score: 0.5224
Profit: -495

Эпоха 14 | Train Loss: 0.0291 | Val ROC-AUC: 0.9822 | Val Profit: -495
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9761
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 15 | Train Loss: 0.0308 | Val ROC-AUC: 0.9761 | Val Profit: -110
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9363
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 16 | Train Loss: 0.0266 | Val ROC-AUC: 0.9363 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9702
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 17 | Train Loss: 0.0223 | Val ROC-AUC: 0.9702 | Val Profit: -145
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9781
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 18 | Train Loss: 0.0277 | Val ROC-AUC: 0.9781 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.8931
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 19 | Train Loss: 0.0205 | Val ROC-AUC: 0.8931 | Val Profit: -115
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8394
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 20 | Train Loss: 0.0205 | Val ROC-AUC: 0.8394 | Val Profit: -195
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.8011
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 21 | Train Loss: 0.0221 | Val ROC-AUC: 0.8011 | Val Profit: -100
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9101
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 22 | Train Loss: 0.0184 | Val ROC-AUC: 0.9101 | Val Profit: -95
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.6848
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 23 | Train Loss: 0.0174 | Val ROC-AUC: 0.6848 | Val Profit: -90
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8122
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 24 | Train Loss: 0.0132 | Val ROC-AUC: 0.8122 | Val Profit: -150
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.7632
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 25 | Train Loss: 0.0114 | Val ROC-AUC: 0.7632 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9065
Precision: 0.9286
Recall: 0.619
F0.5-score: 0.8442
Profit: 0

Эпоха 26 | Train Loss: 0.0216 | Val ROC-AUC: 0.9065 | Val Profit: 0
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.8899
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 27 | Train Loss: 0.0206 | Val ROC-AUC: 0.8899 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9323
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 28 | Train Loss: 0.0191 | Val ROC-AUC: 0.9323 | Val Profit: -100
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9027
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 29 | Train Loss: 0.0129 | Val ROC-AUC: 0.9027 | Val Profit: -165
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.7812
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 30 | Train Loss: 0.0085 | Val ROC-AUC: 0.7812 | Val Profit: -80

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9852448021462106
val
ROC-AUC: 0.9852
Precision: 0.75
Recall: 0.5714
F0.5-score: 0.7059
Profit: -85

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9111
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2108 | Val ROC-AUC: 0.9111 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9588
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1080 | Val ROC-AUC: 0.9588 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9708
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0716 | Val ROC-AUC: 0.9708 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9677
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0581 | Val ROC-AUC: 0.9677 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9757
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 5 | Train Loss: 0.0484 | Val ROC-AUC: 0.9757 | Val Profit: -200
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9482
Precision: 0.3846
Recall: 0.7143
F0.5-score: 0.4237
Profit: -555

Эпоха 6 | Train Loss: 0.0464 | Val ROC-AUC: 0.9482 | Val Profit: -555
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9602
Precision: 0.3889
Recall: 0.3333
F0.5-score: 0.3763
Profit: -310

Эпоха 7 | Train Loss: 0.0459 | Val ROC-AUC: 0.9602 | Val Profit: -310
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9736
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 8 | Train Loss: 0.0436 | Val ROC-AUC: 0.9736 | Val Profit: -165
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9706
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 9 | Train Loss: 0.0390 | Val ROC-AUC: 0.9706 | Val Profit: -205
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9689
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 10 | Train Loss: 0.0357 | Val ROC-AUC: 0.9689 | Val Profit: -225
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9567
Precision: 0.3846
Recall: 0.2381
F0.5-score: 0.3425
Profit: -255

Эпоха 11 | Train Loss: 0.0353 | Val ROC-AUC: 0.9567 | Val Profit: -255
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9751
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 12 | Train Loss: 0.0374 | Val ROC-AUC: 0.9751 | Val Profit: -95
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9701
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 13 | Train Loss: 0.0366 | Val ROC-AUC: 0.9701 | Val Profit: -155
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9796
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 14 | Train Loss: 0.0341 | Val ROC-AUC: 0.9796 | Val Profit: -140
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9776
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 15 | Train Loss: 0.0361 | Val ROC-AUC: 0.9776 | Val Profit: -60
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9844
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 16 | Train Loss: 0.0387 | Val ROC-AUC: 0.9844 | Val Profit: -70
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9819
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 17 | Train Loss: 0.0300 | Val ROC-AUC: 0.9819 | Val Profit: -60
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.981
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0341 | Val ROC-AUC: 0.9810 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9801
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0318 | Val ROC-AUC: 0.9801 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9824
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 20 | Train Loss: 0.0296 | Val ROC-AUC: 0.9824 | Val Profit: -95
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9394
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0281 | Val ROC-AUC: 0.9394 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9458
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 22 | Train Loss: 0.0263 | Val ROC-AUC: 0.9458 | Val Profit: -90
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9796
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0305 | Val ROC-AUC: 0.9796 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9677
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.0305 | Val ROC-AUC: 0.9677 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9856
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 25 | Train Loss: 0.0271 | Val ROC-AUC: 0.9856 | Val Profit: -70
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9795
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 26 | Train Loss: 0.0295 | Val ROC-AUC: 0.9795 | Val Profit: -140
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9736
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 27 | Train Loss: 0.0272 | Val ROC-AUC: 0.9736 | Val Profit: -155
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9591
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0252 | Val ROC-AUC: 0.9591 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9847
Precision: 0.5714
Recall: 0.9524
F0.5-score: 0.6211
Profit: -280

Эпоха 29 | Train Loss: 0.0304 | Val ROC-AUC: 0.9847 | Val Profit: -280
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9787
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 30 | Train Loss: 0.0291 | Val ROC-AUC: 0.9787 | Val Profit: -145

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.985647216633132
val
ROC-AUC: 0.9856
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9412
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2235 | Val ROC-AUC: 0.9412 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9358
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1175 | Val ROC-AUC: 0.9358 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9573
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0732 | Val ROC-AUC: 0.9573 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9399
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0578 | Val ROC-AUC: 0.9399 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9461
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0489 | Val ROC-AUC: 0.9461 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9576
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0475 | Val ROC-AUC: 0.9576 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9553
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0478 | Val ROC-AUC: 0.9553 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.912
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0464 | Val ROC-AUC: 0.9120 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0382 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0341 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0314 | Val ROC-AUC: 0.9725 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9746
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0295 | Val ROC-AUC: 0.9746 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9691
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0289 | Val ROC-AUC: 0.9691 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9293
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0269 | Val ROC-AUC: 0.9293 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0244 | Val ROC-AUC: 0.9599 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9587
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0248 | Val ROC-AUC: 0.9587 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8638
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 17 | Train Loss: 0.0273 | Val ROC-AUC: 0.8638 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9223
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 18 | Train Loss: 0.0267 | Val ROC-AUC: 0.9223 | Val Profit: -225
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9653
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 19 | Train Loss: 0.0296 | Val ROC-AUC: 0.9653 | Val Profit: -235
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9452
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 20 | Train Loss: 0.0279 | Val ROC-AUC: 0.9452 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9577
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 21 | Train Loss: 0.0251 | Val ROC-AUC: 0.9577 | Val Profit: -90
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9659
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 22 | Train Loss: 0.0203 | Val ROC-AUC: 0.9659 | Val Profit: -140
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9455
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 23 | Train Loss: 0.0179 | Val ROC-AUC: 0.9455 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9489
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 24 | Train Loss: 0.0169 | Val ROC-AUC: 0.9489 | Val Profit: -165
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9651
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 25 | Train Loss: 0.0183 | Val ROC-AUC: 0.9651 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9728
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 26 | Train Loss: 0.0173 | Val ROC-AUC: 0.9728 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9357
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 27 | Train Loss: 0.0163 | Val ROC-AUC: 0.9357 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9642
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 28 | Train Loss: 0.0148 | Val ROC-AUC: 0.9642 | Val Profit: -160
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9442
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 29 | Train Loss: 0.0138 | Val ROC-AUC: 0.9442 | Val Profit: -185
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9443
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 30 | Train Loss: 0.0130 | Val ROC-AUC: 0.9443 | Val Profit: -195

Лучшая эпоха для model_9_Focal_loss: 12
Лучший ROC-AUC: 0.9746478873239437
val
ROC-AUC: 0.9746
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8365
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2258 | Val ROC-AUC: 0.8365 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9235
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1211 | Val ROC-AUC: 0.9235 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.956
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0786 | Val ROC-AUC: 0.9560 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9579
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0583 | Val ROC-AUC: 0.9579 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0514 | Val ROC-AUC: 0.9598 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9568
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0464 | Val ROC-AUC: 0.9568 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0457 | Val ROC-AUC: 0.9543 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0407 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.97
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0374 | Val ROC-AUC: 0.9700 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9724
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0387 | Val ROC-AUC: 0.9724 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9624
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0366 | Val ROC-AUC: 0.9624 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0337 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.8558
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0313 | Val ROC-AUC: 0.8558 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9366
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0322 | Val ROC-AUC: 0.9366 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9717
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0277 | Val ROC-AUC: 0.9717 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0249 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 17 | Train Loss: 0.0236 | Val ROC-AUC: 0.9602 | Val Profit: -130
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9553
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 18 | Train Loss: 0.0233 | Val ROC-AUC: 0.9553 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9295
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 19 | Train Loss: 0.0229 | Val ROC-AUC: 0.9295 | Val Profit: -150
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9728
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 20 | Train Loss: 0.0244 | Val ROC-AUC: 0.9728 | Val Profit: -95
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9696
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 21 | Train Loss: 0.0225 | Val ROC-AUC: 0.9696 | Val Profit: -280
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9651
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 22 | Train Loss: 0.0224 | Val ROC-AUC: 0.9651 | Val Profit: -110
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9735
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 23 | Train Loss: 0.0246 | Val ROC-AUC: 0.9735 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9508
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 24 | Train Loss: 0.0233 | Val ROC-AUC: 0.9508 | Val Profit: -130
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9268
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 25 | Train Loss: 0.0224 | Val ROC-AUC: 0.9268 | Val Profit: -140
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9247
Precision: 0.3462
Recall: 0.4286
F0.5-score: 0.36
Profit: -440

Эпоха 26 | Train Loss: 0.0286 | Val ROC-AUC: 0.9247 | Val Profit: -440
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9653
Precision: 0.5161
Recall: 0.7619
F0.5-score: 0.5517
Profit: -320

Эпоха 27 | Train Loss: 0.0366 | Val ROC-AUC: 0.9653 | Val Profit: -320
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9706
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 28 | Train Loss: 0.0335 | Val ROC-AUC: 0.9706 | Val Profit: -210
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9351
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0217 | Val ROC-AUC: 0.9351 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9085
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0166 | Val ROC-AUC: 0.9085 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 8
Лучший ROC-AUC: 0.9741784037558686
val
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9298
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2256 | Val ROC-AUC: 0.9298 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1167 | Val ROC-AUC: 0.9596 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9527
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0754 | Val ROC-AUC: 0.9527 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9591
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0586 | Val ROC-AUC: 0.9591 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0535 | Val ROC-AUC: 0.9730 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9522
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0497 | Val ROC-AUC: 0.9522 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9576
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0461 | Val ROC-AUC: 0.9576 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0436 | Val ROC-AUC: 0.9518 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0426 | Val ROC-AUC: 0.9650 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9777
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0420 | Val ROC-AUC: 0.9777 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9612
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0463 | Val ROC-AUC: 0.9612 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9647
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0436 | Val ROC-AUC: 0.9647 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0447 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0442 | Val ROC-AUC: 0.9563 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9704
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0441 | Val ROC-AUC: 0.9704 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9757
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0360 | Val ROC-AUC: 0.9757 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0338 | Val ROC-AUC: 0.9671 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9736
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0304 | Val ROC-AUC: 0.9736 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9174
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0376 | Val ROC-AUC: 0.9174 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0345 | Val ROC-AUC: 0.9608 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0325 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9639
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 22 | Train Loss: 0.0323 | Val ROC-AUC: 0.9639 | Val Profit: -95
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.943
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 23 | Train Loss: 0.0296 | Val ROC-AUC: 0.9430 | Val Profit: -100
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8845
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 24 | Train Loss: 0.0272 | Val ROC-AUC: 0.8845 | Val Profit: -195
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9046
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 25 | Train Loss: 0.0255 | Val ROC-AUC: 0.9046 | Val Profit: -170
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9581
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 26 | Train Loss: 0.0270 | Val ROC-AUC: 0.9581 | Val Profit: -360
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9771
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 27 | Train Loss: 0.0263 | Val ROC-AUC: 0.9771 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9565
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 28 | Train Loss: 0.0251 | Val ROC-AUC: 0.9565 | Val Profit: -115
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8729
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 29 | Train Loss: 0.0226 | Val ROC-AUC: 0.8729 | Val Profit: -115
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.807
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 30 | Train Loss: 0.0202 | Val ROC-AUC: 0.8070 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 10
Лучший ROC-AUC: 0.9777330650570086
val
ROC-AUC: 0.9777
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8149
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2310 | Val ROC-AUC: 0.8149 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9317
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1274 | Val ROC-AUC: 0.9317 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9476
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0811 | Val ROC-AUC: 0.9476 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0621 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9447
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0513 | Val ROC-AUC: 0.9447 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9412
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0419 | Val ROC-AUC: 0.9412 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9277
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0376 | Val ROC-AUC: 0.9277 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9624
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0344 | Val ROC-AUC: 0.9624 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9524
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0322 | Val ROC-AUC: 0.9524 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9278
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0307 | Val ROC-AUC: 0.9278 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9556
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0314 | Val ROC-AUC: 0.9556 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0296 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9404
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0282 | Val ROC-AUC: 0.9404 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0270 | Val ROC-AUC: 0.9510 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9458
Precision: 0.4
Recall: 0.381
F0.5-score: 0.396
Profit: -325

Эпоха 15 | Train Loss: 0.0270 | Val ROC-AUC: 0.9458 | Val Profit: -325
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9683
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 16 | Train Loss: 0.0207 | Val ROC-AUC: 0.9683 | Val Profit: -145
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9583
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 17 | Train Loss: 0.0161 | Val ROC-AUC: 0.9583 | Val Profit: -190
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9725
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 18 | Train Loss: 0.0112 | Val ROC-AUC: 0.9725 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9561
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 19 | Train Loss: 0.0079 | Val ROC-AUC: 0.9561 | Val Profit: -70
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9598
Precision: 0.8889
Recall: 0.381
F0.5-score: 0.7018
Profit: -50

Эпоха 20 | Train Loss: 0.0058 | Val ROC-AUC: 0.9598 | Val Profit: -50
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9505
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 21 | Train Loss: 0.0049 | Val ROC-AUC: 0.9505 | Val Profit: -75
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9442
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 22 | Train Loss: 0.0045 | Val ROC-AUC: 0.9442 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9135
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 23 | Train Loss: 0.0048 | Val ROC-AUC: 0.9135 | Val Profit: -100
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9431
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 24 | Train Loss: 0.0042 | Val ROC-AUC: 0.9431 | Val Profit: -75
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9473
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 25 | Train Loss: 0.0039 | Val ROC-AUC: 0.9473 | Val Profit: -65
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9435
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 26 | Train Loss: 0.0038 | Val ROC-AUC: 0.9435 | Val Profit: -65
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9414
Precision: 0.9
Recall: 0.4286
F0.5-score: 0.7377
Profit: -40

Эпоха 27 | Train Loss: 0.0036 | Val ROC-AUC: 0.9414 | Val Profit: -40
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9357
Precision: 0.8889
Recall: 0.381
F0.5-score: 0.7018
Profit: -50

Эпоха 28 | Train Loss: 0.0036 | Val ROC-AUC: 0.9357 | Val Profit: -50
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9349
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 29 | Train Loss: 0.0035 | Val ROC-AUC: 0.9349 | Val Profit: -75
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9333
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 30 | Train Loss: 0.0034 | Val ROC-AUC: 0.9333 | Val Profit: -75

Лучшая эпоха для model_9_Focal_loss: 18
Лучший ROC-AUC: 0.9725016767270288
val
ROC-AUC: 0.9725
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8204
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2315 | Val ROC-AUC: 0.8204 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9272
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1278 | Val ROC-AUC: 0.9272 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9537
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0819 | Val ROC-AUC: 0.9537 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0609 | Val ROC-AUC: 0.9745 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9626
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0509 | Val ROC-AUC: 0.9626 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9497
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0461 | Val ROC-AUC: 0.9497 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9564
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0395 | Val ROC-AUC: 0.9564 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9649
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0356 | Val ROC-AUC: 0.9649 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0348 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9635
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0326 | Val ROC-AUC: 0.9635 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9316
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0309 | Val ROC-AUC: 0.9316 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9351
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0295 | Val ROC-AUC: 0.9351 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9227
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0302 | Val ROC-AUC: 0.9227 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9445
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0303 | Val ROC-AUC: 0.9445 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9221
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0306 | Val ROC-AUC: 0.9221 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9433
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0310 | Val ROC-AUC: 0.9433 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9708
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 17 | Train Loss: 0.0301 | Val ROC-AUC: 0.9708 | Val Profit: -125
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9697
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 18 | Train Loss: 0.0242 | Val ROC-AUC: 0.9697 | Val Profit: -45

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9572
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 19 | Train Loss: 0.0228 | Val ROC-AUC: 0.9572 | Val Profit: -95
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.962
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 20 | Train Loss: 0.0241 | Val ROC-AUC: 0.9620 | Val Profit: -90
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9533
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 21 | Train Loss: 0.0230 | Val ROC-AUC: 0.9533 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9435
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 22 | Train Loss: 0.0195 | Val ROC-AUC: 0.9435 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.938
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.0172 | Val ROC-AUC: 0.9380 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9376
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 24 | Train Loss: 0.0162 | Val ROC-AUC: 0.9376 | Val Profit: -120
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9535
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 25 | Train Loss: 0.0153 | Val ROC-AUC: 0.9535 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9531
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 26 | Train Loss: 0.0145 | Val ROC-AUC: 0.9531 | Val Profit: -120
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9545
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0139 | Val ROC-AUC: 0.9545 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9553
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 28 | Train Loss: 0.0133 | Val ROC-AUC: 0.9553 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9561
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 29 | Train Loss: 0.0128 | Val ROC-AUC: 0.9561 | Val Profit: -100
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9592
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0123 | Val ROC-AUC: 0.9592 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 4
Лучший ROC-AUC: 0.9745137491616365
val
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.2319 | Val ROC-AUC: 0.8596 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9486
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.1257 | Val ROC-AUC: 0.9486 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9294
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0794 | Val ROC-AUC: 0.9294 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9586
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0621 | Val ROC-AUC: 0.9586 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9576
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0557 | Val ROC-AUC: 0.9576 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9634
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0507 | Val ROC-AUC: 0.9634 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9315
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0430 | Val ROC-AUC: 0.9315 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9412
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 8 | Train Loss: 0.0403 | Val ROC-AUC: 0.9412 | Val Profit: -95
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9046
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 9 | Train Loss: 0.0367 | Val ROC-AUC: 0.9046 | Val Profit: -120
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9518
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 10 | Train Loss: 0.0373 | Val ROC-AUC: 0.9518 | Val Profit: -185
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9685
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 11 | Train Loss: 0.0283 | Val ROC-AUC: 0.9685 | Val Profit: -65
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9367
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 12 | Train Loss: 0.0250 | Val ROC-AUC: 0.9367 | Val Profit: -110
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9552
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 13 | Train Loss: 0.0195 | Val ROC-AUC: 0.9552 | Val Profit: -65
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9666
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 14 | Train Loss: 0.0198 | Val ROC-AUC: 0.9666 | Val Profit: -225
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9539
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 15 | Train Loss: 0.0297 | Val ROC-AUC: 0.9539 | Val Profit: -220
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9451
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 16 | Train Loss: 0.0266 | Val ROC-AUC: 0.9451 | Val Profit: -245
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.937
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 17 | Train Loss: 0.0180 | Val ROC-AUC: 0.9370 | Val Profit: -65
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9655
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 18 | Train Loss: 0.0149 | Val ROC-AUC: 0.9655 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9583
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 19 | Train Loss: 0.0142 | Val ROC-AUC: 0.9583 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9663
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 20 | Train Loss: 0.0178 | Val ROC-AUC: 0.9663 | Val Profit: -290
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9356
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 21 | Train Loss: 0.0228 | Val ROC-AUC: 0.9356 | Val Profit: -190
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9433
Precision: 0.3846
Recall: 0.2381
F0.5-score: 0.3425
Profit: -255

Эпоха 22 | Train Loss: 0.0183 | Val ROC-AUC: 0.9433 | Val Profit: -255
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9779
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 23 | Train Loss: 0.0191 | Val ROC-AUC: 0.9779 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9572
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 24 | Train Loss: 0.0109 | Val ROC-AUC: 0.9572 | Val Profit: -100
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9529
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0093 | Val ROC-AUC: 0.9529 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9607
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 26 | Train Loss: 0.0073 | Val ROC-AUC: 0.9607 | Val Profit: -100
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9184
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 27 | Train Loss: 0.0065 | Val ROC-AUC: 0.9184 | Val Profit: -110
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8816
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 28 | Train Loss: 0.0060 | Val ROC-AUC: 0.8816 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8794
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 29 | Train Loss: 0.0057 | Val ROC-AUC: 0.8794 | Val Profit: -85
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8778
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 30 | Train Loss: 0.0056 | Val ROC-AUC: 0.8778 | Val Profit: -85

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9778672032193159
val
ROC-AUC: 0.9779
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9171
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0234 | Val ROC-AUC: 0.9171 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9563
Precision: 0.3889
Recall: 0.3333
F0.5-score: 0.3763
Profit: -310

Эпоха 2 | Train Loss: 0.0112 | Val ROC-AUC: 0.9563 | Val Profit: -310

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9612
Precision: 0.4615
Recall: 0.5714
F0.5-score: 0.48
Profit: -335

Эпоха 3 | Train Loss: 0.0080 | Val ROC-AUC: 0.9612 | Val Profit: -335
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9608
Precision: 0.5
Recall: 0.7143
F0.5-score: 0.5319
Profit: -330

Эпоха 4 | Train Loss: 0.0065 | Val ROC-AUC: 0.9608 | Val Profit: -330
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9543
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 5 | Train Loss: 0.0058 | Val ROC-AUC: 0.9543 | Val Profit: -410
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9486
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 6 | Train Loss: 0.0053 | Val ROC-AUC: 0.9486 | Val Profit: -345
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9569
Precision: 0.3846
Recall: 0.7143
F0.5-score: 0.4237
Profit: -555

Эпоха 7 | Train Loss: 0.0049 | Val ROC-AUC: 0.9569 | Val Profit: -555
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9686
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 8 | Train Loss: 0.0049 | Val ROC-AUC: 0.9686 | Val Profit: -295
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9726
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 9 | Train Loss: 0.0050 | Val ROC-AUC: 0.9726 | Val Profit: -175
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9812
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 10 | Train Loss: 0.0044 | Val ROC-AUC: 0.9812 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9846
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 11 | Train Loss: 0.0038 | Val ROC-AUC: 0.9846 | Val Profit: -95
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9756
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 12 | Train Loss: 0.0036 | Val ROC-AUC: 0.9756 | Val Profit: -150
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9726
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 13 | Train Loss: 0.0032 | Val ROC-AUC: 0.9726 | Val Profit: -140
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9761
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 14 | Train Loss: 0.0036 | Val ROC-AUC: 0.9761 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.98
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 15 | Train Loss: 0.0030 | Val ROC-AUC: 0.9800 | Val Profit: -70
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9795
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 16 | Train Loss: 0.0030 | Val ROC-AUC: 0.9795 | Val Profit: -135
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9799
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 17 | Train Loss: 0.0027 | Val ROC-AUC: 0.9799 | Val Profit: -80
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9832
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 18 | Train Loss: 0.0029 | Val ROC-AUC: 0.9832 | Val Profit: -140
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9665
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 19 | Train Loss: 0.0025 | Val ROC-AUC: 0.9665 | Val Profit: -70
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9827
Precision: 0.6296
Recall: 0.8095
F0.5-score: 0.6589
Profit: -185

Эпоха 20 | Train Loss: 0.0034 | Val ROC-AUC: 0.9827 | Val Profit: -185
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9533
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 21 | Train Loss: 0.0036 | Val ROC-AUC: 0.9533 | Val Profit: -60
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9751
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0021 | Val ROC-AUC: 0.9751 | Val Profit: -125
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9567
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0016 | Val ROC-AUC: 0.9567 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9402
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 24 | Train Loss: 0.0017 | Val ROC-AUC: 0.9402 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9218
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 25 | Train Loss: 0.0016 | Val ROC-AUC: 0.9218 | Val Profit: -90
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9471
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 26 | Train Loss: 0.0013 | Val ROC-AUC: 0.9471 | Val Profit: -200
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9449
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 27 | Train Loss: 0.0020 | Val ROC-AUC: 0.9449 | Val Profit: -60
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9655
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 28 | Train Loss: 0.0018 | Val ROC-AUC: 0.9655 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8778
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 29 | Train Loss: 0.0016 | Val ROC-AUC: 0.8778 | Val Profit: -170
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9099
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 30 | Train Loss: 0.0008 | Val ROC-AUC: 0.9099 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 11
Лучший ROC-AUC: 0.9845741113346747
val
ROC-AUC: 0.9846
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9324
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 1 | Train Loss: 0.0231 | Val ROC-AUC: 0.9324 | Val Profit: -95
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9402
Precision: 0.4118
Recall: 0.3333
F0.5-score: 0.3933
Profit: -285

Эпоха 2 | Train Loss: 0.0113 | Val ROC-AUC: 0.9402 | Val Profit: -285
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.956
Precision: 0.4167
Recall: 0.4762
F0.5-score: 0.4274
Profit: -355

Эпоха 3 | Train Loss: 0.0090 | Val ROC-AUC: 0.9560 | Val Profit: -355
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9626
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 4 | Train Loss: 0.0074 | Val ROC-AUC: 0.9626 | Val Profit: -185
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.974
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 5 | Train Loss: 0.0057 | Val ROC-AUC: 0.9740 | Val Profit: -160
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.981
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 6 | Train Loss: 0.0047 | Val ROC-AUC: 0.9810 | Val Profit: -125
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9592
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 7 | Train Loss: 0.0047 | Val ROC-AUC: 0.9592 | Val Profit: -200
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9713
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 8 | Train Loss: 0.0048 | Val ROC-AUC: 0.9713 | Val Profit: -100
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9698
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 9 | Train Loss: 0.0048 | Val ROC-AUC: 0.9698 | Val Profit: -205
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9332
Precision: 0.36
Recall: 0.4286
F0.5-score: 0.3719
Profit: -415

Эпоха 10 | Train Loss: 0.0056 | Val ROC-AUC: 0.9332 | Val Profit: -415
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9728
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 11 | Train Loss: 0.0050 | Val ROC-AUC: 0.9728 | Val Profit: -170
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8221
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 12 | Train Loss: 0.0042 | Val ROC-AUC: 0.8221 | Val Profit: -180
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9759
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 13 | Train Loss: 0.0049 | Val ROC-AUC: 0.9759 | Val Profit: -225
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9616
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 14 | Train Loss: 0.0049 | Val ROC-AUC: 0.9616 | Val Profit: -115
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9772
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 15 | Train Loss: 0.0045 | Val ROC-AUC: 0.9772 | Val Profit: -160
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9807
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 16 | Train Loss: 0.0039 | Val ROC-AUC: 0.9807 | Val Profit: -205
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9666
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 17 | Train Loss: 0.0044 | Val ROC-AUC: 0.9666 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9108
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 18 | Train Loss: 0.0039 | Val ROC-AUC: 0.9108 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9781
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 19 | Train Loss: 0.0044 | Val ROC-AUC: 0.9781 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8846
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 20 | Train Loss: 0.0037 | Val ROC-AUC: 0.8846 | Val Profit: -110
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.972
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0036 | Val ROC-AUC: 0.9720 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9414
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 22 | Train Loss: 0.0034 | Val ROC-AUC: 0.9414 | Val Profit: -145
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.838
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 23 | Train Loss: 0.0033 | Val ROC-AUC: 0.8380 | Val Profit: -95
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9847
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

Эпоха 24 | Train Loss: 0.0040 | Val ROC-AUC: 0.9847 | Val Profit: -340
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9286
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 25 | Train Loss: 0.0040 | Val ROC-AUC: 0.9286 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9712
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 26 | Train Loss: 0.0039 | Val ROC-AUC: 0.9712 | Val Profit: -160
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9144
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0039 | Val ROC-AUC: 0.9144 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8388
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0035 | Val ROC-AUC: 0.8388 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.842
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 29 | Train Loss: 0.0029 | Val ROC-AUC: 0.8420 | Val Profit: -100
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.6306
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 30 | Train Loss: 0.0026 | Val ROC-AUC: 0.6306 | Val Profit: -170

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9847082494969819
val
ROC-AUC: 0.9847
Precision: 0.5278
Recall: 0.9048
F0.5-score: 0.5758
Profit: -340

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9052
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0235 | Val ROC-AUC: 0.9052 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9092
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0118 | Val ROC-AUC: 0.9092 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0092 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9535
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0084 | Val ROC-AUC: 0.9535 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9708
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0076 | Val ROC-AUC: 0.9708 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9679
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0068 | Val ROC-AUC: 0.9679 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9561
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0069 | Val ROC-AUC: 0.9561 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.967
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 8 | Train Loss: 0.0074 | Val ROC-AUC: 0.9670 | Val Profit: -95
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9635
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0070 | Val ROC-AUC: 0.9635 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0068 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0065 | Val ROC-AUC: 0.9725 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0060 | Val ROC-AUC: 0.9706 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9725
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 13 | Train Loss: 0.0060 | Val ROC-AUC: 0.9725 | Val Profit: -205
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0061 | Val ROC-AUC: 0.9773 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.98
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0059 | Val ROC-AUC: 0.9800 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0054 | Val ROC-AUC: 0.9816 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9844
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0053 | Val ROC-AUC: 0.9844 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9796
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 18 | Train Loss: 0.0055 | Val ROC-AUC: 0.9796 | Val Profit: -90
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9753
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 19 | Train Loss: 0.0056 | Val ROC-AUC: 0.9753 | Val Profit: -160
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9875
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0057 | Val ROC-AUC: 0.9875 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9826
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 21 | Train Loss: 0.0052 | Val ROC-AUC: 0.9826 | Val Profit: -85
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9811
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0056 | Val ROC-AUC: 0.9811 | Val Profit: -125
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9801
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0054 | Val ROC-AUC: 0.9801 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9894
Precision: 0.7619
Recall: 0.7619
F0.5-score: 0.7619
Profit: -70

Эпоха 24 | Train Loss: 0.0052 | Val ROC-AUC: 0.9894 | Val Profit: -70
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9779
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 25 | Train Loss: 0.0050 | Val ROC-AUC: 0.9779 | Val Profit: -75
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9862
Precision: 0.7143
Recall: 0.7143
F0.5-score: 0.7143
Profit: -105

Эпоха 26 | Train Loss: 0.0049 | Val ROC-AUC: 0.9862 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9863
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0049 | Val ROC-AUC: 0.9863 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9889
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 28 | Train Loss: 0.0048 | Val ROC-AUC: 0.9889 | Val Profit: -70
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9838
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 29 | Train Loss: 0.0047 | Val ROC-AUC: 0.9838 | Val Profit: -85
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9838
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 30 | Train Loss: 0.0051 | Val ROC-AUC: 0.9838 | Val Profit: -45

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9894030851777331
val
ROC-AUC: 0.9894
Precision: 0.7619
Recall: 0.7619
F0.5-score: 0.7619
Profit: -70

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8735
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0261 | Val ROC-AUC: 0.8735 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.8735
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0138 | Val ROC-AUC: 0.8735 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9502
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0096 | Val ROC-AUC: 0.9502 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9557
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0074 | Val ROC-AUC: 0.9557 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9623
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0065 | Val ROC-AUC: 0.9623 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9553
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 6 | Train Loss: 0.0056 | Val ROC-AUC: 0.9553 | Val Profit: -225
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9392
Precision: 0.4286
Recall: 0.2857
F0.5-score: 0.3896
Profit: -245

Эпоха 7 | Train Loss: 0.0046 | Val ROC-AUC: 0.9392 | Val Profit: -245
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9619
Precision: 0.4474
Recall: 0.8095
F0.5-score: 0.4913
Profit: -460

Эпоха 8 | Train Loss: 0.0039 | Val ROC-AUC: 0.9619 | Val Profit: -460
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.8994
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 9 | Train Loss: 0.0041 | Val ROC-AUC: 0.8994 | Val Profit: -190
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9168
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 10 | Train Loss: 0.0034 | Val ROC-AUC: 0.9168 | Val Profit: -280
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9225
Precision: 0.5
Recall: 0.6667
F0.5-score: 0.5263
Profit: -315

Эпоха 11 | Train Loss: 0.0035 | Val ROC-AUC: 0.9225 | Val Profit: -315
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9634
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 12 | Train Loss: 0.0031 | Val ROC-AUC: 0.9634 | Val Profit: -260
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9763
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 13 | Train Loss: 0.0027 | Val ROC-AUC: 0.9763 | Val Profit: -145
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9704
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 14 | Train Loss: 0.0026 | Val ROC-AUC: 0.9704 | Val Profit: -170
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9615
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 15 | Train Loss: 0.0024 | Val ROC-AUC: 0.9615 | Val Profit: -300
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9518
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 16 | Train Loss: 0.0021 | Val ROC-AUC: 0.9518 | Val Profit: -220
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9681
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 17 | Train Loss: 0.0023 | Val ROC-AUC: 0.9681 | Val Profit: -160
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9258
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 18 | Train Loss: 0.0015 | Val ROC-AUC: 0.9258 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9524
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 19 | Train Loss: 0.0011 | Val ROC-AUC: 0.9524 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9199
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 20 | Train Loss: 0.0013 | Val ROC-AUC: 0.9199 | Val Profit: -135
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9702
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 21 | Train Loss: 0.0007 | Val ROC-AUC: 0.9702 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9685
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 22 | Train Loss: 0.0005 | Val ROC-AUC: 0.9685 | Val Profit: -80
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9689
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 23 | Train Loss: 0.0005 | Val ROC-AUC: 0.9689 | Val Profit: -80
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9689
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 24 | Train Loss: 0.0005 | Val ROC-AUC: 0.9689 | Val Profit: -80
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9689
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 25 | Train Loss: 0.0004 | Val ROC-AUC: 0.9689 | Val Profit: -80
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9694
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 26 | Train Loss: 0.0004 | Val ROC-AUC: 0.9694 | Val Profit: -80
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9693
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 27 | Train Loss: 0.0004 | Val ROC-AUC: 0.9693 | Val Profit: -80
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9687
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 28 | Train Loss: 0.0004 | Val ROC-AUC: 0.9687 | Val Profit: -80
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9686
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 29 | Train Loss: 0.0004 | Val ROC-AUC: 0.9686 | Val Profit: -80
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9681
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 30 | Train Loss: 0.0004 | Val ROC-AUC: 0.9681 | Val Profit: -80

Лучшая эпоха для model_9_Focal_loss: 13
Лучший ROC-AUC: 0.9762575452716298
val
ROC-AUC: 0.9763
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0253 | Val ROC-AUC: 0.8744 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0128 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0091 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9568
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0072 | Val ROC-AUC: 0.9568 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9599
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0064 | Val ROC-AUC: 0.9599 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9686
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0066 | Val ROC-AUC: 0.9686 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9568
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0060 | Val ROC-AUC: 0.9568 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.943
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0063 | Val ROC-AUC: 0.9430 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0061 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0057 | Val ROC-AUC: 0.9268 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9496
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0059 | Val ROC-AUC: 0.9496 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9746
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0051 | Val ROC-AUC: 0.9746 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.937
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0044 | Val ROC-AUC: 0.9370 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9289
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0040 | Val ROC-AUC: 0.9289 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9359
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0038 | Val ROC-AUC: 0.9359 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9184
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0038 | Val ROC-AUC: 0.9184 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.961
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 17 | Train Loss: 0.0044 | Val ROC-AUC: 0.9610 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9489
Precision: 0.3939
Recall: 0.619
F0.5-score: 0.4248
Profit: -475

Эпоха 18 | Train Loss: 0.0060 | Val ROC-AUC: 0.9489 | Val Profit: -475
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9606
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 19 | Train Loss: 0.0045 | Val ROC-AUC: 0.9606 | Val Profit: -190
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9649
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 20 | Train Loss: 0.0037 | Val ROC-AUC: 0.9649 | Val Profit: -200
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9724
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0034 | Val ROC-AUC: 0.9724 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9715
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 22 | Train Loss: 0.0030 | Val ROC-AUC: 0.9715 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0027 | Val ROC-AUC: 0.8567 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9462
Precision: 0.3721
Recall: 0.7619
F0.5-score: 0.4145
Profit: -620

Эпоха 24 | Train Loss: 0.0045 | Val ROC-AUC: 0.9462 | Val Profit: -620
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9215
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 25 | Train Loss: 0.0047 | Val ROC-AUC: 0.9215 | Val Profit: -255

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.703
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 26 | Train Loss: 0.0046 | Val ROC-AUC: 0.7030 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9649
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 27 | Train Loss: 0.0048 | Val ROC-AUC: 0.9649 | Val Profit: -305
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9755
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 28 | Train Loss: 0.0036 | Val ROC-AUC: 0.9755 | Val Profit: -100
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9375
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0028 | Val ROC-AUC: 0.9375 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9308
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0023 | Val ROC-AUC: 0.9308 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9754527162977867
val
ROC-AUC: 0.9755
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8964
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0254 | Val ROC-AUC: 0.8964 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9541
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0133 | Val ROC-AUC: 0.9541 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9274
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0100 | Val ROC-AUC: 0.9274 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0095 | Val ROC-AUC: 0.9498 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9528
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0083 | Val ROC-AUC: 0.9528 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.945
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0080 | Val ROC-AUC: 0.9450 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9325
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0072 | Val ROC-AUC: 0.9325 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9646
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0068 | Val ROC-AUC: 0.9646 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9717
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0059 | Val ROC-AUC: 0.9717 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.976
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 10 | Train Loss: 0.0053 | Val ROC-AUC: 0.9760 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.974
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 11 | Train Loss: 0.0049 | Val ROC-AUC: 0.9740 | Val Profit: -130
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9779
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 12 | Train Loss: 0.0059 | Val ROC-AUC: 0.9779 | Val Profit: -205
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9709
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0050 | Val ROC-AUC: 0.9709 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9776
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0046 | Val ROC-AUC: 0.9776 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9683
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0040 | Val ROC-AUC: 0.9683 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9753
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 16 | Train Loss: 0.0041 | Val ROC-AUC: 0.9753 | Val Profit: -175
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8657
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0041 | Val ROC-AUC: 0.8657 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9771
Precision: 0.3621
Recall: 1.0
F0.5-score: 0.415
Profit: -820

Эпоха 18 | Train Loss: 0.0054 | Val ROC-AUC: 0.9771 | Val Profit: -820
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9796
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0044 | Val ROC-AUC: 0.9796 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9693
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0038 | Val ROC-AUC: 0.9693 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9663
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0035 | Val ROC-AUC: 0.9663 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9591
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 22 | Train Loss: 0.0040 | Val ROC-AUC: 0.9591 | Val Profit: -295
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0039 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9779
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 24 | Train Loss: 0.0036 | Val ROC-AUC: 0.9779 | Val Profit: -285

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9635
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 25 | Train Loss: 0.0038 | Val ROC-AUC: 0.9635 | Val Profit: -210
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0038 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0035 | Val ROC-AUC: 0.9745 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9814
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 28 | Train Loss: 0.0032 | Val ROC-AUC: 0.9814 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8893
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 29 | Train Loss: 0.0033 | Val ROC-AUC: 0.8893 | Val Profit: -155
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9808
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 30 | Train Loss: 0.0040 | Val ROC-AUC: 0.9808 | Val Profit: -230

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9813547954393025
val
ROC-AUC: 0.9814
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.849
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0266 | Val ROC-AUC: 0.8490 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9324
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0134 | Val ROC-AUC: 0.9324 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9288
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0091 | Val ROC-AUC: 0.9288 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0072 | Val ROC-AUC: 0.9513 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9584
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0060 | Val ROC-AUC: 0.9584 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9502
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0057 | Val ROC-AUC: 0.9502 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9207
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0049 | Val ROC-AUC: 0.9207 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9286
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0048 | Val ROC-AUC: 0.9286 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.954
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0048 | Val ROC-AUC: 0.9540 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9168
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0046 | Val ROC-AUC: 0.9168 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9525
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0040 | Val ROC-AUC: 0.9525 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9263
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0040 | Val ROC-AUC: 0.9263 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0039 | Val ROC-AUC: 0.9608 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9612
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 14 | Train Loss: 0.0039 | Val ROC-AUC: 0.9612 | Val Profit: -205
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9549
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 15 | Train Loss: 0.0035 | Val ROC-AUC: 0.9549 | Val Profit: -250
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9386
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 16 | Train Loss: 0.0039 | Val ROC-AUC: 0.9386 | Val Profit: -280
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9414
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 17 | Train Loss: 0.0046 | Val ROC-AUC: 0.9414 | Val Profit: -140
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9586
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 18 | Train Loss: 0.0035 | Val ROC-AUC: 0.9586 | Val Profit: -95
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9704
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 19 | Train Loss: 0.0026 | Val ROC-AUC: 0.9704 | Val Profit: -120
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.966
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 20 | Train Loss: 0.0024 | Val ROC-AUC: 0.9660 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9514
Precision: 0.4231
Recall: 0.5238
F0.5-score: 0.44
Profit: -370

Эпоха 21 | Train Loss: 0.0024 | Val ROC-AUC: 0.9514 | Val Profit: -370
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9559
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 22 | Train Loss: 0.0025 | Val ROC-AUC: 0.9559 | Val Profit: -180
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.922
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 23 | Train Loss: 0.0026 | Val ROC-AUC: 0.9220 | Val Profit: -175
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9717
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 24 | Train Loss: 0.0027 | Val ROC-AUC: 0.9717 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9748
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 25 | Train Loss: 0.0026 | Val ROC-AUC: 0.9748 | Val Profit: -210
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9662
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 26 | Train Loss: 0.0023 | Val ROC-AUC: 0.9662 | Val Profit: -125
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9653
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 27 | Train Loss: 0.0018 | Val ROC-AUC: 0.9653 | Val Profit: -80
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9679
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 28 | Train Loss: 0.0016 | Val ROC-AUC: 0.9679 | Val Profit: -85
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9681
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 29 | Train Loss: 0.0014 | Val ROC-AUC: 0.9681 | Val Profit: -110
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9678
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 30 | Train Loss: 0.0012 | Val ROC-AUC: 0.9678 | Val Profit: -85

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9748490945674044
val
ROC-AUC: 0.9748
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8893
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0264 | Val ROC-AUC: 0.8893 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9512
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0134 | Val ROC-AUC: 0.9512 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9533
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 3 | Train Loss: 0.0097 | Val ROC-AUC: 0.9533 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9293
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0074 | Val ROC-AUC: 0.9293 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.937
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0066 | Val ROC-AUC: 0.9370 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9465
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0065 | Val ROC-AUC: 0.9465 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0062 | Val ROC-AUC: 0.9642 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9317
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0059 | Val ROC-AUC: 0.9317 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.955
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0054 | Val ROC-AUC: 0.9550 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9545
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0051 | Val ROC-AUC: 0.9545 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9496
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0048 | Val ROC-AUC: 0.9496 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.927
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0051 | Val ROC-AUC: 0.9270 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9317
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0059 | Val ROC-AUC: 0.9317 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0049 | Val ROC-AUC: 0.9689 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9329
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0044 | Val ROC-AUC: 0.9329 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0040 | Val ROC-AUC: 0.9344 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9532
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 17 | Train Loss: 0.0040 | Val ROC-AUC: 0.9532 | Val Profit: -215
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9664
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 18 | Train Loss: 0.0043 | Val ROC-AUC: 0.9664 | Val Profit: -240
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9604
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 19 | Train Loss: 0.0040 | Val ROC-AUC: 0.9604 | Val Profit: -135
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9646
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 20 | Train Loss: 0.0033 | Val ROC-AUC: 0.9646 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9195
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 21 | Train Loss: 0.0033 | Val ROC-AUC: 0.9195 | Val Profit: -85
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9628
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 22 | Train Loss: 0.0030 | Val ROC-AUC: 0.9628 | Val Profit: -90
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8771
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 23 | Train Loss: 0.0028 | Val ROC-AUC: 0.8771 | Val Profit: -165
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.7842
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 24 | Train Loss: 0.0026 | Val ROC-AUC: 0.7842 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9229
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 25 | Train Loss: 0.0027 | Val ROC-AUC: 0.9229 | Val Profit: -290
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9364
Precision: 0.3261
Recall: 0.7143
F0.5-score: 0.3659
Profit: -730

Эпоха 26 | Train Loss: 0.0044 | Val ROC-AUC: 0.9364 | Val Profit: -730
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9779
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 27 | Train Loss: 0.0053 | Val ROC-AUC: 0.9779 | Val Profit: -175
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9763
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 28 | Train Loss: 0.0037 | Val ROC-AUC: 0.9763 | Val Profit: -95
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9756
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 29 | Train Loss: 0.0028 | Val ROC-AUC: 0.9756 | Val Profit: -80
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9763
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 30 | Train Loss: 0.0022 | Val ROC-AUC: 0.9763 | Val Profit: -100

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9778672032193159
val
ROC-AUC: 0.9779
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9019
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0267 | Val ROC-AUC: 0.9019 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0137 | Val ROC-AUC: 0.9268 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.921
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0099 | Val ROC-AUC: 0.9210 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9581
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0087 | Val ROC-AUC: 0.9581 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9494
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0080 | Val ROC-AUC: 0.9494 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9612
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0078 | Val ROC-AUC: 0.9612 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9595
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0069 | Val ROC-AUC: 0.9595 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0063 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9551
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 9 | Train Loss: 0.0058 | Val ROC-AUC: 0.9551 | Val Profit: -175
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0056 | Val ROC-AUC: 0.9698 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9362
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 11 | Train Loss: 0.0051 | Val ROC-AUC: 0.9362 | Val Profit: -120
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9716
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 12 | Train Loss: 0.0053 | Val ROC-AUC: 0.9716 | Val Profit: -150
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9532
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0047 | Val ROC-AUC: 0.9532 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9529
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 14 | Train Loss: 0.0053 | Val ROC-AUC: 0.9529 | Val Profit: -120
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9117
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0044 | Val ROC-AUC: 0.9117 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9649
Precision: 0.4333
Recall: 0.619
F0.5-score: 0.461
Profit: -400

Эпоха 16 | Train Loss: 0.0050 | Val ROC-AUC: 0.9649 | Val Profit: -400
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0047 | Val ROC-AUC: 0.9675 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9572
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0045 | Val ROC-AUC: 0.9572 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9584
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 19 | Train Loss: 0.0041 | Val ROC-AUC: 0.9584 | Val Profit: -65
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9725
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 20 | Train Loss: 0.0042 | Val ROC-AUC: 0.9725 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.959
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0035 | Val ROC-AUC: 0.9590 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9693
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 22 | Train Loss: 0.0042 | Val ROC-AUC: 0.9693 | Val Profit: -265
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9553
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 23 | Train Loss: 0.0040 | Val ROC-AUC: 0.9553 | Val Profit: -140
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9642
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 24 | Train Loss: 0.0047 | Val ROC-AUC: 0.9642 | Val Profit: -325
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9726
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 25 | Train Loss: 0.0040 | Val ROC-AUC: 0.9726 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9678
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 26 | Train Loss: 0.0043 | Val ROC-AUC: 0.9678 | Val Profit: -195
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9563
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 27 | Train Loss: 0.0042 | Val ROC-AUC: 0.9563 | Val Profit: -95
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9704
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 28 | Train Loss: 0.0038 | Val ROC-AUC: 0.9704 | Val Profit: -80
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9741
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 29 | Train Loss: 0.0030 | Val ROC-AUC: 0.9741 | Val Profit: -220
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9721
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0037 | Val ROC-AUC: 0.9721 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 29
Лучший ROC-AUC: 0.9741113346747149
val
ROC-AUC: 0.9741
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9167
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0468 | Val ROC-AUC: 0.9167 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9451
Precision: 0.4375
Recall: 0.3333
F0.5-score: 0.4118
Profit: -260

Эпоха 2 | Train Loss: 0.0226 | Val ROC-AUC: 0.9451 | Val Profit: -260
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9646
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 3 | Train Loss: 0.0159 | Val ROC-AUC: 0.9646 | Val Profit: -275
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9645
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 4 | Train Loss: 0.0136 | Val ROC-AUC: 0.9645 | Val Profit: -360
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9525
Precision: 0.4167
Recall: 0.4762
F0.5-score: 0.4274
Profit: -355

Эпоха 5 | Train Loss: 0.0108 | Val ROC-AUC: 0.9525 | Val Profit: -355
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9595
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 6 | Train Loss: 0.0102 | Val ROC-AUC: 0.9595 | Val Profit: -310
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9716
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 7 | Train Loss: 0.0101 | Val ROC-AUC: 0.9716 | Val Profit: -370
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9755
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 8 | Train Loss: 0.0097 | Val ROC-AUC: 0.9755 | Val Profit: -230
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9761
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 9 | Train Loss: 0.0113 | Val ROC-AUC: 0.9761 | Val Profit: -160
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.974
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 10 | Train Loss: 0.0095 | Val ROC-AUC: 0.9740 | Val Profit: -90
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9838
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 11 | Train Loss: 0.0078 | Val ROC-AUC: 0.9838 | Val Profit: -55
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.989
Precision: 0.6429
Recall: 0.8571
F0.5-score: 0.6767
Profit: -175

Эпоха 12 | Train Loss: 0.0078 | Val ROC-AUC: 0.9890 | Val Profit: -175
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9785
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 13 | Train Loss: 0.0084 | Val ROC-AUC: 0.9785 | Val Profit: -95
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.978
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 14 | Train Loss: 0.0065 | Val ROC-AUC: 0.9780 | Val Profit: -240
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9847
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 15 | Train Loss: 0.0061 | Val ROC-AUC: 0.9847 | Val Profit: -125
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9822
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 16 | Train Loss: 0.0058 | Val ROC-AUC: 0.9822 | Val Profit: -125
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9812
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 17 | Train Loss: 0.0079 | Val ROC-AUC: 0.9812 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9771
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 18 | Train Loss: 0.0064 | Val ROC-AUC: 0.9771 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9839
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 19 | Train Loss: 0.0044 | Val ROC-AUC: 0.9839 | Val Profit: -80
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9865
Precision: 0.7619
Recall: 0.7619
F0.5-score: 0.7619
Profit: -70

Эпоха 20 | Train Loss: 0.0046 | Val ROC-AUC: 0.9865 | Val Profit: -70
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9363
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0057 | Val ROC-AUC: 0.9363 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9395
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 22 | Train Loss: 0.0036 | Val ROC-AUC: 0.9395 | Val Profit: -95
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.938
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 23 | Train Loss: 0.0042 | Val ROC-AUC: 0.9380 | Val Profit: -100
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9616
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 24 | Train Loss: 0.0046 | Val ROC-AUC: 0.9616 | Val Profit: -70
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9689
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 25 | Train Loss: 0.0062 | Val ROC-AUC: 0.9689 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9709
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 26 | Train Loss: 0.0032 | Val ROC-AUC: 0.9709 | Val Profit: -160
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.97
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 27 | Train Loss: 0.0026 | Val ROC-AUC: 0.9700 | Val Profit: -175
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9623
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 28 | Train Loss: 0.0019 | Val ROC-AUC: 0.9623 | Val Profit: -185
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9437
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0019 | Val ROC-AUC: 0.9437 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9465
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0024 | Val ROC-AUC: 0.9465 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 12
Лучший ROC-AUC: 0.9890006706908114
val
ROC-AUC: 0.989
Precision: 0.6429
Recall: 0.8571
F0.5-score: 0.6767
Profit: -175

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.949
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0465 | Val ROC-AUC: 0.9490 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9592
Precision: 0.4516
Recall: 0.6667
F0.5-score: 0.4828
Profit: -390

Эпоха 2 | Train Loss: 0.0226 | Val ROC-AUC: 0.9592 | Val Profit: -390
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9598
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 3 | Train Loss: 0.0156 | Val ROC-AUC: 0.9598 | Val Profit: -240
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9689
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 4 | Train Loss: 0.0128 | Val ROC-AUC: 0.9689 | Val Profit: -225
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9694
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 5 | Train Loss: 0.0119 | Val ROC-AUC: 0.9694 | Val Profit: -365
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9638
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 6 | Train Loss: 0.0112 | Val ROC-AUC: 0.9638 | Val Profit: -190
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9781
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 7 | Train Loss: 0.0092 | Val ROC-AUC: 0.9781 | Val Profit: -120
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9665
Precision: 0.4444
Recall: 0.7619
F0.5-score: 0.4848
Profit: -445

Эпоха 8 | Train Loss: 0.0100 | Val ROC-AUC: 0.9665 | Val Profit: -445
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9792
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 9 | Train Loss: 0.0109 | Val ROC-AUC: 0.9792 | Val Profit: -80
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9775
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 10 | Train Loss: 0.0097 | Val ROC-AUC: 0.9775 | Val Profit: -140
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9722
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 11 | Train Loss: 0.0095 | Val ROC-AUC: 0.9722 | Val Profit: -120
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 12 | Train Loss: 0.0090 | Val ROC-AUC: 0.9761 | Val Profit: -130
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9772
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 13 | Train Loss: 0.0066 | Val ROC-AUC: 0.9772 | Val Profit: -60
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9763
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 14 | Train Loss: 0.0068 | Val ROC-AUC: 0.9763 | Val Profit: -270
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9525
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 15 | Train Loss: 0.0073 | Val ROC-AUC: 0.9525 | Val Profit: -115
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9812
Precision: 0.7273
Recall: 0.7619
F0.5-score: 0.7339
Profit: -95

Эпоха 16 | Train Loss: 0.0072 | Val ROC-AUC: 0.9812 | Val Profit: -95
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9768
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 17 | Train Loss: 0.0079 | Val ROC-AUC: 0.9768 | Val Profit: -185
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9704
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 18 | Train Loss: 0.0080 | Val ROC-AUC: 0.9704 | Val Profit: -100
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9769
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 19 | Train Loss: 0.0076 | Val ROC-AUC: 0.9769 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9756
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 20 | Train Loss: 0.0070 | Val ROC-AUC: 0.9756 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9761
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 21 | Train Loss: 0.0059 | Val ROC-AUC: 0.9761 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9639
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 22 | Train Loss: 0.0086 | Val ROC-AUC: 0.9639 | Val Profit: -485
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9759
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 23 | Train Loss: 0.0102 | Val ROC-AUC: 0.9759 | Val Profit: -145
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9775
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 24 | Train Loss: 0.0082 | Val ROC-AUC: 0.9775 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9525
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0071 | Val ROC-AUC: 0.9525 | Val Profit: -130
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9288
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 26 | Train Loss: 0.0066 | Val ROC-AUC: 0.9288 | Val Profit: -110
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9378
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 27 | Train Loss: 0.0068 | Val ROC-AUC: 0.9378 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 28 | Train Loss: 0.0060 | Val ROC-AUC: 0.9268 | Val Profit: -180
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.7832
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -180

Эпоха 29 | Train Loss: 0.0048 | Val ROC-AUC: 0.7832 | Val Profit: -180
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9752
Precision: 0.6818
Recall: 0.7143
F0.5-score: 0.6881
Profit: -130

Эпоха 30 | Train Loss: 0.0064 | Val ROC-AUC: 0.9752 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9812206572769953
val
ROC-AUC: 0.9812
Precision: 0.7273
Recall: 0.7619
F0.5-score: 0.7339
Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9082
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0460 | Val ROC-AUC: 0.9082 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9438
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0235 | Val ROC-AUC: 0.9438 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9066
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0171 | Val ROC-AUC: 0.9066 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9643
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 4 | Train Loss: 0.0153 | Val ROC-AUC: 0.9643 | Val Profit: -85
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9352
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0132 | Val ROC-AUC: 0.9352 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9508
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 6 | Train Loss: 0.0132 | Val ROC-AUC: 0.9508 | Val Profit: -120
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.835
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0118 | Val ROC-AUC: 0.8350 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.978
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 8 | Train Loss: 0.0124 | Val ROC-AUC: 0.9780 | Val Profit: -120
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9729
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0113 | Val ROC-AUC: 0.9729 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9787
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 10 | Train Loss: 0.0108 | Val ROC-AUC: 0.9787 | Val Profit: -110

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9784
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0123 | Val ROC-AUC: 0.9784 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0104 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9775
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 13 | Train Loss: 0.0105 | Val ROC-AUC: 0.9775 | Val Profit: -175
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9771
Precision: 0.5517
Recall: 0.7619
F0.5-score: 0.5839
Profit: -270

Эпоха 14 | Train Loss: 0.0106 | Val ROC-AUC: 0.9771 | Val Profit: -270
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9725
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0116 | Val ROC-AUC: 0.9725 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9767
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 16 | Train Loss: 0.0102 | Val ROC-AUC: 0.9767 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9823
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 17 | Train Loss: 0.0102 | Val ROC-AUC: 0.9823 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.973
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 18 | Train Loss: 0.0098 | Val ROC-AUC: 0.9730 | Val Profit: -95
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0098 | Val ROC-AUC: 0.9710 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9769
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 20 | Train Loss: 0.0099 | Val ROC-AUC: 0.9769 | Val Profit: -165
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9737
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0105 | Val ROC-AUC: 0.9737 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9772
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0097 | Val ROC-AUC: 0.9772 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9789
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.0090 | Val ROC-AUC: 0.9789 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9712
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 24 | Train Loss: 0.0088 | Val ROC-AUC: 0.9712 | Val Profit: -160
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9756
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0086 | Val ROC-AUC: 0.9756 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9805
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 26 | Train Loss: 0.0092 | Val ROC-AUC: 0.9805 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.974
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 27 | Train Loss: 0.0084 | Val ROC-AUC: 0.9740 | Val Profit: -150
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9658
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0089 | Val ROC-AUC: 0.9658 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9594
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 29 | Train Loss: 0.0097 | Val ROC-AUC: 0.9594 | Val Profit: -455

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9847
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 30 | Train Loss: 0.0118 | Val ROC-AUC: 0.9847 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.9847082494969819
val
ROC-AUC: 0.9847
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.87
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0523 | Val ROC-AUC: 0.8700 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9049
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0281 | Val ROC-AUC: 0.9049 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9387
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0191 | Val ROC-AUC: 0.9387 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9416
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0148 | Val ROC-AUC: 0.9416 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9308
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0137 | Val ROC-AUC: 0.9308 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9619
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0120 | Val ROC-AUC: 0.9619 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9627
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0114 | Val ROC-AUC: 0.9627 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0111 | Val ROC-AUC: 0.9575 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0099 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9522
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0087 | Val ROC-AUC: 0.9522 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9319
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0081 | Val ROC-AUC: 0.9319 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9625
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0082 | Val ROC-AUC: 0.9625 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0093 | Val ROC-AUC: 0.9563 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9421
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0099 | Val ROC-AUC: 0.9421 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9564
Precision: 0.4091
Recall: 0.4286
F0.5-score: 0.4128
Profit: -340

Эпоха 15 | Train Loss: 0.0088 | Val ROC-AUC: 0.9564 | Val Profit: -340
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.971
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 16 | Train Loss: 0.0087 | Val ROC-AUC: 0.9710 | Val Profit: -175
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9666
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 17 | Train Loss: 0.0069 | Val ROC-AUC: 0.9666 | Val Profit: -235
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9494
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 18 | Train Loss: 0.0057 | Val ROC-AUC: 0.9494 | Val Profit: -125
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9651
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 19 | Train Loss: 0.0056 | Val ROC-AUC: 0.9651 | Val Profit: -85
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.972
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 20 | Train Loss: 0.0048 | Val ROC-AUC: 0.9720 | Val Profit: -160
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9704
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 21 | Train Loss: 0.0046 | Val ROC-AUC: 0.9704 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9736
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 22 | Train Loss: 0.0043 | Val ROC-AUC: 0.9736 | Val Profit: -150
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9733
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 23 | Train Loss: 0.0041 | Val ROC-AUC: 0.9733 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9737
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 24 | Train Loss: 0.0040 | Val ROC-AUC: 0.9737 | Val Profit: -125
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9733
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 25 | Train Loss: 0.0038 | Val ROC-AUC: 0.9733 | Val Profit: -125
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9732
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 26 | Train Loss: 0.0037 | Val ROC-AUC: 0.9732 | Val Profit: -125
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9722
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 27 | Train Loss: 0.0036 | Val ROC-AUC: 0.9722 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9724
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 28 | Train Loss: 0.0035 | Val ROC-AUC: 0.9724 | Val Profit: -115
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9725
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 29 | Train Loss: 0.0034 | Val ROC-AUC: 0.9725 | Val Profit: -115
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9726
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 30 | Train Loss: 0.0033 | Val ROC-AUC: 0.9726 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9737089201877934
val
ROC-AUC: 0.9737
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8907
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0514 | Val ROC-AUC: 0.8907 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9466
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0263 | Val ROC-AUC: 0.9466 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 3 | Train Loss: 0.0185 | Val ROC-AUC: 0.9544 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.949
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0150 | Val ROC-AUC: 0.9490 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9531
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0132 | Val ROC-AUC: 0.9531 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9296
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0127 | Val ROC-AUC: 0.9296 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9524
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0118 | Val ROC-AUC: 0.9524 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9641
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0117 | Val ROC-AUC: 0.9641 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0108 | Val ROC-AUC: 0.9610 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9604
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0105 | Val ROC-AUC: 0.9604 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9178
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0092 | Val ROC-AUC: 0.9178 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9262
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0089 | Val ROC-AUC: 0.9262 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9476
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0081 | Val ROC-AUC: 0.9476 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.8965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0104 | Val ROC-AUC: 0.8965 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0101 | Val ROC-AUC: 0.9675 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9421
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 16 | Train Loss: 0.0091 | Val ROC-AUC: 0.9421 | Val Profit: -100
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9196
Precision: 0.375
Recall: 0.1429
F0.5-score: 0.283
Profit: -200

Эпоха 17 | Train Loss: 0.0082 | Val ROC-AUC: 0.9196 | Val Profit: -200
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9588
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 18 | Train Loss: 0.0076 | Val ROC-AUC: 0.9588 | Val Profit: -200
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9733
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 19 | Train Loss: 0.0063 | Val ROC-AUC: 0.9733 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.968
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 20 | Train Loss: 0.0056 | Val ROC-AUC: 0.9680 | Val Profit: -175
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.8689
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 21 | Train Loss: 0.0055 | Val ROC-AUC: 0.8689 | Val Profit: -145
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9363
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0061 | Val ROC-AUC: 0.9363 | Val Profit: -125
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9556
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 23 | Train Loss: 0.0048 | Val ROC-AUC: 0.9556 | Val Profit: -145
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9019
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 24 | Train Loss: 0.0047 | Val ROC-AUC: 0.9019 | Val Profit: -135
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9738
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 25 | Train Loss: 0.0040 | Val ROC-AUC: 0.9738 | Val Profit: -115
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.926
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 26 | Train Loss: 0.0045 | Val ROC-AUC: 0.9260 | Val Profit: -110
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.968
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 27 | Train Loss: 0.0064 | Val ROC-AUC: 0.9680 | Val Profit: -295
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9756
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 28 | Train Loss: 0.0061 | Val ROC-AUC: 0.9756 | Val Profit: -185
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9001
Precision: 0.3846
Recall: 0.2381
F0.5-score: 0.3425
Profit: -255

Эпоха 29 | Train Loss: 0.0068 | Val ROC-AUC: 0.9001 | Val Profit: -255
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9645
Precision: 0.5
Recall: 0.619
F0.5-score: 0.52
Profit: -300

Эпоха 30 | Train Loss: 0.0057 | Val ROC-AUC: 0.9645 | Val Profit: -300

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.975586854460094
val
ROC-AUC: 0.9756
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8977
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 1 | Train Loss: 0.0512 | Val ROC-AUC: 0.8977 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9154
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0266 | Val ROC-AUC: 0.9154 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0196 | Val ROC-AUC: 0.9598 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.951
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0157 | Val ROC-AUC: 0.9510 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9427
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0149 | Val ROC-AUC: 0.9427 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9484
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0145 | Val ROC-AUC: 0.9484 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9497
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0155 | Val ROC-AUC: 0.9497 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9522
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0154 | Val ROC-AUC: 0.9522 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9631
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0136 | Val ROC-AUC: 0.9631 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9663
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0128 | Val ROC-AUC: 0.9663 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9583
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0133 | Val ROC-AUC: 0.9583 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0127 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0114 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9776
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0123 | Val ROC-AUC: 0.9776 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9697
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0112 | Val ROC-AUC: 0.9697 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9753
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0102 | Val ROC-AUC: 0.9753 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9183
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0096 | Val ROC-AUC: 0.9183 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0100 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9746
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0095 | Val ROC-AUC: 0.9746 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0093 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9752
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 21 | Train Loss: 0.0096 | Val ROC-AUC: 0.9752 | Val Profit: -185
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9584
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 22 | Train Loss: 0.0110 | Val ROC-AUC: 0.9584 | Val Profit: -230
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9764
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 23 | Train Loss: 0.0109 | Val ROC-AUC: 0.9764 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9745
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0087 | Val ROC-AUC: 0.9745 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 25 | Train Loss: 0.0076 | Val ROC-AUC: 0.9785 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9628
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 26 | Train Loss: 0.0073 | Val ROC-AUC: 0.9628 | Val Profit: -140
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9717
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 27 | Train Loss: 0.0108 | Val ROC-AUC: 0.9717 | Val Profit: -220
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9746
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 28 | Train Loss: 0.0088 | Val ROC-AUC: 0.9746 | Val Profit: -160
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9767
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0070 | Val ROC-AUC: 0.9767 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0069 | Val ROC-AUC: 0.9752 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 25
Лучший ROC-AUC: 0.9785378940308519
val
ROC-AUC: 0.9785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0533 | Val ROC-AUC: 0.8667 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9429
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0271 | Val ROC-AUC: 0.9429 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9372
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0189 | Val ROC-AUC: 0.9372 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9488
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0146 | Val ROC-AUC: 0.9488 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9293
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0127 | Val ROC-AUC: 0.9293 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0115 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0100 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.8553
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0092 | Val ROC-AUC: 0.8553 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9556
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0098 | Val ROC-AUC: 0.9556 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9395
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0095 | Val ROC-AUC: 0.9395 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9606
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0089 | Val ROC-AUC: 0.9606 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0086 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9043
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0091 | Val ROC-AUC: 0.9043 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9659
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0088 | Val ROC-AUC: 0.9659 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9595
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0079 | Val ROC-AUC: 0.9595 | Val Profit: -95
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9646
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 16 | Train Loss: 0.0064 | Val ROC-AUC: 0.9646 | Val Profit: -75
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9579
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 17 | Train Loss: 0.0057 | Val ROC-AUC: 0.9579 | Val Profit: -125
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9675
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 18 | Train Loss: 0.0051 | Val ROC-AUC: 0.9675 | Val Profit: -140
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9628
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 19 | Train Loss: 0.0048 | Val ROC-AUC: 0.9628 | Val Profit: -100
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9658
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 20 | Train Loss: 0.0045 | Val ROC-AUC: 0.9658 | Val Profit: -80
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9646
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 21 | Train Loss: 0.0044 | Val ROC-AUC: 0.9646 | Val Profit: -145
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9718
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 22 | Train Loss: 0.0043 | Val ROC-AUC: 0.9718 | Val Profit: -195
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9382
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 23 | Train Loss: 0.0040 | Val ROC-AUC: 0.9382 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9384
Precision: 0.3704
Recall: 0.4762
F0.5-score: 0.3876
Profit: -430

Эпоха 24 | Train Loss: 0.0056 | Val ROC-AUC: 0.9384 | Val Profit: -430
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.964
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 25 | Train Loss: 0.0066 | Val ROC-AUC: 0.9640 | Val Profit: -385
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9698
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 26 | Train Loss: 0.0059 | Val ROC-AUC: 0.9698 | Val Profit: -140
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.967
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 27 | Train Loss: 0.0054 | Val ROC-AUC: 0.9670 | Val Profit: -250
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9594
Precision: 0.4419
Recall: 0.9048
F0.5-score: 0.4922
Profit: -515

Эпоха 28 | Train Loss: 0.0078 | Val ROC-AUC: 0.9594 | Val Profit: -515
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.948
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 29 | Train Loss: 0.0068 | Val ROC-AUC: 0.9480 | Val Profit: -165
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9427
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 30 | Train Loss: 0.0043 | Val ROC-AUC: 0.9427 | Val Profit: -185

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.971830985915493
val
ROC-AUC: 0.9718
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8934
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0534 | Val ROC-AUC: 0.8934 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9188
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0275 | Val ROC-AUC: 0.9188 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0178 | Val ROC-AUC: 0.9567 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0135 | Val ROC-AUC: 0.9610 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9479
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0118 | Val ROC-AUC: 0.9479 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9295
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0116 | Val ROC-AUC: 0.9295 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9366
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0112 | Val ROC-AUC: 0.9366 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9088
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0106 | Val ROC-AUC: 0.9088 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9597
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0103 | Val ROC-AUC: 0.9597 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0098 | Val ROC-AUC: 0.9575 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9438
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0094 | Val ROC-AUC: 0.9438 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9638
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0086 | Val ROC-AUC: 0.9638 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.929
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0086 | Val ROC-AUC: 0.9290 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9563
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0109 | Val ROC-AUC: 0.9563 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9619
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0098 | Val ROC-AUC: 0.9619 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9598
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0089 | Val ROC-AUC: 0.9598 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9637
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 17 | Train Loss: 0.0078 | Val ROC-AUC: 0.9637 | Val Profit: -70
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9214
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 18 | Train Loss: 0.0072 | Val ROC-AUC: 0.9214 | Val Profit: -295

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9643
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 19 | Train Loss: 0.0076 | Val ROC-AUC: 0.9643 | Val Profit: -60
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9239
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 20 | Train Loss: 0.0074 | Val ROC-AUC: 0.9239 | Val Profit: -155
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9677
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0069 | Val ROC-AUC: 0.9677 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9555
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 22 | Train Loss: 0.0058 | Val ROC-AUC: 0.9555 | Val Profit: -145
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.926
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 23 | Train Loss: 0.0053 | Val ROC-AUC: 0.9260 | Val Profit: -145
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9288
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 24 | Train Loss: 0.0052 | Val ROC-AUC: 0.9288 | Val Profit: -125
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.815
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 25 | Train Loss: 0.0047 | Val ROC-AUC: 0.8150 | Val Profit: -185
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8949
Precision: 0.3
Recall: 0.5714
F0.5-score: 0.3315
Profit: -685

Эпоха 26 | Train Loss: 0.0077 | Val ROC-AUC: 0.8949 | Val Profit: -685
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9124
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 27 | Train Loss: 0.0102 | Val ROC-AUC: 0.9124 | Val Profit: -350
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9048
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 28 | Train Loss: 0.0088 | Val ROC-AUC: 0.9048 | Val Profit: -250
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9594
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 29 | Train Loss: 0.0069 | Val ROC-AUC: 0.9594 | Val Profit: -230
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.963
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 30 | Train Loss: 0.0053 | Val ROC-AUC: 0.9630 | Val Profit: -185

Лучшая эпоха для model_9_Focal_loss: 21
Лучший ROC-AUC: 0.9676727028839704
val
ROC-AUC: 0.9677
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9355
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0525 | Val ROC-AUC: 0.9355 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9501
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0267 | Val ROC-AUC: 0.9501 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9294
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0188 | Val ROC-AUC: 0.9294 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9429
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0166 | Val ROC-AUC: 0.9429 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9285
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0145 | Val ROC-AUC: 0.9285 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9459
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0150 | Val ROC-AUC: 0.9459 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9442
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0137 | Val ROC-AUC: 0.9442 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9663
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0133 | Val ROC-AUC: 0.9663 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9612
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0124 | Val ROC-AUC: 0.9612 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0117 | Val ROC-AUC: 0.9611 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.8872
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0107 | Val ROC-AUC: 0.8872 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9588
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0110 | Val ROC-AUC: 0.9588 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0107 | Val ROC-AUC: 0.9516 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0114 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9376
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0105 | Val ROC-AUC: 0.9376 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0110 | Val ROC-AUC: 0.9651 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9741
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0109 | Val ROC-AUC: 0.9741 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9728
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0096 | Val ROC-AUC: 0.9728 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9653
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0087 | Val ROC-AUC: 0.9653 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9722
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0079 | Val ROC-AUC: 0.9722 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9636
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 21 | Train Loss: 0.0081 | Val ROC-AUC: 0.9636 | Val Profit: -125
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9587
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 22 | Train Loss: 0.0091 | Val ROC-AUC: 0.9587 | Val Profit: -115
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9556
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0084 | Val ROC-AUC: 0.9556 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9669
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 24 | Train Loss: 0.0080 | Val ROC-AUC: 0.9669 | Val Profit: -170
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9594
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 25 | Train Loss: 0.0084 | Val ROC-AUC: 0.9594 | Val Profit: -120
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9694
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 26 | Train Loss: 0.0089 | Val ROC-AUC: 0.9694 | Val Profit: -100

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9614
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 27 | Train Loss: 0.0081 | Val ROC-AUC: 0.9614 | Val Profit: -110
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9649
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 28 | Train Loss: 0.0070 | Val ROC-AUC: 0.9649 | Val Profit: -195
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0062 | Val ROC-AUC: 0.9721 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9614
Precision: 0.4359
Recall: 0.8095
F0.5-score: 0.4802
Profit: -485

Эпоха 30 | Train Loss: 0.0060 | Val ROC-AUC: 0.9614 | Val Profit: -485

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.974111334674715
val
ROC-AUC: 0.9741
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9249
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0929 | Val ROC-AUC: 0.9249 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9575
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 2 | Train Loss: 0.0445 | Val ROC-AUC: 0.9575 | Val Profit: -255
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9549
Precision: 0.4242
Recall: 0.6667
F0.5-score: 0.4575
Profit: -440

Эпоха 3 | Train Loss: 0.0319 | Val ROC-AUC: 0.9549 | Val Profit: -440
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9581
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 4 | Train Loss: 0.0254 | Val ROC-AUC: 0.9581 | Val Profit: -310
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.969
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 5 | Train Loss: 0.0229 | Val ROC-AUC: 0.9690 | Val Profit: -425
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.971
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 6 | Train Loss: 0.0214 | Val ROC-AUC: 0.9710 | Val Profit: -225
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9718
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 7 | Train Loss: 0.0208 | Val ROC-AUC: 0.9718 | Val Profit: -200
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9765
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 8 | Train Loss: 0.0178 | Val ROC-AUC: 0.9765 | Val Profit: -120
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9751
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 9 | Train Loss: 0.0139 | Val ROC-AUC: 0.9751 | Val Profit: -210
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9623
Precision: 0.4545
Recall: 0.7143
F0.5-score: 0.4902
Profit: -405

Эпоха 10 | Train Loss: 0.0185 | Val ROC-AUC: 0.9623 | Val Profit: -405
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.974
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 11 | Train Loss: 0.0190 | Val ROC-AUC: 0.9740 | Val Profit: -145
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9575
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 12 | Train Loss: 0.0129 | Val ROC-AUC: 0.9575 | Val Profit: -205
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9729
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 13 | Train Loss: 0.0109 | Val ROC-AUC: 0.9729 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9811
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 14 | Train Loss: 0.0115 | Val ROC-AUC: 0.9811 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9881
Precision: 0.85
Recall: 0.8095
F0.5-score: 0.8416
Profit: -10

Эпоха 15 | Train Loss: 0.0133 | Val ROC-AUC: 0.9881 | Val Profit: -10
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9708
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 16 | Train Loss: 0.0141 | Val ROC-AUC: 0.9708 | Val Profit: -185
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9749
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 17 | Train Loss: 0.0122 | Val ROC-AUC: 0.9749 | Val Profit: -175
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9529
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 18 | Train Loss: 0.0084 | Val ROC-AUC: 0.9529 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9602
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 19 | Train Loss: 0.0109 | Val ROC-AUC: 0.9602 | Val Profit: -345
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9736
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 20 | Train Loss: 0.0156 | Val ROC-AUC: 0.9736 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9789
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 21 | Train Loss: 0.0100 | Val ROC-AUC: 0.9789 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9738
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 22 | Train Loss: 0.0069 | Val ROC-AUC: 0.9738 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.945
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 23 | Train Loss: 0.0061 | Val ROC-AUC: 0.9450 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9746
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 24 | Train Loss: 0.0060 | Val ROC-AUC: 0.9746 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9294
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 25 | Train Loss: 0.0070 | Val ROC-AUC: 0.9294 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9524
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 26 | Train Loss: 0.0090 | Val ROC-AUC: 0.9524 | Val Profit: -155
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9733
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 27 | Train Loss: 0.0113 | Val ROC-AUC: 0.9733 | Val Profit: -115
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 28 | Train Loss: 0.0081 | Val ROC-AUC: 0.9611 | Val Profit: -155
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9623
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 29 | Train Loss: 0.0053 | Val ROC-AUC: 0.9623 | Val Profit: -135
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9349
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 30 | Train Loss: 0.0033 | Val ROC-AUC: 0.9349 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 15
Лучший ROC-AUC: 0.9880617035546613
val
ROC-AUC: 0.9881
Precision: 0.85
Recall: 0.8095
F0.5-score: 0.8416
Profit: -10

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9258
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 1 | Train Loss: 0.0915 | Val ROC-AUC: 0.9258 | Val Profit: -145
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9399
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 2 | Train Loss: 0.0450 | Val ROC-AUC: 0.9399 | Val Profit: -280
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9531
Precision: 0.3
Recall: 0.1429
F0.5-score: 0.2459
Profit: -250

Эпоха 3 | Train Loss: 0.0320 | Val ROC-AUC: 0.9531 | Val Profit: -250
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9607
Precision: 0.5
Recall: 0.8095
F0.5-score: 0.5414
Profit: -360

Эпоха 4 | Train Loss: 0.0268 | Val ROC-AUC: 0.9607 | Val Profit: -360
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9594
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 5 | Train Loss: 0.0248 | Val ROC-AUC: 0.9594 | Val Profit: -280
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9666
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 6 | Train Loss: 0.0210 | Val ROC-AUC: 0.9666 | Val Profit: -260
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9696
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 7 | Train Loss: 0.0208 | Val ROC-AUC: 0.9696 | Val Profit: -260
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9728
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 8 | Train Loss: 0.0184 | Val ROC-AUC: 0.9728 | Val Profit: -170
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9685
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 9 | Train Loss: 0.0187 | Val ROC-AUC: 0.9685 | Val Profit: -155
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9792
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 10 | Train Loss: 0.0173 | Val ROC-AUC: 0.9792 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9759
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 11 | Train Loss: 0.0147 | Val ROC-AUC: 0.9759 | Val Profit: -135
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9801
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 12 | Train Loss: 0.0181 | Val ROC-AUC: 0.9801 | Val Profit: -85
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9846
Precision: 0.8333
Recall: 0.4762
F0.5-score: 0.7246
Profit: -55

Эпоха 13 | Train Loss: 0.0162 | Val ROC-AUC: 0.9846 | Val Profit: -55
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9714
Precision: 0.5185
Recall: 0.6667
F0.5-score: 0.5426
Profit: -290

Эпоха 14 | Train Loss: 0.0149 | Val ROC-AUC: 0.9714 | Val Profit: -290
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9577
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 15 | Train Loss: 0.0164 | Val ROC-AUC: 0.9577 | Val Profit: -210
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9757
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 16 | Train Loss: 0.0177 | Val ROC-AUC: 0.9757 | Val Profit: -215
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9663
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 17 | Train Loss: 0.0156 | Val ROC-AUC: 0.9663 | Val Profit: -135
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.971
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 18 | Train Loss: 0.0130 | Val ROC-AUC: 0.9710 | Val Profit: -195
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9345
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 19 | Train Loss: 0.0130 | Val ROC-AUC: 0.9345 | Val Profit: -85
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9536
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 20 | Train Loss: 0.0120 | Val ROC-AUC: 0.9536 | Val Profit: -180
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9797
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 21 | Train Loss: 0.0138 | Val ROC-AUC: 0.9797 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9898
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 22 | Train Loss: 0.0110 | Val ROC-AUC: 0.9898 | Val Profit: -45
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9863
Precision: 0.68
Recall: 0.8095
F0.5-score: 0.7025
Profit: -135

Эпоха 23 | Train Loss: 0.0159 | Val ROC-AUC: 0.9863 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9532
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 24 | Train Loss: 0.0132 | Val ROC-AUC: 0.9532 | Val Profit: -95
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9869
Precision: 0.8125
Recall: 0.619
F0.5-score: 0.7647
Profit: -50

Эпоха 25 | Train Loss: 0.0116 | Val ROC-AUC: 0.9869 | Val Profit: -50
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9839
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 26 | Train Loss: 0.0118 | Val ROC-AUC: 0.9839 | Val Profit: -75
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9565
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 27 | Train Loss: 0.0097 | Val ROC-AUC: 0.9565 | Val Profit: -80
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9666
Precision: 0.8571
Recall: 0.5714
F0.5-score: 0.7792
Profit: -35

Эпоха 28 | Train Loss: 0.0110 | Val ROC-AUC: 0.9666 | Val Profit: -35
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9721
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 29 | Train Loss: 0.0097 | Val ROC-AUC: 0.9721 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9636
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 30 | Train Loss: 0.0067 | Val ROC-AUC: 0.9636 | Val Profit: -85

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9898054996646546
val
ROC-AUC: 0.9898
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9278
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 1 | Train Loss: 0.0912 | Val ROC-AUC: 0.9278 | Val Profit: -130
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9504
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0450 | Val ROC-AUC: 0.9504 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9728
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0337 | Val ROC-AUC: 0.9728 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9587
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 4 | Train Loss: 0.0262 | Val ROC-AUC: 0.9587 | Val Profit: -115

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.971
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 5 | Train Loss: 0.0272 | Val ROC-AUC: 0.9710 | Val Profit: -115
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9682
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 6 | Train Loss: 0.0230 | Val ROC-AUC: 0.9682 | Val Profit: -115
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9724
Precision: 0.5152
Recall: 0.8095
F0.5-score: 0.5556
Profit: -335

Эпоха 7 | Train Loss: 0.0220 | Val ROC-AUC: 0.9724 | Val Profit: -335
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9655
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 8 | Train Loss: 0.0214 | Val ROC-AUC: 0.9655 | Val Profit: -110
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9718
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 9 | Train Loss: 0.0231 | Val ROC-AUC: 0.9718 | Val Profit: -275
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.976
Precision: 0.6111
Recall: 0.5238
F0.5-score: 0.5914
Profit: -170

Эпоха 10 | Train Loss: 0.0216 | Val ROC-AUC: 0.9760 | Val Profit: -170
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.8915
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0194 | Val ROC-AUC: 0.8915 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9559
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 12 | Train Loss: 0.0197 | Val ROC-AUC: 0.9559 | Val Profit: -180
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9736
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 13 | Train Loss: 0.0212 | Val ROC-AUC: 0.9736 | Val Profit: -85
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.978
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 14 | Train Loss: 0.0231 | Val ROC-AUC: 0.9780 | Val Profit: -155

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9729
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0253 | Val ROC-AUC: 0.9729 | Val Profit: -95
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9746
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 16 | Train Loss: 0.0179 | Val ROC-AUC: 0.9746 | Val Profit: -130
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9728
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 17 | Train Loss: 0.0186 | Val ROC-AUC: 0.9728 | Val Profit: -145
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9738
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 18 | Train Loss: 0.0170 | Val ROC-AUC: 0.9738 | Val Profit: -190
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9553
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 19 | Train Loss: 0.0193 | Val ROC-AUC: 0.9553 | Val Profit: -160
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9834
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 20 | Train Loss: 0.0200 | Val ROC-AUC: 0.9834 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9781
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0165 | Val ROC-AUC: 0.9781 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9492
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0164 | Val ROC-AUC: 0.9492 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9729
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 23 | Train Loss: 0.0170 | Val ROC-AUC: 0.9729 | Val Profit: -150
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9811
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 24 | Train Loss: 0.0218 | Val ROC-AUC: 0.9811 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.985
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0186 | Val ROC-AUC: 0.9850 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9827
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0151 | Val ROC-AUC: 0.9827 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9895
Precision: 0.9167
Recall: 0.5238
F0.5-score: 0.7971
Profit: -20

Эпоха 27 | Train Loss: 0.0155 | Val ROC-AUC: 0.9895 | Val Profit: -20
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9815
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 28 | Train Loss: 0.0195 | Val ROC-AUC: 0.9815 | Val Profit: -85
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.974
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0158 | Val ROC-AUC: 0.9740 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9645
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.0141 | Val ROC-AUC: 0.9645 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9895372233400402
val
ROC-AUC: 0.9895
Precision: 0.9167
Recall: 0.5238
F0.5-score: 0.7971
Profit: -20

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.879
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1035 | Val ROC-AUC: 0.8790 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9198
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0545 | Val ROC-AUC: 0.9198 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9285
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0380 | Val ROC-AUC: 0.9285 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9422
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 4 | Train Loss: 0.0297 | Val ROC-AUC: 0.9422 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0272 | Val ROC-AUC: 0.9608 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9339
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0238 | Val ROC-AUC: 0.9339 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9135
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0205 | Val ROC-AUC: 0.9135 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9553
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0192 | Val ROC-AUC: 0.9553 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0176 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9627
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0173 | Val ROC-AUC: 0.9627 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9691
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0179 | Val ROC-AUC: 0.9691 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9053
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0196 | Val ROC-AUC: 0.9053 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9504
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0178 | Val ROC-AUC: 0.9504 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0160 | Val ROC-AUC: 0.9661 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9463
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 15 | Train Loss: 0.0136 | Val ROC-AUC: 0.9463 | Val Profit: -180
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.8926
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 16 | Train Loss: 0.0126 | Val ROC-AUC: 0.8926 | Val Profit: -130
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8934
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 17 | Train Loss: 0.0107 | Val ROC-AUC: 0.8934 | Val Profit: -135
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.8992
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 18 | Train Loss: 0.0101 | Val ROC-AUC: 0.8992 | Val Profit: -205
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.864
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 19 | Train Loss: 0.0094 | Val ROC-AUC: 0.8640 | Val Profit: -185
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8896
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 20 | Train Loss: 0.0088 | Val ROC-AUC: 0.8896 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9115
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 21 | Train Loss: 0.0100 | Val ROC-AUC: 0.9115 | Val Profit: -135
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8245
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 22 | Train Loss: 0.0088 | Val ROC-AUC: 0.8245 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9101
Precision: 0.3846
Recall: 0.7143
F0.5-score: 0.4237
Profit: -555

Эпоха 23 | Train Loss: 0.0126 | Val ROC-AUC: 0.9101 | Val Profit: -555
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9486
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 24 | Train Loss: 0.0147 | Val ROC-AUC: 0.9486 | Val Profit: -205
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9624
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 25 | Train Loss: 0.0128 | Val ROC-AUC: 0.9624 | Val Profit: -185
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9379
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 26 | Train Loss: 0.0100 | Val ROC-AUC: 0.9379 | Val Profit: -225
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9725
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 27 | Train Loss: 0.0077 | Val ROC-AUC: 0.9725 | Val Profit: -140
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8813
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 28 | Train Loss: 0.0072 | Val ROC-AUC: 0.8813 | Val Profit: -150
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8793
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 29 | Train Loss: 0.0065 | Val ROC-AUC: 0.8793 | Val Profit: -155
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9343
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 30 | Train Loss: 0.0053 | Val ROC-AUC: 0.9343 | Val Profit: -160

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9725016767270288
val
ROC-AUC: 0.9725
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8981
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1027 | Val ROC-AUC: 0.8981 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9435
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0522 | Val ROC-AUC: 0.9435 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9459
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0365 | Val ROC-AUC: 0.9459 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9535
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0282 | Val ROC-AUC: 0.9535 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9556
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0272 | Val ROC-AUC: 0.9556 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9561
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0247 | Val ROC-AUC: 0.9561 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0257 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9536
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0245 | Val ROC-AUC: 0.9536 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0215 | Val ROC-AUC: 0.9698 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9243
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0194 | Val ROC-AUC: 0.9243 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9013
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0179 | Val ROC-AUC: 0.9013 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0175 | Val ROC-AUC: 0.9411 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0169 | Val ROC-AUC: 0.9773 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9176
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0179 | Val ROC-AUC: 0.9176 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9645
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0187 | Val ROC-AUC: 0.9645 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9713
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 16 | Train Loss: 0.0163 | Val ROC-AUC: 0.9713 | Val Profit: -165
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9641
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 17 | Train Loss: 0.0185 | Val ROC-AUC: 0.9641 | Val Profit: -185
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9733
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 18 | Train Loss: 0.0156 | Val ROC-AUC: 0.9733 | Val Profit: -170
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9735
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 19 | Train Loss: 0.0125 | Val ROC-AUC: 0.9735 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9747
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 20 | Train Loss: 0.0128 | Val ROC-AUC: 0.9747 | Val Profit: -125
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9316
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 21 | Train Loss: 0.0120 | Val ROC-AUC: 0.9316 | Val Profit: -185
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9227
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 22 | Train Loss: 0.0102 | Val ROC-AUC: 0.9227 | Val Profit: -135
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9117
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 23 | Train Loss: 0.0095 | Val ROC-AUC: 0.9117 | Val Profit: -170
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9352
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 24 | Train Loss: 0.0084 | Val ROC-AUC: 0.9352 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9332
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 25 | Train Loss: 0.0115 | Val ROC-AUC: 0.9332 | Val Profit: -170
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9696
Precision: 0.5455
Recall: 0.8571
F0.5-score: 0.5882
Profit: -300

Эпоха 26 | Train Loss: 0.0134 | Val ROC-AUC: 0.9696 | Val Profit: -300
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9342
Precision: 0.5
Recall: 0.6667
F0.5-score: 0.5263
Profit: -315

Эпоха 27 | Train Loss: 0.0160 | Val ROC-AUC: 0.9342 | Val Profit: -315
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8651
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 28 | Train Loss: 0.0104 | Val ROC-AUC: 0.8651 | Val Profit: -80
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9723
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 29 | Train Loss: 0.0112 | Val ROC-AUC: 0.9723 | Val Profit: -160
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9409
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 30 | Train Loss: 0.0092 | Val ROC-AUC: 0.9409 | Val Profit: -155

Лучшая эпоха для model_9_Focal_loss: 13
Лучший ROC-AUC: 0.9773306505700872
val
ROC-AUC: 0.9773
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8897
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1011 | Val ROC-AUC: 0.8897 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0535 | Val ROC-AUC: 0.9344 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9556
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0376 | Val ROC-AUC: 0.9556 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9669
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0324 | Val ROC-AUC: 0.9669 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9554
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0293 | Val ROC-AUC: 0.9554 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9571
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0259 | Val ROC-AUC: 0.9571 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9522
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0260 | Val ROC-AUC: 0.9522 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9687
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0251 | Val ROC-AUC: 0.9687 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9545
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0239 | Val ROC-AUC: 0.9545 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.967
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0214 | Val ROC-AUC: 0.9670 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0230 | Val ROC-AUC: 0.9498 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9634
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0290 | Val ROC-AUC: 0.9634 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9687
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0220 | Val ROC-AUC: 0.9687 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9694
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0199 | Val ROC-AUC: 0.9694 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9632
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0176 | Val ROC-AUC: 0.9632 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9651
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0173 | Val ROC-AUC: 0.9651 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9379
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0173 | Val ROC-AUC: 0.9379 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9277
Precision: 0.3333
Recall: 0.381
F0.5-score: 0.3419
Profit: -425

Эпоха 18 | Train Loss: 0.0169 | Val ROC-AUC: 0.9277 | Val Profit: -425
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9769
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 19 | Train Loss: 0.0195 | Val ROC-AUC: 0.9769 | Val Profit: -65
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9681
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 20 | Train Loss: 0.0175 | Val ROC-AUC: 0.9681 | Val Profit: -220
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9586
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 21 | Train Loss: 0.0187 | Val ROC-AUC: 0.9586 | Val Profit: -175
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9732
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 22 | Train Loss: 0.0175 | Val ROC-AUC: 0.9732 | Val Profit: -155
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0135 | Val ROC-AUC: 0.9675 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9724
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 24 | Train Loss: 0.0122 | Val ROC-AUC: 0.9724 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.934
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 25 | Train Loss: 0.0115 | Val ROC-AUC: 0.9340 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9628
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 26 | Train Loss: 0.0106 | Val ROC-AUC: 0.9628 | Val Profit: -145
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9588
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 27 | Train Loss: 0.0139 | Val ROC-AUC: 0.9588 | Val Profit: -205
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9635
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 28 | Train Loss: 0.0208 | Val ROC-AUC: 0.9635 | Val Profit: -525
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9729
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 29 | Train Loss: 0.0192 | Val ROC-AUC: 0.9729 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9763
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 30 | Train Loss: 0.0131 | Val ROC-AUC: 0.9763 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 19
Лучший ROC-AUC: 0.9769282360831657
val
ROC-AUC: 0.9769
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8698
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1055 | Val ROC-AUC: 0.8698 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0537 | Val ROC-AUC: 0.9268 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9391
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0370 | Val ROC-AUC: 0.9391 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9494
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0287 | Val ROC-AUC: 0.9494 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9497
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0246 | Val ROC-AUC: 0.9497 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0214 | Val ROC-AUC: 0.9513 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0188 | Val ROC-AUC: 0.9671 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9507
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0209 | Val ROC-AUC: 0.9507 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.954
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0198 | Val ROC-AUC: 0.9540 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.8918
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0189 | Val ROC-AUC: 0.8918 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9632
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0181 | Val ROC-AUC: 0.9632 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9219
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0151 | Val ROC-AUC: 0.9219 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0146 | Val ROC-AUC: 0.9498 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9344
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0154 | Val ROC-AUC: 0.9344 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9565
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 15 | Train Loss: 0.0139 | Val ROC-AUC: 0.9565 | Val Profit: -130
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9516
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 16 | Train Loss: 0.0118 | Val ROC-AUC: 0.9516 | Val Profit: -95
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9681
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 17 | Train Loss: 0.0106 | Val ROC-AUC: 0.9681 | Val Profit: -145
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9675
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.0102 | Val ROC-AUC: 0.9675 | Val Profit: -100
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9639
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 19 | Train Loss: 0.0092 | Val ROC-AUC: 0.9639 | Val Profit: -75
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9666
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 20 | Train Loss: 0.0085 | Val ROC-AUC: 0.9666 | Val Profit: -100
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9718
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 21 | Train Loss: 0.0081 | Val ROC-AUC: 0.9718 | Val Profit: -100
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9686
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 22 | Train Loss: 0.0077 | Val ROC-AUC: 0.9686 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.967
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 23 | Train Loss: 0.0073 | Val ROC-AUC: 0.9670 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9657
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 24 | Train Loss: 0.0069 | Val ROC-AUC: 0.9657 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.965
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 25 | Train Loss: 0.0067 | Val ROC-AUC: 0.9650 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9657
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 26 | Train Loss: 0.0064 | Val ROC-AUC: 0.9657 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9649
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 27 | Train Loss: 0.0062 | Val ROC-AUC: 0.9649 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9635
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 28 | Train Loss: 0.0060 | Val ROC-AUC: 0.9635 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9634
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 29 | Train Loss: 0.0058 | Val ROC-AUC: 0.9634 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9658
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 30 | Train Loss: 0.0057 | Val ROC-AUC: 0.9658 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 21
Лучший ROC-AUC: 0.971830985915493
val
ROC-AUC: 0.9718
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8873
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1052 | Val ROC-AUC: 0.8873 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9521
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0518 | Val ROC-AUC: 0.9521 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9614
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0344 | Val ROC-AUC: 0.9614 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0278 | Val ROC-AUC: 0.9516 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9419
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0240 | Val ROC-AUC: 0.9419 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9493
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0222 | Val ROC-AUC: 0.9493 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9616
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0196 | Val ROC-AUC: 0.9616 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.95
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0180 | Val ROC-AUC: 0.9500 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.8909
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0172 | Val ROC-AUC: 0.8909 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.961
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0160 | Val ROC-AUC: 0.9610 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0142 | Val ROC-AUC: 0.9567 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8732
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0129 | Val ROC-AUC: 0.8732 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9002
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0124 | Val ROC-AUC: 0.9002 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9571
Precision: 0.5238
Recall: 0.5238
F0.5-score: 0.5238
Profit: -245

Эпоха 14 | Train Loss: 0.0136 | Val ROC-AUC: 0.9571 | Val Profit: -245
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9421
Precision: 0.4211
Recall: 0.381
F0.5-score: 0.4124
Profit: -300

Эпоха 15 | Train Loss: 0.0163 | Val ROC-AUC: 0.9421 | Val Profit: -300
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9384
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 16 | Train Loss: 0.0150 | Val ROC-AUC: 0.9384 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9242
Precision: 0.36
Recall: 0.4286
F0.5-score: 0.3719
Profit: -415

Эпоха 17 | Train Loss: 0.0141 | Val ROC-AUC: 0.9242 | Val Profit: -415
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9547
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 18 | Train Loss: 0.0201 | Val ROC-AUC: 0.9547 | Val Profit: -375
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9651
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 19 | Train Loss: 0.0146 | Val ROC-AUC: 0.9651 | Val Profit: -185
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9357
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 20 | Train Loss: 0.0110 | Val ROC-AUC: 0.9357 | Val Profit: -95
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9278
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 21 | Train Loss: 0.0101 | Val ROC-AUC: 0.9278 | Val Profit: -185
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9552
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 22 | Train Loss: 0.0103 | Val ROC-AUC: 0.9552 | Val Profit: -360
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9693
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 23 | Train Loss: 0.0120 | Val ROC-AUC: 0.9693 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9616
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 24 | Train Loss: 0.0099 | Val ROC-AUC: 0.9616 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9657
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 25 | Train Loss: 0.0089 | Val ROC-AUC: 0.9657 | Val Profit: -65
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9416
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0070 | Val ROC-AUC: 0.9416 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9471
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 27 | Train Loss: 0.0061 | Val ROC-AUC: 0.9471 | Val Profit: -230
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9188
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 28 | Train Loss: 0.0056 | Val ROC-AUC: 0.9188 | Val Profit: -130
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9132
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 29 | Train Loss: 0.0048 | Val ROC-AUC: 0.9132 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.921
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 30 | Train Loss: 0.0044 | Val ROC-AUC: 0.9210 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9692823608316566
val
ROC-AUC: 0.9693
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8943
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.1040 | Val ROC-AUC: 0.8943 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9293
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0551 | Val ROC-AUC: 0.9293 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9429
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0378 | Val ROC-AUC: 0.9429 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9164
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0296 | Val ROC-AUC: 0.9164 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9408
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0252 | Val ROC-AUC: 0.9408 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.923
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 6 | Train Loss: 0.0254 | Val ROC-AUC: 0.9230 | Val Profit: -145
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9587
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 7 | Train Loss: 0.0238 | Val ROC-AUC: 0.9587 | Val Profit: -175
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9645
Precision: 0.4
Recall: 0.1905
F0.5-score: 0.3279
Profit: -215

Эпоха 8 | Train Loss: 0.0200 | Val ROC-AUC: 0.9645 | Val Profit: -215
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9506
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 9 | Train Loss: 0.0187 | Val ROC-AUC: 0.9506 | Val Profit: -140
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9677
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 10 | Train Loss: 0.0150 | Val ROC-AUC: 0.9677 | Val Profit: -120
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9639
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 11 | Train Loss: 0.0119 | Val ROC-AUC: 0.9639 | Val Profit: -120
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9567
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 12 | Train Loss: 0.0123 | Val ROC-AUC: 0.9567 | Val Profit: -395
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9447
Precision: 0.3429
Recall: 0.5714
F0.5-score: 0.3727
Profit: -560

Эпоха 13 | Train Loss: 0.0180 | Val ROC-AUC: 0.9447 | Val Profit: -560
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9642
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 14 | Train Loss: 0.0152 | Val ROC-AUC: 0.9642 | Val Profit: -170
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9595
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0116 | Val ROC-AUC: 0.9595 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9682
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 16 | Train Loss: 0.0102 | Val ROC-AUC: 0.9682 | Val Profit: -90
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9501
Precision: 0.3939
Recall: 0.619
F0.5-score: 0.4248
Profit: -475

Эпоха 17 | Train Loss: 0.0149 | Val ROC-AUC: 0.9501 | Val Profit: -475

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.748
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 18 | Train Loss: 0.0144 | Val ROC-AUC: 0.7480 | Val Profit: -65
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.915
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 19 | Train Loss: 0.0126 | Val ROC-AUC: 0.9150 | Val Profit: -90
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9481
Precision: 0.4167
Recall: 0.4762
F0.5-score: 0.4274
Profit: -355

Эпоха 20 | Train Loss: 0.0133 | Val ROC-AUC: 0.9481 | Val Profit: -355
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9214
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 21 | Train Loss: 0.0105 | Val ROC-AUC: 0.9214 | Val Profit: -180
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.7093
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 22 | Train Loss: 0.0087 | Val ROC-AUC: 0.7093 | Val Profit: -100
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9661
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 23 | Train Loss: 0.0072 | Val ROC-AUC: 0.9661 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.7598
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 24 | Train Loss: 0.0061 | Val ROC-AUC: 0.7598 | Val Profit: -85
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.7533
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0047 | Val ROC-AUC: 0.7533 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.7269
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 26 | Train Loss: 0.0040 | Val ROC-AUC: 0.7269 | Val Profit: -85
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.7105
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 27 | Train Loss: 0.0037 | Val ROC-AUC: 0.7105 | Val Profit: -75
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8757
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 28 | Train Loss: 0.0035 | Val ROC-AUC: 0.8757 | Val Profit: -90
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8054
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 29 | Train Loss: 0.0034 | Val ROC-AUC: 0.8054 | Val Profit: -75
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.7518
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0032 | Val ROC-AUC: 0.7518 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9682092555331991
val
ROC-AUC: 0.9682
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9327
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0103 | Val ROC-AUC: 0.9327 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.949
Precision: 0.4
Recall: 0.4762
F0.5-score: 0.4132
Profit: -380

Эпоха 2 | Train Loss: 0.0051 | Val ROC-AUC: 0.9490 | Val Profit: -380

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9454
Precision: 0.375
Recall: 0.7143
F0.5-score: 0.4144
Profit: -580

Эпоха 3 | Train Loss: 0.0038 | Val ROC-AUC: 0.9454 | Val Profit: -580
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9651
Precision: 0.4828
Recall: 0.6667
F0.5-score: 0.5109
Profit: -340

Эпоха 4 | Train Loss: 0.0031 | Val ROC-AUC: 0.9651 | Val Profit: -340
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9598
Precision: 0.3878
Recall: 0.9048
F0.5-score: 0.4378
Profit: -665

Эпоха 5 | Train Loss: 0.0028 | Val ROC-AUC: 0.9598 | Val Profit: -665
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9586
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 6 | Train Loss: 0.0030 | Val ROC-AUC: 0.9586 | Val Profit: -235
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9777
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 7 | Train Loss: 0.0033 | Val ROC-AUC: 0.9777 | Val Profit: -255
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9671
Precision: 0.4545
Recall: 0.4762
F0.5-score: 0.4587
Profit: -305

Эпоха 8 | Train Loss: 0.0027 | Val ROC-AUC: 0.9671 | Val Profit: -305
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9641
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 9 | Train Loss: 0.0023 | Val ROC-AUC: 0.9641 | Val Profit: -235
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9788
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 10 | Train Loss: 0.0023 | Val ROC-AUC: 0.9788 | Val Profit: -135
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9756
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 11 | Train Loss: 0.0020 | Val ROC-AUC: 0.9756 | Val Profit: -100
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9789
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 12 | Train Loss: 0.0019 | Val ROC-AUC: 0.9789 | Val Profit: -100
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9799
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 13 | Train Loss: 0.0023 | Val ROC-AUC: 0.9799 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9751
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 14 | Train Loss: 0.0021 | Val ROC-AUC: 0.9751 | Val Profit: -120
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9734
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 15 | Train Loss: 0.0015 | Val ROC-AUC: 0.9734 | Val Profit: -135
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9772
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 16 | Train Loss: 0.0014 | Val ROC-AUC: 0.9772 | Val Profit: -145
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.973
Precision: 0.4722
Recall: 0.8095
F0.5-score: 0.5152
Profit: -410

Эпоха 17 | Train Loss: 0.0018 | Val ROC-AUC: 0.9730 | Val Profit: -410
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9721
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 18 | Train Loss: 0.0021 | Val ROC-AUC: 0.9721 | Val Profit: -200
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9784
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 19 | Train Loss: 0.0018 | Val ROC-AUC: 0.9784 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9842
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 20 | Train Loss: 0.0010 | Val ROC-AUC: 0.9842 | Val Profit: -145
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9799
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 21 | Train Loss: 0.0010 | Val ROC-AUC: 0.9799 | Val Profit: -145
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9414
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 22 | Train Loss: 0.0011 | Val ROC-AUC: 0.9414 | Val Profit: -170
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9814
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 23 | Train Loss: 0.0018 | Val ROC-AUC: 0.9814 | Val Profit: -115
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.982
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 24 | Train Loss: 0.0011 | Val ROC-AUC: 0.9820 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9807
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 25 | Train Loss: 0.0007 | Val ROC-AUC: 0.9807 | Val Profit: -135
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9764
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 26 | Train Loss: 0.0006 | Val ROC-AUC: 0.9764 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9808
Precision: 0.7647
Recall: 0.619
F0.5-score: 0.7303
Profit: -75

Эпоха 27 | Train Loss: 0.0006 | Val ROC-AUC: 0.9808 | Val Profit: -75
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9795
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 28 | Train Loss: 0.0011 | Val ROC-AUC: 0.9795 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9709
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 29 | Train Loss: 0.0013 | Val ROC-AUC: 0.9709 | Val Profit: -115
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9419
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 30 | Train Loss: 0.0014 | Val ROC-AUC: 0.9419 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 20
Лучший ROC-AUC: 0.9841716968477532
val
ROC-AUC: 0.9842
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9202
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 1 | Train Loss: 0.0103 | Val ROC-AUC: 0.9202 | Val Profit: -160
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9522
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 2 | Train Loss: 0.0048 | Val ROC-AUC: 0.9522 | Val Profit: -225
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9535
Precision: 0.375
Recall: 0.4286
F0.5-score: 0.3846
Profit: -390

Эпоха 3 | Train Loss: 0.0037 | Val ROC-AUC: 0.9535 | Val Profit: -390
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9588
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 4 | Train Loss: 0.0033 | Val ROC-AUC: 0.9588 | Val Profit: -375
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9569
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 5 | Train Loss: 0.0037 | Val ROC-AUC: 0.9569 | Val Profit: -295
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9749
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 6 | Train Loss: 0.0033 | Val ROC-AUC: 0.9749 | Val Profit: -140
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9729
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 7 | Train Loss: 0.0026 | Val ROC-AUC: 0.9729 | Val Profit: -165
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9674
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 8 | Train Loss: 0.0025 | Val ROC-AUC: 0.9674 | Val Profit: -165
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9775
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 9 | Train Loss: 0.0027 | Val ROC-AUC: 0.9775 | Val Profit: -110
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9733
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 10 | Train Loss: 0.0025 | Val ROC-AUC: 0.9733 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9366
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 11 | Train Loss: 0.0023 | Val ROC-AUC: 0.9366 | Val Profit: -115
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9777
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 12 | Train Loss: 0.0023 | Val ROC-AUC: 0.9777 | Val Profit: -150
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9229
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 13 | Train Loss: 0.0022 | Val ROC-AUC: 0.9229 | Val Profit: -85
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9647
Precision: 0.4643
Recall: 0.619
F0.5-score: 0.4887
Profit: -350

Эпоха 14 | Train Loss: 0.0026 | Val ROC-AUC: 0.9647 | Val Profit: -350
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9709
Precision: 0.4571
Recall: 0.7619
F0.5-score: 0.4969
Profit: -420

Эпоха 15 | Train Loss: 0.0028 | Val ROC-AUC: 0.9709 | Val Profit: -420
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9856
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 16 | Train Loss: 0.0026 | Val ROC-AUC: 0.9856 | Val Profit: -95
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9755
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 17 | Train Loss: 0.0022 | Val ROC-AUC: 0.9755 | Val Profit: -80
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9805
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0022 | Val ROC-AUC: 0.9805 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0026 | Val ROC-AUC: 0.9761 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9763
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0022 | Val ROC-AUC: 0.9763 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9705
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 21 | Train Loss: 0.0022 | Val ROC-AUC: 0.9705 | Val Profit: -265
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9771
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 22 | Train Loss: 0.0028 | Val ROC-AUC: 0.9771 | Val Profit: -110

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9795
Precision: 0.8571
Recall: 0.2857
F0.5-score: 0.6122
Profit: -70

Эпоха 23 | Train Loss: 0.0023 | Val ROC-AUC: 0.9795 | Val Profit: -70
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9569
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 24 | Train Loss: 0.0020 | Val ROC-AUC: 0.9569 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9769
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0022 | Val ROC-AUC: 0.9769 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9705
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 26 | Train Loss: 0.0022 | Val ROC-AUC: 0.9705 | Val Profit: -65
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9763
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 27 | Train Loss: 0.0025 | Val ROC-AUC: 0.9763 | Val Profit: -90
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.983
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0023 | Val ROC-AUC: 0.9830 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8955
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0018 | Val ROC-AUC: 0.8955 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9819
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 30 | Train Loss: 0.0019 | Val ROC-AUC: 0.9819 | Val Profit: -145

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.985647216633132
val
ROC-AUC: 0.9856
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.905
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0105 | Val ROC-AUC: 0.9050 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.923
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0055 | Val ROC-AUC: 0.9230 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9526
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0045 | Val ROC-AUC: 0.9526 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0043 | Val ROC-AUC: 0.9594 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9646
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0040 | Val ROC-AUC: 0.9646 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9728
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 6 | Train Loss: 0.0042 | Val ROC-AUC: 0.9728 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9678
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0037 | Val ROC-AUC: 0.9678 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9513
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0036 | Val ROC-AUC: 0.9513 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9729
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0037 | Val ROC-AUC: 0.9729 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 10 | Train Loss: 0.0035 | Val ROC-AUC: 0.9772 | Val Profit: -120
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9721
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0033 | Val ROC-AUC: 0.9721 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9761
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0035 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0033 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9789
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0032 | Val ROC-AUC: 0.9789 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9772
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 15 | Train Loss: 0.0032 | Val ROC-AUC: 0.9772 | Val Profit: -195
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9748
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0032 | Val ROC-AUC: 0.9748 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9725
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 17 | Train Loss: 0.0031 | Val ROC-AUC: 0.9725 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9765
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 18 | Train Loss: 0.0032 | Val ROC-AUC: 0.9765 | Val Profit: -285
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9824
Precision: 0.2442
Recall: 1.0
F0.5-score: 0.2877
Profit: -1520

Эпоха 19 | Train Loss: 0.0030 | Val ROC-AUC: 0.9824 | Val Profit: -1520
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9768
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0032 | Val ROC-AUC: 0.9768 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9828
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 21 | Train Loss: 0.0031 | Val ROC-AUC: 0.9828 | Val Profit: -75

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9819
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0029 | Val ROC-AUC: 0.9819 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.982
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 23 | Train Loss: 0.0029 | Val ROC-AUC: 0.9820 | Val Profit: -60
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9801
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0029 | Val ROC-AUC: 0.9801 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9835
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 25 | Train Loss: 0.0029 | Val ROC-AUC: 0.9835 | Val Profit: -260
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9856
Precision: 1.0
Recall: 0.2381
F0.5-score: 0.6098
Profit: -55

Эпоха 26 | Train Loss: 0.0028 | Val ROC-AUC: 0.9856 | Val Profit: -55
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9819
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 27 | Train Loss: 0.0029 | Val ROC-AUC: 0.9819 | Val Profit: -90
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9838
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 28 | Train Loss: 0.0027 | Val ROC-AUC: 0.9838 | Val Profit: -45
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9822
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0027 | Val ROC-AUC: 0.9822 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9836
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.0027 | Val ROC-AUC: 0.9836 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9856472166331322
val
ROC-AUC: 0.9856
Precision: 1.0
Recall: 0.2381
F0.5-score: 0.6098
Profit: -55

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.859
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0118 | Val ROC-AUC: 0.8590 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9442
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0065 | Val ROC-AUC: 0.9442 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9484
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0043 | Val ROC-AUC: 0.9484 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9549
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0035 | Val ROC-AUC: 0.9549 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9709
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 5 | Train Loss: 0.0027 | Val ROC-AUC: 0.9709 | Val Profit: -155
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9631
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 6 | Train Loss: 0.0020 | Val ROC-AUC: 0.9631 | Val Profit: -230

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9662
Precision: 0.4167
Recall: 0.7143
F0.5-score: 0.4545
Profit: -480

Эпоха 7 | Train Loss: 0.0018 | Val ROC-AUC: 0.9662 | Val Profit: -480
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9567
Precision: 0.4348
Recall: 0.4762
F0.5-score: 0.4425
Profit: -330

Эпоха 8 | Train Loss: 0.0023 | Val ROC-AUC: 0.9567 | Val Profit: -330
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9537
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 9 | Train Loss: 0.0020 | Val ROC-AUC: 0.9537 | Val Profit: -180
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9115
Precision: 0.4762
Recall: 0.4762
F0.5-score: 0.4762
Profit: -280

Эпоха 10 | Train Loss: 0.0014 | Val ROC-AUC: 0.9115 | Val Profit: -280
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9705
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 11 | Train Loss: 0.0014 | Val ROC-AUC: 0.9705 | Val Profit: -275
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9541
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 12 | Train Loss: 0.0014 | Val ROC-AUC: 0.9541 | Val Profit: -145
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.934
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 13 | Train Loss: 0.0011 | Val ROC-AUC: 0.9340 | Val Profit: -180
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9222
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 14 | Train Loss: 0.0011 | Val ROC-AUC: 0.9222 | Val Profit: -135
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9307
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 15 | Train Loss: 0.0006 | Val ROC-AUC: 0.9307 | Val Profit: -130
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9235
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 16 | Train Loss: 0.0004 | Val ROC-AUC: 0.9235 | Val Profit: -110
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9311
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 17 | Train Loss: 0.0003 | Val ROC-AUC: 0.9311 | Val Profit: -160
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9296
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 18 | Train Loss: 0.0003 | Val ROC-AUC: 0.9296 | Val Profit: -185
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9296
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 19 | Train Loss: 0.0003 | Val ROC-AUC: 0.9296 | Val Profit: -185
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9294
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 20 | Train Loss: 0.0002 | Val ROC-AUC: 0.9294 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9294
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 21 | Train Loss: 0.0002 | Val ROC-AUC: 0.9294 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9266
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 22 | Train Loss: 0.0002 | Val ROC-AUC: 0.9266 | Val Profit: -175
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9268
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 23 | Train Loss: 0.0002 | Val ROC-AUC: 0.9268 | Val Profit: -185
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.927
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 24 | Train Loss: 0.0002 | Val ROC-AUC: 0.9270 | Val Profit: -185
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9273
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 25 | Train Loss: 0.0002 | Val ROC-AUC: 0.9273 | Val Profit: -185
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9274
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 26 | Train Loss: 0.0002 | Val ROC-AUC: 0.9274 | Val Profit: -185
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.927
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 27 | Train Loss: 0.0002 | Val ROC-AUC: 0.9270 | Val Profit: -185
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.927
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 28 | Train Loss: 0.0002 | Val ROC-AUC: 0.9270 | Val Profit: -185
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9382
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 29 | Train Loss: 0.0002 | Val ROC-AUC: 0.9382 | Val Profit: -135
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9324
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 30 | Train Loss: 0.0002 | Val ROC-AUC: 0.9324 | Val Profit: -135

Лучшая эпоха для model_9_Focal_loss: 5
Лучший ROC-AUC: 0.9708920187793428
val
ROC-AUC: 0.9709
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9416
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0117 | Val ROC-AUC: 0.9416 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9485
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0061 | Val ROC-AUC: 0.9485 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9459
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0046 | Val ROC-AUC: 0.9459 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9379
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0037 | Val ROC-AUC: 0.9379 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9643
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 5 | Train Loss: 0.0037 | Val ROC-AUC: 0.9643 | Val Profit: -225
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9568
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 6 | Train Loss: 0.0035 | Val ROC-AUC: 0.9568 | Val Profit: -135
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9556
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 7 | Train Loss: 0.0030 | Val ROC-AUC: 0.9556 | Val Profit: -115
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9658
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 8 | Train Loss: 0.0029 | Val ROC-AUC: 0.9658 | Val Profit: -235
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9693
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 9 | Train Loss: 0.0026 | Val ROC-AUC: 0.9693 | Val Profit: -190
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9702
Precision: 0.6087
Recall: 0.6667
F0.5-score: 0.6195
Profit: -190

Эпоха 10 | Train Loss: 0.0027 | Val ROC-AUC: 0.9702 | Val Profit: -190
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9691
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 11 | Train Loss: 0.0023 | Val ROC-AUC: 0.9691 | Val Profit: -325
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 12 | Train Loss: 0.0023 | Val ROC-AUC: 0.9655 | Val Profit: -155
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9471
Precision: 0.4
Recall: 0.5714
F0.5-score: 0.4255
Profit: -435

Эпоха 13 | Train Loss: 0.0022 | Val ROC-AUC: 0.9471 | Val Profit: -435
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9705
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 14 | Train Loss: 0.0020 | Val ROC-AUC: 0.9705 | Val Profit: -135
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9686
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 15 | Train Loss: 0.0017 | Val ROC-AUC: 0.9686 | Val Profit: -110
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9744
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 16 | Train Loss: 0.0019 | Val ROC-AUC: 0.9744 | Val Profit: -140
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9701
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 17 | Train Loss: 0.0015 | Val ROC-AUC: 0.9701 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0012 | Val ROC-AUC: 0.9608 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9321
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 19 | Train Loss: 0.0010 | Val ROC-AUC: 0.9321 | Val Profit: -130
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.8365
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 20 | Train Loss: 0.0008 | Val ROC-AUC: 0.8365 | Val Profit: -130
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9015
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 21 | Train Loss: 0.0010 | Val ROC-AUC: 0.9015 | Val Profit: -140
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9353
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 22 | Train Loss: 0.0017 | Val ROC-AUC: 0.9353 | Val Profit: -215
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9682
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 23 | Train Loss: 0.0017 | Val ROC-AUC: 0.9682 | Val Profit: -195
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9697
Precision: 0.3333
Recall: 0.0952
F0.5-score: 0.2222
Profit: -185

Эпоха 24 | Train Loss: 0.0016 | Val ROC-AUC: 0.9697 | Val Profit: -185
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.8059
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 25 | Train Loss: 0.0011 | Val ROC-AUC: 0.8059 | Val Profit: -155
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8451
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 26 | Train Loss: 0.0008 | Val ROC-AUC: 0.8451 | Val Profit: -85
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9607
Precision: 0.4783
Recall: 0.5238
F0.5-score: 0.4867
Profit: -295

Эпоха 27 | Train Loss: 0.0011 | Val ROC-AUC: 0.9607 | Val Profit: -295
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.974
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 28 | Train Loss: 0.0022 | Val ROC-AUC: 0.9740 | Val Profit: -215
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9753
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 29 | Train Loss: 0.0015 | Val ROC-AUC: 0.9753 | Val Profit: -100
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9712
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 30 | Train Loss: 0.0014 | Val ROC-AUC: 0.9712 | Val Profit: -120

Лучшая эпоха для model_9_Focal_loss: 29
Лучший ROC-AUC: 0.9753185781354796
val
ROC-AUC: 0.9753
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9188
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0118 | Val ROC-AUC: 0.9188 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9219
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0064 | Val ROC-AUC: 0.9219 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9268
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0054 | Val ROC-AUC: 0.9268 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9541
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Эпоха 4 | Train Loss: 0.0047 | Val ROC-AUC: 0.9541 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9152
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0051 | Val ROC-AUC: 0.9152 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9364
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0047 | Val ROC-AUC: 0.9364 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9258
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0043 | Val ROC-AUC: 0.9258 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0042 | Val ROC-AUC: 0.9705 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0039 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9588
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0040 | Val ROC-AUC: 0.9588 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9581
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0036 | Val ROC-AUC: 0.9581 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9476
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0038 | Val ROC-AUC: 0.9476 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9505
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0035 | Val ROC-AUC: 0.9505 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0037 | Val ROC-AUC: 0.9544 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9577
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0035 | Val ROC-AUC: 0.9577 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9693
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0034 | Val ROC-AUC: 0.9693 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9708
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0033 | Val ROC-AUC: 0.9708 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9671
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0032 | Val ROC-AUC: 0.9671 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9722
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0031 | Val ROC-AUC: 0.9722 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9674
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0032 | Val ROC-AUC: 0.9674 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9717
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0032 | Val ROC-AUC: 0.9717 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9768
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0030 | Val ROC-AUC: 0.9768 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9709
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0029 | Val ROC-AUC: 0.9709 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9559
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0034 | Val ROC-AUC: 0.9559 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9749
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0031 | Val ROC-AUC: 0.9749 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.976
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0029 | Val ROC-AUC: 0.9760 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9724
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0029 | Val ROC-AUC: 0.9724 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9801
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0030 | Val ROC-AUC: 0.9801 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9738
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0028 | Val ROC-AUC: 0.9738 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9769
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0029 | Val ROC-AUC: 0.9769 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9801475519785379
val
ROC-AUC: 0.9801
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9007
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0124 | Val ROC-AUC: 0.9007 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9327
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0062 | Val ROC-AUC: 0.9327 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9572
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0044 | Val ROC-AUC: 0.9572 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9441
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0035 | Val ROC-AUC: 0.9441 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 5 | Train Loss: 0.0032 | Val ROC-AUC: 0.9411 | Val Profit: -130
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9594
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 6 | Train Loss: 0.0027 | Val ROC-AUC: 0.9594 | Val Profit: -175
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9598
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 7 | Train Loss: 0.0021 | Val ROC-AUC: 0.9598 | Val Profit: -205

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9646
Precision: 0.5263
Recall: 0.4762
F0.5-score: 0.5155
Profit: -230

Эпоха 8 | Train Loss: 0.0018 | Val ROC-AUC: 0.9646 | Val Profit: -230
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9679
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 9 | Train Loss: 0.0018 | Val ROC-AUC: 0.9679 | Val Profit: -120
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9581
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 10 | Train Loss: 0.0013 | Val ROC-AUC: 0.9581 | Val Profit: -100
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9492
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 11 | Train Loss: 0.0010 | Val ROC-AUC: 0.9492 | Val Profit: -80
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9673
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 12 | Train Loss: 0.0008 | Val ROC-AUC: 0.9673 | Val Profit: -100
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9579
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 13 | Train Loss: 0.0009 | Val ROC-AUC: 0.9579 | Val Profit: -95
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9438
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 14 | Train Loss: 0.0008 | Val ROC-AUC: 0.9438 | Val Profit: -125
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.8816
Precision: 0.4286
Recall: 0.5714
F0.5-score: 0.4511
Profit: -385

Эпоха 15 | Train Loss: 0.0017 | Val ROC-AUC: 0.8816 | Val Profit: -385
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9635
Precision: 0.4815
Recall: 0.619
F0.5-score: 0.5039
Profit: -325

Эпоха 16 | Train Loss: 0.0017 | Val ROC-AUC: 0.9635 | Val Profit: -325
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9608
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 17 | Train Loss: 0.0011 | Val ROC-AUC: 0.9608 | Val Profit: -85
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9599
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 18 | Train Loss: 0.0011 | Val ROC-AUC: 0.9599 | Val Profit: -250
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9465
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 19 | Train Loss: 0.0005 | Val ROC-AUC: 0.9465 | Val Profit: -265
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9539
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 20 | Train Loss: 0.0004 | Val ROC-AUC: 0.9539 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.95
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 21 | Train Loss: 0.0002 | Val ROC-AUC: 0.9500 | Val Profit: -175
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9517
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 22 | Train Loss: 0.0002 | Val ROC-AUC: 0.9517 | Val Profit: -175
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9518
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 23 | Train Loss: 0.0001 | Val ROC-AUC: 0.9518 | Val Profit: -150
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9531
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 24 | Train Loss: 0.0001 | Val ROC-AUC: 0.9531 | Val Profit: -150
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9536
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 25 | Train Loss: 0.0001 | Val ROC-AUC: 0.9536 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9544
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 26 | Train Loss: 0.0001 | Val ROC-AUC: 0.9544 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9541
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 27 | Train Loss: 0.0001 | Val ROC-AUC: 0.9541 | Val Profit: -160
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9541
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 28 | Train Loss: 0.0001 | Val ROC-AUC: 0.9541 | Val Profit: -160
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9539
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 29 | Train Loss: 0.0001 | Val ROC-AUC: 0.9539 | Val Profit: -160
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9536
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 30 | Train Loss: 0.0001 | Val ROC-AUC: 0.9536 | Val Profit: -160

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9679409792085848
val
ROC-AUC: 0.9679
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8675
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0126 | Val ROC-AUC: 0.8675 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9078
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0065 | Val ROC-AUC: 0.9078 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9431
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0047 | Val ROC-AUC: 0.9431 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9313
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0038 | Val ROC-AUC: 0.9313 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9411
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0033 | Val ROC-AUC: 0.9411 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9551
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 6 | Train Loss: 0.0030 | Val ROC-AUC: 0.9551 | Val Profit: -165
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9571
Precision: 0.4688
Recall: 0.7143
F0.5-score: 0.5034
Profit: -380

Эпоха 7 | Train Loss: 0.0026 | Val ROC-AUC: 0.9571 | Val Profit: -380
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9379
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 8 | Train Loss: 0.0030 | Val ROC-AUC: 0.9379 | Val Profit: -160
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9714
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 9 | Train Loss: 0.0024 | Val ROC-AUC: 0.9714 | Val Profit: -90
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9441
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 10 | Train Loss: 0.0016 | Val ROC-AUC: 0.9441 | Val Profit: -110
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9683
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 11 | Train Loss: 0.0018 | Val ROC-AUC: 0.9683 | Val Profit: -210
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9765
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 12 | Train Loss: 0.0019 | Val ROC-AUC: 0.9765 | Val Profit: -285
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9332
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0020 | Val ROC-AUC: 0.9332 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9596
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 14 | Train Loss: 0.0024 | Val ROC-AUC: 0.9596 | Val Profit: -95
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9717
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 15 | Train Loss: 0.0016 | Val ROC-AUC: 0.9717 | Val Profit: -265
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9671
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 16 | Train Loss: 0.0013 | Val ROC-AUC: 0.9671 | Val Profit: -135

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9315
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0007 | Val ROC-AUC: 0.9315 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9642
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0005 | Val ROC-AUC: 0.9642 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.8606
Precision: 0.4
Recall: 0.4762
F0.5-score: 0.4132
Profit: -380

Эпоха 19 | Train Loss: 0.0004 | Val ROC-AUC: 0.8606 | Val Profit: -380
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9457
Precision: 0.4444
Recall: 0.381
F0.5-score: 0.4301
Profit: -275

Эпоха 20 | Train Loss: 0.0013 | Val ROC-AUC: 0.9457 | Val Profit: -275
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9632
Precision: 0.4054
Recall: 0.7143
F0.5-score: 0.4438
Profit: -505

Эпоха 21 | Train Loss: 0.0018 | Val ROC-AUC: 0.9632 | Val Profit: -505

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9706
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 22 | Train Loss: 0.0020 | Val ROC-AUC: 0.9706 | Val Profit: -210
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9679
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 23 | Train Loss: 0.0015 | Val ROC-AUC: 0.9679 | Val Profit: -160
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9755
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 24 | Train Loss: 0.0009 | Val ROC-AUC: 0.9755 | Val Profit: -85
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9198
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0005 | Val ROC-AUC: 0.9198 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9677
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 26 | Train Loss: 0.0003 | Val ROC-AUC: 0.9677 | Val Profit: -85

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9332
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 27 | Train Loss: 0.0002 | Val ROC-AUC: 0.9332 | Val Profit: -65
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9239
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 28 | Train Loss: 0.0002 | Val ROC-AUC: 0.9239 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8997
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 29 | Train Loss: 0.0002 | Val ROC-AUC: 0.8997 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8901
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 30 | Train Loss: 0.0001 | Val ROC-AUC: 0.8901 | Val Profit: -85

Лучшая эпоха для model_9_Focal_loss: 12
Лучший ROC-AUC: 0.9765258215962441
val
ROC-AUC: 0.9765
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.927
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0123 | Val ROC-AUC: 0.9270 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9565
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0066 | Val ROC-AUC: 0.9565 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9433
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0052 | Val ROC-AUC: 0.9433 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0047 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9595
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0047 | Val ROC-AUC: 0.9595 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9661
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0041 | Val ROC-AUC: 0.9661 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9312
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0044 | Val ROC-AUC: 0.9312 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9549
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0042 | Val ROC-AUC: 0.9549 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9455
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0042 | Val ROC-AUC: 0.9455 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9433
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0038 | Val ROC-AUC: 0.9433 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9681
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0038 | Val ROC-AUC: 0.9681 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9741
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0035 | Val ROC-AUC: 0.9741 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9655
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0037 | Val ROC-AUC: 0.9655 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.943
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0037 | Val ROC-AUC: 0.9430 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9388
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0034 | Val ROC-AUC: 0.9388 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0035 | Val ROC-AUC: 0.9706 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9649
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0033 | Val ROC-AUC: 0.9649 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9324
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0032 | Val ROC-AUC: 0.9324 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9498
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0035 | Val ROC-AUC: 0.9498 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9514
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0035 | Val ROC-AUC: 0.9514 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9459
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0031 | Val ROC-AUC: 0.9459 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.931
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0033 | Val ROC-AUC: 0.9310 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0031 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9646
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0030 | Val ROC-AUC: 0.9646 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9518
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0029 | Val ROC-AUC: 0.9518 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9551
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0029 | Val ROC-AUC: 0.9551 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9624
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0033 | Val ROC-AUC: 0.9624 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9708
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0029 | Val ROC-AUC: 0.9708 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0028 | Val ROC-AUC: 0.9608 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9516
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0029 | Val ROC-AUC: 0.9516 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9743796109993293
val
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9088
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0208 | Val ROC-AUC: 0.9088 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9635
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0104 | Val ROC-AUC: 0.9635 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9666
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 3 | Train Loss: 0.0077 | Val ROC-AUC: 0.9666 | Val Profit: -145
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9598
Precision: 0.4444
Recall: 0.5714
F0.5-score: 0.4651
Profit: -360

Эпоха 4 | Train Loss: 0.0070 | Val ROC-AUC: 0.9598 | Val Profit: -360
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9583
Precision: 0.4483
Recall: 0.619
F0.5-score: 0.4745
Profit: -375

Эпоха 5 | Train Loss: 0.0061 | Val ROC-AUC: 0.9583 | Val Profit: -375
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9677
Precision: 0.5312
Recall: 0.8095
F0.5-score: 0.5705
Profit: -310

Эпоха 6 | Train Loss: 0.0059 | Val ROC-AUC: 0.9677 | Val Profit: -310
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9646
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 7 | Train Loss: 0.0060 | Val ROC-AUC: 0.9646 | Val Profit: -455
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9732
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 8 | Train Loss: 0.0049 | Val ROC-AUC: 0.9732 | Val Profit: -135
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9746
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 9 | Train Loss: 0.0038 | Val ROC-AUC: 0.9746 | Val Profit: -100
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.938
Precision: 0.4324
Recall: 0.7619
F0.5-score: 0.4734
Profit: -470

Эпоха 10 | Train Loss: 0.0041 | Val ROC-AUC: 0.9380 | Val Profit: -470
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9663
Precision: 0.6667
Recall: 0.6667
F0.5-score: 0.6667
Profit: -140

Эпоха 11 | Train Loss: 0.0048 | Val ROC-AUC: 0.9663 | Val Profit: -140
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.963
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 12 | Train Loss: 0.0036 | Val ROC-AUC: 0.9630 | Val Profit: -140
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9658
Precision: 0.6
Recall: 0.5714
F0.5-score: 0.5941
Profit: -185

Эпоха 13 | Train Loss: 0.0035 | Val ROC-AUC: 0.9658 | Val Profit: -185
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9755
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 14 | Train Loss: 0.0042 | Val ROC-AUC: 0.9755 | Val Profit: -90
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9474
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 15 | Train Loss: 0.0033 | Val ROC-AUC: 0.9474 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9812
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

Эпоха 16 | Train Loss: 0.0029 | Val ROC-AUC: 0.9812 | Val Profit: -220
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9392
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 17 | Train Loss: 0.0037 | Val ROC-AUC: 0.9392 | Val Profit: -100
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9724
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 18 | Train Loss: 0.0031 | Val ROC-AUC: 0.9724 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9784
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 19 | Train Loss: 0.0029 | Val ROC-AUC: 0.9784 | Val Profit: -115
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9378
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 20 | Train Loss: 0.0023 | Val ROC-AUC: 0.9378 | Val Profit: -150
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9772
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 21 | Train Loss: 0.0025 | Val ROC-AUC: 0.9772 | Val Profit: -135
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9729
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 22 | Train Loss: 0.0025 | Val ROC-AUC: 0.9729 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9364
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 23 | Train Loss: 0.0027 | Val ROC-AUC: 0.9364 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9614
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 24 | Train Loss: 0.0030 | Val ROC-AUC: 0.9614 | Val Profit: -165
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9793
Precision: 0.8462
Recall: 0.5238
F0.5-score: 0.7534
Profit: -45

Эпоха 25 | Train Loss: 0.0031 | Val ROC-AUC: 0.9793 | Val Profit: -45
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9771
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 26 | Train Loss: 0.0018 | Val ROC-AUC: 0.9771 | Val Profit: -115
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9741
Precision: 0.5556
Recall: 0.7143
F0.5-score: 0.5814
Profit: -255

Эпоха 27 | Train Loss: 0.0024 | Val ROC-AUC: 0.9741 | Val Profit: -255
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.972
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 28 | Train Loss: 0.0027 | Val ROC-AUC: 0.9720 | Val Profit: -110
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9127
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 29 | Train Loss: 0.0014 | Val ROC-AUC: 0.9127 | Val Profit: -100
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9022
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 30 | Train Loss: 0.0008 | Val ROC-AUC: 0.9022 | Val Profit: -110

Лучшая эпоха для model_9_Focal_loss: 16
Лучший ROC-AUC: 0.9812206572769953
val
ROC-AUC: 0.9812
Precision: 0.5926
Recall: 0.7619
F0.5-score: 0.6202
Profit: -220

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9105
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0208 | Val ROC-AUC: 0.9105 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9458
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 2 | Train Loss: 0.0103 | Val ROC-AUC: 0.9458 | Val Profit: -120
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9473
Precision: 0.4444
Recall: 0.381
F0.5-score: 0.4301
Profit: -275

Эпоха 3 | Train Loss: 0.0078 | Val ROC-AUC: 0.9473 | Val Profit: -275
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9567
Precision: 0.4167
Recall: 0.7143
F0.5-score: 0.4545
Profit: -480

Эпоха 4 | Train Loss: 0.0076 | Val ROC-AUC: 0.9567 | Val Profit: -480
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.965
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 5 | Train Loss: 0.0066 | Val ROC-AUC: 0.9650 | Val Profit: -175
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9616
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 6 | Train Loss: 0.0061 | Val ROC-AUC: 0.9616 | Val Profit: -205
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9729
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 7 | Train Loss: 0.0056 | Val ROC-AUC: 0.9729 | Val Profit: -235
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9608
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 8 | Train Loss: 0.0052 | Val ROC-AUC: 0.9608 | Val Profit: -80
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9607
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 9 | Train Loss: 0.0048 | Val ROC-AUC: 0.9607 | Val Profit: -120
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9638
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 10 | Train Loss: 0.0052 | Val ROC-AUC: 0.9638 | Val Profit: -195
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9686
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 11 | Train Loss: 0.0053 | Val ROC-AUC: 0.9686 | Val Profit: -110
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9422
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 12 | Train Loss: 0.0047 | Val ROC-AUC: 0.9422 | Val Profit: -110
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9811
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 13 | Train Loss: 0.0043 | Val ROC-AUC: 0.9811 | Val Profit: -150
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.976
Precision: 0.5135
Recall: 0.9048
F0.5-score: 0.5621
Profit: -365

Эпоха 14 | Train Loss: 0.0040 | Val ROC-AUC: 0.9760 | Val Profit: -365
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9776
Precision: 0.8182
Recall: 0.4286
F0.5-score: 0.6923
Profit: -65

Эпоха 15 | Train Loss: 0.0046 | Val ROC-AUC: 0.9776 | Val Profit: -65
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9757
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 16 | Train Loss: 0.0047 | Val ROC-AUC: 0.9757 | Val Profit: -110
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8936
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 17 | Train Loss: 0.0041 | Val ROC-AUC: 0.8936 | Val Profit: -110
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.8672
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0039 | Val ROC-AUC: 0.8672 | Val Profit: -130
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9465
Precision: 0.5
Recall: 0.5238
F0.5-score: 0.5046
Profit: -270

Эпоха 19 | Train Loss: 0.0045 | Val ROC-AUC: 0.9465 | Val Profit: -270
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9769
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 20 | Train Loss: 0.0053 | Val ROC-AUC: 0.9769 | Val Profit: -115
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.973
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 21 | Train Loss: 0.0040 | Val ROC-AUC: 0.9730 | Val Profit: -130
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9147
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0035 | Val ROC-AUC: 0.9147 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.983
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 23 | Train Loss: 0.0032 | Val ROC-AUC: 0.9830 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.8469
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 24 | Train Loss: 0.0036 | Val ROC-AUC: 0.8469 | Val Profit: -130
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9526
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 25 | Train Loss: 0.0036 | Val ROC-AUC: 0.9526 | Val Profit: -125
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9811
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 26 | Train Loss: 0.0040 | Val ROC-AUC: 0.9811 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.976
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 27 | Train Loss: 0.0040 | Val ROC-AUC: 0.9760 | Val Profit: -115
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9827
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 28 | Train Loss: 0.0039 | Val ROC-AUC: 0.9827 | Val Profit: -275
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9768
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 29 | Train Loss: 0.0052 | Val ROC-AUC: 0.9768 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9814
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 30 | Train Loss: 0.0051 | Val ROC-AUC: 0.9814 | Val Profit: -90

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9829644533869886
val
ROC-AUC: 0.983
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9356
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0207 | Val ROC-AUC: 0.9356 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9525
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0106 | Val ROC-AUC: 0.9525 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9018
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0097 | Val ROC-AUC: 0.9018 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.958
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0089 | Val ROC-AUC: 0.9580 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9677
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0078 | Val ROC-AUC: 0.9677 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9536
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 6 | Train Loss: 0.0068 | Val ROC-AUC: 0.9536 | Val Profit: -130
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9775
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0068 | Val ROC-AUC: 0.9775 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9725
Precision: 0.6
Recall: 0.4286
F0.5-score: 0.5556
Profit: -165

Эпоха 8 | Train Loss: 0.0076 | Val ROC-AUC: 0.9725 | Val Profit: -165
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9622
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0063 | Val ROC-AUC: 0.9622 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9657
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 10 | Train Loss: 0.0063 | Val ROC-AUC: 0.9657 | Val Profit: -85

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9729
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 11 | Train Loss: 0.0062 | Val ROC-AUC: 0.9729 | Val Profit: -120
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9744
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0061 | Val ROC-AUC: 0.9744 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9764
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 13 | Train Loss: 0.0062 | Val ROC-AUC: 0.9764 | Val Profit: -125
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0057 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9761
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 15 | Train Loss: 0.0060 | Val ROC-AUC: 0.9761 | Val Profit: -250

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9824
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0065 | Val ROC-AUC: 0.9824 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9811
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0059 | Val ROC-AUC: 0.9811 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9818
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0057 | Val ROC-AUC: 0.9818 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9879
Precision: 1.0
Recall: 0.381
F0.5-score: 0.7547
Profit: -25

Эпоха 19 | Train Loss: 0.0057 | Val ROC-AUC: 0.9879 | Val Profit: -25
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9828
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 20 | Train Loss: 0.0054 | Val ROC-AUC: 0.9828 | Val Profit: -75

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9882
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0055 | Val ROC-AUC: 0.9882 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9883
Precision: 1.0
Recall: 0.2857
F0.5-score: 0.6667
Profit: -45

Эпоха 22 | Train Loss: 0.0051 | Val ROC-AUC: 0.9883 | Val Profit: -45
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9769
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 23 | Train Loss: 0.0056 | Val ROC-AUC: 0.9769 | Val Profit: -135
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9882
Precision: 0.4286
Recall: 1.0
F0.5-score: 0.4839
Profit: -595

Эпоха 24 | Train Loss: 0.0059 | Val ROC-AUC: 0.9882 | Val Profit: -595
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9856
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0053 | Val ROC-AUC: 0.9856 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9855
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 26 | Train Loss: 0.0055 | Val ROC-AUC: 0.9855 | Val Profit: -85
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9887
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 27 | Train Loss: 0.0051 | Val ROC-AUC: 0.9887 | Val Profit: -105
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9831
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0052 | Val ROC-AUC: 0.9831 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9906
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0049 | Val ROC-AUC: 0.9906 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9859
Precision: 0.5806
Recall: 0.8571
F0.5-score: 0.6207
Profit: -250

Эпоха 30 | Train Loss: 0.0052 | Val ROC-AUC: 0.9859 | Val Profit: -250

Лучшая эпоха для model_9_Focal_loss: 29
Лучший ROC-AUC: 0.9906103286384977
val
ROC-AUC: 0.9906
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8704
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0237 | Val ROC-AUC: 0.8704 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9274
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0127 | Val ROC-AUC: 0.9274 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9547
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0087 | Val ROC-AUC: 0.9547 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9466
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0075 | Val ROC-AUC: 0.9466 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9521
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0066 | Val ROC-AUC: 0.9521 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9439
Precision: 0.4706
Recall: 0.381
F0.5-score: 0.4494
Profit: -250

Эпоха 6 | Train Loss: 0.0058 | Val ROC-AUC: 0.9439 | Val Profit: -250
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9489
Precision: 0.4737
Recall: 0.4286
F0.5-score: 0.4639
Profit: -265

Эпоха 7 | Train Loss: 0.0050 | Val ROC-AUC: 0.9489 | Val Profit: -265
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9343
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 8 | Train Loss: 0.0036 | Val ROC-AUC: 0.9343 | Val Profit: -160
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9651
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 9 | Train Loss: 0.0037 | Val ROC-AUC: 0.9651 | Val Profit: -275
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9701
Precision: 0.5185
Recall: 0.6667
F0.5-score: 0.5426
Profit: -290

Эпоха 10 | Train Loss: 0.0042 | Val ROC-AUC: 0.9701 | Val Profit: -290
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9669
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 11 | Train Loss: 0.0037 | Val ROC-AUC: 0.9669 | Val Profit: -240
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9431
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 12 | Train Loss: 0.0023 | Val ROC-AUC: 0.9431 | Val Profit: -210
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9278
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 13 | Train Loss: 0.0021 | Val ROC-AUC: 0.9278 | Val Profit: -225
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9375
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 14 | Train Loss: 0.0033 | Val ROC-AUC: 0.9375 | Val Profit: -250
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9406
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 15 | Train Loss: 0.0041 | Val ROC-AUC: 0.9406 | Val Profit: -455
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9586
Precision: 0.5714
Recall: 0.381
F0.5-score: 0.5195
Profit: -175

Эпоха 16 | Train Loss: 0.0028 | Val ROC-AUC: 0.9586 | Val Profit: -175
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9588
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 17 | Train Loss: 0.0028 | Val ROC-AUC: 0.9588 | Val Profit: -185
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9722
Precision: 0.2
Recall: 0.0476
F0.5-score: 0.122
Profit: -195

Эпоха 18 | Train Loss: 0.0013 | Val ROC-AUC: 0.9722 | Val Profit: -195
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9734
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 19 | Train Loss: 0.0007 | Val ROC-AUC: 0.9734 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9685
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 20 | Train Loss: 0.0004 | Val ROC-AUC: 0.9685 | Val Profit: -175
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.972
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 21 | Train Loss: 0.0002 | Val ROC-AUC: 0.9720 | Val Profit: -135
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9737
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 22 | Train Loss: 0.0002 | Val ROC-AUC: 0.9737 | Val Profit: -155
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9741
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 23 | Train Loss: 0.0001 | Val ROC-AUC: 0.9741 | Val Profit: -145
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9742
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 24 | Train Loss: 0.0001 | Val ROC-AUC: 0.9742 | Val Profit: -145
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.974
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 25 | Train Loss: 0.0001 | Val ROC-AUC: 0.9740 | Val Profit: -145
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9741
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 26 | Train Loss: 0.0001 | Val ROC-AUC: 0.9741 | Val Profit: -145
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9732
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 27 | Train Loss: 0.0001 | Val ROC-AUC: 0.9732 | Val Profit: -145
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.973
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 28 | Train Loss: 0.0001 | Val ROC-AUC: 0.9730 | Val Profit: -145
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9734
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 29 | Train Loss: 0.0001 | Val ROC-AUC: 0.9734 | Val Profit: -145
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9733
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 30 | Train Loss: 0.0000 | Val ROC-AUC: 0.9733 | Val Profit: -145

Лучшая эпоха для model_9_Focal_loss: 24
Лучший ROC-AUC: 0.9742454728370221
val
ROC-AUC: 0.9742
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.914
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0233 | Val ROC-AUC: 0.9140 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9477
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 2 | Train Loss: 0.0121 | Val ROC-AUC: 0.9477 | Val Profit: -110
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9694
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 3 | Train Loss: 0.0085 | Val ROC-AUC: 0.9694 | Val Profit: -85
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9679
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 4 | Train Loss: 0.0068 | Val ROC-AUC: 0.9679 | Val Profit: -215
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9604
Precision: 0.4211
Recall: 0.381
F0.5-score: 0.4124
Profit: -300

Эпоха 5 | Train Loss: 0.0049 | Val ROC-AUC: 0.9604 | Val Profit: -300
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9724
Precision: 0.5484
Recall: 0.8095
F0.5-score: 0.5862
Profit: -285

Эпоха 6 | Train Loss: 0.0042 | Val ROC-AUC: 0.9724 | Val Profit: -285
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9586
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 7 | Train Loss: 0.0039 | Val ROC-AUC: 0.9586 | Val Profit: -345
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.8771
Precision: 0.3103
Recall: 0.4286
F0.5-score: 0.3285
Profit: -515

Эпоха 8 | Train Loss: 0.0042 | Val ROC-AUC: 0.8771 | Val Profit: -515
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9681
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 9 | Train Loss: 0.0052 | Val ROC-AUC: 0.9681 | Val Profit: -185
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.976
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 10 | Train Loss: 0.0044 | Val ROC-AUC: 0.9760 | Val Profit: -125
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9536
Precision: 0.3846
Recall: 0.2381
F0.5-score: 0.3425
Profit: -255

Эпоха 11 | Train Loss: 0.0029 | Val ROC-AUC: 0.9536 | Val Profit: -255
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9657
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 12 | Train Loss: 0.0028 | Val ROC-AUC: 0.9657 | Val Profit: -145
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9229
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 13 | Train Loss: 0.0035 | Val ROC-AUC: 0.9229 | Val Profit: -160
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9315
Precision: 0.6667
Recall: 0.5714
F0.5-score: 0.6452
Profit: -135

Эпоха 14 | Train Loss: 0.0032 | Val ROC-AUC: 0.9315 | Val Profit: -135
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9101
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 15 | Train Loss: 0.0032 | Val ROC-AUC: 0.9101 | Val Profit: -220
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9493
Precision: 0.5
Recall: 0.2857
F0.5-score: 0.4348
Profit: -195

Эпоха 16 | Train Loss: 0.0027 | Val ROC-AUC: 0.9493 | Val Profit: -195
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.888
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 17 | Train Loss: 0.0026 | Val ROC-AUC: 0.8880 | Val Profit: -235
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9081
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 18 | Train Loss: 0.0017 | Val ROC-AUC: 0.9081 | Val Profit: -165
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9622
Precision: 0.4167
Recall: 0.4762
F0.5-score: 0.4274
Profit: -355

Эпоха 19 | Train Loss: 0.0022 | Val ROC-AUC: 0.9622 | Val Profit: -355
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9724
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 20 | Train Loss: 0.0028 | Val ROC-AUC: 0.9724 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9741
Precision: 0.7368
Recall: 0.6667
F0.5-score: 0.7216
Profit: -90

Эпоха 21 | Train Loss: 0.0025 | Val ROC-AUC: 0.9741 | Val Profit: -90
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9789
Precision: 0.6
Recall: 0.8571
F0.5-score: 0.6383
Profit: -225

Эпоха 22 | Train Loss: 0.0031 | Val ROC-AUC: 0.9789 | Val Profit: -225
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9752
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 23 | Train Loss: 0.0030 | Val ROC-AUC: 0.9752 | Val Profit: -110
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9524
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 24 | Train Loss: 0.0017 | Val ROC-AUC: 0.9524 | Val Profit: -110
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.956
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 25 | Train Loss: 0.0010 | Val ROC-AUC: 0.9560 | Val Profit: -115

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8766
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0009 | Val ROC-AUC: 0.8766 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9383
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 27 | Train Loss: 0.0006 | Val ROC-AUC: 0.9383 | Val Profit: -130
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.8875
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 28 | Train Loss: 0.0005 | Val ROC-AUC: 0.8875 | Val Profit: -150
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.8901
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 29 | Train Loss: 0.0004 | Val ROC-AUC: 0.8901 | Val Profit: -150
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.8829
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 30 | Train Loss: 0.0004 | Val ROC-AUC: 0.8829 | Val Profit: -150

Лучшая эпоха для model_9_Focal_loss: 22
Лучший ROC-AUC: 0.9789403085177732
val
ROC-AUC: 0.9789
Precision: 0.6
Recall: 0.8571
F0.5-score: 0.6383
Profit: -225

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8429
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0236 | Val ROC-AUC: 0.8429 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9536
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0123 | Val ROC-AUC: 0.9536 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9628
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0094 | Val ROC-AUC: 0.9628 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9634
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0086 | Val ROC-AUC: 0.9634 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9432
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0085 | Val ROC-AUC: 0.9432 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.956
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0076 | Val ROC-AUC: 0.9560 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9543
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0080 | Val ROC-AUC: 0.9543 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9636
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0077 | Val ROC-AUC: 0.9636 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9532
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0077 | Val ROC-AUC: 0.9532 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9315
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0079 | Val ROC-AUC: 0.9315 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9591
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0077 | Val ROC-AUC: 0.9591 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9701
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0074 | Val ROC-AUC: 0.9701 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9706
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0066 | Val ROC-AUC: 0.9706 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.962
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0065 | Val ROC-AUC: 0.9620 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0060 | Val ROC-AUC: 0.9689 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0060 | Val ROC-AUC: 0.9755 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.969
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0062 | Val ROC-AUC: 0.9690 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.969
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0058 | Val ROC-AUC: 0.9690 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9755
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0067 | Val ROC-AUC: 0.9755 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.976
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 20 | Train Loss: 0.0061 | Val ROC-AUC: 0.9760 | Val Profit: -105
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9733
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0052 | Val ROC-AUC: 0.9733 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9168
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 22 | Train Loss: 0.0047 | Val ROC-AUC: 0.9168 | Val Profit: -105
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9738
Precision: 0.65
Recall: 0.619
F0.5-score: 0.6436
Profit: -150

Эпоха 23 | Train Loss: 0.0046 | Val ROC-AUC: 0.9738 | Val Profit: -150
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9681
Precision: 0.4545
Recall: 0.9524
F0.5-score: 0.5076
Profit: -505

Эпоха 24 | Train Loss: 0.0052 | Val ROC-AUC: 0.9681 | Val Profit: -505
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9675
Precision: 0.5333
Recall: 0.381
F0.5-score: 0.4938
Profit: -200

Эпоха 25 | Train Loss: 0.0052 | Val ROC-AUC: 0.9675 | Val Profit: -200
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.965
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 26 | Train Loss: 0.0046 | Val ROC-AUC: 0.9650 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9418
Precision: 0.3519
Recall: 0.9048
F0.5-score: 0.4008
Profit: -790

Эпоха 27 | Train Loss: 0.0049 | Val ROC-AUC: 0.9418 | Val Profit: -790
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9776
Precision: 0.5833
Recall: 0.6667
F0.5-score: 0.5983
Profit: -215

Эпоха 28 | Train Loss: 0.0061 | Val ROC-AUC: 0.9776 | Val Profit: -215
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9776
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0050 | Val ROC-AUC: 0.9776 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9768
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0042 | Val ROC-AUC: 0.9768 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 29
Лучший ROC-AUC: 0.9775989268947016
val
ROC-AUC: 0.9776
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.904
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0247 | Val ROC-AUC: 0.9040 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9478
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0123 | Val ROC-AUC: 0.9478 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9471
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0086 | Val ROC-AUC: 0.9471 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.945
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0071 | Val ROC-AUC: 0.9450 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.948
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 5 | Train Loss: 0.0059 | Val ROC-AUC: 0.9480 | Val Profit: -160
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9662
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 6 | Train Loss: 0.0051 | Val ROC-AUC: 0.9662 | Val Profit: -135
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.961
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 7 | Train Loss: 0.0049 | Val ROC-AUC: 0.9610 | Val Profit: -260
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9565
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 8 | Train Loss: 0.0037 | Val ROC-AUC: 0.9565 | Val Profit: -170
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.8849
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 9 | Train Loss: 0.0025 | Val ROC-AUC: 0.8849 | Val Profit: -135
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9611
Precision: 0.4
Recall: 0.7619
F0.5-score: 0.442
Profit: -545

Эпоха 10 | Train Loss: 0.0022 | Val ROC-AUC: 0.9611 | Val Profit: -545
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9584
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 11 | Train Loss: 0.0032 | Val ROC-AUC: 0.9584 | Val Profit: -125
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.8761
Precision: 0.2
Recall: 0.0476
F0.5-score: 0.122
Profit: -195

Эпоха 12 | Train Loss: 0.0028 | Val ROC-AUC: 0.8761 | Val Profit: -195
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9178
Precision: 0.4211
Recall: 0.381
F0.5-score: 0.4124
Profit: -300

Эпоха 13 | Train Loss: 0.0017 | Val ROC-AUC: 0.9178 | Val Profit: -300
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9516
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 14 | Train Loss: 0.0022 | Val ROC-AUC: 0.9516 | Val Profit: -135
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9556
Precision: 0.5
Recall: 0.4286
F0.5-score: 0.4839
Profit: -240

Эпоха 15 | Train Loss: 0.0023 | Val ROC-AUC: 0.9556 | Val Profit: -240
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9641
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 16 | Train Loss: 0.0017 | Val ROC-AUC: 0.9641 | Val Profit: -65
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9674
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 17 | Train Loss: 0.0007 | Val ROC-AUC: 0.9674 | Val Profit: -90
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9669
Precision: 1.0
Recall: 0.2381
F0.5-score: 0.6098
Profit: -55

Эпоха 18 | Train Loss: 0.0004 | Val ROC-AUC: 0.9669 | Val Profit: -55
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9674
Precision: 1.0
Recall: 0.3333
F0.5-score: 0.7143
Profit: -35

Эпоха 19 | Train Loss: 0.0003 | Val ROC-AUC: 0.9674 | Val Profit: -35
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.967
Precision: 0.875
Recall: 0.3333
F0.5-score: 0.6604
Profit: -60

Эпоха 20 | Train Loss: 0.0003 | Val ROC-AUC: 0.9670 | Val Profit: -60
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9659
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 21 | Train Loss: 0.0003 | Val ROC-AUC: 0.9659 | Val Profit: -80
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9658
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 22 | Train Loss: 0.0002 | Val ROC-AUC: 0.9658 | Val Profit: -80
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9647
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 23 | Train Loss: 0.0002 | Val ROC-AUC: 0.9647 | Val Profit: -80
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9639
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 24 | Train Loss: 0.0002 | Val ROC-AUC: 0.9639 | Val Profit: -90
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9636
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 25 | Train Loss: 0.0002 | Val ROC-AUC: 0.9636 | Val Profit: -100
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9636
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 26 | Train Loss: 0.0002 | Val ROC-AUC: 0.9636 | Val Profit: -90
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9632
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 27 | Train Loss: 0.0002 | Val ROC-AUC: 0.9632 | Val Profit: -90
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9631
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 28 | Train Loss: 0.0002 | Val ROC-AUC: 0.9631 | Val Profit: -90
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9628
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 29 | Train Loss: 0.0002 | Val ROC-AUC: 0.9628 | Val Profit: -90
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9624
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 30 | Train Loss: 0.0001 | Val ROC-AUC: 0.9624 | Val Profit: -90

Лучшая эпоха для model_9_Focal_loss: 17
Лучший ROC-AUC: 0.9674044265593561
val
ROC-AUC: 0.9674
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8103
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0253 | Val ROC-AUC: 0.8103 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9581
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0131 | Val ROC-AUC: 0.9581 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9517
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0093 | Val ROC-AUC: 0.9517 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9453
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0078 | Val ROC-AUC: 0.9453 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9651
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 5 | Train Loss: 0.0067 | Val ROC-AUC: 0.9651 | Val Profit: -135
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9608
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0048 | Val ROC-AUC: 0.9608 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9627
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 7 | Train Loss: 0.0040 | Val ROC-AUC: 0.9627 | Val Profit: -135
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.961
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 8 | Train Loss: 0.0047 | Val ROC-AUC: 0.9610 | Val Profit: -285
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9658
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 9 | Train Loss: 0.0040 | Val ROC-AUC: 0.9658 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9298
Precision: 0.3462
Recall: 0.4286
F0.5-score: 0.36
Profit: -440

Эпоха 10 | Train Loss: 0.0037 | Val ROC-AUC: 0.9298 | Val Profit: -440
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9555
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 11 | Train Loss: 0.0042 | Val ROC-AUC: 0.9555 | Val Profit: -120
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9548
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 12 | Train Loss: 0.0023 | Val ROC-AUC: 0.9548 | Val Profit: -95
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.967
Precision: 0.5185
Recall: 0.6667
F0.5-score: 0.5426
Profit: -290

Эпоха 13 | Train Loss: 0.0025 | Val ROC-AUC: 0.9670 | Val Profit: -290
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9653
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 14 | Train Loss: 0.0028 | Val ROC-AUC: 0.9653 | Val Profit: -295
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9539
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 15 | Train Loss: 0.0035 | Val ROC-AUC: 0.9539 | Val Profit: -345
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9646
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 16 | Train Loss: 0.0024 | Val ROC-AUC: 0.9646 | Val Profit: -120
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9608
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 17 | Train Loss: 0.0015 | Val ROC-AUC: 0.9608 | Val Profit: -150
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9492
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 18 | Train Loss: 0.0011 | Val ROC-AUC: 0.9492 | Val Profit: -190
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9535
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 19 | Train Loss: 0.0010 | Val ROC-AUC: 0.9535 | Val Profit: -180
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9484
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 20 | Train Loss: 0.0009 | Val ROC-AUC: 0.9484 | Val Profit: -140
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9641
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 21 | Train Loss: 0.0008 | Val ROC-AUC: 0.9641 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9624
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 22 | Train Loss: 0.0007 | Val ROC-AUC: 0.9624 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9632
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 23 | Train Loss: 0.0007 | Val ROC-AUC: 0.9632 | Val Profit: -150
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9608
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 24 | Train Loss: 0.0006 | Val ROC-AUC: 0.9608 | Val Profit: -125
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9595
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 25 | Train Loss: 0.0006 | Val ROC-AUC: 0.9595 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9588
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 26 | Train Loss: 0.0006 | Val ROC-AUC: 0.9588 | Val Profit: -175
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.956
Precision: 0.4545
Recall: 0.2381
F0.5-score: 0.3846
Profit: -205

Эпоха 27 | Train Loss: 0.0006 | Val ROC-AUC: 0.9560 | Val Profit: -205
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9657
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 28 | Train Loss: 0.0007 | Val ROC-AUC: 0.9657 | Val Profit: -100
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9386
Precision: 0.236
Recall: 1.0
F0.5-score: 0.2785
Profit: -1595

Эпоха 29 | Train Loss: 0.0085 | Val ROC-AUC: 0.9386 | Val Profit: -1595
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9103
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 30 | Train Loss: 0.0096 | Val ROC-AUC: 0.9103 | Val Profit: -225

Лучшая эпоха для model_9_Focal_loss: 13
Лучший ROC-AUC: 0.9670020120724346
val
ROC-AUC: 0.967
Precision: 0.5185
Recall: 0.6667
F0.5-score: 0.5426
Profit: -290

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9002
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0248 | Val ROC-AUC: 0.9002 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9376
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0134 | Val ROC-AUC: 0.9376 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9414
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0094 | Val ROC-AUC: 0.9414 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9209
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0083 | Val ROC-AUC: 0.9209 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9117
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0077 | Val ROC-AUC: 0.9117 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9544
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0061 | Val ROC-AUC: 0.9544 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9531
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 7 | Train Loss: 0.0059 | Val ROC-AUC: 0.9531 | Val Profit: -140
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9471
Precision: 0.4118
Recall: 0.3333
F0.5-score: 0.3933
Profit: -285

Эпоха 8 | Train Loss: 0.0064 | Val ROC-AUC: 0.9471 | Val Profit: -285

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9494
Precision: 0.375
Recall: 0.4286
F0.5-score: 0.3846
Profit: -390

Эпоха 9 | Train Loss: 0.0059 | Val ROC-AUC: 0.9494 | Val Profit: -390
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9457
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0056 | Val ROC-AUC: 0.9457 | Val Profit: -105
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9598
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 11 | Train Loss: 0.0048 | Val ROC-AUC: 0.9598 | Val Profit: -135
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9607
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 12 | Train Loss: 0.0050 | Val ROC-AUC: 0.9607 | Val Profit: -150
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9721
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 13 | Train Loss: 0.0050 | Val ROC-AUC: 0.9721 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.7311
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0040 | Val ROC-AUC: 0.7311 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.8351
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 15 | Train Loss: 0.0031 | Val ROC-AUC: 0.8351 | Val Profit: -130
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9624
Precision: 0.2414
Recall: 1.0
F0.5-score: 0.2846
Profit: -1545

Эпоха 16 | Train Loss: 0.0052 | Val ROC-AUC: 0.9624 | Val Profit: -1545
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9583
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 17 | Train Loss: 0.0053 | Val ROC-AUC: 0.9583 | Val Profit: -320
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9716
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 18 | Train Loss: 0.0042 | Val ROC-AUC: 0.9716 | Val Profit: -130

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.976
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0035 | Val ROC-AUC: 0.9760 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9701
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 20 | Train Loss: 0.0036 | Val ROC-AUC: 0.9701 | Val Profit: -155
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.959
Precision: 0.4615
Recall: 0.2857
F0.5-score: 0.411
Profit: -220

Эпоха 21 | Train Loss: 0.0036 | Val ROC-AUC: 0.9590 | Val Profit: -220
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.96
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 22 | Train Loss: 0.0036 | Val ROC-AUC: 0.9600 | Val Profit: -150
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.926
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 23 | Train Loss: 0.0027 | Val ROC-AUC: 0.9260 | Val Profit: -130
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9721
Precision: 0.5417
Recall: 0.619
F0.5-score: 0.5556
Profit: -250

Эпоха 24 | Train Loss: 0.0036 | Val ROC-AUC: 0.9721 | Val Profit: -250
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9435
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0032 | Val ROC-AUC: 0.9435 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.972
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 26 | Train Loss: 0.0035 | Val ROC-AUC: 0.9720 | Val Profit: -130
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9733
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 27 | Train Loss: 0.0032 | Val ROC-AUC: 0.9733 | Val Profit: -145
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9775
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 28 | Train Loss: 0.0030 | Val ROC-AUC: 0.9775 | Val Profit: -145

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9761
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 29 | Train Loss: 0.0036 | Val ROC-AUC: 0.9761 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9669
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 30 | Train Loss: 0.0029 | Val ROC-AUC: 0.9669 | Val Profit: -125

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.9774647887323944
val
ROC-AUC: 0.9775
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9136
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0413 | Val ROC-AUC: 0.9136 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9353
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0211 | Val ROC-AUC: 0.9353 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9634
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 3 | Train Loss: 0.0153 | Val ROC-AUC: 0.9634 | Val Profit: -220

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.96
Precision: 0.55
Recall: 0.5238
F0.5-score: 0.5446
Profit: -220

Эпоха 4 | Train Loss: 0.0127 | Val ROC-AUC: 0.9600 | Val Profit: -220
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.97
Precision: 0.4848
Recall: 0.7619
F0.5-score: 0.5229
Profit: -370

Эпоха 5 | Train Loss: 0.0106 | Val ROC-AUC: 0.9700 | Val Profit: -370
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9701
Precision: 0.5333
Recall: 0.7619
F0.5-score: 0.5674
Profit: -295

Эпоха 6 | Train Loss: 0.0099 | Val ROC-AUC: 0.9701 | Val Profit: -295
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9708
Precision: 0.5625
Recall: 0.8571
F0.5-score: 0.604
Profit: -275

Эпоха 7 | Train Loss: 0.0102 | Val ROC-AUC: 0.9708 | Val Profit: -275
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9687
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 8 | Train Loss: 0.0087 | Val ROC-AUC: 0.9687 | Val Profit: -265
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9638
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 9 | Train Loss: 0.0090 | Val ROC-AUC: 0.9638 | Val Profit: -200
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9694
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 10 | Train Loss: 0.0089 | Val ROC-AUC: 0.9694 | Val Profit: -145
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9737
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 11 | Train Loss: 0.0085 | Val ROC-AUC: 0.9737 | Val Profit: -145
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9691
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 12 | Train Loss: 0.0064 | Val ROC-AUC: 0.9691 | Val Profit: -95
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9717
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 13 | Train Loss: 0.0079 | Val ROC-AUC: 0.9717 | Val Profit: -100
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9748
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 14 | Train Loss: 0.0082 | Val ROC-AUC: 0.9748 | Val Profit: -180
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9714
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 15 | Train Loss: 0.0078 | Val ROC-AUC: 0.9714 | Val Profit: -90
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9732
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 16 | Train Loss: 0.0065 | Val ROC-AUC: 0.9732 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9661
Precision: 0.7857
Recall: 0.5238
F0.5-score: 0.7143
Profit: -70

Эпоха 17 | Train Loss: 0.0048 | Val ROC-AUC: 0.9661 | Val Profit: -70
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9734
Precision: 0.7059
Recall: 0.5714
F0.5-score: 0.6742
Profit: -110

Эпоха 18 | Train Loss: 0.0047 | Val ROC-AUC: 0.9734 | Val Profit: -110
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9772
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 19 | Train Loss: 0.0042 | Val ROC-AUC: 0.9772 | Val Profit: -230
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9708
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 20 | Train Loss: 0.0050 | Val ROC-AUC: 0.9708 | Val Profit: -185
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9738
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 21 | Train Loss: 0.0055 | Val ROC-AUC: 0.9738 | Val Profit: -230
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9753
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 22 | Train Loss: 0.0064 | Val ROC-AUC: 0.9753 | Val Profit: -110
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9815
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 23 | Train Loss: 0.0051 | Val ROC-AUC: 0.9815 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9742
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 24 | Train Loss: 0.0032 | Val ROC-AUC: 0.9742 | Val Profit: -155
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9783
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 25 | Train Loss: 0.0040 | Val ROC-AUC: 0.9783 | Val Profit: -115
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9756
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 26 | Train Loss: 0.0034 | Val ROC-AUC: 0.9756 | Val Profit: -140
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.974
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 27 | Train Loss: 0.0045 | Val ROC-AUC: 0.9740 | Val Profit: -125
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9484
Precision: 0.5455
Recall: 0.2857
F0.5-score: 0.4615
Profit: -170

Эпоха 28 | Train Loss: 0.0043 | Val ROC-AUC: 0.9484 | Val Profit: -170
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9706
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 29 | Train Loss: 0.0036 | Val ROC-AUC: 0.9706 | Val Profit: -120
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9655
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 30 | Train Loss: 0.0023 | Val ROC-AUC: 0.9655 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 23
Лучший ROC-AUC: 0.9814889336016096
val
ROC-AUC: 0.9815
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9092
Precision: 0.3333
Recall: 0.1429
F0.5-score: 0.2632
Profit: -225

Эпоха 1 | Train Loss: 0.0409 | Val ROC-AUC: 0.9092 | Val Profit: -225
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9603
Precision: 0.4412
Recall: 0.7143
F0.5-score: 0.4777
Profit: -430

Эпоха 2 | Train Loss: 0.0199 | Val ROC-AUC: 0.9603 | Val Profit: -430
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9576
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 3 | Train Loss: 0.0155 | Val ROC-AUC: 0.9576 | Val Profit: -120
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9641
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 4 | Train Loss: 0.0136 | Val ROC-AUC: 0.9641 | Val Profit: -265
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9524
Precision: 0.4444
Recall: 0.1905
F0.5-score: 0.3509
Profit: -190

Эпоха 5 | Train Loss: 0.0121 | Val ROC-AUC: 0.9524 | Val Profit: -190
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9679
Precision: 0.5217
Recall: 0.5714
F0.5-score: 0.531
Profit: -260

Эпоха 6 | Train Loss: 0.0106 | Val ROC-AUC: 0.9679 | Val Profit: -260
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.972
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 7 | Train Loss: 0.0111 | Val ROC-AUC: 0.9720 | Val Profit: -90
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9752
Precision: 0.7273
Recall: 0.381
F0.5-score: 0.6154
Profit: -100

Эпоха 8 | Train Loss: 0.0112 | Val ROC-AUC: 0.9752 | Val Profit: -100
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9779
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 9 | Train Loss: 0.0092 | Val ROC-AUC: 0.9779 | Val Profit: -175
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9741
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 10 | Train Loss: 0.0080 | Val ROC-AUC: 0.9741 | Val Profit: -115
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9748
Precision: 0.75
Recall: 0.4286
F0.5-score: 0.6522
Profit: -90

Эпоха 11 | Train Loss: 0.0104 | Val ROC-AUC: 0.9748 | Val Profit: -90
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9733
Precision: 0.5667
Recall: 0.8095
F0.5-score: 0.6028
Profit: -260

Эпоха 12 | Train Loss: 0.0095 | Val ROC-AUC: 0.9733 | Val Profit: -260
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9481
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 13 | Train Loss: 0.0105 | Val ROC-AUC: 0.9481 | Val Profit: -155
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9799
Precision: 0.6667
Recall: 0.7619
F0.5-score: 0.6838
Profit: -145

Эпоха 14 | Train Loss: 0.0073 | Val ROC-AUC: 0.9799 | Val Profit: -145
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.921
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 15 | Train Loss: 0.0073 | Val ROC-AUC: 0.9210 | Val Profit: -145
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9732
Precision: 0.38
Recall: 0.9048
F0.5-score: 0.4299
Profit: -690

Эпоха 16 | Train Loss: 0.0100 | Val ROC-AUC: 0.9732 | Val Profit: -690
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9769
Precision: 0.6154
Recall: 0.381
F0.5-score: 0.5479
Profit: -150

Эпоха 17 | Train Loss: 0.0102 | Val ROC-AUC: 0.9769 | Val Profit: -150
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9801
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 18 | Train Loss: 0.0081 | Val ROC-AUC: 0.9801 | Val Profit: -120
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9427
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 19 | Train Loss: 0.0064 | Val ROC-AUC: 0.9427 | Val Profit: -120
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.947
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 20 | Train Loss: 0.0064 | Val ROC-AUC: 0.9470 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.972
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 21 | Train Loss: 0.0087 | Val ROC-AUC: 0.9720 | Val Profit: -140
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8845
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 22 | Train Loss: 0.0061 | Val ROC-AUC: 0.8845 | Val Profit: -130
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9738
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 23 | Train Loss: 0.0064 | Val ROC-AUC: 0.9738 | Val Profit: -195
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9765
Precision: 0.5714
Recall: 0.1905
F0.5-score: 0.4082
Profit: -140

Эпоха 24 | Train Loss: 0.0078 | Val ROC-AUC: 0.9765 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9329
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 25 | Train Loss: 0.0058 | Val ROC-AUC: 0.9329 | Val Profit: -125
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9336
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 26 | Train Loss: 0.0060 | Val ROC-AUC: 0.9336 | Val Profit: -120
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.974
Precision: 0.56
Recall: 0.6667
F0.5-score: 0.5785
Profit: -240

Эпоха 27 | Train Loss: 0.0089 | Val ROC-AUC: 0.9740 | Val Profit: -240
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9694
Precision: 0.8
Recall: 0.381
F0.5-score: 0.6557
Profit: -75

Эпоха 28 | Train Loss: 0.0088 | Val ROC-AUC: 0.9694 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9567
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0071 | Val ROC-AUC: 0.9567 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9319
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 30 | Train Loss: 0.0058 | Val ROC-AUC: 0.9319 | Val Profit: -130

Лучшая эпоха для model_9_Focal_loss: 18
Лучший ROC-AUC: 0.9801475519785379
val
ROC-AUC: 0.9801
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9316
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0410 | Val ROC-AUC: 0.9316 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9339
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 2 | Train Loss: 0.0202 | Val ROC-AUC: 0.9339 | Val Profit: -120

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9478
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 3 | Train Loss: 0.0164 | Val ROC-AUC: 0.9478 | Val Profit: -155
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.959
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 4 | Train Loss: 0.0152 | Val ROC-AUC: 0.9590 | Val Profit: -85
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9569
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0144 | Val ROC-AUC: 0.9569 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9659
Precision: 0.625
Recall: 0.2381
F0.5-score: 0.4717
Profit: -130

Эпоха 6 | Train Loss: 0.0127 | Val ROC-AUC: 0.9659 | Val Profit: -130
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9441
Precision: 0.6
Recall: 0.2857
F0.5-score: 0.4918
Profit: -145

Эпоха 7 | Train Loss: 0.0157 | Val ROC-AUC: 0.9441 | Val Profit: -145
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9596
Precision: 0.5
Recall: 0.3333
F0.5-score: 0.4545
Profit: -210

Эпоха 8 | Train Loss: 0.0140 | Val ROC-AUC: 0.9596 | Val Profit: -210
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9627
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0113 | Val ROC-AUC: 0.9627 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.974
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 10 | Train Loss: 0.0107 | Val ROC-AUC: 0.9740 | Val Profit: -130
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9705
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0115 | Val ROC-AUC: 0.9705 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9847
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 12 | Train Loss: 0.0111 | Val ROC-AUC: 0.9847 | Val Profit: -80

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9761
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 13 | Train Loss: 0.0109 | Val ROC-AUC: 0.9761 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9714
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0112 | Val ROC-AUC: 0.9714 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9816
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0102 | Val ROC-AUC: 0.9816 | Val Profit: -105
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9772
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 16 | Train Loss: 0.0104 | Val ROC-AUC: 0.9772 | Val Profit: -135
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9759
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0103 | Val ROC-AUC: 0.9759 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9842
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 18 | Train Loss: 0.0098 | Val ROC-AUC: 0.9842 | Val Profit: -115
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9693
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 19 | Train Loss: 0.0101 | Val ROC-AUC: 0.9693 | Val Profit: -120
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9749
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 20 | Train Loss: 0.0109 | Val ROC-AUC: 0.9749 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9769
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 21 | Train Loss: 0.0100 | Val ROC-AUC: 0.9769 | Val Profit: -105
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9763
Precision: 0.5385
Recall: 0.6667
F0.5-score: 0.56
Profit: -265

Эпоха 22 | Train Loss: 0.0129 | Val ROC-AUC: 0.9763 | Val Profit: -265

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9763
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 23 | Train Loss: 0.0101 | Val ROC-AUC: 0.9763 | Val Profit: -95
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9856
Precision: 0.64
Recall: 0.7619
F0.5-score: 0.6612
Profit: -170

Эпоха 24 | Train Loss: 0.0116 | Val ROC-AUC: 0.9856 | Val Profit: -170
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9859
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0104 | Val ROC-AUC: 0.9859 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.7602
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0089 | Val ROC-AUC: 0.7602 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.984
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 27 | Train Loss: 0.0097 | Val ROC-AUC: 0.9840 | Val Profit: -120
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9863
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 28 | Train Loss: 0.0086 | Val ROC-AUC: 0.9863 | Val Profit: -120
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9823
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 29 | Train Loss: 0.0086 | Val ROC-AUC: 0.9823 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9852
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 30 | Train Loss: 0.0086 | Val ROC-AUC: 0.9852 | Val Profit: -105

Лучшая эпоха для model_9_Focal_loss: 28
Лучший ROC-AUC: 0.986317907444668
val
ROC-AUC: 0.9863
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8667
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0469 | Val ROC-AUC: 0.8667 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9242
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0252 | Val ROC-AUC: 0.9242 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.95
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0173 | Val ROC-AUC: 0.9500 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9575
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0140 | Val ROC-AUC: 0.9575 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9628
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0129 | Val ROC-AUC: 0.9628 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9551
Precision: 0.5833
Recall: 0.3333
F0.5-score: 0.5072
Profit: -160

Эпоха 6 | Train Loss: 0.0119 | Val ROC-AUC: 0.9551 | Val Profit: -160
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9686
Precision: 0.5357
Recall: 0.7143
F0.5-score: 0.5639
Profit: -280

Эпоха 7 | Train Loss: 0.0086 | Val ROC-AUC: 0.9686 | Val Profit: -280
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9655
Precision: 0.5455
Recall: 0.5714
F0.5-score: 0.5505
Profit: -235

Эпоха 8 | Train Loss: 0.0073 | Val ROC-AUC: 0.9655 | Val Profit: -235
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9583
Precision: 0.5882
Recall: 0.4762
F0.5-score: 0.5618
Profit: -180

Эпоха 9 | Train Loss: 0.0051 | Val ROC-AUC: 0.9583 | Val Profit: -180
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9744
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

Эпоха 10 | Train Loss: 0.0059 | Val ROC-AUC: 0.9744 | Val Profit: -315
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9501
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 11 | Train Loss: 0.0089 | Val ROC-AUC: 0.9501 | Val Profit: -205
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9595
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 12 | Train Loss: 0.0059 | Val ROC-AUC: 0.9595 | Val Profit: -290
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9738
Precision: 0.6
Recall: 0.7143
F0.5-score: 0.6198
Profit: -205

Эпоха 13 | Train Loss: 0.0041 | Val ROC-AUC: 0.9738 | Val Profit: -205
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9714
Precision: 0.619
Recall: 0.619
F0.5-score: 0.619
Profit: -175

Эпоха 14 | Train Loss: 0.0031 | Val ROC-AUC: 0.9714 | Val Profit: -175
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9486
Precision: 0.4
Recall: 0.0952
F0.5-score: 0.2439
Profit: -160

Эпоха 15 | Train Loss: 0.0041 | Val ROC-AUC: 0.9486 | Val Profit: -160
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9721
Precision: 0.6316
Recall: 0.5714
F0.5-score: 0.6186
Profit: -160

Эпоха 16 | Train Loss: 0.0030 | Val ROC-AUC: 0.9721 | Val Profit: -160
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9687
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 17 | Train Loss: 0.0034 | Val ROC-AUC: 0.9687 | Val Profit: -180
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9407
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 18 | Train Loss: 0.0023 | Val ROC-AUC: 0.9407 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.8735
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 19 | Train Loss: 0.0013 | Val ROC-AUC: 0.8735 | Val Profit: -135
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9598
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 20 | Train Loss: 0.0006 | Val ROC-AUC: 0.9598 | Val Profit: -180
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.954
Precision: 0.5
Recall: 0.1905
F0.5-score: 0.3774
Profit: -165

Эпоха 21 | Train Loss: 0.0004 | Val ROC-AUC: 0.9540 | Val Profit: -165
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9431
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 22 | Train Loss: 0.0002 | Val ROC-AUC: 0.9431 | Val Profit: -150
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9399
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 23 | Train Loss: 0.0002 | Val ROC-AUC: 0.9399 | Val Profit: -150
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9367
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 24 | Train Loss: 0.0002 | Val ROC-AUC: 0.9367 | Val Profit: -150
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9352
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 25 | Train Loss: 0.0001 | Val ROC-AUC: 0.9352 | Val Profit: -150
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9335
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 26 | Train Loss: 0.0001 | Val ROC-AUC: 0.9335 | Val Profit: -150
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9316
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 27 | Train Loss: 0.0001 | Val ROC-AUC: 0.9316 | Val Profit: -150
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9315
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 28 | Train Loss: 0.0001 | Val ROC-AUC: 0.9315 | Val Profit: -150
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9319
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 29 | Train Loss: 0.0001 | Val ROC-AUC: 0.9319 | Val Profit: -150
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9309
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 30 | Train Loss: 0.0001 | Val ROC-AUC: 0.9309 | Val Profit: -150

Лучшая эпоха для model_9_Focal_loss: 10
Лучший ROC-AUC: 0.9743796109993292
val
ROC-AUC: 0.9744
Precision: 0.5429
Recall: 0.9048
F0.5-score: 0.5901
Profit: -315

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.914
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0462 | Val ROC-AUC: 0.9140 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9596
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0237 | Val ROC-AUC: 0.9596 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9594
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0173 | Val ROC-AUC: 0.9594 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0156 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9624
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 5 | Train Loss: 0.0123 | Val ROC-AUC: 0.9624 | Val Profit: -175
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9577
Precision: 0.4286
Recall: 0.7143
F0.5-score: 0.4658
Profit: -455

Эпоха 6 | Train Loss: 0.0128 | Val ROC-AUC: 0.9577 | Val Profit: -455
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9592
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 7 | Train Loss: 0.0121 | Val ROC-AUC: 0.9592 | Val Profit: -125
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.951
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 8 | Train Loss: 0.0111 | Val ROC-AUC: 0.9510 | Val Profit: -205
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9663
Precision: 0.7778
Recall: 0.3333
F0.5-score: 0.614
Profit: -85

Эпоха 9 | Train Loss: 0.0102 | Val ROC-AUC: 0.9663 | Val Profit: -85
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9753
Precision: 0.7222
Recall: 0.619
F0.5-score: 0.6989
Profit: -100

Эпоха 10 | Train Loss: 0.0081 | Val ROC-AUC: 0.9753 | Val Profit: -100
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9645
Precision: 0.7692
Recall: 0.4762
F0.5-score: 0.6849
Profit: -80

Эпоха 11 | Train Loss: 0.0061 | Val ROC-AUC: 0.9645 | Val Profit: -80
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9454
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 12 | Train Loss: 0.0056 | Val ROC-AUC: 0.9454 | Val Profit: -205
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9466
Precision: 0.3846
Recall: 0.2381
F0.5-score: 0.3425
Profit: -255

Эпоха 13 | Train Loss: 0.0070 | Val ROC-AUC: 0.9466 | Val Profit: -255
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9245
Precision: 0.4375
Recall: 0.6667
F0.5-score: 0.4698
Profit: -415

Эпоха 14 | Train Loss: 0.0067 | Val ROC-AUC: 0.9245 | Val Profit: -415
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.965
Precision: 0.5
Recall: 0.5714
F0.5-score: 0.5128
Profit: -285

Эпоха 15 | Train Loss: 0.0085 | Val ROC-AUC: 0.9650 | Val Profit: -285
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9651
Precision: 0.6842
Recall: 0.619
F0.5-score: 0.6701
Profit: -125

Эпоха 16 | Train Loss: 0.0086 | Val ROC-AUC: 0.9651 | Val Profit: -125
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9736
Precision: 0.6875
Recall: 0.5238
F0.5-score: 0.6471
Profit: -120

Эпоха 17 | Train Loss: 0.0065 | Val ROC-AUC: 0.9736 | Val Profit: -120
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.971
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 18 | Train Loss: 0.0048 | Val ROC-AUC: 0.9710 | Val Profit: -145
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9674
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 19 | Train Loss: 0.0033 | Val ROC-AUC: 0.9674 | Val Profit: -145
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9645
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 20 | Train Loss: 0.0025 | Val ROC-AUC: 0.9645 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9595
Precision: 0.5
Recall: 0.0476
F0.5-score: 0.1724
Profit: -120

Эпоха 21 | Train Loss: 0.0019 | Val ROC-AUC: 0.9595 | Val Profit: -120
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9418
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 22 | Train Loss: 0.0017 | Val ROC-AUC: 0.9418 | Val Profit: -150
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9408
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 23 | Train Loss: 0.0027 | Val ROC-AUC: 0.9408 | Val Profit: -125
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9709
Precision: 0.4318
Recall: 0.9048
F0.5-score: 0.4822
Profit: -540

Эпоха 24 | Train Loss: 0.0041 | Val ROC-AUC: 0.9709 | Val Profit: -540
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9693
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 25 | Train Loss: 0.0069 | Val ROC-AUC: 0.9693 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9791
Precision: 0.8
Recall: 0.5714
F0.5-score: 0.7407
Profit: -60

Эпоха 26 | Train Loss: 0.0043 | Val ROC-AUC: 0.9791 | Val Profit: -60
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9618
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 27 | Train Loss: 0.0033 | Val ROC-AUC: 0.9618 | Val Profit: -180
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9658
Precision: 0.6667
Recall: 0.381
F0.5-score: 0.5797
Profit: -125

Эпоха 28 | Train Loss: 0.0028 | Val ROC-AUC: 0.9658 | Val Profit: -125
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9376
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 29 | Train Loss: 0.0018 | Val ROC-AUC: 0.9376 | Val Profit: -105
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9329
Precision: 0.5
Recall: 0.1429
F0.5-score: 0.3333
Profit: -150

Эпоха 30 | Train Loss: 0.0012 | Val ROC-AUC: 0.9329 | Val Profit: -150

Лучшая эпоха для model_9_Focal_loss: 26
Лучший ROC-AUC: 0.9790744466800805
val
ROC-AUC: 0.9791
Precision: 0.8
Recall: 0.5714
F0.5-score: 0.7407
Profit: -60

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8604
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0472 | Val ROC-AUC: 0.8604 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9488
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0252 | Val ROC-AUC: 0.9488 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9307
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0184 | Val ROC-AUC: 0.9307 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.8865
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0197 | Val ROC-AUC: 0.8865 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9422
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0162 | Val ROC-AUC: 0.9422 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9539
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0146 | Val ROC-AUC: 0.9539 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9654
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0132 | Val ROC-AUC: 0.9654 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9341
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0150 | Val ROC-AUC: 0.9341 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.932
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0186 | Val ROC-AUC: 0.9320 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9459
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0170 | Val ROC-AUC: 0.9459 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9529
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 11 | Train Loss: 0.0136 | Val ROC-AUC: 0.9529 | Val Profit: -105
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9696
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 12 | Train Loss: 0.0129 | Val ROC-AUC: 0.9696 | Val Profit: -105
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9261
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 13 | Train Loss: 0.0115 | Val ROC-AUC: 0.9261 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9747
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 14 | Train Loss: 0.0119 | Val ROC-AUC: 0.9747 | Val Profit: -105
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9708
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 15 | Train Loss: 0.0115 | Val ROC-AUC: 0.9708 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9742
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 16 | Train Loss: 0.0109 | Val ROC-AUC: 0.9742 | Val Profit: -105
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9776
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 17 | Train Loss: 0.0110 | Val ROC-AUC: 0.9776 | Val Profit: -105
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9785
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 18 | Train Loss: 0.0086 | Val ROC-AUC: 0.9785 | Val Profit: -105
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9792
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 19 | Train Loss: 0.0084 | Val ROC-AUC: 0.9792 | Val Profit: -105
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9716
Precision: 0.6364
Recall: 0.6667
F0.5-score: 0.6422
Profit: -165

Эпоха 20 | Train Loss: 0.0084 | Val ROC-AUC: 0.9716 | Val Profit: -165
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9324
Precision: 0.28
Recall: 1.0
F0.5-score: 0.3271
Profit: -1245

Эпоха 21 | Train Loss: 0.0122 | Val ROC-AUC: 0.9324 | Val Profit: -1245
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.971
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 22 | Train Loss: 0.0109 | Val ROC-AUC: 0.9710 | Val Profit: -125
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9792
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 23 | Train Loss: 0.0088 | Val ROC-AUC: 0.9792 | Val Profit: -105
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9759
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0077 | Val ROC-AUC: 0.9759 | Val Profit: -105
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9796
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 25 | Train Loss: 0.0071 | Val ROC-AUC: 0.9796 | Val Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9765
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 26 | Train Loss: 0.0067 | Val ROC-AUC: 0.9765 | Val Profit: -105
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9561
Precision: 0.4545
Recall: 0.4762
F0.5-score: 0.4587
Profit: -305

Эпоха 27 | Train Loss: 0.0088 | Val ROC-AUC: 0.9561 | Val Profit: -305
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9752
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 28 | Train Loss: 0.0097 | Val ROC-AUC: 0.9752 | Val Profit: -105
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9689
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -130

Эпоха 29 | Train Loss: 0.0084 | Val ROC-AUC: 0.9689 | Val Profit: -130
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9815
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 30 | Train Loss: 0.0079 | Val ROC-AUC: 0.9815 | Val Profit: -80

Лучшая эпоха для model_9_Focal_loss: 30
Лучший ROC-AUC: 0.9814889336016097
val
ROC-AUC: 0.9815
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9002
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0490 | Val ROC-AUC: 0.9002 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9353
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0245 | Val ROC-AUC: 0.9353 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9493
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0173 | Val ROC-AUC: 0.9493 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9341
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0142 | Val ROC-AUC: 0.9341 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9587
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0119 | Val ROC-AUC: 0.9587 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9517
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 6 | Train Loss: 0.0098 | Val ROC-AUC: 0.9517 | Val Profit: -95
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9549
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 7 | Train Loss: 0.0085 | Val ROC-AUC: 0.9549 | Val Profit: -225
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9512
Precision: 0.4667
Recall: 0.3333
F0.5-score: 0.4321
Profit: -235

Эпоха 8 | Train Loss: 0.0073 | Val ROC-AUC: 0.9512 | Val Profit: -235
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9455
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 9 | Train Loss: 0.0064 | Val ROC-AUC: 0.9455 | Val Profit: -255
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.833
Precision: 0.25
Recall: 0.0476
F0.5-score: 0.1351
Profit: -170

Эпоха 10 | Train Loss: 0.0058 | Val ROC-AUC: 0.8330 | Val Profit: -170
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9599
Precision: 1.0
Recall: 0.1905
F0.5-score: 0.5405
Profit: -65

Эпоха 11 | Train Loss: 0.0039 | Val ROC-AUC: 0.9599 | Val Profit: -65
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9595
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 12 | Train Loss: 0.0036 | Val ROC-AUC: 0.9595 | Val Profit: -395
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9631
Precision: 0.7143
Recall: 0.4762
F0.5-score: 0.6494
Profit: -105

Эпоха 13 | Train Loss: 0.0045 | Val ROC-AUC: 0.9631 | Val Profit: -105
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9553
Precision: 0.6667
Recall: 0.4762
F0.5-score: 0.6173
Profit: -130

Эпоха 14 | Train Loss: 0.0039 | Val ROC-AUC: 0.9553 | Val Profit: -130
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9642
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 15 | Train Loss: 0.0036 | Val ROC-AUC: 0.9642 | Val Profit: -95
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9592
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 16 | Train Loss: 0.0017 | Val ROC-AUC: 0.9592 | Val Profit: -100
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9583
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 17 | Train Loss: 0.0011 | Val ROC-AUC: 0.9583 | Val Profit: -95
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9458
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 18 | Train Loss: 0.0009 | Val ROC-AUC: 0.9458 | Val Profit: -100
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9493
Precision: 0.75
Recall: 0.1429
F0.5-score: 0.4054
Profit: -100

Эпоха 19 | Train Loss: 0.0006 | Val ROC-AUC: 0.9493 | Val Profit: -100
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9505
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 20 | Train Loss: 0.0006 | Val ROC-AUC: 0.9505 | Val Profit: -115
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9551
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 21 | Train Loss: 0.0005 | Val ROC-AUC: 0.9551 | Val Profit: -95
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.8903
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 22 | Train Loss: 0.0008 | Val ROC-AUC: 0.8903 | Val Profit: -75
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.8651
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 23 | Train Loss: 0.0053 | Val ROC-AUC: 0.8651 | Val Profit: -95
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9497
Precision: 0.8
Recall: 0.1905
F0.5-score: 0.4878
Profit: -90

Эпоха 24 | Train Loss: 0.0052 | Val ROC-AUC: 0.9497 | Val Profit: -90
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9579
Precision: 0.5172
Recall: 0.7143
F0.5-score: 0.5474
Profit: -305

Эпоха 25 | Train Loss: 0.0071 | Val ROC-AUC: 0.9579 | Val Profit: -305
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9473
Precision: 0.75
Recall: 0.2857
F0.5-score: 0.566
Profit: -95

Эпоха 26 | Train Loss: 0.0064 | Val ROC-AUC: 0.9473 | Val Profit: -95
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9744
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 27 | Train Loss: 0.0027 | Val ROC-AUC: 0.9744 | Val Profit: -95
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9744
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 28 | Train Loss: 0.0013 | Val ROC-AUC: 0.9744 | Val Profit: -75
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9716
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 29 | Train Loss: 0.0009 | Val ROC-AUC: 0.9716 | Val Profit: -95
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9713
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0006 | Val ROC-AUC: 0.9713 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9743796109993292
val
ROC-AUC: 0.9744
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8942
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0486 | Val ROC-AUC: 0.8942 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9292
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0247 | Val ROC-AUC: 0.9292 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9484
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0180 | Val ROC-AUC: 0.9484 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9541
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0142 | Val ROC-AUC: 0.9541 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9266
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0119 | Val ROC-AUC: 0.9266 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9548
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 6 | Train Loss: 0.0105 | Val ROC-AUC: 0.9548 | Val Profit: -105
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9421
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0101 | Val ROC-AUC: 0.9421 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9516
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 8 | Train Loss: 0.0099 | Val ROC-AUC: 0.9516 | Val Profit: -175
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9614
Precision: 0.4412
Recall: 0.7143
F0.5-score: 0.4777
Profit: -430

Эпоха 9 | Train Loss: 0.0089 | Val ROC-AUC: 0.9614 | Val Profit: -430
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9266
Precision: 0.3889
Recall: 0.3333
F0.5-score: 0.3763
Profit: -310

Эпоха 10 | Train Loss: 0.0083 | Val ROC-AUC: 0.9266 | Val Profit: -310
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9579
Precision: 0.5294
Recall: 0.4286
F0.5-score: 0.5056
Profit: -215

Эпоха 11 | Train Loss: 0.0068 | Val ROC-AUC: 0.9579 | Val Profit: -215
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9252
Precision: 0.52
Recall: 0.619
F0.5-score: 0.5372
Profit: -275

Эпоха 12 | Train Loss: 0.0056 | Val ROC-AUC: 0.9252 | Val Profit: -275
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9508
Precision: 0.4583
Recall: 0.5238
F0.5-score: 0.4701
Profit: -320

Эпоха 13 | Train Loss: 0.0056 | Val ROC-AUC: 0.9508 | Val Profit: -320
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.8313
Precision: 0.4375
Recall: 0.3333
F0.5-score: 0.4118
Profit: -260

Эпоха 14 | Train Loss: 0.0056 | Val ROC-AUC: 0.8313 | Val Profit: -260
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9594
Precision: 0.5
Recall: 0.381
F0.5-score: 0.4706
Profit: -225

Эпоха 15 | Train Loss: 0.0047 | Val ROC-AUC: 0.9594 | Val Profit: -225
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9392
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 16 | Train Loss: 0.0031 | Val ROC-AUC: 0.9392 | Val Profit: -80
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9222
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 17 | Train Loss: 0.0014 | Val ROC-AUC: 0.9222 | Val Profit: -115
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.8381
Precision: 0.45
Recall: 0.4286
F0.5-score: 0.4455
Profit: -290

Эпоха 18 | Train Loss: 0.0029 | Val ROC-AUC: 0.8381 | Val Profit: -290
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.961
Precision: 0.4286
Recall: 0.8571
F0.5-score: 0.4762
Profit: -525

Эпоха 19 | Train Loss: 0.0124 | Val ROC-AUC: 0.9610 | Val Profit: -525
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9129
Precision: 0.5556
Recall: 0.2381
F0.5-score: 0.4386
Profit: -155

Эпоха 20 | Train Loss: 0.0075 | Val ROC-AUC: 0.9129 | Val Profit: -155
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9341
Precision: 0.5
Recall: 0.2381
F0.5-score: 0.4098
Profit: -180

Эпоха 21 | Train Loss: 0.0040 | Val ROC-AUC: 0.9341 | Val Profit: -180
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9387
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 22 | Train Loss: 0.0021 | Val ROC-AUC: 0.9387 | Val Profit: -75
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9422
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 23 | Train Loss: 0.0011 | Val ROC-AUC: 0.9422 | Val Profit: -80
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9296
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 24 | Train Loss: 0.0008 | Val ROC-AUC: 0.9296 | Val Profit: -80
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9298
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 25 | Train Loss: 0.0006 | Val ROC-AUC: 0.9298 | Val Profit: -80
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9289
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 26 | Train Loss: 0.0006 | Val ROC-AUC: 0.9289 | Val Profit: -80
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9281
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 27 | Train Loss: 0.0005 | Val ROC-AUC: 0.9281 | Val Profit: -80
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9272
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 28 | Train Loss: 0.0005 | Val ROC-AUC: 0.9272 | Val Profit: -80
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9264
Precision: 0.8333
Recall: 0.2381
F0.5-score: 0.5556
Profit: -80

Эпоха 29 | Train Loss: 0.0004 | Val ROC-AUC: 0.9264 | Val Profit: -80
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9254
Precision: 1.0
Recall: 0.2381
F0.5-score: 0.6098
Profit: -55

Эпоха 30 | Train Loss: 0.0004 | Val ROC-AUC: 0.9254 | Val Profit: -55

Лучшая эпоха для model_9_Focal_loss: 9
Лучший ROC-AUC: 0.9613682092555331
val
ROC-AUC: 0.9614
Precision: 0.4412
Recall: 0.7143
F0.5-score: 0.4777
Profit: -430

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.8909
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0486 | Val ROC-AUC: 0.8909 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9362
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 2 | Train Loss: 0.0256 | Val ROC-AUC: 0.9362 | Val Profit: -105
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9297
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 3 | Train Loss: 0.0176 | Val ROC-AUC: 0.9297 | Val Profit: -105
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9465
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 4 | Train Loss: 0.0177 | Val ROC-AUC: 0.9465 | Val Profit: -105
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.9526
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 5 | Train Loss: 0.0148 | Val ROC-AUC: 0.9526 | Val Profit: -105
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.9606
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 6 | Train Loss: 0.0146 | Val ROC-AUC: 0.9606 | Val Profit: -115
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9595
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 7 | Train Loss: 0.0145 | Val ROC-AUC: 0.9595 | Val Profit: -105
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9704
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 8 | Train Loss: 0.0116 | Val ROC-AUC: 0.9704 | Val Profit: -105
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.971
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 9 | Train Loss: 0.0096 | Val ROC-AUC: 0.9710 | Val Profit: -105
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9673
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 10 | Train Loss: 0.0080 | Val ROC-AUC: 0.9673 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.9712
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 11 | Train Loss: 0.0072 | Val ROC-AUC: 0.9712 | Val Profit: -110
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9714
Precision: 0.5789
Recall: 0.5238
F0.5-score: 0.567
Profit: -195

Эпоха 12 | Train Loss: 0.0079 | Val ROC-AUC: 0.9714 | Val Profit: -195
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9712
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 13 | Train Loss: 0.0121 | Val ROC-AUC: 0.9712 | Val Profit: -210
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9627
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 14 | Train Loss: 0.0103 | Val ROC-AUC: 0.9627 | Val Profit: -175
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.8703
Precision: 0.3333
Recall: 0.0476
F0.5-score: 0.1515
Profit: -145

Эпоха 15 | Train Loss: 0.0084 | Val ROC-AUC: 0.8703 | Val Profit: -145
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9199
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 16 | Train Loss: 0.0069 | Val ROC-AUC: 0.9199 | Val Profit: -155
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.8834
Precision: 0.5625
Recall: 0.4286
F0.5-score: 0.5294
Profit: -190

Эпоха 17 | Train Loss: 0.0064 | Val ROC-AUC: 0.8834 | Val Profit: -190
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9746
Precision: 0.6364
Recall: 0.3333
F0.5-score: 0.5385
Profit: -135

Эпоха 18 | Train Loss: 0.0078 | Val ROC-AUC: 0.9746 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9745
Precision: 0.6
Recall: 0.1429
F0.5-score: 0.3659
Profit: -125

Эпоха 19 | Train Loss: 0.0067 | Val ROC-AUC: 0.9745 | Val Profit: -125
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9678
Precision: 0.4706
Recall: 0.7619
F0.5-score: 0.5096
Profit: -395

Эпоха 20 | Train Loss: 0.0054 | Val ROC-AUC: 0.9678 | Val Profit: -395
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9581
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 21 | Train Loss: 0.0089 | Val ROC-AUC: 0.9581 | Val Profit: -135
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9659
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 22 | Train Loss: 0.0082 | Val ROC-AUC: 0.9659 | Val Profit: -210
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.9737
Precision: 1.0
Recall: 0.1429
F0.5-score: 0.4545
Profit: -75

Эпоха 23 | Train Loss: 0.0060 | Val ROC-AUC: 0.9737 | Val Profit: -75
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9419
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 24 | Train Loss: 0.0046 | Val ROC-AUC: 0.9419 | Val Profit: -105

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9337
Precision: 0.7143
Recall: 0.2381
F0.5-score: 0.5102
Profit: -105

Эпоха 25 | Train Loss: 0.0033 | Val ROC-AUC: 0.9337 | Val Profit: -105
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.8873
Precision: 1.0
Recall: 0.0952
F0.5-score: 0.3448
Profit: -85

Эпоха 26 | Train Loss: 0.0033 | Val ROC-AUC: 0.8873 | Val Profit: -85
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9769
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

Эпоха 27 | Train Loss: 0.0038 | Val ROC-AUC: 0.9769 | Val Profit: -230
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9636
Precision: 0.4167
Recall: 0.9524
F0.5-score: 0.4695
Profit: -605

Эпоха 28 | Train Loss: 0.0077 | Val ROC-AUC: 0.9636 | Val Profit: -605
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9737
Precision: 0.4634
Recall: 0.9048
F0.5-score: 0.5135
Profit: -465

Эпоха 29 | Train Loss: 0.0099 | Val ROC-AUC: 0.9737 | Val Profit: -465
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9752
Precision: 1.0
Recall: 0.0476
F0.5-score: 0.2
Profit: -95

Эпоха 30 | Train Loss: 0.0090 | Val ROC-AUC: 0.9752 | Val Profit: -95

Лучшая эпоха для model_9_Focal_loss: 27
Лучший ROC-AUC: 0.9769282360831657
val
ROC-AUC: 0.9769
Precision: 0.5769
Recall: 0.7143
F0.5-score: 0.6
Profit: -230

In [146]:
best = max(results, key=lambda r: r["profit"])
print("Лучшие гиперпараметры:", best)

Лучшие гиперпараметры: {'lr': 0.005, 'gamma': 2.0, 'alpha': 0.99, 'dropout': 0.0, 'weight_decay': 0.0, 'profit': np.int64(-10), 'roc_auc': 0.9880617035546613}

In [147]:
LR = best["lr"]
GAMMA = best["gamma"]
ALPHA = best["alpha"]
DROPOUT_COEF = best["dropout"]
WEIGHT_DECAY = best["weight_decay"]

In [148]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED) 


model_9 = nn.Sequential(
    nn.Linear(9, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(32, 16),
    nn.BatchNorm1d(16),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(16, 8),
    nn.BatchNorm1d(8),
    nn.ReLU(),
    nn.Dropout(DROPOUT_COEF),

    nn.Linear(8, 1)
)

loss_fn = FocalLoss(alpha=ALPHA, gamma=GAMMA)
optimizer = torch.optim.Adam(model_9.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

config = {
    "model": "MLP_focal_loss",
    "optimizer": str(optimizer.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "alpha": ALPHA,
    "gamma": GAMMA,
    "pos_weight": pos_weight,
    "loss": str(loss_fn.__class__.__name__),
    "architecture": str(model_9)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="model_9_focal_loss", config=config)
log_file = new_log_file()

model_9 = train_model(
    model=model_9,
    train_loader=train_loader,
    X_valid=X_val,
    y_valid=y_val,
    loss_fn=loss_fn,
    optimizer=optimizer,
    epochs=EPOCHS,
    threshold=0.5,
    model_name="model_9_Focal_loss"
)


save_results(model_9, "model_9", log_file, run)

run.finish()

/Users/katya/Desktop/Катя/ВШЭ/смадимо/gp-5/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

model_9_Focal_loss | valid epoch 1
ROC-AUC: 0.9249
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -105

Эпоха 1 | Train Loss: 0.0929 | Val ROC-AUC: 0.9249 | Val Profit: -105
model_9_Focal_loss | valid epoch 2
ROC-AUC: 0.9575
Precision: 0.5
Recall: 0.4762
F0.5-score: 0.495
Profit: -255

Эпоха 2 | Train Loss: 0.0445 | Val ROC-AUC: 0.9575 | Val Profit: -255
model_9_Focal_loss | valid epoch 3
ROC-AUC: 0.9549
Precision: 0.4242
Recall: 0.6667
F0.5-score: 0.4575
Profit: -440

Эпоха 3 | Train Loss: 0.0319 | Val ROC-AUC: 0.9549 | Val Profit: -440
model_9_Focal_loss | valid epoch 4
ROC-AUC: 0.9581
Precision: 0.48
Recall: 0.5714
F0.5-score: 0.4959
Profit: -310

Эпоха 4 | Train Loss: 0.0254 | Val ROC-AUC: 0.9581 | Val Profit: -310
model_9_Focal_loss | valid epoch 5
ROC-AUC: 0.969
Precision: 0.4737
Recall: 0.8571
F0.5-score: 0.5202
Profit: -425

Эпоха 5 | Train Loss: 0.0229 | Val ROC-AUC: 0.9690 | Val Profit: -425
model_9_Focal_loss | valid epoch 6
ROC-AUC: 0.971
Precision: 0.5652
Recall: 0.619
F0.5-score: 0.5752
Profit: -225

Эпоха 6 | Train Loss: 0.0214 | Val ROC-AUC: 0.9710 | Val Profit: -225
model_9_Focal_loss | valid epoch 7
ROC-AUC: 0.9718
Precision: 0.5909
Recall: 0.619
F0.5-score: 0.5963
Profit: -200

Эпоха 7 | Train Loss: 0.0208 | Val ROC-AUC: 0.9718 | Val Profit: -200
model_9_Focal_loss | valid epoch 8
ROC-AUC: 0.9765
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 8 | Train Loss: 0.0178 | Val ROC-AUC: 0.9765 | Val Profit: -120
model_9_Focal_loss | valid epoch 9
ROC-AUC: 0.9751
Precision: 0.5714
Recall: 0.5714
F0.5-score: 0.5714
Profit: -210

Эпоха 9 | Train Loss: 0.0139 | Val ROC-AUC: 0.9751 | Val Profit: -210
model_9_Focal_loss | valid epoch 10
ROC-AUC: 0.9623
Precision: 0.4545
Recall: 0.7143
F0.5-score: 0.4902
Profit: -405

Эпоха 10 | Train Loss: 0.0185 | Val ROC-AUC: 0.9623 | Val Profit: -405
model_9_Focal_loss | valid epoch 11
ROC-AUC: 0.974
Precision: 0.6471
Recall: 0.5238
F0.5-score: 0.618
Profit: -145

Эпоха 11 | Train Loss: 0.0190 | Val ROC-AUC: 0.9740 | Val Profit: -145
model_9_Focal_loss | valid epoch 12
ROC-AUC: 0.9575
Precision: 0.5556
Recall: 0.4762
F0.5-score: 0.5376
Profit: -205

Эпоха 12 | Train Loss: 0.0129 | Val ROC-AUC: 0.9575 | Val Profit: -205
model_9_Focal_loss | valid epoch 13
ROC-AUC: 0.9729
Precision: 0.7
Recall: 0.3333
F0.5-score: 0.5738
Profit: -110

Эпоха 13 | Train Loss: 0.0109 | Val ROC-AUC: 0.9729 | Val Profit: -110
model_9_Focal_loss | valid epoch 14
ROC-AUC: 0.9811
Precision: 0.6522
Recall: 0.7143
F0.5-score: 0.6637
Profit: -155

Эпоха 14 | Train Loss: 0.0115 | Val ROC-AUC: 0.9811 | Val Profit: -155
model_9_Focal_loss | valid epoch 15
ROC-AUC: 0.9881
Precision: 0.85
Recall: 0.8095
F0.5-score: 0.8416
Profit: -10

Эпоха 15 | Train Loss: 0.0133 | Val ROC-AUC: 0.9881 | Val Profit: -10
model_9_Focal_loss | valid epoch 16
ROC-AUC: 0.9708
Precision: 0.5385
Recall: 0.3333
F0.5-score: 0.4795
Profit: -185

Эпоха 16 | Train Loss: 0.0141 | Val ROC-AUC: 0.9708 | Val Profit: -185
model_9_Focal_loss | valid epoch 17
ROC-AUC: 0.9749
Precision: 0.4286
Recall: 0.1429
F0.5-score: 0.3061
Profit: -175

Эпоха 17 | Train Loss: 0.0122 | Val ROC-AUC: 0.9749 | Val Profit: -175
model_9_Focal_loss | valid epoch 18
ROC-AUC: 0.9529
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 18 | Train Loss: 0.0084 | Val ROC-AUC: 0.9529 | Val Profit: -135
model_9_Focal_loss | valid epoch 19
ROC-AUC: 0.9602
Precision: 0.44
Recall: 0.5238
F0.5-score: 0.4545
Profit: -345

Эпоха 19 | Train Loss: 0.0109 | Val ROC-AUC: 0.9602 | Val Profit: -345
model_9_Focal_loss | valid epoch 20
ROC-AUC: 0.9736
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 20 | Train Loss: 0.0156 | Val ROC-AUC: 0.9736 | Val Profit: -120
model_9_Focal_loss | valid epoch 21
ROC-AUC: 0.9789
Precision: 0.6667
Recall: 0.0952
F0.5-score: 0.303
Profit: -110

Эпоха 21 | Train Loss: 0.0100 | Val ROC-AUC: 0.9789 | Val Profit: -110
model_9_Focal_loss | valid epoch 22
ROC-AUC: 0.9738
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 22 | Train Loss: 0.0069 | Val ROC-AUC: 0.9738 | Val Profit: -120
model_9_Focal_loss | valid epoch 23
ROC-AUC: 0.945
Precision: 0.6667
Recall: 0.2857
F0.5-score: 0.5263
Profit: -120

Эпоха 23 | Train Loss: 0.0061 | Val ROC-AUC: 0.9450 | Val Profit: -120
model_9_Focal_loss | valid epoch 24
ROC-AUC: 0.9746
Precision: 0.6429
Recall: 0.4286
F0.5-score: 0.5844
Profit: -140

Эпоха 24 | Train Loss: 0.0060 | Val ROC-AUC: 0.9746 | Val Profit: -140
model_9_Focal_loss | valid epoch 25
ROC-AUC: 0.9294
Precision: 0.7333
Recall: 0.5238
F0.5-score: 0.679
Profit: -95

Эпоха 25 | Train Loss: 0.0070 | Val ROC-AUC: 0.9294 | Val Profit: -95
model_9_Focal_loss | valid epoch 26
ROC-AUC: 0.9524
Precision: 0.625
Recall: 0.4762
F0.5-score: 0.5882
Profit: -155

Эпоха 26 | Train Loss: 0.0090 | Val ROC-AUC: 0.9524 | Val Profit: -155
model_9_Focal_loss | valid epoch 27
ROC-AUC: 0.9733
Precision: 0.6923
Recall: 0.4286
F0.5-score: 0.6164
Profit: -115

Эпоха 27 | Train Loss: 0.0113 | Val ROC-AUC: 0.9733 | Val Profit: -115
model_9_Focal_loss | valid epoch 28
ROC-AUC: 0.9611
Precision: 0.0
Recall: 0.0
F0.5-score: 0.0
Profit: -155

Эпоха 28 | Train Loss: 0.0081 | Val ROC-AUC: 0.9611 | Val Profit: -155
model_9_Focal_loss | valid epoch 29
ROC-AUC: 0.9623
Precision: 0.5
Recall: 0.0952
F0.5-score: 0.2703
Profit: -135

Эпоха 29 | Train Loss: 0.0053 | Val ROC-AUC: 0.9623 | Val Profit: -135
model_9_Focal_loss | valid epoch 30
ROC-AUC: 0.9349
Precision: 0.6667
Recall: 0.1905
F0.5-score: 0.4444
Profit: -115

Эпоха 30 | Train Loss: 0.0033 | Val ROC-AUC: 0.9349 | Val Profit: -115

Лучшая эпоха для model_9_Focal_loss: 15
Лучший ROC-AUC: 0.9880617035546613
Train
ROC-AUC: 0.9916
Precision: 0.831
Recall: 0.7108
F0.5-score: 0.8038
Profit: -125

Test
ROC-AUC: 0.9702
Precision: 0.6867
Recall: 0.5698
F0.5-score: 0.6597
Profit: -137610

In [149]:
train_metrics = evaluate_model(model_9, X_train, y_train, threshold=0.5, name="Train")
test_metrics = evaluate_model(model_9, X_test, y_test, threshold=0.5, name="Test")

Train
ROC-AUC: 0.9916
Precision: 0.831
Recall: 0.7108
F0.5-score: 0.8038
Profit: -125

Test
ROC-AUC: 0.9702
Precision: 0.6867
Recall: 0.5698
F0.5-score: 0.6597
Profit: -137610

В этом эксперименте пробовали ментять функцию активации, но это особо не помогло. Использовал FocalLoss. И перебирали параметры

На валидации profit отличный, но на тесте хуже бейзлайна. Такой большой разрыв говорит о переобучении

# ансамбль ПОКА НЕ ТРОГАЛ

In [ ]:
import numpy as np

In [ ]:
def build_model():
    return nn.Sequential(
        nn.Linear(9, 64),
        nn.BatchNorm1d(64),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(64, 32),
        nn.BatchNorm1d(32),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(32, 1),
        )

In [ ]:
EPOCHS = 120
LR = 0.001
WEIGHT_DECAY = 1e-4
N_ENSEMBLE = 5

net = build_model()
opt = torch.optim.Adam(net.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

In [ ]:
loss_fn2 = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

In [ ]:
config = {
    "model": "Ensemble",
    "optimizer": str(opt.__class__.__name__),
    "task": "fraud_detection",
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "lr": LR,
    "weight_decay": WEIGHT_DECAY,
    "pos_weight": pos_weight,
    "loss": str(loss_fn2.__class__.__name__),
    "n_ensemble": N_ENSEMBLE,
    "architecture": str(net)
}

run = wandb.init(project=WANDB_PROJECT, entity=WANDB_ENTITY, name="ensemble", config=config)

In [ ]:
test_probs = []
logging.info("Запустили обучение моделей ансамбля")

np.random.seed(42)
seeds = np.random.randint(1, 525252, size=N_ENSEMBLE)
ensemble = []
for i in range(N_ENSEMBLE):
    seed = seeds[i]
    torch.manual_seed(seed)
    net = build_model()
    opt = torch.optim.Adam(net.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    logging.info(f"Запустили обучение модели {i+1}. Сид: {seed}")


    net.train()
    for epoch in range(1, EPOCHS + 1):
        epoch_loss = 0
        for xb, yb in train_loader:
            opt.zero_grad()
            loss = loss_fn2(net(xb), yb)
            loss.backward()
            epoch_loss += loss.item()
            opt.step()
        
        logging.info(f"эпоха: {epoch}, loss:  {round(epoch_loss, 4)}")
        wandb.log({"epoch": epoch, f"ensemble/{i}/train_loss": epoch_loss})
    
    ensemble.append(net.state_dict())

    net.eval()
    with torch.no_grad():
        test_probs.append(torch.sigmoid(net(X_test)).numpy())

    logging.info(f"Сеть {i} обучена")
    print("сеть", i, "обучена")

probs2 = np.mean(test_probs, axis=0)

In [ ]:
auc_score = roc_auc_score(y_true, probs2)
logging.info(f"На тесте ROC_AUC: {auc_score}")
auc_score

In [ ]:
pre_score = average_precision_score(y_true, probs2)
logging.info(f"На тесте Precision: {pre_score}")
pre_score

In [ ]:
results = wandb.Table(columns=['model', 'test/avg_roc_auc', 'test/avg_precision'])
results.add_data("ensemble", auc_score, pre_score)
wandb.log({"results": results})

In [ ]:
import pickle

pickle.dump(ensemble, open("models/model_fraud_ensemble.pkl", 'wb'))
logging.info("Сохранили веса моделей ансамбля в папку models")

In [ ]:
artifact = wandb.Artifact(name="model_fraud_ensemble.pkl", type="model", description="Ансамбль моделей для определения Фрода")

artifact.add_file("models/model_fraud_ensemble.pkl")
artifact.add_file(log_file)
run.log_artifact(artifact)

In [ ]:
run.finish()

In [36]:
wandb.finish()

In [608]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_auc_score, confusion_matrix
import numpy as np

k_values = [3, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15]

best_k = None
best_roc_auc = -1
best_knn = None

X_train_np = X_train.numpy()
y_train_np = y_train.numpy().ravel()

X_val_np = X_val.numpy()
y_val_np = y_val.numpy().ravel()

X_test_np = X_test.numpy()
y_test_np = y_test.numpy().ravel()

for k in k_values:
    knn = KNeighborsClassifier(
        n_neighbors=k,
        weights="distance"
    )

    knn.fit(X_train_np, y_train_np)

    val_probs = knn.predict_proba(X_val_np)[:, 1]
    val_roc_auc = roc_auc_score(y_val_np, val_probs)

    print(f"k={k} | val ROC-AUC={val_roc_auc:.4f}")

    if val_roc_auc > best_roc_auc:
        best_roc_auc = val_roc_auc
        best_k = k
        best_knn = knn

print("\nЛучший KNN")
print("-" * 30)
print("best k:", best_k)
print("best val ROC-AUC:", round(best_roc_auc, 4))

k=3 | val ROC-AUC=0.7783
k=5 | val ROC-AUC=0.8613
k=7 | val ROC-AUC=0.8891
k=8 | val ROC-AUC=0.9312
k=9 | val ROC-AUC=0.9356
k=10 | val ROC-AUC=0.9371
k=11 | val ROC-AUC=0.9336
k=12 | val ROC-AUC=0.9298
k=13 | val ROC-AUC=0.9272
k=14 | val ROC-AUC=0.9328
k=15 | val ROC-AUC=0.9313

Лучший KNN
------------------------------
best k: 10
best val ROC-AUC: 0.9371

In [609]:
threshold = 0.5

test_probs = best_knn.predict_proba(X_test_np)[:, 1]
test_pred = (test_probs >= threshold).astype(int)

tn, fp, fn, tp = confusion_matrix(y_test_np, test_pred).ravel()

test_profit = tp * 5 - fp * 25 - fn * 5
test_roc_auc = roc_auc_score(y_test_np, test_probs)

print("\nKNN на test")
print("-" * 30)
print("k:", best_k)
print("threshold:", threshold)
print("ROC-AUC:", round(test_roc_auc, 4))
print("Profit:", test_profit)
print("TN, FP, FN, TP:", tn, fp, fn, tp)

KNN на test
------------------------------
k: 10
threshold: 0.5
ROC-AUC: 0.8991
Profit: -130230
TN, FP, FN, TP: 473649 745 23024 703